### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by n1msy** [NEZNAMY/TAB#10]
You're TAB list is already incredible. I barely know any non-paid scoreboard plugins that are high quality. As in they're laggy and such. It would be amazing if you added a scoreboard feature. I know that is not what this plugin is about, let alone the title, but I think it would be really cool to see this for people like me.

**Comment by MrApocalyptic** [comment]
+1

**Comment by NEZNAMY** [comment]
https://www.spigotmc.org/resources/scoreboard.14754/
Could you give this plugin a try and tell if it's good enough or not ?

**Comment by NEZNAMY** [comment]
Testing version available for donators on discord.
