### ISSUE TITLE
Scoreboard disabled by default on a Folia server

### ISSUE THREAD

**Issue by iLemon** [NEZNAMY/TAB#1001]
### Server version

Folia 1.20.1

### TAB version

4.0.3-SNAPSHOT 23eb55a

### Describe the bug

The plugin works fine except when you join, your scoreboard is disabled by default. You have to type `/sb` twice (disable and then enable) for it to appear.

If you do this to make it show, and then relog, the scoreboard is gone again.

### Expected behavior

The scoreboard should display when logging in.

### Steps to reproduce

Step 1: Setup Folia server with TAB and a scoreboard in the config
Step 2: Join server, your scoreboard doesn't show
Step 3: Type /sb, then type /sb again to make it show

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=Emc7sG8wvVA).

**Comment by iLemon** [comment]
Seems to be caused by a papi expansion. Closing this.
