### ISSUE TITLE
Bug with yellow bossbar

### ISSUE THREAD

**Issue by KarteloreMc** [NEZNAMY/TAB#1002]
### Server version

Spigot 1.18,2

### TAB version

3.0.2

### Stack trace

When i make animations to bossbar like
- Yellow 
- Purple
its just show only purple color, i testet with normal minecraft /bossbar command and only yellow color not working

(no error in console)

### Steps to reproduce (if known)

Add yellow color to bossbar animation

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Opening an error report without an error? Share your configuration.
