### ISSUE TITLE
per world scoreboard is not work 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [NEZNAMY/TAB#1003]
### Server version

purpur 1.18.2

### TAB version

4.0.3

### Describe the bug

i use display-condition: '%world%=privatemines' to make per world scoreboard but it not work 
scoreboard config

  scoreboards:
    default:
      title: '%animation:title%'
      lines:
      - '&7         %server_time_dd/MM/y%'
      - ''
      - '&6➢ &lProfile'
      - '&e ◆ &7&l%player_name%'
      - '&e ◆ Money: &7$%vault_eco_balance_formatted%'
      - '&e ◆ Tokens: &7%xprison_tokens_formatted%'
      - '&e ◆ Gems: &7%xprison_gems_formatted%'
      - '&e ◆ Crystals: &7%clcy_crystals_formatted%'
      - '&r'
      - '&6➢ &lInfo'
      - '&e ◆ Prestige: &7%xprison_prestige_id%'
      - '&e ◆ Blocks Mined: &7%xprison_blocks_3%'
      - '&e ◆ &6&lProgress'
      - '&e ◆ %xprison_rank% &6⇨ %xprison_next_rank% &6⛃ &e%xprison_next_rank_cost_formatted%'
      - '&e ◆ %xprison_rankup_progress_bar% %xprison_rankup_progress%'
    privatemine:
      display-condition: '%world%=privatemines'
      title: '%animation:title%'
      lines:
      - '&7         %server_time_dd/MM/y%'
      - ''
      - '&6➢ &lProfile'
      - '&e ◆ &7&l%player_name%'
      - '&e ◆ Money: &7$%vault_eco_balance_formatted%'
      - '&e ◆ Tokens: &7%xprison_tokens_formatted%'
      - '&e ◆ Gems: &7%xprison_gems_formatted%'
      - '&e ◆ Crystals: &7%clcy_crystals_formatted%'
      - '&r'
      - '&6➢ &lInfo'
      - '&e ◆ Prestige: &7%xprison_prestige_id%'
      - '&e ◆ Blocks Mined: &7%xprison_blocks_3%'
      - '&e ◆ &6&lProgress'
      - '&e ◆ %prisonranksx_currentrank_name% &6⇨ %prisonranksx_rankup_name% &6⛃ &e%prisonranksx_rankup_cost_formatted%'
      - '&e ◆ %prisonranksx_rankup_progress% %prisonranksx_rankup_percentage_decimal%'

### Expected behavior

show scoreboard per world 

### Steps to reproduce

just make a per world scoreboard or copy paste my config and check it.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
Caused by incorrect configuration
Check: [https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#chaining-scoreboards](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#chaining-scoreboards)  again.
