### ISSUE TITLE
How to disable the display of the nickname above the head?

### ISSUE THREAD

**Issue by norwaj** [NEZNAMY/TAB#1004]
Hello. I apologize for such a question here, not sure if I'm posting it in the right place.

The plugin sets its own display of the nickname above the head. I looked at the config and groups but did not find how to change it (before that, the nickname was replaced by a variable from PlaceHolderAPI)

Can I change this value without using TabAPI? If this is not possible, then where can I download the TabAPI and what should I put in there?

**Comment by DrWurzeli** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-display-name-from-nickname-plugins
GitHub issues are not for configuration support, please refer to the wiki and if you need additional help, open a ticket on discord.
