### ISSUE TITLE
NameTag still appeared when player died

### ISSUE THREAD

**Issue by cupangafk** [NEZNAMY/TAB#1005]
### Server version

`[19:20:32 INFO]: Current: git-Purpur-2019 (MC: 1.20.1)*`

### TAB version

`[19:20:49 INFO] [TAB]: TAB v4.0.3`

### Describe the bug

one of my player were afk fishing and got shooted by a skeleton and refuse to respawn (because he was afk)

his name is still there 
![image](https://github.com/NEZNAMY/TAB/assets/66926348/73304e63-7cd5-4dd3-a352-df6069d8bbf7)

### Expected behavior

the name should be gone too when the player dead

### Steps to reproduce

- play (2 player or more)
- dead (one of the player)
- refuse to respawn (the one who dead)
- wait a while (maybe ?)

### Additional info

by the time i'm writing this
its been 1 hour since his death and i already rejoined like 3 times 

he is cracked player but i think that doesn't matter

server setup is using waterfall proxy and 1 purpur server 

the tab plugin is on the proxy with tab bridge on the purpur server
the tab bridge version is `3.1.2`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by cupangafk** [comment]
> - [X]  I ticked all of the boxes without actually reading them

sorry bout that, i read them actually (like about now :) )

**Comment by NEZNAMY** [comment]
It's been 26 false bug reports since the last actual valid bug report, it's quite refreshing to see one again, I didn't think it would ever happen anymore.

**Comment by cupangafk** [comment]
> it's quite refreshing to see one again, I didn't think it would ever happen anymore.

you sounds like you are happy to see a bug in your software XD


well i can confirm with tab bridge `3.1.3` the name tag working perfectly ( already did the steps, bug is solved )
you can close this now

**Comment by NEZNAMY** [comment]
After 31 false bug reports in a row yes, it's refreshing.
