### ISSUE TITLE
Feature Request: Ability to get total player count of Bungeecord/Velocity proxy

### ISSUE THREAD

**Issue by RealTriassic** [NEZNAMY/TAB#1008]
Before I begin, I am not sure if feature requests are still accepted on this repository, so I apologize if they are not, but I thought this would probably take a couple minutes to add, so here I am.

![image](https://github.com/NEZNAMY/TAB/assets/40073455/c105fa70-af70-433d-89ad-3c9ddbbeee3a)
I believe a placeholder to get the total player count of the entire Bungeecord/Velocity network would be nice.

Currently, the only way to do this is to go ahead and add all of the servers to a server-group in global-playerlist and then use the player list group placeholder, but this isn't ideal as then TAB prints a warning saying that it is discouraged to use layouts and global-playerlist at the same time.

Again, I apologize if this issue causes you any inconvenience, thanks.

**Comment by NEZNAMY** [comment]
%online%?

**Comment by RealTriassic** [comment]
> %online%?

I thought this only gets the player count of the server the player is on

**Comment by NEZNAMY** [comment]
Of the server where plugin is installed. If it's installed on proxy, it shows proxy online count.

**Comment by RealTriassic** [comment]
> Of the server where plugin is installed. If it's installed on proxy, it shows proxy online count.

Oh thank you, that solves it then, apologies for opening a useless issue.
