### ISSUE TITLE
RGB color in brackets displays brackets when closing brackets are not provided

### ISSUE THREAD

**Issue by ESpinach** [NEZNAMY/TAB#1009]
### Server version

Purpur 1.18.2

### TAB version

4.0.3

### Describe the bug

RGB color in brackets displays unexpected brackets when closing brackets are not provided.

### Expected behavior

No additional brackets should be displayed.

### Steps to reproduce

1. Paste this any config area that has support for RGB color, footer in my case: `<#FF0000|3>test`
2. See this:
![image](https://github.com/NEZNAMY/TAB/assets/137733878/30dddd3b-d202-4838-aaef-ee7375376c01)

### Additional info

Adding closing brackets `<#FF0000|3>test</#FF0000>` fixes everything.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Where does the wiki say this format is supported?

**Comment by Tanguygab** [comment]
put the # before the <

**Comment by NEZNAMY** [comment]
Format not supported, all available formats are on the wiki https://github.com/NEZNAMY/TAB/wiki/How-to-use-RGB-color-codes#usage.
