### ISSUE TITLE
Failed permission

### ISSUE THREAD

**Issue by xNathanz** [NEZNAMY/TAB#101]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
2.6.4

**Describe the bug**
Nothing just spamming the error file making it big

**How to reproduce**
Nothing just spamming the error file making it big

**Expected behavior**
Nothing just spamming the error file making it big

**Actual behavior**
Nothing just spamming the error file making it big

**Additional info** (errors, screenshots, ...)
[TAB v2.5.4] Failed to get permission group of xNathanz (permission plugin: LuckPerms)

**Comment by NEZNAMY** [comment]
So your plugin version is 2.6.4, but error message which was fixed in 2.6.0 says 2.5.4 ?
