### ISSUE TITLE
Entity Nametag

### ISSUE THREAD

**Issue by sweatopants69** [NEZNAMY/TAB#1011]
### Server version

paper 1.20.1

### TAB version

4.0.3

### Describe the bug

Nametags work on non friendly mobs, once tamed the tag disappears.

### Expected behavior

Tamed animal nametag should not disappear

https://github.com/NEZNAMY/TAB/assets/118136852/5c700373-2ae7-49a1-af6e-547d8e9f0440

### Steps to reproduce

tame a wolf, use a nametag on it

### Additional info

i tested this bug with tab removed from the load order, and it did not reoccur so im certain its a tab issue

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-3---prefixsuffix-on-pets
