### ISSUE TITLE
Lunar Client logo does not display when "Unlimited-Nametag_Mode" is enabled

### ISSUE THREAD

**Issue by Narrow-band** [NEZNAMY/TAB#1012]
### Server version

Spigot 1.20.1

### TAB version

V 4.0.3

### Describe the bug

Title pretty much says it all, if you enable the "unlimited_nametag_mode" in the config the Lunar Client Logo is no longer displayed. 

### Expected behavior

I would like to be able to see the Lunar Client Logo in the server Tab and on the Nametags when "unlimited_nametag_mode" is enabled. 

### Steps to reproduce

Enable "unlimited_nametag_mode" in config.yml

### Additional info

This isn't a game-breaking mechanic and I know that this is a 3rd-party client it would just be nice to see this resolved. The only reason I have that setting enabled is to display the nick name on the player's tag. 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Not possible, the unlimited nametag mode hides vanilla nametags and spawns armorstands above players.
