### ISSUE TITLE
Server constantly getting OOM killed possibly due to scoreboard refreshing

### ISSUE THREAD

**Issue by mallusrgreatv2** [NEZNAMY/TAB#1013]
https://bin.birdflop.com/igocubatox.makefile
Config.yml:
https://bin.birdflop.com/axamusinis.yaml

**Comment by NEZNAMY** [comment]
Why did you ignore issue templates? Where is any proof supporting your statement?

**Comment by mallusrgreatv2** [comment]
Alright sorry
I thought it wasn't related to any of the templates mentioned

**Comment by NEZNAMY** [comment]
Memory leak is an existing template exactly matches your issue type.
