### ISSUE TITLE
Tean not changin after editing name

### ISSUE THREAD

**Issue by EURedBoy** [NEZNAMY/TAB#1014]
### Server version

NachoSpigot 1.8.9

### TAB version

4.0.3

### Describe the bug

When I try to change the name using nms, the player team doesn't apply on the new name

Nms code:
`public void nsmName(Player player, String name) {
        try {
            GameProfile profile = ((CraftPlayer) player).getHandle().getProfile();
            PlayerConnection connection = ((CraftPlayer) player).getHandle().playerConnection;

            Field field = profile.getClass().getDeclaredField("name");

            field.setAccessible(true);
            field.set(profile, name);

            connection.sendPacket(new PacketPlayOutPlayerInfo(
                    PacketPlayOutPlayerInfo.EnumPlayerInfoAction.UPDATE_DISPLAY_NAME,
                    ((CraftPlayer) player).getHandle()
            ));

        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
    } `
    
![image](https://github.com/NEZNAMY/TAB/assets/69308679/0c22d1a4-64c6-4c9f-bc8a-6aff94d4ab19)

### Expected behavior

The team should follow the player even if it changes its name

### Steps to reproduce

Step 1: Set a prefix for the player
Step 2: Update the player name using nms

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
try latest build

**Comment by EURedBoy** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/69308679/5def4253-d802-497a-8779-a9fb408adc70)
i just tried to use the latest build but its still not working

**Comment by NEZNAMY** [comment]
You only edited player's name field, you did not send any packet using it, such as add packet. TAB is not checking player's name periodically to see if there is a change or not, it's listening to packets.

**Comment by EURedBoy** [comment]
Even in this way, however, the prefix is ​​not updated

```
public void nsmName(Player player, String name) {
        try {

            GameProfile profile = ((CraftPlayer) player).getHandle().getProfile();
            PlayerConnection connection = ((CraftPlayer) player).getHandle().playerConnection;

            hideAll(player);
            connection.sendPacket(new PacketPlayOutPlayerInfo(
                    PacketPlayOutPlayerInfo.EnumPlayerInfoAction.REMOVE_PLAYER,
                    ((CraftPlayer) player).getHandle()
            ));

            Field field = profile.getClass().getDeclaredField("name");

            field.setAccessible(true);
            field.set(profile, name);

            showAll(player);
            connection.sendPacket(new PacketPlayOutPlayerInfo(
                    PacketPlayOutPlayerInfo.EnumPlayerInfoAction.ADD_PLAYER,
                    ((CraftPlayer) player).getHandle()
            ));

        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }
    }
```

**Comment by NEZNAMY** [comment]
With latest build? Send the packet to all players, not just the one who changed name.

**Comment by EURedBoy** [comment]
Using the spigot function hidePlayer you send the remove player packet same thing with showPlayer, and yes i'm using the latest version of the plugin

**Comment by EURedBoy** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/69308679/766d5b9c-f97a-4085-8c61-1a31ee7349c9)
