### ISSUE TITLE
Bug tagprefix

### ISSUE THREAD

**Issue by Carl6661** [NEZNAMY/TAB#1015]
### Server version

1.20.1

### TAB version

4.0.3

### Describe the bug

The plugin does not support HEX colors in tagname in the groups folder
Supports only regular colors

### Expected behavior

![image](https://github.com/NEZNAMY/TAB/assets/129277526/89727bd3-f35d-4c93-8714-2a6b4e8aeb4d)

Displaying HEX colors over the player's head in the nickname

![image](https://github.com/NEZNAMY/TAB/assets/129277526/3ef1402c-2c7a-4464-93c2-b7cd2d6ce412)

### Steps to reproduce

Add HEX color support

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#limitations
