### ISSUE TITLE
NameTag position is incorrect when riding camel

### ISSUE THREAD

**Issue by cupangafk** [NEZNAMY/TAB#1016]
### Server version

`[10:24:05 INFO]: Current: git-Purpur-2028 (MC: 1.20.1)*`

### TAB version

[10:24:55 INFO] [TAB]: TAB v4.0.3

### Describe the bug

nametag is inside the camel when it supposed to be above player head
![image](https://github.com/NEZNAMY/TAB/assets/66926348/eeb73421-827b-4672-ae57-654d7b0eefc7)
![image](https://github.com/NEZNAMY/TAB/assets/66926348/2e93e80f-0b3c-48e4-bc40-2c3ba35b9742)
![image](https://github.com/NEZNAMY/TAB/assets/66926348/441eb720-eaf2-4f18-9dc2-e0643db4b0a8)

### Expected behavior

it should be like when riding a horse
![image](https://github.com/NEZNAMY/TAB/assets/66926348/0b095546-7548-4466-b777-134a302d5271)

### Steps to reproduce

- logged in
- ride a camel
- make your friends watch you happily ride a camel until they notice something is wrong

### Additional info

- server setup is 1 waterfall proxy, and 1 purpur server with TAB on the proxy and TAB Bridge is on the purpur server
bridge version is `3.1.3`
- server is in offline mode 
- i haven't checked when both player are riding the camel (i dont have that many friends)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Th7bo** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-6---position-bug-on-camels

**Comment by cupangafk** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-6---position-bug-on-camels

tyty
