### ISSUE TITLE
Scoreboard-Teams is not working

### ISSUE THREAD

**Issue by SF2333333** [NEZNAMY/TAB#1017]
### Server version

1.20.1

### TAB version

4.0.3

### Describe the bug

I install tab on BungeeCord and I don't get the group the player is in, but I install it on the backend server and get the group normally I tried using /btab parse %group% but only the default group is displayed

### Expected behavior

I know

### Steps to reproduce

BungeeCord installs tab The backend server installs TAB-Bridge
config ：scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:admin,king,rank3,rank2,rank1,default
  - PLACEHOLDER_A_TO_Z:%player%

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/68703324/10596193-7718-49a6-b336-052c66120abe)
![image](https://github.com/NEZNAMY/TAB/assets/68703324/26f3963a-eda2-4d3e-a6de-065c24e68209)
![image](https://github.com/NEZNAMY/TAB/assets/68703324/6749af1f-1a1b-4e85-bd3b-2d42a790e90e)
![image](https://github.com/NEZNAMY/TAB/assets/68703324/3d809c7d-314e-433c-939e-4de7538ff26e)
![image](https://github.com/NEZNAMY/TAB/assets/68703324/9333b91a-6a15-479f-84b6-696dba373c5f)
![image](https://github.com/NEZNAMY/TAB/assets/68703324/d1f6faf3-c426-41db-b8c9-3446c3e2ef7f)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by SF2333333** [comment]
I tried sorting by permissions But it shows that I don't have any permissions I suspect it's a placeholder issue But the prefix gets fine

**Comment by NEZNAMY** [comment]
Sorting is working. See sorting page and common mistakes.

**Comment by SF2333333** [comment]
I read the problem manual and troubleshooted, and it still doesn't work

**Comment by NEZNAMY** [comment]
You showed debug output of a player in default group. Is that player supposed to be in default group or not? Where in the tablist is that player and where is that player supposed to be? You completely cut player names.

**Comment by SF2333333** [comment]
Sorry to bother you, I'm a little stupid How should I configure it to work?

**Comment by SF2333333** [comment]
Yes, btab does not get the player's group, they are all in the correct group, not the default, when I install it separately on the backend server can get the correct and use the configuration of btab but bc does not get properly

**Comment by SF2333333** [comment]
I misunderstood you

**Comment by NEZNAMY** [comment]
Then you did not configure LuckPerms correctly. I will not help with that. This is an issue tracker.
