### ISSUE TITLE
TAB doesn't update player prefix and suffix when changing name

### ISSUE THREAD

**Issue by porudev** [NEZNAMY/TAB#1018]
### Server version

Spigot 1.8.8

### TAB version

4.03

### Describe the bug

The plugin doesn't update player prefix and suffix after changing the player name, even after forcing prefix and suffix change via the API

```
        TabPlayer tabPlayer = tabAPI.getPlayer(name);
        if(tabPlayer != null && nameTagManager != null){
            nameTagManager.setPrefix(tabPlayer, nameTagManager.getCustomPrefix(tabPlayer));
            nameTagManager.setSuffix(tabPlayer, nameTagManager.getCustomSuffix(tabPlayer));
        }
```

Player's prefix and suffix is only changed after doing a reload

### Expected behavior

The plugin automatically update player's prefix and suffix

### Steps to reproduce

Modify the player's GameProfile to change the name while still keep the rest of the properties

### Additional info

This is how a name change is perform

```
    public void changeName(Player player, String name) {
        player.setCustomName(player.getName());
        player.setPlayerListName(name);
        player.setDisplayName(name);

        try {
            Method getHandle = player.getClass().getMethod("getHandle");
            Object entityPlayer = getHandle.invoke(player);
            Object profile = entityPlayer.getClass().getMethod("getProfile").invoke(entityPlayer);
            Field nameField = profile.getClass().getDeclaredField("name");
            nameField.setAccessible(true);
            nameField.set(profile, name);
        } catch (NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | NoSuchFieldException | InvocationTargetException e) {
            logger.severe("Error while changing " + player.getName() + "'s nick!");
        }

        TabPlayer tabPlayer = tabAPI.getPlayer(name);
        if(tabPlayer != null && nameTagManager != null){
            nameTagManager.setPrefix(tabPlayer, nameTagManager.getCustomPrefix(tabPlayer));
            nameTagManager.setSuffix(tabPlayer, nameTagManager.getCustomSuffix(tabPlayer));
        }
    }
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What is supposed to change exactly? And your "force" doesn't really do anything. Also /ver tab.

**Comment by porudev** [comment]
> What is supposed to change exactly? And your "force" doesn't really do anything. Also /ver tab.

Since TAB don't support changing of  player's name it self, i have to change it via external plugin, my "force" was originally from me thinking that TAB do the same when i performance a `/tab reload`. Do you have any solution to force update the prefix and suffix?

/ver tab
```
[14:39:38 INFO]: TAB version 4.0.3
[14:39:38 INFO]: An all-in-one solution that works
[14:39:38 INFO]: Website: https://github.com/NEZNAMY/TAB
[14:39:38 INFO]: Author: NEZNAMY
```

**Comment by NEZNAMY** [comment]
It is not advertised that 4.0.3 is listening to name change packet.

**Comment by porudev** [comment]
Do you have any solution to force update prefix and suffix via the API?

**Comment by NEZNAMY** [comment]
Force is not required. Name change detection will be added in 4.0.4.

**Comment by porudev** [comment]
> Force is not required. Name change detection will be added in 4.0.4. Apparently you are not even sending the packet. TAB is not periodically checking player's game profile to see if a random plugin changed the value.

i will add a sending via player.hidePlayer() and player.showPlayer() method

**Comment by NEZNAMY** [comment]
Won't help in the current release. See https://github.com/NEZNAMY/TAB/issues/1014, which you are precisely duplicating.

**Comment by porudev** [comment]
> Won't help in the current release. See #1014, which you are precisely duplicating.

Everything works perfectly now! I'm wondering if you guys are going to release 4.0.4 soon?

**Comment by NEZNAMY** [comment]
No.
