### ISSUE TITLE
getActiveScorebord should be nullable

### ISSUE THREAD

**Issue by kforbro** [NEZNAMY/TAB#1019]
### Server version

Purpur 1.20.1

### TAB version

4.0.4-SNAPSHOT

### Describe the bug

getActiveScoreboard can be null if the player disabled the scoreboard with the command
![image](https://github.com/NEZNAMY/TAB/assets/39985355/b131b223-7a90-48ad-87d0-f0b96eb4e9a7)
![image](https://github.com/NEZNAMY/TAB/assets/39985355/a89a8b4e-53c2-42b9-ad9a-4e5362d35f11)
![image](https://github.com/NEZNAMY/TAB/assets/39985355/73b833cf-971c-4fc3-a20c-b945af9415c8)

getActiveScoreboard can be null if the player disabled the scoreboard with the command

### Expected behavior

@Nullable Scoreboard getActiveScoreboard(@NonNull TabPlayer player);

### Steps to reproduce

1. execute /scoreboard
2. send custom board via api
3.
TabPlayer tabPlayer = TabAPI.getInstance().getPlayer(player.getUniqueId());
TabAPI tabApi = TabAPI.getInstance();
ScoreboardManager scoreboardManager = tabApi.getScoreboardManager();
if (scoreboardManager == null) return;
if (!scoreboardManager.hasCustomScoreboard(tabPlayer) return;
Scoreboard board = scoreboardManager.getActiveScoreboard(tabPlayer);
system.out.println(board.getLines().size())

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
this was already fixed https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/scoreboard/ScoreboardManager.java#L168
