### ISSUE TITLE
CMI AFK Support

### ISSUE THREAD

**Issue by Insprill** [NEZNAMY/TAB#102]
Hey i would love to have the AFK feature work with CMI :)

**Comment by NEZNAMY** [comment]
Not possible, i would need access to the jar to do it, and i'm not going to buy it.
Check PlaceholderAPI https://www.spigotmc.org/resources/placeholderapi.6245/
and placeholders CMI offers for it https://www.spigotmc.org/wiki/cmi-placeholders/

**Comment by Insprill** [comment]
I mean even tho i shouldn't i could send u the jar

**Comment by NEZNAMY** [comment]
Is there a reason you can't install placeholderapi ? It was made exactly for this purpose.
