### ISSUE TITLE
Essentials/Vault Error

### ISSUE THREAD

**Issue by FoxtrayStudio** [NEZNAMY/TAB#1021]
### Server version

Spigot 1.8.8

### TAB version

4.0.3

### Stack trace

https://pastebin.com/cg1aMAPj

### Steps to reproduce (if known)

Install vault and essentials expansions, and use the placeholders (we use it thru a gui)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
TAB -> PlaceholderAPI -> Vault -> Essentials.
Because of this, the error is not on TAB's side. It is using PlaceholderAPI normally and what happens after that is out of TAB's control.
