### ISSUE TITLE
Is not compatible with ArcLight

### ISSUE THREAD

**Issue by randomkid123** [NEZNAMY/TAB#1022]
### Server version

Arclight 1.20.1 version 1.0.0

### TAB version

4.0.3

### Describe the bug

Upon start up when the plugin attempts to load it says this message:

[TAB] A compatibility issue with your server was found. Unless you are running some really weird server software, this is a bug.
![image](https://github.com/NEZNAMY/TAB/assets/45009702/79838c6c-9228-4d7d-854d-bc1a1a990aba)

### Expected behavior

I expected the plugin to load correctly.

### Steps to reproduce

Step 1: Create an arclight server on that version.
Step 2: Add TAB as a plugin.
Step 3: Start the server.

### Additional info

As far as I'm aware ArcLight isn't listed on the plugin's compatibility page.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Why are you expecting the plugin to load? Where does the compatibility page say that software is supported?

**Comment by randomkid123** [comment]
It may not say it's supported but it doesn't say it isn't supported either, and since almost every bukkit plugin works on arclight it's a fair assumption. I also had success using this plugin on older versions of arclight.

**Comment by NEZNAMY** [comment]
I can't name every hybrid server software, there's too many. And plugin only supports those using bukkit mapping or mojang mappings, which older version of that software may have used, but new version apparently doesn't. I also wasn't even able to start the server to test it.

**Comment by randomkid123** [comment]
That's unfortunate, would of loved to use this plugin. I'll see if I can get the forge version working but as it's on 1.16.5 I don't think I'll get very far lol.
