### ISSUE TITLE
Redis Tablist bug

### ISSUE THREAD

**Issue by Official-KronixLP** [NEZNAMY/TAB#1023]
### Server version

VeloCity 1.20.1

### TAB version

4.0.3

### Describe the bug

When using Redisbungee on Velocity (Velocity build #119 1.20.1), you will not be able to see the player names when enabling the globalplayerlist feature on
both proxys. Only the player counter is working.

### Expected behavior

Seeing the other players in the tablist even if you are on a different proxy using Redis Bungee.

### Steps to reproduce

Installing Redis and using 2 Proxy's with 1 sub server each while having TAB on the proxys with globalplayerlist enabled

### Additional info

would be nice to know if there is a way to fix this :)
saw a thread from 2020 that it mind be added soon.
there are no alternative's sadly and TAB is already the best plugin.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Velocity is not supported and RedisBungee support is only available on, well, Bungee

**Comment by 4drian3d** [comment]
> RedisBungee support is only available on, well, Bungee

https://github.com/NEZNAMY/TAB/blob/master/velocity/src/main/java/me/neznamy/tab/platforms/velocity/features/VelocityRedisSupport.java 👀

**Comment by NEZNAMY** [comment]
Not tested however.
