### ISSUE TITLE
Player shown twice one formatted one not

### ISSUE THREAD

**Issue by konek101** [NEZNAMY/TAB#1025]
### Server version

Paper 1.19.4

### TAB version

4.0.3

### Describe the bug

I have a config for columns to show and set the player group to display from 2 to 40 but still the not formatted player displays at the top 
![image](https://github.com/NEZNAMY/TAB/assets/131317299/6b21b14d-50a8-48ac-9f8f-6a6f5ab31dbf)

### Expected behavior

The first line shoud not have the player

### Steps to reproduce

I tried with only the tab plugin and still its like it 

here is the config

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - <#FFFFFF>&m                                                </#FFFF00>
  - '&3&lSerwer'
  footer:
  - '&cŻycia będą po tygodniu'
  - '&a%kaska%'
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: false
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
yellow-number-in-tablist:
  enabled: false
  value: '%czaszka%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
layout:
  enabled: true
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
        - '1|&eGracze Online'
        - '41|&eŚmierci'
        - '42|%zgon_1%'
        - '43|%zgon_2%'
        - '44|%zgon_3%'
        - '45|%zgon_4%'
        - '46|%zgon_5%'
        - '47|%zgon_6%'
        - '48|%zgon_7%'
        - '49|%zgon_8%'
        - '50|%zgon_9%'
        - '51|%zgon_10%'
        - '52|%zgon_11%'
        - '53|%zgon_12%'
        - '54|%zgon_13%'
        - '55|%zgon_14%'
        - '56|%zgon_15%'
        - '57|%zgon_16%'
        - '58|%zgon_17%'
        - '59|%zgon_18%'
        - '60|%zgon_19%'
        - '61|&eKasa'
        - '62|%kasa_1%'
        - '63|%kasa_2%'
        - '64|%kasa_3%'
        - '65|%kasa_4%'
        - '66|%kasa_5%'
        - '67|%kasa_6%'
        - '68|%kasa_7%'
        - '69|%kasa_8%'
        - '70|%kasa_9%'
        - '71|%kasa_10%'
        - '72|%kasa_11%'
        - '73|%kasa_12%'
        - '74|%kasa_13%'
        - '75|%kasa_14%'
        - '76|%kasa_15%'
        - '77|%kasa_16%'
        - '78|%kasa_17%'
        - '79|%kasa_18%'
        - '80|%kasa_19%'
      groups:
        players:
          slots:
          - '2-40'
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Delete world/data/scoreboard.dat and try again.

**Comment by konek101** [comment]
but still in the wiki it does not say that scoreboard-teams off makes it do that

**Comment by NEZNAMY** [comment]
Sounds like an issue that should be solved.
