### ISSUE TITLE
When doing /tab scoreboard show (scoreboard), the scoreboard selected does not stay if you rejoin.

### ISSUE THREAD

**Issue by Niccckkkk** [NEZNAMY/TAB#1026]
### Server version

Paper 1.20.1

### TAB version

4.0.1

### Describe the bug

I have multiple scoreboard types with different designs, as well as a staff scoreboard.
The scoreboard "shown" does not stay shown if you rejoin, and instead goes to the default scoreboard.

### Expected behavior

The plugin remembers the scoreboard being used (with the /tab scoreboard show command), and I join the server with the same scoreboard that I had selected in my previous selection.

### Steps to reproduce

Create multiple scoreboards in config.yml, then /tab scoreboard show (scoreboard) to a player, then rejoin. That scoreboard will not appear upon rejoining and only show the default scoreboard you made.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
try on latest version

**Comment by NEZNAMY** [comment]
Show command's data is not stored between rejoins.

**Comment by Niccckkkk** [comment]
> Show command's data is not stored between rejoins.

Ahh I gotcha. Nw! no suggestions rn yeah?
