### ISSUE TITLE
Players don't show as spectator when layout is enabled

### ISSUE THREAD

**Issue by BlueSoapTurtle** [NEZNAMY/TAB#1027]
### Server version

Velocity 1.20.1

### TAB version

4.0.3

### Describe the bug

When enabling layout on the proxy config for tab, anyone in spectator mode or on another server don't show as in spectate mode, even with these settings
display-others-as-spectators: true
display-vanished-players-as-spectators: true

### Expected behavior

Expected that players on another server than the one you're on or players in spectate mode would show as spectator in the tab

### Steps to reproduce

Enable layout on proxy tab config and have one player on server A and server B

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Expected for Layout, though why did you send your global-playerlist settings? and Velocity is not supported.

**Comment by NEZNAMY** [comment]
Spectators automatically go to the bottom of tablist, which would break the layout completely.

**Comment by BlueSoapTurtle** [comment]
> Expected for Layout, though why did you send your global-playerlist settings? and Velocity is not supported.

I figured it was the only thing relevant to it, and you say velocity isn't supported but it works on velocity though?

> Spectators automatically go to the bottom of tablist, which would break the layout completely.
Ah that makes sense yeah, I'll make a placeholder that shows them in another color if they're not in your server instead. thanks :)
