### ISSUE TITLE
 Players excluded due to error

### ISSUE THREAD

**Issue by QuQuShKa1205** [NEZNAMY/TAB#1028]
### Server version

SSSpigot 1.20.1

### TAB version

4.0.3

### Stack trace

Hello. I have a problem on the server. I think the problem is in the tab plugin. Logs - https://github.com/NEZNAMY/TAB/files/12363984/logs.1.log. "Issue - [14:38:26] [Netty Epoll Server IO #3/ERROR]: Packet encoding of packet ID 82 threw (skippable? false)"

### Checklist

- [x] I am running latest version of the plugin
- [x] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Unrelated, TAB does not do anything related to items
