### ISSUE TITLE
Switching from 1.20.1 to 1.19.4, scoreboard is no longer shown

### ISSUE THREAD

**Issue by mallusrgreatv2** [NEZNAMY/TAB#1029]
### Server version

Pufferfish 1.19.4

### TAB version

4.0.3

### Describe the bug

This has happened to a few players on the server already, and I recently experienced it.
I played a bit on my server with 1.19.4, the main version of the server. Then, I decided to change my version to 1.20.1. I decided to go back to 1.19.4, but then the scoreboard wasn't shown anymore. Re-enabling it using the /sb command doesn't work either.

### Expected behavior

The scoreboard is shown.

### Steps to reproduce

Step 0: Install a multi-version support plugin like ViaVersion
Step 1: Log onto the server in 1.20.1
Step 2: Close it and open 1.19.4
Step 3: Watch as your scoreboard is no longer shown.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config. Also try reproducing it on a test server with no other plugins.

**Comment by mallusrgreatv2** [comment]
https://paste.helpch.at/romucifupo.yaml
I tried it on a test server. No plugins at all, except TAB. Doesn't show up. Same files as the server. Tried to regenerate playerdata.yaml and users.yml, didn't do anything.

**Comment by NEZNAMY** [comment]
Remove line 95. You are not meeting the condition, therefore the scoreboard is not displayed.

**Comment by mallusrgreatv2** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/69511006/9db1769e-1225-4e75-8cdc-69284454ed51)
latest.log: https://paste.helpch.at/onajumapek.log

**Comment by mallusrgreatv2** [comment]
Alright thanks

**Comment by NEZNAMY** [comment]
Was that really it? Then it's not a bug, is it?
