### ISSUE TITLE
per-world-playerlist isn't working.

### ISSUE THREAD

**Issue by iiAhmedYT** [NEZNAMY/TAB#1032]
### Server version

Paper 1.8.8

### TAB version

4.0.3

### Describe the bug

It's exactly what the title says. No errors, nothing.
per-world-playerlist is enabled but doesn't work at all

### Expected behavior

Don't see players in world69 when I'm in world420 in tab

### Steps to reproduce

No.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send plugin list.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/26b02ba8-5f79-4b0f-bbb3-ec08957d373f)

**Comment by NEZNAMY** [comment]
Try with only TAB and the multi-world plugin.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/b672bb22-b314-4808-9896-283af254d715)
still doesn't work (SlimeWorldManager is required for worlds to work)

**Comment by NEZNAMY** [comment]
You didn't even remove the bedwars plugin, which is causing it. Remove bedwars and try again.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/18e8ef00-0fe7-4506-be4c-cbc43cc04922)
still not working

**Comment by NEZNAMY** [comment]
Send screenshot of tablist and output of `/tab parse <player> %world%` for both players.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/33f2f372-395a-435f-af04-43002163a1d9)

**Comment by NEZNAMY** [comment]
Send per world playerlist part of your config. You also forgot to take a screenshot of the tablist.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/0b401de1-2532-459f-839e-97fe0f44a09a)
im still in the test world and he's on the "world" world

![image](https://github.com/NEZNAMY/TAB/assets/61851106/01680c96-ceba-411b-ba1b-ecb98e8ff533)

**Comment by NEZNAMY** [comment]
Does /tab reload fix it?

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/e2fcb388-bdae-4fee-bf04-ee3fc81f9943)

**Comment by NEZNAMY** [comment]
Remove all plugins except TAB. Use nether portal to switch worlds. I just tested it on 1.8.8 paper and it works.

**Comment by iiAhmedYT** [comment]
well maybe TAB lacks SWM support?

**Comment by NEZNAMY** [comment]
Such support was never advertised in the first place. If you think so, use multiverse, which is confirmed to be working.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/85d223a7-68b5-4b47-8ba2-82b2549b0874)
ok what now.

**Comment by iiAhmedYT** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/61851106/3cff5784-a53b-47f4-ba8b-19f4a5852923)

**Comment by NEZNAMY** [comment]
Set debug: true in config and show console output on join.

**Comment by iiAhmedYT** [comment]
I don't think it's TAB now. I think it could be my dev fucking up our paper fork. I trust TAB more than our lmao. ill let you know in a min

**Comment by NEZNAMY** [comment]
That means you lied when you said you are using 1.8.8 paper. Use 1.8.8 paper, which you claim to be using.

**Comment by iiAhmedYT** [comment]
Let's close this issue for now till i am able to change the jar. If its still broken ill let you know.
