### ISSUE TITLE
Relation placeholderapi problem

### ISSUE THREAD

**Issue by OldisPL** [NEZNAMY/TAB#1033]
### Server version

1.19

### TAB version

4.0.3

### Describe the bug

Hello,

Hi,

We are using a plugin to generate a scoreboard over a player's head, the problem occurs when I try to use a variable that is relative to another player.

https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/expansion/Relational.java
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#relational-placeholders

/papi parserel Oldis Oldis %rel_clan_clan-name%
/papi parserel Oldis OtherPlayer %rel_clan_clan-name%

Return valid values, placeholder also work inside other plugins but we can't use that inside scoreboard overhead.

### Expected behavior

Variable should be rendered

### Steps to reproduce

1. Create your variable/use other from public extensions
2. Place it inside suffix/prefix
3. Should be rendered

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
And what's the issue? You didn't send any output (whether it's the one TAB outputs or the one PAPI outputs) nor did you provide any configuration

**Comment by OldisPL** [comment]
Output from PAPI:

![image](https://github.com/NEZNAMY/TAB/assets/11366057/c8d17d80-7aa7-46aa-879d-3fc32334fc86)

Also we are using that inside our code (as you see on screen):

![image](https://github.com/NEZNAMY/TAB/assets/11366057/3b344131-c4cd-4384-9301-3a93facbc8ce)

Suffix/Prefix is added via luckperms

Result:
![image](https://github.com/NEZNAMY/TAB/assets/11366057/1f2815fc-1d9d-46ef-98ba-65a88b26168e)

**Comment by Tanguygab** [comment]
/tab debug Oldis
and check if you got an errors.log or placeholder-errors.log file

**Comment by NEZNAMY** [comment]
Relational placeholders inside normal placeholders are currently not supported.

**Comment by OldisPL** [comment]
@NEZNAMY 

Hmm, I don't understand, so somehow I can register my variable in some other way to support that via your plugin? I can do workaround and register it somehow if it possible

**Comment by Tanguygab** [comment]
send the output of /tab debug <player>

**Comment by OldisPL** [comment]
@Tanguygab 

![image](https://github.com/NEZNAMY/TAB/assets/11366057/6c7e065d-29a4-4a86-b1e7-bb4b595bd2c1)

**Comment by Tanguygab** [comment]
I don't see the placeholder here

**Comment by NEZNAMY** [comment]
You must use the relational placeholder directly in TAB, not inside another placeholder (%luckperms-suffix%).

**Comment by OldisPL** [comment]
@NEZNAMY  holy, okey, now I catch, Ty bro!

@Tanguygab  Thanks a lot for guiding me!
