### ISSUE TITLE
Incompatibility with GrimAC?

### ISSUE THREAD

**Issue by mooziii** [NEZNAMY/TAB#1034]
### Server version

Paper 1.20.1

### TAB version

4.0.3

### Describe the bug

When using with Grim, I get this error: https://pastes.dev/y8VP9s6ABH, in **Line 94** it also mentions a method of TAB

### Expected behavior

Plugin should work fine

### Steps to reproduce

Step 1: Install Grim
Step 2: Install TAB
Step 3: the error should occour 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
TAB does not send or modify chunk packets. Remove TAB and see if it continues.
