### ISSUE TITLE
Tab AFK Status after 4.0.0 - what to do? 

### ISSUE THREAD

**Issue by H34R7L3s** [NEZNAMY/TAB#1036]
![image](https://github.com/NEZNAMY/TAB/assets/111546017/b1d22128-9ee4-4337-b01e-1a0aef085b5f)

![image](https://github.com/NEZNAMY/TAB/assets/111546017/1e146ad5-d16a-4d4c-82fd-d0b5db63392e)

![image](https://github.com/NEZNAMY/TAB/assets/111546017/cbd2e38d-ea9c-4c6e-9f67-381638660f39)

what am i missing?
Both Ideas not working.
Any help would be nice

**Comment by NEZNAMY** [comment]
This is an issue tracker, not support.
You are missing:
* PlaceholderAPI, Essentials or essentials expansion
* You are using two name placeholders in customtabname
* You duplicated conditions map, with the second one overriding the first one
