### ISSUE TITLE
TAB bunge server bug

### ISSUE THREAD

**Issue by dol4iua** [NEZNAMY/TAB#1037]
### Server version

Bungee -1.20 / Purpur -1.20.1 / Paper 1.12.2 

### TAB version

TAB.v4.0.2.jar

### Describe the bug

the prefix from one server to another is stored
![1](https://github.com/NEZNAMY/TAB/assets/24779133/3047b6f4-9832-4f08-9bd3-d007c80f8389)
![Знімок екрана 2023-08-21 194213](https://github.com/NEZNAMY/TAB/assets/24779133/6268f75e-9e28-47eb-a196-dd8ff67d21a5)

### Expected behavior

Not displaying the prefix from another server

### Steps to reproduce

I installed a bungee tab and bridges to the server, disabled unnecessary servers

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
`/btab debug <player>` 
`/btab parse <player> %luckperms_prefix%`
`/papi parse <player> %luckperms_prefix%`

**Comment by dol4iua** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/24779133/f3b70f60-00ab-4428-843c-21b23f99db63)
![image](https://github.com/NEZNAMY/TAB/assets/24779133/2bbcc930-a150-4a39-a3f3-e9931346ed35)
![image](https://github.com/NEZNAMY/TAB/assets/24779133/dbd2402b-e811-4546-97cc-ec1cd706b51c)
![image](https://github.com/NEZNAMY/TAB/assets/24779133/d27f512b-9a2f-4060-a57e-24aedc4edd61)

**Comment by dol4iua** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/24779133/90eba266-0225-4e6e-bd97-8d1acad9cf51)

**Comment by NEZNAMY** [comment]
So you are reporting that entering a disabled server makes he plugin send the format using unparsed placeholders?

**Comment by dol4iua** [comment]
This is the bedwars server, it has its own tab, but for some reason some people on the tab are given aliases that are in the bungee tab

**Comment by NEZNAMY** [comment]
Mixed installation is not supported.

**Comment by dol4iua** [comment]
That is, it is impossible to disable TAB for the server if it is in the bungee network?

**Comment by NEZNAMY** [comment]
It is. Can you confirm that the issue is what I described above?

**Comment by dol4iua** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/24779133/b439798c-9ce0-4496-bcb1-850b067f1ea5)
https://www.youtube.com/watch?v=aOcu54h4tOs&feature=youtu.be
Maybe it will be easier for you to understand the problem. Sorry for my English, it's not my native language

**Comment by NEZNAMY** [comment]
So the plugin is still formatting tablist names despite being disabled?

**Comment by dol4iua** [comment]
+

But it takes the name from the last server where it is enabled

**Comment by dol4iua** [comment]
Maybe you have some solution to this?

**Comment by NEZNAMY** [comment]
No, I am not able to test it right now. Making free plugins is not my full-time job.

**Comment by dol4iua** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/24779133/2835eb6d-a286-4ae2-9898-a425afed0f06)

Is it possible, or is this not a question for you?

**Comment by NEZNAMY** [comment]
No, this kind of setup will work poorly.

**Comment by dol4iua** [comment]
Thank you very much for your help, if I find a solution I will let you know, maybe it will be useful for you. Have a nice and peaceful day.

**Comment by dol4iua** [comment]
Build #833 Fix it , Thank you very much for your work
