### ISSUE TITLE
tab placeholder"s error in deluxemenus

### ISSUE THREAD

**Issue by Weyl1** [NEZNAMY/TAB#1039]
### Server version

pufferfish 1.20.1

### TAB version

4.0.3

### Describe the bug

In the deluxemenus discord, it says that it comes from a problem of TAB plugin

https://pastebin.com/5GruHmng

### Expected behavior

![image](https://github.com/NEZNAMY/TAB/assets/96068728/b45aead7-f202-447e-8241-a945628e8344)

### Steps to reproduce

/

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
what placeholder are you using?

**Comment by Weyl1** [comment]
I use for example %tab_tabprefix%

**Comment by Tanguygab** [comment]
does it work in /papi parse me %placeholder%?

**Comment by Weyl1** [comment]
yes actually everything works and after a while the placeholders start giving this error

**Comment by Tanguygab** [comment]
I'm not sure why that happens, you'll have to wait for NEZ to answer

**Comment by NEZNAMY** [comment]
Called too early on join. Use latest build from actions, it will avoid that error.

**Comment by Weyl1** [comment]
actions? This is PlaceholderAPI or TAB ?
