### ISSUE TITLE
Bug in formatting with nickname plugin

### ISSUE THREAD

**Issue by RAFAELESPADA** [NEZNAMY/TAB#1040]
### Server version

1.8

### TAB version

4.0.3

### Describe the bug

Hi. I have a issue with tab plugin
I use my custom plugin to change player gameprofile and use TAB method to set their temporary group to default. The problem is that the fake player is always on the top and the temporary group method dont work with my plugin.
I wanted to when player nicknames himself he goes below everyone on the tablist and not on the top

### Expected behavior

The API should function correctly in ALL cases and makes the sorting correctly

### Steps to reproduce

Use /fake random (It is my plugin command)
And your nickname will be above everyone

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Use latest dev build (found in Actions tab)
This happens because players are sorted by their team names, and since teams are bound to player names instead of UUIDs, if you change the name of the player, the team wont be applied.
In 4.0.4 dev builds, name change detection was brought back so this should be fixed.

**Comment by RAFAELESPADA** [comment]
what is the method to get a player by its name?
im using  apitab.getPlayer(playerData.getName()).setTemporaryGroup("default");

**Comment by NEZNAMY** [comment]
That is correct, but latest release does not listen to packets to detect name change.

**Comment by RAFAELESPADA** [comment]
> what is the method to get a player by its name? im using apitab.getPlayer(playerData.getName()).setTemporaryGroup("default");

This is the method that i need to use to change player position by its name?

**Comment by NEZNAMY** [comment]
Yes. Check new sorting values using /tab debug. Either update to latest build or don't change player names.
