### ISSUE TITLE
Name tags do not apply to domesticated cats.

### ISSUE THREAD

**Issue by Ecilpse** [NEZNAMY/TAB#1041]
### Server version

1.20.1

### TAB version

4.0.3

### Describe the bug

Name tags do not apply to domesticated cats.

### Expected behavior

.

### Steps to reproduce

i reproduce issue through video: https://youtu.be/cpZf8PSod8Q

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-3---prefixsuffix-on-pets

**Comment by NEZNAMY** [comment]
- Ticked all boxes without reading them
- Private video
- Poor description
Must be another day on TAB issue tracker.
