### ISSUE TITLE
about unlimited-nametag-mode

### ISSUE THREAD

**Issue by yizexiaomu** [NEZNAMY/TAB#1043]
### Server version

Fabric 1.20.1

### TAB version

4.0.3

### Describe the bug

The unrestricted nametag mode function of this mod in the fabric version cannot be successfully configured.Modify the unlimited nametag mode in the configuration file to enable reloading the configuration file. After entering the command, it still shows that the feature needs to be enabled
![QQ截图20230825213852](https://github.com/NEZNAMY/TAB/assets/143194618/3b015bda-b657-4de6-9442-ce22757f6b34)
![QQ截图20230825213852](https://github.com/NEZNAMY/TAB/assets/143194618/5ad9f565-3e62-4352-8a5a-25d7b65cdd76)
![QQ截图20230825213909](https://github.com/NEZNAMY/TAB/assets/143194618/2905ae6e-0999-4d1e-807e-545d81bc5344)

### Expected behavior

I hope this feature can function properly after changing the configuration file

### Steps to reproduce

Step1: Change the unlimited nametag mode to enable in the configuration file
Step2:Reload the mod configuration file within the server
Step3:Enter this command:/tab player <username> customtagname 1

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/de47418b-497b-4624-9c1a-14faa5f18f16)
