### ISSUE TITLE
¿Bug with nametags?

### ISSUE THREAD

**Issue by Scrulius** [NEZNAMY/TAB#1044]
### Server version

Paper 1.20.1 ver 100

### TAB version

4.0.3

### Describe the bug

I don't know if it's really a bug, but I'm configuring the nametags and the player name overlaps the unlimited-nametag-mode.

I have read the whole wiki but I don't see what the problem could be.

I've gone on discord to ask for help but there are no channels.

Thanks and sorry for the inconvenience

![image](https://github.com/NEZNAMY/TAB/assets/43689161/04cd6118-cbca-4819-a205-c4bcbfc6cf76)

My config:
https://pastebin.com/CmwV0wHs

My groups:

https://pastebin.com/XevcRLTt

### Expected behavior

Something like this (i use holograms to recreate the nametag)

![image](https://github.com/NEZNAMY/TAB/assets/43689161/bb5e2479-74ca-4d50-b9ed-699684c05319)

### Steps to reproduce

I really dont know

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Are you using Lunar?

**Comment by NEZNAMY** [comment]
Try with no other plugins.

**Comment by Scrulius** [comment]
> Are you using LunarClient? If yes, that's a bug in their client. Nothing we can do

Nope, normal minecraft

**Comment by Scrulius** [comment]
> Try with no other plugins.

Im gonna try, thanks

**Comment by Scrulius** [comment]
> Try with no other plugins.

Still happends 

![image](https://github.com/NEZNAMY/TAB/assets/43689161/1c1767e4-1cf8-4e88-a736-05677ec7c201)

**Comment by Tanguygab** [comment]
check your paper.yml, is enable-player-collisions set to false? if yes, set it to true
Also, did you get an anti-override.log file in your TAB folder?

**Comment by Scrulius** [comment]
> Try without any proxy plugins. Also did you get world/data/scoreboard.dat file? If yes, delete it.

Okey, was a proxy plugin, im really sorry for bothering you, thanks guys ^^

![image](https://github.com/NEZNAMY/TAB/assets/43689161/f61b8dd7-a917-4c9b-b910-cbd5dcc6270e)

**Comment by NEZNAMY** [comment]
Which one?

**Comment by Scrulius** [comment]
> Which one?

Velocitab, previously I used TAB for cross-server, the problem is that it doesn't work with velocity :(

Now I use TAB for scoreboard and nametags :P

**Comment by NEZNAMY** [comment]
Of course you can't have 2 plugins handle teams.
