### ISSUE TITLE
Bug with TAB on Velocity

### ISSUE THREAD

**Issue by Gal1leooo** [NEZNAMY/TAB#1045]
### Server version

Velocity 1.19.4

### TAB version

4.0.3

### Describe the bug

Hi, I installed TAB on my Velocity network with Luck Perm. The tablist doesn't update properly, I switch from one server to another and the formatting of the names gets lost, or I change my group of luckperms and the prefix doesn't appear in the tablist. What can I do?

### Expected behavior

Immediate update on group change, and maintenance of name formatting

### Steps to reproduce

I really don't know how to reproduce it

### Additional info

I know that velocity is not fully supported at the moment but I hope you can give me some support.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
That's exactly the reason why Velocity is not supported
