### ISSUE TITLE
PlaceholderAPI not work on TAB

### ISSUE THREAD

**Issue by FaiqGaming** [NEZNAMY/TAB#1046]
### Server version

Paper 1.19.4

### TAB version

4.0.3

### Describe the bug

I have some problem with the Placeholder when i use /parse me <placeholder> it works fine but when i implement to the TAB he didn't work the placeholder.....

### Expected behavior

![image](https://github.com/NEZNAMY/TAB/assets/39037579/56b9127f-ef2a-4734-aad8-845d0e98b5c5)

### Steps to reproduce

/

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What happened here?
