### ISSUE TITLE
Can't change interval on memory-used-gb

### ISSUE THREAD

**Issue by DasCanard** [NEZNAMY/TAB#1047]
### Server version

Paper 1.20.1

### TAB version

4.0.3

### Describe the bug

If you set an placeholder interval for memory-used-gb via config, the behavior won't change.

### Expected behavior

Changed interval.

### Steps to reproduce

Edit config to something like this: 

```
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%memory-used-gb%': 1000
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
```

-> you will see no changes ingame

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That's an internal placeholder, not a PlaceholderAPI one.
![image](https://github.com/NEZNAMY/TAB/assets/6338394/05be37a8-6499-4d21-8637-51560f926bd3)
