### ISSUE TITLE
Players can see when others are in spectator 

### ISSUE THREAD

**Issue by RhinoCD** [NEZNAMY/TAB#1048]
### Server version

Purpur 1.20.1

### TAB version

4.0.3

### Describe the bug

prevent-spectator-effect:
  enabled: true
  
  Players can still see those with the permission tab.spectatorbypass

### Expected behavior

Players not to be able to see those with tab.spectatorbypass

### Steps to reproduce

prevent-spectator-effect:
  enabled: true
  
  Players can still see those with the permission tab.spectatorbypass

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/81fac4c3-23c6-4791-b4f8-6e725a35da2e)
Permission is supposed to make you see others as spectators despite this feature being enabled. So you are saying players without that permission who should see players normally still see them as spectators? Can you make a video?

**Comment by RhinoCD** [comment]
after updating to a dev build the issue has been fixed

**Comment by RhinoCD** [comment]
so I guess whenever you release the next update, its already been patched, thanks!

**Comment by NEZNAMY** [comment]
Last change to the feature was 2 months ago, before 4.0.2 release. But considering the poor information provided, I am happy to get this closed.
