### ISSUE TITLE
BungeeCord TAB，%luckperms-prefix% Does not work

### ISSUE THREAD

**Issue by welove69** [NEZNAMY/TAB#1049]
### Server version

1.20.1

### TAB version

TAB 4.0.3    TAB - Bridge v3.1.3

### Describe the bug

BungeeCord TAB
In the tab list, the placeholder %luckperms-prefix%, %luckperms-suffix%, is displayed blank, and the subserver has TAB - Bridge installed

### Expected behavior

Placeholders can be displayed normally

### Steps to reproduce

BC
In the tab list, the placeholder %luckperms-prefix%, %luckperms-suffix%, is displayed blank, and the subserver has TAB - Bridge installed

### Additional info

The subserver papi also has the luck placeholder installed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
either use LuckPerms on Bungee as well and synchronise it with LP on the backend, or enable `use-bukkit-permissions-manager` in config

**Comment by NEZNAMY** [comment]
Do you have LP installed on bungeecord?
