### ISSUE TITLE
Empty lines not hidden?

### ISSUE THREAD

**Issue by catches** [NEZNAMY/TAB#1051]
### Server version

This server is running Pufferfish version git-Pufferfish-22 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2bc9d45 on HEAD) You are running 1 version beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations. Previous version: git-Pufferfish-19 (MC: 1.20.1)

### TAB version

4.0.3

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/105005455/de7cd1f1-6222-41fa-b8f9-3434e2f8decd)

Would expect the empty line to be hidden

### Expected behavior

Hide empty line

### Steps to reproduce

Step 1: Have abovename
Step 2: Make custom line

### Additional info

Not sure if it's because I'm using relational color + faction name, but the empty line does not appear to be hidden.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Do you maybe have a space in the text? Find out with /tab debug <player>
If it's the case, try dev builds

**Comment by Tanguygab** [comment]
it looks fine, can you try dev builds anyways?

**Comment by Tanguygab** [comment]
send your config.yml

**Comment by Tanguygab** [comment]
config looks fine, unsure what happens, I'll let NEZ handle this

**Comment by NEZNAMY** [comment]
The empty line is hidden, just other lines don't adapt. The plugin is not made to do that. You can achieve such result with conditions.

**Comment by NEZNAMY** [comment]
If the text would be empty, display the text in the first abovename property, if not, display it in 2.

**Comment by NEZNAMY** [comment]
I meant the "bounty" line.

**Comment by NEZNAMY** [comment]
I won't do it for you. Automatic height management does not include output of placeholders, because it would need to support relational placeholders as well, which would require a different view for every online player, which would further complicate already complicated code.
