### ISSUE TITLE
TAB v3.3.0 and TAB v4.0.3 Error in console

### ISSUE THREAD

**Issue by Alisa121212** [NEZNAMY/TAB#1052]
### Server version

1.12.2 sponge

### TAB version

v3.3.0 and v4.0.3 

### Stack trace (TAB v3.3.0)

28.08.2023 - 08:46:57 - [TAB v3.3.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
28.08.2023 - 08:46:57 - java.lang.NullPointerException: null
28.08.2023 - 08:46:57 - 	at java.util.ArrayList.<init>(Unknown Source)
28.08.2023 - 08:46:57 - 	at me.neznamy.tab.shared.command.DebugCommand.getExtraLines(DebugCommand.java:178)
28.08.2023 - 08:46:57 - 	at me.neznamy.tab.shared.command.TabCommand.<init>(TabCommand.java:44)
28.08.2023 - 08:46:57 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:153)
28.08.2023 - 08:46:57 - 	at me.neznamy.tab.platforms.sponge7.Sponge7TAB.onServerStart(Sponge7TAB.java:49)
28.08.2023 - 08:46:57 - 	at org.spongepowered.common.event.listener.GameStartedServerEventListener_Sponge7TAB_onServerStart116.handle(Unknown Source)
28.08.2023 - 08:46:57 - 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)
28.08.2023 - 08:46:57 - 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
28.08.2023 - 08:46:57 - 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
28.08.2023 - 08:46:57 - 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
28.08.2023 - 08:46:57 - 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255)
28.08.2023 - 08:46:57 - 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:363)
28.08.2023 - 08:46:57 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.08.2023 - 08:46:57 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:46:57 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:46:57 - 	at java.lang.reflect.Method.invoke(Unknown Source)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
28.08.2023 - 08:46:57 - 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
28.08.2023 - 08:46:57 - 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
28.08.2023 - 08:46:57 - 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
28.08.2023 - 08:46:57 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.08.2023 - 08:46:57 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:46:57 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:46:57 - 	at java.lang.reflect.Method.invoke(Unknown Source)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
28.08.2023 - 08:46:57 - 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
28.08.2023 - 08:46:57 - 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
28.08.2023 - 08:46:57 - 	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
28.08.2023 - 08:46:57 - 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
28.08.2023 - 08:46:57 - 	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
28.08.2023 - 08:46:57 - 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
28.08.2023 - 08:46:57 - 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
28.08.2023 - 08:46:57 - 	at java.lang.Thread.run(Unknown Source)
28.08.2023 - 08:47:59 - [TAB v3.3.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
28.08.2023 - 08:47:59 - java.lang.NullPointerException: null
28.08.2023 - 08:47:59 - 	at java.util.ArrayList.<init>(Unknown Source)
28.08.2023 - 08:47:59 - 	at me.neznamy.tab.shared.command.DebugCommand.getExtraLines(DebugCommand.java:178)
28.08.2023 - 08:47:59 - 	at me.neznamy.tab.shared.command.TabCommand.<init>(TabCommand.java:44)
28.08.2023 - 08:47:59 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:153)
28.08.2023 - 08:47:59 - 	at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:29)
28.08.2023 - 08:47:59 - 	at me.neznamy.tab.platforms.sponge7.Sponge7TAB.executeCommand(Sponge7TAB.java:67)
28.08.2023 - 08:47:59 - 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
28.08.2023 - 08:47:59 - 	at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355)
28.08.2023 - 08:47:59 - 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360)
28.08.2023 - 08:47:59 - 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)
28.08.2023 - 08:47:59 - 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
28.08.2023 - 08:47:59 - 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
28.08.2023 - 08:47:59 - 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
28.08.2023 - 08:47:59 - 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
28.08.2023 - 08:47:59 - 	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219)
28.08.2023 - 08:47:59 - 	at net.minecraft.network.PacketThreadUtil$1.redirect$zln000$impl$redirectToPhaseTracker(SourceFile:540)
28.08.2023 - 08:47:59 - 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
28.08.2023 - 08:47:59 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
28.08.2023 - 08:47:59 - 	at java.util.concurrent.FutureTask.run(Unknown Source)
28.08.2023 - 08:47:59 - 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
28.08.2023 - 08:47:59 - 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:331)
28.08.2023 - 08:47:59 - 	at net.minecraft.server.MinecraftServer.redirect$zkb000$onRun(MinecraftServer.java:4682)
28.08.2023 - 08:47:59 - 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
28.08.2023 - 08:47:59 - 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
28.08.2023 - 08:47:59 - 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
28.08.2023 - 08:47:59 - 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
28.08.2023 - 08:47:59 - 	at java.lang.Thread.run(Unknown Source)
28.08.2023 - 08:50:13 - [TAB v3.3.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
28.08.2023 - 08:50:13 - java.lang.NullPointerException: null
28.08.2023 - 08:50:13 - 	at java.util.ArrayList.<init>(Unknown Source)
28.08.2023 - 08:50:13 - 	at me.neznamy.tab.shared.command.DebugCommand.getExtraLines(DebugCommand.java:178)
28.08.2023 - 08:50:13 - 	at me.neznamy.tab.shared.command.TabCommand.<init>(TabCommand.java:44)
28.08.2023 - 08:50:13 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:153)
28.08.2023 - 08:50:13 - 	at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:29)
28.08.2023 - 08:50:13 - 	at me.neznamy.tab.platforms.sponge7.Sponge7TAB.executeCommand(Sponge7TAB.java:67)
28.08.2023 - 08:50:13 - 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
28.08.2023 - 08:50:13 - 	at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355)
28.08.2023 - 08:50:13 - 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360)
28.08.2023 - 08:50:13 - 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665)
28.08.2023 - 08:50:13 - 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
28.08.2023 - 08:50:13 - 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
28.08.2023 - 08:50:13 - 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
28.08.2023 - 08:50:13 - 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
28.08.2023 - 08:50:13 - 	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219)
28.08.2023 - 08:50:13 - 	at net.minecraft.network.PacketThreadUtil$1.redirect$zln000$impl$redirectToPhaseTracker(SourceFile:540)
28.08.2023 - 08:50:13 - 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
28.08.2023 - 08:50:13 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
28.08.2023 - 08:50:13 - 	at java.util.concurrent.FutureTask.run(Unknown Source)
28.08.2023 - 08:50:13 - 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
28.08.2023 - 08:50:13 - 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:331)
28.08.2023 - 08:50:13 - 	at net.minecraft.server.MinecraftServer.redirect$zkb000$onRun(MinecraftServer.java:4682)
28.08.2023 - 08:50:13 - 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
28.08.2023 - 08:50:13 - 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
28.08.2023 - 08:50:13 - 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
28.08.2023 - 08:50:13 - 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
28.08.2023 - 08:50:13 - 	at java.lang.Thread.run(Unknown Source)
28.08.2023 - 08:51:04 - [TAB v3.3.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
28.08.2023 - 08:51:04 - java.lang.NullPointerException: null
28.08.2023 - 08:53:08 - [TAB v3.3.0] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
28.08.2023 - 08:53:08 - java.lang.NullPointerException: null
28.08.2023 - 08:53:08 - 	at java.util.ArrayList.<init>(Unknown Source)
28.08.2023 - 08:53:08 - 	at me.neznamy.tab.shared.command.DebugCommand.getExtraLines(DebugCommand.java:178)
28.08.2023 - 08:53:08 - 	at me.neznamy.tab.shared.command.TabCommand.<init>(TabCommand.java:44)
28.08.2023 - 08:53:08 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:153)
28.08.2023 - 08:53:08 - 	at me.neznamy.tab.platforms.sponge7.Sponge7TAB.onServerStart(Sponge7TAB.java:49)
28.08.2023 - 08:53:08 - 	at org.spongepowered.common.event.listener.GameStartedServerEventListener_Sponge7TAB_onServerStart116.handle(Unknown Source)
28.08.2023 - 08:53:08 - 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)
28.08.2023 - 08:53:08 - 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
28.08.2023 - 08:53:08 - 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
28.08.2023 - 08:53:08 - 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
28.08.2023 - 08:53:08 - 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255)
28.08.2023 - 08:53:08 - 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:363)
28.08.2023 - 08:53:08 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.08.2023 - 08:53:08 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:53:08 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:53:08 - 	at java.lang.reflect.Method.invoke(Unknown Source)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
28.08.2023 - 08:53:08 - 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
28.08.2023 - 08:53:08 - 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
28.08.2023 - 08:53:08 - 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
28.08.2023 - 08:53:08 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.08.2023 - 08:53:08 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:53:08 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
28.08.2023 - 08:53:08 - 	at java.lang.reflect.Method.invoke(Unknown Source)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
28.08.2023 - 08:53:08 - 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
28.08.2023 - 08:53:08 - 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
28.08.2023 - 08:53:08 - 	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
28.08.2023 - 08:53:08 - 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
28.08.2023 - 08:53:08 - 	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
28.08.2023 - 08:53:08 - 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
28.08.2023 - 08:53:08 - 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
28.08.2023 - 08:53:08 - 	at java.lang.Thread.run(Unknown Source)

TAB v3.3.0:
[errors.log](https://github.com/NEZNAMY/TAB/files/12450730/errors.log)

![изображение_2023-08-28_085648602](https://github.com/NEZNAMY/TAB/assets/52006485/de8e6b0c-9a34-411f-866b-33a044e1b808)

TAB v4.0.3
![image](https://github.com/NEZNAMY/TAB/assets/52006485/8522d504-f320-4480-94e4-ebbc96fcff56)

![image](https://github.com/NEZNAMY/TAB/assets/52006485/b68fd5d1-9e31-4b1b-8522-05d7b31fb190)

![image](https://github.com/NEZNAMY/TAB/assets/52006485/2fbc4230-d94b-4437-8a20-42431b298311)

### Steps to reproduce (if known)

Just try to type a tab command or press tab button to see that it is not work

### Additional info

The latest version doesn't load a config files, but TAB v3.3.0 load a config files

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show full server log with TAB 4.0.3.

**Comment by Alisa121212** [comment]
TAB v3.3.0 which generate config files

![image](https://github.com/NEZNAMY/TAB/assets/52006485/8ebadad0-b3ee-4417-88fa-f5cb9bbad98c)

Stil the same problem

**Comment by NEZNAMY** [comment]
Read compatibility page. Did you follow Sponge 7 instructions?

**Comment by Alisa121212** [comment]
I read compatibility page, but it doesn't help

![image](https://github.com/NEZNAMY/TAB/assets/52006485/bddd7db1-169a-4e48-b12a-7c5f48943253)

I do everything that instruction says on TAB-4.0.4-SNAPSHOT for sponge7, but still doesn't work (config didn't create and tab command didn't work too)

![image](https://github.com/NEZNAMY/TAB/assets/52006485/7692eb9b-6f1e-4c45-b8f7-aa5796f628c6)

Commands still don't work

**Comment by NEZNAMY** [comment]
This turned out to be caused by a startup error that you didn't send at all. I have tried it myself to get it and it's fixed now in new build.

**Comment by Alisa121212** [comment]
Okay, thanks

**Comment by Alisa121212** [comment]
I'm so sorry for those dumb questions, but where i should put this?
![image](https://github.com/NEZNAMY/TAB/assets/52006485/a7dbf996-7e38-4bfc-aec7-8f8446759d8f)

Because of TAB have only .class type of file
![image](https://github.com/NEZNAMY/TAB/assets/52006485/400a0ebc-b62d-4d7d-a7fc-df8230423316)

**Comment by NEZNAMY** [comment]
You download the latest build from https://github.com/NEZNAMY/TAB/suites/15557236487/artifacts/887769590 and delete the folders as compatibility page says.

**Comment by Alisa121212** [comment]
Now i get errors
![image](https://github.com/NEZNAMY/TAB/assets/52006485/78e9d1e6-635b-40c8-a173-7a7e9795b6b6)

![image](https://github.com/NEZNAMY/TAB/assets/52006485/011924d1-c407-413f-a428-f98c6b2c17f6)

**Comment by NEZNAMY** [comment]
Delete config and start again.

**Comment by Alisa121212** [comment]
Deleted

![image](https://github.com/NEZNAMY/TAB/assets/52006485/8032f176-bee9-43d4-b584-8cd8159bbeea)

![image](https://github.com/NEZNAMY/TAB/assets/52006485/e6782ecc-6207-4555-bcc2-81ece55618cc)

**Comment by NEZNAMY** [comment]
Upload newly generated config to pastebin and send it.

**Comment by Alisa121212** [comment]
https://pastebin.com/uWhyqyKk

**Comment by NEZNAMY** [comment]
SkinsRestorer?

**Comment by Alisa121212** [comment]
I delete SkinRestorer 

![image](https://github.com/NEZNAMY/TAB/assets/52006485/8c312ea5-f105-4a8d-a381-945b3e1c5555)

![image](https://github.com/NEZNAMY/TAB/assets/52006485/c9f187f2-56ad-49e6-965f-a8be261a147b)

[errors.log](https://github.com/NEZNAMY/TAB/files/12454048/errors.log)

https://pastebin.com/Gjj3Jar7

**Comment by NEZNAMY** [comment]
You keep sending some weird files. Go to `config/tab/config.yml` and copy that one.

**Comment by Alisa121212** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/52006485/bf10f38d-1645-442b-834e-8316cf11b2c9)

**Comment by NEZNAMY** [comment]
Then you have something, maybe a mod, messing with the configuration file system. Remove all mods and only keep TAB, delete the configs and start over. Then add mods one by one until one of them breaks config structure.

**Comment by Alisa121212** [comment]
Okay, thank you so much for the help and spended time!
