### ISSUE TITLE
Nametag

### ISSUE THREAD

**Issue by SheffGx** [NEZNAMY/TAB#1053]
### Server version

Paper 1.16.5

### TAB version

4.0.3

### Describe the bug

annoying bug, plugin works as described until the player leaves his faction to create another one, the TAB plugin must be reloaded for the tag to take effect again, the tab prefix stays the same however, but the tag doesnt it just turns to vanilla tag as shown in the pictures. 
i am using SaberFactions as the factions core and no other plugins like tab or anything to do with nametags, i have essentials and luckperms also

[image](https://github.com/NEZNAMY/TAB/assets/100444348/2cbfdd91-3d39-4eac-af3c-72e28f6e290d)
![image](https://github.com/NEZNAMY/TAB/assets/100444348/f5d341c2-77f9-437f-b6e8-da4274dd2fcf)

### Expected behavior

its supposed to maintain its prefix throughout the whole proccess, but instead it loses the prefix and the plugin must be reloaded to take effect again

### Steps to reproduce

DOWNLOAD MY TAB CONFIG 
[TAB v4.0.3.zip](https://github.com/NEZNAMY/TAB/files/12457331/TAB.v4.0.3.zip)

have both TAB and SaberFactions installed on the server,

create a faction with /f create
disband the faction with /f disband
create a new faction with /f create, then boom the tag is gone like in my screenshots (if its not clear enough pls let me know here or discord 310k)

### Additional info

my discord is 310k, id: 431028332549767178

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by SheffGx** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/100444348/03b29436-c717-4ea8-a386-43721ec493f1)
this is what it looks like when makin a new faction after leaving the old one

**Comment by NEZNAMY** [comment]
Lines 38 and 44 are supposed to be true. Your faction plugin is clearing TAB's nametags.

**Comment by SheffGx** [comment]
Thank you so much i love you ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
