### ISSUE TITLE
Working with TabAPI

### ISSUE THREAD

**Issue by davidegrigioni** [NEZNAMY/TAB#1054]
Also, I tried to search after a Support Discord but couldn't find anything, I need to make a Nametag plugin like this
<img width="190" alt="image" src="https://github.com/NEZNAMY/TAB/assets/65981549/f511c8c7-e14b-4cbe-af1a-2844d62daa82">
I saw the Dev Wiki for Nametag Unlimited mode but It didn't work and I think is a bit outdated too since I used API 4.0.0 and didn't found "getTeamManager", so yeah, how could I get a bit of help here?

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/TabAPI.java#L91

**Comment by davidegrigioni** [comment]
I understand that you don't provide support in github issues but where I can ask support then? I tried with debugging multiple times and the nametags still won't show.
https://paste.learnspigot.com/wonuzomiju.typescript
I still won't get any nametag below my name (in the code is written myCustomLine but with belowname didn't work too), so If you have a better place where to ask help I'll be glad to join

**Comment by NEZNAMY** [comment]
Show output of `/tab debug <player>` and screenshot of you looking at **another** player who is supposed to have extra line but doesn't have.
