### ISSUE TITLE
After changing unlimited name tag mode to true it is not aknowledged

### ISSUE THREAD

**Issue by veryredpp** [NEZNAMY/TAB#1055]
### Server version

Fabric 1.20.1

### TAB version

4.0.3

### Describe the bug

I try to set a below name value and it rejects me even if my ulimited-name-tag mode is true. I have tried reloading

### Expected behavior

it working

### Steps to reproduce

pretty obvious

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Compatibility#supported-features-per-platform
![20230829_023815.jpg](https://github.com/NEZNAMY/TAB/assets/45695833/42df4fdf-8125-41ce-857f-3bc743799086)
