### ISSUE TITLE
Tab menu shows placeholders instead of player name (e.g. "[Player] %essentialsnick%%afk%")

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [NEZNAMY/TAB#1057]
### Server version

Paper 1.20.1

### TAB version

4.0.3

### Describe the bug

1. Tab menu shows placeholders instead of player name (e.g. "[Player] %essentialsnick%%afk%")

Example:
https://gyazo.com/73d432e54bee009c2e77b60cf2c98492

2. Furthermore it also does this in-game above the player:
Example:
https://gyazo.com/808281d65cd3622f3fc5066cf7497d21

Feedback would be appreciated, thank you!

### Expected behavior

I expect it to show the player name and no broken placeholders.

### Steps to reproduce

I have not changed the configuration for quite some time (months or years). So **either** this is an issue with the default config **or** my config was working, I updated the plugin, and the auto-updating of the plugin config failed and I didn't realize this.

### Additional info

latest.log: https://pastebin.com/Fz7k2reu
/plugins:
[18:42:41 INFO]: Server Plugins (14): CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FarmControl, LuckPerms, MyCommand, PlaceholderAPI, ProtocolLib, SuperVanish, TAB, Vault, WorldEdit, WorldGuard

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by PiggiesGoSqueal** [comment]
To update I deleted the config and let it regenerate to experiment (as per the 4th checkbox). It did resolve the issue. I will look into this further.

**Comment by NEZNAMY** [comment]
You don't need to investigate too much, all you need to do is read the changelog.
