### ISSUE TITLE
Can't see our nametag

### ISSUE THREAD

**Issue by trucbidule001** [NEZNAMY/TAB#1059]
### Server version

Ispigot 

### TAB version

4.3.0

### Describe the bug

I can see other player name but I can't see mine.
Example: 

### Expected behavior

The plugin is supposed to show nametags

### Steps to reproduce

Step 1: Install the plugin and restart the server.
Step 2: Upload this files instead of normal config files in /plugins/TAB
[config.zip](https://github.com/NEZNAMY/TAB/files/12489470/config.zip)

### Additional info

This is what I saw about how to configure this feature: https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Scroll down on the page you linked yourself, https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-2---f5-view

**Comment by trucbidule001** [comment]
Thank you, but I see this: 
![image](https://github.com/NEZNAMY/TAB/assets/143750013/1fe9bff3-7fa5-4f2a-bfed-1c534667ea4d)
I see my name 2 times.

**Comment by DrWurzeli** [comment]
Try reading the next line as well. it is there for a reason "When using a modified client, you may end up with double nametags. One of them is the vanilla one and second is using armor stands. Modified clients usually don't respect visibility rule and make nametag visible despite TAB setting it to be invisible."

**Comment by trucbidule001** [comment]
My modified client does not touch anything related to tab. I just tried with official Minecraft Launcher too but I have the same issue. It is possible to show ADMIN name for everyone view and just Color + name for f5 view ?

**Comment by NEZNAMY** [comment]
/tab nametag preview
You were told several times already.

**Comment by NEZNAMY** [comment]
No? How should that even work? You have a vanilla name, which the plugin hides, then armor stands, which can be configured.

**Comment by trucbidule001** [comment]
Alright, thank you for your help. But it would be better to have support that doesn't mock you and is a bit more pleasant. If I need plugins, it's because I don't know how to make them..

**Comment by NEZNAMY** [comment]
This is not support. This is an issue tracker. You did not ask for help. You made a bug report.
