### ISSUE TITLE
Glow not working on bungeecord

### ISSUE THREAD

**Issue by Sikatsu** [NEZNAMY/TAB#106]
**Server version**
git-Paper-90 (MC: 1.15.2)

**Plugin version** ("latest" is not a version)
TAB 2.7.0-pre1

**Describe the bug**
Glow doesn't work, when you use /cmi glow red, the name changes to red, but the glow stays white.

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/5664135/74167390-7a26fe00-4c28-11ea-818c-1ea61cf4f5e8.png)

**Comment by NEZNAMY** [comment]
Because you didn't read wiki.

**Comment by iSilviu-debug** [comment]
For those looking for a solution:
_https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins_
