### ISSUE TITLE
One of the % % things wont work

### ISSUE THREAD

**Issue by That1Gamer** [NEZNAMY/TAB#1061]
### Server version

Paper 1.20.1

### TAB version

4.0.3

### Describe the bug

When I try use %server_uptime% it does not show how long the server has been online for like intended.

### Expected behavior

It is supposed to show the server uptime like 1h 30m 30s

### Steps to reproduce

Put %server_uptime% on the tablist config

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Download https://www.spigotmc.org/resources/placeholderapi.6245/
/papi ecloud download server
/papi reload

**Comment by NEZNAMY** [comment]
No response for a week, assuming user has died and this is not a bug report, just an attempt to get support.
