### ISSUE TITLE
PlaceholderAPI Scoreboard Objectives Placeholder using too much cpu

### ISSUE THREAD

**Issue by mccrafter1** [NEZNAMY/TAB#1063]
### Server version

1.20.1 Purpur

### TAB version

4.0.3

### Evidence

even /tab cpu dont give info (intervals are 10000)
![image](https://github.com/NEZNAMY/TAB/assets/137173374/f35f8231-ae52-4d65-a609-6f5bc1537bd0)
Here is information on console
![image](https://github.com/NEZNAMY/TAB/assets/137173374/3abc2f79-38d8-4eff-88ba-904293b8f2d2)

### Steps to reproduce (if known)

I have almost 80 placeholders they are scores and counting numbers with fake names.
For example:
100 ExampleName
scoreboard adding 100 with command to that fake name and it becomes
200 ExampleName
I cant use vault balance etc. cuz it wants real player.

### Additional info

Are there any approach for fake name and score other than this plugin for tab?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
Run the command several times every 10 seconds until you get a valid output. Also consider updating to latest build from github actions, it has improved cpu tracking information.

> Are there any approach for fake name and score other than this plugin for tab?

I don't understand this question.

**Comment by mccrafter1** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/137173374/30c4edf8-9c06-4707-9312-756e714b17b6)
yes it works better now but performance of placeholder still low can i do refreshing of 80 placeholders like each of them going to refresh one by one each 100ms that means all of them going to refresh total of 8sec and cpu will stay low with this approach?

**Comment by NEZNAMY** [comment]
You already have them refresh every 10000ms, which gives 125ms to each placeholder. Assuming your server does not have 1000 online players, it means the placeholderapi expansion is inefficient and needs an optimization. There is nothing TAB can do about this.

**Comment by mccrafter1** [comment]
thank you for help

**Comment by mccrafter1** [comment]
ty for your help
