### ISSUE TITLE
What repository can I use to make use of TAB's API?

### ISSUE THREAD

**Issue by bergerkiller** [NEZNAMY/TAB#1064]
Unfortunately TAB v4.0.3 completely changed the API, so I'm going to need to write code specifically to support it. I integrated something in my own plugins to hide nametags that the TAB plugin otherwise generates.

What maven repository can I use?

In the past there was [https://repo.kryptonmc.org/#/releases/me/neznamy/tab-api](https://repo.kryptonmc.org/#/releases/me/neznamy/tab-api) but this doesn't go beyond version 4.0.0. Unable to find it anywhere on the WIKI at all, so idk where I even got that one from.

**Comment by NEZNAMY** [comment]
Which function is throwing error as missing when using 4.0.0 api with 4.0.3 release?

**Comment by bergerkiller** [comment]
This commit https://github.com/NEZNAMY/TAB/commit/3eeb025f2380508c8224d4de8f5a0daea50350bd#diff-3a6e39dee5824f23185b35c69cbf9159e434fcbbd9b6ea1d099ffb6c1b7bdd12L89 changes TeamManager into NameTagManager among other things. I use it for the hideNametag/showNametag API.

**Comment by NEZNAMY** [comment]
I opened the commit, cliked "Browse files", opened `build.gradle.kts` and see `    version = "4.0.0-SNAPSHOT"`. This means the change was made during 4.0.0 development, before the release. 

Additionally, I downloaded the 4.0.0 API jar from https://repo.kryptonmc.org/#/releases/me/neznamy/tab-api/4.0.0, and saw the class is already renamed to `NameTagManager`. 

Looking at commit history of https://github.com/NEZNAMY/TAB/commits/master/api, the last breaking change was https://github.com/NEZNAMY/TAB/commit/42f38513398d90d96f799376dba394373e6b03c5 on May 24, 2 weeks before 4.0.0 release.

All of this proves you are not using 4.0.0 API, but an older one.

**Comment by bergerkiller** [comment]
My apologies, I had clicked on the 4.0.3 tag and checked the files out there where I saw a build.gradle version of 4.0.3, so I thought it was missing. I didn't know that that particular commit was published with api 4.0.0 snapshot. I can confirm that checking out 4.0.0 snapshot api has the proper renamed classes.

Thank you for the speedy answer :+1:
