### ISSUE TITLE
Nametag not on the head

### ISSUE THREAD

**Issue by siBalda** [NEZNAMY/TAB#1066]
### Server version

Purpur 1.20.1

### TAB version

4.0.3

### Describe the bug

The name of the player should be on his head, but sometimes it is bugged and the name is not on his head but near him.
![2023-09-07_14 03 26](https://github.com/NEZNAMY/TAB/assets/140272116/0e2160e1-b3da-48b7-ae9a-cee598cca6ec)
![2023-09-07_14 03 16](https://github.com/NEZNAMY/TAB/assets/140272116/05a2ca53-0179-4233-9fa5-bf267f90f0d2)

### Expected behavior

The name of the player should be on his head.

### Steps to reproduce

There aren't specific steps to reproduce.

### Checklist

- [x] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Are you sure you didn't just describe https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-3---position-desync?

**Comment by siBalda** [comment]
I think it's the same, if it is not fixable, I'm sorry.

**Comment by NEZNAMY** [comment]
It is fixable, but this is a server-sided bug and should be fixed in server code, not externally by a plugin that has nothing to do with fixing server bugs.
