### ISSUE TITLE
errors when starting server with tab 

### ISSUE THREAD

**Issue by rafa203gt** [NEZNAMY/TAB#1068]
### Server version

fabric 1.19.2

### TAB version

4.0.3

### Stack trace

[main/ERROR]: Failed to start the minecraft server
--
1810 | java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'tab'!
1811 | at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
1812 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
1813 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
1814 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
1815 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
1816 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.22.jar:?]
1817 | at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
1818 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
1819 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
1820 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
1821 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
1822 | Caused by: java.lang.NoSuchMethodError: 'int net.minecraft.class_6489.method_48020()'
1823 | at me.neznamy.tab.platforms.fabric.FabricTAB.onInitializeServer(FabricTAB.java:34) ~[TAB%20v4.0.3.jar:?]
1824 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
1825 | ... 7 more

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by DrWurzeli** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/54333442/942b00e9-e390-48ff-8a8d-7f94d27280bb)
https://github.com/NEZNAMY/TAB/wiki/Compatibility

**Comment by rafa203gt** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/66626151/026cae62-8a9d-43ca-a333-1c57b22efa5f)
Hi , according to modrinth.com , it says it works from 1.5.1 to 1.20.1.

**Comment by Tanguygab** [comment]
That's because the plugin works from 1.5.1 to 1.20.1 on Spigot, but we can't make a different version filter for Fabric. Either way, you ticked the box regarding the Compatibility page while you clearly didn't. We can't do any more.

**Comment by FReEzZzi** [comment]
Is support for 1.19.2 possible?

**Comment by NEZNAMY** [comment]
You will need some developer to backport it for you.
