### ISSUE TITLE
Spectator fix issue after world change

### ISSUE THREAD

**Issue by Kismalax** [NEZNAMY/TAB#1069]
### Server version

Paper 1.19.2 Build:307

### TAB version

4.0.3

### Describe the bug

When somebody switch to spectator mode, then changes his world while still in spectator mode, everybody in the server can see the spectating player.

### Expected behavior

When _**prevent-spectator-effect**_ is enabled, players never should see spectating staff.

### Steps to reproduce

Config:
_prevent-spectator-effect:
  enabled: true_

Dont give _**tab.spectatorbypass**_ permission to anybody.

1. Switch to spectator mode
2. Switch to an other world, while you still in spectator
3. Others on the server can see your spectating status

### Additional info

When I used TAB 3.3.1 with same config, I didnt experienced any issues with this feature.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=I7NkQsXh7yE).

**Comment by Kismalax** [comment]
Just created a brand new test environment with only theese plugins:
  _Essentials, EssentialsSpawn, LuckPerms, Multiverse-Core, PlaceholderAPI, PlugManX, TAB, Vault_
  
With paper-1.19.2-307, I can reproduce this every time.
I created an other test with paper-1.20.1-176. In this case, everything looks fine, I cant reproduce the issue.
Is Your test environment 1.20.x based?

**Comment by NEZNAMY** [comment]
Tried with Paper 1.19.2 build 307, still works as on the video.

**Comment by Kismalax** [comment]
Reduced the plugin list to: _LuckPerms, Multiverse-Core, PlaceholderAPI, TAB_
My test server is a new server installation, all plugins and the server config is unmodified default config, except the following:

server.properties: online-mode=false
TAB config: enabled prevent-spectator-effect
My "staff" account is OP, and got _mv.bypass.gamemode.world_nether_ permission to avoid unnecessary gamemode change.
Thats all changes I made.

I used _/gamemode spectator_ and _/mv tp world_nether_ commands in the test.
What other information would I provide to support your reproduce?

**Comment by NEZNAMY** [comment]
Could you try latest build from actions?

**Comment by Kismalax** [comment]
Tested it, had the same issue.

**Comment by NEZNAMY** [comment]
When creating a new installation, I somehow became able to reproduce this issue. I don't understand why did it not work before.

After hours of debugging and dealing with multiverse bugs I found this difference in server code:

1.19.2:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/cfdf9c6d-d3fe-4cf3-8dc4-e6f491cc3d46)
1.20.1:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/f62f4896-5881-4741-b066-a04db27254e2)

with 1.19.2 sending gamemode update packet to all players when a player is teleported between worlds using the API (somehow it doesn't call this when using nether portal).

Resending fake gamemode again on world switch to prevent this. Worked fine for me. I don't really have a better solution.

**Comment by Kismalax** [comment]
Last build from actions works for me.
Thank you for your work.
