### ISSUE TITLE
Scoreboard Deaths and Kills Not Displaying

### ISSUE THREAD

**Issue by Hateqble** [NEZNAMY/TAB#1070]
### Server version

Paper 1.20.1

### TAB version

4.0.3

### Describe the bug

Instead of displaying players deaths or kills it's showing the placeholders
%statistic_player_kills%
%statistic_deaths%
and it's only those 2

### Expected behavior

show kills and deaths

### Steps to reproduce

enable scoreboard

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Hateqble** [comment]
it's showing normal players 0

**Comment by Hateqble** [comment]
fixed with Placeholder API
using commands
/papi ecloud download statistic
/papi reload

**Comment by NEZNAMY** [comment]
How is this a TAB bug then?

**Comment by Hateqble** [comment]
I didn't know it was a placeholder thing
