### ISSUE TITLE
Cannot set tabsuffix and tagsuffix to geyser player via command

### ISSUE THREAD

**Issue by liquidman228** [NEZNAMY/TAB#1071]
### Server version

Paper 1.20

### TAB version

4.0.3

### Describe the bug

When I try to use on bedrock player /tab player (player) tabsuffix (some suffix) - it does nothing, but on java player everything works

### Expected behavior

Normal suffix setting on bedrock player

### Steps to reproduce

1. Find some bedrock player
2. Try to set a tabsuffix or tagsuffix via a command
3. Get nothing 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Additional-information#issues-with--in-name ?

**Comment by liquidman228** [comment]
Oh, I apologize, I was writing this at like 4:00 in the morning, so I didn't notice
Yes, my geyser prefix is "."
It works with uuid
