### ISSUE TITLE
tag bug

### ISSUE THREAD

**Issue by Kocimietka7192** [NEZNAMY/TAB#1072]
### Server version

pufferfish-25

### TAB version

4.03

### Describe the bug

while enabled   
unlimited-nametag-mode and customtagname set while using the invisibility pot - the player cannot be seen, but you can see the tag itself

### Expected behavior

tag should not be visible

### Steps to reproduce

1: you set unlimited mode and customtag
2: 2: you activate the invisibility pot on the other player

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://youtu.be/EFsxl_E6suo).

**Comment by NEZNAMY** [comment]
No response for 2 weeks, assuming user has died. Issue could not be reproduced either. Closing this issue, reopen if anything new is available.
