### ISSUE TITLE
Update placeholder only when necessary

### ISSUE THREAD

**Issue by EURedBoy** [NEZNAMY/TAB#1074]
Is there a way to update a determinate placeholder only when there is necessity, maybe when i call placeHolder.update() or other things ?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/placeholder/PlayerPlaceholder.java#L11-L29 ?

**Comment by EURedBoy** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/69308679/9345c3c8-ddf2-4be5-b9a3-dac1bca1ee4a)
I use this api, maybe an old version?

**Comment by NEZNAMY** [comment]
What does the class I sent you look like in that version?

**Comment by EURedBoy** [comment]
nevermind I just had to cast him
![image](https://github.com/NEZNAMY/TAB/assets/69308679/d85b74c1-bce8-4894-9277-0da6c80736cd)

**Comment by NEZNAMY** [comment]
Or use the returned value when registering a placeholder.
So what is the issue here?

**Comment by EURedBoy** [comment]
No issue, i was just asking if there is a method like that, so i can close, thank you :D
