### ISSUE TITLE
PERMISSION sorting type does not work

### ISSUE THREAD

**Issue by IIHaunted** [NEZNAMY/TAB#1076]
### Server version

PurPur 1.18.2

### TAB version

4.0.1

### Describe the bug

I want to sort the tablist by permission, but when I register the rights, the sorting does not work.

### Expected behavior

Sort the tab so that the player with the right to the prefix "ᴀᴅᴍɪɴ" is higher than the others.

### Steps to reproduce

...

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/139511010/742a0099-44b3-46fc-87c2-98edfea64436) - what does my tab look like.
![image](https://github.com/NEZNAMY/TAB/assets/139511010/f697d265-5a46-4647-97a5-f5957d44a9aa) - what I wrote in the configuration

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
I am pretty sure those are not valid permissions, just LuckPerms internals for prefix. If you believe they are valid permissions check output of `/papi parse me %player_has_permission_<your full permission string used in config>%`.

**Comment by IIHaunted** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/139511010/701fdb30-0384-43ba-b55c-28b5abcb4608)

**Comment by NEZNAMY** [comment]
What does `/tab debug <player>` show for sorting note?

**Comment by IIHaunted** [comment]
> What does `/tab debug <player>` show for sorting note? Also 4.0.1 is not the latest version.

![image](https://github.com/NEZNAMY/TAB/assets/139511010/43670f22-de74-4c11-8786-f54b703b5241)

**Comment by NEZNAMY** [comment]
And the other user?

**Comment by IIHaunted** [comment]
Oh, it turns out the second player was with op, I didn't notice. Everything is working, I'm sorry for the trouble

**Comment by IIHaunted** [comment]
problem solved

**Comment by NEZNAMY** [comment]
Considering this bug invalid then.
