### ISSUE TITLE
Unordered TabList

### ISSUE THREAD

**Issue by CoachYT1** [NEZNAMY/TAB#1078]
### Server version

Purpur 1.20.1

### TAB version

4.0.4

### Describe the bug

My tablist is not ordered.
Using /tab reload fixes the orering

### Expected behavior

Tablist should be always ordered

### Steps to reproduce

Purpur 1.20.1
TAB 4.0.4

### Additional info

My plugins:
![immagine](https://github.com/NEZNAMY/TAB/assets/69034647/84c27bfb-9df0-41f9-bc2a-8c381918b35b)

I think it's a compatibility issue, but i can't find what's the plugin causing this issue.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
`  sorting-types: []`
sorting types is empty?

**Comment by CoachYT1** [comment]
I'm using LuckPerms weight for group priority

![immagine](https://github.com/NEZNAMY/TAB/assets/69034647/cccec93d-a173-4393-89f2-6b16a253bca2)

I also tried setting "PLACEHOLDER_HIGH_TO_LOW:%luckperms_highest_group_weight%"

**Comment by CoachYT1** [comment]
https://pastebin.com/pqmeFHen

**Comment by CoachYT1** [comment]
![immagine](https://github.com/NEZNAMY/TAB/assets/69034647/74d51bb4-975e-4c72-9608-099848d8e5ef)
![immagine](https://github.com/NEZNAMY/TAB/assets/69034647/76b2db4f-dd77-49e7-85cc-1976763ed9ad)

**Comment by NEZNAMY** [comment]
Pick a player sorted lower than they should be and show output of `/tab debug <player>`.

**Comment by CoachYT1** [comment]
![immagine](https://github.com/NEZNAMY/TAB/assets/69034647/40dd05d6-56fc-4099-b40a-da2bc240b769)

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/f166328b-702c-44aa-8d2c-44184b58293b)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d700b8fc-6a24-4859-80d4-1d38b69a9c73)

**Comment by CoachYT1** [comment]
Oh... I'm dumb... thanks for the help

**Comment by NEZNAMY** [comment]
We didn't help you. This is not support. This is an issue tracker. We fixed a bug you reported.
