### ISSUE TITLE
I opened the server with a bungee code.  I want to see all players, even if they are on different servers.

### ISSUE THREAD

**Issue by leestar960** [NEZNAMY/TAB#1079]
### Server version

paper 1.20.1

### TAB version

4.0.4

### Describe the bug

I opened the server with a bungee code.

There is a list of servers as below

- lobby
- easy

There are a total of 2 servers, and I want to see all players regardless of which server they are on. I followed the settings listed on the wiki, but
I only see users on the same server?

### Expected behavior

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - <#FFFFFF>&m                                                </#FFFF00>
  - '&e&lTogether Island'
  - ''
  - '&7>> %animation:Welcome%&3 &c%player%&7! &7<<'
  - '&f접속중인 유저 : &f%online%'
  - '&6접속중인 스텝 : &e%staffonline%'
  - ''
  footer:
  - ''
  - '&b디스코드 가입을 권장 합니다.'
  - <#FFFFFF>&m                                                </#FFFF00>
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,mod,helper,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
yellow-number-in-tablist:
  enabled: true
  value: '%ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  server-groups: {}
  spy-servers:
  - lobby
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true

### Steps to reproduce

I placed the tab plugin in the bungee code plugin folder.

I put the Tab Bridge plugin in the Paper Plugin folder.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/66def3fc-1598-4b61-8515-8b11790fa4ae)

This is not how you paste your config, the formatting is all broken.

You say you are using paper, but do you have it on bungeecord?

**Comment by leestar960** [comment]
It's because it's my first time asking a question.

Sorry

I am using Waterfull 1.20 proxy and opening a paper server.

Please tell me how to solve it

**Comment by leestar960** [comment]
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  server-groups: {}
  spy-servers:
  - lobby
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true


이부분만 수정 하면 되는거 아니야 ?

**Comment by NEZNAMY** [comment]
I don't see an immediate issue, so this will require further investigation. Set `debug: true` in config and show console output on plugin load.

**Comment by leestar960** [comment]
![Uploading 캡처.PNG…]()

**Comment by leestar960** [comment]
[](url)

**Comment by leestar960** [comment]
[04:39:00 INFO] [TAB]: [TAB v4.0.3] An error was thrown when executing task
[04:39:00 INFO] [TAB]: java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.ScoreboardDisplay.<init>(byte, java.lang.String)'
[04:39:00 INFO] [TAB]:  at me.neznamy.tab.platforms.bungeecord.BungeeScoreboard.setDisplaySlot(BungeeScoreboard.java:28)
[04:39:00 INFO] [TAB]:  at me.neznamy.tab.shared.features.YellowNumber.onJoin(YellowNumber.java:92)
[04:39:00 INFO] [TAB]:  at me.neznamy.tab.shared.FeatureManager.onJoin(FeatureManager.java:135)
[04:39:00 INFO] [TAB]:  at me.neznamy.tab.shared.platform.EventListener.lambda$serverChange$3(EventListener.java:68)
[04:39:00 INFO] [TAB]:  at me.neznamy.tab.shared.CpuManager.run(CpuManager.java:252)
[04:39:00 INFO] [TAB]:  at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:105)
[04:39:00 INFO] [TAB]:  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:39:00 INFO] [TAB]:  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:39:00 INFO] [TAB]:  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[04:39:00 INFO] [TAB]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:39:00 INFO] [TAB]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:39:00 INFO] [TAB]:  at java.base/java.lang.Thread.run(Thread.java:833)
[04:39:00 INFO] [TAB]: [TAB v4.0.3] Tried to modify non-existing team null for player Ferrero__

**Comment by NEZNAMY** [comment]
Support for 1.20.2 bungeecord was added in 4.0.4 which you claim to be using, but are in fact using 4.0.3.

**Comment by leestar960** [comment]
와! 진짜 고마워 !
