### ISSUE TITLE
BelowName changed to Owner[Name]

### ISSUE THREAD

**Issue by naqibnadzir** [NEZNAMY/TAB#108]
**Server version**
1.14.3

**Plugin version** ("latest" is not a version)
2.6.5

**Describe the bug**
When I set my group to Owner, the belowname of NPC changed from "0 Health" to animated "0 OWNER[1S8]". Info bar also appeared with animated "OWNER[1S8]" eventho I cant find where the setting for info bar. Upon changing group to default, the belowname with animated "0 OWNER[1S8]" stopped and had to do /tab reload to fix it back. I confirmed in animation.yml, there is no animation for OWNER[name].

**How to reproduce**
Promote yourself to become owner rank in your server.

**Expected behavior**
By changing group to owner, NPC below name should stay "0 health". Info bar should not be displayed, or at least, a setting to disable it.

**Actual behavior**
By changing group to owner, NPC below name changed to "0 OWNER[name]". Info bar shows animated "OWNER [name]". 

**Additional info** (errors, screenshots, ...)
![EonF0ciaNp](https://user-images.githubusercontent.com/56784812/74759011-19946280-52b3-11ea-9103-74a688104076.png)

**Comment by NEZNAMY** [comment]
This is vanilla mechanic. Belowname affects all player entities, including fake players from plugins. The text is shared between all players and cannot be personalized. 
Therefore, this is an expected behaviour and the only way to show it on players only is to enable unlimited nametag mode and use belowname from the feature.

**Comment by naqibnadzir** [comment]
Then, how do I disabled this completely? I have disabled the below names but whenever I changed my rank to "OWNER", all NPC below name (which already been disabled) started with the "owner" animation.

**Comment by NEZNAMY** [comment]
Disable belowname feature by setting 
```
belowname:
  enabled: false
```

**Comment by naqibnadzir** [comment]
Hi,

Can you at least help me locate where this coming from? I spent two days to find and I dont see anywhere in the tab that indicates the animation of "Owner[1s8]". 

Here is the video showing the issue: https://drive.google.com/open?id=1lBQQ_CGmAr39ICm9vLNjVNleEDsUbupF

I just want to change it to Health instead of the animation. :(

Here is my configuration: https://drive.google.com/open?id=1tzR7ssJ_auD1LNDjneRMbTyjfFduhwTk

I appreciate your assistance

**Comment by NEZNAMY** [comment]
That's your prefix. It applies for all player entities with that name. Naming your NPCs after you will result on those NPCs getting your prefix too.

**Comment by naqibnadzir** [comment]
Thanks. I managed to find the issue. Its from Additions Plus plugin where it modified the below name of owner by default. I turned it off and now everything back to normal!

Thanks.
