### ISSUE TITLE
[Suggestion] 2 new killer-features!

### ISSUE THREAD

**Issue by ChefMC** [NEZNAMY/TAB#1080]
Hi, you are very talented developer and very experienced in Scoreboard compatibility **as nobody else**, so I want to direct my 2 killer-feature suggestions **to you**:

1. Friends system (placeholder?) like on Shotbow, but with no break of compatilibity with other Scoreboard-around stuff (I think will be better to build this feature up on any existing plugin, which is best of all and has compatibility with Velocity/BungeeCord). Your Friends feature for TAB which is built up on any friends system plugin will add `&9`blue color to nickname only for personal friends of player:
![image](https://github.com/NEZNAMY/TAB/assets/3519015/dc265afc-405d-493e-931a-2661216e04ba)
This is me and my friends (2014-2015 :)
All other players will has their nametag colors as is (not blue).

2. Ability to mark the same way your teammates in competitive mini-games (and not only). Like on TheWalls - you will clearly see your teammates even under the ground and trees/buildings, and they will be colored in color of your team. E.g. in "Greens" team players will see each other highlighted, but players in other teams (e.g. "Red"), will not see players in "Green" team as highlighted.

\* Seeing of semi-transparent Spectators should not be broken.
\* All of these features should work with actual Score-board (meaning visible on right of screen).

Those features are very sensitive to compatibility and custom scoreboards.

**Comment by Tanguygab** [comment]
Feature requests are closed and those ideas are already possible with placeholders.

**Comment by NEZNAMY** [comment]
Your killer feature number 1 can be made as a separate plugin and then offer a PlaceholderAPI placeholder. TAB's purpose is displaying information, not creating it.
Your second killer feature already exists and is called [relational placeholders](https://github.com/NEZNAMY/TAB/wiki/Placeholders#relational-placeholders). All you need to do is use placeholders provided by your minigame plugins. Adding explicit hook into every minigame plugin inside TAB makes no sense at all.
