### ISSUE TITLE
AFK Bug

### ISSUE THREAD

**Issue by Cocoroi** [NEZNAMY/TAB#1081]
### Server version

git-Purpur-2058 (MC: 1.20.1)

### TAB version

4.0.4

### Describe the bug

Hi,
The AFK Suffix is totally broken.
All time when the server (re)start, the tab display %essentials_afk%, instead of AFK for example.
![image](https://github.com/NEZNAMY/TAB/assets/78262052/e0bc3015-a873-44d9-af3d-0c83b3e8d1cf)

### Expected behavior

*

### Steps to reproduce

The plugin break for no reason, so, i don't know how to reproduce the bug.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Do you have essentials and placeholderapi? What does `/papi parse me %essentials_afk%` say?

**Comment by Cocoroi** [comment]
Yeah, i have all these plugins.

And this command says just : %essentials_afk%

**Comment by Tanguygab** [comment]
then you didn't download the Essentials expansion for PAPI

/papi ecloud download Essentials
/papi reload

**Comment by Cocoroi** [comment]
I think it's ok after doing this.
I restart the server and now the tab is good and when i type /papi parse me %essentials_afk%, it says no.
