### ISSUE TITLE
Essencials nick

### ISSUE THREAD

**Issue by Jonesyoff** [NEZNAMY/TAB#1082]
### Server version

Spigot 1.20.1

### TAB version

4.0.4

### Describe the bug

How can i put the Nick of the players have the colors of the essencials /nick

### Expected behavior

I dont know how.

### Steps to reproduce

?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-display-name-from-nickname-plugins

This is an issue tracker, we don't provide support here.
