### ISSUE TITLE
without the existence of its requested objective 'TAB-BelowName'

### ISSUE THREAD

**Issue by Squesly** [NEZNAMY/TAB#1083]
### Server version

Spigot 1.8.8

### TAB version

4.0.4

### Describe the bug

When player was in game player can't see enemy or in team health

BelowName doesn't work and gave me error

### Expected behavior

I'm using Bedwars1058 plugin and turn off all health thing from bedwars plugin
and use from TAB instead but it gave me error and some player can't see ppl health

Its gave me this error
Tried to update score (Unkown_hacker) without the existence of its requested objective 'TAB-BelowName' to player

this is my config:

tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: false
  disable-condition: ''
scoreboard-teams:
  enabled: true
  enable-collision: false
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,manager,senioradmin,admin,mod,helper,screensharer,media,demon,goat,mvp,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: ''
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: ''
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
yellow-number-in-tablist:
  enabled: true
  value: '0%health%'
  disable-condition: '%world%=world'
belowname-objective:
  enabled: true
  number: '%health%'
  text: '&c❤'
  disable-condition: '%world%=world'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Manager
- SeniorAdmin
- Admin
- Mod
- Helper
- ScreenSharer
- Media
- Demon
- Goat
- MVP
- VIP
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: true
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true

  

### Steps to reproduce

1.Join game
2.Wait game start
3.Play game

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
And this is why you don't paste config like that. It cannot be copied at all. You also didn't show any screenshots explaining your issue.

**Comment by Caleston** [comment]
At least Geyser keeps spamming console with: 
`[Geyser player thread-4-7/INFO] [Geyser-BungeeCord]: Tried to update score without the existence of its requested objective 'TAB-BelowName'`

**Comment by NEZNAMY** [comment]
That one comes from unlimited nametags. In that case, you can disable vanilla belowname, since it's not visible anyway. For decimals, use a better placeholder.

**Comment by NEZNAMY** [comment]
Marking this as resolved with the linked commit.
The initial reporter refuses to cooperate and did not provide enough information. The message itself is harmless and the issue explained has most likely nothing to do with this.
Second person is not even using belowname feature and it's not even known if they are up to date and just used someone elses issue to bypass the issue template.
