### ISSUE TITLE
Warnings about sorting on bungeecord

### ISSUE THREAD

**Issue by Truongvv10** [NEZNAMY/TAB#1088]
### Server version

1.20.1

### TAB version

v4.0.5

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/67742370/747100e5-e47f-4e74-b57e-6b9dc9eaa13c)

Updating TAB plugin to latest version v4.0.5. Didn't use to do this

### Expected behavior

No warnings at all. 

### Steps to reproduce

1. Update tab plugin with latest version on **bungeecord**

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Elikill58** [comment]
I have the same issue with some custom placeholders, only since updating TAB

**Comment by ArionOwO** [comment]
i'm also having the same issue on paper 1.20.2 build #217
![Screenshot 2023-10-06 233236](https://github.com/NEZNAMY/TAB/assets/147049235/24d0fe7f-03be-4c88-9ef1-a152611d3db8)

**Comment by NEZNAMY** [comment]
That's because you made a mistake in configuration.

**Comment by ArionOwO** [comment]
Weird, I haven't changed the config at all, it just started happening after I updated to paper 1.20.2

**Comment by ArionOwO** [comment]
![Screenshot 2023-10-08 032006](https://github.com/NEZNAMY/TAB/assets/147049235/0b0fd9fc-6065-460f-a1f5-357fe3b683db)
Even when i change it to luckperm weights it still gives an error, but i also have   - PLACEHOLDER_A_TO_Z:%player% there as well but that one doesn't give an error. i haven't changed the config for months and just started getting an error after updating to 1.20.2 paper and tab 4.0.6

**Comment by NEZNAMY** [comment]
Check /papi list if LP is there.

**Comment by Elikill58** [comment]
Same for me as I said, but on paper 1.20.2. I have a custom placeholder that always return int. I didn't change config or placeholder behavior, and since 4.0.5 I've got this issue

**Comment by NEZNAMY** [comment]
Ia the message sent before or after PAPI says your expansion was registered?
