### ISSUE TITLE
The plugin refuses to run with the kubejs Mod on Mohist 1.20.1.

### ISSUE THREAD

**Issue by Xing-C** [NEZNAMY/TAB#1089]
### Server version

Mohist 1.20.1

### TAB version

4.0.6

### Describe the bug

The plugin refuses to run with the kubejs Mod on Mohist 1.20.1.

[21:41:15 INFO]: [TAB] Enabling TAB v4.0.6
[21:41:15 INFO]: [TAB] A compatibility issue with your server was found. Unless you are running some really weird server software, this is a bug.
[21:41:15 INFO]: [TAB] Disabling TAB v4.0.6

### Expected behavior

Tab should work

### Steps to reproduce

Using Mohist 1.20.1(mohist-1.20.1-457-server.jar) Server
Install the TAB plugin, Install kubejs Mod and its dependent rhino and architecture

kubejs-forge-2001.6.3-build.52.jar
rhino-forge-2001.2.2-build.6.jar
architectury-9.1.12-forge.jar

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/440c1a3b-0f1c-4773-886e-615d2f2c4551)
Are you sure it works without that other mod?

**Comment by Xing-C** [comment]
Yes, everything was fine before installing Kubejs, and the plugin still works when only installing dependent mod

**Comment by NEZNAMY** [comment]
Can you send download links to all of the mods?

**Comment by Xing-C** [comment]
[mods.zip](https://github.com/NEZNAMY/TAB/files/12784707/mods.zip)
this

**Comment by Xing-C** [comment]
https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4774726
https://www.curseforge.com/minecraft/mc-mods/rhino/files/4735056
https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/4663010
 this

**Comment by Xing-C** [comment]
Thank you very much, it was really very prompt
