### ISSUE TITLE
Essentials nick

### ISSUE THREAD

**Issue by iTaeyeonKim** [NEZNAMY/TAB#109]
**Server version**
1.14.4

**Plugin version** ("latest" is not a version)
TAB v2.6.5.jar

How do I actually add to players that have nicknames from essentials plugin to have ~ on tab list?

**Comment by NEZNAMY** [comment]
There's no way currently. Plugin only takes the nickname without ~.

**Comment by iTaeyeonKim** [comment]
Are you planning to add that or not?

This is not request, just asking.

Diky/Thanks

**Comment by NEZNAMY** [comment]
I can add a hidden config option for this.

**Comment by NEZNAMY** [comment]
Check new build on discord.
