### ISSUE TITLE
PLACEHOLDERS ERROR

### ISSUE THREAD

**Issue by Astralymc** [NEZNAMY/TAB#1090]
### Server version

Purpur 1.18.2

### TAB version

4.0.6 

### Describe the bug

The addon works smoothly for a while, then as time goes by and more players join, the placeholders break.
![Captura de pantalla 2023-10-02 142655](https://github.com/NEZNAMY/TAB/assets/146713470/5543366f-16bc-4f31-a644-e02788125aa1)

### Expected behavior

I use the tab plugin for a multiserver, (2 servers simultaneously synchronized with tab bungee and tab bridge)

### Steps to reproduce

When many players enter over time, it breaks.

### Additional info

![Captura de pantalla 2023-10-02 142655](https://github.com/NEZNAMY/TAB/assets/146713470/646a7b19-1ae6-46cf-87b1-17eac288d4c2)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Astralymc** [comment]
The second image is when there is absolutely no one on the server, I kicked them all and they are still on the tab

**Comment by NEZNAMY** [comment]
What does /btab cpu say?

**Comment by Astralymc** [comment]
https://mclo.gs/I9ftCHb
https://mclo.gs/25nX2iW

**Comment by Astralymc** [comment]
I think the errors are from the AstralyStatistics placeholder, but the strange thing is that I have been using it for more than 1 year without problems, it only started happening to me since the last version

**Comment by NEZNAMY** [comment]
The placeholder might be overloading bridge, causing delays. Sadly CPU measuring of bridge is not available, however, there are things you can try:
* Remove the placeholders throwing errors
* Join in and type /btab debug. If it says "Bridge connection: Not connected", bridge is overloaded. Run the command periodically until it says connected to get a rough idea how long it took.

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/01f5a8cb-f08a-4b9a-b6df-52ac93e47905)
It happens very randomly, that is, with any group or person, and if I change the server on which it is synchronized with tab bridge, it is totally different

**Comment by Astralymc** [comment]
https://mclo.gs/CMmAVpc Okay, so it's an overload problem?

**Comment by NEZNAMY** [comment]
Yes. Any idea how long it took to connect? Can you try? Or at least "give up" after enough time?

**Comment by NEZNAMY** [comment]
Also get spark and make a report of all threads and send it.

**Comment by Astralymc** [comment]
Never connected, still offline...
Yes, let me generate the spark profile.

**Comment by Astralymc** [comment]
https://spark.lucko.me/oYZuu8Ab3a

**Comment by NEZNAMY** [comment]
I told you to do all threads, not just the server one.

**Comment by Astralymc** [comment]
https://spark.lucko.me/AZtpQps0rV
Okay sorry, this should be correct, just threads

**Comment by NEZNAMY** [comment]
This is still only server thread.

**Comment by Astralymc** [comment]
Sorry for my ignorance, I don't know much about that, but didn't you want all the threads? I am currently using spark profiler --threads *, I know this is beside the point and you don't have to answer this, but is that so?

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/5b091c0f-9407-428f-9e63-cf4bd89a2ded)
This is what I see when opening your report. It only shows server thread. Changing views to "flat" or "plugins" doesn't show them either. Do they show up when you open the report?

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/4a938cc0-e942-473e-8664-f2f9c6e2b88f)
Not very relevant data, it's still out of sync hahaha

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/110dfd1c-6487-4d46-9890-57462801a498)
Wow, how strange this is, now it doesn't even appear

**Comment by NEZNAMY** [comment]
> ![image](https://user-images.githubusercontent.com/146713470/272070695-db1a5dde-be7e-4838-bb02-c9fc48d14e57.png) I see it this way when using 'Flat'

Correct, it only shows server thread, just like for me.

**Comment by Astralymc** [comment]
What information do you need?

**Comment by NEZNAMY** [comment]
Report of all threads.

**Comment by Astralymc** [comment]
Well, I just asked spark and they just told me that those are all the threads, there are no more threads to show
I don't know what specific threads you're looking for, I could look deeper there.

**Comment by Astralymc** [comment]
I'm going to try deleting those placeholders to see if it works.

**Comment by NEZNAMY** [comment]
> Well, I just asked spark and they just told me that those are all the threads, there are no more threads to show I don't know what specific threads you're looking for, I could look deeper there.

Can I see a screenshot of all threads? Even better, bridge's thread?

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/7fe99342-e764-4d81-80b8-f9573e61f62f)
Yes, the problem is that in the backends there is only the tab-bridge, and in bungee there is no way to use a spark

**Comment by NEZNAMY** [comment]
Clearly says "server thread".

**Comment by Astralymc** [comment]
Okay, tell me what I have to do to be able to give you the threads you want, from spark and reading a little, I'm doing it correctly according to what I read, but it's still wrong and that information is not useful to you, I really want to help you but I don't know how

**Comment by NEZNAMY** [comment]
Unfortunately I don't know how to make spark show all threads. I don't run servers, I don't even play MC. Try asking in their support place.

**Comment by Astralymc** [comment]
https://spark.lucko.me/15C9J2Jujm 
I suppose you are referring to this, but with another spark (Same format that I sent you previously) There is no cpu overhead or so, the tab inside the server does not consume absolutely anything, if there is any problem, it should be the BTAB

**Comment by Astralymc** [comment]
https://mclo.gs/Tl6Gc3b Checking the BUNGEE log, I found this

**Comment by NEZNAMY** [comment]
> https://spark.lucko.me/15C9J2Jujm I suppose you are referring to this, but with another spark (Same format that I sent you previously) There is no cpu overhead or so, the tab inside the server does not consume absolutely anything, if there is any problem, it should be the BTAB

That's heap dump, not what I wanted.



> https://mclo.gs/Tl6Gc3b Checking the BUNGEE log, I found this

Remove TAB to see if it continues. Or, check if it's still broken for 1.20.1 and lower clients.

**Comment by Astralymc** [comment]
Yes, it is definitely a problem for some 1.20.2 users

**Comment by Astralymc** [comment]
It broke again and I already removed the error placeholders

**Comment by NEZNAMY** [comment]
Try asking on spark support place how to create a report with all threads. Also go to placeholderapi-refresh-intervals and change default value to a significantly higher value.

**Comment by Astralymc** [comment]
https://mclo.gs/TwpuBr5 The error that I showed you yesterday is repeated a lot, is it due to using xcord specifically or will the same thing happen to me with other forks? I'm just asking to try and rule out solutions.

**Comment by NEZNAMY** [comment]
4.0.6 changelog says you need a newer bungeecord build for proper 1.20.2 support. Your fork did not update yet. Go back to bungeecord.

**Comment by NEZNAMY** [comment]
I have moved placeholder refreshing to a different thread to prevent them from overloading the entire plugin. You can get the latest build of bridge from https://github.com/NEZNAMY/TAB-Bridge/suites/16839695701/artifacts/961780630. Let me know if you are having any other issues with latest build of bungeecord (not a fork) and that version.

**Comment by c0dingnoobi** [comment]
> Try asking on spark support place how to create a report with all threads.

btw @Astralymc its `/spark profiler start --thread *`

**Comment by Astralymc** [comment]
https://spark.lucko.me/KXxn6CJk0p

**Comment by NEZNAMY** [comment]
Looking good. Are you having issues right now?

**Comment by NEZNAMY** [comment]
With few online players there's no point. Since you are using new bridge build, you should no longer be experiencing any issues, since placeholders will now refresh in a different thread. Making a spark report will still help in case that thread gets overloaded to find out which placeholder is causing it.

**Comment by Astralymc** [comment]
https://spark.lucko.me/gBpcrryl41 It just broke again and here I send you the threads.

**Comment by NEZNAMY** [comment]
Does /btab debug say player is not loaded? Did you get error file in TAB's folder?

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/29171ab7-f9a2-4cd0-bd09-324eb9111ca8)
 Yes, it says it is connected... It does not generate any new records in the error file

**Comment by NEZNAMY** [comment]
So what is the issue now? And no new errors could also mean you reached the 1MB limit.

**Comment by Astralymc** [comment]
I would believe that the error is fixed using /btab reload, when it happened I created spark, it sent it to you and then I reloaded the plugin, if it happens again, I will look with debug

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/f06cbf8e-9fcf-4d56-b35e-f3648337a5be)
![image](https://github.com/NEZNAMY/TAB/assets/146713470/059b3f01-9d65-4d28-b93a-9fed618af97a)
The placeholders were broken again, the groups were disordered and some names were repeated. When using debug, the image I sent you appears.

https://spark.lucko.me/nYgcu9qNGW
Here is a new spark in case it helps you

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/b12d547d-9077-46d5-af4f-a05e7a55af28)
Again, apply the /btab reload command and everything was back to normal

**Comment by NEZNAMY** [comment]
Are you sure you did not get error file in TAB's folder?

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/247f9fc5-3784-4273-93a6-e823c07215bb)
https://mclo.gs/Hzts4TT 
That's what I get in the error yml

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/f8b9cf76-45a6-4ddb-96b0-62d014d37246)
It was like this, however there are no placeholder errors in the folder

**Comment by NEZNAMY** [comment]
Show top part of the debug as well. You could be using a broken bungeecord build.

**Comment by Astralymc** [comment]
Maybe, I'm using xcord, which was updated today

**Comment by Astralymc** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/146713470/a495a5de-bbec-4df1-a138-d5554eb65b58)

**Comment by NEZNAMY** [comment]
Just to stay safe, switch to latest build of bungeecord. Also do the same https://github.com/NEZNAMY/TAB/issues/1092#issuecomment-1746192423.

**Comment by Astralymc** [comment]
https://mclo.gs/uUyfqNc This error happens to me when closing my bungee

**Comment by NEZNAMY** [comment]
Does it happen during runtime as well?

**Comment by NEZNAMY** [comment]
@Astralymc try new build from actions.
