### ISSUE TITLE
Custom Placeholder breaks by /tab reload

### ISSUE THREAD

**Issue by MassiveLag** [NEZNAMY/TAB#1096]
### Server version

1.20.1

### TAB version

v4.0.6

### Describe the bug

When you register custom placeholders via the api. And you want to update something in config. Placeholders will break. This should be keep going even if you reload the plugin.

### Expected behavior

Custom placeholders should stay working when you reload.

### Steps to reproduce

1. Register the placeholder via the api.
2. And allow us to do /tab reload and placeholders stay working.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [-] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This is how the plugin works. Reload reloads everything, including placeholder manager. You can listen to TAB's events and re-register placeholders on reload.

**Comment by MassiveLag** [comment]
Okay, thankyou.
