### ISSUE TITLE
TAB on Spigot side does not override Bungee TAB

### ISSUE THREAD

**Issue by SpinKnight** [NEZNAMY/TAB#1097]
### Server version

1.20

### TAB version

4.0.6

### Describe the bug

When a TAB feature, such as "scoreboard-teams:", is enabled on both the Spigot and Bungee side, the one from the Spigot side does not override the Bungee one.

### Expected behavior

To have TAB features from the Spigot side override Bungee features, as the Spigot side of things will always be more specific.

### Steps to reproduce

Enable "scoreboard-teams" feature on Bungeecord server
Enable "scoreboard-teams" feature on Spigot server
Watch the Bungeecord one override the TAB config on the Spigot server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[Mixed installation](https://github.com/NEZNAMY/TAB/wiki/Installation#mixed-installation) is not supported and this is exactly why. It is not even theoretically possible for a backend plugin to take priority over a proxy plugin, as proxy is closer to the client. You are supposed to disable features you don't want on each installation if you really must use mixed installation for any reason.

**Comment by SpinKnight** [comment]
Well, I'm using a mixed installation as it's not otherwise possible for us to have server-specifics for some features, I believe, such as group priority in TAB.

**Comment by SpinKnight** [comment]
I see that there are "per-server" options for some features, but not for others. Perhaps a solution could be to integrate a "whitelisted-servers" option of sorts into the config, where you could enable certain features on some servers only.

**Comment by SpinKnight** [comment]
Or if it was possible to somehow negate the "|-" condition, in contexts of "disable-condition" options.

**Comment by NEZNAMY** [comment]
You should disable whole features, not just on some servers using a condition.

**Comment by SpinKnight** [comment]
Yeah, but that defeats the point of having TAB on Bungee, though

**Comment by NEZNAMY** [comment]
Then don't install it there. While it tries to provide you with everything backend does, it can't go that deep per-server like per-server installation can. This is not a bug.
