### ISSUE TITLE
Unlimited Prefix/Suffix removes name on Tamed Dogs

### ISSUE THREAD

**Issue by UoibiE** [NEZNAMY/TAB#11]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
2.5.0

**Describe the bug**
Dogs can be named untamed, but not tamed.

**How to reproduce**
Name a dog, tame it, name goes away.

**Expected behavior**
Name is supposed to stay

**Actual behavior**
Name disappears and you can't name it.

**Additional info** (errors, screenshots, ...)
No errors

**Comment by NEZNAMY** [comment]
"fix-pet-names" option not working will be fixed in next version, for now use build from discord server.
