### ISSUE TITLE
Question [How do I sort Ranks in Tab if you're OP?]

### ISSUE THREAD

**Issue by lqsers** [NEZNAMY/TAB#110]
Hey! I have a question, if there are two owners and one admin online then all 3 of them are operators, how so can you organize it making it OWNER -> ADMIN from top to bottom.
Right now it currently looks like this for some reason, (we're all OP).
OWNER
ADMIN
OWNER
ETC.
ETC.

Thanks! Help would be appreciated.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Why-is-player-sorting-not-working-%3F

**Comment by lqsers** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Why-is-player-sorting-not-working-%3F

But does this fix if the User is OP?

**Comment by NEZNAMY** [comment]
Just don't use sorting by permissions but by groups as the wiki page says.
