### ISSUE TITLE
Tab ping

### ISSUE THREAD

**Issue by DrSatoru** [NEZNAMY/TAB#1100]
### Server version

Arclight 1.16.5

### TAB version

4.0.6

### Describe the bug

I tried to add gradient codes into my tablist. At first it worked but after some time i reconigzed that the ping and the player names are stuck together. It is only when you put gradient codes in it. After it the ping is normally on the right side behind the player names. 

When i use gradient codes it looks like this.

![2023-10-07_13 43 37](https://github.com/NEZNAMY/TAB/assets/147250019/c359d027-71d9-4531-bd60-33076e720fcf)

### Expected behavior

Never saw this bug before.

### Steps to reproduce

Use gradient codes for the rank name and the name like that:

prefix.100.§x§c§7§3§e§f§f§l§oO§x§c§e§5§6§f§6§l§ow§x§d§5§6§e§e§c§l§on§x§d§b§8§5§e§3§l§oe§x§e§2§9§d§d§9§l§or §7| §x§c§7§3§e§f§f§l§o

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Rendering is client-sided. Are you sure you don't have any mod or client modification that introduces it?

**Comment by DrSatoru** [comment]
I try to uninstall the tab plugin after that it worked. Tried a other tab plugin too and it worked.

Even when i turn the ping number off it is like that.

**Comment by NEZNAMY** [comment]
Send a screenshot of tablist with "a other tab plugin" with the same configuration.

**Comment by DrSatoru** [comment]
I use technic launcher. And as i already wrote im using "arclight 1.16.5"

**Comment by NEZNAMY** [comment]
Try vanilla client and spigot or paper.

**Comment by DrSatoru** [comment]
Okay thats not helpful than i need to find a way on my own. I dont create a server just because you want a proof that your plugin is the issue or not. 

I tested already a plugin what gives you a scoreboard and tab and it worked. Even if i put your plugin down it works as it should.

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/1c29943e-85d0-4578-9bef-ce6a75eb432b)
Works for me using TLauncher to start MC 1.16.5, Arclight 1.16.5 server and provided prefix (for some reason it has a different color for me).
