### ISSUE TITLE
The Nametag not work properly

### ISSUE THREAD

**Issue by xFedeT** [NEZNAMY/TAB#1101]
### Server version

NachoSpigot 1.8.9

### TAB version

4.0.6

### Describe the bug

When i have a specify role with luckperms with a prefix in name tag is not the same:
![image](https://github.com/NEZNAMY/TAB/assets/76874696/ee7fe7ab-d5ab-4ac0-9581-2826534946ff)

### Expected behavior

The color of the name is supposed to be green

### Steps to reproduce

I don't know i changed the prefix from luckperms and that happened

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by xFedeT** [comment]
I Know why that happend, this is the prefix permission: prefix.999.&8[&cSrAdmin&8] &c
if i remove 2 character to it it works fine

**Comment by xFedeT** [comment]
Can you fix it?

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/7aa5be36-2a1e-4074-b660-f06716bc1d84)
No, I can't edit the minecraft client and then hack all of your players and install my modified copy of the game for them, sorry.
