### ISSUE TITLE
Maybe the plugin can support Minedown color format?

### ISSUE THREAD

**Issue by starmc63** [NEZNAMY/TAB#1102]
### Server version

Folia 1.20.1

### TAB version

4.0.6

### Evidence

For example, when I set my Luckperms prefix to "&#FF0000&Hello" it can be translated to a red "Hello" instead of a red"&Hello", I sincerely hope that my opinion can be adopted

Minedown repo:

https://github.com/Phoenix616/MineDown

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
How is this a performance issue?
On which marketplace is 3.0.2 latest?
What's the point of adding an extra &?

**Comment by starmc63** [comment]
> What I mean is that this is a new color format
https://github.com/Phoenix616/MineDown

**Comment by Tanguygab** [comment]
Why don't you just use #RRGGBB ? moreover the &#RRGGBB format is already supported https://github.com/NEZNAMY/TAB/wiki/How-to-use-RGB-color-codes

**Comment by starmc63** [comment]
I am a noob plugin developer, I sincerely want to know how you can modify the nametag on the player's head on a Folia server, using the NMS method? I have asked many developers, but only you can solve it ,I don't want to use the API you provide, just want to learn how to change the player‘s nametag by myself.

**Comment by Tanguygab** [comment]
TAB doesn't change the player's nametag, it only adds prefixes and suffixes through scoreboard teams which you can do with Bukkit's API https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/scoreboard/Team.html

**Comment by NEZNAMY** [comment]
This is a TAB issue tracker, not Bukkit API help center.

**Comment by starmc63** [comment]
> TAB doesn't change the player's nametag, it only adds prefixes and suffixes through scoreboard teams which you can do with Bukkit's API https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/scoreboard/Team.html

https://github.com/PaperMC/Folia/tree/master   but scoreboard api was broken in folia

**Comment by NEZNAMY** [comment]
And how is that a TAB problem?

**Comment by NEZNAMY** [comment]
- This is not a performance issue
- Feature requests are permanently closed
- It would not be possible to support both old formats and this new one, since the ending & would be ambiguous as whether it's supposed to be ending the color or starting a new one (especially if followed by a character that can represent a color code). Forcing everyone to use a new format because your plugin is broken on folia is just absurd.
