### ISSUE TITLE
Tablist don't update right

### ISSUE THREAD

**Issue by PanetiX** [NEZNAMY/TAB#1103]
### Server version

Paper 1.20.1

### TAB version

4.0.6

### Describe the bug

I have installed TAB Plugin on Proxy (Waterfall)
and TAB Bridge Plugin on every subserver

I use custom tabprefix vor every subserver like:
  Testserver-1:
    _DEFAULT_:
      tabprefix: "&8ʟʙ  %luckperms-suffix%&8 | &7"
  Themepark-1:
    _DEFAULT_:
      tabprefix: "&dꜰᴘ  %luckperms-suffix%&8 | &7"
  Anarchie-1:
    _DEFAULT_:
      tabprefix: "&4ꜱᴠ  %luckperms-suffix%&8 | &7"
  BauServer-1:
    _DEFAULT_:
      tabprefix: "&eʙꜱ  %luckperms-suffix%&8 | &7"
  PlotServer-1:
    _DEFAULT_:
      tabprefix: "&bᴘꜱ  %luckperms-suffix%&8 | &7"
  LiveGames-1:
    _DEFAULT_:
      tabprefix: "&5ʟɢ  %luckperms-suffix%&8 | &7"

The tabprefix shows the different shortcuts vor every subserver in front of the playersuffix (i use this instead of prefix).
Now when a player change the subserver this tabprefix don't update for players on other subservers and for the player self.
Only when i use /btab reload this will be updated.

### Expected behavior

It should update :D

### Steps to reproduce

as i describe in the bug

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Your config is not copypasteable as you didn't put it into code or a paste website. Send a screenshot of the tablist before & after, output of `/btab debug <player>` before & after and your config.yml using a proper paste website.

**Comment by NEZNAMY** [comment]
No response for a week, assuming user has died. Based on provided information it is safe to assume that if this is a bug, it's probably a duplicate of the two already open issues regarding proxy installation, which are scheduled to be fixed in the next release.
