### ISSUE TITLE
The plugin don't enable

### ISSUE THREAD

**Issue by googleWKL** [NEZNAMY/TAB#1105]
### Server version

customs imanity 1.8.8

### TAB version

4.0.6

### Stack trace

[06:20:09 INFO]: [Server Thread] [TAB] Enabling TAB v4.0.6
[06:20:09 INFO]: [Server Thread] [TAB] A compatibility issue with your server was found. Unless you are running some really weird server software, this is a bug.
[06:20:09 INFO]: [Server Thread] [TAB] Disabling TAB v4.0.6

### Steps to reproduce (if known)

Previously we had version 3.1.5 and had no bugs. We updated the tab plugin because of another of our plugins and since then it no longer works.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Can you send link to that server software?

**Comment by NEZNAMY** [comment]
Yeah I'm not paying 50$ for that. Try latest build from actions, I did fix one thing, maybe it will fix this too.

**Comment by googleWKL** [comment]
If it helps we have the sources of the imanity spigot it seems to me.

**Comment by NEZNAMY** [comment]
Jar is enough, I would need someone to test a jar with the compatibility error printed to see what's wrong (it's hidden by default to prevent incompetent users from abusing that stack trace for example in reviews when a new MC version comes out).

**Comment by googleWKL** [comment]
I can send this to you privately, not here.
You can add me on discord google_oke
