### ISSUE TITLE
Will not allow me to change Primary Group

### ISSUE THREAD

**Issue by staceeamyers** [NEZNAMY/TAB#1106]
### Server version

Paper 1.20.1

### TAB version

4.0.6

### Describe the bug

It will not allow me to take Default off the Owner username. It will automatically re-add it to the player no matter what I do. I can delete and clear all the permissions to this person, and it will add default when I do not want the default on it since it is completely breaking the plugin. It works on other servers with 1.20.1 but the fresh server I got it DOES NOT WORK ON... and I have all the same settings and the luckperms from that server connected as well.

### Expected behavior

Should allow me to use the groups prefixes for the tab.

### Steps to reproduce

Fix this.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Ticked all the boxes without reading them?

Show output of `/tan debug <player who you cannot get a prefix off of>`.

**Comment by Tanguygab** [comment]
I think you're looking for this https://luckperms.net/wiki/Default-Groups
LuckPerms prevents you automatically adds back the default group if you don't have one. This isn't an issue with TAB, we only fetch the information given by LP.

**Comment by staceeamyers** [comment]
Nope, it only happens in one server with the luck perms connected. It works on one server and not the other.

**Comment by staceeamyers** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/79070547/d8250298-054c-4bca-af67-08f1474fb2f8)
First server with Primary Group as owner.

![image](https://github.com/NEZNAMY/TAB/assets/79070547/39584bb9-eb17-4f83-8b88-034da7b1696d)
One I'm having problems with. They run the exact same Luck Perms from database.

**Comment by Tanguygab** [comment]
do /lp user <player> info
and /lp info
on the server where you're having issues

**Comment by NEZNAMY** [comment]
What happened? Why did you close the issue?
