### ISSUE TITLE
Multiple Proxys (Bungee Redis)

### ISSUE THREAD

**Issue by MineTommy** [NEZNAMY/TAB#1108]
### Server version

Waterfall 1.20.2 Latest - Backendservers all 1.20.1 Paper

### TAB version

3.0.7

### Describe the bug

We have now an new Proxy with an possible Loadbalancer.
Now i check it out to connect Both Tablists (Bungeeredis Working)

![image](https://github.com/NEZNAMY/TAB/assets/17363482/65eb9884-e34f-4ce0-aaae-9815e44282ef)
This is Proxy 1 (The Player MineTommySpielt is connected to Proxy 2)

![image](https://github.com/NEZNAMY/TAB/assets/17363482/8fe7abd0-c0f4-40a1-ac53-51a5256a3bf2)
This is Proxy 2 (Player MineTommySpielt is connected to this)
From Proxy 2 only the Placeholders of Players on other Servers are Shown correctly

From Proxy 1 Never Seeens the Placeholders of Players from Proxy 2

Database of TAB Plugin is connected

### Expected behavior

Placeholders are dont shown correctly

### Steps to reproduce

Install 2 Proxys and connect it With BungeeRedis.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
/btab debug <broken player> (the entire output)
and /ver TAB-Bridge

**Comment by MineTommy** [comment]
TAB Bridge

![image](https://github.com/NEZNAMY/TAB/assets/17363482/002a758e-5135-4cb3-b516-286e3dc78e3d)
![image](https://github.com/NEZNAMY/TAB/assets/17363482/36eb9228-2a58-46f3-b7c0-67a7930806c5)
![image](https://github.com/NEZNAMY/TAB/assets/17363482/33e749da-92c4-4a99-aa1a-05154dc85ebc)
![image](https://github.com/NEZNAMY/TAB/assets/17363482/be32b440-989d-426b-b0b0-69e102933dd3)

I hope so is readable

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/e2b1d539-5550-4098-aa13-eac13d640d40)
Did you get error file in TAB's folder?

**Comment by MineTommy** [comment]
Hey,

i checked this. I start both Proxys (Delete before the Old error Logs) and Join with Both accounts
No New Error Logs

**Comment by MineTommy** [comment]
I try it out with 2 Proxys and an New Config. Maybe its an Problem on the Config

**Comment by NEZNAMY** [comment]
Are you still experiencing the issue with latest build of TAB from gtihub actions? Also, did you get error file again?

**Comment by MineTommy** [comment]
I try it tomorrow

NEZNAMY ***@***.***> schrieb am Do., 2. Nov. 2023, 18:42:

**Comment by NEZNAMY** [comment]
@MineTommy it's been 2 months. Try latest TAB and Bridge.

**Comment by MineTommy** [comment]
Tested with Latest Version and Works now

Thanks
