### ISSUE TITLE
Vanished players are not hidden from players on a different proxy

### ISSUE THREAD

**Issue by Limeiyy** [NEZNAMY/TAB#1109]
### Server version

Velocity 3.2.0 - Purpur 1.20.1

### TAB version

4.0.7 (Bridge 3.1.7)

### Describe the bug

Like the title says, vanished players are not hidden from other players if they are on different proxies and if the tablist is synchronized among a group of backend servers. Everything works fine if the vanished and an other player are on the same backend server but on different proxies (or the same proxy). Otherwise if the players are not on the same proxy, the player can see the vanished player in the tablist. It also shows the configured vanish-suffix.

### Expected behavior

Vanished players are hidden to everyone without the permission to see them. Also if the players are on different proxies.

### Steps to reproduce

Step 1: Setup at least 2 proxies connected with redisbungee on velocity
Step 2: Setup at least 2 backend servers on purpur with the latest tab-bridge installed
Step 3: One player joins on proxy-1 -> backend-1 and one on proxy-2 -> backend-2
Step 4: Player one enables vanish, player two, who does not have permission to see vanished players, should now still see player one

### Additional info

If all players are on the same proxy, everything works fine.

Output of /btab debug:
```
[tab]: [TAB] Showing debug information
[tab]: >-------------------------------<
[tab]: Server version: [Velocity] Velocity - 3.2.0-SNAPSHOT (git-0d9a097a-b272)
[tab]: Plugin version: 4.0.7
[tab]: Permission plugin: Vault through Bridge
[tab]: Permission group choice logic: Primary group
[tab]: Sorting system: GROUPS
[tab]: Storage type: File
[tab]: >-------------------------------<
```
```
>-------------------------------<
Player: Limeiyy
Bridge connection: Connected
Primary permission group: Founder
Team name: 0A
Sorting note: 
-> Primary group (Founder) is #1 in sorting list.
tabprefix: Disabled
tabsuffix: Disabled
customtabname: Disabled
tagprefix: "%vault_prefix%" (Source: group=_DEFAULT_)
tagsuffix: "%condition:vanish%" (Source: group=_DEFAULT_)
>-------------------------------<
```

Thank you!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Golfing7** [comment]
Which vanish plugin do you use?

**Comment by NEZNAMY** [comment]
I have added vanish status updating, but am not able to test it due to complexity of the setup. Do you have any suggestion how you could test the fix without me having to push a potentially broken commit?

**Comment by Limeiyy** [comment]
Sure, I would test it on the network if you can send me the plugin through discord (“limeiyy“) or somehow else.
