### ISSUE TITLE
Invisible Mobs - Again.

### ISSUE THREAD

**Issue by 61TOfficial** [NEZNAMY/TAB#111]
Invisible villagers, my players say its only the villagers. Have not found another invisible mob yet, we removed tab and they became visible, Added it back, Bam invisible again.

**Comment by NEZNAMY** [comment]
What's your plugin and server version ?

**Comment by 61TOfficial** [comment]
Tab errors does not state anything out of the ordinary besides some errors on being unable to unload the plugin. Im on 1.15.2 paper

**Comment by NEZNAMY** [comment]
No one else reported this issue, i believe it's not caused by TAB.

**Comment by NEZNAMY** [comment]
Also i wouldn't trust your players, you should try it yourself.

**Comment by 61TOfficial** [comment]
hi there, So i did test this myself actually, i enabled the tab and they
went invisible, when i disabled it they re appeared.

>

**Comment by NEZNAMY** [comment]
Try using plugman to unload/load the plugin quickly and see.

**Comment by NEZNAMY** [comment]
Do you still believe TAB is causing it ?

**Comment by 61TOfficial** [comment]
I fixed it so far, I reloaded tab a few times and it seemed to stop
happening.. but I thought so

It's all good now
