### ISSUE TITLE
Teams not reapplying on server switch on FlameCord

### ISSUE THREAD

**Issue by allgamesofficial** [NEZNAMY/TAB#1110]
### Server version

FlameCord

### TAB version

4.0.7

### Describe the bug

When I move from one server to another the player's name appears at the end and it seems to double the line

FlameCord -> https://prnt.sc/X7NWyfmgo8vo

I tried it with another bungeecord and it worked normally, would there be a way to fix it with flamecord?
BungeeCord normally -> https://prnt.sc/nveTVvo1SGnr

### Expected behavior

The problem from what I saw only happens with flamecord, but I really wanted to use flamecord

### Steps to reproduce

enter the server, move to another server with example /server pvp, and then return with /server lobby and that's it, your name will be duplicated

### Additional info

https://prnt.sc/X7NWyfmgo8vo
https://prnt.sc/nveTVvo1SGnr

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by linsaftw** [comment]
Willing to help solving this

**Comment by NEZNAMY** [comment]
Client version? Can you send your config?

**Comment by allgamesofficial** [comment]
Client version 1.8.8
Server Version 1.8.8

Config -> https://hastebin.skyra.pw/xitapovero.nestedtext

**Comment by NEZNAMY** [comment]
Line 18 is supposed to be true. You must have gotten a warn on startup about this.

**Comment by allgamesofficial** [comment]
Before it was true, but I spent hours and hours trying to disable and activate various things to see if it would resolve, but I still activated it and the bug continues -> https://prnt.sc/vbzhXWajIDoY

**Comment by NEZNAMY** [comment]
Is it fixed after /btab reload?

**Comment by allgamesofficial** [comment]
the bug has not been fixed and I do not use the plugin in bungeecord, only in java paperspigot and when I change servers it is buggy as shown in the photo

**Comment by NEZNAMY** [comment]
So reload command does not fix it? Your initial message suggests you use it on FlameCord. Try installing the plugin there with anti-override enabled and check if you got `anti-override.log` file in TAB folder (and if it works).

**Comment by allgamesofficial** [comment]
I have anti-override turned on and it has a bug, but it is not generating the anti-override.log folder

https://prnt.sc/f60Tx77heDY4

**Comment by NEZNAMY** [comment]
Is TAB on the proxy now? I see you got an error log, send it.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/1110#issuecomment-1767756267

**Comment by allgamesofficial** [comment]
Apparently it worked, you need to have the tab plugin on the bungeecord (proxy) and on the server, but tell me how I can use the tab api when it is on the bungeecord (proxy), because before I only set the group and it got the group and put it in the tab

**Comment by allgamesofficial** [comment]
It worked, I put bridge on the server and the tab on bungeecord, thank you very much and before I was using a version that didn't work on bungeecord, so when I went to update the system I found that it still didn't work on bungeecord, but thank you very much, now it's perfect

**Comment by NEZNAMY** [comment]
Had to change the title, because it kept me hella confused every time I saw it.

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=t5jCL7sm0YQ).

**Comment by NEZNAMY** [comment]
@allgamesofficial are you interested in getting this resolved? You didn't respond in 2 weeks.

**Comment by NEZNAMY** [comment]
No response for 2 weeks, assuming user has died. I was not able to reproduce this issue either. Closing.
