### ISSUE TITLE
TAB blank

### ISSUE THREAD

**Issue by StelarMCnt** [NEZNAMY/TAB#1111]
### Server version

1.19.3 (And more that I have tested)

### TAB version

4.0.7

### Describe the bug

Sometimes the tab is set as follows::
![image](https://github.com/NEZNAMY/TAB/assets/139014558/f3f70114-122e-4659-a4d8-69e0571908c4)

### Expected behavior

The tab should be normal and not broken.

### Steps to reproduce

It's random, I didn't know the steps (It has happened to me on several servers)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by StelarMCnt** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/139014558/4eac2c8d-8fb9-45b0-9151-8e44c1c70c3f)

**Comment by Tanguygab** [comment]
send your config

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/f3e0ffbd-814b-40a9-9f8b-5a699fcd977a)
Explain "normal tablist". Provide a screenshot.

**Comment by StelarMCnt** [comment]
Ohh, sorry. Here is my config and a screenshot of normal tablist:
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ''
  - '&a☄ &a&lStelar&f&lMC &f&lNetwork &a☄'
  - '&7IP: stelarmc.es'
  - ''
  - '&fStelarBox: &7[&f%server_online%&7] &8▐  &fGlobal: &7[&f%cloudmultiproxy_total%&7]'
  - ''
  footer:
  - ''
  - '&b✉ &f¿Quieres enterarte de muchas &bnovedades&f? &b✉'
  - '&7Unete a nosotros con: &fdiscord.gg/stelarmc'
  - ''
  - '&eKits &8● &bRangos &8● &cMejoras &8● &dItems'
  - '&7Consulta en &a&ntienda.stelarmc.net'
  - ''
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  disable-condition: '%world%=disabledworld'
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,ekino,admin,diego,developer,jradmin,mod+,mod,trialmod,helper,soporte,builder,famous,twitch,youtube,box,santa,ghost,space,apolo,stelar,galaxy,venus,myt,mars,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    space-between-lines: 0.22
    dynamic-lines:
    - nametag
    - nivel
    - health
    static-lines:
      myCustomLine: 0.66
    disable-condition: '%world%=disabledworld'
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
yellow-number-in-tablist:
  enabled: false
  value: ''
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: true
  number: '%health%'
  text: '&c❤'
  disable-condition: '%world%=world|%world%=tutorial'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /scoreboard
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: true
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard2:
      title: '#00ECFB&lSTELAR#FFDFEA&lBOX &8[&7%server_online%&8]'
      lines:
      - '&r    &7⌚ %server_time_MMM dd, H:mm%&r'
      - ''
      - '&8● &fNombre: #FFE601%player_name%'
      - '&8● &fRango: %vault_rank%'
      - '&8● &fBalance: #FFEB39%vault_eco_balance_formatted% ⛃'
      - ''
      - '&8● &fBajas: #FF3131%statistic_player_kills% 🗡'
      - '&8● &fMuertes: #FF3131%statistic_deaths% ☠'
      - ''
      - '&8● &fB. Minados: #00FFC2%statistic_mine_block% ⛏'
      - '&8● &fH. Jugadas: #A2FF6A%statistic_hours_played%ʜ'
      - ''
      - '&8● &fPiñata: #00D1FF%zvoteparty_votes_recorded%/50'
      - ''
      - '#00ECFB→  stelarmc.es'
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 5000
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- ekino
- Admin
- diego
- developer
- jradmin
- Mod+
- Mod
- trialmod
- Helper
- soporte
- builder
- famous
- twitch
- youtube
- myt
- box
- santa
- ghost
- space
- Apolo
- Stelar
- Galaxy
- Venus
- Mars
- vip
- Default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
use-online-uuid-in-tablist: true
global-playerlist:
  enabled: false
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '&7... y %s jugadores mas'
  empty-slot-ping-value: 0
  layouts:
    default:
      groups:
        players:
          slots:
          - 1-80


![image](https://github.com/NEZNAMY/TAB/assets/139014558/414dd18c-f9eb-4a28-82d4-b6a7c3f43b09)
And this does not happen to me with version 4.0.3

**Comment by NEZNAMY** [comment]
Your config paste is not readable, let alone copy-pasteable. Sounds like the plugin didn't process you due to being overloaded. Show output of `/tab cpu`. Also enable debug option in config and show console output on join when it happens to you.

**Comment by StelarMCnt** [comment]
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ''
  - '&a☄ &a&lStelar&f&lMC &f&lNetwork &a☄'
  - '&7IP: stelarmc.es'
  - ''
  - '&fStelarBox: &7[&f%server_online%&7] &8▐  &fGlobal: &7[&f%cloudmultiproxy_total%&7]'
  - ''
  footer:
  - ''
  - '&b✉ &f¿Quieres enterarte de muchas &bnovedades&f? &b✉'
  - '&7Unete a nosotros con: &fdiscord.gg/stelarmc'
  - ''
  - '&eKits &8● &bRangos &8● &cMejoras &8● &dItems'
  - '&7Consulta en &a&ntienda.stelarmc.net'
  - ''
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  disable-condition: '%world%=disabledworld'
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,ekino,admin,diego,developer,jradmin,mod+,mod,trialmod,helper,soporte,builder,famous,twitch,youtube,box,santa,ghost,space,apolo,stelar,galaxy,venus,myt,mars,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    space-between-lines: 0.22
    dynamic-lines:
    - nametag
    - nivel
    - health
    static-lines:
      myCustomLine: 0.66
    disable-condition: '%world%=disabledworld'
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
yellow-number-in-tablist:
  enabled: false
  value: ''
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: true
  number: '%health%'
  text: '&c❤'
  disable-condition: '%world%=world|%world%=tutorial'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /scoreboard
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: true
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard2:
      title: '#00ECFB&lSTELAR#FFDFEA&lBOX &8[&7%server_online%&8]'
      lines:
      - '&r    &7⌚ %server_time_MMM dd, H:mm%&r'
      - ''
      - '&8● &fNombre: #FFE601%player_name%'
      - '&8● &fRango: %vault_rank%'
      - '&8● &fBalance: #FFEB39%vault_eco_balance_formatted% ⛃'
      - ''
      - '&8● &fBajas: #FF3131%statistic_player_kills% 🗡'
      - '&8● &fMuertes: #FF3131%statistic_deaths% ☠'
      - ''
      - '&8● &fB. Minados: #00FFC2%statistic_mine_block% ⛏'
      - '&8● &fH. Jugadas: #A2FF6A%statistic_hours_played%ʜ'
      - ''
      - '&8● &fPiñata: #00D1FF%zvoteparty_votes_recorded%/50'
      - ''
      - '#00ECFB→  stelarmc.es'
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 5000
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- ekino
- Admin
- diego
- developer
- jradmin
- Mod+
- Mod
- trialmod
- Helper
- soporte
- builder
- famous
- twitch
- youtube
- myt
- box
- santa
- ghost
- space
- Apolo
- Stelar
- Galaxy
- Venus
- Mars
- vip
- Default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
use-online-uuid-in-tablist: true
global-playerlist:
  enabled: false
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '&7... y %s jugadores mas'
  empty-slot-ping-value: 0
  layouts:
    default:
      groups:
        players:
          slots:
          - 1-80

**Comment by NEZNAMY** [comment]
@StelarMCnt I am still waiting for the information I asked for. Are you still interested in this? Aren't you suffering from this issue?

**Comment by VOrlando520** [comment]
Can say I am having this issue as well on your Fabric version. When a player is flagged AFK they lose their prefix until the command /tab reload is ran

**Comment by NEZNAMY** [comment]
That has nothing to do with this issue. You probably disabled anti-override or are outdated or something else unusual. Please don't change the topic of this issue.

**Comment by NEZNAMY** [comment]
No response for a week, assuming has died. Reopen if not.
