### ISSUE TITLE
Players are disappearing.

### ISSUE THREAD

**Issue by ArifErdoganK** [NEZNAMY/TAB#1112]
### Server version

PaperSpigot 1.8.8 #445

### TAB version

4.0.7

### Describe the bug

The feature of displaying all players on the tab list across all servers is not functioning properly. When waiting for a while on the main server or when other players switch between different servers, some players occasionally disappear from the tab list. When transitioning to a different server or returning to the same server, the missing players reappear.

### Expected behavior

There is no issue in the configuration settings.

### Steps to reproduce

Step 1: To activate the global-playerlist feature.
Step 2: To link 8 servers together.
Step 3: Players on the servers should switch between servers, and during this process, one person on the main server should check the tab list a few minutes later. This person should also wait on the main server while other players switch between servers.

### Additional info

![tab](https://github.com/NEZNAMY/TAB/assets/47728022/a4da6bf7-aea7-4587-ac0b-484d4cdf72de)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Global playerlist is a proxy-only feature, it won't work on paper.

**Comment by NEZNAMY** [comment]
Well you said paper. What's your game version?

**Comment by ArifErdoganK** [comment]
The latest travertine version. XCord.

**Comment by NEZNAMY** [comment]
Are you able to reproduce it using a free proxy, so I can try it myself?

**Comment by ArifErdoganK** [comment]
This issue continues in Velocity 3.2.0 SNAPSHOT 276 as well.
My config.yml, which I use, is as follows.
```
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - '&f  &b&l&m---&8&l&m[ &f       &b&lᄽ &6&lM U Z &f&lC R A F T &b&lᄿ    &8&l&m ]&b&l&m---&f '
  - '&e&lHER ZAMAN EN IYIYE!'
  - '&b&l1.8 - 1.20'
  - ''
  - '&e&lFaction'
  - '&a&l%math_{bungee_Faction Merkez}+{bungee_Faction Klan}+{bungee_Faction Hammadde}+{bungee_Faction Arena}+{bungee_Faction Arsa}+{bungee_Faction Boss}+{bungee_Faction Duello}+{bungee_Faction Event}% Çevrimiçi'
  - '&b'
  footer:
  - '&4'
  - '&eIP: &aMC.MUZCRAFT.COM'
  - '&eWebsite: &aWWW.MUZCRAFT.COM'
  - '&4'
  - '&eŞu anda &aFaction&e''da &a%server_name% &esunucusuna bağlısınız.'
  - '&eSunucu performansı &a%server_tps_1% TPS&e. Pinginiz &a%player_ping%&e.'
  disable-condition: '%server%=SkyBlock|%server%=cheat'
  per-world:
    Faction Klan;Faction Hammadde;Faction Arena;Faction Arsa;Faction Boss;Faction Duello;Faction Event:
      header:
      - '&f  &b&l&m---&8&l&m[ &f       &b&lᄽ &6&lM U Z &f&lC R A F T &b&lᄿ    &8&l&m]&b&l&m---&f '
      - '&e&lHER ZAMAN EN IYIYE!'
      - '&b&l1.8 - 1.20'
      - ''
      - '&e&lFaction'
      - '&a&l%math_{bungee_Faction Merkez}+{bungee_Faction Klan}+{bungee_Faction Hammadde}+{bungee_Faction
        Arena}+{bungee_Faction Arsa}+{bungee_Faction Boss}+{bungee_Faction Duello}+{bungee_Faction
        Event}% Çevrimiçi'
      - '&b'
      footer:
      - '&4'
      - '&eIP: &aMC.MUZCRAFT.COM'
      - '&eWebsite: &aWWW.MUZCRAFT.COM'
      - '&4'
      - '&eŞu anda &aFaction&e''da &a%server_name% &esunucusuna bağlısınız.'
      - '&eSunucu performansı &a%server_tps_1% TPS&e. Pinginiz &a%player_ping%&e.'
    lobi:
      header:
      - '&f  &b&l&m---&8&l&m[ &f       &b&lᄽ &6&lM U Z &f&lC R A F T &b&lᄿ    &8&l&m]&b&l&m---&f '
      - '&e&lHER ZAMAN EN IYIYE!'
      - '&b&l1.8 - 1.20'
      - ''
      - '&a&l%online% Çevrimiçi'
      - '&b'
      footer:
      - '&4'
      - '&eIP: &aMC.MUZCRAFT.COM'
      - '&eWebsite: &aWWW.MUZCRAFT.COM'
      - '&4'
    clobi:
      header:
      - '&f  &b&l&m---&8&l&m[ &f       &b&lᄽ &6&lM U Z &f&lC R A F T &b&lᄿ    &8&l&m]&b&l&m---&f '
      - '&e&lHER ZAMAN EN IYIYE!'
      - '&b&l1.8 - 1.20'
      - ''
      - '&a&l%online% Çevrimiçi'
      - '&b'
      footer:
      - '&4'
      - '&aT &etuşu ile klavyeyi kullanabilirsiniz.'
      - '&eKayıt olmak için &a/kaydol şifre tekrar-şifre &eyazınız.'
      - '&eGiriş yapmak için &a/giriş şifre &eyazınız.'
      - '&f'
      - '&eŞifrenizi mi unuttunuz?'
      - '&awww.muzcraft.com/sifremi-unuttum'
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%server%=SkyBlock|%server%=clobi|%server%=lobi|%server%=cheat'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,mod,helper,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%server%=SkyBlock|%server%=clobi|%server%=lobi|%server%=cheat'
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
yellow-number-in-tablist:
  enabled: true
  value: '%ping%'
  disable-condition: '%server%=SkyBlock|%server%=clobi|%server%=lobi|%server%=cheat'
belowname-objective:
  enabled: true
  number: '%player_health%'
  text: '&4❦'
  disable-condition: '%server%=SkyBlock|%server%=Faction Event|%server%=Faction Arena|%server%=Faction Duello|%server%=cheat|%server%=lobi|%server%=clobi'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 1
  delay-on-join-milliseconds: 10
  respect-other-plugins: true
  scoreboards:
    a1:
      display-condition: '%server%=Faction Boss|%server%=Faction Arsa|%server%=Faction Hammadde|%server%=Faction Klan'
      title: '&b&lᄽ&6&lM&b&lᄿ'
      lines:
      - '  &7%server_time_dd.MM.yy HH:mm%'
      - ' '
      - '&6&lBilgi'
      - ' &fRütbe &a%luckperms_primary_group_name%'
      - ' &fPara &a%vault_eco_balance_formatted%'
      - ' &fKredi &a%leaderos_kredi%'
      - ' &fK/D &a%statz_players_killed%/%statz_deaths%'
      - ' &fPing &a%player_ping%'
      - ' '
      - '&6&lKlan Bilgi'
      - ' &fKlan &e%uclans_hasclan_formated%'
      - ' &fPuan &e%uclans_points%'
      - ' &fK/D &e%uclans_clan_kills%/%uclans_clan_deaths%'
      - ' '
      - '&fmc.muzcraft.com'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%server_name%':
    'Faction Merkez': 'Merkez'
    'Faction Arsa': 'Arsa'
    'Faction Arena': 'Arena'
    'Faction Boss': 'Boss'
    'Faction Duello': 'Düello'
    'Faction Event': 'Etkinlik'
    'Faction Hammadde': 'Hammadde'
  '%playtime_is_afk%':
    'True': '&cAFK'
    'False': '&a%server_name%'
  '%jobsr_user_points_fixed%':
    '%jobsr_user_points_fixed%': '0'
  '%skript_sync_grvp::{player}%':
    '%skript_sync_grvp::{player}%': '0'
  '%skript_sync_bssp::{player}%':
    '%skript_sync_bssp::{player}%': '0'
  '%luckperms_primary_group_name%':
    '%luckperms_primary_group_name%': '0'
  '%vault_eco_balance_formatted%':
    '%vault_eco_balance_formatted%': '0'
  '%leaderos_kredi%':
    '%leaderos_kredi%': '0'
  '%player_ping%':
    '%player_ping%': '0'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- kurucu
- yonetici
- moderator
- yetkili
- stajyeryetkili
- faction_muzvip
- altin_katil
- altin_madenci
- altin_avci
- altin_balikci
- altin_oyuncu
- gumus_katil
- gumus_madenci
- gumus_avci
- gumus_balikci
- gumus_oyuncu
- bronz_katil
- bronz_madenci
- bronz_avci
- bronz_balikci
- bronz_oyuncu
- faction_kingvip
- faction_ultravip
- faction_megavip
- faction_clasvip
- katledici
- korkusuz
- acimasiz
- efsane
- imparator
- kral
- kahraman
- asil
- soylu
- ustad
- usta
- uzman
- tecrubeli
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: true
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    Faction:
    - Faction Klan
    - Faction Hammadde
    - Faction Arena
    - Faction Arsa
    - Faction Boss
    - Faction Duello
    - Faction Event
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
```

**Comment by ArifErdoganK** [comment]
Error.logs
```
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     kamil666   ï¿½)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     TheVoid   $)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     st1volec    )
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     ZoxyTR   ?)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     	ElderMitu   6)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     xelnox   )
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     Legitadam02   ^)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     Wednesday_Addams   ï¿½)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     Voiday   )
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     Emindmr   !)
20.10.2023 - 18:40:49 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= PacketPlayOutScoreboardScore TAB-YellowNumber     lokyZen   %)
20.10.2023 - 18:40:50 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= 	Expansion placeholder_animation:muzvip2 &8á„½&6MV&8á„¿ &5)
20.10.2023 - 18:40:50 - [TAB v4.0.6] Skipped plugin message send to AYDINAKBAS, because player is notconnected to any server (message= 	Expansion placeholder_animation:muzvip &8á„½&6MV&8á„¿ &5)
```

**Comment by NEZNAMY** [comment]
Why does TAB v4.0.7 say 4.0.6 in error log?

**Comment by ArifErdoganK** [comment]
> Why does TAB v4.0.7 say 4.0.6 in error log? But it's not related to this issue anyway.

How can I help you solve this issue? I'm currently using version 4.0.6 of TAB. I can upgrade to 4.0.7 if you want, but the problem will likely persist because it was ongoing in previous subversions, and you haven't mentioned any fixes in the 4.0.7 update.

**Comment by NEZNAMY** [comment]
4.0.7 changelog clearly says it has big fixes for bungeecord, which you were using. It never hurts to update, as some of the internal changes may fix issues on velocity as well. I don't know why would you intentionally stay outdated when opening a bug report and even intentionally lie and say you are using latest version while you are not.

**Comment by ArifErdoganK** [comment]
> 4.0.7 changelog clearly says it has big fixes for bungeecord, which you were using. It never hurts to update, as some of the internal changes may fix issues on velocity as well. I don't know why would you intentionally stay outdated when opening a bug report and even intentionally lie and say you are using latest version while you are not.

You're right. The error continues to occur.
error.logs:
```
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to rolax0, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam EA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to seysizk1llua, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam EA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to Wednesday_Addams, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam EA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to saribero, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam EA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to Oncellibrahim, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam EA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to seysizk1llua, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam NA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to saribero, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam NA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to Oncellibrahim, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam NA       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to Clkasl1716, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam NB       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to saribero, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam NB       )
22.10.2023 - 08:05:20 - [TAB v4.0.7] Skipped plugin message send to Oncellibrahim, because player is notconnected to any server (message= PacketPlayOutScoreboardTeam NB       )
```

The problem of when you teleport from one server to another while being on the move in the global player list, the players on the server you were on before teleporting cannot see you on the tab continues.

**Comment by ArifErdoganK** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/47728022/3521abdd-31c7-4278-9a34-96fc8a0c193b)
After the 4.0.7 update, the display of the number of players on other servers using the math placeholder is malfunctioning. While this value is correct on the central server, it shows as 0 on the other servers.

```
    FactionKlan;FactionHammadde;FactionArena;FactionArsa;FactionBoss;FactionDuello;FactionEvent:
      header:
      - '&f  &b&l&m---&8&l&m[ &f       &b&lᄽ &6&lM U Z &f&lC R A F T &b&lᄿ    &8&l&m]&b&l&m---&f '
      - '&e&lHER ZAMAN EN IYIYE!'
      - '&b&l1.8 - 1.20'
      - ''
      - '&e&lFaction'
      - '&a&l%math_{bungee_FactionMerkez}+{bungee_FactionKlan}+{bungee_FactionHammadde}+{bungee_FactionArena}+{bungee_FactionArsa}+{bungee_FactionBoss}+{bungee_FactionDuello}+{bungee_FactionEvent}% Çevrimiçi'
      - '&b'
      footer:
      - '&4'
      - '&eIP: &aMC.MUZCRAFT.COM'
      - '&eWebsite: &aWWW.MUZCRAFT.COM'
      - '&4'
      - '&eŞu anda &aFaction&e''da &a%server_name% &esunucusuna bağlısınız.'
      - '&eSunucu performansı &a%server_tps_1% TPS&e. Pinginiz &a%player_ping%&e.'
```
If you're wondering why the server names have changed, it may be due to the fact that they were separated by spaces, so I updated them in this way.

**Comment by ArifErdoganK** [comment]
After the 4.0.7 update, the display of the number of players on other servers using the math placeholder is malfunctioning. While this value is correct on the central server, it shows as 0 on the other servers.

![image](https://github.com/NEZNAMY/TAB/assets/47728022/0b95c4a1-855c-4853-8b9c-04ec702f62ba)


```
    FactionKlan;FactionHammadde;FactionArena;FactionArsa;FactionBoss;FactionDuello;FactionEvent:
      header:
      - '&f  &b&l&m---&8&l&m[ &f       &b&lᄽ &6&lM U Z &f&lC R A F T &b&lᄿ    &8&l&m]&b&l&m---&f '
      - '&e&lHER ZAMAN EN IYIYE!'
      - '&b&l1.8 - 1.20'
      - ''
      - '&e&lFaction'
      - '&a&l%math_{bungee_FactionMerkez}+{bungee_FactionKlan}+{bungee_FactionHammadde}+{bungee_FactionArena}+{bungee_FactionArsa}+{bungee_FactionBoss}+{bungee_FactionDuello}+{bungee_FactionEvent}% Çevrimiçi'
      - '&b'
      footer:
      - '&4'
      - '&eIP: &aMC.MUZCRAFT.COM'
      - '&eWebsite: &aWWW.MUZCRAFT.COM'
      - '&4'
      - '&eŞu anda &aFaction&e''da &a%server_name% &esunucusuna bağlısınız.'
      - '&eSunucu performansı &a%server_tps_1% TPS&e. Pinginiz &a%player_ping%&e.'
```

**Comment by NEZNAMY** [comment]
@ArifErdoganK try latest build from github actions.

**Comment by ArifErdoganK** [comment]
> @ArifErdoganK try latest build from github actions.

If you're talking about the TAB, I'm already using the latest version. The latest version on GitHub is 4.0.7, which was released two weeks ago.

**Comment by NEZNAMY** [comment]
That's why I said actions. Whatever. Here's direct download link https://github.com/NEZNAMY/TAB/suites/17701704892/artifacts/1013171924

**Comment by ArifErdoganK** [comment]
> That's why I said actions. Whatever. Here's direct download link https://github.com/NEZNAMY/TAB/suites/17701704892/artifacts/1013171924

I have tested the latest version, TAB-4.0.8-SNAPSHOT.jar, with the latest version of velocity-3.2.0-SNAPSHOT-286.jar, and the issue still persists.

**Comment by ArifErdoganK** [comment]
> That's why I said actions. Whatever. Here's direct download link https://github.com/NEZNAMY/TAB/suites/17701704892/artifacts/1013171924

I've been waiting for you for 5 days, is there any progress?

**Comment by NEZNAMY** [comment]
No, I wasn't able to reproduce the issue yet. I don't run a public server with players where I could experience it myself. I have never used this plugin on any server I'd own. I don't even play minecraft. I don't personally know anyone using the plugin. I'm not even getting paid. I don't even know why am I doing all this, yet I still am. If you believe the quality of service you didn't even pay for is poor, you are welcome to switch to any other plugin. I am not preventing anyone from doing so.

**Comment by ArifErdoganK** [comment]
> No, I wasn't able to reproduce the issue yet. I don't run a public server with players where I could experience it myself. I have never used this plugin on any server I'd own. I don't even play minecraft. I don't personally know anyone using the plugin. I'm not even getting paid. I don't even know why am I doing all this, yet I still am. If you believe the quality of service you didn't even pay for is poor, you are welcome to switch to any other plugin. I am not preventing anyone from doing so.

You are a very strange person.

**Comment by ArifErdoganK** [comment]
I don't care if you make a paid plugin free. A paid service should deliver the promised features without issues. Arguing with me here won't justify your actions. You can try making the plugin paid again and providing support properly.

https://prnt.sc/GDU2uR2bLZKs

**Comment by NEZNAMY** [comment]
Then why are you not on the discord? Send your BBB profile link, I will refund you.


> You are a very strange person.
Yes, it's called "I don't lie". This is actually what most developers think, they just don't tell you to make people feel like their plugins are still maintained while they are not.

**Comment by ArifErdoganK** [comment]
> I have tried to reproduce this issue again today, with the same result. I recorded it, you can find the video [here](https://www.youtube.com/watch?v=xdzyu8kjgGw). I added in some bots and kept switching servers myself, as well as sending other players using Velocity's new /send command, with no success of reproducing it. Using latest build of both TAB and Velocity.

I don't want a refund because your plugin is similar and I need it. I can join Discord. This issue may not be related to you because it occurs when a player quickly uses a command to teleport to another server while the player is in motion. The player should be on your server before they teleport. Thank you for your efforts, I would like to assist you in getting this done correctly.

**Comment by NEZNAMY** [comment]
Moving in game cannot be related to being missing from tablist. Those are completely different unrelated things. I will need a reliable way to reproduce it.

**Comment by ArifErdoganK** [comment]
I understand. I will wait for news from you.

**Comment by NEZNAMY** [comment]
I don't have enough reliable information to make progress on this.

**Comment by ArifErdoganK** [comment]
Alright, then I will wait for you to gather information.

**Comment by NEZNAMY** [comment]
Are the missing players on the same server as you?

**Comment by ArifErdoganK** [comment]
> Are the missing players on the same server as you?

No, when they switch to a different server from the one I am on, they rarely disappear from the tab. I have determined that the issue is due to an incompatibility with the Jobs plugin, which might be useful to you. I have currently resolved the issue by downgrading the old Jobs 4.17.2 to the required CMILib plugin version 1.0.2.0, but unfortunately, I won't be able to benefit from the updates of the Jobs plugin.

**Comment by NEZNAMY** [comment]
Sounds like jobs plugin bug to me then. Can you send link to it? And which version is broken and which isn't?

**Comment by NEZNAMY** [comment]
@ArifErdoganK did you forget about this issue? Can you try with latest version of TAB?

**Comment by NEZNAMY** [comment]
No response for 2 months, assuming user has died. 
Reopen if interested.

**Comment by ZorudaRinku** [comment]
@NEZNAMY I'm experiencing this issue on 4.1.2
![image](https://github.com/NEZNAMY/TAB/assets/13283879/a6be367c-eb8f-47ab-ae04-8957f2bd4b09)

```
13.04.2024` - 21:56:11 - [TAB v4.1.2] Skipped plugin message send to Greek32, because player is not connected to any server (message= 	Expansion "placeholder_animation:MyAnimation1 &3---&d-&3-----------)
13.04.2024 - 21:56:12 - [TAB v4.1.2] Skipped plugin message send to Greek32, because player is not connected to any server (message= 	Expansion "placeholder_animation:MyAnimation1 &3--&d-&3------------)
13.04.2024 - 21:56:12 - [TAB v4.1.2] Skipped plugin message send to Greek32, because player is not connected to any server (message= 	Expansion "placeholder_animation:MyAnimation1 &3-&d-&3-------------)
```

Proxy server:
velocity-3.3.0-SNAPSHOT-375

Downstream Server:
This server is running Paper version git-Paper-477 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 1207162)
You are 7 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-446 (MC: 1.20.4)

**Comment by NEZNAMY** [comment]
I will need steps to reproduce. It may also be caused by configuration that makes the player not shown on purpose.

**Comment by ArifErdoganK** [comment]
> I will need steps to reproduce. It may also be caused by configuration that makes the player not shown on purpose.

The configuration settings are correct.

The issue occurs when I update the CMILib plugin from version 1.0.2.2 to later versions. You can reproduce the issue by testing with the latest version of CMILib and the TAB plugin on two servers. The problem is that when a player teleports directly from one server to another, they disappear from the TAB list.

**Comment by NEZNAMY** [comment]
If the issue occurs only with CMILib, it sounds like a bug in that plugin.
