### ISSUE TITLE
Memory Leak, (severe, keeps world objects)

### ISSUE THREAD

**Issue by ItzZisker** [NEZNAMY/TAB#1113]
### Server version
1.8.8
### TAB version
4.0.6
### Heap dump
I can't upload heapdump, but here are reference paths to TabPlayer object:
![image](https://github.com/NEZNAMY/TAB/assets/68909399/b663079a-72df-4dee-8e9a-3ea6aeae2efe)
### Uncleared object(s)
TabPlayers that are holding EntityPlayer which holds WorldServer and world stays in memory
### Additional info
Server was whitelisted and there was no players while capturing heapdump, this happened when i upgraded tab from v3.2.2 to v4.0.6
### Checklist
- [ ] I am running latest version of the plugin
- [ ] I have included download link of my heap dump
- [ ] I ticked all of the boxes without actually reading them
- [ ] I have explained what I believe is wrong with the heap dump

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/fbad68ec-9c1e-4069-9ca1-be20b0413db7)
No you didn't and the screenshot do not give me enough information.

![image](https://github.com/NEZNAMY/TAB/assets/6338394/1901d5ad-458b-4bf5-856c-8a789435aeb0)
?

**Comment by ItzZisker** [comment]
I can't upload the heapdump due to security reasons, but I just wanted to report that happened just after about 4 5 hours server running, not sure why, but if you want more information about heapdump, you can ask and i will send for you

**Comment by NEZNAMY** [comment]
Yes, I need the full path from GC roots to the player object(s) that should have been cleared. Also where is 4.0.6 latest?

**Comment by ItzZisker** [comment]
![Uploading Screenshot_20231019_193828.png…]()

**Comment by NEZNAMY** [comment]
Were 0 players online at that time? Remove the bedwars plugins and try again.

**Comment by ItzZisker** [comment]
Bedwars is fine, MemoryAnalyzer doesn't flag any stuff on bedwars plugin, It just happened right after the TAB update, however if you feel unsure, here is all I do with tab api on bedwars:

```java
public final class TABHookModule_v4_0_2 implements TABHookModule {

    private final TabAPI api = TabAPI.getInstance();

    @Override
    public String getTeamNameOr(Player player, String default_) {
        TabPlayer tabPlayer = api.getPlayer(player.getUniqueId());

        if (tabPlayer != null) {
            SortingManager mgr = api.getSortingManager();
            return mgr != null ? mgr.getOriginalTeamName(tabPlayer) : default_;
        } else {
            return default_;
        }
    }
}```

**Comment by NEZNAMY** [comment]
Did you get error file in TAB's folder?

**Comment by ItzZisker** [comment]
I checked both placeholder-errors.log and errors.log, however there were no "new" errors.
I mean, i found errors from 03-05-2023 which is quite old, and yes i scrolled all the way to the bottom, there were no new errors.

**Comment by NEZNAMY** [comment]
Are you sure it's not due to [1MB limit](https://github.com/NEZNAMY/TAB/wiki/Error-logging#about)?

**Comment by ItzZisker** [comment]
Yes the file sizes was almost 1MB, so I cleared them now.

**Comment by NEZNAMY** [comment]
@ItzZisker it's been a week, are you going to provide any information I can work with? Ideally the full heap dump when 0 players are connected.

**Comment by NEZNAMY** [comment]
No response for 2 weeks, assuming user has died.
