### ISSUE TITLE
Fabric 1.20.2: %world% is replaced by "N/A"

### ISSUE THREAD

**Issue by ruattd** [NEZNAMY/TAB#1115]
### Server version

1.20.2 with Fabric 0.14.23

### TAB version

4.0.7

### Describe the bug

Placeholder `%world%` is replaced by "N/A"

Screenshot:
![image](https://github.com/NEZNAMY/TAB/assets/61044187/7d2367f4-2ac6-4927-a073-46e7e6483ce5)

### Expected behavior

Show "Overworld"

### Steps to reproduce

Add placeholder `%world%` to config file

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
World name is not available on Fabric. It does not have any reasonable way to get name of world.

**Comment by NEZNAMY** [comment]
Added in the hard way. It will show `world`, `world_nether` and `world_the_end`, just like on Bukkit.

**Comment by ruattd** [comment]
@NEZNAMY  I'm sorry but just saw you edit.

I just want to use per-world config (to define a color for each dimension), but it was not working on Fabric, that's when I discovered `%world%` didn't work.

**Comment by NEZNAMY** [comment]
I already added it 2 weeks ago and the update is out as well.
