### ISSUE TITLE
Tab triton 

### ISSUE THREAD

**Issue by Dancbeunny98** [NEZNAMY/TAB#1116]
### Server version

plazma 1.19.4 964880b

### TAB version

4.0.7

### Describe the bug

https://github.com/tritonmc/Triton/issues/336

### Expected behavior

- 

### Steps to reproduce

-

### Additional info

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
If you want to use Triton's language keys in TAB, use Triton's PAPI placeholders https://triton.rexcantor64.com/concepts/placeholderapi.html#using-variables1

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d55e6897-aab5-46df-9f53-669b0d85dc92)
The only thing you provided is link to a message on a discord server that is not TAB's discord and is most likely locked for buyers of that plugin only. There is nothing suggesting anything is wrong with TAB.

**Comment by NEZNAMY** [comment]
What happened? Why did you close the issue?
