### ISSUE TITLE
LuckPerms Prefix/Suffix for subserver don't work

### ISSUE THREAD

**Issue by PanetiX** [NEZNAMY/TAB#1119]
### Server version

Paper 1.20.1

### TAB version

4.0.7

### Describe the bug

I don't know if this is a bug or i'm to stupid to use that :D

I have a Proxy Server and different Subservers like Citybuild, Survival, Skygames ...
Every Server has their own LuckPerms Database. The most groups are available on every subserver but some subservers has speicla groups like the citybuild server has a "cityowner" group, for users which has a own city. Users has only on the "cityowner" group on the Citybuild Subserver and i want to display that in the tablist. 

Because the TAB Plugin is installed on proxy it use only the groups from the Proxys LuckPerms.

Of course i installed TAB-Bridge v3.1.7.jar Plugin on every subserver.

How i can display the special subservers luckperms group on this Citybuild Subserver?

### Expected behavior

N/A

### Steps to reproduce

N/A

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups#taking-groups-from-backend-servers-when-tab-is-on-bungeecord ?

![image](https://github.com/NEZNAMY/TAB/assets/6338394/036e0611-0492-4b6b-8db6-67fd6bc5d557)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/3f4f24cf-6e85-4ee5-99b3-4f809db5f463)
confusion

**Comment by PanetiX** [comment]
Sorry, Server Version is Waterfall 1.20-R0.2 #548

But this don't work.
I have tested for a player he has on the subserver 
group.default and group.stammspieler
but in tablist he will be shown as group.premium (he has this group on proxy server)

other problem is when is set use-bukkit-permissions-manager: true
the whole sorting don't work anymore. I use   

sorting-types:
  - GROUPS:MY GROUPS HERE


only when i set use-bukkit-permissions-manager to false this will work.

when set to false:
![image](https://github.com/NEZNAMY/TAB/assets/10868753/bfc7782c-e44e-4b3d-a9e7-b2edf998cddf)
(this is how it should looks!)

when set to true:
![image](https://github.com/NEZNAMY/TAB/assets/10868753/54bf03c0-688b-48f1-a25a-84c60e9be694)

**Comment by NEZNAMY** [comment]
`/btab debug <player>` command is your friend. It will tell you everything you need to know about a player. I would need to see your LP and TAB configuration, but we are getting into support territory by that, while this is an issue tracker, so you cannot get help here.

**Comment by PanetiX** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/10868753/e9f9c471-5891-4b1e-9e11-f8b62640ff4a)

it says "Spieler+" is not in Sortinglist, this group is called "stammspielerplus" on luckperms and sure, i have this in the sortinglist...

  sorting-types:
  - GROUPS:leitung,admin,entwickler,eventmanager,parkleiter,mod,architekt,architektjr,support+,support,streamer,vip,premiumplusplus,premiumplus,premium,legende,elite,stadthalterplusplus,premiumstadthalter,stadthalter,stammspielerplus,stammspieler,default

**Comment by NEZNAMY** [comment]
Your group name contains color codes for some reason and no, it's not called "stammspielerplus". TAB takes groups from LP, it doesn't randomly make up names. You have a lot of LP configuration to do. Check `/lpb user <player> info` to see player's primary group name.
Also this is an issue tracker, support is not provided here.

**Comment by PanetiX** [comment]
Yea sorry he is in group "stammspieler" not "stammspielerplus" my fault. But that doesn't work, too.

![image](https://github.com/NEZNAMY/TAB/assets/10868753/5209984b-253d-44ca-a638-52e4ab754486)

here you can see the group is called "stammspieler" ...

**Comment by PanetiX** [comment]
> primary group name. Also this is an issue tracker, support is not provided here.

where you can give better support? :)

**Comment by NEZNAMY** [comment]
You didn't show top part of the debug, so I don't know if that invalid group comes from backend or proxy LP. I may have told you to use the wrong command because of that.

Support licenses are currently not for sale as I have left the plugin development and want to have nothing to do with it anymore.

**Comment by PanetiX** [comment]
which top part? its the whole debug message..

/lp user PaDo90 info
![image](https://github.com/NEZNAMY/TAB/assets/10868753/93c0cb20-21ec-43f7-b214-4205d5f9b536)

/btab debug pado90
![image](https://github.com/NEZNAMY/TAB/assets/10868753/e4bb4697-5090-44dc-b3d6-c6eb3515e08b)

in this list is "stammspieler", too: 
`  sorting-types:
  - GROUPS:leitung,admin,entwickler,eventmanager,parkleiter,mod,architekt,architektjr,support+,support,streamer,vip,premiumplusplus,premiumplus,premium,legende,elite,stadthalterplusplus,premiumstadthalter,stadthalter,stammspielerplus,stammspieler,default`

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/3b5f6323-3647-4957-bbac-b96f0c7a9c3a)
This is what I get when I run debug command. If you did not get the top part in debug output, something is broken in the plugin jar you are using.

**Comment by PanetiX** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/10868753/f1c20f90-c027-43a2-8d5a-f71c1f58abfa)
okay this is how it looks like in my console but everything is showing the same... :D 

as you can se the player has the group "Spieler+" which is "stammspieler" in LuckPerms

![image](https://github.com/NEZNAMY/TAB/assets/10868753/65bf290e-2c53-40f0-b7da-efb412923208)

The tablist still showing a wrong prefix/suffix.

Here the config from this Tablist:

`  CityBuild-1:
    _DEFAULT_:
      tabprefix: '&9ᴄʙ  %luckperms-suffix%&8 | &7'
      tabsuffix: ' %cmi_user_afk_symbol%%cmi_user_vanished_symbol%'`
      
    and this is on luckperms on the group "stammspieler":
![image](https://github.com/NEZNAMY/TAB/assets/10868753/090b49e2-4d9e-4080-a7c5-201ec4cb41da)

**Comment by Tanguygab** [comment]
when taking groups from Vault (through Bridge since TAB is on Bungee and LP on Spigot) TAB receives the displayname of the group (the name in the sidebar of your LP editor), which in your case is &9Spieler+

**Comment by NEZNAMY** [comment]
I don't know why does LP return display name instead of group name, but why don't you just use display name in sorting list (including the color code)? Or why are you even using display names in the first place since you know they are completely useless?

**Comment by PanetiX** [comment]
Okay, wow i removed the displayname now it looks like this:

![image](https://github.com/NEZNAMY/TAB/assets/10868753/062d829e-c693-4e78-9f41-bfe5b2790cae)

but on tablist the player still have "Premium++"
![image](https://github.com/NEZNAMY/TAB/assets/10868753/4681d845-55ca-45ec-945e-7bfaacbd442f)

that not make any sense... why The %luckperms-suffix% is showing the wrong? it still shows from the group this user has on  proxy luckperms...

**Comment by NEZNAMY** [comment]
You are not even using %luckperms-suffix% placeholder.
Use `/btab parse <player> %luckperms-prefix%` and show output. Also show LP info of the player using /lpb, not /lp (because you decided you want to take prefix from proxy LP and not backend).

**Comment by PanetiX** [comment]
sure is use this placeholder see:
      tabprefix: '&9ᴄʙ  %luckperms-suffix%&8 | &7'
      
i use prefix and suffix other way because we have different display types for this.

this is output from: /btab parse pado90 %luckperms-suffix%
![image](https://github.com/NEZNAMY/TAB/assets/10868753/07d76ff8-bf3e-4fd0-888e-986b69dc7141)

**Comment by NEZNAMY** [comment]
No, you don't want to take prefix from backend LP, because if you did, you would read the wiki that says how to do it. You decided to take prefix from proxy, and that's what it returned.

**Comment by PanetiX** [comment]
> No, you don't want to take prefix from backend LP, because if you did, you would read the wiki that says how to do it. You decided to take prefix from proxy, and that's what it returned.

i have set:

use-bukkit-permissions-manager: true

its set to TRUE so Yes i want from Backendserver???? what do you want to telling me?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#taking-prefixessuffixes-from-permission-plugin

![image](https://github.com/NEZNAMY/TAB/assets/6338394/cc54ac44-2b01-4bf6-ad04-d57e3a4630a1)

**Comment by PanetiX** [comment]
wow so you know my issue for a long time but don't telling me? i never see this part in the wiki

**Comment by NEZNAMY** [comment]
No, I have no clue why is LuckPerms API returning group's display name instead of its actual name. And it is not my responsibility to read the wiki for you.

**Comment by PanetiX** [comment]
i just need to switch %luckperms-suffix% to %luckperms_suffix% and now it works... WOW :D

**Comment by NEZNAMY** [comment]
It's no magic, it makes perfect sense once you understand how placeholders work. What is the bug you came to report then? I still haven't performed any code change that would lead to this issue being fixed.

**Comment by PanetiX** [comment]
its no bug i just need support... but there is no discord or stuff like that for support.
a "user to user" support would helpful for that, too...

what do you mean with "as I have left the plugin development and want to have nothing to do with it anymore." will this plugin get further updates?

**Comment by NEZNAMY** [comment]
Support is not provided and abusing the issue tracker for support will not work either.
No, it will not get further updates. Please consider switching to a different plugin.

**Comment by PanetiX** [comment]
Okay that's very hard to hear. Will anyone else continue the development or is there a possibility that our developer will continue to develop the plugin?

**Comment by NEZNAMY** [comment]
You can hire a developer to update any plugin for you. That's up to you and your budget. It has nothing to do with me. It has nothing to do with providing support in issue tracker.

**Comment by PanetiX** [comment]
But why you will leave this plugin? i think it's the best TAB plugin what exists... :(
