### ISSUE TITLE
TAB papi reload breaking Lands plugin

### ISSUE THREAD

**Issue by ColaIan** [NEZNAMY/TAB#112]
**Server version**
Paper-114

**Plugin version** ("latest" is not a version)
v2.7.0-pre13

**Describe the bug**

> [TAB] Expansion lands is used but not installed. Installing!
> No expansion found with the name: lands
> [TAB] Reloading PlaceholderAPI for the changes to take effect

**How to reproduce**
Use any lands placeholder, then TAB will try to install it and reload papi, which breaks the way Lands register their placeholders.

**Expected behavior**
Placeholders from Lands would work

**Actual behavior**
Placeholders from Lands doesn't work

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/43201383/75102168-45e90f80-5622-11ea-884b-5e06a464223b.png)

**Comment by NEZNAMY** [comment]
Since the plugin is paid i'm unable to check it's code to find a possible reason for this.

**Comment by Tanguygab** [comment]
> Since the plugin is paid i'm unable to check it's code to find a possible reason for this.
> I could possibly add a check to prevent plugin from running reload command when nothing was downloaded.

I think that maybe the plugin doesn't register again the PAPI expansion on reload of PlaceholderAPI, I remember that BedWars1058 had the same issue

**Comment by NEZNAMY** [comment]
Both happened. I added a check and issue creator said that lands plugin author fixed it.
