### ISSUE TITLE
Luckperms prefix colour not correct

### ISSUE THREAD

**Issue by BumbleTree** [NEZNAMY/TAB#1120]
### Server version

1.20.1 Fabric

### TAB version

4.0.3 

### Describe the bug

Im using <color> codes in my luckperms prefix however some colours dont seem to work in the tab menu
Expected output in tab
<img width="249" alt="image" src="https://github.com/NEZNAMY/TAB/assets/77128029/f25a801b-7850-420e-a580-e9b161790838">
Actual 
<img width="339" alt="image" src="https://github.com/NEZNAMY/TAB/assets/77128029/62a4209b-57f2-4eaa-bee3-064bf3582e12">
ignore the Username not being the same, may report separately..
For some reason Pink is not displaying correctly, others work fine aswell.
<img width="119" alt="image" src="https://github.com/NEZNAMY/TAB/assets/77128029/7903fd0e-d420-4c2d-a231-861b8e95b9f5">
My prefix is this prefix.0.<gray>[<pink>Mew<gray>] <reset>

its showing the gray, yellow and reset tags correctly, but outputs pink as plaintext for some reason

### Expected behavior

it to show all colours

### Steps to reproduce

Use < pink > formatting in a name that appears on the tab menu

### Additional info

I believe V 4.0.3 is the most up to date one I can do on 1.20.1 so i don't think i can download any fixes if you arent supporting this version any more i guess.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#18---is-minimessage-supported

**Comment by BumbleTree** [comment]
You reply quick, 
Thank you, Light_purple worked.
I did want to ask, before I create another bug report, with the same setup when we set a nickname which changes the display name, it shows up in the tab correctly, however once the player reconnects tab will only ever show the actual username again.
Is this a limitation of not being able to use essentials placeholders as its a mod, or is this something that should work.

Thank you for your assistance

**Comment by NEZNAMY** [comment]
TAB does not support any placeholder plugins on Fabric. That is not a bug either. Also 4.0.3 is outdated and anti-override for tablist was not available back then either, but now it is.

**Comment by BumbleTree** [comment]
4.0.3 is the latest i can install for 1.20.1 as the others crash, I assumed they are only supposed to work on 1.20.2. Is that the case? Then that's fine and this can be closed.

**Comment by NEZNAMY** [comment]
Yes, latest is only for 1.20.2. You can hire someone to backport it for you.

**Comment by BumbleTree** [comment]
No issue,
Advise given
