### ISSUE TITLE
No player Prefix in chat

### ISSUE THREAD

**Issue by TimeToShine6308** [NEZNAMY/TAB#1122]
### Server version

Paper 1.20.2

### TAB version

4.0.7

### Describe the bug

I tried to add prefixes to the players, which worked. But then if the player types something into the chat, its just showing <Player> Message. Im not sure how to fix it. I have Vault, TAB, Essentials and LuckPerms.
Thank You!

### Expected behavior

I expected a format like this *Prefix* *Player*: *Message*

### Steps to reproduce

I created the groups. Then i changed the chat format in the essentials config to:
format: '{PREFIX} {DISPLAYNAME}: {MESSAGE}'

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What does TAB have to do with chat?

**Comment by TimeToShine6308** [comment]
I thought it made prefixes, also in chat

**Comment by NEZNAMY** [comment]
Where does the wiki say that?

**Comment by TimeToShine6308** [comment]
Nowhere, but how can i have a prefix in chat?

**Comment by NEZNAMY** [comment]
Using a chat plugin. TAB is not a chat plugin. This is a TAB issue tracker.

**Comment by TimeToShine6308** [comment]
What chat plugins work with tab?

**Comment by NEZNAMY** [comment]
TAB does not affect chat in any way and therefore has no compatibility issues nor synergies with any chat plugin. This is a TAB issue tracker, not server support.

**Comment by TimeToShine6308** [comment]
Yes, sorry my bad, but now i have a real TAB issue
![grafik](https://github.com/NEZNAMY/TAB/assets/106665507/e1d492f8-c2d5-4e85-b4ab-c1975fa07caf)

**Comment by NEZNAMY** [comment]
Remove smpcore plugin.

**Comment by TimeToShine6308** [comment]
I don't have it installed

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/86abc8a6-f202-44c1-aa7b-0cbeaba2d974)
What is this then?

**Comment by TimeToShine6308** [comment]
Oh, thats my lifesteal plugin.

**Comment by NEZNAMY** [comment]
Delete it and stop using TAB's issue tracker to ask for help with other plugins.
