### ISSUE TITLE
Compatibility issue with latest BungeeCord

### ISSUE THREAD

**Issue by LucidAPs** [NEZNAMY/TAB#1123]
### Server version

Waterfall 1.20 Build #549

### TAB version

TAB v4.0.7

### Describe the bug

Waterfall 1.20 Build #549
Paper 1.20.2 Build #260
TAB v4.0.7
TAB-Bridge v3.1.7

https://mclo.gs/87yKBgu

Also doing /btab reload kicked me from the network the error is at the bottom of the logs.

### Expected behavior

no bugs

### Steps to reproduce

network setup with the server versions i have maybe?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
I have added support for the new builds, however there's a packet encoding bug on <1.13 that will make players disconnect immediately join. It is therefore not a good idea to update to these new builds, especially if you want <1.13 players on your server.

**Comment by Leahcimkrob** [comment]
Only the default CMI tab is displayed, although TAB is active on the bungee and the tab bridge is active on the backend servers.
Paper 1.20.1-196
With /btab reload I get the same error as LucidAPs

**Comment by NEZNAMY** [comment]
What's the point of re-reporting an issue that is already scheduled to be fixed in the next release and already available for download in github actions?

**Comment by Leahcimkrob** [comment]
Above it was all about getting kicked during a reload. But the whole tab doesn't work for us, it could have been something else

**Comment by NEZNAMY** [comment]
Once again, in the commit linked above I added support for the latest bungeecord.
