### ISSUE TITLE
Citizens collision conflict fix and so on

### ISSUE THREAD

**Issue by exosmium** [NEZNAMY/TAB#1125]
Hi. Currently plugin supports only true/false collision values. But what to do, if i need to make npc's collidable, but players not? 
Feature in Citizens, which allows to to this manually results in nothing when you are using TAB. Can you add those **FOR_OWN_TEAM**, **FOR_OTHER_TEAM** options to collision rule in Developer API or add more options of collision in config? I really need this.

**Comment by NEZNAMY** [comment]
Feature requests are closed, as you can see from the missing template. You can fork the plugin and use your own version.

**Comment by exosmium** [comment]
I am creating npc's with random names. So it can't be considered as bug?

**Comment by NEZNAMY** [comment]
Then how are you expecting "for other teams" / "for own team" to behave exactly? Each player is put into a different team not shared with anyone else, so "for other teams" means "for everyone". Same for the other option.

**Comment by exosmium** [comment]
Logically.. so there is no option to achieve my goal?

**Comment by exosmium** [comment]
I want to make:
**COLLIDABLE** - _PLAYER and CITIZENS NPC_
**NOT COLLIDABLE** - _PLAYER and PLAYER_

**Comment by NEZNAMY** [comment]
And how exactly would these options help? Option "push other teams" means "push everyone", a.k.a. "always", because no one else is in the same team as the player. Same thing for the other option.

**Comment by exosmium** [comment]
I understood it. That's why i've asked, "so there is no option to achieve my goal?" Now you understand my goal :)

**Comment by NEZNAMY** [comment]
You guessed it, there is no way. Good thing I discussed this first before wasting time adding it, documenting and teaching everyone what it means and how to use it, explaining it's pretty much useless just to get you finding out it didn't solve your issue.

**Comment by exosmium** [comment]
Are there any options to override one team with another?

**Comment by NEZNAMY** [comment]
Mojang did not add an option for player to be in 2 teams.

**Comment by exosmium** [comment]
Okay.  Sorry for wasting your time. Thank you.
