### ISSUE TITLE
Transparent Nametags

### ISSUE THREAD

**Issue by Daseldorf** [NEZNAMY/TAB#1126]
### Server version

1.20.2

### TAB version

4.0.7

### Describe the bug

Hey Im a Tab buyer but I cant find your discord server anywhere (if you can send to me the link to find it again, thanks). I got an issue. When they shift and go up again we see transparent nametags, maybe they shift again and it seems to be seen good again. So, sometimes we see transparent nametags, normally when people shift. I have read the wiki I cant find something like that.

Thanks cordial greetings.

### Expected behavior

It would be shown good (normal, not transparent), as a good plugin it is. TOP plugin. Thanks.

### Steps to reproduce

Shifting

### Additional info

We enter from 1.20 to 1.20.2 (Server is paper 1.20.2)
Most of us got premium accounts

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You can find discord link on top of the page where you bought the plugin.

**Comment by Daseldorf** [comment]
Okay I bought at BuiltByBit (McMarket). Im going to look for the link later, thanks. I dont know how to upload here videos but look this, Its not the texture pack or shaders, It happened to me before with clean premium launcher.
I can send you to screenshots, it happens when he shift sometimes.
**Normal:** https://i.imgur.com/fdmdnJP.png
**Strange:** https://i.imgur.com/gxMSZCb.png
Thanks again, cordial greetings.

**Comment by NEZNAMY** [comment]
Is the player using any third party client that gives unfair advantage and allows player to sneak at a rapid rate?

**Comment by Daseldorf** [comment]
Lunar Client in this case, but I see it happening on all players.

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=sX0bD5q01Us).

**Comment by Daseldorf** [comment]
Have you tried with Viaversion & Viabackwards one on 1.20.1 and the other on 1.20.2?
Well thanks. Cordial greetings.

**Comment by NEZNAMY** [comment]
You closed this issue. Was it by accident?

I performed the same test as I did on the video just now, using 1.20.1 + 1.20.2 clients, using ViaVersion on both 1.20.1 and 1.20.2 server, still works properly. 
It looks like you have another plugin or a setting causing this issue. You will need to identify the cause and report it back, otherwise I will not be able to look into it.

**Comment by Daseldorf** [comment]
Okay it will be that for sure then, thanks again! Best Plugin!

**Comment by NEZNAMY** [comment]
I don't really understand. Did the issue suddenly fix itself?
