### ISSUE TITLE
Support Using TAB

### ISSUE THREAD

**Issue by JustJP2K** [NEZNAMY/TAB#1127]
Hello,  was wondering if there was a discord server for support?

It seems if you use multiple placeholders for conditional placeholders, if they arent met itll leave a bank space instead like so: 
![image](https://github.com/NEZNAMY/TAB/assets/74447960/ab223c3c-1f9d-4e18-805a-ccec1709137f)

So it has 2 blank spaces in between. If i dont use spaces it will just mush them all together in one line.

![image](https://github.com/NEZNAMY/TAB/assets/74447960/f8cbd915-5d0d-440d-9942-e486864b07a4)

Is there a way to get around that limitation?

customtabname: "%cmi_user_afk_symbol% %cmi_user_nickname%"

Also i would like to add the ~ prefix for nicknames from CMI to the tab list using {nicknameprefix}, how would i do that since its not a placeholder and therefore doesnt get displayed?

**Comment by NEZNAMY** [comment]
Support is not provided as I am no longer able to spend 16 hours a day configuring random minecraft servers for free. I have left the development as well. Please consider switching to a different plugin.
