### ISSUE TITLE
mysql wont connect?

### ISSUE THREAD

**Issue by UnrivaledKid** [NEZNAMY/TAB#1128]
### Server version

Velocity 3.2.0 SNAPSHOT

### TAB version

4.0.7

### Describe the bug

whenever i enable mysql on my velocity server i get errors and it says it cant connect to mysql. i have the proper database setup and linked. my server provider also looked into it and couldnt see any reason why it isnt working and said i should reach out. Ive follow the wiki and tried everything i can think of and im out of ideas.  I am running TAB 4.0.7 on the proxy and im running TAB Bridge 3.1.7 on the internal servers. 

### Expected behavior

![info1](https://github.com/NEZNAMY/TAB/assets/90822278/11dfc498-1daa-4fd1-ab39-144a9e4a2dcb)

### Steps to reproduce

install Velocity 3.2.0 SNAPSHOT for proxy
download TAB 4.0.7 on the proxy
install Paper 1.20.2 for internal server
download TAB Bridge 3.1.7 on the internal server
input database settings in config.yml on proxy server
enable database in config and start server
then i get the error pictured.
everything else seems to work just fine for me thus far other then mysql.

### Additional info

any help is appreciated. Thanks in advance.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Velocity does not have a mysql driver. You don't need it anyway, since it's all stored in the same folder anyway.

**Comment by UnrivaledKid** [comment]
makes sense. thanks for the quick reply

**Comment by axctal** [comment]
> Velocity does not have a mysql driver. You don't need it anyway, since it's all stored in the same folder anyway.

Velocity does not have mysql driver ... yet LuckPerms-velocity does work with MySQL ... ?
How does it work? Do they have that driver "onboard" ?
Maybe there is an "improvement opportunity" ?  :)

> lpv info
[08:11:50 INFO]: [LP] Running LuckPerms v5.4.121 by Luck.
[08:11:50 INFO]: [LP] -  Platform: Velocity
[08:11:50 INFO]: [LP] -  Server Brand: Velocity
[08:11:50 INFO]: [LP] -  Server Version:
[08:11:50 INFO]: [LP]      3.3.0-SNAPSHOT (git-9e42049a-b376)
[08:11:50 INFO]: [LP] -  Storage:
[08:11:50 INFO]: [LP]      Type: MariaDB
[08:11:50 INFO]: [LP]      Connected: true
[08:11:50 INFO]: [LP]      Ping: 3ms
[08:11:50 INFO]: [LP] -  Extensions:
[08:11:50 INFO]: [LP]      None
[08:11:50 INFO]: [LP] -  Messaging: PluginMessage
[08:11:50 INFO]: [LP] -  Instance:
[08:11:50 INFO]: [LP]      Static contexts: (server=proxy)
[08:11:50 INFO]: [LP]      Online Players: 0 (0 unique)
[08:11:50 INFO]: [LP]      Uptime: 7s
[08:11:50 INFO]: [LP]      Local Data: 0 users, 1 groups, 0 tracks
>

As for "dont need" ... a matter of convenience, maybe? ( like keeping config for multiple servers in one central location as opposed to track those setting on multiple individual servers )

**Comment by Tanguygab** [comment]
> like keeping config for multiple servers in one central location as opposed to track those setting on multiple individual servers

the only settings that are shared with MySQL are the ones in groups.yml & players.yml, and when used on Velocity, since you only have TAB on Velocity and not on the backend servers, you only have 1 set of those files
> Velocity does not have mysql driver ... yet LuckPerms-velocity does work with MySQL ... ?
How does it work? Do they have that driver "onboard" ?

they download the drivers themselves I guess, something like that
