### ISSUE TITLE
Per worlds group tab list

### ISSUE THREAD

**Issue by TheMixaDev** [NEZNAMY/TAB#113]
What about adding feature with per world groups tab list? Like peoples from world, world_nether and world_the_end can see each other, but can't see players in worlds second, second_nether and second_the_end, and of course players in second, second_nether and second_the_end can see each other too
Idea for cfg:

groups:
   group1:
      - world
      - world_nether
      - world_the_end
   group2:
      - second
      - second_nether
      - second_the_end
   group3:
      - hub
      - minigame_hub

**Comment by NEZNAMY** [comment]
This was actually my next feature plan.

**Comment by NEZNAMY** [comment]
Check new build on discord

**Comment by TheMixaDev** [comment]
Well, that isn't working for me. Server: spigot 1.8
CFG:
per-world-playerlist:
  ignore-effect-in-worlds:
  \- hub
  shared-playerlist-world-groups:
    classic:
    \- world
    \- world_nehter
    \- world_the_end
    easysurvival:
    \- easy
    \- easy_nehter
    \- easy_the_end
  allow-bypass-permission: false
  enabled: true

**Comment by NEZNAMY** [comment]
Your worlds probably have "nether" in their name instead of "nehter".

**Comment by TheMixaDev** [comment]
Yeah, I've got that

**Comment by NEZNAMY** [comment]
So.. does it work after fixing your world names ?

**Comment by TheMixaDev** [comment]
Yep! Thanks!
