### ISSUE TITLE
Add api for manually refreshing placeholders

### ISSUE THREAD

**Issue by Ielelele29** [NEZNAMY/TAB#1130]
### Server version

Paper 1.20.1

### TAB version

4.0.8

### Evidence

I wanted to propose a feature that could optimize the use of the plugin's API. Today I was creating some not exactly lightweight placeholders that need to be updated quickly in certain circumstances and very slowly in others. 
To do this I looked to see if there was a command to manually refresh a placeholder but I couldn't find it. 

It would be very convenient to be able to refresh these placeholders at specific times chosen by me, and it would also greatly optimize the performance of all those placeholders who are often updated because they have to urgently modify a value that changes once every 2/3 minutes

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/placeholder/ServerPlaceholder.java
https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/placeholder/PlayerPlaceholder.java
https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/placeholder/RelationalPlaceholder.java

Already done a long time ago.

**Comment by Ielelele29** [comment]
I'm probably blind...
