### ISSUE TITLE
incorrect scoreboard title

### ISSUE THREAD

**Issue by shooutz** [NEZNAMY/TAB#1132]
### Server version

waterfall-548 & paper-1.8

### TAB version

tab-4.0.8 & bridge-3.1.7

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/120399502/122aa35a-d341-4ddb-8cbd-06dddc508139)
![image](https://github.com/NEZNAMY/TAB/assets/120399502/fdc64ff6-14da-4086-af91-6c12e4a1b671)
![image](https://github.com/NEZNAMY/TAB/assets/120399502/62bc509a-bcf4-4a40-86fe-54556abd1606)
mc version: 1.8

the last tab update caused me this problem, I don't know if this has to do with the current problem with bungeecord, but as neznamy said to use version [548](https://github.com/NEZNAMY/TAB/releases/tag/4.0.8) of waterfall, I did so

### Expected behavior

This clearly shouldn't happen

### Steps to reproduce

???

### Additional info

I initially suspected this to be a problem on my client, but I've already logged into other servers and it doesn't happen.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
See 4.0.8 changelog. Latest BungeeCord is bugged for <1.13 players. Downgrade it.

**Comment by shooutz** [comment]
Turns out not, I updated waterfall to the latest yesterday, the version I was using was build 548, but as I saw problems in recent versions (disconnect due to extremely large nickname??)
![image](https://github.com/NEZNAMY/TAB/assets/120399502/0038a0b0-74c2-4f82-a131-2649a58a20f1)

**Comment by NEZNAMY** [comment]
What client version are you using? Also send your config so I can use it to try.

**Comment by NEZNAMY** [comment]
I got the issue as well, I will investigate further.

**Comment by shooutz** [comment]
Sorry for the delay, there was just a power outage in my neighborhood, even the mobile internet isn't working properly
Do you still want me to send the config file? I still have no energy but I can try

**Comment by NEZNAMY** [comment]
No, I fixed it in 4.0.9.
