### ISSUE TITLE
%staffonline% only shows OPs

### ISSUE THREAD

**Issue by VulkanoTG** [NEZNAMY/TAB#1133]
### Server version

Purpur 2062 (1.20.1

### TAB version

TAB v408

### Describe the bug

Adding the "tab.staff" permissions by luckyperms for helper and moderator positions does not force them to be shown in %staffonline%.

### Expected behavior

it was supposed to show only the players with the "vigilante" rank in %staffonline%

### Steps to reproduce

I have set permissions allowing staff.tab for the guard and denied permission for the positions above him

### Additional info

config: https://imgur.com/ni3Br3X
config ranks tab: https://imgur.com/AZSBF54
Luckyperms rank permisson: https://imgur.com/Lmzhf7y
player with OP: https://imgur.com/noOQdUz (counts as staff on regardless of rank)
the same player was removed from the OP and placed in the rank to continue showing as %staffonline%: https://imgur.com/GdYszWL
the rank he is in: https://imgur.com/eLJS2ww

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
LuckPerms has a permission test command. Can you use it to test if the player has the permission + show output of `/tab parse me %staffonline%`?

**Comment by VulkanoTG** [comment]
/tab parse <player> %staffonline%
https://imgur.com/94rm1Tg

/lp user <player> permission check tab.staff
https://imgur.com/V3eu7iy

**Comment by NEZNAMY** [comment]
How many staff members were online at that time?

**Comment by VulkanoTG** [comment]
I'm the only player online, and I'm doing the test by giving and taking the op

**Comment by NEZNAMY** [comment]
You were the only one online, you had the permission and placeholders says 1. I see no problem.

**Comment by VulkanoTG** [comment]
when I'm not with OP and in the "watchman" position that should show as staff it doesn't show, it only shows when I'm with OP

**Comment by NEZNAMY** [comment]
Deop yourself and run the commands again.

**Comment by VulkanoTG** [comment]
ok

**Comment by VulkanoTG** [comment]
https://imgur.com/LNdvqLv

https://imgur.com/28zRjhQ

**Comment by NEZNAMY** [comment]
"Result: false"
Not a TAB issue. Contact LuckPerms support.

**Comment by VulkanoTG** [comment]
ok
