### ISSUE TITLE
endsWith (-|) condition not working

### ISSUE THREAD

**Issue by alfoons** [NEZNAMY/TAB#1134]
### Server version

BUNGEE

### TAB version

latest

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/88468043/3025fb56-0b74-4248-8f43-bb6f53fa67e5)

### Expected behavior

![image](https://github.com/NEZNAMY/TAB/assets/88468043/1f81d3d9-6e8f-43eb-a4e0-e5f04647c514)

### Steps to reproduce

![image](https://github.com/NEZNAMY/TAB/assets/88468043/ce480635-7c7f-4b1a-b5e0-a5b00894f564)

### Checklist

- [x] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/26da9ddf-41dd-4480-b362-c49af113bfbe)
?

Do you have bridge installed?

**Comment by alfoons** [comment]
yes but error in  console proxy

**Comment by alfoons** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/88468043/bc163faf-8671-4daf-878f-e7ce58c9f633)

**Comment by NEZNAMY** [comment]
I'll fix it.

**Comment by alfoons** [comment]
when?

**Comment by NEZNAMY** [comment]
I am not a robot and cannot fix things instantly. It may take up to several minutes.

**Comment by alfoons** [comment]
I know yes I'm just asking ;D

**Comment by alfoons** [comment]
i have a question it is possbile to do a scoreboard per server?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#example-1---per-world-scoreboards
This is not support.

**Comment by alfoons** [comment]
okay ;l

**Comment by alfoons** [comment]
Is there anything like that planned to be added? this

**Comment by NEZNAMY** [comment]
Like what?

**Comment by NEZNAMY** [comment]
How am I supposed to add something that already exists? I literally sent you a link that says how to do it.
Please stop abusing the issue tracker for support.

**Comment by alfoons** [comment]
you sent me a link where you can do it on the per world and not on the per server

**Comment by alfoons** [comment]
sorry my bad XD

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/96c6bf0a-06f1-4224-a25f-199a12edb6db)
This is not funny at all.
