### ISSUE TITLE
Compatibility issue with latest BungeeCord

### ISSUE THREAD

**Issue by thevalleyy** [NEZNAMY/TAB#1135]
### Server version

Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:cc856ed:552

### TAB version

4.0.9

### Describe the bug

The tagprefixes just don't work anymore. It worked on v4.0.3 (Waterfall 1.20.1)

I don't know if this is related to the nametag bug, but upon entering `/btab reload`, [this happens](https://pastebin.com/ALx2YQav).

### Expected behavior

The nametags should be working, the reload command shouldn't crash and unload the plugin.

### Steps to reproduce

Step 1: Install TAB v4.0.9 on a bungeecord server running 1.20.2
Step 2: Setup nametags (e.g. using luckperms)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Your server version information is misleadig, since you have it installed on BungeeCord, but you said purpur. Support for latest BungeeCord will be added in next version.

**Comment by thevalleyy** [comment]
Damn true, I'm a little bit too tired to think... but the flame for my english was sassy 😭
