### ISSUE TITLE
layout randomly breaks 

### ISSUE THREAD

**Issue by czychuuu** [NEZNAMY/TAB#1138]
### Server version

git-Purpur-2078 (MC: 1.20.2)

### TAB version

v4.0.8

### Describe the bug

sometimes when someone joins the first slot in layout mode is replaced with player instead of animation, only the player sees that everyone else has normal tab
![image](https://github.com/NEZNAMY/TAB/assets/60987404/90871ea8-e89f-4aa2-b23e-cb6cc8207729)
after /tab reload
![image](https://github.com/NEZNAMY/TAB/assets/60987404/49d8ad95-5702-4044-b553-965cb71c9633)

### Expected behavior

tab loads normally for everyone

### Steps to reproduce

no idea

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by czychuuu** [comment]
> Send your config.

https://pastebin.com/QrGJ2uZM

**Comment by NEZNAMY** [comment]
Console must have told you that you must set line 30 to true.

**Comment by czychuuu** [comment]
wdym

**Comment by NEZNAMY** [comment]
Send your startup log.

**Comment by czychuuu** [comment]
https://pastebin.com/Msw6ACba

**Comment by NEZNAMY** [comment]
Read line 513 of that log.

**Comment by czychuuu** [comment]
i have the same thing on the lobby and its working fine there

**Comment by NEZNAMY** [comment]
You probably don't have that other plugin or another source breaking it there. Please stop playing games and enable it. I don't want to play with you.

**Comment by czychuuu** [comment]
okay okay fine

**Comment by NEZNAMY** [comment]
Let me know if it fixed the bug.
