### ISSUE TITLE
Groups Priorities

### ISSUE THREAD

**Issue by Tanguygab** [NEZNAMY/TAB#114]
Hey NEZ, when you check for a group priority, it will only check for the group you have with the higher priority. But if this groups isn't specified in the config (like in the group-sorting-priority-list), it won't check if the player have a group with the nearest priority that is specified in the config

It would be usefull if you can add a check for that.

If you want an example:
in the priority list there are the groups A and C
But I have the groups C and B and B have a higher priority in my permission plugin.
What TAB should do, is check for my other ranks, so it finds the group C and it will sort me as a player with the group C instead of adding me at the bottom of the tablist.

Idk if you understand x) but it would be a cool suggestion =) Thanks !

**Comment by NEZNAMY** [comment]
This would be a misconfiguration compensation which would delete a feature (sorting by prefix when group is not in list). I don't see any real use for this.
