### ISSUE TITLE
not showing font texture on scoreboard

### ISSUE THREAD

**Issue by Oukaa** [NEZNAMY/TAB#1140]
### Server version

1.20.1

### TAB version

4.0.3

### Describe the bug

i want to put my rank texture on scoreboard but its only showing the text, not the texture. i tried tab parse me and it works normally how can i put this into my scoreboard
![image](https://github.com/NEZNAMY/TAB/assets/71058827/40ab35a8-bc79-4206-99c6-b7dd2edf54fe)
![image](https://github.com/NEZNAMY/TAB/assets/71058827/175365ec-0513-4273-90f4-b0df12b51ab1)

### Expected behavior

it suppose to be font texture in my scoreboard

### Steps to reproduce

i have no idea 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#14---how-can-i-display-itemsadder-images
On which marketplace is 4.0.3 the latest version?

**Comment by Oukaa** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/71058827/e92ae785-155f-454f-9e5a-f0a5ac5e85e5)

**Comment by Oukaa** [comment]
i see, i just use the itemsadder placeholder 

> https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#14---how-can-i-display-itemsadder-images On which marketplace is 4.0.3 the latest version?

oh i see, i must use the itemsadder placeholder itself, thanks!
