### ISSUE TITLE
unlimited nametag mode when enabled nametag not work bungee

### ISSUE THREAD

**Issue by alfoons** [NEZNAMY/TAB#1141]
### Server version

BUNGEE

### TAB version

4.10

### Describe the bug

when unlimited nametag mode when enabled nametag not work bungee
![image](https://github.com/NEZNAMY/TAB/assets/88468043/0bf3c4f5-3c2b-4ec7-9e77-c6b8f5e56372)

### Expected behavior

/

### Steps to reproduce

enable unlimited nametag mode on bungee

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Did you install bridge plugin? /pl

**Comment by NEZNAMY** [comment]
Why did you close the issue? What happened?
