### ISSUE TITLE
Relational placeholder with hex not work on nametag bungee

### ISSUE THREAD

**Issue by alfoons** [NEZNAMY/TAB#1142]
### Server version

BUNGEE

### TAB version

4.10

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/88468043/f218d916-5c22-4f28-ab29-fdb05a77d162)
relational placeholder with hex not work on nametag but on chat work
![image](https://github.com/NEZNAMY/TAB/assets/88468043/c17fe10c-dbd0-4744-adca-fc3ea68c00e1)

### Expected behavior

,

### Steps to reproduce

,

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags
Also what happened to your previous issue? Why did you close it?

**Comment by alfoons** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags Also what happened to your previous issue? Why did you close it?

bc i not install tab bridge

**Comment by alfoons** [comment]
i have unlimited nametag mode and not work

**Comment by NEZNAMY** [comment]
But this is an issue tracker. It is for tracking bugs, not to provide support. 
Are you sure you are **not** looking at yourself? https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-2---f5-view

**Comment by alfoons** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/88468043/1adde4a0-1349-40ba-95b1-f7bb635e4625)

**Comment by NEZNAMY** [comment]
What did you configure as name? `/btab debug <player>`.

**Comment by alfoons** [comment]
> What did you configure as name? `/btab debug <player>`.

![image](https://github.com/NEZNAMY/TAB/assets/88468043/1d38ffad-c294-4987-be12-56a313f8da6d)

**Comment by alfoons** [comment]
soo?

**Comment by NEZNAMY** [comment]
I am not a robot and wasn't able to fully recode RGB handling in bridge to solve this within the given time frame. You will either need to wait for a little longer, or look for a different plugin.

**Comment by alfoons** [comment]
okay i'm go wait thanks

**Comment by NEZNAMY** [comment]
I am not able to test this as I don't have a placeholder that returns RGB codes, so you'll need to test it yourself. Get the latest build of bridge from actions (https://github.com/NEZNAMY/TAB-Bridge/suites/18118058732/artifacts/1044475827) and let me know.

**Comment by alfoons** [comment]
> I am not able to test this as I don't have a relational placeholder that returns RGB codes, so you'll need to test it yourself. Get the latest build of bridge from actions (https://github.com/NEZNAMY/TAB-Bridge/suites/18118058732/artifacts/1044475827) and let me know if it works.

![image](https://github.com/NEZNAMY/TAB/assets/88468043/8fed976a-130d-4670-a356-4b504ae7295b)

**Comment by NEZNAMY** [comment]
My bad, get new one from https://github.com/NEZNAMY/TAB-Bridge/actions

**Comment by alfoons** [comment]
thanks it's working

**Comment by alfoons** [comment]
i have 1 bug

**Comment by alfoons** [comment]
when the player left from the kingdom then tab not update the abovename

**Comment by NEZNAMY** [comment]
Yeah relational placeholders in unlimited nametags are handled differently to avoid extreme complexity and sadly don't trigger an update. However, they do update when another placeholder used in that line updates. You can use a workaround by for example creating an animation with 2 frames that only consist of color codes (different) and put it after the placeholder to trigger the update.

**Comment by alfoons** [comment]
> when the player left from the kingdom then tab not update the abovename

it's update when player rejoin on death

**Comment by alfoons** [comment]
> Yeah relational placeholders in unlimited nametags are handled differently to avoid extreme complexity and sadly don't trigger an update. However, they do update when another placeholder used in that line updates. You can use a workaround by for example creating an animation with 2 frames that only consist of color codes (different) and put it after the placeholder to trigger the update.

but on normal version of tab spigot works normal

**Comment by NEZNAMY** [comment]
Correct, because it doesn't require network communication.

**Comment by alfoons** [comment]
so?

**Comment by NEZNAMY** [comment]
I am not going to recode the entire communication protocol just for you. I told you about a workaround you can use.

**Comment by alfoons** [comment]
> Yeah relational placeholders in unlimited nametags are handled differently to avoid extreme complexity and sadly don't trigger an update. However, they do update when another placeholder used in that line updates. You can use a workaround by for example creating an animation with 2 frames that only consist of color codes (different) and put it after the placeholder to trigger the update.

![image](https://github.com/NEZNAMY/TAB/assets/88468043/232f5c63-ac65-437a-b7ea-7c155f817f37)

like this?

**Comment by NEZNAMY** [comment]
```
test:
  change-interval: 1000
  texts:
    - "&0"
    - "&1"
```
`abovename: "%rel_kingdoms_relation_name%%animation:test%"`

**Comment by alfoons** [comment]
won't it invoke lags?

**Comment by NEZNAMY** [comment]
Plugin is async.

**Comment by alfoons** [comment]
okay, thanks for help

**Comment by NEZNAMY** [comment]
I didn't help you, support is not provided.
