### ISSUE TITLE
relational placeholder not work

### ISSUE THREAD

**Issue by alfoons** [NEZNAMY/TAB#1153]
### Server version

BUNGEE

### TAB version

4.10

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/88468043/47bb3fdf-a55f-406c-8e5f-30370f4b37c3)
tab bridge connected

### Expected behavior

.

### Steps to reproduce

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you are not using it inside another placeholder? `/btab debug <player>`

**Comment by alfoons** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/88468043/780fb74f-684a-44e4-b97e-6601652643a9)

**Comment by NEZNAMY** [comment]
Yeah this is not supported.

**Comment by alfoons** [comment]
so how can i do ?? when i use the condition

**Comment by NEZNAMY** [comment]
You can't. This is currently not supported.
