### ISSUE TITLE
Scoreboard condition

### ISSUE THREAD

**Issue by ImYuv1** [NEZNAMY/TAB#1156]
### TAB version

4.0.7

### Software causing compatibility issue

Im using the scoreboard with 3 condition but i don't know why is not working:
I thought it was the placeholder of the plugin is not working correctly but i created a custom condition and that one is working

    defaultBoard:
      display-condition: '%world%=world;%combatlogx_time_left_decimal%=0'
      lines:

    defaultBountyBoard:
      display-condition: '%world%=world;%combatlogx_time_left_decimal%=0;%azurakitpvp_player_bounty%>0.0'
      lines:
      - extra line (bounty placeholder)

Server version: 1.8.9 vortex spigot

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
On which marketplace is 4.0.7 latest?
Did you read https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#chaining-scoreboards ?

**Comment by ImYuv1** [comment]
my bad, i write thw wrong version, i have the 4.0.9 from spigotmc and i checked the wiki as well but nothing changed, i tried every placeholder with other plugin condition and they are working well

**Comment by NEZNAMY** [comment]
Based on the configuration you sent there is never a possibility of the second scoreboard displaying. How do you want the plugin to work exactly?

**Comment by ImYuv1** [comment]
this is the complete configuration and the board that have the bounty information are not working

scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    defaultBoard:
      title: '&5&lQuora&f&lParty &8(&7%cmi_server_online%&8)'
      display-condition: '%world%=world;%combatlogx_time_left_decimal%=0'
      lines:
      - ''
      - '  &fRank &7â–¸ %azurakitpvp_elo_rank_color%%azurakitpvp_elo_rank%'
      - '  &fUccisioni &7â–¸ &5%azurakitpvp_kills%'
      - '  &fMorti &7â–¸ &5%azurakitpvp_deaths%'
      - '  &fELO &7â–¸ &5%azurakitpvp_elo%'
      - '  &fSoldi &7â–¸ &5%vault_eco_balance_formatted%'
      - ' '
      - '  &fStreak &7â–¸ &5%azurakitpvp_killstreak%'
      - ''
      - '  &5play.QuoraParty.it '
    defaultBountyBoard:
      title: '&5&lQuora&f&lParty &8(&7%cmi_server_online%&8)'
      display-condition: '%world%=world;%combatlogx_time_left_decimal%=0;%azurakitpvp_player_bounty%>0.0'
      lines:
      - ''
      - '  &fRank &7â–¸ %azurakitpvp_elo_rank_color%%azurakitpvp_elo_rank%'
      - '  &fUccisioni &7â–¸ &5%azurakitpvp_kills%'
      - '  &fMorti &7â–¸ &5%azurakitpvp_deaths%'
      - '  &fELO &7â–¸ &5%azurakitpvp_elo%'
      - '  &fSoldi &7â–¸ &5%vault_eco_balance_formatted%'
      - ' '
      - '  &fStreak &7â–¸ &5%azurakitpvp_killstreak%'
      - '  &fTaglia &7â–¸ &6&l%azurakitpvp_player_bounty_formatted%$'
      - ''
      - '  &5play.QuoraParty.it '
    combatBoard:
      display-condition: '%world%=world;%combatlogx_time_left_decimal%>0'
      title: '&5&lQuora&f&lParty&8(&7%cmi_server_online%&8)'
      lines:
      - ''
      - '  &fRank &7â–¸ %azurakitpvp_elo_rank_color%%azurakitpvp_elo_rank%'
      - '  &fUccisioni &7â–¸ &5%azurakitpvp_kills%'
      - '  &fMorti &7â–¸ &5%azurakitpvp_deaths%'
      - '  &fELO &7â–¸ &5%azurakitpvp_elo%'
      - '  &fSoldi &7â–¸ &5%vault_eco_balance_formatted%'
      - ' '
      - '  &fStreak &7â–¸ &e%azurakitpvp_killstreak%'
      - '  &fCombat &7â–¸ &c%combatlogx_time_left_decimal%s'
      - ''
      - '  &5play.QuoraParty.it '
    combatBountyBoard:
      display-condition: '%world%=world;%combatlogx_time_left_decimal%>0'
      title: '&5&lQuora&f&lParty&8(&7%cmi_server_online%&8)'
      lines:
      - ''
      - '  &fRank &7â–¸ %azurakitpvp_elo_rank_color%%azurakitpvp_elo_rank%'
      - '  &fUccisioni &7â–¸ &5%azurakitpvp_kills%'
      - '  &fMorti &7â–¸ &5%azurakitpvp_deaths%'
      - '  &fELO &7â–¸ &5%azurakitpvp_elo%'
      - '  &fSoldi &7â–¸ &5%vault_eco_balance_formatted%'
      - ' '
      - '  &fStreak &7â–¸ &e%azurakitpvp_killstreak%'
      - '  &fTaglia &7â–¸ &6&l%azurakitpvp_player_bounty_formatted%$''
      - '  &fCombat &7â–¸ &c%combatlogx_time_left_decimal%s'
      - ''
      - '  &5play.QuoraParty.it '

**Comment by NEZNAMY** [comment]
Did you read the wiki page I sent you? You didn't seem to have swapped the first two scoreboards at all. Obviously if the first condition is met, second one is not checked anymore and since the second one is harder to meet, it will never get to that point.

**Comment by ImYuv1** [comment]
i fixed it, thanks :D
