### ISSUE TITLE
Tab Support - Coordinates 

### ISSUE THREAD

**Issue by RedX3203** [NEZNAMY/TAB#1157]
### Server version

Spigot 1.20.2

### TAB version

4.0.9

### Describe the bug

On latest version, TAB dosen't support showing self coordinates on tab menu 

### Expected behavior

Variable %location% .. to show current location

### Steps to reproduce

N/A

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Where does the wiki say the plugin offers "%location%" placeholder?
