### ISSUE TITLE
Compatibility with Battle Royale X

### ISSUE THREAD

**Issue by Daseldorf** [NEZNAMY/TAB#1158]
### TAB version

4.0.9

### Software causing compatibility issue

Hi best plugin, I got a compatibility issue with BRX, I cant get rid of its scoreboard with TAB, I have tried:
**respect-other-plugins: false
anti-override: true
switching scoreboards
delaying scoreboard 60miliseconds**
and some more things...
Could you help me to use TAB there?
(If it possible only at _BRX lobby world_)
Thanks, cordial greetings.

### Additional info

Thanks

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
I don't understand the issue. Do you want TAB to override that scoreboard or hide it to allow the other plugin to show its own?

**Comment by Daseldorf** [comment]
I want great TAB to override that scoreboard please, thanks

**Comment by NEZNAMY** [comment]
Why don't you disable it in the other plugin? TAB does not offer preventing other plugins from sending scoreboards.

**Comment by NEZNAMY** [comment]
I already told you that TAB does not prevent other plugins from sending scoreboard. You must configure other plugins properly, in this case to make it not send scoreboard if you don't want it. This is your job as a server owner. You can't expect to start a server, install plugins, get plugins devs to configure those plugins and then just grab the money from selling ranks.

**Comment by Tanguygab** [comment]
if it's a bug with BRX, why should TAB fix it?

**Comment by NEZNAMY** [comment]
I already said that TAB does not offer preventing other plugins from sending scoreboard. Compensating for bugs in other plugins is something I did in the past, bug with the rising amount of plugins and their plugins it's just not possible anymore.

If you are a customer, use https://discord.gg/uCTWB7QpXz for support, not github issues.

**Comment by Daseldorf** [comment]
Okay sorry, please remove this issue, yo bro Im not at your discord server, someone shoot me out, Im going to verify again right now. Thanks again, remove this please.

**Comment by Daseldorf** [comment]
Lol
