### ISSUE TITLE
Player groups and placeholders do not work

### ISSUE THREAD

**Issue by BakiDance** [NEZNAMY/TAB#1159]
### Server version

Paper-309 1.20.2 on BungeeCord 1774

### TAB version

4.0.9

### Describe the bug

![2023-11-30_15 58 42](https://github.com/NEZNAMY/TAB/assets/43658058/01f8ecd7-cc4a-4413-8f21-3389e74ba2a7)
![image](https://github.com/NEZNAMY/TAB/assets/43658058/249920fc-5c91-4465-9f93-43a0a0ac989a)

Since updating TAB to 4.0.9, player formats do not work correctly. Relational placeholders also do not work as expected, taking significant time to update. 

Attempting to reload the plugin with /btab reload causes an internal exception.

[another_tab_errors.log](https://github.com/NEZNAMY/TAB/files/13518125/another_tab_errors.log)

### Expected behavior

-

### Steps to reproduce

-

### Additional info

Sidenote: How can I get paid support? I seem to have a new problem with the plugin every time I update it, and at this point I would rather just support the project and hopefully get faster fixes, haha. Thanks for the help.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
#1135 for an instant and free fix.

**Comment by BakiDance** [comment]
Thanks! If I want to support the project monetarily, how can I do so?

**Comment by NEZNAMY** [comment]
You can not.
