### ISSUE TITLE
LuckPerms Placeholders

### ISSUE THREAD

**Issue by NaTorOG** [NEZNAMY/TAB#1162]
### Server version

Waterfall 1.20_R2

### TAB version

4.0.9

### Describe the bug

Additional Informations:
- TAB Bridge on Backends (3.1.8)
- Backends versions (1.19.4 and 1.20.1)
- LuckPerms version (5.4.108)
- LuckPerms Structure (LuckPermsBungee and LuckPerms Spigot have a dedicated database so are not connected)

TAB CONFIG

https://pastebin.com/1TdZhAVS

BUG

https://imgur.com/IxzbnMh.png

After restarting the Proxy server, TAB is not able to retrieve (only in scoreboard) LuckPerms group names/prefixes and in general Placeholders related to LuckPerms. 
/papi parse me %luckperms placeholder% correctly returns an output 

BTAB DEBUG
https://pastebin.com/xiLhYXSx

### Expected behavior

Correctly displaying LuckPerms Prefixes while using TAB on Bungee and Tab Bridge on Backends

### Steps to reproduce

1: When all the backends are active, just restart the proxy server and this will happen

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure it works correctly in /papi parse? You said it only breaks after proxy restart?

**Comment by NaTorOG** [comment]
![immagine](https://github.com/NEZNAMY/TAB/assets/4592301/2903288c-586d-40c3-b920-451ca25c83a3)

**Comment by NEZNAMY** [comment]
Can you try with latest dev builds of both TAB and bridge from github actions?

**Comment by NEZNAMY** [comment]
What's preventing you from swapping waterfall for bungeecord?

**Comment by NEZNAMY** [comment]
Do you think someone would attack and totally destroy your server during that short time frame?

**Comment by NEZNAMY** [comment]
Bump to latest bungeecord version was some time ago now.

**Comment by NEZNAMY** [comment]
But how is it that the other LP placeholders work? In order for placeholders to work in parse command, they must be used somewhere else as well.

**Comment by NaTorOG** [comment]
I don't know, tablist sorting is correctly displayed, for displaying prefixes, instead of parsing lp placeholder in the tablist, in groups.yml I have created static texts to don't consume CPU too much

**Comment by NaTorOG** [comment]
Hello, any update?

**Comment by NaTorOG** [comment]
> I am not able to fix an issue that I am [unable to reproduce](https://www.youtube.com/watch?v=f_7OV-DgOTA) using provided steps. You will need to provide additional information if you want this fixed.
Sure not a problem, just tell me what you need to know.

**Comment by NEZNAMY** [comment]
Reliable steps to reproduce. Start with a clean network from scratch with only TAB, LP and PlaceholderAPI and see if it works there.

**Comment by bridgelol** [comment]
Hey, this happens with all placeholders if your line length is past a certain threshold, aka, the string is being limited before parsing the placeholder, this is a recent development

**Comment by bridgelol** [comment]
For extra context, works on the 4.0.9 release

**Comment by NaTorOG** [comment]
> For extra context, works on the 4.0.9 release

You don't have a bug in 4.0.9 about this?

**Comment by NaTorOG** [comment]
I have switched from %luckperms_highest_group_by_weight% to %group%, repeated the tests serveral times and this didn't happened.

So its correct what bridglelol is saying, if placeholder is too long this happens sometimes

**Comment by bridgelol** [comment]
> > For extra context, works on the 4.0.9 release
> 
> You don't have a bug in 4.0.9 about this?

Indeed

**Comment by NEZNAMY** [comment]
Once you think you came up with reliable steps to reproduce, let me know.

**Comment by bridgelol** [comment]
> Once you think you came up with reliable steps to reproduce, let me know.

Essentially just add a placeholder that's over the scoreboard line character limit and it will just simply wipe this placeholder and not parse it.

**Comment by NaTorOG** [comment]
Im not available to test till 13th December due to exams. I will try in a clean environment @bridgelol If you want to try in a clean env let Neznamy know the result

**Comment by HappyDev345** [comment]
The yellow ping next to the player gets overlapped by the user.. how to fix?

**Comment by NEZNAMY** [comment]
What does that have to do with placeholders not parsing?

**Comment by NEZNAMY** [comment]
Any news @NaTorOG ? Are you still experiencing the issue with latest version and it only affects LP placeholders?

**Comment by NEZNAMY** [comment]
Fixed in TAB-Bridge 5.0.2. Reopen if not.

**Comment by NaTorOG** [comment]
> Any news @NaTorOG ? Are you still experiencing the issue with latest version and it only affects LP placeholders?

Deeply sorry for the delay, I have not been at home lately. Its working perfectly now! Thanks again
