### ISSUE TITLE
Tabsuffix is not aligned properly 

### ISSUE THREAD

**Issue by BakiDance** [NEZNAMY/TAB#1164]
### Server version

Paper-309 1.20.2 on BungeeCord 1774

### TAB version

4.1.0 - SNAPSHOT ( #930 ) #930

### Describe the bug

`align-tabsuffix-on-the-right: true` has no effect; tab suffixes appear directly after the player's username in TAB, rather than on the right side as in previous versions.

### Expected behavior

group tabsuffixes should appear at the end of the player's listing in the tab list.

### Steps to reproduce

1. Have a tabsuffix (eg. tabsuffix: '&7%ping%') defined
2. set `align-tabsuffix-on-the-right: true` under tablist-name-formatting

### Additional info

I understand this may be an issue with the snapshot; I'm just reporting this in case it's an unexpected issue. While reading the wiki pages, trying to fix this myself, I noticed that the wiki page for aligned tabsuffixes is inaccessible (https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Aligned-Tabsuffix).

I'm also noticing that the config section for `yellow-number-in-tablist` is also missing.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
The wiki page you linked was removed and merged into tablist nanme formatting.
yellow number was renamed to playerlist objective, since 1.20.3 will unlock all limits and it will no longer have to be yellow nor a number.
Aligned suffix feature will be removed as well, since the feature was buggy and hard to maintain and 1.20.3 will add this exact feature, which TAB will use instead.

**Comment by NEZNAMY** [comment]
In the meantime, stay on 4.0.9. But even after the update, it will only be visible on 1.20.3+, so old clients will not see it. I don't know if you support 1.8 and such, if not it's all good, if yes, you may want to consider staying on an old version (or potentially ask someone to add the feature back for you and maintain it).

**Comment by BakiDance** [comment]
Will do, thanks for the information!
