### ISSUE TITLE
[Unlimited nametag mode] Flicker on sneak

### ISSUE THREAD

**Issue by EagL3-GIT** [NEZNAMY/TAB#1168]
### Server version

1.20.2

### TAB version

4.1.2

### Describe the bug

The first bug - You can see flickering armorstands above player.
Second one - When you enter a boat, hex colors transform into legacy colors.
(Watch videos, so you can see it properly.)

### Expected behavior

It should not happen.

### Steps to reproduce

Just watch included videos. 

### Additional info

https://github.com/NEZNAMY/TAB/assets/63203158/f88338da-f973-4119-9a01-5ded797f55b7

https://github.com/NEZNAMY/TAB/assets/63203158/b06a1052-e926-4b7e-bd39-a698d8a2ee06

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You forgot to specify client version. Spawn and entity metadata are separated packets and there's a chance frame is rendered between receiving those two. Nothing can be done about that.
For the second "issue", the feature is [disabled for players in boats](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-settings) automatically to avoid position desync.

**Comment by EagL3-GIT** [comment]
Those flickering armorstands were tested with 1.20.3 and .4, about that boat -Its not about position desync, those hex colors while in boat are just basic minecraft legacy colors. So like hex is displayed as closest similiar minecraft color.

**Comment by NEZNAMY** [comment]
Correct, because armor stands are disabled on boats, therefore you can see vanilla nametags with vanilla limitations.

**Comment by EagL3-GIT** [comment]
Then disable-on-boats is not working cause its set to true for me and those lines are still showing as you can see on the video.

**Comment by NEZNAMY** [comment]
Any news @EagL3-GIT ?

**Comment by EagL3-GIT** [comment]
Yep @NEZNAMY, that flickering only happen when u shifting, it was not like that before, I guess its caused by 1.20.3 or 1.20.4 client version update..

**Comment by NEZNAMY** [comment]
I cannot fix client-sided issues. Anything else? Also did you get to understand how disabling on boat works?

**Comment by EagL3-GIT** [comment]
Well I am just guessing, maybe its not client side, anyways I understand that boat thing.

**Comment by NEZNAMY** [comment]
@EagL3-GIT I have tried the sneaking and it's extremely rare, which confirms my theory that the frame was rendered between the 2 packets (spawn + metadata) were received, which is something I can't do much about.
