### ISSUE TITLE
TAB from proxy not displaying correctly on Thermos

### ISSUE THREAD

**Issue by SanderWxD** [NEZNAMY/TAB#1172]
### TAB version

4.1.2

### Software causing compatibility issue

TAB is configured using Layouts on our Velocity proxy (version 3.2.0) with 14 backend (modded) servers. TAB works lovely on all of them, except our ancient FTB Infinity Evolved server, which is on Minecraft 1.7.10, running Thermos-1614 server software. See the screenshot below of what TAB looks like on Thermos and how it's supposed to look like.
![image](https://github.com/NEZNAMY/TAB/assets/71182068/cab4b1ce-ff65-4075-93b3-6c976fccf482)

![image](https://github.com/NEZNAMY/TAB/assets/71182068/934aab2a-6729-48fc-afc6-3f8b419d89ad)

Normally I wouldn't open issue tickets for such old versions of Minecraft, but your Github wiki claimed Thermos compatibility, and we would of course love nothing more than being able to encorporate our 1.7.10 Thermos server with TAB. I've scoured through your detailled wiki but failed to find any mention or fix for the problem I am experiencing.

In case it's necessary, here is our config file: 
[config.txt](https://github.com/NEZNAMY/TAB/files/13629432/config.txt)

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
The [layout](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Layout) feature is only available for 1.8+ players due to massive differences in tablist and I don't think I would be able to deliver a fully working version without any side issues, compatibility issues and so on.

**Comment by SanderWxD** [comment]
I see. Thank you for the fast reply.
Is it then possible to exclude our pre-1.8 server from the TAB layout, so that server can fall back to default/vanilla tablist?
