### ISSUE TITLE
Default white nametag appears

### ISSUE THREAD

**Issue by POCCITO** [NEZNAMY/TAB#1173]
### Server version

Spigot 1.18.2

### TAB version

4.1.2

### Describe the bug

I use this plugin for nametags only (rest is disabled). Ever since 1.20.2 came out (might be the reason but not 100% sure, I got this weird bug that you see the default white name see picture below).
![image](https://github.com/NEZNAMY/TAB/assets/124311204/01ac5c97-a695-40bd-b5ca-830704037fca)

### Expected behavior

The white default nametag should not appear and be invisible.

### Steps to reproduce

Step 1: Install the latest version of TAB onto your server.
Step 2: Disable all features except the nametag.
Step 3: Confiure the groups and nametag itself.
Step 4: On world or server switch (switch to the server where TAB is installed) the white nametag appears.

### Additional info

PS: This is my first report on Github ever, let me know if I did anything wrong. I can disable the tag myself probably but might be worth reporting it.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by POCCITO** [comment]
```# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: false
  header:
  - ''
  footer:
  - ''
tablist-name-formatting:
  enabled: false
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: false
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,dev,senior_mod,mod,helper
  case-sensitive-sorting: true
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    space-between-lines: 0.25
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-condition: '%world%=disabledworld'
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
yellow-number-in-tablist:
  enabled: false
  value: '%ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:bossbarcolor%'
      progress: '100'
      text: '%animation:bossbartext%'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%&7/&4%maxplayers%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: true
primary-group-finding-list:
- owner
- admin
- dev
- senior_mod
- mod
- helper
- celestial
- eternal
- cosmic
- galactic
- solar
- lunar
- content_creator
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
global-playerlist:
  enabled: false
use-online-uuid-in-tablist: true
layout:
  enabled: false```

**Comment by NEZNAMY** [comment]
Send plugin list on your proxy. And just in case, backend as well.

**Comment by POCCITO** [comment]
Proxy:
![image](https://github.com/NEZNAMY/TAB/assets/124311204/ad034631-c73c-4f96-8ca0-f669c31fa076)

Backend:
![image](https://github.com/NEZNAMY/TAB/assets/124311204/bc18344e-5d20-4625-9ac8-19c9fc7669c3)
![image](https://github.com/NEZNAMY/TAB/assets/124311204/4175b340-c7aa-40d4-938d-a0606660aae6)
![image](https://github.com/NEZNAMY/TAB/assets/124311204/29ce347f-f600-4898-bbbe-55482c0ad1a1)

**Comment by NEZNAMY** [comment]
Remove BTLP. You can only have 1 team plugin working at a time.

**Comment by NEZNAMY** [comment]
Right, so the plugin might be conflicting with itself if teams are not disabled on proxy. Too many good reasons for this to not work.

**Comment by POCCITO** [comment]
Ye makes sense!

Thank you for helping out so quickly, appreciate it!

I know it's not recommended but I tried using the API so hide nametags behind walls through proxy but the API is too slow since I want them to hide ever like 1 second or so (and reappear). TAB packets or queued I think, hence why we went back to TAB on server individually (worked super well with hiding nametags through API).

**Comment by NEZNAMY** [comment]
The API isn't slow on proxy. Maybe just your API requests were.
Also we didn't help, since as you know, help is currently [not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). Instead, we fixed a bug.
