### ISSUE TITLE
Scoreboard-Lines are random in 1.20.4

### ISSUE THREAD

**Issue by JaroxCraft** [NEZNAMY/TAB#1175]
### Server version

Paper 1.20.4 (beta) #328

### TAB version

4.1.2

### Describe the bug

Every line in the scoreboard is in a random location

![image](https://github.com/NEZNAMY/TAB/assets/153843016/cd9418dd-e0b9-4351-9c9e-8fc464c020f1)
![image](https://github.com/NEZNAMY/TAB/assets/153843016/fa858a0f-4999-4e72-bfe2-1dc27d261c18)

### Expected behavior

The lines should be sorted like in the config

### Steps to reproduce

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Send your full config.yml, I cannot copy-paste it from your screenshot.

**Comment by JaroxCraft** [comment]
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ''
  - ''
  - 'Ⓐ'
  - ''
  footer:
  - ''
  - '&3&lPing: &e%ping%'
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: ''
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,mod,helper,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    disable-condition: ''
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
playerlist-objective:
  enabled: true
  value: '%lifestealz_hearts%'
  fancy-value: '%lifestealz_hearts%Ⓑ'
  disable-condition: ''
belowname-objective:
  enabled: true
  number: '%health%'
  text: '&cHealth'
  fancy-display-players: '&c%health%'
  fancy-display-default: NPC
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: true
  hidden-by-default: true
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: true
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard-1.20.3+:
      title: Ⓐ
      display-condition: '%player-version-id%>=765'
      lines:
      - '&bRang'
      - '⮩ %luckperms_prefix%'
      - '&bHerzen'
      - '⮩ %lifestealz_hearts%'
      - '&bKills'
      - '⮩ Not ready'
      - '&bPing'
      - '⮩ %ping%'
    scoreboard:
      title: Ⓐ
      lines:
      - '&bRang'
      - '⮩ %luckperms_prefix%'
      - '&bHerzen'
      - '⮩ %lifestealz_hearts%'
      - '&bKills'
      - '⮩ %statistic_player_kills%'
      - '&bPing'
      - '⮩ %ping%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true

**Comment by JaroxCraft** [comment]
i have to do it like that i cant upload .yml files

**Comment by NEZNAMY** [comment]
Yeah I can't copypaste that either. Try again using some paste site.

**Comment by JaroxCraft** [comment]
https://pastebin.com/9aNTypqt

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/ebf6f60c-946a-45e0-9547-c5c9e159b25a)
Looking good to me. You might be using a third party plugin that breaks it. Try without any other plugins.

**Comment by JaroxCraft** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/153843016/d8c3766d-5b76-4fd7-900f-5abc6a3b3bd8)
what should i remove?

**Comment by NEZNAMY** [comment]
None of them should be causing this. Are you running a bungeecord network? Also are you using a vanilla client?

**Comment by JaroxCraft** [comment]
maybe its because of the server version(beta)?

**Comment by NEZNAMY** [comment]
I tried paper 1.20.4 like you said and it works fine. This is not a server software issue.
