### ISSUE TITLE
Relative placeholders don't work sometimes with bridge on bungeecord

### ISSUE THREAD

**Issue by Pyrbu** [NEZNAMY/TAB#1176]
### Server version

Purpur 1.20.1 b2051

### TAB version

TAB 4.1.2 & TAB-Bridge 5.0.1

### Describe the bug

Relative placeholders refuse to parse on some players
![image](https://github.com/NEZNAMY/TAB/assets/75636092/f673f9e0-538d-491f-abf2-ec70720dd8fb)

### Expected behavior

The placeholders to parse normally

### Steps to reproduce

1. Use tab on waterfall with tab bridge installed
2. Set the tagprefix, tagsuffix, tabprefix or tabsuffix to a relative placeholder
3. Get a couple players on the server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Pyrbu** [comment]
Also I forgot to mention that I am using RedisBungee with multiple waterfall servers however this does not seem to affect the bug since some players on the same proxy still have the issue while others who aren't on the same proxy don't.

**Comment by Pyrbu** [comment]
Another screenshot from an admin who had just joined the server, might this be overloading the bridge?
![image](https://github.com/NEZNAMY/TAB/assets/75636092/9e68f384-7312-49ce-ad95-f86634fce75f)

**Comment by NEZNAMY** [comment]
Are the players on both same proxy **and** same backend server? For bridge overload set `debug: true` in config and look for [this message](https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/proxy/PluginMessageHandler.java#L107) in console on join. You can also use spark with all thread profiling to see if bridge is overloaded.

**Comment by Pyrbu** [comment]
No, the players aren't all on the same backend server however when you switch servers all of the same players still have the bug.

Server 1:
![image](https://github.com/NEZNAMY/TAB/assets/75636092/3c5b9d52-2a23-4e4b-a4d3-ff8a19fbfbf1)

Server 2:
![image](https://github.com/NEZNAMY/TAB/assets/75636092/cc1a183b-2026-44a5-b326-548dcf4497cf)

Bridge debug (most of the others are anywhere from 100 to 800 ms):
![image](https://github.com/NEZNAMY/TAB/assets/75636092/8e049861-e657-46dc-878b-a1d9028249fe)

However in the spark profile the placeholder refreshing thread seems to be completely pinned
![image](https://github.com/NEZNAMY/TAB/assets/75636092/f0b54a8b-abef-4455-9de7-f73a50aca1ae)

**Comment by Pyrbu** [comment]
I have also just tried setting the refresh interval of the placeholder to 15000 but that didn't seem to help

**Comment by NEZNAMY** [comment]
Well your relational placeholder is killing it. I'm surprised you didn't get a console warn from bridge, but it's probably due to the extreme amount of requests, not that they would take exceptionally long. This is just how relational placeholders are. I don't know how many online players do you have, but try it again when you have less and/or look into improving its performance. You didn't show further info in the spark report, but it will tell you what exactly took so long.

**Comment by Pyrbu** [comment]
Yeah I realised that after looking around a bit longer in the spark report I'm looking at improving its performance right now. Thanks for the help!

**Comment by NEZNAMY** [comment]
This wasn't help, this is looking to fix a problem and I'm still not sure what to do to prevent it from happening to others in the future.

**Comment by Pyrbu** [comment]
Maybe disable relational placeholders in the tab list altogether? They make sense in name tags but not in the tab list when the server can't determine relation for all players.

**Comment by NEZNAMY** [comment]
This is more complicated than it sounds, you can always use replacements feature to achive  this. The plugin also offers relational placeholder registration on the proxy level, so checking for same server would not exactly be ideal.
