### ISSUE TITLE
Death Count in Tab List

### ISSUE THREAD

**Issue by InstantAva** [NEZNAMY/TAB#1177]
### Server version

1.20.1

### TAB version

4.1.2

### Evidence

I didn't know if there was a way for me to import a players death count in tab? Specifically where the ping is located... I was wondering if there was a way to replace %player_ping% with a death count in config.yml? Let me know if anyone knows a way around this!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#displaying-kill--death-counter-in-tablist ?
How is this a performance issue?

**Comment by NEZNAMY** [comment]
Why did you close the issue? Was the performance issue fixed?
