### ISSUE TITLE
Placeholders not displaying on scoreboard

### ISSUE THREAD

**Issue by Toggl3Combo** [NEZNAMY/TAB#1179]
### Server version

Paper 1.20.4

### TAB version

4.1.2

### Describe the bug

**Placeholders are not showing up on the scoreboard**

![2023-12-19_18 00 19](https://github.com/NEZNAMY/TAB/assets/65083613/f7796fa6-6ba2-413a-9cb4-8a63f0ec42e4)

This is one of the lines I have written in the config file for the scoreboard.
`&a⛨ &fTeam:||&a%betterteams_name%`

And when i run the command to check the placeholder.
`/papi parse me %betterteams_name%`
![2023-12-19_18 06 04](https://github.com/NEZNAMY/TAB/assets/65083613/cd7f4114-9f45-4692-9673-66bcf04e425f)
It returns the right value, so that indicates that the issue is related to the TAB plugin.

### Expected behavior

The plugin should have displayed the placeholder.

### Steps to reproduce

Try using a placeholder from a different plugin. The placeholders provided within the plugin such as `%date%` works.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you using client version 1.20.4 as well? Can you send your full config file?

**Comment by Toggl3Combo** [comment]
> Are you using client version 1.20.4 as well? Can you send your full config file?

Yes I am. Here is my config file.
[config.txt](https://github.com/NEZNAMY/TAB/files/13718460/config.txt)

**Comment by Toggl3Combo** [comment]
> Booted up 1.20.4 server & client and this is what I got with your config: ![image](https://private-user-images.githubusercontent.com/6338394/291664685-8ce07efd-0b8f-4669-b247-566f1ba424fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDY4MTksIm5iZiI6MTcwMzAwNjUxOSwicGF0aCI6Ii82MzM4Mzk0LzI5MTY2NDY4NS04Y2UwN2VmZC0wYjhmLTQ2NjktYjI0Ny01NjZmMWJhNDI0ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTcyMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVjMTA3NGI3NjQ3ZTk5MjNhM2QzYjFhMmM4N2NhZTA1MzJmMDVhZDJjNDBkZjcyOWEwMGFkZjk0NzA0ZGJjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0E98JvrgfLiUCZsWjzVlzckVNbWN_qKJH0kbZ5xMlVU)
> 
> Works as intended. I have also noticed your lines are in the wrong order. Are you absolutely sure you are using vanilla client without any unofficial modifications or resource packs?

I was on lunarclient and it didn't work. Now that I've switched to vanilla it works as intendant. Lunar Client also reverses the order of the lines for some reason as well. I dont know what could be causing this but it's definitely lunar sided.

**Comment by NEZNAMY** [comment]
Lunar has an enormous amount of bugs, never use it when making a bug report to other software.

**Comment by Toggl3Combo** [comment]
Thank you for the amazing support. Sorry for taking up your time.

**Comment by NEZNAMY** [comment]
I did not provide support, [support is not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). I resolved a bug.
