### ISSUE TITLE
Tab reverts to and older version.

### ISSUE THREAD

**Issue by Jermudi** [NEZNAMY/TAB#118]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
v.2.6.5

**Describe the bug**
The tab is perfected and really working and good. But when I relog it suddenly reverts to some older kind of version where there is different text, spaces missing and a placeholder changed. Pretty much it looks like an older test version of mine when I was playing around with the plugin.

**How to reproduce**
Reload -> Relog 

**Expected behavior**
To keep being the tab written in the config.

**Actual behavior**
Changes back to some different text that doesnt really exist anywhere.

**Additional info** (errors, screenshots, ...)
-

**Comment by NEZNAMY** [comment]
You installed the plugin on both bukkit and bungeecord and both instances are trying to handle everything, but you configured them differently and this is the result.

**Comment by Jermudi** [comment]
I'm still confused, how do I fix? After reloading PlaceholderAPI it seems to work aswell. 

Also thank you very much for this insane speed of answering,

**Comment by NEZNAMY** [comment]
Choose either bukkit servers or bungeecord to handle everything and uninstall the plugin from the other.

**Comment by Jermudi** [comment]
Sorry there were 2 tab plugins accidentally on. Thank you very much.
