### ISSUE TITLE
Tab not sorting

### ISSUE THREAD

**Issue by leobaehre** [NEZNAMY/TAB#1180]
### Server version

1.20.4

### TAB version

4.1.2

### Describe the bug

After setting the permission group to every player and setting the corresponding groups in order in the scoreboard-teams.sorting-types. The plugin does not sort the players. /tab debug does give the correct response (at the end of the issue).

```yml
sorting-types:
  - GROUPS:admin,moderator,helper,builder,player
```

Result:
![Screenshot 2023-12-20 181401](https://github.com/NEZNAMY/TAB/assets/78550459/91576374-71d0-4919-9044-01aaeee3753a)
Current tab that is not sorted

### Expected behavior

The plugin should sort the player on the tablist corresponding to their group that is set.

### Steps to reproduce

1. Give players their permission groups
2. Set in the config the order of the groups. And save.
3. Look on the tab after reload or restart of the server

### Additional info

![Screenshot 2023-12-20 180555](https://github.com/NEZNAMY/TAB/assets/78550459/85d5f170-b830-4eab-adc5-d1ff2778c582)
return of /tab debug

config.yml: https://pastebin.com/1DUB9DTt

I set the groups with the TabAPI with my own plugin. This shouldn't be a issue

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You didn't show debug output of the helper. It can explain the reason.

**Comment by leobaehre** [comment]
![Screenshot 2023-12-20 182355](https://github.com/NEZNAMY/TAB/assets/78550459/d0da11c9-b2f2-497c-bed5-5dc953c09e83)
Of course, hope this helps.

**Comment by NEZNAMY** [comment]
Are you using any proxy? BungeeCord / Velocity.

**Comment by leobaehre** [comment]
No

**Comment by NEZNAMY** [comment]
Does sorting work properly if you don't use the API?

**Comment by leobaehre** [comment]
I tried it with the built-in health placeholder. And it has the same result. It does not sort
```yml
sorting-types:
  - "PLACEHOLDER_LOW_TO_HIGH:%health%"
 ```

**Comment by NEZNAMY** [comment]
Show a screenshot of tablist and debug output of 2 players in opposite order.

**Comment by leobaehre** [comment]
I tried it again to make some screenshots. But I came to conclusion that the health sorting does work. My apologies.

It still have the issue with the groups. Are you able to help me with my code in my own plugin if I send it?

I don't have any other plugins that could intervene.

**Comment by NEZNAMY** [comment]
I do not provide java courses. Does sorting by groups work if you don't use the API?

**Comment by leobaehre** [comment]
I am dumb

**Comment by NEZNAMY** [comment]
How am I supposed to translate this for future people who will report the same?
