### ISSUE TITLE
Tab bug with Scoreboard

### ISSUE THREAD

**Issue by VentureStudios** [NEZNAMY/TAB#1181]
### Server version

purpur 1-20-4

### TAB version

4.1.2

### Describe the bug

Hi, I have a problem with the TAB plugin. I configured the Scoreboard correctly also because it worked with previous versions but in the game it appears strange, as if the texts had changed position on their own... I attach photos

![image](https://github.com/NEZNAMY/TAB/assets/70705179/776f9162-7a72-4115-950d-37eb3130f3b7)
![2023-12-22_09 52 08](https://github.com/NEZNAMY/TAB/assets/70705179/6da10ecb-5cae-4fb2-8ac2-d82278466582)

### Expected behavior

scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard1:
      display-condition: '%world%=Spawn'
      title: ' &f你 &#69FF35&lBETTER SURVIVAL '
      lines:
      - ''
      - '&8&l • &#69FF35ɴᴀᴍᴇ: &f%player_name%'
      - '&8&l • &#69FF35ʀᴏʟᴇ: &f%luckperms_prefix%'
      - '&8&l • &#69FF35ɢʀᴀᴅᴇ: &f%luckperms_suffix%'
      - '&8&l • &#69FF35ꜱᴛᴀᴛᴜꜱ: &f%marriagemaster_StatusHeart%'
      - ''
      - '&8&l • &#69FF35ᴛᴇʀʀɪᴛᴏʀʏ: &fᴄᴏᴜɴᴛʀʏ'
      - '&8&l • &#69FF35ᴡᴀʟʟᴇᴛ: &#ffd500%vault_eco_balance_commas%&f🬅'
      - '&8&l • &#69FF35ʙᴀɴᴋ: &#ffd500%bankplus_balance%&f🬅'
      - ''
      - '&8&l • &#69FF35ʜᴇᴀʀᴛꜱ: &#f7020f%aureliumskills_hp%&#f7020f䴐'
      - '&8&l • &#69FF35ᴍᴀɴᴀ: &#00aeff%aureliumskills_mana_int%&f䴙'
      - '&8&l • &#69FF35ɢᴇᴍꜱ: &#30e633%tm_tokens_commas%&f🬆'
      - ''
      - '&7ᴘʟᴀʏ.ꜱᴇʀᴠᴇʀ.ɴᴇᴛ'
    scoreboard2:
      display-condition: '%world%=World_nether'
      title: ' &f你 &#69FF35&lBETTER SURVIVAL '
      lines:
      - ''
      - '&8&l • &#69FF35ɴᴀᴍᴇ: &f%player_name%'
      - '&8&l • &#69FF35ʀᴏʟᴇ: &f%luckperms_prefix%'
      - '&8&l • &#69FF35ɢʀᴀᴅᴇ: &f%luckperms_suffix%'
      - '&8&l • &#69FF35ꜱᴛᴀᴛᴜꜱ: &f%marriagemaster_StatusHeart%'
      - ''
      - '&8&l • &#69FF35ᴛᴇʀʀɪᴛᴏʀʏ: &fɴᴇᴛʜᴇʀ'
      - '&8&l • &#69FF35ᴡᴀʟʟᴇᴛ: &#ffd500%vault_eco_balance_commas%&f🬅'
      - '&8&l • &#69FF35ʙᴀɴᴋ: &#ffd500%bankplus_balance%&f🬅'
      - ''
      - '&8&l • &#69FF35ʜᴇᴀʀᴛꜱ: &#f7020f%aureliumskills_hp%&#f7020f䴐'
      - '&8&l • &#69FF35ᴍᴀɴᴀ: &#00aeff%aureliumskills_mana_int%&f䴙'
      - '&8&l • &#69FF35ɢᴇᴍꜱ: &#30e633%tm_tokens_commas%&f🬆'
      - ''
      - '&7ᴘʟᴀʏ.ꜱᴇʀᴠᴇʀ.ɴᴇᴛ'
    scoreboard3:
      display-condition: '%world%=World_the_end'
      title: ' &f你 &#69FF35&lBETTER SURVIVAL '
      lines:
      - ''
      - '&8&l • &#69FF35ɴᴀᴍᴇ: &f%player_name%'
      - '&8&l • &#69FF35ʀᴏʟᴇ: &f%luckperms_prefix%'
      - '&8&l • &#69FF35ɢʀᴀᴅᴇ: &f%luckperms_suffix%'
      - '&8&l • &#69FF35ꜱᴛᴀᴛᴜꜱ: &f%marriagemaster_StatusHeart%'
      - ''
      - '&8&l • &#69FF35ᴛᴇʀʀɪᴛᴏʀʏ: &fᴛʜᴇ ᴇɴᴅ'
      - '&8&l • &#69FF35ᴡᴀʟʟᴇᴛ: &#ffd500%vault_eco_balance_commas%&f🬅'
      - '&8&l • &#69FF35ʙᴀɴᴋ: &#ffd500%bankplus_balance%&f🬅'
      - ''
      - '&8&l • &#69FF35ʜᴇᴀʀᴛꜱ: &#f7020f%aureliumskills_hp%&#f7020f䴐'
      - '&8&l • &#69FF35ᴍᴀɴᴀ: &#00aeff%aureliumskills_mana_int%&f䴙'
      - '&8&l • &#69FF35ɢᴇᴍꜱ: &#30e633%tm_tokens_commas%&f🬆'
      - ''
      - '&7ᴘʟᴀʏ.ꜱᴇʀᴠᴇʀ.ɴᴇᴛ'
    scoreboard4:
      display-condition: '%world%=World'
      title: ' &f你 &#69FF35&lBETTER SURVIVAL '
      lines:
      - ''
      - '&8&l • &#69FF35ɴᴀᴍᴇ: &f%player_name%'
      - '&8&l • &#69FF35ʀᴏʟᴇ: &f%luckperms_prefix%'
      - '&8&l • &#69FF35ɢʀᴀᴅᴇ: &f%luckperms_suffix%'
      - '&8&l • &#69FF35ꜱᴛᴀᴛᴜꜱ: &f%marriagemaster_StatusHeart%'
      - ''
      - '&8&l • &#69FF35ᴛᴇʀʀɪᴛᴏʀʏ: &fᴏᴠᴇʀᴡᴏʀʟᴅ'
      - '&8&l • &#69FF35ᴡᴀʟʟᴇᴛ: &#ffd500%vault_eco_balance_commas%&f🬅'
      - '&8&l • &#69FF35ʙᴀɴᴋ: &#ffd500%bankplus_balance%&f🬅'
      - ''
      - '&8&l • &#69FF35ʜᴇᴀʀᴛꜱ: &#f7020f%aureliumskills_hp%&#f7020f䴐'
      - '&8&l • &#69FF35ᴍᴀɴᴀ: &#00aeff%aureliumskills_mana_int%&f䴙'
      - '&8&l • &#69FF35ɢᴇᴍꜱ: &#30e633%tm_tokens_commas%&f🬆'
      - ''
      - '&7ᴘʟᴀʏ.ꜱᴇʀᴠᴇʀ.ɴᴇᴛ'

### Steps to reproduce

/

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Your formatting is broken, making it unable to copypaste your config. Are you using vanilla client?

**Comment by VentureStudios** [comment]
I use Feather Client, but it always worked.

**Comment by NEZNAMY** [comment]
We don't do that here. Is it working on vanilla?

**Comment by VentureStudios** [comment]
Hey, is feather bug. Sorry bro..
