### ISSUE TITLE
Delayed placeholders warning

### ISSUE THREAD

**Issue by DeriksonTM** [NEZNAMY/TAB#1182]
### Server version

Purpur 1.20.2

### TAB version

4.1.2

### Stack trace

I use TAB on the Velocity server and TAB-Bridge on the Lobby server, I also use PlaceholderAPI in the tab on the lobby server, for example I made automatic expansion of the tab sheet area when there are more than 22 players, which makes the borders of the player list wider and prettier. There is also on the TPS scale, but for some reason I get such messages in the console of the Lobby server, is there any way to fix it?

### Steps to reproduce (if known)

Start the server and just log in

### Additional info

![2023-12-23_15-19](https://github.com/NEZNAMY/TAB/assets/92043849/0b673cf8-6517-464f-8837-1435a38ad0f8)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [x] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/af51e773-d19a-4f47-acb6-968ec3057f13)
The warn is just a warn suggesting a placeholder needs optimizing and if unattended, it may cause plugin overload. There is nothing I can do about that. Closing your eyes and pretending like you don't see anything (= hiding the message) does not resolve anything.

**Comment by DeriksonTM** [comment]
But what exactly is the plugin loading? PlaceholderAPI or is there a problem in the plugin itself?

> ![image](https://private-user-images.githubusercontent.com/6338394/292625729-af51e773-d19a-4f47-acb6-968ec3057f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzQ2MTIsIm5iZiI6MTcwMzMzNDMxMiwicGF0aCI6Ii82MzM4Mzk0LzI5MjYyNTcyOS1hZjUxZTc3My1kMTlhLTRmNDctYWNiNi05NjhlYzMwNTdmMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjNUMTIyNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWIzY2I5YTZiNDA3YWQ3M2Y0OTU0M2VlNDI2MzY2ZThkMzg4M2Q1ZjJmZDE4OGFmOTNmMzgzOWU1ZjU2MTU1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6_QER9Q9yDQnt8NcvS1qYaF4JSifN6FWT1ls-Z4vUBY) The warn is just a warn suggesting a placeholder needs optimizing and if unattended, it may cause plugin overload. There is nothing I can do about that. Closing your eyes and pretending like you don't see anything (= hiding the message) does not resolve the actual problem.

**Comment by DeriksonTM** [comment]
It's just that when I used TAB only on the Lobby server, without tab-bridge still installed, then everything worked fine without any warnings

**Comment by NEZNAMY** [comment]
It means literally what it says. The placeholder took an extremely long time to return value. Obviously if you don't have TAB installed, it will not be requesting configured placeholders.

**Comment by DeriksonTM** [comment]
And maybe you can tell me if there is any way to solve it. I generally want players to be displayed from all servers, here is my list

Velocity
Lobby
Survival

Is it possible to solve the problem by turning off 

header-footer:
  enabled: true

on the Velocity server, but leave the spy-server enabled.

Then just put TAB and Tab-bridge on each server? Or it won't work that way?

**Comment by NEZNAMY** [comment]
Javascript is generally very slow and should be replaced with java code for best performance. Global playerlist has nothing to with javascript, you decided to use that placeholder by yourself, plugin does not require it.

**Comment by DeriksonTM** [comment]
Thanks! ♥
