### ISSUE TITLE
Incorrect formatting of the scoreboard on version 1.20.4

### ISSUE THREAD

**Issue by itsnotm4sters** [NEZNAMY/TAB#1185]
### Server version

Purpur 1.20.1

### TAB version

4.1.2

### Describe the bug

https://imgur.com/a/4ivEztR

### Expected behavior

The problem that occurs is stated in the title.

### Steps to reproduce

Simply if someone launches Minecraft on version 1.20.4, they may notice this formatting error with the scoreboard.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you are **not** using Lunar client?

**Comment by itsnotm4sters** [comment]
I am using the Feather Client

**Comment by NEZNAMY** [comment]
That one is also buggy. Try vanilla.

**Comment by itsnotm4sters** [comment]
So could the problem be from them? There's no such issue on 1.20.2

**Comment by NEZNAMY** [comment]
Use vanilla to find out.

**Comment by itsnotm4sters** [comment]
I checked on vanilla and the problem no longer exists, even launchers seem to have compatibility issues 🤡
