### ISSUE TITLE
How i can add money

### ISSUE THREAD

**Issue by NickolasX** [NEZNAMY/TAB#1186]
### Server version

1.20

### TAB version

latest

### Evidence

hello how i can add on scoreboard the personal money?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
[Support services are no longer provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).
