### ISSUE TITLE
MySQL Database error 

### ISSUE THREAD

**Issue by Sw1ftLukas** [NEZNAMY/TAB#1188]
### Server version

Spigot 1.20.2

### TAB version

4.1.2

### Stack trace

I have a problem connecting my server to MySQL  

ERROR:

28.12 14:59:13 [Server] INFO [TAB] [WARN] at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitTAB.onEnable(BukkitTAB.java:24)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at TAB v4.1.2.jar//me.neznamy.tab.shared.TAB.create(TAB.java:112)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at TAB v4.1.2.jar//me.neznamy.tab.shared.TAB.load(TAB.java:163)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at TAB v4.1.2.jar//me.neznamy.tab.shared.config.Configs.<init>(Configs.java:80)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at TAB v4.1.2.jar//me.neznamy.tab.shared.config.mysql.MySQL.openConnection(MySQL.java:30)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.NativeSession.connect(NativeSession.java:134)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1430)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:206)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:370)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:101)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:191)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:214)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
28.12 14:59:13 [Server] INFO [TAB] [WARN] at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
28.12 14:59:13 [Server] INFO [TAB] [WARN] java.io.EOFException: SSL peer shut down incorrectly
28.12 14:59:13 [Server] INFO [TAB] [WARN] Failed to connect to MySQL

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You cut the most important part of the error. `java.io.EOFException: SSL peer shut down incorrectly` suggests something is wrong with your database.

**Comment by Sw1ftLukas** [comment]
Yes, I am very sure that everything is correct

**Comment by NEZNAMY** [comment]
Does it keep happening? Do other plugins work with the same database?

**Comment by NEZNAMY** [comment]
No response for 3 weeks, assuming user has died. 
According to the internet it has something to do with different security settings, but we will never find out.
