### ISSUE TITLE
sorting broken on 1.7, works on 1.8

### ISSUE THREAD

**Issue by lolw0tm8** [NEZNAMY/TAB#119]
**Server version**
1.8.8 (1.7.10 with viaversion)

**Plugin version** ("latest" is not a version)
2.6.5

**Describe the bug**
Basically, on 1.7 group sorting is broken in a weird way and just sorts any user randomly, works perfectly on 1.8 though

**How to reproduce**
Have a 1.8.8 server, add 1.7 support with viaversion, connect with 1.7

**Expected behavior**
I expected it to be sorted correctly in 1.7 (LEFT -> RIGHT) and on 1.8 too (UP -> DOWN)

**Actual behavior**
On 1.7 users are randomly sorted, on 1.8 they are correctly sorted

**Additional info** (errors, screenshots, ...)
![eeeeeeeeeeeeeeeeeeeeeee](https://user-images.githubusercontent.com/53062952/76553906-2f054280-6495-11ea-8573-3f577706f50d.png)

**Comment by NEZNAMY** [comment]
Yes, player sorting was added in 1.8

**Comment by lolw0tm8** [comment]
Could you fix group sorting in 1.7 though?

**Comment by NEZNAMY** [comment]
I don't think mojang will add support for sorting on 1.7

**Comment by lolw0tm8** [comment]
Is that a thing you cannot add?

**Comment by NEZNAMY** [comment]
Everything plugins do is because it's possible and authors know how to do it. If you tell me how to sort players on 1.7, i can add it.

**Comment by toxamin** [comment]
While there is no way to "sort" players in 1.7, you could add fake entries to tablist. You could then add these entries to teams, and update the prefixes and suffixes of said teams, thus, providing the effect of sorting.

**Comment by NEZNAMY** [comment]
Already requested #31

**Comment by NEZNAMY** [comment]
Sorting did not exist in 1.7 and therefore cannot be added.
