### ISSUE TITLE
Automatic Scoreboard reload

### ISSUE THREAD

**Issue by Buttercuq** [NEZNAMY/TAB#1192]
### Page link

Empty

### Current text (if applicable)

Empty

### New text

I couldn't find automatic scoreboard reload on the wiki so I used bungee-tab but I couldn't find how to make 2 different leaderboards for 2 servers, I've been browsing the wiki for hours I deleted the flamecord I had today and reinstalled bungeecord but I can't do exactly what I want to do I have a global rank system with Luckperms I want to put 2 different tabs in 1 rank so that when there is a different vip, I want it to automatically show a different scoreboard, but within 1 group In short, if the player rank is: default, the scoreboard he sees in the lobby and the scoreboard he sees in the faction will be different, if he becomes a vip, I want the image to change automatically in the lobby and faction.

**Comment by NEZNAMY** [comment]
The requested guide is already available at https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#example-1---per-world-scoreboards. All you have to do is to read the note saying to use %server% instead of %world%.

**Comment by Buttercuq** [comment]
> The requested guide is already available at https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#example-1---per-world-scoreboards. All you have to do is to read the note saying to use %server% instead of %world%.

Thank you, I was blinded, as a last question, if I type 2 scoreboards in 1 groups in luckypermset, will the bunnge automatically show 2 scoreboards in faction and lobby?

**Comment by NEZNAMY** [comment]
You cannot see 2 scoreboards at the same time. Support is not provided. Please don't abuse the issue tracker for support.

**Comment by Buttercuq** [comment]
> You cannot see 2 scoreboards at the same time. Support is not provided. Please don't abuse the issue tracker for support.

I'm sorry, I understand.
