### ISSUE TITLE
TAB's list doesn't work with Luckperms

### ISSUE THREAD

**Issue by complist** [NEZNAMY/TAB#1194]
### TAB version

4.0.9

### Software causing compatibility issue

I am trying to make so the list of player is sorted by their luckperms ranks.
like owner will be at the top
than manager and on and on
but i don't know how

### Additional info

i am running version 4.0.9 and if the problem requires a new version pls explain how do i update mine

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
This is not a compatibility issue. 4.0.9 is not latest either. Support is not provided in github issues.
