### ISSUE TITLE
Heads not visible when server is in offline mode

### ISSUE THREAD

**Issue by ABHI01E** [NEZNAMY/TAB#1195]
### Server version

Purpur 1.19.4

### TAB version

4.1.2

### Describe the bug

So i want to create a tab layout with custom head skins. When i added the values like mineskin:383747683. It doesn't show the custom head skins in the tablist. 

### Expected behavior

I expect it to show the custom head skins as intended in the wiki.

### Steps to reproduce

1. Edit the config.yml in the layout section
2. Change the default-skin option with default-skin: mineskin:383747683
3. Adding my layout : 
`  layouts:
    default:
      fixed-slots:
      - '1|&e&lPlayers &7(%online%) &f:|mineskin:1307755006'
      - '61|&6&lInformasi &f:|mineskin:1074335506'
      groups:
        players:
          slots:
          - 1-60`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
It literally took me like 20 minutes of testing before I decided to read the description of the skin on mineskin (https://mineskin.org/383747683) and the title literally says "Dark Gray", just like the default default-skin, and guess what - it indeed is dark gray.
![image](https://github.com/NEZNAMY/TAB/assets/6338394/7084002b-708c-4dc9-bcd5-7a1268bd0f8e)
There is absolutely no way that your server is offline mode, which [causes heads to not show](https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#8---how-to-make-player-heads-visible-in-tablist), right?

**Comment by ABHI01E** [comment]
> It literally took me like 20 minutes of testing before I decided to read the description of the skin on mineskin (https://mineskin.org/383747683) and the title literally says "Dark Gray", just like the default default-skin, and guess what - it indeed is dark gray. ![image](https://private-user-images.githubusercontent.com/6338394/293582433-7084002b-708c-4dc9-bcd5-7a1268bd0f8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjE4ODQsIm5iZiI6MTcwNDEyMTU4NCwicGF0aCI6Ii82MzM4Mzk0LzI5MzU4MjQzMy03MDg0MDAyYi03MDhjLTRkYzktYmNkNS03YTEyNjhiZDBmOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTUwNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODE5M2IyNzgyYzU5ZDAxMjE2M2NhNjY3MDM0MTU2YTJlMjc0ZDFiNjAwZWQwZjhkOWY4NmJiZDQxYzEyYjBhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PFMR59TOXgh84hCxTif92aVhpXFAX7vvx6PKj6TN7Lw) There is absolutely no way that your server is offline mode, which [causes heads to not show](https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#8---how-to-make-player-heads-visible-in-tablist), right?
Yes my server is offline mode, thanks for the help.

**Comment by NEZNAMY** [comment]
That's it? I didn't expect such an advanced user to make a beginner mistake. Also I did not help, [support is not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).
