### ISSUE TITLE
After a Velocity Update for version 1.20.3 TAB reverses scoreboard,

### ISSUE THREAD

**Issue by Nicola001** [NEZNAMY/TAB#1197]
### Server version

Paper 1.8.8

### TAB version

4.1.2

### Describe the bug

The scoreboard is reversed,

### Expected behavior

I just updated the .jar of the TAB plugin and in the console it tells me this:

**[22:40:32] [Server thread/INFO]: [TAB] [0;33;1mPerforming configuration conversion from 4.0.9 to 4.1.0[m**

i have 4.1.2 version of TAB

### Steps to reproduce

I updated the velocity .jar and restarted the server, then updated by removing the old TAB .jar and put the new one(4.1.2) and then restarted the server.

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/40999523/79d636ee-d710-4965-a32b-c1728c00d708)

In the image on the right I put the numbers as they are now, on the left I put the numbers as they should be so in the footer (4)mc.monoper.com, above (1) Name:, in the middle(2) Rank: and (3) Players:

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you 100% sure you are using vanilla client? You just described a bug shared among multiple custom clients, such as lunar and feather.

**Comment by Nicola001** [comment]
I'm using Lunarclient Yes, server jar is paperspigot, the problem is Lunar?

**Comment by NEZNAMY** [comment]
Well I literally said that.

#1185
#1181

**Comment by Nicola001** [comment]
Ok thanks man

**Comment by NEZNAMY** [comment]
You have nothing to thank for, I am not going to fix Lunar bugs.
