### ISSUE TITLE
TAB with Haonick

### ISSUE THREAD

**Issue by BystricTV** [NEZNAMY/TAB#1199]
### TAB version

4.1.2

### Software causing compatibility issue

TAB

### Additional info

I don't understand how to configure, because I put the condition (https://github.com/NEZNAMY/TAB/wiki/How-to-display-name-from-nickname-plugins#tip-2---sorting-nicked-players-with-lowest-priority) but when I do /haonick:random i.e. to put a nickname it doesn't just change my name in tabs and tags but the prefix always remains and the draw doesn't work

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Your message is unclear. Does the nickname in tablist and nametag change or not? Prefix/suffix does not change, because plugin is using the value that is configured regardless of output of a placeholder.

**Comment by BystricTV** [comment]
> Your message is unclear. Does the nickname in tablist and nametag change or not? Prefix/suffix does not change, because plugin is using the value that is configured regardless of output of a placeholder.

Yes, that changes because I put cutomtab and customtagname with %haonick_name%, I thought changing the prefix would also work, the fact is that the draw doesn't work but if the prefix doesn't change it seems a bit useless to me

**Comment by NEZNAMY** [comment]
Well what is the prefix supposed to change to? The plugin can't read your mind and remove player's prefix only because placeholder X's value is Y. You can use conditional placeholders and only display prefix if player is not nicked. None of this is a compatibility issue. The plugin works as described.

**Comment by BystricTV** [comment]
> Well what is the prefix supposed to change to? The plugin can't read your mind and remove player's prefix only because placeholder X's value is Y. You can use conditional placeholders and only display prefix if player is not nicked. None of this is a compatibility issue. The plugin works as described.

But will you calm down?? I opened here because 1. it was poorly written and 2. because I couldn't open in another section, but do you want to calm down? I asked for support for something and you have to treat me like this?

**Comment by NEZNAMY** [comment]
Support is [not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). You linked a guide about sorting, of course it won't say anything about prefixes.

**Comment by BystricTV** [comment]
> Support is [not provided](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). You linked a guide about sorting, of course it won't say anything about prefixes. I was just trying to understand your question, because it wasn't clear to me.

Okay and for this I thank you for telling me but at least have a little more patience please

**Comment by NEZNAMY** [comment]
Sorry, but after 10000+ tickets throughout the last few years my patience is all gone.

**Comment by BystricTV** [comment]
I understand well but did you want to make the decision to create such a large plugin? Now you better understand that there are and will be even worse users so I would say that your patience will have to return

> Sorry, but after 10000+ tickets throughout the last few years my patience is all gone.

**Comment by BystricTV** [comment]
Now I thank you for your response because you seem available and I would like to end the discussion here please, thank you for your support

**Comment by NEZNAMY** [comment]
> I understand well but did you want to make the decision to create such a large plugin?

Actually no. Originally I uploaded the plugin to spigot as a joke with no expectations whatsoever.

**Comment by BystricTV** [comment]
> > I understand well but did you want to make the decision to create such a large plugin?
> 
> Actually no. Originally I uploaded the plugin to spigot as a joke with basic functionality and no expectations whatsoever. You also need to understand that by no law am I enforced to provide high quality support to anyone in the world who asks for it.

Of course I understand it but your reputation would be greatly diminished.. and honestly all the support I have received from the plugins has always been concluded well so you know.. but whatever

**Comment by BystricTV** [comment]
Can we end the discussion here? I think we're both wasting our time

**Comment by NEZNAMY** [comment]
> Of course I understand it but your reputation would be greatly diminished

My reputation is gone for a long time now.

> and honestly all the support I have received from the plugins has always been concluded well so you know

Receiving support from other plugin authors is something you should be thankful for, not expect. The plugins were also most likely smaller, which means the authors most likely don't average 20 support requests a day.

> Can we end the discussion here? I think we're both wasting our time

Sure, I was just reacting to your statements.

**Comment by BystricTV** [comment]
> > Of course I understand it but your reputation would be greatly diminished
> 
> My reputation is gone for a long time now.
> 
> > and honestly all the support I have received from the plugins has always been concluded well so you know
> 
> Receiving support from other plugin authors is something you should be thankful for, not expect. The plugins were also most likely smaller, which means the authors most likely don't average 20 support requests a day.
> 
> > Can we end the discussion here? I think we're both wasting our time
> 
> Sure, I was just reacting to your statements.

Well.. I can only say, recover then, you are not obliged to carry on the plugin, there are also breaks in life
