### ISSUE TITLE
Showing incorrect ping value

### ISSUE THREAD

**Issue by AdamFriska** [NEZNAMY/TAB#12]
**Server version**
1.13.2

**Plugin version** ("latest" is not a version)
2.4.11

**Describe the bug**
it shows 500ms up to 2000ms, for players who join the server
( it will show their actual ping after 2minutes )
as an example, i'm having 1500 ping, and every 20 or maybe 30 seconds it'll start to update
from 1500ms -> 1300ms -> 1200ms -> 900ms -> 500ms -> 200ms ( until it reaches 34ms which is my stable or actual ping )

**Expected behavior**
Showing correct ping

**Actual behavior**
Showing incorrect ping value/display,

Thank you!

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Plugin is currently using spigot's ping measuring system which got broken in about 1.11. You can use paper which has this fixed.

**Comment by AdamFriska** [comment]
can my server still run normally with paper?

**Comment by NEZNAMY** [comment]
Yes

**Comment by AdamFriska** [comment]
thank you!

**Comment by AdamFriska** [comment]
any Paper 1.13.2 will do right?

**Comment by NEZNAMY** [comment]
Yes
