### ISSUE TITLE
Per World Playerlist join issue

### ISSUE THREAD

**Issue by freddycor** [NEZNAMY/TAB#1200]
### Server version

1.8.8

### TAB version

4.1.2

### Describe the bug

Hi, I'm using the option "per world playerlist" and it works well, the only problem is that when a new player joins the server. All the other player that are not supposed to see him, can see his name in tab. As soon as he changes world it's all good, but until that he's visible from all the players in the server

If he returns to the lobby after joining another world it's all ok too. The problem is only present on first join

Thanks in Advance

### Expected behavior

The player in the lobby world (first join world) should not be visible from the players in the other worlds

### Steps to reproduce

- Enter Server
- Enter a world that is not sharing playerlist with the world where you join in
- Take another account
- Join the server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by freddycor** [comment]
Sorry I missed the Server type, It's Paper 1.8.8

**Comment by NEZNAMY** [comment]
Try without any other plugins.

**Comment by freddycor** [comment]
If someone one day asks the same question, It was "WorldResourcePacks" plugin causing this issue

Thanks for the Help!

**Comment by freddycor** [comment]
I discovered that SkinsRestorer was the main cause of this, other than WorldResourcePakcs. Considering that both the plugins are responsible of injecting resourcepacks or skins to the player, maybe it make conflicts with TAB going out of sync, don't know. I'm saying this because both the resourcepack and skins provoke a little lag client-side when they apply skin/pack.

**Comment by NEZNAMY** [comment]
SkinsRestorer sends respawn packets and it looks like it doesn't check whether player is hidden to viewer or not.

**Comment by freddycor** [comment]
Yeah I tried it using only one parameter too. 
However I'll try it again using multiple way to get the right player.
For the anti-override I checked it, It's all on true, even because I'm using only TAB on the server atm.

**Comment by NEZNAMY** [comment]
What does that have to do with per world playerlist though? Are you using vanilla client? Are you using unlimited nametags? Should still be compatible, but disabling it for testing won't hurt. Are you sure your code ran fully without an error?

**Comment by freddycor** [comment]
Oooooh wait a sec, So HideNameTag is used to hide the nametag on top of the player, and not the Tab one?
Omg I'm so stupid yeah, I see it working in the Nametag

So there is no way to access tab playerlist trough the API?

**Comment by freddycor** [comment]
Is there a way, if you know, to hide player in tab to another player using bukkit api? Or I have to abandon this project?

Thanks a lot for the help and sorry for misunderstanding "hideNameTag"

**Comment by NEZNAMY** [comment]
... and this is why support is no longer provided.
The API only allows you to alter behavior of existing features. It does not allow you to do things outside of scope of the plugin. Per world playerlist feature does not have an API, because back when feature requests were still available, nobody requested this, because there was no reason to. I am not going to add new API to compensate for bugs in other plugins. I did that in the past, but it's gone too far over the years.

You can use `Player#hidePlayer(Player)` Bukkit API method, which is what the plugin also uses.

**Comment by freddycor** [comment]
Thank you very much for the help and the patience, you saved me!
