### ISSUE TITLE
ViaVersion + Tab [PLATFORM NOT LOADED]

### ISSUE THREAD

**Issue by Flintstqne** [NEZNAMY/TAB#1201]
### Server version

Pufferfish 1.20.4

### TAB version

4.1.2 (Backend Server)

### Stack trace

07.01.2024 - 22:59:06 - [TAB v4.1.2] An error was thrown when executing task
07.01.2024 - 22:59:06 - java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
07.01.2024 - 22:59:06 - 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
07.01.2024 - 22:59:06 - 	at LuckPerms-Bukkit-5.4.113.jar//com.viaversion.viaversion.api.Via.manager(Via.java:84)
07.01.2024 - 22:59:06 - 	at LuckPerms-Bukkit-5.4.113.jar//com.viaversion.viaversion.api.Via.getAPI(Via.java:40)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.hook.ViaVersionHook.getPlayerVersion(ViaVersionHook.java:36)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.backend.BackendTabPlayer.<init>(BackendTabPlayer.java:32)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.<init>(BukkitTabPlayer.java:60)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.createPlayer(BukkitEventListener.java:45)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.createPlayer(BukkitEventListener.java:20)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:24)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173)
07.01.2024 - 22:59:06 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$3(CpuManager.java:98)
07.01.2024 - 22:59:06 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
07.01.2024 - 22:59:06 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
07.01.2024 - 22:59:06 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
07.01.2024 - 22:59:06 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
07.01.2024 - 22:59:06 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
07.01.2024 - 22:59:06 - 	at java.base/java.lang.Thread.run(Thread.java:840)

### Additional info

**ViaVersion on a Velocity Proxy:** Version 4.9.3

Another thing to note: I tried following the Compatibility wiki page to parse my player-version and see if anything was happening, but TAB is not responding to any commands.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
if TAB is on the backend, use ViaVersion there as well, not on the proxy

**Comment by Flintstqne** [comment]
`07.01.2024 - 23:39:40 - [TAB v4.1.2] An error was thrown when executing task
07.01.2024 - 23:39:40 - java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
07.01.2024 - 23:39:40 - 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//com.viaversion.viaversion.api.Via.manager(Via.java:84)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//com.viaversion.viaversion.api.Via.getAPI(Via.java:40)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.hook.ViaVersionHook.getPlayerVersion(ViaVersionHook.java:36)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.backend.BackendTabPlayer.<init>(BackendTabPlayer.java:32)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.<init>(BukkitTabPlayer.java:60)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.createPlayer(BukkitEventListener.java:45)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitEventListener.createPlayer(BukkitEventListener.java:20)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.platform.EventListener.lambda$join$0(EventListener.java:24)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.run(CpuManager.java:173)
07.01.2024 - 23:39:40 - 	at TAB v4.1.2.jar//me.neznamy.tab.shared.cpu.CpuManager.lambda$submit$3(CpuManager.java:98)
07.01.2024 - 23:39:40 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
07.01.2024 - 23:39:40 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
07.01.2024 - 23:39:40 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
07.01.2024 - 23:39:40 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
07.01.2024 - 23:39:40 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
07.01.2024 - 23:39:40 - 	at java.base/java.lang.Thread.run(Thread.java:840)
`

I'm pretty sure the same stacktrace error is occurring, with it now on the backend with TAB.

**Comment by Tanguygab** [comment]
can you send the full server logs? maybe ViaVersion failed to load correctly?

**Comment by Flintstqne** [comment]
https://mclo.gs/S8X7JON

**Comment by Tanguygab** [comment]
[23:38:35] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.9.3-SNAPSHOT
[23:38:35] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.20.3/1.20.4 (765)
[23:38:35] [Server thread/WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version!
[23:38:35] [Server thread/WARN]: [ViaVersion] Please remember that ViaVersion only adds support for versions newer than the server version.
[23:38:35] [Server thread/WARN]: [ViaVersion] If you need support for older versions you may need to use one or more ViaVersion addons too.
[23:38:35] [Server thread/WARN]: [ViaVersion] In that case please read the ViaVersion resource page carefully or use https://viaversion.com/setup
[23:38:35] [Server thread/WARN]: [ViaVersion] and if you're still unsure, feel free to join our Discord-Server for further assistance.

**Comment by Flintstqne** [comment]
My hub is running the same configurations and server file (same version as well) as my main (the log you just read) and TAB works on the hub but not my main.

**Comment by NEZNAMY** [comment]
Viaversion did not load, because it has nothing to offer for your server version. Just like the message says, if you want older client support, install addons as well, otherwise remove the plugin.

**Comment by NEZNAMY** [comment]
@Flintstqne can you send your full startup log and upload your TAB & LuckPerms jars? The stack trace suggests via classes are in these plugins, while they shouldn't be.

**Comment by NEZNAMY** [comment]
No response for a week, assuming user has died and I was right.
