### ISSUE TITLE
Relational PAPI placeholders not parsed for self tag when using a proxy setup.

### ISSUE THREAD

**Issue by Jake-Moore** [NEZNAMY/TAB#1203]
### Server version

Tab-Bridge-5.0.2 on Pufferfish 1.19.4

### TAB version

4.1.3 on Velocity 3.3.0 b316

### Describe the bug

I'm on TAB 4.1.3 (on Velocity) from compiling pull request #1202 from the current Github master branch. 

My spigot server is running Pufferfish+ for MC 1.19.4 using TAB-BRIDGE 5.0.2

Everything is working except on clients that allow players to view their own player tag above their head. These display nearly correctly, where regular placeholders are parsing, but not the relational ones.
![image](https://github.com/NEZNAMY/TAB/assets/38172916/7888b81d-fad7-48a9-b29b-2b640425f785)

That tagsuffix has 2 placeholders, one relational and one standard placeholder. (For color and name). The name placeholder is parsing correctly (-> 'test'), but the relational is only parsing on other player's tags.

### Expected behavior

The expected behavior would be to parse the placeholder in the tag using the player as both player one and player two.
For reference, this is the same placeholder combo when using TAB 4.1.2 on spigot (no proxy setup), with the same plugins and placeholders in use on the spigot server.
![image](https://github.com/NEZNAMY/TAB/assets/38172916/7699aeb5-3195-4c7c-bab9-b9311a2d0a63)

### Steps to reproduce

1. Use a client other than vanilla that allows you to see your own tag above your head in F5 mode. (Like Feather or Labymod)
2. Set up a Velocity proxy and spigot server using TAB-Bridge
3. Set the tagsuffix (or otherwise) on the Velocity TAB `groups.yml` config to include a relational placeholder.
4. Join the spigot server to see that the relational placeholders work for other player's tags, but not your own in F5.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure your relational placeholder is not programmed to ignore the request when both players are the same? Try /papi parserel and input the same player twice.

**Comment by Jake-Moore** [comment]
That’s the first thing I tried. Expected output is “&a” as shown in the second screenshot above.

```Java

// %rel_gangs_relation%
    @Override
    public String onPlaceholderRequest(Player one, Player two, String params) {
        if (one == null || two == null) {
            return "&c"; // We require both Players to be online
        }

        if (params.equalsIgnoreCase("relation")) {
            Gang gangOne = GangsAPI.getGang(one, false);
            Gang gangTwo = GangsAPI.getGang(two, false);
            if (gangOne == null || gangTwo == null) { return "&c"; }

            if (gangOne.getId().equals(gangTwo.getId())) {
                return "&a";
            }else {
                return "&c";
            }
        }

        return null;
    }
```
As long as both player variables are not null, a color is returned.

**Comment by Jake-Moore** [comment]
One thing to note, given the groups configuration in TAB on the proxy, all 6 properties (tab/tag pre/suffix + above/below name) are set to luckperms meta placeholders). 
This works on TAB spigot and on TAB velocity for the non relational placeholder in the tag suffix. But that relational placeholder %rel_gangs_relation% is a placeholder within another placeholder parsed for the tag suffix.

**Comment by Tanguygab** [comment]
Does it work if you use the relational placeholder directly in the tagsuffix without the meta placeholder?

**Comment by Jake-Moore** [comment]
I will test as soon as possible.

**Comment by NEZNAMY** [comment]
Can you try with 4.1.2 release?

**Comment by NEZNAMY** [comment]
Try new build.

**Comment by Jake-Moore** [comment]
### Testing Direct Placeholders (no change)

![IMG_6220](https://github.com/NEZNAMY/TAB/assets/38172916/69e8f6a3-4961-4b5b-8644-61455de992e4)

I swapped the placeholders for distinction from other screenshots.

this is in groups.yml
`tagsuffix: ‘%rel_gangs_relation%%player_name%’`

**Comment by NEZNAMY** [comment]
With new build?

**Comment by Jake-Moore** [comment]
Apologies I’m working from my phone so GitHub doesn’t update unless I refresh.

That was on the old 4.1.3 build from my PR.

this is from 4.1.2 (working)
![IMG_6221](https://github.com/NEZNAMY/TAB/assets/38172916/75977112-ef88-4060-92bb-d71b6e73d23d)

Let me try and build the new jar real quick. 
can you review the PR btw, it adjusts how the header footer section parses per-server keys, allowing server groups from the global playlist to be used.

**Comment by NEZNAMY** [comment]
I merged it already.

**Comment by Jake-Moore** [comment]
It’ll have to be a bit longer before I can build the new jar and test.

**Comment by Jake-Moore** [comment]
**Latest build is working. Issue can be Resolved.**

On a separate note:
the gradle subproject for fabric 1_18_2, namely the `Loader_1_18_2` class had issues resolving minecraft libraries. Both the 1_14_4 and 1_19_2 subprojects compiled fine, but this one couldn't find the minecraft libraries on a fresh git clone.
I was able to compile locally by removing that method, but this might pose an issue for future contributors if that subproject errors for them too.

![image](https://github.com/NEZNAMY/TAB/assets/38172916/26aaee8c-bc18-4cbf-8cfe-cbf06a293cf4)

I have prompts from IntelliJ for both the 1_14_4 loom and 1_19_2, just not the 1_18_2
![image](https://github.com/NEZNAMY/TAB/assets/38172916/cbc27a26-5f5a-4696-adc6-3e3e21a9a08b)

**Comment by Jake-Moore** [comment]
Thank you for the quick fix and PR review.

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/6d131995-3f5f-41d0-b3bb-3d4dae753196)
Works for me, as well as github actions.

**Comment by Jake-Moore** [comment]
Odd, must be a broken gradle cache on my end or something.
