### ISSUE TITLE
ERROR CONSOLE BUNGEECORD

### ISSUE THREAD

**Issue by trazodana** [NEZNAMY/TAB#1206]
### Server version

LAEST

### TAB version

BUILD 984

### Describe the bug

[21:06:45 WARN] [TAB]: Player Cxotinha's group (none) is not in sorting list! Sorting list: dono,gerente,admin,moderador,ajudante,equipe,youtuber,miniyt,imperador,rei,infante,duque,default. Player will be sorted on the bottom.

....

CONFIG:

  sorting-types:
  - GROUPS:dono,gerente,admin,moderador,ajudante,equipe,youtuber,miniyt,imperador,rei,infante,duque,default
  - PLACEHOLDER_A_TO_Z:%player%

### Expected behavior

no have error

### Steps to reproduce

updated

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
So you want me to remove the warning because you don't want to use a permission plugin?

**Comment by trazodana** [comment]
> Então você quer que eu remova o aviso porque não deseja usar um plugin de permissão?

Note that I commented that the problem started after updating.

And yes, I use permission plugin (luckperms), both on bungeecord and on the backend servers. I applied it to the config according to the extensive wiki to consider the backend server groups

**Comment by trazodana** [comment]
I already solve. Previously default was enough to mean no group. Now that it's updated, it requires you to enter none to represent a player without a group.

Thanks.

**Comment by NEZNAMY** [comment]
> > Então você quer que eu remova o aviso porque não deseja usar um plugin de permissão?
> 
> Note that I commented that the problem started after updating.
> 
> And yes, I use permission plugin (luckperms), both on bungeecord and on the backend servers. I applied it to the config according to the extensive wiki to consider the backend server groups

Yes, the warn was added a week ago in https://github.com/NEZNAMY/TAB/commit/1ac6d906330c9f09c3635090bfdbe6489ae492b3 to prevent people from asking for help when they didn't configure sorting properly. Sadly it has the opposite effect.
If you have LP on bungeecord, it should never initialize your group to "none". The only exception is if you accidentally enable `use-bukkit-permission-manager` without knowing what it does. Is this your case?
