### ISSUE TITLE
`%maxplayers%` placeholder doesn't work after TAB update

### ISSUE THREAD

**Issue by ChefMC** [NEZNAMY/TAB#1208]
### Server version

Paper 1.12.2 & Velocity 3.2

### TAB version

4.1.2

### Describe the bug

`%maxplayers%` placeholder doesn't work, it just shown as `%maxplayers%`

### Expected behavior

`%maxplayers%` should be a number of max players capacity, 
either it's installed on Velocity/BungeeCord or Paper/Spigot

### Steps to reproduce

Install plugin and use this placeholder in Tab header

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
That's 3 years ago. If you want to stay outdated, stay outdated. Otherwise, use PlaceholderAPI or just manually insert the number into your config.

**Comment by NEZNAMY** [comment]
Because you can put the number in manually anyway. It's not like you change max player count every day.
