### ISSUE TITLE
[Velocity] [MiniMessage] hex-colors displaying as legacy colors

### ISSUE THREAD

**Issue by Sybsuper** [NEZNAMY/TAB#1210]
### Server version

Velocity 3.3.0-SNAPSHOT (with folia 1.20.2 using tab-bridge v5.0.2)

### TAB version

4.1.2

### Describe the bug

Tab gradient does not match tag gradient, even though they are set to the same values.
Tag nametag:
![image](https://github.com/NEZNAMY/TAB/assets/36895604/fc7cd6b7-c637-478b-8acd-74defcb7639d)
Tab nametag:
![image](https://github.com/NEZNAMY/TAB/assets/36895604/8340b6a5-33d4-435c-a748-fb05bc998e3f)

As you can see in the screenshot, the tab nametag has been reduced to named (pre 1.16) colors. Even though, I am using a 1.20.2 client in the screenshots provided.

### Expected behavior

Tab name should be the same as tag name.

### Steps to reproduce

set a prefix to `<gradient:#ffffff:#000000><bold>` and a suffix to `</gradient>` in both tab and tag:
```
/btab player <player> tabprefix <gradient:#ffffff:#000000><bold>
/btab player <player> tagprefix <gradient:#ffffff:#000000><bold>
/btab player <player> tabsuffix </bold></gradient>
/btab player <player> tagsuffix </bold></gradient>
```

### Additional info

I've done some testing and it seems like setting the prefix to `<#ffffff>&l` and suffix to `</#000000>` (in tab and tag) does work the same in tab and tag name!

Is there a more general issue with the MiniMessage formatting? I'd think not as the tag is displayed correctly.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Send your config.yml.

**Comment by Sybsuper** [comment]
worked, thank you for the quick response
