### ISSUE TITLE
ViaVersion Bug

### ISSUE THREAD

**Issue by Yomamaeatstoes** [NEZNAMY/TAB#1214]
### Server version

This server is running Folia version git-Folia-"1e5e215" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1e5e215) You are running the latest version Previous version: git-Paper-318 (MC: 1.20.2)

### TAB version

4.1.2

### Describe the bug

unknown cause, perhaps the same issue as ( https://github.com/NEZNAMY/TAB/issues/1211 ) 

### Expected behavior

No error

### Steps to reproduce

unknown

### Additional info

I have this giant error log - https://mclo.gs/l0wluJK#L2401

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
try without TAB and see if it still happens

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/735e395c-c09a-4fa9-89fa-339f41ebb4bc)

**Comment by Yomamaeatstoes** [comment]
> > Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17
> 
> TAB doesn't touch blocks & items so it's probably due to another plugin. Try without TAB and see if it still happens

It seems I posted my whole log. https://mclo.gs/fqkF6Rw I did see those missing block things with the achievements so I am still looking into that.

**Comment by Yomamaeatstoes** [comment]
I thought I had to check all the boxes to continue. Although that is a good 2 step verification to see if people actually followed the guidelines.

**Comment by Tanguygab** [comment]
> > > Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17
> > 
> > TAB doesn't touch blocks & items so it's probably due to another plugin. Try without TAB and see if it still happens
> 
> It seems I posted my whole log. https://mclo.gs/fqkF6Rw I did see those missing block things with the achievements so I am still looking into that. 

you're missing the top part of the error
with what you sent, we only know that a packet error occurred, and since TAB listens to packets, it's listed in the stacktrace

**Comment by NEZNAMY** [comment]
Looks like removing TAB to find out if it keeps happening is a super complicated task.

**Comment by NEZNAMY** [comment]
No reponse for a week, assuming user has died. This is clearly a ViaVersion issue and TAB does not even send block packets.
