### ISSUE TITLE
Cat's name tag and others

### ISSUE THREAD

**Issue by imtorich** [NEZNAMY/TAB#1215]
### Server version

Plazma 1.20.1 latest

### TAB version

4.1.2

### Describe the bug

If you name pets such as a cat AND so on, no name will be displayed above them until the TAB plugin is turned off.

### Expected behavior

Stable

### Steps to reproduce

Tag
Anvil
Name
Wildcat, and other certain creatures
= bug

### Checklist

- [x] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-2---prefixsuffix-on-pets ?

**Comment by imtorich** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-2---prefixsuffix-on-pets ?

Oh, thank you so much :)
I apologize.
