### ISSUE TITLE
Crouching changes the color of a nametag in unexpected ways

### ISSUE THREAD

**Issue by xZinio** [NEZNAMY/TAB#1217]
### Server version

Paper git-Paper-384 in MC 1.20.4 on Java 21

### TAB version

4.1.2

### Describe the bug

When I (or any player with a custom NameTag defined using TAB) crouch, the color does not change at all at first. Then once you uncrouch, the color changes to a greyer, darker version of the original color like you would expect when crouching, but not when standing normally again. From here on, the colors seem to be "inverted". When you crouch the color is normal and when uncrouched you get the dark color.

I tested it a little, but it turns out that you still cannot see the nametag through walls when crouched, like you would want it to be.

## Normal
![Screenshot_1](https://github.com/NEZNAMY/TAB/assets/69718740/596bad9a-0ddd-46f1-a4b0-f98529a37f56)
## After crouching and standing up again
![Screenshot_2](https://github.com/NEZNAMY/TAB/assets/69718740/994ba280-0437-4fca-81dc-9e1476ed07bc)
## Crouch --> Uncrouch --> Crouch again
![Screenshot_3](https://github.com/NEZNAMY/TAB/assets/69718740/68c04576-f51b-4ebe-ad26-ea2aafecdc86)

### Expected behavior

Usually, you want the name to have this darker version when the player is crouched and normal when the player is standing. However, here it seems to be completely inverted once you crouch once.

### Steps to reproduce

Step 1: Set any custom nametag with a color for yourself or a friend.
Step 2: Crouch and have the preview enabled or observe your friend when he/she crouches.

Bug should now be visible.

### Additional info

My active plugins:
![Screenshot_5](https://github.com/NEZNAMY/TAB/assets/69718740/b9cce294-e0ad-41cc-ad50-eb7020e57ff3)

My guess right now that this is not the fault of TAB (since I could not find any other people having the exact same issue). However it might be, and even if it's not, I still wanted to ask for a tip which plugin might be causing issues.

Also, maybe the "unlimited"-mode is at fault. I technically don't actually need multiple lines of nametags and could therefore also just disable it if you tell me how.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You can disable a feature by setting enabled: false on the feature. Disable it and see if it keeps happening. Instead of asking if any other plugin could be causing it you should have just deleted them all and see.
Are you 100% sure you are using vanilla client?

**Comment by xZinio** [comment]
Clientside I am using Optifine 1.20.4. I don't know exactly if setting the unlimited nametag mode to false, but currently, the bug does not seem to present anymore. I'll try and test around with it some and will let you know if I determined the cause.

**Comment by NEZNAMY** [comment]
Were you able to find out what causes it?

**Comment by xZinio** [comment]
With some testing, the most likely issue seems to have indeed been the unlimited nametag mode.

**Comment by xZinio** [comment]
Yeah it has now lead me to an issue where enabling the unlimited nametag mode will produce this sneaking bug, but disabling the unlimited nametag mode will prevent HEX color codes from showing up correctly (the prefix has the correct color, but the name of the player has the color of the next-closest minecraft color code).

**Comment by NEZNAMY** [comment]
> With some testing, the most likely issue seems to have indeed been the unlimited nametag mode.

Maybe this is how the game renders custom names of armor stands. Sadly rendering logic is client-sided and cannot be changed with a plugin.

**Comment by xZinio** [comment]
Yeah really a bummer, my solution now was to disable the unlimited nametag mode and just go with default Minecraft color codes instead of HEX codes since those render just fine.
