### ISSUE TITLE
allign-tabsuffix-on-the-right

### ISSUE THREAD

**Issue by LucidAPs** [NEZNAMY/TAB#122]
Minecraft: 1.15.2
Tuinity: build 13
Java 11
Tab Premium  v2.7.1

Using the option allign-tabsuffix-on-the-right: true makes staff members disappear on bungee network if they are not in the same server.

**Comment by NEZNAMY** [comment]
That doesn't make sense. Why only staff ? Who are "staff" even ? How disappear ?

**Comment by LucidAPs** [comment]
False alarm, it happened only the first i enabled the setting. It went back to normal after i disabled and re enabled it. If you don't mind me asking the tab objective is still not accepting color codes and letters even so it says otherwise in the plugin description.

**Comment by NEZNAMY** [comment]
That description is a little misleading, from the name of the feature you see it aligns your tabsuffix manually instead of using the feature. So you need to disable tablist objective and configure it as tabsuffix.

**Comment by LucidAPs** [comment]
Ahh right, thanks a lot.
