### ISSUE TITLE
Team 175737544045376 already exists in this scoreboard

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB#1223]
### Server version

waterfall-1.20-562

### TAB version

TAB-4.1.3-SNAPSHOT.jar

### Describe the bug

when players try to enter 1.8 they get this error, and it only happens to 1 in 10 players.

error: https://mclo.gs/vOosFXR

### Expected behavior

no kick players

### Steps to reproduce

enter the waterfall server, and go to survival 1.20.1 in version 1.8, and you are kicked, and an error appears in the waterfall, in survival there is no error only in the waterfall

I'm using TAB in waterfall

entering 1.12x - 1.20.4 solves the problem

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
[This team name does not come from TAB](https://github.com/NEZNAMY/TAB/wiki/Additional-information#scoreboard-objective-and-team-naming).

**Comment by SrMonsterYT** [comment]
is there a solution to this?

or detect which plugin is doing this? because the only scoreboard I have is for TAB, no other plugin has a scoreboard

**Comment by NEZNAMY** [comment]
Yes, the solution is to delete the plugin creating teams. This team name does not come from TAB. Support for other plugins is not provided here.

**Comment by SrMonsterYT** [comment]
> Yes, the solution is to delete the plugin creating teams. This team name does not come from TAB. Support for other plugins is not provided here.

but I don't have any plugin that creates scoreboards, this only happened after I put in bungeecord, I've been using this plugin for years and this only happened now, the tab plugin itself could tell you which plugin is interfering with it.

**Comment by NEZNAMY** [comment]
How is the plugin supposed to know where does a packet come from?
Do you know that teams are not only used for sidebar scoreboard? They are used for nametags, sorting, for NPCs to hide their original name, some may even use it for entities.

**Comment by SrMonsterYT** [comment]
> How is the plugin supposed to know where does a packet come from? Do you know that teams are not only used for sidebar scoreboard? They are used for nametags, sorting, for NPCs to hide their original name, some may even use it for entities.

could it be my misconfiguration? is it in the group? can you look?

**Comment by NEZNAMY** [comment]
No, I am not interested in helping you configure plugins that are not TAB.

**Comment by SrMonsterYT** [comment]
> No, I am not interested in helping you configure plugins that are not TAB.

but it's the TAB, I think it's because I set up the tab groups wrong, sorry if I misspelled it, we're talking 100% about the tab.

**Comment by NEZNAMY** [comment]
As I already told you countless times, this team name does not come from TAB.
