### ISSUE TITLE
MYSQL disabled but is enabled Tab/Tab-Bridge error

### ISSUE THREAD

**Issue by Nicalion** [NEZNAMY/TAB#1226]
### Server version

Paper newest / Velocity newest

### TAB version

4.1.2 / bridge 5.0.2

### Stack trace

06.02.2024 - 20:49:19 - [TAB v4.1.2] Failed to connect to MySQL
06.02.2024 - 20:49:19 - java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
06.02.2024 - 20:49:19 - 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87)
06.02.2024 - 20:49:19 - 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64)
06.02.2024 - 20:49:19 - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
06.02.2024 - 20:49:19 - 	at java.base/java.lang.Class.forName0(Native Method)
06.02.2024 - 20:49:19 - 	at java.base/java.lang.Class.forName(Class.java:383)
06.02.2024 - 20:49:19 - 	at java.base/java.lang.Class.forName(Class.java:376)
06.02.2024 - 20:49:19 - 	at me.neznamy.tab.shared.config.Configs.<init>(Configs.java:76)
06.02.2024 - 20:49:19 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:163)
06.02.2024 - 20:49:19 - 	at me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:24)
06.02.2024 - 20:49:19 - 	at me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:53)
06.02.2024 - 20:49:19 - 	at me.neznamy.tab.platforms.velocity.VelocityTabCommand.execute(VelocityTabCommand.java:31)
06.02.2024 - 20:49:19 - 	at me.neznamy.tab.platforms.velocity.VelocityTabCommand.execute(VelocityTabCommand.java:16)
06.02.2024 - 20:49:19 - 	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81)
06.02.2024 - 20:49:19 - 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
06.02.2024 - 20:49:19 - 	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226)
06.02.2024 - 20:49:19 - 	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:264)
06.02.2024 - 20:49:19 - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
06.02.2024 - 20:49:19 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02.2024 - 20:49:19 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02.2024 - 20:49:19 - 	at java.base/java.lang.Thread.run(Thread.java:833)
06.02.2024 - 21:17:33 - [TAB v4.1.2] Failed to connect to MySQL
06.02.2024 - 21:17:33 - java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
06.02.2024 - 21:17:33 - 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87)
06.02.2024 - 21:17:33 - 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64)
06.02.2024 - 21:17:33 - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
06.02.2024 - 21:17:33 - 	at java.base/java.lang.Class.forName0(Native Method)
06.02.2024 - 21:17:33 - 	at java.base/java.lang.Class.forName(Class.java:383)
06.02.2024 - 21:17:33 - 	at java.base/java.lang.Class.forName(Class.java:376)
06.02.2024 - 21:17:33 - 	at me.neznamy.tab.shared.config.Configs.<init>(Configs.java:76)
06.02.2024 - 21:17:33 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:163)
06.02.2024 - 21:17:33 - 	at me.neznamy.tab.shared.TAB.create(TAB.java:112)
06.02.2024 - 21:17:33 - 	at me.neznamy.tab.platforms.velocity.VelocityTAB.onProxyInitialization(VelocityTAB.java:53)
06.02.2024 - 21:17:33 - 	at me.neznamy.tab.platforms.velocity.Lmbda$7.execute(Unknown Source)
06.02.2024 - 21:17:33 - 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
06.02.2024 - 21:17:33 - 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
06.02.2024 - 21:17:33 - 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
06.02.2024 - 21:17:33 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
06.02.2024 - 21:17:33 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
06.02.2024 - 21:17:33 - 	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

in config on velocity i enabled mysql with right connection.
mysql: true
but i cant use the /btab mysql upload / download command

![javaw_g9iXYi1gQx](https://github.com/NEZNAMY/TAB/assets/41806623/5712be82-6577-4e7b-8564-cfea903e7f2a)

### Additional info

When i use without velocity on each server the same config will work with mysql

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Velocity does not have a built-in MySQL driver. Why would you even need it? It's to sync data between multiple servers without having to manually edit each file, but on proxy you already have only 1 file.

**Comment by Nicalion** [comment]
thx for fast answer i want the mysql because i want to create a second proxy for the same mirrored server
or did you think is better when i use it per proxy without mysql?

**Comment by NEZNAMY** [comment]
If you only have 2 proxies, is it that much of a hassle to copy groups.yml file from one to another proxy on change? Most people just keep the file in default format that takes data from LP, so it doesn't even need to be modified.

**Comment by Nicalion** [comment]
yea you are right its better but its good to know thats proxy didnt usw mysql support

**Comment by NEZNAMY** [comment]
MySQL is optional, not required and on proxies mostly doesn't even make sense.
On BungeeCord it works though.

**Comment by Nicalion** [comment]
Fixed Thx 
Problem sovled:

-Velocity didnt support mysql
-use without mysql
