### ISSUE TITLE
plugin stopping working

### ISSUE THREAD

**Issue by tanzbr** [NEZNAMY/TAB#1227]
### Server version

Velocity 3.3.0 b343

### TAB version

4.1.3

### Describe the bug

The server starts normally with the tab working, at some point it stops working (even without changing anything on it), and when trying to use /btab reload it shows this error

![image](https://github.com/NEZNAMY/TAB/assets/86328823/01b12035-9bc4-4d0e-b81b-9a7fa12890c4)
Console log: https://mclo.gs/jFwm1db

sometimes after a few minutes it miraculously starts working again, but there are times when just restarting the server

### Expected behavior

Tab not stopping working

### Steps to reproduce

1. Install plugin on velocity and tab-bridge on spigot
2. Run plugin for some time
3. Wait it stop working

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Send your config. The stack trace mentions scoreboard, which is disabled by default.

**Comment by tanzbr** [comment]
> Send your config. The stack trace mentions scoreboard, which is disabled by default.

https://mclo.gs/RPAvomP
