### ISSUE TITLE
Unable to link MySQL correctly

### ISSUE THREAD

**Issue by BBDL233** [NEZNAMY/TAB#1228]
### Server version

velocity-3.3.0-SNAPSHOT-346 and paper-1.8.8-445

### TAB version

4.1.2

### Describe the bug

Unable to connect to MySQL on 1.8.8 and velocity
like this （velocity-3.3.0-SNAPSHOT-346）
![image](https://github.com/NEZNAMY/TAB/assets/99265367/d9dee551-9357-444d-8fad-022e1ebbfe37)
and （paper-1.8.8-445）
![image](https://github.com/NEZNAMY/TAB/assets/99265367/6b3cba84-f595-473c-8492-99e3e1ffc279)
I don't know why this is happening, because I can link MySQL normally on a higher version server（paper-1.20.4-409）
Your question is very similar to another plugin（https://github.com/AlonsoAliaga/AlonsoLevels/issues/16）
java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
what is this?
If possible, please fix this '255' issue

### Expected behavior

mysql:
  enabled: true
  host: localhost
  port: 25564
  database: tab
  username: root
  password: ----

### Steps to reproduce

Put the plugin into plugins and set
mysql:
  enabled: true
  host: localhost
  port: 25564
  database: tab
  username: root
  password: ---
in \plugins \TAB \config.yml

### Additional info

velocity-3.3.0-SNAPSHOT-346:
![image](https://github.com/NEZNAMY/TAB/assets/99265367/d9dee551-9357-444d-8fad-022e1ebbfe37)
paper-1.8.8-445:
![image](https://github.com/NEZNAMY/TAB/assets/99265367/6b3cba84-f595-473c-8492-99e3e1ffc279)
config.yml:
mysql:
  enabled: true
  host: localhost
  port: 25564
  database: tab
  username: root
  password: ---

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
If multiple plugins are throwing the same error it has to be something with your database. Since I don't have this issue, I can't test my potential fix. What is your discord username? I will add you to test a jar.

**Comment by BBDL233** [comment]
BBDL233

Perhaps you can teach me how to use MySQL correctly

**Comment by NEZNAMY** [comment]
User confirmed it works with latest build and after disabling SSL.
