### ISSUE TITLE
Tab failing to load player

### ISSUE THREAD

**Issue by CallumSmith526** [NEZNAMY/TAB#1229]
### Server version

Arclight 1.16.5

### TAB version

TAB v4.1.2

### Describe the bug

When players joined the server, the tab functionality appeared to have failed. Instead of displaying the custom tab, it defaulted to the standard Minecraft tab, and all placeholders broke. Attempts to use the tab command proved unresponsive, leaving no option but to reboot the server. It was fine before that but rebooting has caused this to happen. the only tab command option was "/tab:tab". The placeholders would say "Player is not loaded". There were no errors in logs or plugin folders.
![image](https://github.com/NEZNAMY/TAB/assets/95317856/466240dc-2041-420a-baf7-ae5645135317)

### Expected behavior

Tab working correctly
![Screenshot 2024-02-10 191834](https://github.com/NEZNAMY/TAB/assets/95317856/5bc757e4-f949-4fba-b58f-fa3f7a2fe8c3)
 and tab placeholders working

### Steps to reproduce

Was from a random reboot so not exactly sure.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Enable debug in config, make a spark report (`/spark profiler --timeout 30 --thread *`) when it's broken and send both spark report and console logs on join.

**Comment by NEZNAMY** [comment]
No response for 3 weeks, assuming user has died. 
Several issues that may have caused this will be fixed in 4.1.3.
