### ISSUE TITLE
Tab list ordering required "change-nametag-prefix-suffix: true"

### ISSUE THREAD

**Issue by Teddander** [NEZNAMY/TAB#123]
Server Version 1.15.2 (Paper)

Plugin Version v2.7.0

The tab list will not order according to the defined "group-sorting-priority-list:" unless the seemingly unrelated option "change-nametag-prefix-suffix:" is set to true.
This is a problem, as this option will also mean that every player has an invisible armor stand above their head even if you're not using that feature for anything.  Which creates unnecessary strain on the server.

How to reproduce: Define a couple of ranks in the "group-sorting-priority-list:" section and allow a couple of players to join to make sure it is ordering. Now turn "change-nametag-prefix-suffix:" to false.

Expected behavior: The tab list should still order correctly according to the group sorting priority list.

Actual behavior: The tab list's defined order priority break and resets to mine crafts default ordering.

Additional info: If this option is actually required for the feature, it should at the very least be added as a comment to the config. It took me quite a while to figure out why my ordering was not working.

**Comment by NEZNAMY** [comment]
Yes, mentioned at https://github.com/NEZNAMY/TAB/wiki/config.yml#change-nametag-prefix-suffix and https://github.com/NEZNAMY/TAB/wiki/config.yml#group-sorting-priority-list.

**Comment by Teddander** [comment]
Apologies for the unnecessary issue opening. Thanks for the reply!
