### ISSUE TITLE
Plugin thread deadlock

### ISSUE THREAD

**Issue by tanzbr** [NEZNAMY/TAB#1230]
### Server version

Velocity 3.3.0 b343

### TAB version

4.1.3

### Describe the bug

the plugin stops working randomly, one hour it is working and it simply stops working
after the bug, the /btab command shows literally nothing when executed

I don't know if this is related but it seems that when this happens the cpu usage goes up a lot

![image](https://github.com/NEZNAMY/TAB/assets/86328823/d86eec7a-e757-4162-90ce-a42e0a626e13)
![image](https://github.com/NEZNAMY/TAB/assets/86328823/8014757c-bfe4-4ba7-9e68-3dc84011d138)

### Expected behavior

tab working normally without crashing

![image](https://github.com/NEZNAMY/TAB/assets/86328823/b9cf778e-e7fc-489c-8741-ad54d7188879)

### Steps to reproduce

1. Use plugin on velocity
2. Wait plugin stop working

### Additional info

If you need additional information just let me know

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by tanzbr** [comment]
I saw that in another related issue you requested spark timings, here it is if you need it too :) https://spark.lucko.me/WYGMqkJIJp
Generated using the command `/spark profiler --timeout 30 --thread *`

**Comment by NEZNAMY** [comment]
According to the spark report it breaks on reload. Can you make a report when it breaks without reloading?

**Comment by tanzbr** [comment]
> According to the spark report it breaks on reload. Can you make a report when it breaks without reloading?

Sure, i will wait it happens again

**Comment by NEZNAMY** [comment]
Also try new build from actions.

**Comment by tanzbr** [comment]
It looks like the problem has been resolved, if it happens again I will open another issue, thank you for your support
