### ISSUE TITLE
[Velocity] [MiniMessage] hex-colors displaying as legacy colors

### ISSUE THREAD

**Issue by SeaOrangejuice** [NEZNAMY/TAB#1231]
### Server version

velocity-3.3.0-SNAPSHOT-358

### TAB version

4.1.2

### Describe the bug

The same is \<#f4b8e4>\</#f4b8e4>, but the color display is inconsistent. The color is normal after removing \<italic >\</italic.>
![1](https://github.com/NEZNAMY/TAB/assets/116551329/77948ea6-8c4a-4b9b-ad5f-63e8dfd1b6f0)
![2](https://github.com/NEZNAMY/TAB/assets/116551329/3cbfadcf-6a95-4524-b562-5eea747b6f95)

### Expected behavior

I want it to display properly.

### Steps to reproduce

Add \<talic>\</italic>

### Additional info

I tried writing on another plugin with the same function and found that it does not have this problem.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
I am unable to copypaste the text from your screenshot. Why don't you just use `&o`?

**Comment by SeaOrangejuice** [comment]
Because minimassage is more readable. If I want to write a long sentence, minimassage can better adjust the file.

**Comment by SeaOrangejuice** [comment]
header-footer:
  enabled: true
  header:
  - <#f4b8e4><italic>☁</italic></#f4b8e4>
  - <#ca9ee6>Kaleidos☁</#ca9ee6>
  - <#f4b8e4>🗡    ⛏    🪓</#f4b8e4>
  footer:
  - ''
  - "在线玩家: %online%"
  - ''
  - <#f4b8e4>© YSBB and SOOJCRAFT</#f4b8e4>

**Comment by NEZNAMY** [comment]
Works fine for me.
```
  header:
  - "<#f4b8e4>Text 1</#f4b8e4>"
  - "<#f4b8e4><italic>Text 2</italic></#f4b8e4>"
```
![image](https://github.com/NEZNAMY/TAB/assets/6338394/c697a143-5653-4ca4-94f3-82c00a6313fd)

**Comment by SeaOrangejuice** [comment]
I tried, but it still didn't work.
https://github.com/NEZNAMY/TAB/assets/116551329/f1c831e1-188b-4bb5-a2ad-b45fe2553b73

**Comment by NEZNAMY** [comment]
Are you using vanilla client? If not, try it.
Also try latest build from [actions](https://github.com/NEZNAMY/TAB/actions), I did fix some RGB related issue on velocity with minimessage there.

**Comment by SeaOrangejuice** [comment]
Thank you very much. When I use latest build from actions, it works.
