### ISSUE TITLE
Feature request: MiniPlaceholders support

### ISSUE THREAD

**Issue by Kamillaova** [NEZNAMY/TAB#1233]
### Describe the feature request

MiniPlaceholders is a _**MiniMessage Component-based Placeholders for Paper, Fabric, Sponge, Folia and Velocity platforms**_

It would be great to see MiniPlaceholders support in TAB

### Additional info

https://github.com/MiniPlaceholders/MiniPlaceholders
https://github.com/MiniPlaceholders/MiniPlaceholders/wiki/Projects-using-MiniPlaceholders-API

**Comment by NEZNAMY** [comment]
[Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). What's the point of doing this anyway? PlaceholderAPI is available on bukkit and with bridge you can display placeholders on bungee & velocity as well. That covers roughly 99.98% of TAB users. The placeholders are also basic and don't seem to offers hooks into plugins.

**Comment by Kamillaova** [comment]
> What's the point of doing this anyway?

\*1.16+\* placeholders with a fancy implementation, not through smth like `UNUSUAL_LEGACY_COMPONENT_SERIALIZER.serialize(component)`

That's all.

**Comment by NEZNAMY** [comment]
I am not struggling with serializing components on 1.16+.

**Comment by Kamillaova** [comment]
> I am not struggling with serializing components on 1.16+.

This is about placeholders developers, also about PlaceholderAPI in general

**Comment by NEZNAMY** [comment]
I see no reason to do this even if feature requests were open, which they are not. PlaceholderAPI offers everything you need and much more. Supporting more than 1 placeholder source can also be problematic.

**Comment by Kamillaova** [comment]
Okay
