### ISSUE TITLE
Tab not updating the bossbar

### ISSUE THREAD

**Issue by DarkyG2** [NEZNAMY/TAB#1234]
### Server version

1.20.4

### TAB version

4.1.3

### Describe the bug

I have a bossbar that outputs a message if the placeholder is equals to "TRUE" but even if the placeholder outputs true it won't show the bossbar and it would only fix itself by reloading the plugin and getting that error with it: https://pastebin.com/DYnYM1Py

### Expected behavior

I should see my bossbar wtihout needing to reload the plugin

### Steps to reproduce

1. Create a bossbar that shows itself if the placeholder outputs true
2. Be on folia 1.20.4
3. change the placeholder output from false to true
4. The bossbar won't show itself

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Can you give an example bossbar configuration using some simple PlaceholderAPI (or internal TAB) placeholder that can easily be changed from false to true?

**Comment by NEZNAMY** [comment]
Paper website doesn't have folia downloads. Can you send me a download link? Alternatively, have you tried on regular paper?

**Comment by DarkyG2** [comment]
> Paper website doesn't have folia downloads. Can you send me a download link? Alternatively, have you tried on regular paper?

I'll try on Paper later today since I'm currently not really available (working) but here https://we.tl/t-13ir9h2FQn

**Comment by DarkyG2** [comment]
> [Unable to reproduce](https://www.youtube.com/watch?v=7LstnLhwfDg).

Make sure to restart join and you will have the issue, after couple tab reload and disconnect the issue auto fixes itself

**Comment by NEZNAMY** [comment]
I tried leaving and joining back, still works.

**Comment by DarkyG2** [comment]
> I tried leaving and joining back, still works. Are you sure you didn't get errors.log file in TAB's folder?

I'll check asap, currently out of town for diner

**Comment by DarkyG2** [comment]
Sorry for the delay the issue is quite random and it happens randomly so it's not a big issue, I won't keep the issue open without more information since it might be an extremely specific issue
