### ISSUE TITLE
"Blocked attempt to add player into team" on Velocity

### ISSUE THREAD

**Issue by MrRockis** [NEZNAMY/TAB#1238]
### Server version

Paper 1.20.4

### TAB version

4.1.3-SNAPSHOT build #1054

### Describe the bug

We just switched from waterfall to velocity and saw some errors from TAB and TAB-Bridge regarding teams.

I fired up two paper servers with tab-bridge and few other plugins and a velocity and a waterfall proxy. Both proxies only have tab installed with the same exact config.

When connecting via waterfall, no message appears to the proxy nor the game servers.
When connecting via velocity the message "[TAB-Bridge] Blocked attempt to add player MrRockis into team 䀁耀%core_name%A" appears **multiple** times. On our main server all game servers get filled up when we login to the proxy. For example when we join proxy and lobby, survival server spams the same message as well. Is this caused my plugin message on velocity?

%core_name% is a placeholder that returns a prefix for the player. This is configured in groups.yml as a tagprefix.

### Expected behavior

This will cause a lot of errors to the console and sometimes placeholders will not appear in the tablist.

### Steps to reproduce

1. Install tab on empty waterfall and velocity
2. Configure both to have a custom placeholder as a tagprefix
3. Setup multiple game servers with TAB-Bridge

### Additional info

We are using the latest development builds (actions) from both TAB and TAB-Bridge.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you don't get `anti-override.log` file on waterfall installation? Can you send full log with that message spam? Also this has nothing to do with placeholders not parsing.

**Comment by MrRockis** [comment]
On the main network when joining via velocity we get the error in multiple different game servers.

Hub: (where the player joined)
![image](https://github.com/NEZNAMY/TAB/assets/30273291/97d8b47c-06ab-4716-8608-9d1ae295cdb4)

Creative (player not joined, just connected via same proxy/both have tab-bridge)
![image](https://github.com/NEZNAMY/TAB/assets/30273291/628c7a86-ecaf-4871-809c-5a5fb82de00f)

Survival (player not joined, just connected via same proxy/both have tab-bridge)
![image](https://github.com/NEZNAMY/TAB/assets/30273291/7d03875d-ed98-4c97-bb51-2e174e12af92)

**Comment by NEZNAMY** [comment]
Get latest build of bridge from [actions](https://github.com/NEZNAMY/TAB-Bridge/actions) and send new message, it should also contain expected team name.

**Comment by MrRockis** [comment]
Here you go, first join with waterfall second (with error) with velocity.

[latest.log](https://github.com/NEZNAMY/TAB/files/14434753/latest.log)

**Comment by NEZNAMY** [comment]
I think this is because a new packet request was sent before the first was actually flushed, and since these things happen in different threads, bridge already has the new name remembered while the old packet didn't even go through. 
Can you check if nametags work properly for that player when it's thrown?

**Comment by MrRockis** [comment]
With a quick check the nametag seems to function properly. It has the prefix attached to it.

Also found out that when logging in with my second account the error came up three times. The error count scales with the player count and because of that we had a lot of errors in the pictures above.

**Comment by NEZNAMY** [comment]
Can it be reproduced without using sorting by placeholder? Or just using %player% instead of some PAPI one.

**Comment by MrRockis** [comment]
The error is gone when changing from

sorting-types:
  - PLACEHOLDER_A_TO_Z:%core_name%
  to
  - PLACEHOLDER_A_TO_Z:%player%

**Comment by NEZNAMY** [comment]
After some tests, my theory was proven correct.
```
[15:06:26] [Server thread/INFO]: _NEZNAMY_[/127.0.0.1:56550] logged in with entity id 25 at ([world]-170.78195865668863, 113.0, -52.179537935378484)
[15:06:26] [TAB-Bridge Processing Thread/INFO]: [TAB-Bridge] [STDOUT] Registering team 6%player_name%A
[15:06:26] [TAB-Bridge Processing Thread/WARN]: Nag author(s): '[NEZNAMY]' of 'TAB-Bridge v5.0.2' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[15:06:26] [TAB-Bridge Processing Thread/INFO]: [TAB-Bridge] [STDOUT] Unregistering team 6%player_name%A
[15:06:26] [TAB-Bridge Processing Thread/INFO]: [TAB-Bridge] [STDOUT] Registering team 6_NEZNAMY_A
[15:06:26] [Netty Server IO #1/INFO]: [TAB-Bridge] Blocked attempt to add player _NEZNAMY_ into team 6%player_name%A (expected team: 6_NEZNAMY_A)
[15:06:26] [Netty Server IO #1/INFO]: [TAB-Bridge] [STDOUT] [TAB-Bridge] Letting team register 6_NEZNAMY_A
```
How should this be resolved? I don't want to disable the console message, because it may prove useful to some users who are genuinely interested in having their plugins configured correctly. Unfortunately lots of them reject such solutions. Should I remove the message and act like nothing is wrong?

**Comment by NEZNAMY** [comment]
BungeeCord offers scoreboard packet encoding while velocity doesn't. As a result, packet encoding is done by bridge when TAB is on velocity. The reason why this doesn't happen is that it doesn't have to send the packet encode request to bridge but sends it directly, which is faster and packet is encoded and flushed before the response from bridge comes.

**Comment by MrRockis** [comment]
Interesting. It is not optimal for it to spam the message everywhere either. Would it be possible to add a small delay that the teams would be registered in correct order?

What would be the best approach here?

**Comment by NEZNAMY** [comment]
I have made a professional graph explaining the current behavior:

![image](https://github.com/NEZNAMY/TAB/assets/6338394/08401cb8-ae84-4ea6-815b-a9209801d4ab)

Now imagine you push the red square (and the one after it as well) significantly to the right. Suddenly you started encoding first packet while already prepared the second one. This can happen on join when the netty thread is overloaded from joining in (expecially when sending the world data) and ping is close to or equal to 0, so there is no delay anywhere.

**Comment by MrRockis** [comment]
What do you think would be the best way to solve this then? A fix would be to disable the messages if velocity is being used but as thated it might cause real issues to be unnoticed.

The error message seems to be the same always. Would it be possible to somehow "ignore" that team (in this case "core_name") and prevent those errors from coming up?

**Comment by NEZNAMY** [comment]
`A fix would be to disable the messages if velocity is being used`
Team packets are only encoded by bridge when velocity is used, since BungeeCord does that already. Removing the message is probably the best solution here, considering issues like https://github.com/NEZNAMY/TAB-Bridge/issues/30 and many other tickets we get from people who refuse to configure their plugins properly.
Blocking the first team packet's add player causes no harm, so it is completely safe.

**Comment by MrRockis** [comment]
Unfortunately everyone doesn't want to configure their team/scoreboard plugins correctly. Deploy a fix that you think would be the best 👌

**Comment by NEZNAMY** [comment]
Disabled the message. https://github.com/NEZNAMY/TAB-Bridge/actions
