### ISSUE TITLE
Limited minimessage compatibility

### ISSUE THREAD

**Issue by IllusionTheDev** [NEZNAMY/TAB#1239]
### TAB version

4.1.2

### Software causing compatibility issue

MiniMessage 

### Additional info

TAB claims to support minimessage. While color serialization is the case, it still lacks support for other minimessage features, such as translatable components.

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
TAB doesn't use translatable components at all. It's completely missing from the code and not converted into any platform components, not even adventure. This is not a compatibility issue.

**Comment by IllusionTheDev** [comment]
Anything I can do about it or should I call it a day and make my own scoreboard plugin?

**Comment by NEZNAMY** [comment]
You'll need to make your own. Feature requests are closed.

**Comment by qdpy** [comment]
Interested to have the <lang> minimessage support!

**Comment by qdpy** [comment]
I'm talking about Minimessage translatable!

**Comment by NEZNAMY** [comment]
As mentioned above as well as README, feature requests are permanently closed.

**Comment by qdpy** [comment]
Then Minimessage isn't fully supported yep :(

**Comment by NEZNAMY** [comment]
I guess not then.
