### ISSUE TITLE
Multiple list-objectives in TAB

### ISSUE THREAD

**Issue by JVT038** [NEZNAMY/TAB#124]
Hi,
Is there a way to have multiple list-objectives next to a players' name?
For example:

{PREFIX} %PLAYERNAME% %PING% %HEALTH% %DEATH%
With kind regards,

**Comment by NEZNAMY** [comment]
Yes, `/tab group _OTHER_ tabprefix %vault-prefix%`, `/tab group _OTHER_ tabsuffix %ping %health% %deaths%`
