### ISSUE TITLE
[Velocity] Missing compatibility with nick plugins

### ISSUE THREAD

**Issue by MrRockis** [NEZNAMY/TAB#1240]
### Server version

Paper 1.20.4

### TAB version

4.1.3-SNAPSHOT build #1054

### Describe the bug

We have a "disguise" system on our server. When a player runs /disguise <name> the target's uuid, skin and username get received from mojang's servers.

The player's playerprofile is then changed with the API:
```
PlayerProfile currentProfile = p.getPlayerProfile();
PlayerProfile newProfile = Bukkit.createProfileExact(p.getUniqueId(), disguisedName);

newProfile.setProperties(currentProfile.getProperties());

newProfile.removeProperty("textures");
newProfile.setProperty(new ProfileProperty("textures", skin.texture, skin.signature));

p.setDisplayName(disguisedName);
p.setPlayerProfile(newProfile);
```

We have a placeholder %core_nametag% which returns the the color of the nametag the player is supposed to have. The default one is gray and whilst disguised it will return "&7". We also have a %core_rankweight% placeholder which tells tab in what position should the player appear (disguise should appear lower because no rank).

Our sortingtype in the config:
```
  sorting-types:
  - PLACEHOLDER_HIGH_TO_LOW:%core_rankweight%
  - PLACEHOLDER_A_TO_Z:%core_name%
```

On velocity the username changes, but appears white. The player is the first one on tab list. When reverting back to the old name the color and position works again.

Tried with the older version of TAB-Bridge and it shows the error "Blocked attempt to add player". No errors on proxy/error.log/anti-override.log

### Expected behavior

Player is supposed to have a gray nametag because tagprefix is set to %core_nametag% and the placeholder returns gray color. Instead it is not showing the placeholder at all.

Tablist order is also broken.

### Steps to reproduce

1. Have a placeholder sorting order
2. Have a placeholder tagprefix
3. Change player's player profile
4. Tagprefix is no longer applied and sorting order is wrong

### Additional info

Might be related to the previous issue: https://github.com/NEZNAMY/TAB/issues/1238

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-display-name-from-nickname-plugins#type-2-plugins-that-change-profile-name
Support for this is not available on velocity, because teams are bound to player names and plugin doesn't know you changed a player's name.

**Comment by MrRockis** [comment]
Just found it and the part "but may get added if requested".

Would it be possible to add this as an option to the API so that it could be used? We could call the method to tell TAB that the profile/name of a player was changed. Better option would be the same as spigot / bungeecord, but if its not possible that could fix the issue.

**Comment by NEZNAMY** [comment]
On spigot/bungeecord plugin is using pipeline injection, which is not available on velocity. The text needs to be updated as feature requests are closed. I might add an API method though.

**Comment by MrRockis** [comment]
Either one would be appreciated a lot and would probably fix my issue. I think the API method would be the easier one in this case if the pipeline injection is not available on velocity.

**Comment by MrRockis** [comment]
The API method seems to have fixed the issue. Thank you!
