### ISSUE TITLE
Nametags not working on mobs with owner

### ISSUE THREAD

**Issue by Kovalski4** [NEZNAMY/TAB#1243]
### Server version

1.20.4

### TAB version

4.1.2

### Describe the bug

  unlimited-nametag-mode:
    enabled: true

Nametags works on all mobs but if i try to rename mobs have a owner, it wont work and nametag just disappears.

### Expected behavior

Nametags works on mobs with owner

### Steps to reproduce

Step 1: Tame a wolf or any mob
Step 2: Try to rename with nametag
Step 3: Wont work and nametag disappears

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-2---prefixsuffix-on-pets ?

**Comment by Kovalski4** [comment]
I tried that plugin, not working

**Comment by NEZNAMY** [comment]
Did it load properly? Did it throw any errors?

**Comment by Kovalski4** [comment]
[Sun 11:03:58 INFO  Server/PlayerConnection] Kovalski issued server command: /plugman load PetNameFix-1.0.1
  [Sun 11:03:58 INFO  PetNameFix] Loading server plugin PetNameFix v1.0.1
  [Sun 11:03:58 INFO  PetNameFix]

![Capture](https://github.com/NEZNAMY/TAB/assets/49496860/827e4a58-4ab0-4c31-ba8e-dd965eb1588d)
 Enabling PetNameFix v1.0.1

**Comment by NEZNAMY** [comment]
Plugman reload doesn't fix it, because the plugin alters outgoing packets and the "bad" packet already made it to the client and can no longer be altered by the plugin.
There is **NO** way you actually downloaded the plugin and loaded it using plugman without restarting, right?

**Comment by Kovalski4** [comment]
It worked after restart. You can add the plugin to plugman ignored plugin list
Thanks for help

**Comment by NEZNAMY** [comment]
Bruh.
I didn't help you, this is not support. I fixed a bug.. without doing anything.

**Comment by Kovalski4** [comment]
You must add the fix plugin to plugman ignore list. Most player use plugman for small things.

**Comment by NEZNAMY** [comment]
Neither of those plugins are mine. I cannot do anything. Also plugman is not the only plugin of its kind, so even if I managed to do something that's out of my control, it wouldn't work with other plugins.
