### ISSUE TITLE
Error in placeholders

### ISSUE THREAD

**Issue by Grellelite** [NEZNAMY/TAB#1244]
### TAB version

4.1.2

### Software causing compatibility issue

I have a server on the geyser tab system that works with Java and with Pe, but on Java placeholders work and on Pe their place is just empty
![Screenshot_2024-03-04-10-16-18-95_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/NEZNAMY/TAB/assets/162107004/50c46232-afcf-4167-817b-c1cadbd95ec8)

### Additional info

Надеюсь вы сможете помочь 

### Checklist

- [X] I am running latest version of the plugin
- [X] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
send your config

**Comment by Grellelite** [comment]
> пришлите свою конфигурацию

And how? YML is not supported here

**Comment by Tanguygab** [comment]
rename the file to .txt

**Comment by Grellelite** [comment]
> переименуйте файл в .txt или используйте Pastebin

[config (3).txt](https://github.com/NEZNAMY/TAB/files/14479139/config.3.txt)

**Comment by Tanguygab** [comment]
delete lines 90 to 99

**Comment by Grellelite** [comment]
> удалить строки с 90 по 99

Will it help?

**Comment by Tanguygab** [comment]
it will fix your issue

**Comment by Grellelite** [comment]
So from 90 to 99 this is my skateboard

**Comment by Grellelite** [comment]
> это решит вашу проблему

So from 90 to 99 this is my skateboard

**Comment by Grellelite** [comment]
> это решит вашу проблему

How will it help if deleting it won't

**Comment by NEZNAMY** [comment]
[config.3.txt](https://github.com/NEZNAMY/TAB/files/14479713/config.3.txt)
I have fixed your config here. Next time don't abuse the issue tracker for support.
