### ISSUE TITLE
Server crashed 

### ISSUE THREAD

**Issue by LutrexMC** [NEZNAMY/TAB#1245]
### Server version

Purpur 1.20.4

### TAB version

4.1.2

### Stack trace

https://pastes.dev/Z34RAEILKB

### Additional info

I ran /tab and the server crashed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
your HexNicks placeholder is throwing an error, it could be the culprit

**Comment by NEZNAMY** [comment]
HexNicks caused a deadlock. Remove the placeholder from your TAB configuration.
