### ISSUE TITLE
TAB support for Necrotempus (1.7.10 - Crucible)

### ISSUE THREAD

**Issue by Akashiic** [NEZNAMY/TAB#1246]
### TAB version

3.2.2

### Software causing compatibility issue

I have a large mod server on 1.7.10, but as it is on 1.7.10 I must understand that some features do not exist in this version, however, there is a mod that backports some of these features from the new versions to Minecraft, it is called Necrotempus!

I would like to use the features available from TAB with the features backported in Necrotempus. I apologize if my explanation was confusing, but that's basically it!

Necrotempus:
https://github.com/CrucibleMC/NecroTempus

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
On which marketplace is 3.2.2 latest? 
This is not a compatibility issue, plugin doesn't claim to support 1.8+ features on 1.7.10.
[Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). Even if they were open, you are the only person in the world who wants this, at which point you should get a private plugin done to do this. Which features are you even talking about?

**Comment by Akashiic** [comment]
> On which marketplace is 3.2.2 latest? This is not a compatibility issue, plugin doesn't claim to support 1.8+ features on 1.7.10. [Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). Even if they were open, you are the only person in the world who wants this, at which point you should get a private plugin done to do this. Which features are you even talking about?

The features, is custom tab, examples: header tab, bottom tab, like in this image
![download](https://github.com/NEZNAMY/TAB/assets/56742504/a3325858-f425-4c54-9f10-27027101a8e4)

I know that features like this don't exist in 1.7, but Necrotempus makes it exist in 1.7!

And about me being the only person in the world, it must be because the mod is new, and I myself participated in the mod tests!

**Comment by NEZNAMY** [comment]
Still, [feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services) permanently.

**Comment by Akashiic** [comment]
Do I need to be Premium or open a commission? it will be a pleasure!

**Comment by NEZNAMY** [comment]
This kind of service is no longer provided. I have left the development. If you need this, you'll need to look into other plugins or get one made just for you.
