### ISSUE TITLE
[Unlimited Nametags] Nametags don't get removed sometimes when a player logs out/changes world

### ISSUE THREAD

**Issue by bridgelol** [NEZNAMY/TAB#1247]
### Server version

Paper 1.20.4

### TAB version

4.1.3-SNAPSHOT

### Describe the bug

Check title.

This is with infinite nametag mode.

### Expected behavior

Should remove the nametag

### Steps to reproduce

Doesn't happen every time but when you have a bigger playerbase it does happen

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration 
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/0286c24c-64d5-4ef7-a60b-e40f932dfac6)
Steps to reproduce are insufficient.

**Comment by NEZNAMY** [comment]
Unlimited nametag mode was marked for removal and no more bugs will be fixed. See https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c for more info.
