### ISSUE TITLE
[Velocity] TAB "Skipped plugin message send" errors

### ISSUE THREAD

**Issue by MrRockis** [NEZNAMY/TAB#1248]
### Server version

Velocity 3.3.0-SNAPSHOT build 364

### TAB version

4.1.3-SNAPSHOT build #1054

### Describe the bug

errors.log on velocity is full of:
`[TAB v4.1.3-SNAPSHOT] Skipped plugin message send to MrRockis, because player is not connected to any server (message= PacketPlayOutScoreboardTeam 䀁羜  mrrockisA    &4       always never   )`
Everything still seem to work without any issue, but the errors appear on the log file.

### Expected behavior

Those errors should not come into the errors file

### Steps to reproduce

1. Use TAB on velocity proxy
2. See plugins/TAB/errors.log file for errors

### Additional info

No using the latest development build, but looks like all the updates have been to other platforms since that. Using build #1054.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Zoriot** [comment]
Also happened for me on Version 4.1.2.
Maybe its fixed with that commit: https://github.com/NEZNAMY/TAB/commit/66008cd767524af5c1b8f0d768330db50d2294a6
