### ISSUE TITLE
Relational placeholders in unlimited nametag mode do not refresh properly

### ISSUE THREAD

**Issue by Leomelonseeds** [NEZNAMY/TAB#1249]
### Server version

Paper-429 1.20.4

### TAB version

TAB Bungee 4.1.2, Bridge 5.0.3

### Describe the bug

Relational placeholder in nametags do not refresh when they change, but refresh fine in the tablist. 

### Expected behavior

Relational placeholders in nametags should refresh when they change.

### Steps to reproduce

1. Add a relational placeholder to a portion of the nametag, such as in `tagsuffix`. Also add it to a portion of the tab, such as in `tabsuffix`. In my case, I use `%rel_kingdoms_relation_name%` from the KingdomsX plugin.
2. Get 2 players near each other, so they can both see each other's nametags.
3. Change the relational placeholder through the means of the plugin providing it.
4. Notice how the relational placeholder is changed in the tablist, but not in the nametag. 
5. Relogging or travelling far away from the other player and coming back fixes the issue.

### Additional info

If it helps, I'm using layout mode for the tablist.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
To keep things simple and avoid overcomplication, bridge only refreshes relational placeholders in armor stands when another placeholder used in the same line triggers a change. You can force a periodic refresh by creating a slow animation that only consists of 2 different color codes and put it at the end, so it doesn't have any visual effect.

**Comment by Leomelonseeds** [comment]
Ah that makes sense. The animation fix seems to work well. Thanks for the quick response!
