### ISSUE TITLE
Chat color

### ISSUE THREAD

**Issue by TheRealButterPlays** [NEZNAMY/TAB#125]
this would be an extra thing while changing the config file, in the groups area under tab prefix and suffix it would look like
>
    tabprefix: "&0&l[&a&lOwner&0&l] &a"
    tagprefix: "&8&lOwner &a"
    chatcolor: "&8"
>

something like that, of course I wouldn't mind implementation in other ways but that's an example.

**Comment by rodrigozamorad** [comment]
TAB is not a chat plugin

**Comment by TheRealButterPlays** [comment]
fair enough.
