### ISSUE TITLE
Tab Layout Playerlist Issue with ProtocolLib 

### ISSUE THREAD

**Issue by ClassEnkhbat** [NEZNAMY/TAB#1250]
### TAB version

4.1.2

### Software causing compatibility issue

ProtocolLib: 5+
Server Version: 1.8.9

### Additional info

Hello, I updated my ProtocolLib plugin to 5.0.0 and this tab layout menu issue happening. Sometimes player names are on other side, player names not appearing, slot;... name appearing. I even reinstalled but still happening. 

Config:
https://pastebin.com/jcHsTVud

Video:
https://github.com/NEZNAMY/TAB/assets/124324195/ab07ac7b-473c-40c3-8073-18d6ef316b9f

https://github.com/NEZNAMY/TAB/assets/124324195/9c7457f8-29ae-4224-b964-632fe5df1889

https://github.com/NEZNAMY/TAB/assets/124324195/21c4ce3e-5d9d-43a4-9755-2fe8d471ee46

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Does it work fine without ProtocolLib? Are you sure you have the latest build? ProtocolLib is currently very buggy with 800+ bugs, are you sure this is a TAB issue?

**Comment by ClassEnkhbat** [comment]
Okay. It works fine without ProtocolLib. So it's just ProtocolLib's issue that I have to report?

**Comment by NEZNAMY** [comment]
Assuming you are not using latest build, yes.

**Comment by ClassEnkhbat** [comment]
I see. How can I download Tab's development build?

**Comment by NEZNAMY** [comment]
I meant of ProtocolLib. https://ci.dmulloy2.net/job/ProtocolLib/
Also 5.0.0 is not even latest release, 5.1.0 is.

**Comment by ClassEnkhbat** [comment]
I used 5.0.0 and 5.1.0 version. Still same.

**Comment by NEZNAMY** [comment]
This is however out of scope of this repository. This is a TAB issue tracker and another plugin is breaking TAB's packets.
