### ISSUE TITLE
Mixing minimessage and legacy formatting causes minimessage formatting to stop working in unlimited mode

### ISSUE THREAD

**Issue by dasavick** [NEZNAMY/TAB#1253]
### Server version

Purpur 1.20.4

### TAB version

4.1.3

### Describe the bug

I just migrated from my custom solution to TAB, and I'm using placeholders to provide my prefix and suffix values.

When the prefix uses minimessage coloring and the suffix is legacy colors using ampersand, the minimessage formatting gets disabled, but only in the tagprefix, it appears to work fine in the tabprefix.

This works 100% fine with unlimited nametag mode disabled.

### Expected behavior

Formatting behavior is consistent between tabprefix and tagprefix.

### Steps to reproduce

1. Use unlimited mode
2. Create tagprefix with `<red>`
3. Create tagsuffix with `&eA`

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/44551064/8654233e-362e-4893-aaee-159064f76097)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
[Adventure FAQ](https://docs.advntr.dev/faq.html#how-can-i-support-both-minimessage-and-legacy-code-formatting) clearly explains you cannot use both in the same text. When using unlimited nametags, all 3 properties (tagprefix, customtagname, tagsuffix) are merged together (just like in tablist) and then an armor stand is created with custom name that consists of the merged value, where MiniMessage throws an error. When having the feature disabled, prefix and suffix are separate team properties ran through all RGB-related code separately.

**Comment by dasavick** [comment]
Thank you for the quick response. Now it makes a lot more sense why it didn't work in the unlimited mode only. I already removed all the legacy coloring use in my placeholders.

Normally I just do something like this to freely mix components with legacy coloring, didn't notice any issues so far, but I can see this probably isn't something you want to implement.

```java
public static final MiniMessage MINI_MESSAGE = MiniMessage.builder()
        .preProcessor(text -> Pattern.compile("(?i)§([0-9A-FK-OR])").matcher(text).replaceAll("&$1"))
        .postProcessor(component -> component.replaceText(TextReplacementConfig.builder()
            .match(Pattern.compile(".*"))
            .replacement((result, input) -> LegacyComponentSerializer.legacyAmpersand().deserialize(result.group()))
            .build()))
        .build();
```

**Comment by NEZNAMY** [comment]
I'm not interested in adding this kind of solution. MiniMessage was made a certain way and I am absolutely not interested in compensating for its unsatisfactory user experience. I'd rather not even support it at all, but I would get way too many complaints.
