### ISSUE TITLE
[Bug Report] Unable to hide the default player ID

### ISSUE THREAD

**Issue by Yurium7** [NEZNAMY/TAB#1254]
### Server version

purpur-1.19.4-1985

### TAB version

4.1.2

### Describe the bug

Default player IGN cant be Hide

### Expected behavior

Hide Default Player ID

### Steps to reproduce

1. Restats Server
2. Find this Bug

### Additional info

![ebecb46291073d94ec602d78522c0057](https://github.com/NEZNAMY/TAB/assets/133829524/96aafc8e-86ed-4cbf-b812-cf62d626afd3)
![c7b37a4619c9130dbdade645af589d28](https://github.com/NEZNAMY/TAB/assets/133829524/3cd8934d-c30b-44f6-aa40-1c981dae68cc)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Yurium7** [comment]
[config.txt](https://github.com/NEZNAMY/TAB/files/14652659/config.txt)

**Comment by NEZNAMY** [comment]
Does /tab reload fix it? Are you running a proxy network?

**Comment by Yurium7** [comment]
reload can fix , not use

**Comment by NEZNAMY** [comment]
Do reload does fix it? When does it break? On join? Show plugin list.

**Comment by Yurium7** [comment]
Reload can Fix this
restats Server and join
![image](https://github.com/NEZNAMY/TAB/assets/133829524/10c16a45-5781-4577-96e1-8b5f9d9cf086)

**Comment by NEZNAMY** [comment]
CustomNameplates sounds very suspicious. Try removing it. Alternatively try on a testing network with no plugins. If it works there, add plugins back until you find the one that's causing it.

**Comment by Yurium7** [comment]
CustomNameplates Causing this problem

**Comment by NEZNAMY** [comment]
You cannot have 2 plugins trying to do the same thing. Decide which one do you want and disable the other one. I don't see how this is a TAB bug.

**Comment by Yurium7** [comment]
Sorry, this is my problem >_<
