### ISSUE TITLE
gradients not working

### ISSUE THREAD

**Issue by tanzbr** [NEZNAMY/TAB#1255]
### Server version

Velocity 3.3.0 b343

### TAB version

4.1.4 latest build

### Describe the bug

after updating the plugin, hex gradients stopped working on scoreboard and player tags (above the head)

![Screenshot_1](https://github.com/NEZNAMY/TAB/assets/86328823/372d4df4-02a2-4da1-b6cf-27b1134ef818)
![imagem_2024-03-27_100257558](https://github.com/NEZNAMY/TAB/assets/86328823/95861799-841c-48fe-ac27-27bc25f97081)
![imagem_2024-03-27_100308431](https://github.com/NEZNAMY/TAB/assets/86328823/411ffbe2-6d61-4249-8f2f-872b21e6a1b1)

### Expected behavior

hex gradients working normally

![Screenshot_2](https://github.com/NEZNAMY/TAB/assets/86328823/71e1dc8d-6596-434b-a160-7baa682d4d9c)

### Steps to reproduce

use hex gradients on latest build on velocity

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
Assuming you're using the <gradient:#RRGGBB:#RRGGBB> text </gradient> format:
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#18---is-minimessage-supported
![image](https://github.com/NEZNAMY/TAB/assets/45695833/f74a9122-a0e2-4ea1-ba13-6430aa00113c)

**Comment by tanzbr** [comment]
> Assuming you're using the `<gradient:#RRGGBB:#RRGGBB> text </gradient>` format: https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#18---is-minimessage-supported ![image](https://private-user-images.githubusercontent.com/45695833/317274365-f74a9122-a0e2-4ea1-ba13-6430aa00113c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDUwNTIsIm5iZiI6MTcxMTU0NDc1MiwicGF0aCI6Ii80NTY5NTgzMy8zMTcyNzQzNjUtZjc0YTkxMjItYTBlMi00ZWExLWJhMTMtNjQzMGFhMDAxMTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYmMxNzUxMjJiZDcxMjcxZDVkMTIwMWE1YTU1MWY3MDljNzY2YTM1NWY1NmM3MzdiZWJkODQ4MTIwMDg5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3KOqy21c7LSlgJAUG4yIwfJWxHKQ0dvVEFkTB0QBqo)

i use this format
![imagem_2024-03-27_100712766](https://github.com/NEZNAMY/TAB/assets/86328823/0d4e704a-8b40-4d0a-9e1b-f05e2ac35685)

**Comment by Tanguygab** [comment]
send your config.yml & groups.yml

**Comment by tanzbr** [comment]
config.yml https://mcpaste.io/15857899a8f4ab54
groups.yml https://mcpaste.io/64700b57b605c1ce

**Comment by NEZNAMY** [comment]
You are way too into the future, 4.1.3 is not even out and you are using 4.1.4 already?
Update bridge to latest build from [actions](https://github.com/NEZNAMY/TAB-Bridge/actions).

**Comment by tanzbr** [comment]
sorry I typed it wrong, it is 4.1.3 latest build
i will try the latest build of bridge

**Comment by NEZNAMY** [comment]
No response for a week, assuming user no longer cares. Issue was fixed in new version on Bridge (5.0.4).
