### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by raqqeldon** [NEZNAMY/TAB#1257]
### Server version

Spigot 1.20.4

### TAB version

4.1.2

### Describe the bug

**When i load my server up it shows this in console**

30.03.2024 - 12:51:03 - [TAB v4.1.2] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
30.03.2024 - 12:51:03 - com.google.gson.JsonParseException: Invalid color name: whıte
30.03.2024 - 12:51:03 - 	at net.minecraft.SystemUtils.a(SourceFile:1005)
30.03.2024 - 12:51:03 - 	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.b(IChatBaseComponent.java:292)
30.03.2024 - 12:51:03 - 	at net.minecraft.network.chat.IChatBaseComponent$ChatSerializer.b(IChatBaseComponent.java:326)
30.03.2024 - 12:51:03 - 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
30.03.2024 - 12:51:03 - 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.platforms.bukkit.scoreboard.PacketScoreboard.lambda$static$0(PacketScoreboard.java:56)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.util.ComponentCache.get(ComponentCache.java:24)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.platforms.bukkit.scoreboard.PacketScoreboard.toComponent(PacketScoreboard.java:239)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.platforms.bukkit.scoreboard.PacketScoreboard.toComponent(PacketScoreboard.java:233)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.platforms.bukkit.scoreboard.PacketScoreboard.registerTeam0(PacketScoreboard.java:158)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.platform.Scoreboard.registerTeam(Scoreboard.java:91)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.features.nametags.NameTag.registerTeam(NameTag.java:276)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.features.nametags.NameTag.load(NameTag.java:78)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.FeatureManager.load(FeatureManager.java:52)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.TAB.load(TAB.java:171)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.shared.TAB.create(TAB.java:112)
30.03.2024 - 12:51:03 - 	at me.neznamy.tab.platforms.bukkit.BukkitTAB.onEnable(BukkitTAB.java:24)
30.03.2024 - 12:51:03 - 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
30.03.2024 - 12:51:03 - 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
30.03.2024 - 12:51:03 - 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
30.03.2024 - 12:51:03 - 	at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:428)
30.03.2024 - 12:51:03 - 	at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:385)
30.03.2024 - 12:51:03 - 	at com.rylinaux.plugman.util.BukkitPluginUtil.reload(BukkitPluginUtil.java:500)
30.03.2024 - 12:51:03 - 	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125)
30.03.2024 - 12:51:03 - 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97)
30.03.2024 - 12:51:03 - 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
30.03.2024 - 12:51:03 - 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
30.03.2024 - 12:51:03 - 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:887)
30.03.2024 - 12:51:03 - 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
30.03.2024 - 12:51:03 - 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:413)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:335)
30.03.2024 - 12:51:03 - 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:322)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1856)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1818)
30.03.2024 - 12:51:03 - 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
30.03.2024 - 12:51:03 - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.TickTask.run(SourceFile:18)
30.03.2024 - 12:51:03 - 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
30.03.2024 - 12:51:03 - 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
30.03.2024 - 12:51:03 - 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163)
30.03.2024 - 12:51:03 - 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060)
30.03.2024 - 12:51:03 - 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
30.03.2024 - 12:51:03 - 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Expected behavior

i didn't make any configuration.

### Steps to reproduce

Just load the plugin with 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by T14D3** [comment]
> Invalid color name: whıte
Whatever that character is where the "i" should be, it's not an "i", therefor it breaks. 
Replace `whıte` with `white`

**Comment by raqqeldon** [comment]
i searched for it, im using tab plugin without any configuration, **it works on my pc, but not on my server**

**Comment by T14D3** [comment]
Try a full server restart, plugman load is not a thing you should do. Also, send your config.yml/groups.yml

**Comment by raqqeldon** [comment]
[damn.zip](https://github.com/NEZNAMY/TAB/files/14811579/damn.zip)

**Comment by T14D3** [comment]
Can't find the issue in those files, my guess would be it's something in your luckperms groups? Like the prefix of your luckperm group has a messed up color? Either way, don't think it's a TAB issue, and if it is, someone more knowledgable than me has to look at it

**Comment by NEZNAMY** [comment]
Your weird language is missing the `i` letter and replaces it with something invalid. Try latest build from actions, I added compensation for this.

**Comment by raqqeldon** [comment]
**Thank you all so much, it fixed and now its works perfectly**, i dont know what causes this language problem, it was working on my pc but not on my vds server
