### ISSUE TITLE
Hex Color Code formating not working

### ISSUE THREAD

**Issue by Nacholebraa** [NEZNAMY/TAB#1260]
### Server version

Paper 1.20.4 (build 461)

### TAB version

v4.1.2

### Describe the bug

We us LuckPerms as the permissions plugin when we are displaying the prefix/suffix on tab. It does not display the hex color codes properly

![image](https://github.com/NEZNAMY/TAB/assets/36382273/fb41568a-f5f2-4341-95df-01950b504b3c)
![image](https://github.com/NEZNAMY/TAB/assets/36382273/4e188ea9-657d-413f-91ba-b9810d524f09)

### Expected behavior

Being able to use hex color codes within tab as we can use them within the tag that floats above the players head.

### Steps to reproduce

![image](https://github.com/NEZNAMY/TAB/assets/36382273/fb41568a-f5f2-4341-95df-01950b504b3c)
![image](https://github.com/NEZNAMY/TAB/assets/36382273/f0797dab-4ccb-434f-a741-1c9182321fea)

![image](https://github.com/NEZNAMY/TAB/assets/36382273/4e188ea9-657d-413f-91ba-b9810d524f09)
![image](https://github.com/NEZNAMY/TAB/assets/36382273/144f6f86-0ed2-4f47-8c11-5b48ae555ef9)
![2024-03-30_18 52 21](https://github.com/NEZNAMY/TAB/assets/36382273/fa601e7d-9b39-436d-a229-1077a404109b)

The color needs to be displayed correctly. The red staff tag is displayed correctly using the regular Minecraft color codes. However, when trying to use hex color codes in just the TAB, it does not display properly. 

### Additional info

I wouldn't fill these out frequently. If I forgot something, I apologize.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
I am unable to copypaste text from your images, so I cannot test it. Try defining prefixes directly in groups.yml and if it still doesn't work properly, send the file.

**Comment by Nacholebraa** [comment]
The issue persists. I couldn't upload the yml; however, I just copied and pasted it to a .txt, as GitHub suggested.


[New Text Document.txt](https://github.com/NEZNAMY/TAB/files/14815239/New.Text.Document.txt)

**Comment by NEZNAMY** [comment]
I asked you to specify the prefixes directly in groups.yml so I don't need to configure LP like you did.

**Comment by Nacholebraa** [comment]
Sorry, I wasn't following - I believe this is how you wanted it.

The systemmanager is the red one in the pictures above and the purple is the senioradministrator 

[New Text Document.txt](https://github.com/NEZNAMY/TAB/files/14835170/New.Text.Document.txt)

**Comment by NEZNAMY** [comment]
Your file only contained tabsuffix and not tagsuffix, I assume that's a mistake and added those too. The groups were also duplicated, so I removed the duplicated sections.

RGB codes work properly on both groups.

![image](https://github.com/NEZNAMY/TAB/assets/6338394/751caf53-67f4-4f15-8374-a05b151d7607)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/56bb79d7-62c6-4f64-95a9-1fbc6fc3518a)

Are you sure this is **not** caused by another plugin? See #1259 for example. Try without any other plugins.

**Comment by Nacholebraa** [comment]
It turns out that the placeholders used to connect to the group within the group.yml was mistyped on luckperms. Once the spelling issue was resolved, it seemed to have fixed the issue on our end. Sorry for wasting your time, I appreciate your patience.
