### ISSUE TITLE
TAB incompatible with future versions of Paper

### ISSUE THREAD

**Issue by untuned** [NEZNAMY/TAB#1261]
### Server version

N/A

### TAB version

4.1.2

### Describe the bug

TAB tries to parse the relocated CraftBukkit package version, which is unsupported behavior.
Forum post: https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

### Expected behavior

TAB not explicitly parsing the relocation version in https://github.com/NEZNAMY/TAB/blob/master/bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/nms/BukkitReflection.java#L42

### Steps to reproduce

Use this server jar (1.20.4):
https://github.com/PaperMC/testing/releases/tag/no-relocation

### Additional info

Error: https://paste.gg/p/anonymous/daa6410a07724776b8e9c5909ec12920

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by untuned** [comment]
Dupe of #1220

**Comment by NEZNAMY** [comment]
Literally a few lines below it is a comment saying `// Paper without CB relocation`.
