### ISSUE TITLE
Hex color changes between prefix content and player name's one

### ISSUE THREAD

**Issue by Elikill58** [NEZNAMY/TAB#1262]
### Server version

Paper 1.20.4

### TAB version

4.1.2

### Describe the bug

When using hex color code in tag prefix, the color is well showed for text in prefix but it's formatted as basic color for the player name:
![image](https://github.com/NEZNAMY/TAB/assets/17381066/b314fdec-6d98-4e29-bce7-75b6360c8a33)

### Expected behavior

Be the same hex color for the prefix content AND the player name

### Steps to reproduce

1. Use this config:
```yml
_DEFAULT_:
  tagprefix: '&#ff0000ccc'
```
2. Join
3. Check your name with F3 or with another account and you will see the two colors

### Additional info

Discovered with others plugins, then tested without any other plugin. Check using Laby mod and vanilla launcher

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Sounds like a [limitation](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#limitations) to me, specifically name itself not supporting RGB codes.

**Comment by Elikill58** [comment]
Thanks for fast answer. Some others server seems to have this type of feature :
![image](https://github.com/NEZNAMY/TAB/assets/17381066/17799ceb-c6a9-4478-95f1-e97206e920d2)

Do you have ideas about how they do?

**Comment by NEZNAMY** [comment]
Yes, literally read the page I sent you.

**Comment by Elikill58** [comment]
With something like [unlimite nametag](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode) ?

**Comment by NEZNAMY** [comment]
Yes.

**Comment by Elikill58** [comment]
> Yes.

It's generating armor stand to make it works ? (and not text display for 1.20+?)

**Comment by NEZNAMY** [comment]
The wiki page says it creates armor stands and that's exactly what it does.

**Comment by Elikill58** [comment]
Ok, can I make a suggestion to use TextDisplay for newer version?

**Comment by NEZNAMY** [comment]
No, [feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).

**Comment by Elikill58** [comment]
Oh yes, I forgot what you said in one of your last release message.
I will see if I can propose a pull request for this.
