### ISSUE TITLE
Bug with lines yaml syntex problem

### ISSUE THREAD

**Issue by MigraalPL** [NEZNAMY/TAB#1267]
### Server version

spigot 1.16.5

### TAB version

lastest

### Describe the bug

Screen 

### Expected behavior

Its not working i dont no how to fix it

### Steps to reproduce

I dont no how to fix it i did everthing but it doenst work

### Additional info

i cant edit it!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Your yaml syntax is clearly borken. Not a bug. You need yo fix yaml syntax.

**Comment by MigraalPL** [comment]
what is that?

**Comment by NEZNAMY** [comment]
The syntax of .yml files. I can't even fix it for you, because you didn't even send the broken file.

**Comment by MigraalPL** [comment]
every file i need to send you?

**Comment by MigraalPL** [comment]
But how to i need to give it?

**Comment by MigraalPL** [comment]
How can i send it to you? media fire?

**Comment by MigraalPL** [comment]
So how can i do it i mean send i to you @NEZNAMY

**Comment by NEZNAMY** [comment]
Upload it directly to github or pastebin. The full error message says which file it is, you just didn't send that part on purpose to make me not know which file it is.

**Comment by MigraalPL** [comment]
https://github.com/MigraalPL/problem here you can see

**Comment by MigraalPL** [comment]
@NEZNAMY

**Comment by NEZNAMY** [comment]
I fixed syntax of your config file here: https://pastebin.com/cvhw6nC3
Also stop mentioning me over and over, it doesn't teleport me to my PC anymore.

**Comment by MigraalPL** [comment]
Thank you very much
