### ISSUE TITLE
Toggle Vylepšenie

### ISSUE THREAD

**Issue by gazdyy** [NEZNAMY/TAB#1269]
### Server version

Paper 1.19.4

### TAB version

4.1.2

### Evidence

Prosím o pridanie možnosti aby si hráč mohol vypnúť len konkrétny boss bar na ktoré má oprávnenie. napríklad ak má hrač oprávnenie tab.bossbar.toggle.<nazov baru v configu> tak môže použiť príkaz /bossbar <nazov baru v configu> a vypne/zapne to daný bossbar.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
[Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).
This is not a performance issue causing lag.
You can achieve this using display conditions and third party plugins.
