### ISSUE TITLE
Players visiblty in radius

### ISSUE THREAD

**Issue by TheMixaDev** [NEZNAMY/TAB#127]
Hi, I am using minigames plugins, which put all players to one world, named "mg_main". I placed all the arenas in 400-500 blocks apart. And that would be useful to players on theese arenas to see only players on their arena, and that equals to see only players in 300-400 blocks away if player in world named "mg_main"

There is method Location#distance(Location l2) , which would be useful in this situation

**Comment by NEZNAMY** [comment]
How would you imagine the configuration to look like ? Being as short as possible offering as much as possible.

**Comment by TheMixaDev** [comment]
In my plugin(for chat) I did something like this:

world-with-radius-chat:
   mg_hub: 400
   mg_main: 300

On left side world name, on right side - radius aka distance

**Comment by TheMixaDev** [comment]
For my chat plugin I did something like this

https://pastebin.com/AdyurhmQ

**Comment by NEZNAMY** [comment]
This is not the direction I want to go. You are probably the only one who would benefit from this. Also hiding players is an operation that can easily go wrong and I'm not interested to investigate new bugs this introduces.
