### ISSUE TITLE
[Bug] RGB Colours not showing as RGB

### ISSUE THREAD

**Issue by craciu25yt** [NEZNAMY/TAB#1273]
### Server version

Purpur 1.20.5

### TAB version

4.1.4

### Describe the bug

It shows the RGB colours from tab to "legacy like" but it works as expected at the nametag

### Expected behavior

to show they as rgb

### Steps to reproduce

Step 1. add rgb to the rank
Step 2. put it to tab

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/48807342/45decf2d-da0b-4e97-8657-3c8994a768d2)
![image](https://github.com/NEZNAMY/TAB/assets/48807342/7d5ee962-77ba-41b1-9e0e-f65a588e56ac)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by craciu25yt** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/48807342/ab38f470-25ca-43a9-b3cd-9487a5ed4de4)
I forgot to upload this one

**Comment by NEZNAMY** [comment]
Send plugin list.

**Comment by Yarethf** [comment]
the same happens to me

**Comment by Yarethf** [comment]
![imagen_2024-04-24_105003304](https://github.com/NEZNAMY/TAB/assets/107740697/1a4da54a-3f03-4df6-aaa5-86a67bbc299e)

**Comment by Yarethf** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/107740697/014fbb8e-8120-427a-8be3-ec96a35664b0)

**Comment by Yarethf** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/107740697/f80283d4-0753-48e1-b9df-70add18244a8)
![image](https://github.com/NEZNAMY/TAB/assets/107740697/165acffd-efad-4ffe-8483-2b25c7626968)
![image](https://github.com/NEZNAMY/TAB/assets/107740697/25874fc5-3229-4523-bd4e-8dffecf3ae71)

**Comment by NEZNAMY** [comment]
#1259 #1265

**Comment by Yarethf** [comment]
Should I update or delete?

**Comment by NEZNAMY** [comment]
You should not use TAB's issue tracker for reporting bugs in other plugins. Other than that, do whatever you want.

**Comment by NEZNAMY** [comment]
@craciu25yt ?

**Comment by craciu25yt** [comment]
sorry, I just read github emails rn. I will be in my computer in few hours to send them

**Comment by craciu25yt** [comment]
> #1259 #1265

I have grim tho, is it the issue?

**Comment by NEZNAMY** [comment]
Remove it to find out.

**Comment by craciu25yt** [comment]
ok, when I get to my house (arround 5pm utc+1) I will try it and update you

**Comment by craciu25yt** [comment]
yes it was a grim issue
