### ISSUE TITLE
"abovename" Some groups names are invalid

### ISSUE THREAD

**Issue by BangXi** [NEZNAMY/TAB#1274]
### Server version

paper-1.20.4-496.jar

### TAB version

TAB-4.1.5-SNAPSHOT.jar

### Plugin list

TAB  LuckPerms   /Just two

### Describe the bug

"abovename" is now invalidated by the name of the permission group

### Expected behavior

"abovename" should display fine

### Steps to reproduce

<config.yml>：
  unlimited-nametag-mode:
    enabled: true

<groups.yml>：
shop:
  abovename: 'Text1'
cs:
  abovename: 'Text2'
hhhh:
  abovename: 'Text3'

Grant the player permission LP&group "shop"，The "abovename" function is invalid❌
Grant the player permission LP&group "cs"，"abovename" is displayed normally✅
Grant the player permission LP&group "hhhh"，The "abovename" function is invalid❌

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure weights are correct? Check `/tab debug <player>` when it's wrong, it might tell you what's wrong.

**Comment by BangXi** [comment]
> Are you sure weights are correct? Check `/tab debug <player>` when it's wrong, it might tell you what's wrong.

Thank you！！！！！！！！！！！！！！"weight"!!!!!!!!
