### ISSUE TITLE
 group (none) is not in sorting list

### ISSUE THREAD

**Issue by F3F5** [NEZNAMY/TAB#1275]
### Server version

Paper 1.20.5

### TAB version

4.1.4

### Plugin list

TAB

### Describe the bug

[07:04:52 INFO]: [TAB] [WARN] Player MichaelKozlov's group (none) is not in sorting list! Sorting list: owner,admin,mod,helper,builder,vip,default. Player will be sorted on the bottom.

### Expected behavior

default config

### Steps to reproduce

Step 1. install plugin
Step 2. start server

### Additional info

no

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
How is this a bug? What is your expected behavior? You said "default config", what kind of expected behavior is that?

**Comment by F3F5** [comment]
passive agressor, bye
