### ISSUE TITLE
Compatibility issue with "connector" mod

### ISSUE THREAD

**Issue by capubara** [NEZNAMY/TAB#1276]
### Server version

ketting-1.20.1

### TAB version

4.1.4

### Plugin list

 LuckPerms, LootChest, EntityRespawner, PlaceholderAPI, Spicord, CMILib, QuickSave, BanAnnouncer, ProtocolLib, SkinsRestorer, BlueSlimeCore, Maintenance, Pl-Hide-Pro, MOTD, Vault, HideStream, MyCommand, ChatManager, ShopX, WorldEdit, MadMine, AuthMe, nightcore, WorldGuard, Citizens, Shopkeepers, PrimeSeller, DiscordSRV, ajLeaderboards, DeluxeMenus, BanItem, TAB, WGExtender, LibertyBans, CommandNPC, NexEngine, KOTL, Denizen, WorldEditSUI, UltraCosmetics, ExcellentEnchants, ConditionalEvents, CMI, ExcellentCrates, CombatLogX

### Describe the bug

i install TAB and everything was fine before player join the server.When player join i can't reload plugin, it becomes work wrong like names of players are hang up in the air.When i reload i see lots of WARNS and errors

### Expected behavior

it have too work fine, because before join in console i see "Tab is successfully reload"
https://mclo.gs/Uf8MoPb - Errors in config TAB
https://mclo.gs/cmp3u1x - All logs

### Steps to reproduce

Download Tab
join game
use /tab reload

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Send link for your server software, which the plugin is not compatible with.

**Comment by NEZNAMY** [comment]
I tried latest version of that software and it works fine for me. Do you have discord? I would send you a jar to test.

**Comment by NEZNAMY** [comment]
@capubara did you die?

**Comment by capubara** [comment]
Oh, man, sorry for ignoring you, everything is okey , the problem was with mod(connector with fabric)

**Comment by NEZNAMY** [comment]
Which mod? Are you interested in getting it resolved?

**Comment by capubara** [comment]
i said , it was connector

**Comment by NEZNAMY** [comment]
I don't see such thing in the logs you sent. Can you send a link? And Isn't Ketting a forge hybrid? Or is it fabric?

**Comment by capubara** [comment]
https://modrinth.com/mod/connector 

https://modrinth.com/mod/forgified-fabric-api

These mods i have deleted and then everything works fine 

also i have deleted l2 library, but i think,that it is not begging of our problem 

My nickname in discord: capybara5591

**Comment by capubara** [comment]
ketting is forge hybrid
