### ISSUE TITLE
Issue with a custom plugin (OutpostPal)

### ISSUE THREAD

**Issue by developedbyalex** [NEZNAMY/TAB#1277]
### TAB version

v4.1.4

### Software causing compatibility issue

Possibly placeholderAPI causing an issue to not display the placeholder. If need to reproduce, please contact for the plugin as it's planned to be a paid, so do not want to release it to the public.

### Additional info

A custom plugin called outpost pal displaying the placeholder fine on holograms and through /papi parse. However, not displaying on scoreboard.

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
That is an extreme lack of information I cannot do anything with.

**Comment by developedbyalex** [comment]
> That is an extreme lack of information I cannot do anything with.

PlaceholderAPI version: 2.11.5
Server Version: Paper 1.20.4 (latest)

## Pictures
Picture of the placeholder working on a hologram:
![image](https://github.com/NEZNAMY/TAB/assets/48566683/57a0baf3-17ab-4a0d-a16e-54a395d6614e)
Picture of the placeholder not working on TAB scoreboard:
![image](https://github.com/NEZNAMY/TAB/assets/48566683/af1adc90-eb58-42d9-9cbf-5669a8283a9e)
Parsing the placeholder with PAPI:
![image](https://github.com/NEZNAMY/TAB/assets/48566683/811306e2-89df-43b4-ac91-6fef4427005f)

I don't know what other information I can provide? Like I said, if you want the plugin to reproduce, let me know. I will not release it publically since it's going to be a paid plugin. 

Thanks!

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/5ab34595-9896-4977-9fde-7400427a1b46)
?

**Comment by developedbyalex** [comment]
Amazing, it worked. Thanks!
