### ISSUE TITLE
Update 1.20.6 

### ISSUE THREAD

**Issue by Twizzer** [NEZNAMY/TAB#1278]
### TAB version

4.1.4

### Software causing compatibility issue

After updating my server to Spigot 1.20.6 it appears TAB no longer reflect the ping of the user.

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
What happened here?
