### ISSUE TITLE
Scorboard probleme

### ISSUE THREAD

**Issue by xenophe** [NEZNAMY/TAB#1279]
### TAB version

4.1.4

### Software causing compatibility issue

Je n'arrive pas a afficher mais kill et mort sur le scoreboard
![image](https://github.com/NEZNAMY/TAB/assets/123984082/d8622d81-e9c4-40a2-96ea-b54204e7d4ab)
![image](https://github.com/NEZNAMY/TAB/assets/123984082/33285c8b-e643-49e2-8aea-51d1544de53d)

### Additional info

version du serveur 1.8.8 spigot/bukkit

### Checklist

- [X] I am running latest version of the plugin
- [X] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by xenophe** [comment]
"Je n'arrive pas a afficher **mes** kill et mort sur le scoreboard"

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d2ce3323-e3f8-455d-9942-6d03517049a2)
`||` is only for 1.20.3+. It is not visible on lower versions. Remove those symbols and you'll be able to see the text ([more info](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#lines)). How is this a compatibility issue?
