### ISSUE TITLE
Can't delete web option in TAB

### ISSUE THREAD

**Issue by elmundomusical2** [NEZNAMY/TAB#128]
**Server version**
Forge 1.12.2

**Plugin version** ("latest" is not a version)
2.7.1

**Describe the bug**
I can't delete the "visit our web www.domain.com" text from the config/animation file

**Expected behavior**
That I could delete it

**Actual behavior**
I can't delete it

**Additional info** (errors, screenshots, ...)
![Captura de pantalla (50)](https://user-images.githubusercontent.com/58357415/77824682-c361dd00-7104-11ea-91d0-fffdb894d0d2.png)

**Comment by NEZNAMY** [comment]
config.yml "footer" section at the config beginning.

**Comment by elmundomusical2** [comment]
The footer section hasn't got anything related to the web section...

**Comment by NEZNAMY** [comment]
Show your config.yml

**Comment by elmundomusical2** [comment]
![Captura de pantalla (51)](https://user-images.githubusercontent.com/58357415/77825646-e42d3100-710a-11ea-8b1e-d5b27e2ecb14.png)

**Comment by NEZNAMY** [comment]
Full config.

**Comment by elmundomusical2** [comment]
`# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

nametag-refresh-interval-milliseconds: 1000
tablist-refresh-interval-milliseconds: 1000
header-footer-refresh-interval-milliseconds: 100

header:
  - "%animation:ServerName%"
  - ""
  - "&b¡Hola&3 &l%nick%&r&b!"
  - "&7Jugadores conectados: &f%online%"
  - ""
  - "%animation:ping-tps%"
  - ""
  - "&7&l Memoria RAM: %memory-used% MB / %memory-max% MB"
  - "%animation:MyAnimation1%"
footer:
  - "%animation:MyAnimation1%"
  - "%animation:time%"

tablist-objective: PING
tablist-objective-custom-value: "%some_placeholderapi_placeholder%"
group-sorting-priority-list:
  - owner
  - admin
  - mod
  - helper
  - builder
  - premium
  - player
  - default
Groups:
  Owner:
    tabprefix: "&0&l[&a&lOwner&0&l] &a"
    tagprefix: "&2&lOwner &a"
  Admin:
    tabprefix: "&0&l[&4&lAdmin&0&l] &1"
    tagprefix: "%animation:admin_prefix%"
  Player:
    tabprefix: "&0&l[&7&lPlayer&0&l] &3"
    tagprefix: "&2&lPlayer &3"
  hfexample:
    header:
      - "This is an example for per-group header/footer"
    footer:
      - "applied to a group"
  _OTHER_:
    tabprefix: "%vault-prefix% "
    tagprefix: "%vault-prefix% "
    tabsuffix: "%afk%"
    tagsuffix: "%afk%"
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"

Users:
  _NEZNAMY_:
    tabprefix: "&6&lTAB Author &a"
    tagprefix: "&6&lTAB &r&a"
    abovename: "&bOh look, 3 lines of text !"
    belowname: "&eThere's only one plugin out there supporting it"

belowname:
  enabled: true
  refresh-interval-milliseconds: 200
  number: "%health%"
  text: "Health"

enable-collision: true
do-not-move-spectators: false
unlimited-nametag-prefix-suffix-mode:
  enabled: false
  modify-npc-names: false

per-world-settings:
  world1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
  world2-world3:
    header:
      - "This is a shared header for"
      - "world2 and world3"
placeholders:
  afk-yes: " &4*&4&lAFK&4*&r"
  afk-no: ""
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  remove-strings:
    - "[]"
    - "< >"
rank-aliases:
  Admin: "&4&lADMIN"
  Mod: "&b&lMOD"
  Premium: "&6&lPREMIUM"
  Ultra: "&b&lULTRA"
  Legend: "&a&lLEGEND"
  Titan: "&c&lTITAN"
  Youtuber: "&c&lYOUTUBE"
  _OTHER_: "&7No Rank"
  
disable-features-in-worlds:
  header-footer:
    - disabledworld
  tablist-names:
    - disabledworld
  nametag:
    - disabledworld
  tablist-objective:
    - disabledworld
  bossbar:
    - disabledworld
  belowname:
    - disabledworld`

**Comment by NEZNAMY** [comment]
You probably forgot /tab reload.

**Comment by elmundomusical2** [comment]
I've done it, and I also restarted the server

**Comment by NEZNAMY** [comment]
Upload config and animations to pastebin, i will try it and take a screenshot showing how it works.

**Comment by elmundomusical2** [comment]
https://pastebin.com/xc0GmvE9

**Comment by elmundomusical2** [comment]
https://pastebin.com/vkr6g5hJ

**Comment by NEZNAMY** [comment]
http://prntscr.com/rodn6g as predicted. You might have accidentally the plugin installed on bungee too and both are trying to send it.

**Comment by elmundomusical2** [comment]
So how can I solve it?

**Comment by NEZNAMY** [comment]
I don't know what the problem is, you didn't react to my previous possible reason.

**Comment by elmundomusical2** [comment]
I would send you the plugin's folder. Wait a minute

**Comment by elmundomusical2** [comment]
Here is the folder→ https://drive.google.com/drive/folders/1vXyBTvlUpwzRadI5jmphEAlz3j_3kyWe?usp=sharing
Could you edit the files if there is some problem please? Thanks!!

**Comment by NEZNAMY** [comment]
http://prntscr.com/rodrb5 in the config.yml you linked.

**Comment by elmundomusical2** [comment]
Oh, ok. That's strange. In Notepad++, this text doesn't appear. Thanks!
