### ISSUE TITLE
Player List Objective Doesn't Work

### ISSUE THREAD

**Issue by TheCrafter8000** [NEZNAMY/TAB#1282]
### Server version

1.20.6

### TAB version

4.1.4

### Plugin list

CleanPing
Floodgate
Geyser
KickRedirect
LuckPerms
Maintenance
SlashHub
TAB
VelocityWhitelist
ViaBackwards
ViaVersion

### Describe the bug

the playlist objective is enabled with the value being %ping% but when you log on to the server is doesn't show.

### Expected behavior

To show on the tab list.

### Steps to reproduce

Make a Velocity Server
Enable playerlist objective with this config

playerlist-objective:
  enabled: true
  value: '%ping%'
  disable-condition: ''
  fancy-value: '&7Ping: %ping%'
 
 Log on to the server.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
This feature requires bridge plugin installed like wiki says. Show output of /pl.

**Comment by TheCrafter8000** [comment]
how come this isnt need on bungeecord?

**Comment by NEZNAMY** [comment]
BungeeCord contains scoreboard packets, velocity doesn't.

**Comment by TheCrafter8000** [comment]
oh, alright. thanks for the info

**Comment by NEZNAMY** [comment]
What is the bug then?

**Comment by TheCrafter8000** [comment]
there is no bug lol, everything is working now. i just didnt see it in the wiki
