### ISSUE TITLE
[Unlimited Nametags] Armor stands are 2 blocks higher than they should be

### ISSUE THREAD

**Issue by YisusTV** [NEZNAMY/TAB#1283]
### TAB version

TAB-4.1.5-SNAPSHOT

### Software causing compatibility issue

Mods:
AdvancementPlaques-1.20.1-forge-1.5.1.jar
AI-Improvements-1.20-0.5.2.jar
alexscaves-1.1.4.jar
alexsmobs-1.22.8.jar
amendments-1.20-1.1.27.jar
apexcore-1.20.1-10.0.0.jar
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
artifacts-forge-9.5.4.jar
athena-forge-1.20.1-3.1.2.jar
beautify-2.0.2.jar
betterfpsdist-1.20.1-4.3.jar
BiomesOPlenty-1.20.1-18.0.0.598.jar
born_in_chaos_[Forge]1.20.1_1.2.jar
Chipped-forge-1.20.1-3.0.6.jar
citadel-2.5.4-1.20.1.jar
cloth-config-11.1.118-forge.jar
connectedglass-1.1.11-forge-mc1.20.1.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CreativeCore_FORGE_v2.11.27_mc1.20.1.jar
Croptopia-1.20.1-FORGE-3.0.4.jar
cupboard-1.20.1-2.6.jar
curios-forge-5.9.0+1.20.1.jar
decorative_blocks-forge-1.20.1-4.1.3.jar
deeperdarker-forge-1.20.1-1.2.1.jar
dummmmmmy-1.20-1.8.14.jar
Dungeon Crawl-1.20.1-2.3.14.jar
DungeonsArise-1.20.x-2.1.58-release.jar
DungeonsAriseSevenSeas-1.20.x-1.0.2-forge.jar
easy_npc_1.20.1-4.4.0.jar
EpheroLib-1.20.1-FORGE-1.2.0.jar
fantasyfurniture-1.20.1-9.0.0.jar
FarmersDelight-1.20.1-1.2.4.jar
FastFurnace-1.20.1-8.0.2.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
Forge 1.20.1 Minecraft Middle Ages 0.0.5.jar
fusion-1.1.1-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.4.4.jar
iceandfire-2.1.13-1.20.1-beta-4.jar
Iceberg-1.20.1-forge-1.1.21.jar
Jade-1.20.1-forge-11.8.0.jar
jei-1.20.1-forge-15.3.0.4.jar
journeymap-1.20.1-5.9.21-forge.jar
majrusz-library-forge-1.20.1-7.0.6.jar
majruszs-difficulty-forge-1.20.1-1.9.10.jar
mcw-bridges-3.0.0-mc1.20.1forge.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
mcw-fences-1.1.1-mc1.20.1forge.jar
mcw-furniture-3.2.2-mc1.20.1forge.jar
mcw-lights-1.0.6-mc1.20.1forge.jar
mcw-paintings-1.0.5-1.20.1forge.jar
mcw-paths-1.0.4forge-mc1.20.1.jar
mcw-roofs-2.3.0-mc1.20.1forge.jar
mcw-trapdoors-1.1.2-mc1.20.1forge.jar
mcw-windows-2.2.1-mc1.20.1forge.jar
Mine-Pop! 1.0-1.20.1 (FORGE).jar
modernfix-forge-5.17.0+mc1.20.1.jar
moonlight-1.20-2.11.14-forge.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.1.jar
PlayerRevive_FORGE_v2.0.25_mc1.20.1.jar
plushies-1.4.0-forge.jar
polymorph-forge-0.49.3+1.20.1.jar
rechiseled-1.1.6-forge-mc1.20.jar
redirector-5.0.0.jar
RegionsUnexploredForge-0.5.5+1.20.1.jar
resourcefullib-forge-1.20.1-2.1.24.jar
SereneSeasons-1.20.1-9.0.0.46.jar
smoothchunk-1.20.1-3.6.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.21.609.jar
sophisticatedstorage-1.20.1-0.10.21.793.jar
stalwart-dungeons-1.20.1-1.2.8.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.10.jar
TerraBlender-forge-1.20.1-3.0.1.4.jar
twilightforest-1.20.1-4.3.2145-universal.jar
voicechat-forge-1.20.1-2.5.13.jar

Plugins:
AdvancedServerList-Bukkit-3.5.1.jar
Clearlag.jar
customcrafting-spigot-4.16.9.1.jar
DailyRewardsPlus-1.3.5.1.jar
DecentHolograms-2.8.6.jar
DiscordSRV-Build-1.27.0.jar
EssentialsX-2.20.1.jar
EssentialsXChat-2.20.1.jar
ExcellentCrates-5.2.2.1.jar
ExecutableItems_Prem-6.24.4.30.jar
Graves-4.9.1.6.jar
LuckPerms-Bukkit-5.4.102.jar
MyCommand.jar
nightcore-2.5.2.1.jar
NotRanks-1.6.3.jar
oraxen-1.173.0.jar
PlaceholderAPI-2.11.5.jar
ProtectionStones-2.10.4.jar
ProtocolLib.jar
SCore-4.24.4.30.jar
SkinsRestorer.jar
sleep-most-5.4.0.jar
TAB-4.1.5-SNAPSHOT.jar
tebex-bukkit-2.0.5.jar
UserLogin.jar
Vault.jar
wolfyutils-spigot-4.16.15.1.jar
worldedit-bukkit-7.2.15.jar
worldguard-bukkit-7.0.9-dist.jar
WorldGuardExtraFlags.jar

### Additional info

It is the list of mods and plugins that are on my server in case anyone has a problem with the TAB plugin

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
What did you try? Send your TAB configuration (config.yml and groups.yml) and a screenshot of it not working.

**Comment by YisusTV** [comment]
[config and groups.zip](https://github.com/NEZNAMY/TAB/files/15226046/config.and.groups.zip)
![image](https://github.com/NEZNAMY/TAB/assets/146752062/d8af0f11-cb07-4ff1-bd5c-7f1a1c0ddacc)

**Comment by NEZNAMY** [comment]
The only static line defined is "myCustomLine", which you are not using in groups,yml, so it's not visible.
Armor stands being 2 blocks higher is wrong however. The only currently known cause is using 1.8.0 client. Otherwise it sounds like a different issue and you'll need to find out what exactly is causing it, since it works fine for everyone else.

**Comment by YisusTV** [comment]
If it works correctly with the same .jar that I use

![image](https://github.com/NEZNAMY/TAB/assets/146752062/2592b973-8d29-433d-8a29-b52f7aef4c2f)

**Comment by NEZNAMY** [comment]
Same what jar? What did you change that it suddenly works?

**Comment by YisusTV** [comment]
Arclight Trials, Just enter without mods and only with the plugin

**Comment by NEZNAMY** [comment]
Then there you go. Find out which mod is causing it. I'm not interested in finding and downloading them all myself, that's the reporter's job.

**Comment by NEZNAMY** [comment]
Unlimited nametag mode was marked for removal and no more bugs will be fixed. See https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c for more info.
