### ISSUE TITLE
bug PlaceholderAPI

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB#1284]
### Server version

waterfall-1.20-577

### TAB version

TAB-4.1.5-SNAPSHOT

### Plugin list

TAB-4.1.5-SNAPSHOT
TAB-Bridge v5.0.6

### Describe the bug

when I updated TAB and TAB-Bridge, sometimes the tab bugs and this happens, so I have to type in the console /btab reload and it returns to normal

https://prnt.sc/CFRJfxnc4B2U

when I give /btab reload it returns to normal, but this is very rare, it only happened when I updated the tab plugin in waterfall and on the servers with TAB-Bridge

my config: https://mclo.gs/Zb6QT8v

my groups.yml: https://mclo.gs/7h3n4Dm

### Expected behavior

no bugs happen

### Steps to reproduce

update the tab plugin to the latest version

### Additional info

I have a waterfall server, lobby and survival and other servers, the tab plugin is on a network, but the problem happens on the backend

it's not respecting the lobby, it's using the lobby configuration, see this prefix is from the lobby and it's appearing in survival, and the player is in survival it happens to some players, they're in survival but it's showing the lobby prefix, if you notice it's a prefix with simple colors like &a

https://prnt.sc/g_rJddD9fxUI

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by SrMonsterYT** [comment]
I don't know if this bug has been fixed but it seems that the problem is a visual bug, it's happening several times, but some players see it and others don't.

**Comment by SrMonsterYT** [comment]
one before the one you just posted

**Comment by NEZNAMY** [comment]
Well then it makes sense the bug is preseny if you didn't update to the version that fixes it.
