### ISSUE TITLE
[Velocity] Compatibility issue with LimboAuth - Tablist entries not getting formatted

### ISSUE THREAD

**Issue by listtw** [NEZNAMY/TAB#1285]
### Server version

Purpur 1.20.1 Velocity 3.3.0

### TAB version

tab - 4.1.4 btab - 5.0.6

### Plugin list

tab, tab-bridge

### Describe the bug

A player who joins the server sees all the suffixes and prefixes of other users except his own. I have already deleted all plugins, and reviewed your Wiki several times.

### Expected behavior

the plugin must correctly display its own nickname in the tab

### Steps to reproduce

Use velocity + btab

### Additional info

![Снимок экрана 2024-05-08 120244](https://github.com/NEZNAMY/TAB/assets/169247769/171fe926-c9f0-408c-a22d-aef210c641ba)
the screenshot shows how my nickname is displayed (list_tw)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Try latest build from [actions](https://github.com/NEZNAMY/TAB/actions).

**Comment by listtw** [comment]
I installed TAB-4.1.5-SN, it does not work

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ''
  - '#00FF7F&lʟᴇᴀꜰ ᴄɪᴛʏ#00FF7F&l🌲'
  footer:
  - ' #90EE90ᴏɴʟɪɴᴇ: %bungee_total% #90EE90ᴘʟᴀʏᴛɪᴍᴇ: %statistic_hours_played%#90EE90ʜ '
  - '#BCF5BCꜱʜᴏᴘ.ʟᴇᴀꜰᴄɪᴛʏ.ʀᴜ'
  - ''
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,moder,helper,LC+,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
playerlist-objective:
  enabled: false
  value: '%ping%'
  fancy-value: '&7Ping: %ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  fancy-display-players: '&c%health%'
  fancy-display-default: NPC
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard-1.20.3+:
      title: <#E0B11E>MyServer</#FF0000>
      display-condition: '%player-version-id%>=765'
      lines:
      - '&7%date%'
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7:||%online%'
      - '* &eCurrent World&7:||%worldonline%'
      - '* &eStaff&7:||%staffonline%'
      - ''
      - '&6Personal Info:'
      - '* &bRank&7:||%group%'
      - '* &bPing&7:||%ping%&8ms'
      - '* &bWorld&7:||%world%'
      - '%animation:MyAnimation1%'
    scoreboard:
      title: <#E0B11E>MyServer</#FF0000>
      lines:
      - '&7%date%'
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ''
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&8ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: true
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%123'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- owner
- admin
- moder
- helper
- lc+
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: false
  isolate-unlisted-servers: false
  spy-servers:
  - survival
  - creative
  - lobby
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
permission-refresh-interval: 1000

**Comment by NEZNAMY** [comment]
Show output of `/btab debug <player>`. Does `/btab reload` fix it?

**Comment by listtw** [comment]
/btab reload - has no effect
![Снимок экрана 2024-05-08 121936](https://github.com/NEZNAMY/TAB/assets/169247769/27fb9916-489c-4c38-b520-a9f2bdcd53e3)
![Снимок экрана 2024-05-08 121949](https://github.com/NEZNAMY/TAB/assets/169247769/17dfac0e-8cfd-4aec-874c-c11e6f851ad7)

**Comment by NEZNAMY** [comment]
Try toggling `use-online-uuid-in-tablist` option.

**Comment by listtw** [comment]
does not work

**Comment by NEZNAMY** [comment]
Since velocity has lots of settings that might affect tablist UUIDs, I may not be able to reproduce it just with these steps. Create a test network with only TAB and bridge where this issue is still present, zip it and send it, so I can try it myself.

**Comment by listtw** [comment]
I want to clarify that if a player assigned a group, the color of his nickname changed, but suffixes and prefixes did not appear

**Comment by listtw** [comment]
"minecraft /team"

**Comment by NEZNAMY** [comment]
TAB's teams override vanilla teams. I'll need that setup.

**Comment by listtw** [comment]
![Снимок экрана 2024-05-08 123525](https://github.com/NEZNAMY/TAB/assets/169247769/2f6987ed-3da1-4c45-a166-8aae998ade08)
I somehow changed my nickname color using /cmi:glow

**Comment by NEZNAMY** [comment]
Sounds like TAB's teams aren't making it through then. That is also an issue. I'll need the setup.

**Comment by listtw** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/169247769/f27ab719-3a46-401f-b81f-6cb02d042d3a)
I FOUND IT! some proxy plugin replaces tab with tag. I'll write later what kind of plugin it was

**Comment by listtw** [comment]
because of the file - limboauth-v2.mv.db, this error occurs, I do not even know what to do, there are more than 2000-3000 accounts in this db

**Comment by NEZNAMY** [comment]
Try asking on their support what the plugin does that could break TAB.

**Comment by NEZNAMY** [comment]
What do you mean by online / offline players?

**Comment by listtw** [comment]
limbo auth can register both online and offline players. Online players skip the registration process

**Comment by listtw** [comment]
`use-online-uuid-in-tablist` - does not change anything :(

**Comment by listtw** [comment]
I know that everything will work correctly only if the TAB is on internal servers, but then I won't get a list of players from multiple servers

**Comment by NEZNAMY** [comment]
Can you make a test setup with only TAB and the auth plugin that reproduces the issue, zip the whole network and send it?

**Comment by listtw** [comment]
how do I transfer the files to you?

**Comment by listtw** [comment]
Here is the link to the servers - https://www.mediafire.com/file/kyuie2xyop8ig59/testserver.zip/file . In order to get the bug, log in to the server, register using the `/reg <pass>` command, look in the tab and take a screenshot, register `/premium <pass> confirm`, re-visit the server, look in the tab and take a screenshot.

I use a translator, maybe you will understand something wrong. If you don't have the /premium command, download the lp and grant the `limboauth.commands.premium` permission

**Comment by listtw** [comment]
Can you please tell me when you will be checking? I want to be at least a little aware of events

**Comment by NEZNAMY** [comment]
I'll look into it today. You should still be able to use teams though, which format tablist by default unless overridden (which is the part that's failing).

**Comment by listtw** [comment]
should I add placeholders to the team?

**Comment by NEZNAMY** [comment]
You should configure tagprefix. It will (or should) appear in tablist as well.

**Comment by listtw** [comment]
it doesn't work correctly, I checked

**Comment by listtw** [comment]
prefixes will also appear above the players' heads, which I don't need.

**Comment by NEZNAMY** [comment]
It's a workaround, it's not about needing. If you don't mind having them, just do it. I am going to test your setup right now.

**Comment by listtw** [comment]
thanks

**Comment by NEZNAMY** [comment]
After translating messages back to english I get this when trying to activate premium:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/0a2ff796-a8b0-496c-8edf-622bfd44eae7)

I obviously bought the game and am connected via mojang launcher and everything.

**Comment by listtw** [comment]
it's strange, I've never even seen this error, even unlicensed players could register / premium

**Comment by listtw** [comment]
tell me your minecraft nickname, I'll try to make / premium for you and send you a database

**Comment by NEZNAMY** [comment]
It's `_NEZNAMY_`. I still don't understand why would it not work.

**Comment by listtw** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/169247769/19232f1f-71de-4b5d-aa08-8eadc7f7f697)
I have just rechecked the premium connection from my `list_tw` account. Everything worked out. I think there is a mistake in your connection

**Comment by listtw** [comment]
just try to restart the launcher and connect again, this happens periodically

**Comment by listtw** [comment]
is there anything else I can help you with to speed up the error detection process?

**Comment by NEZNAMY** [comment]
I was able to successfully reproduce the issue. I will look into fixing it now.

**Comment by NEZNAMY** [comment]
I did some investigation and it looks like this will require some form of a fix from LimboAuth. Turning connections into online connections with that plugin causes Tablist entry tracker to map entries using online UUID, but mapped entries still have offline ID, so any change made to entries has no effect, since they use the wrong ID. 
What's worse, even if LimboAuth somehow made these entries track online UUID, there is no way to get player's online UUID, since Velocity API returns offline IDs for all players when LimboAuth is installed.

**Comment by listtw** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/169247769/c4b9e82f-b2d8-44f1-8416-6d04f962617d)
- either use the tab on the servers
- themselves or write to the tab developer so that he takes the uuid from limboapi if it is worth it
- LimboAPI.getInitialID()

**Comment by NEZNAMY** [comment]
As I said, Velocity's Tablist entry tracker's actions are invalid due to wrong ID, so even if I knew what the player's online UUID is, it wouldn't fix anything.

**Comment by listtw** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/169247769/68125777-ee51-4b49-870f-665c300d0173)
Unfortunately, I don't know what he means by that

**Comment by NEZNAMY** [comment]
Me getting player's UUID using that function doesn't fix the broken Velocity API.

**Comment by listtw** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/169247769/d69bc3a5-24ac-4f12-996f-c19249fe5ff4)
Yes, it's not about velocity, but the fact that in velocity there is no way to normally replace the uuid after logging in. Well, there is not because there is no such thing in the Mojang protocol. Therefore, the problem is that this was done in the limbo api, you need to use it and there will be a correct id

**Comment by NEZNAMY** [comment]
The person doesn't understand. Ask them to make a tiny plugin that changes tablist display name of a player on join. Regardless of what they try, it will not work with LimboAuth installed.

**Comment by listtw** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/169247769/d6ce98cb-cd83-453c-bef7-7a4ae0194ca5)
- Everything will work if done correctly

Honestly, I don't know what needs to be done to solve the problem, and it's very hard to give up limbo

**Comment by listtw** [comment]
we have more than 3,000 passwords in the database

**Comment by NEZNAMY** [comment]
If everything will work, give me that example plugin that will work.
You can enable teams and configure tagprefix, which will appear in tablist while this feature isn't working.

**Comment by listtw** [comment]
This problem was previously solved by enabling TAB from you and TAB from cmi on the main server. All the players on the proxy were shown, as well as the correct display of online players. But the TAB was still flashing intermittently because of this, so this is not a solution to the problem. I hope this will give you something

**Comment by NEZNAMY** [comment]
Unfortunately that didn't help me at all. I'll try making an example plugin tomorrow to prove it's a bug in that plugin.

**Comment by NEZNAMY** [comment]
Using the following test code:
```
    @Subscribe
    public void onConnect(@NotNull ServerPostConnectEvent e) {
        new Thread(() -> {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
            UUID onlineUUID = UUID.fromString("237d8b55-3f97-4749-aa60-e9fe97b45062");
            UUID offlineUUID = UUID.fromString("6603bf58-226d-3b2b-8f5e-2f5d89104533");
            e.getPlayer().getTabList().getEntry(onlineUUID).ifPresent(entry -> entry.setDisplayName(Component.text("ONLINE " + e.getPlayer().getUsername())));
            e.getPlayer().getTabList().getEntry(offlineUUID).ifPresent(entry -> entry.setDisplayName(Component.text("OFFLINE " + e.getPlayer().getUsername())));
        }).start();
    }
```
Should format my display name based on what UUID the tablist uses. The 2 UUIDs are my online and offline UUIDs.

Online mode enabled:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/94ec6314-7ae8-46ce-8eb5-97dfa3330ad2)

Online mode disabled:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d00011b3-fce1-4cc7-ace1-c3088e84676e)

LimboAuth installed (tried both online and offline velocity):
![image](https://github.com/NEZNAMY/TAB/assets/6338394/63ae205a-ccd0-417c-bb1c-a9a909f46422)

Now I challenge the devs to find the supposed change in my code that will make tablist formatting work.

**Comment by listtw** [comment]
limbo fixed the bug, thanks a lot for the time allocated
https://modrinth.com/plugin/limboapi/version/1b18b3d
