### ISSUE TITLE
[Unlimited Nametags] Relational placeholders not refreshing

### ISSUE THREAD

**Issue by Gal1leooo** [NEZNAMY/TAB#1286]
### Server version

Velocity

### TAB version

TAB 4.1.4

### Plugin list

ajQueuePlus
CommandBlocker
CraftingStore
ForcePack
LiteBans
LuckPerms-Velocity
minimotd-velocity
nuvotifier
protocolize-velocity
ServerUtils-Velocity
spark
SyncCommands
TAB
VulcanVelocity

### Describe the bug

When I use a relational placeholder of my custom plugin in the customtagname it does not always update but only when another placeholder in the customtagname is also updated despite having entered the refresh-intervals at 50.
Also I also put it in the placeholder-output-replacements but the replacements are not applied.

### Expected behavior

The placeholder updates every time defined in the refresh intervals and the output-replacements effectively replace the output.

### Steps to reproduce

I don't know if the problem also exists with other relational placeholders because I use a custom plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/1249

**Comment by Gal1leooo** [comment]
Thanks very much, now it works.
Instead for the placeholder-output-replacements?

**Comment by NEZNAMY** [comment]
I guess those are not applied. This will need to be implemented in bridge.

**Comment by NEZNAMY** [comment]
Unlimited nametag mode was marked for removal and no more bugs will be fixed. See https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c for more info.
