### ISSUE TITLE
Spectators cannot see the nametag of a invisible players

### ISSUE THREAD

**Issue by Overwrite987** [NEZNAMY/TAB#1287]
### Server version

Paper 1.16.5 (works with other forks)

### TAB version

4.1.4

### Plugin list

Essentials, FastAsyncWorldEdit (WorldEdit), ProtocolLib, TAB, ViaVersion, WorldGuard

### Describe the bug

When a player is in spectator mode, he cannot see the nametag of the player with the invisibility effect.
(This only happens when scoreboard-teams is enabled.)

### Expected behavior

Player in spectator mode must be able to see the player's nametag.

### Steps to reproduce

1) give the invisibility effect to a player
2) try looking at his nametag in spectator mode

### Additional info

This bug appeared on TAB 4.1.3, on 4.1.2 everything works correctly.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Do you have unlimited nametags enabled?

**Comment by Overwrite987** [comment]
> Do you have unlimited nametags enabled?

no

**Comment by NEZNAMY** [comment]
I tried with TAB's teams, vanilla teams, as well as no teams. In every single scenario an invisible player had invisible nametag. Why should the player's name tag be visible when player is invisible? This was a bug back in MC 1.8, but got fixed in 1.9. You probably didn't mean that one though.

**Comment by Overwrite987** [comment]
> I tried with TAB's teams, vanilla teams, as well as no teams. In every single scenario an invisible player had invisible nametag. Why should the player's name tag be visible when player is invisible? This was a bug back in MC 1.8, but got fixed in 1.9. You probably didn't mean that one though.

Well, actually, no, the point is that on older versions of TAB everything worked as it should, i mean - the player in spectator mode should be able to see the player's nametag one way or another, no matter if player has invisibility effect or not.

Demonstration:
https://drive.google.com/file/d/1aGo3MagSuc6cgvpspiIy-kj3O-mAM1ar/view?usp=sharing

**Comment by NEZNAMY** [comment]
My bad, forgot to go into spectator gamemode. I was partially right about the 1.8 bug compensation. It's the reason why I was making nametags invisible and in a new version I removed the check related to 1.8 players. Fixed it now.

**Comment by Overwrite987** [comment]
> My bad, forgot to go into spectator gamemode. I was partially right about the 1.8 bug compensation. It's the reason why I was making nametags invisible and in a new version I removed the check related to 1.8 players and didn't realize this can be a consequence. Fixed it now.

Fixed not, thanks for fast support 👍
