### ISSUE TITLE
Crashes with 1.20.6 even though it is listed under 1.20.6 version support in modrinth.

### ISSUE THREAD

**Issue by KdGaming0** [NEZNAMY/TAB#1288]
### Server version

1.20.6 fabric

### TAB version

4.1.4

### Plugin list

Don't have any plugins

### Describe the bug

When I install the mod on my fabric server it says that only the wrong version is present even though modrinth list it under 1.20.6 version.

### Expected behavior

The mod wil work on 1.20.6 when it is listed under 1.20.6 in modrinth.

![image](https://github.com/NEZNAMY/TAB/assets/97355992/fc983004-beb6-4be3-abbe-97cfcc62d53a)
will

### Steps to reproduce

Create a 1.20.6 fabric server and install the latest version from modrinth.

### Additional info

Most likely the mod has a must-have that version in the mod gradle, and that needs to be updated to 1.20.6 

_No response_

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
I didn't want to create a new release just for fabric 1.20.6, I didn't think anyone would switch to it this fast (no other platforms required any update compared to .5). You can add the version manually into fabric.mod.json file inside the plugin jar, or download latest build from [actions](https://github.com/NEZNAMY/TAB/actions).

**Comment by KdGaming0** [comment]
> I didn't want to create a new release just for fabric 1.20.6, I didn't think anyone would switch to it this fast (no other platforms required any update compared to .5). You can add the version manually into fabric.mod.json file inside the plugin jar, or download latest build from [actions](https://github.com/NEZNAMY/TAB/actions).

Okay, but you should remove the 1.20.6 from modrinth

**Comment by NEZNAMY** [comment]
I might. Though every single other platform works.
