### ISSUE TITLE
TAB BungeeCord placeholder BUG

### ISSUE THREAD

**Issue by 4zyy** [NEZNAMY/TAB#1289]
### Server version

Waterfall 1.20 #557

### TAB version

4.1.4

### Plugin list

AdvancedBan, BungeecordParyAndFriends, BungeeOnlineTime, ChatSentinal, CUstomF3Brand, DiscordSynthesis, FallBackServer, floodgate-bungee, Geyser-BungeeCord, GeyserUpdater, HideFriendJoinLeaveMessage, LuckPerms-Bungee, Maintenance, Plan, PremiumVanish, Protocolize-bungeecord, protocolize-legacy-bungeecord, SafeNET, ServerBrand, SimpleProxyChat, SimpleStaffChat, TAB

### Describe the bug

So when you first start the proxy server and you load in and switch from the Lobby Server to the Parkour Server, your rank suffix (from luckperms) looks like %luckperms_suffix%
![Screenshot 2024-05-18 144614](https://github.com/NEZNAMY/TAB/assets/167635937/fd96f4c6-d416-4e7f-960d-ae8e442a68d1)

### Expected behavior

However, its supposed to look like this whenever you are in Parkour
![Screenshot 2024-05-17 221631](https://github.com/NEZNAMY/TAB/assets/167635937/85c4d13e-1aad-4eb5-b968-c018cca1f893)

### Steps to reproduce

Restart the proxy and the first time you join the server you will notice this (enable global-playerlist)

### Additional info

I AM, using the TAB-Bridge plugin on the backend server. When you leave and rejoin the server, the issue is fixed.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by 4zyy** [comment]
Yes works thank you!
