### ISSUE TITLE
Add option to show playerlists based on server groups

### ISSUE THREAD

**Issue by apatuka** [NEZNAMY/TAB#129]
Greetings,

Going to add as Feature Requests on Github to track once is available.

On `per-server-settings:` add a boolean setting something like group-playerlist (true/false, default true if not defined). We can benefit from this feature for splitting a Survival server into multiple Survival Servers. 

Consider as a plus if can override the global-playerlist. 

Thank you so much.

**Comment by NEZNAMY** [comment]
So you want global-playerlist to share between some servers but not all of them, similar to per-world-playerlist on bukkit ?

**Comment by apatuka** [comment]
> 
> 
> So you want global-playerlist to share between some servers but not all of them, similar to per-world-playerlist on bukkit ?

Dear @NEZNAMY, that's right, same feature as per-world-playerlists but on this case is per-servergroup-playerlists.

Thank you very much for the quick response !

**Comment by NEZNAMY** [comment]
This has been requested a lot recently and will be added in next update.
