### ISSUE TITLE
[Unlimited Nametags] nametag remains at sneak position when no longer sneaking

### ISSUE THREAD

**Issue by NoriusCodes** [NEZNAMY/TAB#1290]
### Server version

purpur 1.20.4

### TAB version

4.1.4

### Plugin list

- BungeeGuard
- FAWE 1.9.1
- LuckPerms 5.4.120
- Multiverse-Core 4.3.12
- packetevents-spigot 2.2.1
- PlaceholderAPI 2.11.5
- TAB 4.4.1
- znpcs 4.6
- own plugin (has no influence on packets, just hooks into TAB)

### Describe the bug

When the player sneaks, sometimes the armorstand above his head remains in the sneak position and stays gray.
Here some pictures:
![2024-05-20_16 49 37](https://github.com/NEZNAMY/TAB/assets/138131075/f3db83d7-0db0-4b7b-8141-96e101c497cd)
![2024-05-20_16 49 43](https://github.com/NEZNAMY/TAB/assets/138131075/f4a61732-e679-4ae8-b726-7c3ae2a39834)

### Expected behavior

The nametag should remain over the player head and should not have the sneak effect.

### Steps to reproduce

sneak and move

### Additional info

Im running the server on purpur 1.20.4

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Unfortunately I have decided to remove this feature from the plugin after considering all pros and cons. Once MC 1.21 hits, I will make a bigger announcement, as well as planned removal date. For the time being, bug reports in this feature will no longer be accepted.

**Comment by NoriusCodes** [comment]
In my opinion it is one of the best features in the plugin. Why do you want to remove it? Yes, there are many disadvantages, but I believe that the advantages and the possible applications that it enables clearly predominate. 
You made this feature almost perfect. Your plugin is the only one with this feature and I think that is why it is so popular. 

**To the bug:**
Do you have any idea why this bug occurs and how it could be fixed? Could it be related to the version?

**Comment by NEZNAMY** [comment]
There are many bugs which I have no idea how to fix and most of the limits the game had were removed in recent versions, making the feature even less useful. It is also hard to maintain, since it's a lot of extra code, especially with entities, that needs to be maintained and updated. I have no idea how to fix this one either.

**Comment by NoriusCodes** [comment]
I understand your point. At a certain point, the complexity it brings is no longer worth it.

**Comment by NEZNAMY** [comment]
Unlimited nametag mode was marked for removal and no more bugs will be fixed. See https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c for more info.
