### ISSUE TITLE
Nametag

### ISSUE THREAD

**Issue by VataveLive** [NEZNAMY/TAB#1293]
### Server version

windspigot 1.8

### TAB version

1.1.4

### Plugin list

goBrush 1.8-1.12.jar
goBrush.zip
goPaint.jar
ItemStacker.jar
LuckPerms-S28140-511529.jar
MobDrops.jar
Multiverse-Core-2.5.jar
PlaceholderAPI-2.11.5.jar
PlotSquared-Bukkit-3.823.jar
SimpleClans (2).jar
SimpleScore-3.12.5.jar
Staff+.jar
TAB v4.1.4 (1).jar
Vault.jar
VoidGenerator.jar
VoxelSniper-5.171.0-SNAPSHOT.jar
worldedit-bukkit-6.1.7.2.jar
worldguard-6.1.jar

### Describe the bug

when i try to make a tagprefix for a luckperms group it doesnt chage the name to the right color

my Groups.yml

![Screenshot 2024-05-22 013540](https://github.com/NEZNAMY/TAB/assets/170479158/7dc0047c-f604-4aee-914a-9d449c7eeaad)
![Desktop Screenshot 2024 05 22 - 01 35 12 81](https://github.com/NEZNAMY/TAB/assets/170479158/6f981020-1331-485c-8fc1-3369ab398448)

### Expected behavior

should make the name to the color &7 (grey) and not &8 Darkgrey

### Steps to reproduce

config file

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#limitations

**Comment by VataveLive** [comment]
@Tanguygab my problem is because of the color after sr.mod it doesnt change

**Comment by NEZNAMY** [comment]
Yes, because the color code is cut off due to limit.
