### ISSUE TITLE
Disable condition does not work as it's expected on velocity

### ISSUE THREAD

**Issue by MatinHQ** [NEZNAMY/TAB#1295]
### Server version

velocity build #390

### TAB version

4.1.5

### Plugin list

Not required in this case

### Describe the bug

I have config below in my velocity  tab and I don't want my bedwars servers get formatted by velocity tab however it doesn't behave as it's expected it still tries to override my bedwars custom tab formating

when i set anti-override to false, it would work as it's expected as bedwars tab formatting would be able to override tablist name formating

```
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%server%=bedwars-1|%server%=bedwars-2'
```

### Expected behavior

It shouldn't handle tab format on disabled-condition as it's expected

### Steps to reproduce

1. Put tab jar in velocity
2. enable tab formating and make sure anti-override is also enabled
3. run a spigot server which have custom tab format (ex: bedwars)
4. in velocity tab format disable-condition add the server name so tab doesn't override the name tag

it doesn't work and tab still tries to override tab format on disable-condition server there is doc tape fix to disable anti-override

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
What build of the plugin are you using? I fixed something I accidentally broke previously in build 1130.

**Comment by MatinHQ** [comment]
Actually i already read your commits before opening this issue to see if it got fixed before I report that

and i am well aware of this [commit](https://github.com/NEZNAMY/TAB/commit/17e57f9d0ca4f9589ffb87349b1d1e01955813a1)also I updated to latest dev build again yesterday but issue still persist however I have to mention I didn't update tab on my backend servers can this be the issue?

**Comment by NEZNAMY** [comment]
Mixed installation is unsupported. Why would you use it?

**Comment by MatinHQ** [comment]
long story short, we have different luckperm database for some of game modes for example roleplay as it's have more than 100 groups and we handle name format there spigot side

**Comment by NEZNAMY** [comment]
So on bedwars you are using the plugin on backend for tablist formatting? And the issue is that the backend doesn't properly apply format on join?

**Comment by NEZNAMY** [comment]
Proxy configuration:
```
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%server%=lobby2'
```
```
_NEZNAMY_:
  tabprefix: '&6&lTAB &r'
  tagprefix: '&6&lTAB &r'
```

Backend configuration:
```
_NEZNAMY_:
  tabprefix: '&6&lBackend&r &a'
  tagprefix: '&6&lBackend&r &a'
```

When in `lobby`:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/9392f4d1-3b5f-4e4d-8167-e30524ab78bb)
After using `/server lobby2`:
![image](https://github.com/NEZNAMY/TAB/assets/6338394/fa04536a-a2af-474b-9133-c9f7e05cbe79)

**Comment by MatinHQ** [comment]
I will try with latest build once more and let you know do you have tab bridge also installed on backend or you are doing without it?

**Comment by xii69** [comment]
Also we've another problem about placeholders, when i try to put a placeholders in TAB Velocity on `groups.yml` or `config.yml` I get this error: https://paste.md-5.net/riverodafa.cs

**Comment by NEZNAMY** [comment]
Looks like you used a third party tool to dynamically reload the plugin at runtime. The class is obviously there.

**Comment by MatinHQ** [comment]
It's fixed in the latest version. Sorry for the inconvenience; we had to update the tab on the backend servers to fix the issue
