### ISSUE TITLE
Bossbar Problem

### ISSUE THREAD

**Issue by Syzntex** [NEZNAMY/TAB#1296]
### Server version

Paper 1.20.4

### TAB version

v4.1.4

### Stack trace

[log.txt](https://github.com/NEZNAMY/TAB/files/15431281/log.txt)

### Additional info

I have boss bar settings that I have set for each world using a special condition, but after teleporting between these worlds, the boss bar sometimes disappears and when I look at the console, it gives an error like in the log.txt file

bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    Event:
      style: PROGRESS
      color: "%animation:barcolors%"
      progress: "100"
      text: "%animation:ServerName%"
      display-condition: "%world%=world|%world%=spawn"
    Nether_ON:
      style: "NOTCHED_12"
      color: "YELLOW"
      progress: "100"
      text: "&f%luckperms_expiry_time_nether.teleport%"
      display-condition: "%world%=world_nether;%luckperms_has_permission_nether.teleport%=yes"
    Nether_OFF:
      style: "NOTCHED_20"
      color: "RED"
      progress: "100"
      text: "&fNo teleport to nether"
      display-condition: "%world%=world_nether;%luckperms_has_permission_nether.teleport%=no"

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Check for `errors.log` file in TAB's folder.

**Comment by Syzntex** [comment]
[log.txt](https://github.com/NEZNAMY/TAB/files/15431364/log.txt)

**Comment by NEZNAMY** [comment]
Can you update to latest build from actions? You didn't even fill the report correctly, it explicitly says to not use "latest" as version.

**Comment by Syzntex** [comment]
I'm sorry, I typed it in a hurry, saw the word "latest" and wrote it directly. I edited the version part as you said, I got this error with version v4.1.4

**Comment by NEZNAMY** [comment]
Then go hurry and test latest build from actions if it keeps happening there.

**Comment by NEZNAMY** [comment]
Why did you close the issue? What happened?

**Comment by Syzntex** [comment]
With version v4.1.5, the "latest" version, the problem seems to be solved, after a few teleport tests I got neither a disappearance boss-bar nor a console error, thank you for your help🙏. I just closed the issue, you know I'm in a hurry 😁
