### ISSUE TITLE
Order priority in 4.1.4

### ISSUE THREAD

**Issue by iLemon** [NEZNAMY/TAB#1297]
### Server version

Paper 1.20.4

### TAB version

4.1.4

### Plugin list

n/a

### Describe the bug

Ever since 1.20.5 released and at the same time we updated to 4.1.4 TAB, there has been a weird issue where 1 or a few players have incorrect order in the tab.

![CleanShot 2024-05-26 at 10 47 00@2x](https://github.com/NEZNAMY/TAB/assets/18317307/be3fbbb0-1ba1-4c21-ab88-93a50b90ee59)

```yml
  sorting-types:
  - PLACEHOLDER_HIGH_TO_LOW:%luckperms_meta_weight%
```

I ran %luckperms_meta_weight% for the first 3 players in the screenshot:
- iLemon: 800000
- qjesh: 30000
- Seotang: 60000

### Expected behavior

Player qjesh should be below the players with a weight of 60000

### Steps to reproduce

n/a

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Show output of `/tab debug <player not sorted correctly>`.

**Comment by iLemon** [comment]
> Show output of `/tab debug <player not sorted correctly>`.

![CleanShot 2024-05-26 at 10 53 28@2x](https://github.com/NEZNAMY/TAB/assets/18317307/f131ab10-5f67-43a6-b490-3ce4aeae8c85)

**Comment by NEZNAMY** [comment]
Can you also show someone who is below and should be above? Can you also send your config.yml?

**Comment by iLemon** [comment]
> Can you also show someone who is below and should be above? Can you also send your config.yml?

Above:
![CleanShot 2024-05-26 at 10 55 54@2x](https://github.com/NEZNAMY/TAB/assets/18317307/a02482fb-eb9d-4ef2-9465-cbd1540b21fb)
Below:
![CleanShot 2024-05-26 at 10 56 11@2x](https://github.com/NEZNAMY/TAB/assets/18317307/eccd1602-e34e-40d8-a55c-76cbc0cf505b)
Config: https://pastes.dev/AeK2hNpBqD

**Comment by NEZNAMY** [comment]
Does /tab reload fix it?

**Comment by iLemon** [comment]
> Does /tab reload fix it?

No

**Comment by NEZNAMY** [comment]
I'll give it a try and let you know.

**Comment by iLemon** [comment]
> I'll give it a try and let you know.

Appreciate it, thanks.

Here is a screenshot from another one of our servers:
![CleanShot 2024-05-26 at 11 00 08@2x](https://github.com/NEZNAMY/TAB/assets/18317307/f5b06fa9-dd3f-463b-b2fd-60f87c86f2eb)

The 'King' and 'Epic rank here all all above Supreme (supreme is the highest rank)

**Comment by NEZNAMY** [comment]
Try new build from actions (once it compiles).
