### ISSUE TITLE
playerlist objective 1.20.1

### ISSUE THREAD

**Issue by Nepenseken** [NEZNAMY/TAB#1299]
### Server version

paper 1.20.1

### TAB version

4.1.5

### Stack trace

[TAB Processing Thread/INFO]: [TAB] [WARN] Playerlist objective number is configured to show " ", but returned " " for player .Gamer_robru, which cannot be evaluated to a number.

### Steps to reproduce (if known)

update version of server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
No, updating server version does not forcibly change playerlist objective value to `" "`. You did that. If you don't want the feature, disable it.
