### ISSUE TITLE
It shouldn't show this suffix to nametag

### ISSUE THREAD

**Issue by zJar84** [NEZNAMY/TAB#13]
**Server version:** 1.13.2 (PaperSpigot)

**Plugin version:** 2.5.0

**Describe the bug:**
As we can see [here](https://i.imgur.com/cFHpx0J.png), the plugin add "Unknow translat" to the name tag of a player (It should be just ADMIN KCVault).

**Comment by NEZNAMY** [comment]
ProtocolSupport-related bug, fixed already, build available on discord.
