### ISSUE TITLE
When localizing scoreboard and /tab reload the plugin unloads with an error

### ISSUE THREAD

**Issue by vovmomyt** [NEZNAMY/TAB#1300]
### Server version

Paper 1.20.1

### TAB version

4.1.5

### Stack trace

04.06.2024 - 11:52:02 - [TAB v4.1.5] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
04.06.2024 - 11:52:02 - java.nio.charset.MalformedInputException: Input length = 1
04.06.2024 - 11:52:02 - 	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:279)
04.06.2024 - 11:52:02 - 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:405)
04.06.2024 - 11:52:02 - 	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
04.06.2024 - 11:52:02 - 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
04.06.2024 - 11:52:02 - 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
04.06.2024 - 11:52:02 - 	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
04.06.2024 - 11:52:02 - 	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
04.06.2024 - 11:52:02 - 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347)
04.06.2024 - 11:52:02 - 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436)
04.06.2024 - 11:52:02 - 	at java.base/java.nio.file.Files.readAllLines(Files.java:3395)
04.06.2024 - 11:52:02 - 	at java.base/java.nio.file.Files.readAllLines(Files.java:3433)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.shared.config.file.ConfigurationFile.detectHeader(ConfigurationFile.java:369)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.shared.config.file.ConfigurationFile.<init>(ConfigurationFile.java:54)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.shared.config.file.YamlConfigurationFile.<init>(YamlConfigurationFile.java:48)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.shared.config.Configs.<init>(Configs.java:31)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.shared.TAB.load(TAB.java:171)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:30)
04.06.2024 - 11:52:02 - 	at TAB.jar//me.neznamy.tab.platforms.bukkit.BukkitTabCommand.onCommand(BukkitTabCommand.java:25)
04.06.2024 - 11:52:02 - 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
04.06.2024 - 11:52:02 - 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
04.06.2024 - 11:52:02 - 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
04.06.2024 - 11:52:02 - 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
04.06.2024 - 11:52:02 - 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
04.06.2024 - 11:52:02 - 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
04.06.2024 - 11:52:02 - 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2354)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2314)
04.06.2024 - 11:52:02 - 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
04.06.2024 - 11:52:02 - 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.TickTask.run(TickTask.java:18)
04.06.2024 - 11:52:02 - 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
04.06.2024 - 11:52:02 - 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
04.06.2024 - 11:52:02 - 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
04.06.2024 - 11:52:02 - 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
04.06.2024 - 11:52:02 - 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
04.06.2024 - 11:52:02 - 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Steps to reproduce (if known)

1. Put
    main:
      title: "&9Time&bLapse &4Re&6loaded"
      lines:
        - "&7%date%"
        - "%animation:MyAnimation1%"
        - "&6В сети:"
        - "* &eВсего&7: &f%online%"
        - "* &eВ текущем мире&7: &f%worldonline%"
        - "* &eАдминистрация&7: &f%staffonline%"
        - ""
        - "&6Личная информация:"
        - "* &bРанг&7: &f%group%"
        - "* &bПинг&7: &f%ping%&8ms"
        - "* &bТекущий мир&7: &f%world%"
        - "%animation:MyAnimation1%"
in the config file in the scoreboards key, like this 
![изображение](https://github.com/NEZNAMY/TAB/assets/111626295/0d9bcc91-ecee-43c6-b852-923b35107cac)
3. Reload plugin by /tab reload in game
4. Gets error

### Additional info

I'm sorry, my English in bad
I'm tried to localize it to Russian

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This happens when you use a unicode symbol without saving the file in UTF-8 encoding. Are you sure this is not your case?

**Comment by vovmomyt** [comment]
Thank you! It's worked

**Comment by vovmomyt** [comment]
Btw, why it not UTF-8 by default?

**Comment by NEZNAMY** [comment]
It is.
