### ISSUE TITLE
Players are not in the sorting type list, and the type is none!

### ISSUE THREAD

**Issue by TNTChinaAAA** [NEZNAMY/TAB#1301]
### Server version

Paper 1.20.1

### TAB version

4.1.5

### Plugin list

BetterRTP, Chunky, Essentials, floodgate, Geyser-Spigot, Multiverse-Core, Multiverse-NetherPortals, Multiverse-SignPortals, PlaceholderAPI, ProtocolLib, SkinsRestorer, Slimefun, spark, TAB, ViaBackwards, ViaRewind, ViaVersion

### Describe the bug

[TAB] [WARN] Player TNT_ChinaSky's group (none) is not in sorting list! Sorting list: owner,admin,mod,helper,builder,vip,default. Player will be sorted on the bottom.
![QQ截图20240605153258](https://github.com/NEZNAMY/TAB/assets/40199850/ac60df92-b863-42ee-988e-ffe55ab9e6b9)
![QQ截图20240605153707](https://github.com/NEZNAMY/TAB/assets/40199850/77fac973-8042-4f41-88c5-323f493598df)

### Expected behavior

I hope new players' joining will automatically be classfied into the default group and won't appear this issue.

### Steps to reproduce

I just started a new server and drop the plugins into the "plugin" folder on Paper 1.20.1-196, which was running in offline mode.Then it appeared this issue, which woundn't appear **in the old version**.So is there some ways to address it?I try to add the group called "none" but it didn't work.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You don't have any permission plugin. Where do you expect the plugin to take groups from?

**Comment by NEZNAMY** [comment]
What happened? Why did you close the issue?

**Comment by TNTChinaAAA** [comment]
I got the ways you said to solve the problem, thank you so much.
