### ISSUE TITLE
cracked/offline server not showing player head icon in tab menu

### ISSUE THREAD

**Issue by tinkeringmatt** [NEZNAMY/TAB#1302]
### Server version

1.20.1

### TAB version

4.0.2

### Plugin list

ChunkLimiter, Craftmatic, DamageIndicator, Essentials, EssentialsChat, FarmControl, FullAnarchy, ItemsAdder, ItemsAdderPortals, libreforge, LibsDisguises, LoginRecipe, LoneLibs, LuckPerms, Multiverse-Core, OpenInv, PlaceholderAPI, ProtocolLib, ReNameTag, SafeStop, SkinsRestorer, SpoTchantment, TAB, ViaBackwards, ViaVersion, VoidGen, Votifier, VotingPlugin

### Describe the bug

When the server is set o online, mode  in the server.properties config, it shows the players head  icon in the tab menu.
But when using the  server as a cracked server, the tab menu  lacks the players heads.
This is in spite of the fact that we use skin restorer, meaning player skins are based on the premium skin associated with the  account (if one is available)

### Expected behavior

Expected/hoped that player names/nicknames would show the players head icon in the tab menu

### Steps to reproduce

Step 1) setup everything in with online set to true, ensure the player head icons show up in the tab menu
Step 2) change to online set to false and restart the server, check tab menu for player head icons

### Additional info

"" have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform *""

I read all I could find, and tried understanding it the best I could, however I could have missed something

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
* On which marketplace is 4.0.2 latest?
* Where does TAB say it allows cracked players to see heads in tablist?
* https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#8---how-to-make-player-heads-visible-in-tablist

**Comment by tinkeringmatt** [comment]
I  appologize, I  thought 4.0.2 was the latest, but I forgot I was on my test server.
Also I'm sorry I didn't see the cracked thing in the FAQ, I used control F to jump around articles looking for keywords, and dont know why that one didnt show up.

Thank you for your time
