### ISSUE TITLE
Repo for API is empty

### ISSUE THREAD

**Issue by Farmeurimmo** [NEZNAMY/TAB#1304]
### Server version

all versions

### TAB version

4.1.5

### Plugin list

TAB
My plugin using TabAPI

### Describe the bug

https://repo.kryptonmc.org/releases is down, I know I can directly use the jar.

### Expected behavior

Download the dependencies

### Steps to reproduce

Go to https://repo.kryptonmc.org/releases

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Farmeurimmo** [comment]
Hey, quick update.

The repo is on, but nothing has been pushed into it.

**Comment by NEZNAMY** [comment]
Moved over to jitpack:
```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependency>
	    <groupId>com.github.NEZNAMY</groupId>
	    <artifactId>TAB-API</artifactId>
	    <version>4.1.6</version>
	</dependency>
```
Updated wiki as well.
