### ISSUE TITLE
[Velocity] Sorting doesnt work

### ISSUE THREAD

**Issue by ammodev** [NEZNAMY/TAB#1306]
### Server version

Velocity 1.20.4

### TAB version

4.1.4, 4.1.5 doesnt work either

### Plugin list

Plugins: commandapi, commandwhitelist, luckperms, forceresourcepacks, oneversionremake, packetevents, premiumvanish, signedvelocity, surf-api-velocity, surf-data-velocity, surf-notify-velocity, surf-proxy-velocity, surf-punish, surf-server-selector-velocity, tab, velocitywhitelist

### Describe the bug

The players will randomly get unsorted after a while.

### Expected behavior

The players should be sorted

### Steps to reproduce

Have many players on your server? It's honestly hard to tell when it breaks.

### Additional info

Doesnt work either with no other plugins but tab installed. 

https://github.com/NEZNAMY/TAB/issues/986 - you closed our issue earlier saying that velocity is not officially supported. Now that it is, we are trying to get this fixed again.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Do you have bridge installed?

**Comment by ammodev** [comment]
Yes.

**Comment by NEZNAMY** [comment]
Your steps to reproduce are insufficient. Does /btab reload fix it? What does `/btab debug <player>` show for you / unsorted players before and after reload?

**Comment by ammodev** [comment]
I know my steps are insufficient. Thats why I wrote that we dont really know either when it breaks. It works with less players, but once you get to like 100-200 players it breaks completely. 

/btab reload doesnt fix it. 

debug information is the same, in sorted state and when it breaks

![debug info](https://github.com/NEZNAMY/TAB/assets/32338899/b598e2b5-9dd2-46e8-ba11-dbb44f75a1e9)

**Comment by NEZNAMY** [comment]
You should add at least sorting by player name as well. Sorting only by group and nothing else is attempting to sort multiple palyers into the same slot, which is not supported.

**Comment by NEZNAMY** [comment]
There is a detection of attempts to duplicate team names, which is what the last character is reserved for. However, people have reported issues with it regardless. I'll either need more clear steps or just add player name sorting.

**Comment by NEZNAMY** [comment]
@ammodev did you add sorting by player name too? Did that fix it?

**Comment by ammodev** [comment]
It works with 5 players, like it did most of the time. Our next event is on the 24th. I can tell you if it works with many players once the event starts.

**Comment by ammodev** [comment]
Fixed with adding name sorting
