### ISSUE TITLE
Sorting by placeholder is not working if there any spacebar symbols inside it

### ISSUE THREAD

**Issue by qvazzar** [NEZNAMY/TAB#1308]
### Server version

Paper 1.20.4

### TAB version

4.14

### Plugin list

TAB
Essentials
and some others. I don't think plugin list is required there

### Describe the bug

Sorting by placeholder is not working if there any spacebar symbols inside it. Before the update to version 4.1.4 it was working.

We have multiple types of sorting, one of them is 
```
sorting-types:
  - "PLACEHOLDER:%essentials_afk%:, &7⌛"
```

It was working perfectly until recent update, now it tells console this warn: `[TAB] [WARN] Sorting placeholder %essentials_afk% with pre-defined values [,⌛] returned " ⌛" for player qvazzarius, which is not defined. Player will be sorted on the bottom`

Also we have placeholder output replacement for AFK status:

```
placeholder-output-replacements:
  '%essentials_afk%':
    'yes': ' &7⌛'
    'no': ''
    '%essentials_afk%': ''
```

### Expected behavior

Before the update the plugin did not spam this error to the console.

### Steps to reproduce

Step 1: Install TAB and Essentials
Step 2: Make placeholder-output-replacement for essentials's afk status
Step 3: Try to make placeholder sorting with it

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Looks like the issue is in space trimming while loading the list, but not when finding the element. Could it be that anything with a space is broken, not just special symbols?

**Comment by qvazzar** [comment]
I'm not sure. I use the regular space character, no special characters. Tried non-breaking space, still gives this warn. For me it looks like your plugin is simply removing all the space symbols on the list.
