### ISSUE TITLE
'[???]' displaying at the end of every slot in layout mode

### ISSUE THREAD

**Issue by Juras99** [NEZNAMY/TAB#1309]
### Server version

Paper 1.20.6

### TAB version

4.1.5 and 4.1.6-SNAPSHOT

### Plugin list

![image](https://github.com/NEZNAMY/TAB/assets/81112166/102fc9a7-c9ea-4d8f-820f-c7f1e0c5108f)

### Describe the bug

When using layout mode, '[???]' id displayed at the end of every single TAB slot, even empty ones.

![2024-06-11_16 06 24](https://github.com/NEZNAMY/TAB/assets/81112166/6a2c18b9-4d66-4033-83ab-413bb254b947)

### Expected behavior

The slots should be empty, just like they were on older versions of the plugin.

### Steps to reproduce

Just open TAB.

### Additional info

I'm using a completely clear config. The issue did not exist on plugin version 4.0.7 that I was using previously.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
This looks like it's added by a custom client. Are you absolutely 100% sure you are usimg vanilla client?
