### ISSUE TITLE
Essentials Nickname with BungeeCord & Bukkit Bridge

### ISSUE THREAD

**Issue by PixelTV** [NEZNAMY/TAB#131]
I'd like to display the Essentials Nickname of the user. I'm using the plugin on BungeeCord and on Spigot, set up as Bridge. It's a Placeholder from PlaceholderAPI and I've seen Chat-Plugins with same (BungeeCord and Bukkit Bridge).
What would be cool either, not just supporting LuckPerms in config.yml --> Groups, just all the Vault Plugins (or just CloudNet v2 Permissions).

**Comment by NEZNAMY** [comment]
If you want to use essentials nickname use a placeholderapi placeholder like %essentials_nickname%. For permission plugins, Vault hook is present on bukkit version and on bungeecord all popular permission plugins are supported directly (as Vault doesn't have bungee version).

**Comment by PixelTV** [comment]
Hey thanks, but how can I make TAB use the nickname, not the normal playername? I see this Option just in config.yml on Spigot Server which is in Bridge Mode. So about Vault: It works, but setting group Prefix per Group in TAB Config, doesn‘t work.

**Comment by NEZNAMY** [comment]
As i said, use %essentials_nickname%. Prefixes for groups work too. This is a core feature and if it didn't work, everyone would report it, not just you.

**Comment by PixelTV** [comment]
Hey, thanks, but where to enter %essentials_nickname%? I see no possibility in BungeeCord TAB Config.

**Comment by NEZNAMY** [comment]
As customtabname of groups that should use it.

**Comment by PixelTV** [comment]
Well CloudNet has an API which works on BungeeCord too. I just can't code with BungeeCord.

**Comment by PixelTV** [comment]
Could you may add support for CloudNet? That would be real amazing.

**Comment by NEZNAMY** [comment]
I have no idea what it is and how to add support.

**Comment by PixelTV** [comment]
It is a Cloud-System with an integrated Permissions-System. It also has a documentation and is available on Github.
https://github.com/CloudNetService/CloudNet
https://cloudnetservice.eu/cloudnet/docs/v2.1.17/

**Comment by NEZNAMY** [comment]
Send me it's bungeecord jar and API method to hook into it.

**Comment by PixelTV** [comment]
And where should I send you the Jar? However, that's the download Link: https://ci.cloudnetservice.eu/job/CloudNetService/job/CloudNet/job/master/lastSuccessfulBuild/artifact/cloudnet-api/cloudnet-api-bridge/target/CloudNetAPI.jar
I guess, here https://cloudnetservice.eu/cloudnet/docs/v2.1.17/ you're searching for Class: "PermissionModule".

**Comment by PixelTV** [comment]
Is that enough or do you need more information? I could test plugin then if it works (as I'm using this System obviously).

**Comment by NEZNAMY** [comment]
I will let you know when i try it.

**Comment by NEZNAMY** [comment]
This looks like a bungee fork or something, i don't know how would i possibly add support for it's permission system.

**Comment by A248** [comment]
Why wouldn't CloudNet just override the BungeeCord API's Player#hasPermission? Ideally it would interoperate with existing permission checks seamlessly.

**Comment by NEZNAMY** [comment]
The plugin already checks for permission groups defined in bungeecord config.yml if no permission plugin is installed.

**Comment by Tanguygab** [comment]
in the meantime, you could just set `customtabname: "%essentials_nickname%"` to the `_OTHER_` group
