### ISSUE TITLE
Heart colors changing with team color

### ISSUE THREAD

**Issue by Dylouwu** [NEZNAMY/TAB#1311]
### Server version

spigot-1.8.8-R0.1-SNAPSHOT-latest

### TAB version

4.1.5

### Plugin list

CmdSigns
LuckPerms
WorldTeleporter
TAB
HologramAPI
FateUHC
Skoice
Duels

### Describe the bug

The color of the hearts matches the ones of the team for no reason.

### Expected behavior

Heart color should not change. This is probably due to a conflict in my plugins though :(

### Steps to reproduce

- Step 1 : create a team with the scoreboard commands
- Step 2 : add hearts as an objective and add the display to the TAB

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/118902463/d3327061-3ab7-4fac-af44-5478d69f05ae)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Dylouwu** [comment]
tried playing on a vanilla 1.8.9 client, still had the issue, it's nothing much though i'll prob close the issue since it is on my side

**Comment by NEZNAMY** [comment]
This is not a bug. Hearts might be copying a color from your tablist format, which is a client-sided mechanic. The objective itself does not have configurable color or anything, so TAB cannot be putting a bad value there.

**Comment by Dylouwu** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/118902463/16f93cd8-8310-4350-b5ea-80c11da4e2c7)

stumbled upon that, this looks like a common bug, thanks and sorry cause this has nothing to do with you :) !
