### ISSUE TITLE
Using just a minimessage color as a prefix won't display it

### ISSUE THREAD

**Issue by Folas1337** [NEZNAMY/TAB#1312]
### Server version

paper 1.20.4 build 497

### TAB version

4.1.6

### Plugin list

[22:24:06 INFO]: Server Plugins (2):
[22:24:06 INFO]: Bukkit Plugins:
[22:24:06 INFO]:  - LuckPerms, TAB

### Describe the bug

I'm trying to switch from unlimited nametag mode to playerlist-objective but have come across a problem that I don't seem to be able to fix.

If you leave the all the configurations at the default and install LuckPerms to set your prefix and you then set your prefix by a command like '/lp group default meta setprefix "<green>"' then '/papi parse me %vault_prefix%' shows the string "<green>" but unfortunately the name above my head does not change at all. *I have later uninstalled PAPI to make sure it's not the cause which is why it's not listed above.*

Funnily it does work if I change the following line in groups.yml:
```diff
_DEFAULT_:
-  tagprefix: "%luckperms-prefix%"
+  tagprefix: "%luckperms-prefix%a" 
```

So the moment the tagprefix does not end in just a minimessage color, it works fine.

### Expected behavior

The names above player should be shown in the color that's been provided through the prefix.

### Steps to reproduce

Step 1: Install both LuckPerms and TAB
Step 2: Use '/lp group default meta setprefix "<green>"'
Step 3: Notice how the name colors above players won't change
Step 4: Go into groups.yml and add an "a" after %luckperms-prefix% and notice how the name now changes (but also has an "a" in front of it, obviously.

### Additional info

This does not appear to be happening when using legacy code such as &a.
So if I'm typing '/lp group default meta setprefix "&a"' it changes color just fine.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
The issue here is that MM truncates colors at the end which it finds "redundant", not knowing TAB actually uses that seemigly redundant color code to determine team color. There is no way in MM to disable this "optimization". The workaround a customer who reported this issue first used was switching the order of color and space, so instead of `Text <red>` use `Text<red> `, which should work.

**Comment by Folas1337** [comment]
But I only want to change the color of the name, nothing else. There is no extra text that I am displaying or want to display at all :(

And why the hell does MM do this, that's ridiculous and besides the point of what it should do, good God.
Where do I even report something like this to MM if I'm disliking it? 😕

**Comment by NEZNAMY** [comment]
> There is no extra text that I am displaying or want to display at all :(
Technical detail. You defined a color code and nothing after it, which is technically redundant, because nothing is colored.

I don't have any information regarding reporting issues on MM, you'll need to find out yourself.

**Comment by Folas1337** [comment]
> Technical detail. You defined a color code and nothing after it, which is technically redundant, because nothing is colored.

But then I can't use it properly in something like a prefix.

I shouldn't let this out on you but MM instead, sorry, I shall figure out where to report it. Until then I probably can't switch or have to find another way to use legacy code just for the name tag... I mean legacy code also didn't do this and allows for me to do exactly what I want which is having a prefix just be &a... I fear they didn't properly think MiniMessages through if this is the truth but perhaps they just have to be made aware which I'll do right about now :)

**Comment by Folas1337** [comment]
Also that means I will close this ticket as it is not your fault, sorry for bothering you.

**Comment by NEZNAMY** [comment]
The reason why legacy codes work is because they have nothing to do with MM. TAB processes them internally, not removing any.

**Comment by Folas1337** [comment]
Hold on... why does it seems to work in the tab list then?
Cause I also just color names there and that seems to work fine o.O

**Comment by NEZNAMY** [comment]
Because tablist display names are a single component. It is only split in TAB configuration into prefix, name and suffix for convenience.

**Comment by Folas1337** [comment]
Alright, makes sense, thanks!

**Comment by NEZNAMY** [comment]
I could add a workaround by adding a dummy character at the end before sending it to MM and then removing it after.

**Comment by Folas1337** [comment]
The hell does this answer mean?!
https://github.com/KyoriPowered/adventure/issues/1085

Is that something you'd have to do or I have to do? o.O

**Comment by NEZNAMY** [comment]
I would, though I have no idea how.

**Comment by kezz** [comment]
> The hell does this answer mean?! [KyoriPowered/adventure#1085](https://github.com/KyoriPowered/adventure/issues/1085)

It means you should concatenate MiniMessage strings (e.g. `"<green>" + "<name>"`) or use a larger "format" string with [parsed placeholders](https://docs.advntr.dev/minimessage/api.html) (e.g. `<prefix><username>`).

If you are having issues you're more than welcome to drop into our Discord and ask some questions.

**Comment by NEZNAMY** [comment]
This won't solve the color compacting issue. The text in question is for example `<green>`, which MM translates to an empty string.

**Comment by Folas1337** [comment]
I will reopen this as currently it seems TAB has to fix this and not MM.

**Comment by Folas1337** [comment]
FYI, I was able to confirm with the last v5 build that just using "<green>" as a prefix is now working. I thank you very much and wish you a good time o/
