### ISSUE TITLE
TabList#updateGameMode() does not work with 'scoreboard-teams' enabled.

### ISSUE THREAD

**Issue by Latestion** [NEZNAMY/TAB#1315]
### TAB version

4.1.5

### Software causing compatibility issue

As the title says, I was using that method to _false_ change players gamemode, it worked when 'scoreboard-teams' was disabled.

We had to enabled 'scoreboard-team' as it would not format LuckPerms nametag otherwise. Now that its enabled, the method does not work. 

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Latestion** [comment]
I think I added this under a wrong label, really sorry!

**Comment by NEZNAMY** [comment]
This doesn't make any sense. Teams don't touch tablist at all. Did you enable `prevent-spectator-effect` in config by accident instead?

**Comment by Latestion** [comment]
`# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ''
  - ''
  - '  &#929292▸&#959390&m &#98948E&m &#9A958C&m &#9D968A&m &#A09688&m &#A39786&m
    &#A69883&m &#A89981&m &#AB9A7F&m &#AE9B7D&m &#B19C7B&m &#B49D79&m &#B69E77&m &#B99F75&m
    &#BC9F73&m &#BFA071&m &#C2A16F&m &#C4A26D&m &#C7A36B&m &#CAA468&m &#CDA566&m &#CFA664&m
    &#D2A762&m &#D5A860&m &#D8A85E&m &#DBA95C&m &#DDAA5A&m &#E0AB58&m &#E3AC56&m &#E6AD54&m
    &#E9AE52&m &#EBAF50&m &#EEB04D&m &#F1B14B&m &#F4B149&m &#F7B247&m &#F9B345&m &#FCB443&m
    &#FFB541◂&r                               &#FFB541▸&#FCB443&m &#F9B345&m &#F7B247&m
    &#F4B149&m &#F1B14B&m &#EEB04D&m &#EBAF50&m &#E9AE52&m &#E6AD54&m &#E3AC56&m &#E0AB58&m
    &#DDAA5A&m &#DBA95C&m &#D8A85E&m &#D5A860&m &#D2A762&m &#CFA664&m &#CDA566&m &#CAA468&m
    &#C7A36B&m &#C4A26D&m &#C2A16F&m &#BFA071&m &#BC9F73&m &#B99F75&m &#B69E77&m &#B49D79&m
    &#B19C7B&m &#AE9B7D&m &#AB9A7F&m &#A89981&m &#A69883&m &#A39786&m &#A09688&m &#9D968A&m
    &#9A958C&m &#98948E&m &#959390&m &#929292◂&r  '
  - '&f%img_xenos%'
  - ''
  - ''
  - '&7ᴏɴʟɪɴᴇ: #FFB800%online%                   &7ᴡᴇʟᴄᴏᴍᴇ ᴛᴏ ᴛʜᴇ &#FFB541&lᴡ&#F4B249&lᴏ&#E9AE51&lʀ&#DEAB59&lʟ&#D3A761&lᴅ&#C9A46A&l''&#BEA072&lꜱ
    &#B39D7A&lʙ&#A89982&lᴇ&#9D968A&lꜱ&#929292&lᴛ &7ᴍɪɴᴇᴄʀᴀꜰᴛ ꜱᴇʀᴠᴇʀ!                   &7ᴘɪɴɢ:
    #FD3D00%player_ping%'
  - ''
  footer:
  - ''
  - ''
  - '&e★ &7ʀᴀɴᴋꜱ, ᴄᴏꜱᴍᴇᴛɪᴄꜱ ᴀɴᴅ ᴍᴏʀᴇ: #FFB800sᴛᴏʀᴇ.xᴇɴᴏsᴍᴄ.ɴᴇᴛ &e★'
  - '&c🔥 &7ᴊᴏɪɴ ᴏᴜʀ ᴅɪꜱᴄᴏʀᴅ ꜱᴇʀᴠᴇʀ: #fd3d00ᴅɪsᴄᴏʀᴅ.ɢɢ/xᴇɴᴏsᴍᴄ &c🔥'
  - ''
  - '&#929292▸&#96938F&m &#99948D&m &#9D968A&m &#A19787&m &#A49885&m &#A89982&m &#AB9A7F&m
    &#AF9B7C&m &#B39D7A&m &#B69E77&m &#BA9F74&m &#BEA072&m &#C1A16F&m &#C5A26C&m &#C9A46A&m
    &#CCA567&m &#D0A664&m &#D3A761&m &#D7A85F&m &#DBA95C&m &#DEAB59&m &#E2AC57&m &#E6AD54&m
    &#E9AE51&m &#EDAF4F&m &#F0B04C&m &#F4B249&m &#F8B346&m &#FBB444&m &#FFB541&m &#FBB444&m
    &#F8B346&m &#F4B249&m &#F0B04C&m &#EDAF4F&m &#E9AE51&m &#E6AD54&m &#E2AC57&m &#DEAB59&m
    &#DBA95C&m &#D7A85F&m &#D3A761&m &#D0A664&m &#CCA567&m &#C9A46A&m &#C5A26C&m &#C1A16F&m
    &#BEA072&m &#BA9F74&m &#B69E77&m &#B39D7A&m &#AF9B7C&m &#AB9A7F&m &#A89982&m &#A49885&m
    &#A19787&m &#9D968A&m &#99948D&m &#96938F&m &#929292◂&r'
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=Paradise'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,developer,manager,admin,mod,helper,media,engineer,prototype,mecha,cypher,scrappy,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: true
  disable-condition: '%world%=disabledworld'
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-condition: '%world%=disabledworld'
  fancy-display-default: NPC
  fancy-display-players: '&c%health%'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: BLUE
      progress: '100'
      text: '%animation:servername%'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    default:
      title: '&#929292▸&#A09688&m &#AD9B7E&m &#BB9F74&m &#C9A46A&m &#D6A85F&m &#E4AC55&m
        &#F1B14B&m &#FFB541◂&r #ffb800&lxᴇɴᴏs&7&lᴍᴄ &#FFB541▸&#F1B14B&m &#E4AC55&m
        &#D6A85F&m &#C9A46A&m &#BB9F74&m &#AD9B7E&m &#A09688&m &#929292◂'
      lines:
      - ''
      - '#ffb800&l| #ffb800ᴘʀᴏꜰɪʟᴇ'
      - '&f&l| &7ɴᴀᴍᴇ: &f%player_name%'
      - '&f&l| &7ʀᴀɴᴋ: &f%vault_prefix%'
      - ''
      - '#ffb800&l| #ffb800sᴛᴀᴛs'
      - '&f&l|%img_money% &7ʙᴀʟᴀɴᴄᴇ: &f%vault_eco_balance_formatted%'
      - '&f&l|%img_mc_prismarine_shard% &7ѕʜᴀʀᴅѕ: &f%shards_bal%'
      - '&f&l|%img_credits% &7ᴄʀᴇᴅɪᴛѕ: &a%rivalcredits_balance_decimal%'
      - '&f&l|%img_voltage% &7ʟᴇᴠᴇʟ: &b%level_bal%'
      - '&f&l|%img_shards% &7ʙᴀᴄᴋᴘᴀᴄᴋ: &a%backpack_full%%'
      - '&f&l|%img_mining% &7ᴘɪᴄᴋᴀxᴇ ᴘᴇʀᴄᴇɴᴛ: &a%pickaxe_energy%%'
      - ''
      - '%levelsb% &7(&b%level_percent_to_next_level%%&7)'
      - '     #ffb800ᴘʟᴀʏ.xᴇɴᴏsᴍᴄ.ɴᴇᴛ'
layout:
  enabled: true
  direction: COLUMNS
  default-skin: mineskin:383747683
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - 2|🏹 &#FFB541&lᴘ&#EDAF4F&lʀ&#DBA95C&lᴏ&#C9A46A&lꜰ&#B69E77&lɪ&#A49885&lʟ&#929292&lᴇ
      - '3|└ %img_name% #FFB800ɴᴀᴍᴇ: &f%player_name%'
      - '4|└ %img_player% #FFB800ᴋɪʟʟꜱ: &f%statistic_player_kills%'
      - '5|└ %img_deaths% #FFB800ᴅᴇᴀᴛʜꜱ: &f%statistic_deaths%'
      - '6|└ %img_gang% #FFB800ᴏɴʟɪɴᴇ ᴛɪᴍᴇ: &f%statistic_time_played:days%d %statistic_time_played:hours%h'
      - 8|➹ &#FFB541&lꜱ&#E4AC55&lᴛ&#C9A46A&lᴀ&#AD9B7E&lᴛ&#929292&lꜱ
      - '9|└  #FFB800ʙᴀʟᴀɴᴄᴇ: &f%vault_eco_balance_formatted%'
      - '10|└ %img_shards% #FFB800ѕʜᴀʀᴅѕ: &f%shards_bal%'
      - '11|└ %img_credits% #FFB800ᴄʀᴇᴅɪᴛѕ: &a%rivalcredits_balance_decimal%'
      - '12|└ %img_mining% #FFB800ʟᴇᴠᴇʟ: &b%level_bal%'
      - 22|⛏ &#FFB541&lᴘ&#EDAF4F&lʟ&#DBA95C&lᴀ&#C9A46A&lʏ&#B69E77&lᴇ&#A49885&lʀ&#929292&lꜱ
      - 14|🔥 &#FFB541&lꜱ&#EDAF4F&lᴏ&#DBA95C&lᴄ&#C9A46A&lɪ&#B69E77&lᴀ&#A49885&lʟ&#929292&lꜱ
      - '15|└ #FFB800ᴅɪsᴄᴏʀᴅ.ɢɢ/xᴇɴᴏsᴍᴄ'
      - 17|☂ &#FFB541&lᴇ&#E9AE51&lᴠ&#D3A761&lᴇ&#BEA072&lɴ&#A89982&lᴛ&#929292&lꜱ
      groups:
        players:
          slots:
          - 24-80
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
playerlist-objective:
  enabled: false
  value: '%ping%'
  disable-condition: '%world%=disabledworld'
  fancy-value: '&7Ping: %ping%'
ping-spoof:
  enabled: false
`

TAB.getInstance().getPlayer(this.player.getUniqueId()).getTabList().updateGameMode(p.getUniqueId(), 3);

**Comment by NEZNAMY** [comment]
I cannot copypaste that. Also you are not using the API. Support for internals is not provided.

**Comment by Latestion** [comment]
[Here](https://paste.ofcode.org/kGeFy4LLDnedajzFdzHF7f)

Oh, I didnt know that NEZNAMY. Ill shift over to the API in the meantime

**Comment by NEZNAMY** [comment]
I literally asked you if this could be an "issue" with layout. You have it enabled. Of course the fake player entries won't have spectator effect. Other than that, I could see my hand disappearing in game like in spectator gamemode when running the code.

**Comment by Latestion** [comment]
My bad man, didnt know what Layout was. Also, I am not working with fake players. Thanks for the help.

**Comment by NEZNAMY** [comment]
Layout uses fake players. Real players are pushed out of tablist, so changing anything on them won't make a difference. I don't know what were you trying to achieve. Even if it "worked", spectators would be on the bottom and the entire layout would be shifted, including fixed slots, which you most likely don't even want.

**Comment by Latestion** [comment]
I just want the spectator head effect on real players.
![image](https://github.com/NEZNAMY/TAB/assets/51133083/01b4d649-2396-4961-97b1-a91baf19f477)

**Comment by NEZNAMY** [comment]
And is that not working with layout? Or teams? Does it work if you use vanilla teams instead?

**Comment by Latestion** [comment]
It works fine when the scoreboard-teams is disbaled. I haven't tested it with normal teams. Layout was always enabled when it worked.

**Comment by NEZNAMY** [comment]
Then try vanilla teams.

**Comment by Latestion** [comment]
Works with normal Vanilla Teams! ( added players in a team called ghost, and disabled scoreboard-teams )

**Comment by NEZNAMY** [comment]
Now put them into different teams, not the same team.

**Comment by Latestion** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/51133083/388b9636-7754-4c40-a01c-6e748d35a485)
On different teams. ( We do have to be in the same teams anyway because I want to use the bukkit teams transparent effect too )

**Comment by NEZNAMY** [comment]
And is that head not appearing when using TAB's teams?

**Comment by Latestion** [comment]
I found out the issue. Big XY problem. Thanks for helping me out here.
The real problem is enabling scoreboard-teams, broke my code where my player goes transparent (every player is added to a team called ghost)

Is there a config fix for this?

**Comment by NEZNAMY** [comment]
Fix what? How do you want a player to be in 2 teams at the same time? You need to decide which plugin should manage teams.

**Comment by Latestion** [comment]
If we disable Scoreboard-teams in tab, the LuckPerms Prefix stop being formatted. Soo cant really decide on what to do.

**Comment by NEZNAMY** [comment]
You need to pick one team plugin and configure it. There is nothing I can "fix" here based on provided information.
