### ISSUE TITLE
Wrong/misunderstood player sorting

### ISSUE THREAD

**Issue by RealKomander** [NEZNAMY/TAB#1319]
### Server version

purpur 1.20.4

### TAB version

4.1.6

### Plugin list

<img width="573" alt="image" src="https://github.com/NEZNAMY/TAB/assets/124439290/809b0feb-00a4-4ed1-b90c-88fcdd074c80">

### Describe the bug

Config:
sorting-types:
  - "PLACEHOLDER_A_TO_Z:%rel_dctab_sort%"

/papi parserel RealKomander MechaVibe_MkVII %rel_dctab_sort%
returns: b

/papi parserel RealKomander RealKomander %rel_dctab_sort%
returns: a

/papi parserel RealKomander Zmeika_ %rel_dctab_sort%
returns: a

Tab:
<img width="294" alt="image" src="https://github.com/NEZNAMY/TAB/assets/124439290/fba85bd9-ee48-4f5e-884f-11b7fe766920">

### Expected behavior

RealKomander and Zmeika_ on top, MechaVibe_MkVII below them

### Steps to reproduce

I hope this can be sorted out without reproduction, maybe I just don't understand how PAPI works in playerlists

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by RealKomander** [comment]
Does that mean that it's impossible to sort the list differently for different players?

**Comment by NEZNAMY** [comment]
Correct.
