### ISSUE TITLE
Wrong gradle and kotlin package

### ISSUE THREAD

**Issue by Farmeurimmo** [NEZNAMY/TAB#1320]
### Page link

https://github.com/NEZNAMY/TAB/wiki/Developer-API

### Current text (if applicable)

Currently maven is the only one with working API dependency in copy paste.

![image](https://github.com/NEZNAMY/TAB/assets/71896330/6048d260-ac6a-47f0-a627-440716981d24)

### New text

Should use maven options but translated correctly to gradle because package is wrong and repo url too for kotlin.

![image](https://github.com/NEZNAMY/TAB/assets/71896330/60fb8964-8f9c-445b-8124-4ab80f6ab3d8)

**Comment by Farmeurimmo** [comment]
For gradle:

`
maven {
        url 'https://jitpack.io'
}

compileOnly 'com.github.NEZNAMY:TAB-API:4.1.6'
`

**Comment by NEZNAMY** [comment]
Fixed, thanks.
