### ISSUE TITLE
Apply the fix that was installed in limbo plugins

### ISSUE THREAD

**Issue by listtw** [NEZNAMY/TAB#1321]
### Server version

Purpur 1.21

### TAB version

4.16

### Plugin list

Tab 4.16
BTab  5.06
Limbo API 1.1.24
Limbo auth 1.1.14
Limbo filter 1.1.18

### Describe the bug

The error occurs when the player becomes licensed using limbo auth

### Expected behavior

Correctly display your nickname in the tab

### Steps to reproduce

I have already described in another problem

### Additional info

Here is the link with the applied fix - https://github.com/UserNugget/TAB
My problem -  https://github.com/NEZNAMY/TAB/issues/1285
![image](https://github.com/NEZNAMY/TAB/assets/169247769/35c8bb49-ed5c-4cc0-9ee5-b747215a0946)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Your code will only rewrite UUID of the player viewing tablist, nobody else. Isn't it supposed to rewrite that UUID for everyone to see?

**Comment by UserNugget** [comment]
I think its better to fix this issue on LimboAPI/Velocity side as fixing it here seems a bit inappropriate.
Will try to implement that fix in LimboAPI soon™

**Comment by UserNugget** [comment]
@listtw, can you try to reproduce this issue with the latest LimboAPI [devbuild](https://modrinth.com/plugin/limboapi/version/ca691d8)?

**Comment by listtw** [comment]
I downloaded dev limbo apk, tomorrow I will be able to say for sure whether it helped or not. Thank you for your time
Спасибо!!!!!!!!!!!!!!!

**Comment by listtw** [comment]
It works, thanks
