### ISSUE TITLE
Feature Request - Layout Support RedisBungee

### ISSUE THREAD

**Issue by MacTh3Mac** [NEZNAMY/TAB#1325]
### Server version

Velocity 3 - w/redisbungee

### TAB version

4.1.6

### Plugin list

NA

### Describe the bug

Multi Proxy is used as a resiliency and redundancy feature. Meaning that with multiple proxies online should one fail or have an issue, connectivity is unaffected.  

### Expected behavior

Your wiki states its an unsupported feature as redis is only used by large networks, and thats why you chose not to support layout across multiple proxies.

However as a network with approx 200-400 players we find the tab customisation and versatility in TAB a perfect replacement for our old solution of BTLP (used on waterfall prior) allowing different tab lists on hubs to game servers etc.

However this feature is completely unavailable when using multi proxies.

We did attempt to use globaltablists, but found that the sorting and luck perms prefixes etc didn't show to players connected on different proxies to the viewer.

Feature requested: Add Redisbungee support for the layout feature and ensure that the players meta display across all connected proxies.   

Thanks

### Steps to reproduce

NA

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
* [Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).
* [RedisBungee page](https://github.com/NEZNAMY/TAB/wiki/Feature-info:-RedisBungee-support) says it would require massive changes and isn't worth it.
* `We did attempt to use globaltablists, but found that the sorting and luck perms prefixes etc didn't show to players connected on different proxies to the viewer.` Sounds like a bug, try latest build from actions and if it persists, open a bug report.
