### ISSUE TITLE
Feature Request - Excluded Servers

### ISSUE THREAD

**Issue by MacTh3Mac** [NEZNAMY/TAB#1326]
### Server version

Velocity 3

### TAB version

4.1.6

### Plugin list

NA

### Describe the bug

Feature Requested:

Config option to display back end servers own (bukkit) tab list on specific servers bypassing the TAB list supplied by the proxy.

### Expected behavior

When server is listed in config section

```
#servers listed in the section will display their own native tab list and not the tab lists configured on the proxy
excluded-servers:
  - exampleserver1
  - exampleserver2
```

### Steps to reproduce

Feature Request Only

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
[Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services). You can disable any feature you want in a specific server using disable-condition or display-condition, based on feature. For global playerlist, you can set isolate-unlisted-servers to true and not list it, or create a new group and only put that one server in. I don't even understand the point of this request.

**Comment by MacTh3Mac** [comment]
its not to disable specific features, its to revert to the native tab display entirely.  allowing software running on the actual bukkit based instance to have full control of the tab list.

The point of this request is to assist you as the developer of arguably the most complete currently available Velocity Tab list plugin to pick up the few small pieces that will enable to it be used in all situations.  Previously BTLP was the defacto most complete multi-proxy tab software available.

There are some things that you just wouldn't configure on a proxy, and in that use case rather than have to cater for every edge case scenario, a server owner  or developer can just write their own tab format for that specific use case without affecting the rest of the network.

Anyway, understood feature requests are closed.  So won't request any others.

**Comment by NEZNAMY** [comment]
You still didn't specify which parts exactly. Do you want some backend server to send header/footer? Disable header/footer in that server with condition. Do you want some backend server to format tablist names? Disable tablist foromatting in that server with disable condition. Same for teams and any other feature.

**Comment by MacTh3Mac** [comment]
All parts,  have the ability to completely disable 100% of your softwares features when a player is connected to the named backend servers. 

In effect reverting to the vanilla minecraft tablist. (or whatever bukkit/spigot/paper plugin may generate on that specific instance)

The equivalent of this feature:  https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Global-Configuration#excludeservers

**Comment by NEZNAMY** [comment]
What stops you from doing what I told you to do? You can even make layout only show in different servers, achieving your goal.

**Comment by MacTh3Mac** [comment]
layouts aren't compatible with redid-bungee multi-proxy :(

**Comment by NEZNAMY** [comment]
Layout supports condition, which can be set to not appear on a specified server.

**Comment by NEZNAMY** [comment]
What would your request do that cannot already be achieved using existing options?

**Comment by NEZNAMY** [comment]
Does that mean everything can be achieved?

**Comment by MacTh3Mac** [comment]
It means that I operate a multi-proxy environment on redis, and have just resigned myself that we will need to recode our mini game servers to not use tab list to display info etc, and instead focus on other methods, boss bars, scoreboards etc.

I understand what you are saying that I can turn most features on and off, and use layouts. However layouts are not supported with redisbungee. What I was looking for was an absolute removal of all TAB lists from a specified backend server or servers in the global config, and displaying a 100% vanilla bukkit generated tablist is what im looking for.

It's ok, I understand that we may be the only user who would ever use this feature, so rather than ask for the feature to be added, we will just find another way.  We are planning an update on the mini game servers anyway, so it's not a massive re-write for us.

I have closed the issue as it's not a feature that anyone but us will likely use.     Thanks for your previous responses.

**Comment by NEZNAMY** [comment]
Like I told you, it can be achieved. Use disable-condition for most features and the rest use display condition instead, so configure it to not show in that server. After you're done, go to the disabled server and send a screenshot of whatever is appearing that comes from TAB and is not supposed to.

**Comment by MacTh3Mac** [comment]
Will do. Thanks a lot.  I won't be doing a proxy restart until later in the week, as I have mismatched TAB versions on the network at the moment.  so need to set them all the same and then do a global restart.  I will update both open issues once I have achieved this.

Thanks
