### ISSUE TITLE
The nickname of the players is not displayed correctly when logging in

### ISSUE THREAD

**Issue by listtw** [NEZNAMY/TAB#1327]
### TAB version

4.1.6

### Software causing compatibility issue

HEXNICKS v3.1.1
TAB 4.1.6
BTAB 5.0.6

### Additional info

The nickname of the players is not displayed correctly at the entrance, after half a second everything starts working correctly

video: https://youtu.be/Up-zOWVVJE0

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Make steps to reproduce using a free nick plugin.

**Comment by listtw** [comment]
Use Hexnicks, tab, btab. For nicknames in the tab, specify the placeholder %hexnicks_nick%. For nicknames, specify a colored nickname using the /nick color command to watch other players when logging in

**Comment by listtw** [comment]
example: /nickcolor <gradient:#90EE90:#3CB371>

**Comment by NEZNAMY** [comment]
What did you put into groups.yml to display the nickname?

**Comment by listtw** [comment]
```#Owner:
#  tabprefix: "&0&l[&a&lOwner&0&l] &a"
#  tagprefix: "&2&lOwner &a"
Player:
  tabprefix: "&0&l[&7&lPlayer&0&l] &3"
  tagprefix: "&2&lPlayer &3"
example_group:
  header:
    - "This is an example of per-group header/footer"
  footer:
    - "applied to a group"

 # default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: "%cmi_user_glow_code%"
  customtabname: "%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"
  customtagname: ""
  tabsuffix: ""
  tagsuffix: ""

per-server:
  lobby:
    _DEFAULT_:
      customtabname: "&e● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"

per-world:
  world:
    _DEFAULT_:
      customtabname: "#4eff52● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"
  world_nether:
    _DEFAULT_:
      customtabname: "#ff4e4e● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"
  world_the_end:
    _DEFAULT_:
      customtabname: "#834eff● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"
  lobby:
    _DEFAULT_:
      customtabname: "&e● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"
  farms:
    _DEFAULT_:
      customtabname: "#00BFFF● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"
  farms_nether:
    _DEFAULT_:
      customtabname: "#87CEFA● &f%hexnicks_nick%%luckperms-suffix%%cmi_user_afk_symbol%"```

**Comment by NEZNAMY** [comment]
> example: /nickcolor gradient:#90EE90:#3CB371

![image](https://github.com/NEZNAMY/TAB/assets/6338394/560437a5-6a0b-48da-87dc-bbda7472562f)

**Comment by listtw** [comment]
sorry, use `/nickcolor <gradient:#90EE90:#3CB371>`

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=vsTa88nwSW4).

**Comment by listtw** [comment]
Why then can I get this error? I use Purpur 1.21 and velocity

**Comment by listtw** [comment]
and limbo auth, limbo api

**Comment by NEZNAMY** [comment]
I have no idea either. Try to reproduce it in a testing environment which is reproducable.

**Comment by listtw** [comment]
Perhaps this is due to the connection to Mysql

**Comment by NEZNAMY** [comment]
Find out.

**Comment by NEZNAMY** [comment]
No response for 2 months, assuming user has died. Reopen if not, still having this issue and interested to resolve it.
