### ISSUE TITLE
For Velocity  fancy-display-default: '%player_health_rounded%' not updating

### ISSUE THREAD

**Issue by Potenza7** [NEZNAMY/TAB#1328]
### Server version

folia 1.20.4

### TAB version

TAB-5.0.0-SNAPSHOT+1217

### Plugin list

<img width="497" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/48ba8099-bdd0-4027-9ada-a55919080d34">

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/94790955/6d5a7fe3-9390-4c9b-b2e1-850b7d4782a3)
<img width="257" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/a424f714-e891-4e4c-9996-8bfdd278e6e9">
 The health bar under the player is not updated. It remains stable but there are no updates. When you hit te players the number is always 20. This has been happening since I upgraded to Velocity tab setup.

### Expected behavior

Should be updated health bar

### Steps to reproduce

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Fancy-display-default is a value only visible on NPCs. Leave it empty if you don't want it.

**Comment by Potenza7** [comment]
> Fancy-display-default is a value only visible on NPCs. Leave it empty if you don't want it.

I leave it then this happened 
<img width="561" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/ceb3edc2-ba12-485c-94cd-af46b73f745c">
<img width="266" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/f0728e57-6161-42dd-983d-caf3b5d98a2b">

**Comment by Potenza7** [comment]
its looks empty right now

**Comment by Potenza7** [comment]
<img width="405" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/3ca90e90-615d-4cdf-bde6-f0ccbe89f7e3">
I changed it to the old default NPC, this time the NPC appears on the players. Could it be working bug with tab folia? It is installed via velocity, but there is no tab plugin in folia.
<img width="405" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/8690b0e8-6a3b-4899-83c8-4f2bf58d0857">

**Comment by Potenza7** [comment]
I think everything works fine in the paper lobby, but it doesn't work properly in the folia, which may be why. I would like to point out again that everything was built on Velocity.

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=8ReAxgW4L6E) on Velocity installation using TAB v4.1.6 and TAB-Bridge v5.0.6 on Folia 1.20.4 with the following configuration:
```
belowname-objective:
  enabled: true
  number: '%player_health_rounded%'
  text: '&cHP'
  fancy-display-players: '%player_health_rounded%'
  fancy-display-default: NPC
  disable-condition: '%world%=disabledworld'
```
Please provide new steps to reproduce the issue of health not updating that actually work.

**Comment by Potenza7** [comment]
> [Unable to reproduce](https://www.youtube.com/watch?v=8ReAxgW4L6E) on Velocity installation using TAB v4.1.6 and TAB-Bridge v5.0.6 on Folia 1.20.4 with the following configuration:
> 
> ```
> belowname-objective:
>   enabled: true
>   number: '%player_health_rounded%'
>   text: '&cHP'
>   fancy-display-players: '%player_health_rounded%'
>   fancy-display-default: NPC
>   disable-condition: '%world%=disabledworld'
> ```
> 
> Please provide new steps to reproduce the issue of health not updating that actually work.

Yes, I installed TAB 4.1.6 and then updated the TAB version to the latest version. Is this the problem?  So should I delete the config files and let it recreate them and set them again?

**Comment by NEZNAMY** [comment]
Using latest build from actions worked for me as well.

**Comment by Potenza7** [comment]
> Using latest build from actions worked for me as well.

<img width="277" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/0dfc9514-7fca-47a7-a561-5c2a8a98bcbc">
<img width="362" alt="image" src="https://github.com/NEZNAMY/TAB/assets/94790955/210b2118-074b-4341-8b9d-ac19c09b1f86">
I am using the latest version config but the problem still persists. The strange thing is that sometimes it works fine, but sometimes when I log in and out of the game a few times, it breaks, sometimes when I reload btab it works, sometimes it works, sometimes it gets buggy. The problem still persists.

**Comment by NEZNAMY** [comment]
You are the only person in the world with this issue. There must be something unique with your setup. Find out what it is and provide new working steps to reproduce.

**Comment by Potenza7** [comment]
> You are the only person in the world with this issue. There must be something unique with your setup. Find out what it is and provide new working steps to reproduce.

There is nothing unique. There is only velocity in the tab. And on other servers, I use tabbridge and papiproxybridge, that's all. nothing more.

**Comment by NEZNAMY** [comment]
If it's that easy to reproduce it for you, create a test setup with proxy and 1 server on your localhost, reproduce it there, zip it and send it, so I can try that same exact setup that reproduced the issue for you.

**Comment by Potenza7** [comment]
> If it's that easy to reproduce it for you, create a test setup with proxy and 1 server on your localhost, reproduce it there, zip it and send it, so I can try that same exact setup that reproduced the issue for you.

The problem is very strange. There is no problem on the paper lobby server, but when the players switch to folia survival, NPC is written on them. Some players have the heart number written on them, but some have NPCs written on them. This does not always happen, so it is normal that you do not encounter this in your setup.

**Comment by NEZNAMY** [comment]
Did you get any error log in TAB's folder?

**Comment by NEZNAMY** [comment]
No response for 6 weeks, assuming user has died. Reopen if not, issue still occurs and interested to solve it.
