### ISSUE TITLE
1.8.8 does not work correcrtly

### ISSUE THREAD

**Issue by Lncvrt** [NEZNAMY/TAB#1329]
### Server version

Paper 1.8.8

### TAB version

4.1.6

### Plugin list

![image](https://github.com/NEZNAMY/TAB/assets/171465674/cd5b440d-62d8-4020-980f-57e44b9116d6)
AntiSpamKick was by me, but it modifies a kick event, so unrelated.

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/171465674/05c05c6c-7ec0-4860-bcbf-d503a3308320)
![image](https://github.com/NEZNAMY/TAB/assets/171465674/bd7f40e2-422a-4316-9eed-c4fe3c1e4a31)
Prefixes/suffixes have issues with displaying on NameTags & Tab

Here's CoOwner prefix: "&8&l[&4&lCo&7&l-&4&lOwner&8&l]&r ", Owner prefix: "&8&l[&4&lOwner&8&l]&r "

### Expected behavior

Should properly display like 1.16.5 does

This also is an issue for 1.12.2, I tested it.
ViaVersion does NOT fix the issue when on a newer client.

Also it displays properly in chat
![image](https://github.com/NEZNAMY/TAB/assets/171465674/5f02321a-5744-4500-b2cc-1afc5d2971bf)

### Steps to reproduce

Load a 1.8 server
Add tab
Modify nametags with the ranks I provided
And it will be not properly displayed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Congratulations, you have discovered the 16-character limit mojang removed in 1.13.

**Comment by Lncvrt** [comment]
> Congratulations, you have discovered the 16-character limit mojang removed in 1.13.

So how do I fix it then.

**Comment by Lncvrt** [comment]
> Congratulations, you have discovered the 16-character limit mojang removed in 1.13.

I want ranks in my lobby, but not broken. I'm fine with it being gone from tag or tab

**Comment by NEZNAMY** [comment]
Update your game to 1.13+. Mojang removed the limit there. This is not a TAB bug.

**Comment by Lncvrt** [comment]
> Update your game to 1.13+. Mojang removed the limit there. This is not a TAB bug.

ViaBackwards still causes the issue.

**Comment by NEZNAMY** [comment]
ViaBackwards is for older client versions on newer server. It cannot cause that. Are you sure you updates the client, not server?
