### ISSUE TITLE
Customtabname doesn't get saved

### ISSUE THREAD

**Issue by FaberoM** [NEZNAMY/TAB#133]
**Server version**
1.15.2 Paper (+ Waterfall)

**Plugin version** ("latest" is not a version)
2.7.2

**Describe the bug**
When group's customtabname property is set by using a command it doesn't get saved and disappears when restarting bungeecord.

**How to reproduce**
Change group's customtabname with command something like this: `/btab group _OTHER_ customtagname %player_displayname%` and restart bungeecord.

**Expected behavior**
The customtabname would stay set even after a bungeecord restart.

**Actual behavior**
Customtabname resets back to default.

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Maybe because you ran a command with custom**tag**name.

**Comment by FaberoM** [comment]
Actually, I did run customtagname after that without thinking about it. Does that negate the effect of the previous command?

**Comment by NEZNAMY** [comment]
It doesn't. Check config.yml after you run the command if it got saved correctly.

**Comment by FaberoM** [comment]
Closing this as the command seems to be working fine now, don't really know what was the problem earlier.
