### ISSUE TITLE
Feature Request: Single Run Animations

### ISSUE THREAD

**Issue by tomkeuper** [NEZNAMY/TAB#1330]
### Server version

any

### TAB version

4.1.6

### Plugin list

-

### Describe the bug

I would like to create animations that only run a single time. The idea was to use the scoreboard title to display the server name, followed by the actual server the player is on, and ending with a glowing effect for just the server name. I thought about conditinal placeholders but I dont see a way to folow up an animation with a different animation. But something like an amount of view-cycles would work, or a similar implementation like FeatherBoard as shown in the config below

### Expected behavior

 configuration taken from FeatherBoard plugin: https://pastebin.com/gWCKCW0z

 Start (Single Run, chicken was a payed actor): https://gyazo.com/93014e039ac66285cf04381bb8d4476c

 https://github.com/NEZNAMY/TAB/assets/29728836/158d94b4-1f3c-431f-a571-86c0131a66f8

 Continuous: https://gyazo.com/85ee273c245bb65567bef5a595b9db56

https://github.com/NEZNAMY/TAB/assets/29728836/71c79590-918c-444b-bf65-6f80244a4a89

### Steps to reproduce

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
just fyi
![image](https://github.com/NEZNAMY/TAB/assets/45695833/206c8670-1757-4908-9d03-6ad21b0b8187)

**Comment by NEZNAMY** [comment]
Besides what was said in the comment above, your videos do not match your description. The first one is just one long animation and the second one is a glow that even public websites for making it easier exist. Which one of them is not achievable already?
