### ISSUE TITLE
BBBB in tab list

### ISSUE THREAD

**Issue by VINRED550** [NEZNAMY/TAB#1331]
### Server version

Paper 1.20.4

### TAB version

4.1.5

### Plugin list

![image](https://github.com/NEZNAMY/TAB/assets/174065065/a5ea90fb-c595-4f17-bc4a-1411087036a4)

### Describe the bug

4 letters B at the beginning of the list of players
![image](https://github.com/NEZNAMY/TAB/assets/174065065/ba6d7952-2a0a-4d8a-a74c-1482c5492b11)

### Expected behavior

Don't show BBBB

### Steps to reproduce

standart config

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Try without Triton and Protocollib. There's no way TAB has this issue and nobody else has noticed.

**Comment by NEZNAMY** [comment]
@VINRED550 are you still alive? Did removing ProtocolLib fix it?

**Comment by NEZNAMY** [comment]
No response for 3 weeks, assuming user has died. Another user on discord has confirmed this is caused by another plugin.

**Comment by korovkaK22** [comment]
Also have this bug. It appeared, because TAB doesn't work properly with Triton (Triton adds exta BBBB). So it's Triton's fault
Tested with Tab 4.1.7 and ProtocolLib 5.3
