### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by Hoknyy** [NEZNAMY/TAB#1333]
### Server version

Purpur 1.20.6

### TAB version

5.0.0

### Plugin list

Essentials, ItemsAdder, LoneLibs, LuckPerms, PlaceholderAPI, ProtocolLib, spark, Vault, VentureChat
(this is a simple test server)

### Describe the bug

Hello,

I'm experiencing a bug with the TAB plugin on my Minecraft Purpur 1.20.6 server. Here are the details:

**Problem Description:**

- It's impossible to join the server; I get kicked instantly with the message "Network Protocol Error".

- I've tried the 5.0.0 builds 1231, 1230, 1229, and versions 4.1.6 and 4.1.5 of the plugin.

**Important Information:**

- This bug seems to only occur when TAB-Bridge is present (I tried the 3 latest TAB-Bridge versions without success). Without TAB-Bridge, the TAB is bugged (it switches every second between the Bungee TAB config and the Spigot TAB config).

- With just the TAB plugin on Bungee and not on the Purpur servers, it works fine. However, this setup prevents me from displaying only the players of a certain server group (e.g., two lobby servers sharing the same tab which is different from the skyblock servers' tab).

Additionally, I want the TAB plugin on Spigot because it is useful for nametags.

What should I do?
 
Thank you for your assistance.
 

### Expected behavior

**Expected Behavior:**

- Players should be able to join the server without being kicked and without encountering the "Network Protocol Error" message.

- TAB should work seamlessly with TAB-Bridge, displaying the correct tab configuration for different server groups without switching between Bungee and Spigot configurations.

- The TAB plugin should be able to run on both Bungee and Spigot servers, allowing for custom configurations for different server groups (e.g., lobby servers and skyblock servers) and proper functioning of nametags on Spigot servers.

Thank you for your assistance.

### Steps to reproduce

Steps to Reproduce:

1. Set up a Minecraft Purpur 1.20.6 server.

2. Install the TAB plugin. Test with versions 5.0.0 build 1231, 1230, 1229, as well as 4.1.6 and 4.1.5.

3. Install the latest TAB-Bridge versions and configure them.

4. Attempt to join the server. Observe the "Network Protocol Error" message and the instant kick.

5. Remove TAB-Bridge and observe the TAB configuration switching every second between Bungee and Spigot configurations.

6. Set up the TAB plugin on BungeeCord only and note that it functions correctly but limits the ability to customize tabs for specific server groups and lacks nametag functionality on Spigot servers.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Why did you close the issue? Send the error you get in client console when the disconnect occurs.
