### ISSUE TITLE
Belowname fancy-display doesnt show up in 1.21

### ISSUE THREAD

**Issue by BiblicallyRBLX** [NEZNAMY/TAB#1334]
### Server version

Purpur 1.21

### TAB version

4.1.6

### Plugin list

Tried with nothing (besides spark)

### Describe the bug

It shows the original (text and number) but not (fancy-display-players or fancy-display-default)

### Expected behavior

The fancydisplay to show up lol!

### Steps to reproduce

Step 1: Start Server with Purpur 1.21 and install Tab
Step 2: Setup tab
Step 3: Check

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you are using vanilla client?

**Comment by BiblicallyRBLX** [comment]
Hey sorry for late response, yes I did infact try it out with vanilla. After checking with others, I found out that it works for others just not for me for some reason. So its a client issue, thanks tho!
