### ISSUE TITLE
1337

### ISSUE THREAD

**Issue by T14D3** [NEZNAMY/TAB#1337]
### Server version

-

### TAB version

-

### Plugin list

-

### Describe the bug

-

### Expected behavior

-

### Steps to reproduce

-

### Additional info

I am genuinely sorry but I had to.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
> I am genuinely sorry but I had to.

you had to what?
