### ISSUE TITLE
Placeholder high to low - error ?

### ISSUE THREAD

**Issue by Kyoonit** [NEZNAMY/TAB#1339]
### Server version

fabric 1.21

### TAB version

4.1.6

### Stack trace

[15:46:27] [Server thread/WARN]: [TAB] Placeholder %luckperms_highest_group_weight% used in sorting type PLACEHOLDER_HIGH_TO_LOW returned "%luckperms_highest_group_weight%" for player Kyoonit, which is not a valid number.

[15:46:27] [Server thread/WARN]: [TAB] Placeholder %luckperms_highest_group_weight% used in sorting type PLACEHOLDER_HIGH_TO_LOW returned "%luckperms_highest_group_weight%" for player Machinio, which is not a valid number.

### Additional info

In tab config: the placeholder '%luckperms..'  is written as on the wiki

scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "GROUPS:owner,admin,modo,vip,default"
    - "PLACEHOLDER_HIGH_TO_LOW:%luckperms_highest_group_weight%"

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
%luckperms_highest_group_weight% is a PlaceholderAPI placeholder, which is not available on Fabric.
If you want to sort by group, you can still use TAB's GROUPS sorting type and list all of your groups in the right order https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist#groups

**Comment by Kyoonit** [comment]
Placeholder API is installed and it's not working.

**Comment by Tanguygab** [comment]
TAB does not support the Fabric PlaceholderAPI alternative, only the one on Spigot
