### ISSUE TITLE
tabprefix not work in 1.7.10

### ISSUE THREAD

**Issue by wangyu2333333** [NEZNAMY/TAB#1342]
### TAB version

4.1.6

### Software causing compatibility issue

1.7.10 spigot

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting#about

**Comment by NEZNAMY** [comment]
No response for a week, assuming user has died. Tablist formatting was added in 1.8, the plugin uses nametag feature for <1.8 players to display the text in tablist.
