### ISSUE TITLE
Bedrock scoreboard

### ISSUE THREAD

**Issue by chelminski** [NEZNAMY/TAB#1343]
### TAB version

TAB.v4.1.6

### Software causing compatibility issue

Geyser (Bungee) Build #625 · 27.07.2024; (latest)

### Additional info

Scoreboard does not work properly for players using the pocket edition.

**What bedrock players see:**

![image](https://github.com/user-attachments/assets/bc50cb95-a88f-45d9-b894-b227625c5122)

**What java players see:**

![image](https://github.com/user-attachments/assets/14c5ae35-c596-4bcb-a829-515cc2e28ab0)

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you 100% sure you read https://github.com/NEZNAMY/TAB/wiki/Additional-information#bedrock-compatibility ? Your floodgate is not even configured correctly.

**Comment by chelminski** [comment]
I didn't actually read it :(, I just checked the checkbox 😅. I'll just create a different layout for the bedrock players because I don't use floodgate. Thank you for your help.

**Comment by NEZNAMY** [comment]
How else are you allowing bedrock players? Isn't it a required dependency for geyser? You can just set `use-numbers: true` in scoreboard to fix it as well.

**Comment by chelminski** [comment]
My server works offline. Players have their profiles created on our website with a chosen login. They can log in to the game from java and bedrock using their login and password.

Actually adding `use-numbers: true` fixed the issue. Thx.
