### ISSUE TITLE
The chat box displays slot_1

### ISSUE THREAD

**Issue by ALMikey** [NEZNAMY/TAB#1345]
### Server version

velocity-3.3.0-SNAPSHOT-408 | papermc-1.20.4

### TAB version

TAB v4.1.6

### Plugin list

![image](https://github.com/user-attachments/assets/077db89a-747c-4eca-abdb-64fd0eb59128)

### Describe the bug

![1](https://github.com/user-attachments/assets/e2583367-42b6-4bfe-a202-bae4272e5d61)
Why do I get these prompts when I press the TAB key in the chat box?
I don't want to see so much content, slot_11...

### Expected behavior

null

### Steps to reproduce

null

### Additional info

null

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
"I ticked all of the boxes without actually reading them".

Didn't you just describe https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Layout#additional-note-3---entries-in-chat-complete ? Disable layout if you don't want it.

**Comment by ALMikey** [comment]
> “我勾选了所有的方框，但没有真正阅读它们”。
> 
> 你刚才不是描述了 https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Layout#additional-note-3---entries-in-chat-complete 吗？如果您不需要布局，请禁用布局。

If you don't want this situation to occur, you need to disable layout: enabled: true, right?
Is there any other way to solve it?

**Comment by ALMikey** [comment]
> The wiki link I sent explains everything. It's a part of the feature. Either disable the feature, or downgrade your client (not server) to 1.19.2 or lower.

ok
