### ISSUE TITLE
Network Protocal Error (Something to do with Teams)

### ISSUE THREAD

**Issue by JazzMattic** [NEZNAMY/TAB#1346]
### Server version

Paper 1.20.4

### TAB version

4.1.6

![image](https://github.com/user-attachments/assets/1fd1098e-9b68-4e43-ace3-aab54c2885bc)

### Plugin list

MineChess (Chess MiniGame)
ViaVersion
ViaBackward
Many More......

### Describe the bug

Players are being kicked due to __Network Protocal Error__ when they join a mini-game called MineChess. When looking at the anti-override log within TAB, it shows: 

[TAB v4.1.2] Something just tried to add player bjornicorn712 into team game-team (expected team: 7bjornicorn712A)

The console itself only shows: 

[TAB] [WARN] Player bjornicorn712's group (water) is not in sorting list! Sorting list: owner,admin,mod,helper,builder,vip,default. Player will be sorted on the bottom.

**This does not happen to all players! Only some players have this issue - about 40% - 50% of players.**

### Expected behavior

Not being kicked for joining mini-game.

### Steps to reproduce

1) Join mini-game called Minechess.
2) Interact with anything. Player is only kicked after they change item slots or when they actually interact with the mini-game in any way. If they never interact, but are just in the game - they do not get kicked.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Client console will provide you with the full disconnect error.

**Comment by JazzMattic** [comment]
It genuinly does not. What I provided above is the only thing any plugin spits out when a player gets disconnected due to this error. The only reason I know it's a Network Protocal Error is beacause that is the reason the disconnected player recieves when disconnected. Below I am posting the full log of the event from time to disconnect to when the player is able to rejoin.

 **[Sat 20:28:19 INFO  Server/PlayerConnection] bjornicorn712 lost connection: Disconnected**
  [Sat 20:28:22 INFO  Server] [Not Secure] •[Air]• ⦿ TaaviTheCat: Can I gamble my talis
  [Sat 20:28:22 INFO  Server] [Not Secure] •[Air]• ⦿ TaaviTheCat: lmao
  **[Sat 20:28:23 INFO  Server/LoginListener] UUID of player bjornicorn712 is b79526da-de68-4563-be26-8ae8168baa48
  [Sat 20:28:24 INFO ] [TAB] [WARN] Player bjornicorn712's group (water) is not in sorting list! Sorting list: owner,admin,mod,helper,builder,vip,default. Player will be sorted on the bottom.
  [Sat 20:28:24 INFO  Server/PlayerList] bjornicorn712[/89.98.181.4:63941] logged in with entity id 2909 at ([world]-7326.585655448904, 135.86819527715338, -3658.601948081322)**

**Comment by NEZNAMY** [comment]
I asked for client log, not server log.

**Comment by GewoonMennoplays** [comment]
[disconnect-2024-08-07_09.41.43-client.txt](https://github.com/user-attachments/files/16520159/disconnect-2024-08-07_09.41.43-client.txt)

We are also experiencing that issue. Attachment above is the client log. We only have some basic plugins, like worldguard, worldedit, citizens (since a few days), this plugin, viaversion and Essentials. For more details (such as versions), I can provide is necessarily. 

Server version is 1.21 iirc.

**Comment by NEZNAMY** [comment]
> [disconnect-2024-08-07_09.41.43-client.txt](https://github.com/user-attachments/files/16520159/disconnect-2024-08-07_09.41.43-client.txt)
> 
> We are also experiencing that issue. Attachment above is the client log. We only have some basic plugins, like worldguard, worldedit, citizens (since a few days), this plugin, viaversion and Essentials. For more details (such as versions), I can provide is necessarily.
> 
> Server version is 1.21 iirc.

Team `verstoppers` does not come from TAB. Another plugin is trying to handle teams alongside TAB, which the game doesn't support. Decide which plugin you want to handle teams and disable them in the other one.

**Comment by GewoonMennoplays** [comment]
> > [disconnect-2024-08-07_09.41.43-client.txt](https://github.com/user-attachments/files/16520159/disconnect-2024-08-07_09.41.43-client.txt)
> > We are also experiencing that issue. Attachment above is the client log. We only have some basic plugins, like worldguard, worldedit, citizens (since a few days), this plugin, viaversion and Essentials. For more details (such as versions), I can provide is necessarily.
> > Server version is 1.21 iirc.
> 
> Team `verstoppers` does not come from TAB. Another plugin is trying to handle teams alongside TAB, which the game doesn't support. Decide which plugin you want to handle teams and disable them in the other one.

Hmm okay, we just use the default paper commands for teams (I guess its a spigot feature, but unsure about that). Besides that, we don’t use any plugins for teams.

**Comment by NEZNAMY** [comment]
If you want to use vanilla commands to assign players into teams, disable the feature in TAB config to prevent conflict. The kick should be avoided by TAB, but an exception is if TAB was reloaded.

**Comment by NEZNAMY** [comment]
Any news @GewoonMennoplays ?

**Comment by GewoonMennoplays** [comment]
After testing, the issue was caused by Citizens. We have still no idea why, but it is fixed. Thank you for your help!
