### ISSUE TITLE
running LayoutManager.sendLayout freezes placeholders

### ISSUE THREAD

**Issue by U5B** [NEZNAMY/TAB#1347]
### Server version

Paper 1.19.4

### TAB version

4.1.6

### Plugin list

![2024-08-05_12-18](https://github.com/user-attachments/assets/a8e01ff2-d132-4351-bbee-6e8b69b7420e)

### Describe the bug

LayoutManager.sendLayout freezes placeholders

### Expected behavior

If LayoutManager.sendLayout is sent twice, it shouldn't freeze placeholders

### Steps to reproduce

1. Setup a placeholder that refreshes every second.
2. Run sendLayout once to see the placeholders refresh properly.
3. Run sendLayout again to see the placeholders freeze.

### Additional info

Header and Footer refreshes placeholders like normal
Layout name is changing between sends

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by U5B** [comment]
No errors in server log
And `/tab parse me %placeholder_name%` shows the placeholder updating as well

**Comment by NEZNAMY** [comment]
Send a screenshot / video and example code that reproduces the issue.

**Comment by U5B** [comment]
Code example
```
public void playerLoadEvent(PlayerLoadEvent event) {
	UUID uuid = event.getPlayer().getUniqueId();
	test1(event.getPlayer());
	Bukkit.getScheduler().runTaskLater(Plugin.getInstance(), () -> {
		test2(TabAPI.getInstance().getPlayer(uuid));
	}, 100);
	// Bukkit.getScheduler().runTaskAsynchronously(Plugin.getInstance(), () -> refresh());
}

public void test1(TabPlayer viewer) {
	Layout layout = TabAPI.getInstance().getLayoutManager().createNewLayout("layout_a");
	layout.addFixedSlot(1, "%monumenta_effect_1%");
	layout.addFixedSlot(2, "This is layout A");
	TabAPI.getInstance().getLayoutManager().sendLayout(viewer, layout);
}

public void test2(TabPlayer viewer) {
	Layout layout = TabAPI.getInstance().getLayoutManager().createNewLayout("layout_b");
	layout.addFixedSlot(1, "%monumenta_effect_1%");
	layout.addFixedSlot(2, "This is layout B");
	TabAPI.getInstance().getLayoutManager().sendLayout(viewer, layout);
}
```
https://github.com/user-attachments/assets/f647e8ef-2534-4a74-a3ec-8bb2e9e8538d

**Comment by U5B** [comment]
A workaround that I can do is run `sendLayout` constantly but that is quite silly if there were no changes others then the placeholders

**Comment by U5B** [comment]
Removing `p.layoutData.view.getPattern() != pattern` from https://github.com/NEZNAMY/TAB/blob/032af707dd24057129698a295303caff0a7d79f0/shared/src/main/java/me/neznamy/tab/shared/features/layout/FixedSlot.java#L32
seems to have "fixed" it. However I don't think this is a valid fix.

**Comment by U5B** [comment]
Another idea would to use PlaceholderManager to register placeholders and then just send a layout of placeholders.
However, I wouldn't be able to adjust ping via placeholder then.

**Comment by U5B** [comment]
This doesn't seem like it have fixed it, but it might be specific to my setup

**Comment by NEZNAMY** [comment]
Have you tried the code you sent? I did and it was fixed.

**Comment by U5B** [comment]
> Have you tried the code you sent? I did and it was fixed. Have you tried latest build from github actions?

I tried the latest build from actions. And that code didn't work. However, I did have values in a default layout so it might be because of that.

**Comment by U5B** [comment]
Hmm, having a unique Layout between refreshes (using UUID.randomUUID) fixed it. So I think it was an issue with my setup.

**Comment by NEZNAMY** [comment]
Did you try to create layouts with duplicated names?

**Comment by U5B** [comment]
> Did you try to create layouts with duplicated names?
Yes. My original code swapped between two names `test1` and `test2` over a period of time.

**Comment by NEZNAMY** [comment]
That behavior is not supported. Makes sense now.

**Comment by U5B** [comment]
Yeah I am using TAB in an awkward way. I am using Layout to provide my own set of players since RedisBungee was unreliable in my setup.

Thank you for fixing the issue!
