### ISSUE TITLE
Tab sorting

### ISSUE THREAD

**Issue by AggerTV** [NEZNAMY/TAB#135]
**Server version**
Paper version git-Paper-1617 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Plugin version** ("latest" is not a version)
TAB version 2.7.3

**Describe the bug**
When setting
"change-nametag-prefix-suffix: false" to false, tab sorting breaks

**How to reproduce**
see above

**Expected behavior**
Tab sorting should not break just because I disable TAB's terrible way of handeling nametags above players

**Actual behavior**
Tab sorting should work fine no matter if "change-nametag-prefix-suffix:" is set to true or false.

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Terrible way of handling ? You mean the experimental feature that is DISABLED by default ?
Anyway, https://github.com/NEZNAMY/TAB/wiki/Why-is-player-sorting-not-working-%3F https://github.com/NEZNAMY/TAB/wiki/config.yml#change-nametag-prefix-suffix and https://github.com/NEZNAMY/TAB/wiki/config.yml#group-sorting-priority-list

**Comment by AggerTV** [comment]
Why is tablist sorting depending on whether tab handels the nametag shown above the player?

**Comment by NEZNAMY** [comment]
This is how minecraft is made. Nametags handle sorting.

**Comment by AggerTV** [comment]
Okay, but could you maybe do, so nametags works a bit more like nametagedit for example, instead of  nametags being armor stands.

Because I really do like this plugin, but the armor stand option really doesn't work that well

**Comment by NEZNAMY** [comment]
Simply.. FACEPALM !
This is unlimited nametag mode feature, which is disabled by default and you enabled it. You can disable it.

**Comment by AggerTV** [comment]
Yeah I'm a bit slow today, had like 2 hours of sleep

just delete this ticket
