### ISSUE TITLE
playerlist objectives not works at other backend server

### ISSUE THREAD

**Issue by Timtaran** [NEZNAMY/TAB#1351]
### Server version

Velocity-3.3.0-SNAPSHOT

### TAB version

4.1.6

### Plugin list

emotecraft, fastmotd, viaversion, forcepack, luckperms, huskchat, limboapi, limboauth, limboreconnect, skinsrestorer, tab, velocitywhitelist, voicechat

### Describe the bug

playerlist objectives shows only at one of two servers
![изображение](https://github.com/user-attachments/assets/4195df54-2ab3-460c-be95-e1416ec0ad13)
![изображение](https://github.com/user-attachments/assets/7f31278e-3436-4514-98d2-f1ff342593b8)

### Expected behavior

all gonna be fine

### Steps to reproduce

1. Install TAB on velocity
2. Install TAB-Bridge and PAPI on backend servers
3. Start servers

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Didn't you accidentally forget to install bridge?

**Comment by Timtaran** [comment]
oh, I'm sorry, my bad

**Comment by NEZNAMY** [comment]
That's not a bug then.
