### ISSUE TITLE
TabAPI placeholder is never refresh

### ISSUE THREAD

**Issue by ranminecraft** [NEZNAMY/TAB#1352]
### Server version

This server is running Folia version 1.21-DEV-dev/1.21@2b8c879 (2024-08-08T19:48:56Z) (Implementing API version 1.21-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-DEV-2149923 (MC: 1.21)

### TAB version

4.1.6

### Plugin list

original plugin

### Describe the bug

TabAPI placeholder is never refresh

### Expected behavior

Tab should refresh placeholder from other plugin.

### Steps to reproduce

`TabAPI.getInstance().getPlaceholderManager().registerPlayerPlaceholder("%player-title%", -1, player -> getTitle((Player) player.getPlayer()));`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You made refresh interval -1 and think it's a bug that it doesn't refresh?

**Comment by sakurawald** [comment]
I ticked all of the boxes without actually reading them ?

**Comment by NEZNAMY** [comment]
> I ticked all of the boxes without actually reading them ?

We get this a lot more than you'd think.
