### ISSUE TITLE
Vanish not functional on Fabric 1.19.2 TAB

### ISSUE THREAD

**Issue by Skullians** [NEZNAMY/TAB#1354]
### Server version

Fabric 1.19.2

### TAB version

TAB v4.1.5

### Plugin list

https://mclo.gs/lwvpCts

### Describe the bug

Running `/lp user <name> meta set vanished true` on Fabric does not hide me from the playerlist (either in tab, or from /list or from an external query from the likes of mcsrvstat.us).

### Expected behavior

Player should be hidden from playerlist etc.

### Steps to reproduce

Step 1. Run `/lp user <name> meta set vanished true`
Step 2. See nothing happens.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Where does TAB advertise it removes player from tablist and /list when running some LuckPerms command?

**Comment by Skullians** [comment]
> Where does TAB advertise it removes player from tablist and /list when running some LuckPerms command?

https://github.com/NEZNAMY/TAB/wiki/Additional-information#vanish-detection

> For a player to be detected, player has to have vanished metadata flag set to true. Most, if not all vanish plugins do this, including, but not limited to CMI, Essentials, SuperVanish, PremiumVanish and probably more. If TAB is installed on BungeeCord, [Bridge](https://github.com/NEZNAMY/TAB/wiki/TAB-Bridge) must be installed on backend servers to forward vanish status to the proxy.

**Comment by Skullians** [comment]
Unless I have not understood correctly, the 'vanished metadata flag' you are referring to is a LuckPerms metadata flag?

**Comment by Skullians** [comment]
Although I believe I am wrong about it removing vanished players from /list, but tablist I am certain it does unless I cannot read.

**Comment by NEZNAMY** [comment]
The metadata flag refers to platform's API, not LuckPerms. Fabric doesn't have that. Even if it was possible, TAB doesn't manage vanishing, it only detect vanished players to prevent some of its features from breaking it.

**Comment by Skullians** [comment]
:/ Okay, right.
So if I've understood correctly, Fabric does not have support for this?

Is there any possibility that it _can_ support it?

**Comment by NEZNAMY** [comment]
It could if you edited TAB's code to hook into *something* that tracks *something* that can be used as a vanish status. Even then TAB does not manage vanishing itself, so you'll need an actual vanish plugin.

From the page you sent:
> Although TAB does not manage player vanishing in any way, it checks for vanish status for features to be properly compatible.

**Comment by Skullians** [comment]
Okay, thanks for your time.
Last question, could you maybe link some place in the fabric code / API where I can modify the players shown in the player list, so I can hook into my vanish mod there?

**Comment by NEZNAMY** [comment]
There isn't any API. You'll need to send minecraft packets.

**Comment by Skullians** [comment]
:/ okay. Thanks
