### ISSUE TITLE
Why doesnt it work with dimensional colour plugin?

### ISSUE THREAD

**Issue by Kihungd** [NEZNAMY/TAB#1355]
### TAB version

4.1.6

### Software causing compatibility issue

plugin dimensional colour

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
What is that plugin supposed to do and how is it a TAB issue?

**Comment by NEZNAMY** [comment]
@Kihungd if you do not respond, issue will be closed as invalid.
