### ISSUE TITLE
Prefixes/suffixes from the AFK+ plugin with the TAB plugin do not appear

### ISSUE THREAD

**Issue by TheRa1nY** [NEZNAMY/TAB#1356]
### Server version

1.21.1 Purpur

### TAB version

4.1.7

### Plugin list

AFKPlus, AFKPlusPAPI, AFKPlusPrefix, AntiEnd, AntiSeedCracker, ArmorStandTools, AuthMe, AuthMeTitles, Chatty, CoreProtect
CoreProtectTNT, DiscordSRV, *EasyWhitelist, emotecraft, GSit, Harbor, Hat, HeadDrop, InvSeePlusPlus, LiteBans, LuckPerms, Maintenance, MiniMOTD, packetevents, Pl-Hide-Pro, PlaceholderAPI, PlasmoVoice, *Playtimes, ProtocolLib, pv-addon-discs pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-sculk, ReFrame, *ResourcePackDownloader, SkinsRestorer, SuperVanish, TAB, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, Volleyball, Vulcan

### Describe the bug

Without the TAB plugin, the prefix/suffix appears, but with the plugin it does not appear. When a player gets up in AFK, he should be given a prefix/suffix in the tab, but this does not work with the TAB plugin.

### Expected behavior

it should show the prefix/suffix in the tab from the AFK+ plugin

### Steps to reproduce

1. download tab and afk+, afkpluspapi and afkplusprefix
2. restart server
3. enter afk mode and there will be no prefix/suffix in the tab

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
If you don't want TAB to format tablist names, disable `tablist-name-formatting`.

**Comment by TheRa1nY** [comment]
> If you don't want TAB to format tablist names, disable `tablist-name-formatting`.

what? I need to fix the prefixes and suffixes so that they appear on the contrary from the AFK+ plugin, and not turn them off completely.

**Comment by NEZNAMY** [comment]
Your bug report says something breaks when you install TAB, because you cannot have 2 plugins handle the same thing. I told you how to disable it in TAB to let the AFK plugin handle formatting just like it does when TAB is not installed.

**Comment by TheRa1nY** [comment]
> Your bug report says something breaks when you install TAB, because you cannot have 2 plugins handle the same thing. I told you how to disable it in TAB to let the AFK plugin handle formatting just like it does when TAB is not installed.

even after disabling this line, the prefix/suffix from AFK+ does not appear in the tab.

**Comment by NEZNAMY** [comment]
I don't know how that random plugin you didn't even link works, maybe it uses teams instead. In that case, try also disabling `scoreboard-teams`. Also what is preventing you from simply following [this guide](https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#displaying-afk-status-in-tablist)?

**Comment by TheRa1nY** [comment]
when I turn off the struts, the prefix from the lakperms disappears, but I need it, and also I can't change the prefix and suffix. They are always the same in the tab, only the prefix is displayed there, the red word AFK. What should I do?

**Comment by TheRa1nY** [comment]
![image](https://github.com/user-attachments/assets/fd44c856-1a54-4426-ab5e-2e71922ea87c)

**Comment by TheRa1nY** [comment]
![image](https://github.com/user-attachments/assets/8e58e16c-08da-43c2-9cb2-1e4a8640e641)

**Comment by NEZNAMY** [comment]
Isn't this what you wanted? You have successfully restored behavior that happens without TAB installed, just like you wanted.

**Comment by TheRa1nY** [comment]
I need to make the prefixes and suffixes from LuckPerms and from AFK+ work

**Comment by NEZNAMY** [comment]
Then why don't you follow the guide I sent?

**Comment by TheRa1nY** [comment]
Okay, I'll reset everything and do it according to your guide

**Comment by NEZNAMY** [comment]
Are you sure this is a TAB bug? Keep in mind you are in a bug report right now. This is not support.

Send your relevant configuration sections you configured to show your desired output while they don't.

**Comment by NEZNAMY** [comment]
@TheRa1nY if you do not respond, issue will be closed as invalid.
