### ISSUE TITLE
[Velocity] 1.20.3+ not display red number is not working

### ISSUE THREAD

**Issue by 8MiYile** [NEZNAMY/TAB#1360]
### Server version

Velocity 3.3.0

### TAB version

4.1.7

### Plugin list

HaProxy-Detector; LuckPerms; MiniMOTD-Velocity; MiniPlaceholders; MultiLogin; TAB; ViaVersion; ViaBackwards; ViaRewind; ViaVersion-Expansion

### Describe the bug

i'm using Client 1.20.4
TAB adn ViaVersion is working on Velocity
but... remove red number not working

### Expected behavior

can support viaversion for velocity

### Steps to reproduce

Velocity: TAB + ViaVersion
Paper: TAB-Bridge

### Additional info

![image](https://github.com/user-attachments/assets/12067b2c-1715-470c-8d5e-35667a5ed869)
i remenber these red number in client 1.20.4 can remove
![image](https://github.com/user-attachments/assets/f03134d2-1288-478d-a9af-4d194710113e)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Run `/ver` on backend server and show output.

**Comment by 8MiYile** [comment]
This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
@NEZNAMY

**Comment by NEZNAMY** [comment]
1.18.2 < 1.20.3. Bridge cannot send new content on old server.

**Comment by 8MiYile** [comment]
wait
TAB in Velocity

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Compatibility#supported-features-per-platform
"Via Bridge". Velocity doesn't have a scoreboard API. I am working on one, but it has not been tested enough, so it wasn't publicly advertised yet.

**Comment by 8MiYile** [comment]
so it's a velocity's problem?

**Comment by NEZNAMY** [comment]
It's a missing functionality and this is the workaround.

**Comment by 8MiYile** [comment]
So I just have to wait for a solution right, and how do I get Customer Support for this plugin?

**Comment by NEZNAMY** [comment]
Either wait, or get latest build of TAB from github actions and follow instructions in console.
Customer support is no longer for sale.

**Comment by NEZNAMY** [comment]
That's what my new project will offer.

**Comment by 8MiYile** [comment]
Then we'll wait and see.
——————————————————————————
那就静候佳音

**Comment by NEZNAMY** [comment]
Your reported issue is not a TAB bug.

**Comment by 8MiYile** [comment]
I know

**Comment by NEZNAMY** [comment]
This is an issue tracker, and I don't want to have open "issues" that aren't bugs or anything similar.

**Comment by 8MiYile** [comment]
Okay
