### ISSUE TITLE
skript-placeholders Incompatibility

### ISSUE THREAD

**Issue by DeoviserYT** [NEZNAMY/TAB#1363]
### TAB version

4.1.7

### Software causing compatibility issue

[skript-placeholders](https://github.com/APickledWalrus/skript-placeholders)

### Additional info

When I use the Tab plugin with the skript-placeholders plugin, the result from the placeholder is N/A when it should say Lobby
I need this to be fixed so that I can release a server I have been working on for a long time please fix it!

### Checklist

- [ ] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
does it work in `/papi parse me <placeholder>` ?

**Comment by DeoviserYT** [comment]
> does it work in `/papi parse me <placeholder>` ?

yes

**Comment by NEZNAMY** [comment]
Does it work in `/tab parse me <placeholder>` ? I'll need some screenshots of it not working, the configuration you used and the parse input & output.

**Comment by DeoviserYT** [comment]
you can join and see if you want

**Comment by NEZNAMY** [comment]
I don't want to join. I want to have enough information to work with. I highly doubt this is TAB issue in the first place. It doesn't hook into Skript directly and uses PlaceholderAPI instead.

**Comment by DeoviserYT** [comment]
![2024-09-04_16 19 40](https://github.com/user-attachments/assets/ff1f4884-77ee-41ce-910d-90221c68adf9)
on sidebar it says Server: N/A

**Comment by NEZNAMY** [comment]
Now show your scoreboard section and outputs of both parse commands in chat.

**Comment by DeoviserYT** [comment]
![2024-09-04_16 21 05](https://github.com/user-attachments/assets/3c8dd05d-9cee-4a72-a4b5-de3c88d64d7f)
Command says Lobby

**Comment by NEZNAMY** [comment]
%server% is not a PlaceholderAPI placeholder. TAB has an internal %server% placeholder that is originally proxy-only, but has a backend implementation that takes the value from config, for someone who requested it for MySQL purposes. 
Solution: Don't make your placeholders identical to TAB's. This is not a bug, but intended behavior.

**Comment by DeoviserYT** [comment]
ok thanks i will try it
