### ISSUE TITLE
nametags (group) not properly shown between two proxies

### ISSUE THREAD

**Issue by 301haru** [NEZNAMY/TAB#1365]
### TAB version

4.1.8

### Software causing compatibility issue

Velocity 3.3.0

### Additional info

for example lets say

examplegroup:
  tabprefix: "example"
  tagprefix: "example"
  
is written in groups.yml

there are two proxies (Velocity A, Velocity B) pointing to the same minecraft server (Server A)

Player A joins Server via Velocity A, Player B joins Server via Velocity B
between Velocity A and Velocity B, TAB settings are exactly same, and permissions (groups) between servers are synced by db

However, even though Player A's primary group is "examplegroup", Player B cannot see Player A's tab prefix nor tag prefix. but if Player B joins the server via Velocity A, now it can see prefixs normally.

even though Velocity B knows Player A's primary group, but TAB does not recognizing Player A's group so Player B just see white default Player A's name.

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-info:-RedisBungee-support
Are you sure you installed that plugin? `/velocity plugins`.

**Comment by 301haru** [comment]
so in this case RedisBungee is essential? 
I am not using RedisBungee in my server currently because it is not required to handle what I need for multiple proxy.

**Comment by NEZNAMY** [comment]
Then how is TAB supposed to know there exists some other proxy out there, let alone get data from it?

**Comment by Tanguygab** [comment]
Why not just use TAB on the backend (which is aware of all pmayers connected to it) rather than on each proxy (which only knows players connected to the backend through itself)?

**Comment by 301haru** [comment]
I am using TAB both on backend and frontend and only using name formatting things on frontend because of some optimizations .

**Comment by Tanguygab** [comment]
Mixed installation is not supported, do not use TAB on both the proxies and backend server,just keep it on the backend, I don't see what "optimizations" it would bring, it's just making everytime more complex and won't even work for what you need

**Comment by 301haru** [comment]
yeah I know it is not supported and it makes everything more complex. I had many trials to make everything works fine.
but in my case mixed installation was mandatory.
I am currently using TAB in MultiPaper so if I just let TAB calculate things everything on backend servers, CPU usages was getting so high so mixed installation was the best solution for optimizationing in high player counts.

so RedisBungee would be a best solution for the problem..?

**Comment by NEZNAMY** [comment]
If you are running into performance issues, make a spark report and send it.

**Comment by 301haru** [comment]
what about let tab bridge send player infos to proxies. maybe that would fix this case.
I can't make spart report right now but I'll check it. High CPU usage problem occur in high player counts (1000+player)
with scoreboard-teams enabled.

**Comment by NEZNAMY** [comment]
Using plugin messaging would make performance even worse. Velocity can't even send scoreboard packets, because they are not available there. Dev builds should drastically improve performance at high player counts as well.
