### ISSUE TITLE
%tagprefix% as placeholder not working in sorting?

### ISSUE THREAD

**Issue by PartyKiwi** [NEZNAMY/TAB#1366]
### TAB version

4.1.7

### Software causing compatibility issue

kingdomcraft and custom made plugin

### Additional info

I use the KingdomCraft-plugin and API to get information about a players kingdom. In KingdomCraft I can configure prefixes and ranks for each kingdom. I want the prefix and rank to be available in the TAB plugin. However, because there is no integration between KingdomCraft and TAB I created a plugin in between. When an user joins the server or changes a kingdom an event is triggered to retrieve kingdom information from the KingdomCraft plugin. My plugin combines rank and prefix and uses the TAB API to change the prefix of the NameTag (tab.getNameTagManager()) and the prefix in the tablist (tab.getTabListFormatManager()). 

This works fine, every player shows the right name as tag and in the tab list. However, I now want to sort the tablist based on prefix and name.

I tried %player% as placeholder in the sorting-types of my config. But this doesn't sort on prefix. When I type /tab debug (player) it only shows the name without prefix under 'Sorting note.' I then tried %tagprefix% but this doesn't work and /tab debug (player) doesn't translate %tagprefix%. I tried other placeholders as well like %displayname%. How can I sort on tagprefix and name in the tablist?

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
`%tagprefix%` is not a valid placeholder. Did you mean `%tab_tagprefix%` from TAB's PlaceholderAPI expansion?

**Comment by PartyKiwi** [comment]
Thanks for pointing me in the right direction. I found BukkitTabExpansion.java in your source code which lists all of the TAB placeholders. However, %tab_tagprefix% doesn't translate when I type '/tab debug (player)'. It just says '%tab_tagprefix% returned %tab_tagprefix%'. How do i tell papi to use your placeholders as well?

**Comment by NEZNAMY** [comment]
Did you check the [Placeholders wiki page](https://github.com/NEZNAMY/TAB/wiki/Placeholders#placeholderapi)?

**Comment by PartyKiwi** [comment]
Thank you, that did the trick. Setting 'placeholders: register-tab-expansion' was false in my config. When I changed it to true and reloaded the plugin it worked fine.

**Comment by NEZNAMY** [comment]
So what is the compatibility issue here? I still didn't fix anything.

**Comment by PartyKiwi** [comment]
I followed the workflow creating a new issue, and had to choose a label. When I did, I thought that this label suited the best for my problem. It seems to me that I can't change this label afterwards? Excuse me for the confusion. Thanks for your help!

**Comment by NEZNAMY** [comment]
You were looking for this one, it's on the bottom of the list.
![image](https://github.com/user-attachments/assets/566598b6-bab1-4029-9ca0-216800e6de2f)

**Comment by PartyKiwi** [comment]
Ah, yes, but that didn't give me the option to create an issue. And I really thought that this wasn't a problem on my side. My mistake, sorry for that.
