### ISSUE TITLE
Fabric Geyser 1.21 Server - Roles wont show up next to names in chat

### ISSUE THREAD

**Issue by MarkHarrisMedia** [NEZNAMY/TAB#1367]
### TAB version

TAB v4.1.8.jar

### Software causing compatibility issue

How do I configure luckperms, or TAB so that roles show up in the chat like the do in TAB list..?

Also the invite link to your discord is not working so I had to post here.

-Mark

### Additional info

Fabric Geyser Crossplay 1.21

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
How is this a compatibility issue? TAB is not a chat plugin. Get a chat plugin. Which invite link is not working?

**Comment by NEZNAMY** [comment]
No response for 2 weeks, assuming user has died. TAB does not affect chat in any way.
