### ISSUE TITLE
[Tab] scoreboard unicode problems

### ISSUE THREAD

**Issue by DarkLionQc** [NEZNAMY/TAB#1369]
### Server version

Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### TAB version

TAB v4.1.8

### Plugin list

AdvancedEggHunt, AntiSeedCracker, AxGraves, BanItem, CustomCrops, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, LuckPerms, Maintenance, Oraxen, PlaceholderAPI, Polymart, ProtocolLib, Spartan, SuperVanish, TAB, Tebex, Vault,  WorldEdit, WorldGuard, WorldGuardExtraFlags

### Describe the bug

put %luckperms_prefix% in Tab scoreboard 
Luckperms prefix : prefix.1.&fꐶ&4
![Capture d’écran 2024-10-10 092104](https://github.com/user-attachments/assets/216d4da1-a504-479b-afe1-cb3bbb25f402)

### Expected behavior

![Capture d’écran 2024-10-10 092121](https://github.com/user-attachments/assets/5dcf5f21-121a-4172-868e-fce083ebf635)

### Steps to reproduce

Use a glyph, set a unicode
put in luckperms
put %luckperms_prefix% in scoreboard

( prefix.1.&fꐶ&4 )

### Additional info

it work perfectly in tab, but not in scoreboard

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
What is it supposed to show? Looks like it shows exactly what you configured. If you mapped an image to that symbol in a resource pack and it's not working, it's not a TAB issue. Have you tried it elsewhere, such as chat? Can you try a different scoreboard plugin to see if it works there?

**Comment by DarkLionQc** [comment]
In the TAB you can see, the glyph appear. But in the Scoreboard, he don't appear ( it is the same plug-in )

he show the glyph everywhere but not in scoreboard

![Capture d’écran 2024-10-10 093847](https://github.com/user-attachments/assets/4e3e5c42-2569-4a7e-8a66-323b22cf4827)
![Capture d’écran 2024-10-10 093839](https://github.com/user-attachments/assets/1a4087db-9f23-4125-aef8-933e5a05b323)
![Capture d’écran 2024-10-10 093855](https://github.com/user-attachments/assets/d5e65b8e-7590-4a3b-833a-6f6ea010731d)


![Capture d’écran 2024-10-10 094004](https://github.com/user-attachments/assets/4f33fa72-55ec-445d-8159-9067a72b101f)

**Comment by NEZNAMY** [comment]
TAB is not responsible for making your resource pack map symbols to images. Try another scoreboard plugin to see if it works there.

**Comment by DarkLionQc** [comment]
I found this, it's an expansion using your plug-in + Oraxen( I use oraxen) to work with the glyph but it's not free

https://polymart.org/resource/tab-scoreboard-lpc-amp-luckperms.6371

![Capture d’écran 2024-10-10 101854](https://github.com/user-attachments/assets/9723107d-2ff4-41c0-b2d4-21e4af27048c)

**Comment by NEZNAMY** [comment]
For the third time: try with another scoreboard plugin to see if it works there.

**Comment by NEZNAMY** [comment]
Any news @DarkLionQc ? Does it happen with other scoreboard plugins too?

**Comment by NEZNAMY** [comment]
No response for 3 weeks, assuming user has died. Issue is most likely out of TAB's control.
