### ISSUE TITLE
PlaceholderAPI expansion not downloading

### ISSUE THREAD

**Issue by Fyrezz** [NEZNAMY/TAB#137]
**Server version**
1.8.8

**Plugin version** ("latest" is not a version)
2.7.3

**Describe the bug**
The PlaceholderAPI variables aren't working. The plugin is trying to download PlaceholdeAPI expansion, but fails. I cannot find the expansion in /papi ecloud.

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)
[TAB v2.7.3] Failed to download PlaceholderAPI expansions
19.04.2020 - 02:11:24 - java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.getRegisteredIdentifiers()Ljava/util/Set;
19.04.2020 - 02:11:24 -        at me.neznamy.tab.platforms.bukkit.features.ExpansionDownloader$1$1.run(ExpansionDownloader.java:27)
19.04.2020 - 02:11:24 -        at me.neznamy.tab.shared.CPUManager$3.run(CPUManager.java:79)
19.04.2020 - 02:11:24 -        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.04.2020 - 02:11:24 -        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.04.2020 - 02:11:24 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19.04.2020 - 02:11:24 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19.04.2020 - 02:11:24 -        at java.lang.Thread.run(Thread.java:748)

**Comment by NEZNAMY** [comment]
What is your placeholderapi version ? It's likely very old, update it.
