### ISSUE TITLE
When layout is enabled, skins don't show second layer

### ISSUE THREAD

**Issue by SynaBytez** [NEZNAMY/TAB#1370]
### Server version

1.12.1

### TAB version

4.1.9

### Plugin list

 Paper Plugins: (0):
[21:21:37 INFO]: Bukkit Plugins: (22):
[21:21:37 INFO]:  - AxiomPaper, BeeConomy, CommandPanels, DiscordSRV, DisplayEntityEditor, Essentials, GSit, HeadDatabase, LuckPerms, MiniMOTD
[21:21:37 INFO]:  Multiverse-Core, PlaceholderAPI, ServerBackup, SkBee, Skript, skript-placeholders, skript-reflect, TAB, Tebex, Vault
[21:21:37 INFO]:  WorldEdit, WorldGuard

### Describe the bug

Because what I assume, it's using a skin provider for player skins rather than using the in-game one, the skin provider isn't working right. A lot of them don't right now and only show the first skin layer. You would have to switch to one that shows a second layer too.

### Expected behavior

The skin icons should show both the first and second layer.

### Steps to reproduce

Enable layout and look at your icon

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Unfortunately this is how the game works. For second layer of skin to appear, the tablist entry has to be spawned as an entity. Layout uses fake players to display the tablist and pushes real players away, causing this. It is not fixable from server side.

**Comment by SynaBytez** [comment]
Hmm, so you can't make it so it grabs the icon of the player from a site like the empty slots do?

**Comment by NEZNAMY** [comment]
That would require recoding of the feature, which is not planned.
