### ISSUE TITLE
Trojan trace in TAB  last version Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by CtrlAiDel** [NEZNAMY/TAB#1371]
### Server version

pufferfish 1.21

### TAB version

4.1.9  

### Stack trace

Chrome and edge are deleting the file 4.1.6 was fine

### Additional info

Trojan:Script/Wacatac.B!ml

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://www.spigotmc.org/threads/windows-defender-false-positives.639507/

**Comment by CtrlAiDel** [comment]
Thank you

**Comment by HauserGrim** [comment]
I compiled the plugin from sources (v4 branch) and it has no problems with windows defender:
[tab-my.zip](https://github.com/user-attachments/files/17447252/tab-my.zip)
https://www.virustotal.com/gui/file/c3b3971a1ccce7abec93cb95bddfcbabecfbc621cdcdd8c27f0bd2d07ed493ff
Same as 4.1.8 from releases: https://www.virustotal.com/gui/file/baacd0989e0f1182ddfb9ef6f3563e710a05ff61475cbcbf3162970ebdb9438b
Unlike 4.1.9 from releases: https://www.virustotal.com/gui/file/be3e0459e675fcf93ca7fcacc2044c1711c434c44ffd7a68cd359d924ad18c86

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#18---why-is-the-plugin-flagged-as-a-virus-by-windows-defender

Try compiling 4.1.9 yourself and see.

**Comment by HauserGrim** [comment]
4.1.8, compiled 4.1.9, compiled master do not cause this, only 4.1.9 from releases.
I even decompiled 4.1.9 from the releases and the one I compiled, but decompilied code is the same.
Perhaps there is some minimal difference when building on different systems or jdk.
Either way, I don't think there's any point in wasting time on this.

**Comment by NEZNAMY** [comment]
Correct, there is no point in wasting time on this.
