### ISSUE TITLE
False virus detection(maybe?)

### ISSUE THREAD

**Issue by karu724** [NEZNAMY/TAB#1372]
### Server version

none

### TAB version

4.1.9

### Plugin list

none

### Describe the bug

False virus detection
![image](https://github.com/user-attachments/assets/bec9542c-9d8b-4289-948e-287f4fcd404b)

### Expected behavior

can't download

### Steps to reproduce

just donwloading latest version of tab plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Again? How many more times will I have to answer the same question over and over?
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#18---why-is-the-plugin-flagged-as-a-virus-by-windows-defender

**Comment by karu724** [comment]
sry, thank you :)
