### ISSUE TITLE
Scoreboard placeholders not working with placeholderapi

### ISSUE THREAD

**Issue by luckychampsishere1** [NEZNAMY/TAB#1373]
### TAB version

4.1.9 

### Software causing compatibility issue

So I'm trying to use the tab plugin scoreboard, but when I try to use the placeholders from PlaceHolderAPI the placeholders will not work, I checked the placeholders on the wiki to see if it's right and it is.

![image](https://github.com/user-attachments/assets/71c25c97-af1e-4b7e-baad-831ee7058a0a)

### Checklist

- [X] I am running latest version of the plugin
- [X] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Where is a screenshot of them not working?

**Comment by NEZNAMY** [comment]
No response for a week, assuming user has died. Issue was not described sufficiently. Most likely cause of the described issue is missing PlaceholderAPI or one or more of its expansions.
