### ISSUE TITLE
problem with group, permission syncing.

### ISSUE THREAD

**Issue by 301haru** [NEZNAMY/TAB#1376]
### Server version

Velocity 3.4.0 SNAPSHOT 445

### TAB version

5.0.1

### Plugin list

VelocityScoreboardAPI-1.0.4
voicechat-velocity-2.5.15
LuckPerms-Velocity-5.4.134
TAB.v5.0.1
ajQueue-2.6.0

### Describe the bug

player's group tag prefix/tab prefix only changes immediately with Luckperms ingame commands. But does not supports by the API.

### Expected behavior

tab and tag prefix has to change immediately

### Steps to reproduce

change player's group via API.

```
User user = luckPerms.getUserManager().loadUser(p.getUniqueId(), p.getName()).join();
user.data().clear();
luckPerms.getUserManager().saveUser(user);
```

short example of removing player's group.
It removes player's all data but still player has tag and tab prefixes.
If player rejoins, now TAB knows it has been removed.

### Additional info

It worked fine before in 4.x.x TAB version.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Is that ran on proxy or backend? Is TAB configured to take groups from proxy or backend? Does the old group show in `/btab debug <player>` and does the correct one show in `/lpv user <player> info` ?

**Comment by 301haru** [comment]
TAB runs on proxy. API runs on backend. TAB is in proxy so it should take groups from proxy by luckperms velocity plugin.
and yes old group shows on /btab and correct one on /lp

**Comment by 301haru** [comment]
and if I do /lp user <player> info

after a few seconds, now TAB knows the correct group. /btab shows the correct group.

**Comment by NEZNAMY** [comment]
What you just described is caused by incorrect LP synchronization. Explore messaging-service option in LP config.

**Comment by 301haru** [comment]
I've looked into the config so I tried /lp sync, but TAB still does not know the group.

**Comment by NEZNAMY** [comment]
You need to change a config option, not run a command.

**Comment by 301haru** [comment]
I would like to say there was no problem with TAB version 4.
Same system but upgraded TAB 4 to 5, added VelocityScoreboardAPI, updated velcocity 3.3.0 to 3.4.0

**Comment by NEZNAMY** [comment]
There were no changes to LP hook between the versions.

**Comment by 301haru** [comment]
Okay. then it's pretty weird why it worked in past version because I really did not changed anything beside those.
/lp networksync worked. Thanks for letting me know about the config.
