### ISSUE TITLE
the problem with abovenames

### ISSUE THREAD

**Issue by WelPanBit** [NEZNAMY/TAB#1377]
### Server version

pufferfish 1.21.1

### TAB version

5.0.1

### Plugin list

-

### Describe the bug

after switching to a newer version, `abovename` stopped working through the output command also does not work

### Expected behavior

The text should appear above the player

### Steps to reproduce

Step 1: write the command `/tab group _DEFAULT_ abovename %townyadvanced_town_unformatted%`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Have you been living under a rock? In the past months your console was screaming at you that the feature is getting removed, so did several update changelogs, as well as 5.0.0 changelogs.

**Comment by WelPanBit** [comment]
Maybe the alerts were turned off, so what should I do with this problem?

**Comment by NEZNAMY** [comment]
https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c#what-can-you-do

**Comment by WelPanBit** [comment]
The problem is solved
