### ISSUE TITLE
Sorting players in tablist not working on Velocity

### ISSUE THREAD

**Issue by BAD7777** [NEZNAMY/TAB#1378]
### Server version

Velocity 3.4.0-SNAPSHOT (git-de3f1bcc)

### TAB version

5.0.1

### Plugin list

TAB - Bridge 6.0.0 (on Purpur 1.21.1)
TAB - Velocity 5.0.1

### Describe the bug

Using TAB - Bridge 6.0.0 and TAB - Velocity 5.0.1, players are not sorted by groups in the tablist. The plugins do not function as expected and fail to sort players properly.

### Expected behavior

Players should be sorted by groups in the tablist, as it works with previous plugin versions.

### Steps to reproduce

1. Install TAB - Bridge 6.0.0 and TAB - Velocity 5.0.1.
2. Start the server with these plugins enabled.
3. Check the tablist to see if players are sorted by groups.

### Additional info

When downgrading to TAB - Bridge 5.0.7 and TAB - Velocity 4.1.9, sorting works as intended.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Open your console and read what it says.
