### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Martin-Hausleitner** [NEZNAMY/TAB#138]
Should I translate the plugin into German

**Comment by NEZNAMY** [comment]
Not needed, people don't really need to translate the plugin as those messages are sent to staff members configuring the plugin.

**Comment by Martin-Hausleitner** [comment]
But it looks professional.
And the No Perm message still gets through to the regular players. I think a lot of people would be happy to have a translation that you can download.

**Comment by NEZNAMY** [comment]
That's one message. How would they download it ? Doing this would likely make it even more complicated instead of simplifying.

**Comment by Martin-Hausleitner** [comment]
Well you could just make a folder in Github with the languages.The plugin looks better when there are translations?

**Comment by NEZNAMY** [comment]
It's just one message. Everyone is able to translate the message themselves, it's not hard. Choosing language or downloading translated file would be harder than doing it manually.

**Comment by Martin-Hausleitner** [comment]
i think its way easier to copy and paste the right lang?

**Comment by Martin-Hausleitner** [comment]
if in in the spigot article is a lang section it is easier for everyone

**Comment by NEZNAMY** [comment]
This would be good if we had at least 5 languages, idk if i want to go into this. Also spigot page only has the most important info, this would have to go to wiki which nearly no one reads and those who do are able to do it themselves.

**Comment by Martin-Hausleitner** [comment]
langs are important?

**Comment by NEZNAMY** [comment]
The only message from translations.yml visible to players is the no-perm one, which is not enough to do all of this. If you're talking about config.yml, it's more like preset configs than translation.

**Comment by DrWurzeli** [comment]
@Martin-Hausleitner feel free to upload your german-preset for translations.yml on the official TAB discord server. we have a dedicated preset-configs channel for presets there.
We already provide support in Ger/Fr/Sk/Cz/Nl/Es/En and so far there hasnt been a translation problem as all of the messages are really easy to understand and most people dont use commands anyway.
