### ISSUE TITLE
Tab does not update Primary Group when you give another group to a player

### ISSUE THREAD

**Issue by kot9kas** [NEZNAMY/TAB#1381]
### Server version

NullCordX 1.21

### TAB version

4.1.7

### Plugin list

LuckPerms, plasmovoice, Skinrestorer, TAB

### Describe the bug

When you give a player a higher or lower group, he stays in the same place in the tab and changes only the prefix.

### Expected behavior

When you give a player a higher or lower group, he should change his place in the tab according to the priority of groups

### Steps to reproduce

1. \1. Go to the server
2. Grant a player in the group
3. See that the place where he was has not changed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
On which marketplace is 4.1.7 latest? Does the group update in `/btab debug <player>`?

**Comment by CCjun6** [comment]
Server version: Purpur 1.21.1
TAB version: 5.0.1
TAB-Bridge version: 6.0.0

I installed TAB on Velocity and configured the sorting-types option. It does work in the game, but the list doesn't update in real-time. It only updates the prefix. Let me give you an example:
For two permission groups, A and B, TAB correctly sorts A first and B second. However, when B advances to group A through another method, the list order does not change. Only the prefix changes. I have changed many options in the configuration file, but none of them take effect. Is this a bug, or have I not configured the correct options?

**Comment by CCjun6** [comment]
> On which marketplace is 4.1.7 latest? Does the group update in `/btab debug <player>`?

The group order only updates correctly when the player logs out and re-enters the game. I want to know how to fix this.

**Comment by NEZNAMY** [comment]
Change messaging-service option in LP config to plugin messages and see if that fixes it.

**Comment by NEZNAMY** [comment]
So how is that a TAB bug? And are you related to the author of this issue?

**Comment by CCjun6** [comment]
No, I don't know him. I just happened to encounter this issue because it has never occurred before.

**Comment by CCjun6** [comment]
> No, I don't know him. I just happened to encounter this issue because it has never occurred before.

No, I don't know him. I just happened to encounter this issue because it has never occurred before.
