### ISSUE TITLE
scoreboard getting empty

### ISSUE THREAD

**Issue by tanzbr** [NEZNAMY/TAB#1389]
### Server version

Velocity 3.4.0-SNAPSHOT-451 and Pupur 1.20.1

### TAB version

5.0.3

### Plugin list

![image](https://github.com/user-attachments/assets/badb7d7b-87b4-4565-876e-0ea3fb98cf9f)
![image](https://github.com/user-attachments/assets/b7a90644-3d91-4967-b108-8918604d4e53)

### Describe the bug

when using the newer version of tab + velocityscoreboardapi, when changing servers the scoreboard gets empty

### Expected behavior

scoreboard should keep normal

### Steps to reproduce

1. Setup TAB on Velocity and Tab-Bridge in 1.20.1 servers
2. Change from servers
3. Look at the scoreboard

### Additional info

https://github.com/user-attachments/assets/6f6e002e-97f0-4a81-bca8-67bc80fdf29b

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by tanzbr** [comment]
I forgot to say, but the problem only happens if the client is on 1.21, on 1.20.1 it doesn't happen

**Comment by NEZNAMY** [comment]
Try with vanilla client.

**Comment by tanzbr** [comment]
Ok, I will try

**Comment by tanzbr** [comment]
Sorry for the delay, as my server is in production I need to wait for the next proxy restart to test, because I went back to 5.0.0 version where the problem does not exist. When I can test it I will send the result here ;)

**Comment by DopiGFX** [comment]
Can confirm -> 
1.21 Velocity -> Tab v5.0.2
1.21.3 Backend Servers -> TabBridge v6.0.0

When joining initially, the scoreboard is displayed, but after switchtig servers it's empty except the headline

**Comment by tanzbr** [comment]
I tested it with vanilla client and it really seems to be a launcher problem, I thought it could be something in the TAB because it works in older versions, I'll try to contact the launcher developers, thanks for the help!
