### ISSUE TITLE
Support for HaoNick

### ISSUE THREAD

**Issue by Bensonheimer992** [NEZNAMY/TAB#1390]
### TAB version

5.0.2

### Software causing compatibility issue

[HaoNick](https://www.spigotmc.org/resources/haonick-advanced-nick-plugin-1-8-1-20.81108/)

### Additional info

Please add Support so that the weight of the Fake Rank does something weight 99 is the lowest and 0 the highest

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Insufficient info. Did you read https://github.com/NEZNAMY/TAB/wiki/How-to-display-name-from-nickname-plugins ?

**Comment by Bensonheimer992** [comment]
Ive ready IT the Problem im having is that a Player that the Player has the fakerank Player But is listed above Mod because my real Rank is owner

**Comment by NEZNAMY** [comment]
Is the "fakerank" recognized by luckperms? Does it show in `/tab debug <player>` or does it display the supposedly wrong one?

**Comment by Bensonheimer992** [comment]
What was the Command again in Velocity?

**Comment by NEZNAMY** [comment]
/btab? Why don't you open the wiki since you're already on github?

**Comment by Bensonheimer992** [comment]
![grafik](https://github.com/user-attachments/assets/9a601b7b-5b17-41ec-9dd3-0a876d6f3c5a)

**Comment by NEZNAMY** [comment]
Says primary group `owner`. Is the player supposed to be in owner group? Is that correct?

**Comment by Bensonheimer992** [comment]
Im nicked my real rank is owner but my fakerank should be player

**Comment by Bensonheimer992** [comment]
the haonick plugin uses the [NickAPI Plugin](https://www.spigotmc.org/resources/nickapi-1-8-8-1-20-2-1-21.26013/)

**Comment by NEZNAMY** [comment]
Vault said your group is owner. Do you have LuckPerms?  What does `/lp user <player with fakerank> info` show?

**Comment by Bensonheimer992** [comment]
it says owner as the group

**Comment by NEZNAMY** [comment]
In that case you are reporting the issue in the wrong repository. If LuckPerms says you are owner while you are not supposed to be, it is not a TAB bug.

**Comment by Bensonheimer992** [comment]
I didn't mean to say it was a bug. I wanted to ask if you can implement the Nick API so that the weights work properly

**Comment by NEZNAMY** [comment]
No, I will not be replacing permission hook to use that nick plugin. Configure it to change groups in LP and TAB will take it from there.

**Comment by Bensonheimer992** [comment]
I have now made my own nick plugin which changes the prefix in Luckperms and that works but it also adds a weight node but the player who is the owner and has the weight 0 is still displayed with the other owners (Deepl)

**Comment by NEZNAMY** [comment]
TAB takes groups from LuckPerms, unless using permissions. How is any of this a TAB issue?

**Comment by Bensonheimer992** [comment]
My Problem is that i want to have the nicked users show as normal Players but the still have their perms so i add a weight node to the users when the get nicked but the still show up higher in the tab list as the should

**Comment by NEZNAMY** [comment]
Check `/tab debug <player>`. Does it show the expected group assigned or not?

**Comment by NEZNAMY** [comment]
Can we get this resolved already @Bensonheimer992 ? It's not a TAB bug.
