### ISSUE TITLE
prevent-spectator-effect problem

### ISSUE THREAD

**Issue by smscentras** [NEZNAMY/TAB#1391]
### Server version

Purpur 1.21.1

### TAB version

5.0.3

### Plugin list

ALL world plugin

### Describe the bug

Not working at all:
```
prevent-spectator-effect:
  enabled: true
```

### Expected behavior

plugin must to show player in spectator mode - like normal mode. But player go to the end of list and half hidden in TABlist.

### Steps to reproduce

in config set
```
prevent-spectator-effect:
  enabled: true
```
/gm 3

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you are NOT looking at yourself in the tablist, but others?

**Comment by smscentras** [comment]
My fault, thank you.

**Comment by smscentras** [comment]
My fault, thank you.

**Comment by smscentras** [comment]
My fault, thank you.
