### ISSUE TITLE
Tamed pets that are renamed with a nametag - have problem

### ISSUE THREAD

**Issue by smscentras** [NEZNAMY/TAB#1392]
### Server version

Purpur 1.21.1

### TAB version

5.0.3

### Plugin list

CMI, *all

### Describe the bug

Tamed pets that are renamed with a nametag, have strange bug with additional text - but only when pet owner **nearby**.
All players can see pet name with [vip]: **[vip] PetName**
When the pet owner is away, this thing is normal. All players see pet name only, without [vip]

### Expected behavior

Tamed pets must show allways same - PetName only, without [vip]

### Steps to reproduce

Player must have [vip] privilege.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by smscentras** [comment]
In example: Cat, Wolf

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-2---prefixsuffix-on-pets

**Comment by smscentras** [comment]
Thank you, i will try.
