### ISSUE TITLE
The spaces at Header and Footer of each line will be ignored

### ISSUE THREAD

**Issue by bbz-233** [NEZNAMY/TAB#1393]
### Server version

Paper 1.21.1-132 / Leaves 1.21.1-81

### TAB version

5.0.3

### Plugin list

Server Plugins (1):
Bukkit Plugins:
- TAB

### Describe the bug

The spaces at Header and Footer of each line will be ignored
![image](https://github.com/user-attachments/assets/077d54fe-09af-4339-a0e1-157c48507e59)

### Expected behavior

These spaces with strikethrough should have been displayed

### Steps to reproduce

Install Paper/Leaves server core
Install tab plugin
launch server
Enter the game
Press tab to display the player list

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you didn't delete them from your config? Send it.

**Comment by bbz-233** [comment]
It's interesting that if I modify the configuration like this, the '&' before 'm' will be ignored when displayed
```
header:
    - "<#FFFFFF>&m                                                &m</#FFFF00>"
    - "&3&lServer name"
    - "&7&l>> %animation:Welcome%&3 &l%player%&7&l! &7&l<<"
    - "&7Online players: &f%online%"
    - "&6Online staff: &e%staffonline%"
    - ""
  footer:
    - "%animation:time%"
    - "&2Ping: %ping%"
    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "&7Visit our webpage %animation:web%"
    - "<#FFFFFF>&m                                                &m</#FFFF00>"
```
![image](https://github.com/user-attachments/assets/900babf3-1e57-41b1-8d9e-a194a14ab73f)

**Comment by NEZNAMY** [comment]
Yes, magic codes inside gradients are processed "lazily" to keep the code simple and still fulfill the purpose. You just used something that's not supported.

**Comment by bbz-233** [comment]
So how can I make these spaces with strikethrough lines appear
