### ISSUE TITLE
Sorting and nametags not working on 1.21.4

### ISSUE THREAD

**Issue by DarkKingKaan** [NEZNAMY/TAB#1395]
### Server version

Velocity 1.21.4

### TAB version

5.0.3

### Plugin list

Velocity:
analyse, luckperms, limboapi, vpacketevents, fastlogin, authmevelocity, botsentry, cvetka, infinityfilter, limboreconnect, minimotd-velocity, nuvotifier, premiumvanish, protocolize, signedvelocity, skinsrestorer, snap, spark, velocity-scoreboard-api, tab, tebex, triton, uarvp, ultrastaffchatpro, vroyalutils, vulcan

Paper/backend:
AdvancedPortals, AdventCalendar, ajLeaderboards, AnimatedScoreboard, AntiWorldFly, BottledExp, BuycraftX, ChatInjector, ChatSentry, ChestShop Chunky, Citizens, CleanroomGenerator, CMILib, CombatLogRM, CoreProtect, CrateReloaded, DecentHolograms, DeluxeMentions, Essentials EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExtraCrates, FreedomChat, Gender, GPFlags, GravesX, GriefPrevention GSit, Harbor, HeadDatabase, HubParkour, InteractionVisualizer, InventoryRollbackPlus, ItemRecycler, Jobs, KixsChatGames, LiteBans LobbyGames, LuckPerms, MobFarmManager, Multiverse-Core, OtherAnimalTeleport, PlaceholderAPI, PlayerPoints, PlayerWarps, PremiumVanish, PreventStabby ProtocolLib, RandomTeleport, RestrictedCreative, RewardsLite, RoyalUtils, ShopGUIPlus, ShopGUIPlus-SellGUI, ShopGUIPlusSilkSpawnersBridge, ShowItem, SilkSpawners SmoothTimber, SuperLuckyBlock, TAB-Bridge, TempFly, TheCore, Triton, UltimateAutoRestart, *UnbreakableAnvils, Vault, ViaVersion VillagerNerfer, VoteRewards, Votifier, Vulcan, VulcanDatabase, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3, zMenu

### Describe the bug

After updating to plugin version 5.0.3, the sorting is messed up and the nametags are not working for players on 1.21.4.
Everything works fine for people playing on lower version(s).

![4bS2Ivy](https://github.com/user-attachments/assets/7dd3948e-740e-4a7e-bbb2-3fafc6d2c51b)
![7TkmqCb](https://github.com/user-attachments/assets/7396dca8-0006-44c4-9588-09271c6d0d49)

### Expected behavior

It should look like this, as it does for players playing on lower versions.

**1.21.3** and lower
![image (1)](https://github.com/user-attachments/assets/b3352939-990e-4105-a52f-342dd86a75a5)
![image](https://github.com/user-attachments/assets/465a5de0-47f0-4799-bc6a-c632c6f4ec63)

### Steps to reproduce

Run the plugin on a lower version (1.21.1), then join on a higher version (1.21.4).

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
obviously, 5.0.2 was released before 1.21.4 and therefore didn't support it. Update to 5.0.3

**Comment by NEZNAMY** [comment]
You said you have TAB on paper, but your plugin list only contains TAB-Bridge. Could it be that you have TAB on velocity? With VelocityScoreboardAPI version 1.0.5, which does not support 1.21.4, because support for it was added in 1.0.6?

**Comment by DarkKingKaan** [comment]
Whoops, my bad. The plugin version is 5.0.3. running on Velocity.

I do not use VelocityScoreboardAPI.

**Comment by Tanguygab** [comment]
Wrong version and wrong server software...? 
welp, you've got your answer once again, you're missing VSAPI

**Comment by DarkKingKaan** [comment]
Interesting, I'll take a look. Thanks.

**Comment by NEZNAMY** [comment]
Didn't you get any console warning about this?

**Comment by DarkKingKaan** [comment]
None at all. The sorting and nametags worked just fine for me after 5.0.0. It only "broke" after the last update.

**Comment by NEZNAMY** [comment]
Can you share your proxy log? I want to see that.

**Comment by DarkKingKaan** [comment]
Oh, nevermind, I see it now. I guess I didn't pay enough attention. I've updated VSAPI now.

Thanks for the help.

**Comment by NEZNAMY** [comment]
What? That's it? It wasn't a TAB bug, was it? What can I do to prevent false bug reports like these to be open in the future?

**Comment by DarkKingKaan** [comment]
I highly doubt that you will ever prevent them. The best you can do is gently point people like me in the right direction, which you did and now the issue is resolved.

It was my mistake, because I didn't read the Wiki thoroughly. I just assumed how it should work based on my experience and forgot to check the update logs.

**Comment by NEZNAMY** [comment]
That's truly unfortunate. Looks like I'll keep getting false bug reports every day for the rest of eternity. Is there really no hope left in this world?

**Comment by willywhite0** [comment]
Hello,
I have the exact same problem. I am also using Velocity Build 454. The servers are on Paper Version 1.21.1. I have the TAB Bridge Version 6.0.0 installed on every server (except the Velocity). Also I have VelocityScoreboardAPI Version 1.0.6 installed on Velocity.

When I join there are only white nametags above the players and the sorting in the tablist is broken. When I reload the plugin with /btab reload, everything is normal. Just until I leave and join again, then all nametags and sorting is broken again. I tested this without any other plugins. I don't get any error messages or anything in the logs.

**Comment by NEZNAMY** [comment]
> Hello, I have the exact same problem. I am also using Velocity Build 454. The servers are on Paper Version 1.21.1. I have the TAB Bridge Version 6.0.0 installed on every server (except the Velocity). Also I have VelocityScoreboardAPI Version 1.0.6 installed on Velocity.
> 
> When I join there are only white nametags above the players and the sorting in the tablist is broken. When I reload the plugin with /btab reload, everything is normal. Just until I leave and join again, then all nametags and sorting is broken again. I tested this without any other plugins. I don't get any error messages or anything in the logs.

Open a new issue and provide steps to reproduce (preferably working ones).
