### ISSUE TITLE
Sorting and nametag not working

### ISSUE THREAD

**Issue by willywhite0** [NEZNAMY/TAB#1396]
### Server version

Velocity Build #454

### TAB version

5.0.3

### Plugin list

I deactivated all plugins on Velocity and the Paper Plugins. It was still not working.

### Describe the bug

When you join, all nametags above the player are white and the sorting in the tablist is not working. If you run /btab reload everything works until another person is joining the server.

![{E74A347E-A9E5-43F0-A8AA-FBFC03B0591E}](https://github.com/user-attachments/assets/1b002fc6-64ca-4bc4-8df1-fec3b5b9f63f)
Before /btab reload

![{2CAA0DD7-9DFF-41C6-8BE4-E5D6C356278E}](https://github.com/user-attachments/assets/95f76646-61b0-4a5e-9a0c-6a51b0708f31)
After /btab reload

### Expected behavior

All nametags should have a prefix and the sorting should work properly.

### Steps to reproduce

Step 1: Setup up Velocity Build 454 with following plugins: TAB 5.0.3, Velocity Scoreboard API Version 1.0.6, LuckPerms Version 5,4.149
Step 2: Add a Paper Server Version 1.21.1 Build 132 with TAB-Bridge 6.0.0 and LuckPerms Version 5.4.146
Step 3: Add a prefix to the default group
Step 4: Rejoin with 1.21.1 and see, that the nametag is white
Step 5: Do /btab reload and see that your nametag is working again

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by willywhite0** [comment]
You are absolutely right. That just happens when using LabyMod. So its a bug, that you cannot fix?

**Comment by NEZNAMY** [comment]
No, I am not LabyMod developer, as you may have probably guessed already.

**Comment by willywhite0** [comment]
[18:43:00]	[fzg] Received packet for unknown team 0willywhiteA: team action: REMOVE, player action: null

Thats in the Log of the client. Nothing to do with tab, or?

**Comment by NEZNAMY** [comment]
It actually is related to TAB. Is this in vanilla client? Have you noticed it causing any problems? These issues are kinda hard to reproduce and fix, so I prefer to only go into these with people dedicated to resolve it.

**Comment by willywhite0** [comment]
[19:04:00] [Render thread/WARN]: Received packet for unknown team 0willywhiteA: team action: REMOVE, player action: null

Thats reproduced in the vanilla client. I can't see any problems. But you cant see your own nametag in vanilla, so that could be not working properly.

**Comment by willywhite0** [comment]
![{699D35CF-19EF-4E23-A778-8FEA95B83D61}](https://github.com/user-attachments/assets/24ce3642-f21a-4fb2-9e14-9c2c8f795cd6)
Disabled the tablis name formatting and reloaded

**Comment by NEZNAMY** [comment]
Reconnected too? Can you show output of `/btab debug <player>` to confirm the expected result?

**Comment by willywhite0** [comment]
![{7809AFF0-40F8-43DE-B46F-F52832CB2C96}](https://github.com/user-attachments/assets/037e0842-82ca-444b-aa9c-67c66e5aee37)
I did not reconnect

**Comment by NEZNAMY** [comment]
Can you reconnect then? Also `/btab parse me %luckperms-prefix%`.

**Comment by willywhite0** [comment]
Oh wow. I disabled the tablis-name-formatting and now it has the exact same behavior as using LabyMod and going to the thrid person view...

**Comment by willywhite0** [comment]
![{8270CD1F-7FA8-4A21-A2E4-3473496E7457}](https://github.com/user-attachments/assets/e63355e9-9938-4495-a374-d2811406c769)
Reconnected and its still a white nametag in Tablist

**Comment by willywhite0** [comment]
I dont have a second account... Is it possible to connect with the exact same account to the same proxy?

**Comment by NEZNAMY** [comment]
Use a cracked client then.

**Comment by willywhite0** [comment]
![{BD3A55B2-C088-4F37-B39D-FAC6DF3E40E8}](https://github.com/user-attachments/assets/043d305e-3c62-4fa8-af7c-f078d2b96099)

**Comment by NEZNAMY** [comment]
Can you send your proxy log?

**Comment by willywhite0** [comment]
Can I send it to you privately? I dont want to share confidential information

**Comment by NEZNAMY** [comment]
Log from a fresh velocity installation that only contains plugins you listed in your first message does not contain any confidential information.

**Comment by willywhite0** [comment]
Its working there.....

**Comment by NEZNAMY** [comment]
It was kinda expected of you to write steps describing your situation. Now you can find out which other plugin is causing it.

**Comment by willywhite0** [comment]
After a complete restart of Velocity and the Paper server its working properly again, without disabling other plugins

**Comment by NEZNAMY** [comment]
So what now?

**Comment by willywhite0** [comment]
Could be a temporary bug?

**Comment by NEZNAMY** [comment]
What is that?

**Comment by DenLede** [comment]
I'm getting the same thing for the tablist I'm using the 5.0.3 too Is there any configuration for it or Its a bug ?
![Screenshot_11](https://github.com/user-attachments/assets/324b0828-5423-4302-be9a-998f914f1c42)
When I reload it It becomes normal but When someone joins , like he said 
tag goes default Until the world or group change

**Comment by DenLede** [comment]
Steps to reproduce
Step 1: Setup up CraftBukkit-Spigot 1.8.8-R0.1 with following plugins: TAB 5.0.3 , GroupManager v2.1.31
Step 2: add a prefix to the any group that you have
Step 3: join to server with 1.8 as default version to see If Its working
Step 4: use the /tab reload then It must be working

**Comment by NEZNAMY** [comment]
> Steps to reproduce Step 1: Setup up CraftBukkit-Spigot 1.8.8-R0.1 with following plugins: TAB 5.0.3 , GroupManager v2.1.31 Step 2: add a prefix to the any group that you have Step 3: join to server with 1.8 as default version to see If Its working Step 4: use the /tab reload then It needs to be working
> 
> * I was working on groupmanager before so I kept it (Its not supported as I know from your other threads of github maybe caused of that)
> 
> Maybe the versions are old for groupmanager I don't know don't blame me for it I'll try to update all :c
> 
> Thanks for giving time to look

[Unable to reproduce](https://youtu.be/zNaQHaFnZDk). GroupManager is not supported directly, you must have Vault installed for GroupManager groups to work. Either way I used `_DEFAULT_` in my example, so it doesn't matter there. Check group using `/tab debug <player>`.

**Comment by DenLede** [comment]
Now There's a thing, I'm using different tags on chat and tablist

for example 
on chat the newbie rank prefix is 
- xnewbie

on tablist
newbie12342432

when I add the vault prefix to tablist 
![Screenshot_16](https://github.com/user-attachments/assets/5b8861b6-172d-480c-95bd-c9703a29b664)


I shows up the buggy 
"xnewbie" at the tablist which is needs to be only in chat, when I reload the plugin or someone changes world It changes to the tab plugin's group prefix "newbie12342432"


![Screenshot_17](https://github.com/user-attachments/assets/0f40fa35-c122-49c6-93d9-8b8e36fbbe7f)

**Comment by NEZNAMY** [comment]
What exactly is your client version? 1.8 or 1.8.1+? You are trying to use more than 16 characters, so even if you updated your client to the version with the bug not displaying tablist names properly fixed, nametag would still have the same issue.

**Comment by DenLede** [comment]
My Own Client is 1.8.9
I've used vanilla minecraft 1.8 
and game version at the screen shot is 1.8_Optifine_HD_U_I7

**Comment by NEZNAMY** [comment]
That doesn't make sense. Client and game are the same thing. You are using either 1.8.9 or 1.8. Try vanilla 1.8.9.

**Comment by DenLede** [comment]
wth, the 1.8.9 vanilla fixed the thing but my client is 1.8.9 too seems buggy

**Comment by DenLede** [comment]
Thank you for all that you're really good person, fixed.

**Comment by NEZNAMY** [comment]
I didn't fix anything. I still don't know what the TAB bug you reported is.

**Comment by DenLede** [comment]
the bug I said was that (I didn't know If Its a bug or thing);
- different prefixes
- character limits for 1.8
and as you said mojang did it in 1.8.1

**Comment by NEZNAMY** [comment]
In the future please refrain from reporting minecraft bugs that were fixed a decade ago on TAB repository.

**Comment by DenLede** [comment]
Sorry about that, I wasn't know thats a issue from TAB or Mojang I just searched along the way and saw that post having same issue, have a good day.

**Comment by NEZNAMY** [comment]
@willywhite0 try latest build of VSAPI from https://github.com/NEZNAMY/VelocityScoreboardAPI/actions

**Comment by willywhite0** [comment]
Yes its working again. Thanks
