### ISSUE TITLE
Will this ever be included in NeoForge?

### ISSUE THREAD

**Issue by Spontini** [NEZNAMY/TAB#1397]
### TAB version

9.9.9

### Software causing compatibility issue

-

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
This is an issue tracker. I have no experience with forge and therefore no plans.
