### ISSUE TITLE
MiniMessage TranslatableComponent not detecting player's locale

### ISSUE THREAD

**Issue by AnleaR** [NEZNAMY/TAB#1399]
### Server version

Paper 1.20.4

### TAB version

5.0.3

### Plugin list

I think it doesn't matter in this bug.

### Describe the bug

When I'm trying to use TranslatableComponents from MiniMessage in TAB, plugin transforms components only into English locale.

### Expected behavior

The plugin must take into account the localization of the player. Or rather, to support TranslatableComponent from MiniMessage.

### Steps to reproduce

Step 1: place in any scoreboard line this text <lang:entity.minecraft.chicken>
Step 2: reload the plugin
Step 3: select any language except English

### Additional info

Screenshot: https://imgur.com/a/Umw7aDo

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by AnleaR** [comment]
> TAB does not support translatable components. That's not a bug.

I read FAQ and I know this. May be I selected wrong category for this issue?
I want to make TranslatableComponents work in TAB. Can I contribute to solve this issue?

**Comment by NEZNAMY** [comment]
![image](https://github.com/user-attachments/assets/d4d120c7-150d-414d-80a8-bc6f363a1f10)
Your request would require a large amount of changes, so I don't recommend trying to add it yourself.

**Comment by AnleaR** [comment]
Simple MiniMessage support already includes TranslatableComponents. I don't think it will be difficult to implement.
Okay, can you transfer my issue into Feature Requests?
