### ISSUE TITLE
Remove [] from tab/tag if condition. help to Simpleclans

### ISSUE THREAD

**Issue by comonier** [NEZNAMY/TAB#14]
Hello in another plugin called ultimatechat [chat plugin] there is an option to remove certain strings from the chat, to avoid the simple brackets appearing in simpleclan if the player has no clan. Like u can see on [] comonier example

![image](https://user-images.githubusercontent.com/19571541/62995365-993e0200-be36-11e9-8b22-bab63ebdd522.png)

It's just an idea, but it would be super interesting to have this tab / tag option after all your plugin is the best plugin in the world. With this option would be even better!

Below I have favored to copy and paste the config from another plugin that removes these characters from chat so you have an idea to adapt in TAB Reborn config:

# # Remove this from chat (like empty tags)
#   remove-from-chat:
#   - '[]'
#  - '&7[]'
#   - '&7[&7]'

**Comment by NEZNAMY** [comment]
Check 2.5.1-pre10 from discord.

**Comment by comonier** [comment]
its working fine ty so muth

**Comment by NEZNAMY** [comment]
Don't close, i will close it once 2.5.1 comes out.
