### ISSUE TITLE
BetterRanks ItemsAdder Support doesn't work

### ISSUE THREAD

**Issue by getSono** [NEZNAMY/TAB#1402]
### TAB version

5.0.3

### Software causing compatibility issue

ItemsAdder

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
You forgot to describe your issue.
Is it https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#12---how-can-i-display-itemsadder-images ?

**Comment by getSono** [comment]
Thanks!

**Comment by NEZNAMY** [comment]
What?
