### ISSUE TITLE
Tablist not ordered

### ISSUE THREAD

**Issue by Heliosard** [NEZNAMY/TAB#141]
**Server version**
Paperclip: git-Paper-201 (MC: 1.15.2)
Travertine: Build#135

**Plugin version**
2.7.4 (premium)

**Describe the bug**
I use the "bukkit-bridge" mode to share the tablist between several servers of the same group (like hubs) and simplify the management of the scoreboards.
To order the display of the tablist, I configured the bungeecord this way:

```
sorting-type: GROUPS
```

```
group-sorting-priority-list:
  - "youtuber"
  - "founder"
  - "admin"
  - "developer"
  - "moderator"
  - "helper"
  - "member"
  - "mvp+"
  - "mvp"
  - "vip+"
  - "vip"
  - "default"
```

But, the tab is not orderly, as the screen shows.

![image](https://user-images.githubusercontent.com/31409151/80084963-e2af2700-8557-11ea-84de-d651ddadf132.png)

Thanks for your help,

**Comment by NEZNAMY** [comment]
You probably screwed up weights. This is why you should ask for help first. If sorting didn't work there would be many more complaints than just one.

**Comment by Heliosard** [comment]
Before

![image](https://user-images.githubusercontent.com/31409151/80122907-7a2f6c80-858e-11ea-9fe6-60ed068f194a.png)

After a `/btab reload`

![image](https://user-images.githubusercontent.com/31409151/80122952-87e4f200-858e-11ea-92f4-eb08e6c4ba58.png)
