### ISSUE TITLE
Prefix TAB still white even when assigned group

### ISSUE THREAD

**Issue by jxckgreen** [NEZNAMY/TAB#144]
**Server version**
Spigot 1.14

**Plugin version** ("latest" is not a version)
v2.7.4

**Describe the bug**
Users TAB prefix is still white when added to new groups. (Owner and Admin work fine)

**How to reproduce**
/nte group add MVP
/nte group MVP permission nte.mvp
/nte group MVP prefix '&d&lMVP '
/lp group MVP permission set nte.mvp
/lp user USER parent set MVP
/nte reload

**Expected behavior**
Once the user is added to a group it should have changed their prefix in TAB as it did for groups OWNER and ADMIN

**Actual behavior**
Once the player is added to the new group the player doesn't display the prefix in tab and the username just stays white

**Additional info** (errors, screenshots, ...)
![issue](https://user-images.githubusercontent.com/63876752/80262404-3bc8a900-8685-11ea-88d7-d962c07d4cd8.png)

![issue2](https://user-images.githubusercontent.com/63876752/80262411-3ff4c680-8685-11ea-88e3-3036aa01fd3d.png)

**Comment by NEZNAMY** [comment]
Wrong plugin. This is not nametagedit. This plugin replaces nte entirely.
