### ISSUE TITLE
Only 2 groups work in TABlist

### ISSUE THREAD

**Issue by AymerickA** [NEZNAMY/TAB#147]
**Server version**
Travertine (Fork bungeecord) 1.7-1.15

**Plugin version** ("latest" is not a version)
2.7.3

**Describe the bug**
Only 2 groups work in the TABlist

**How to reproduce**
Use /btab reload and see the tab

**Expected behavior**
Group Creator and Master work

**Additional info** (errors, screenshots, ...)
config.yml : https://framabin.org/p/?a0ad7248c8b4f2f8#geMRzYbEnNzeyaRodON8ozu+do66q4tMRxOLMf/Ug9E=

errors.yml : https://framabin.org/p/?ead11cc7dfc03a2c#rqz+JjCC1E7jjjWuTYLKRI8IfXRqGiv8FCD6d73bHZw=

And a question, how to only use tab function, because i don't want use nametag on players, thanks.

**Comment by Tanguygab** [comment]
Can you try to delete the `errors.txt` file, do `/btab reload` and send the file again ?
Also you're using 2.7.3 while latest version is 2.7.4 so you may want to update.

**Comment by AymerickA** [comment]
The new errors.yml : https://framabin.org/p/?4d2b6e089f88b2de#JNzAKyz+b5sEFi6/gr5EEp/HOqksxpsfkeuBWNL2Tus=

I have successfully make group on tab, i have needed to set a weight on luckperms groups (but for a reason i don't know master and creator with no weight have work) Add this information in wiki if possible

**Comment by Tanguygab** [comment]
yeah the weights are needed to get assigned to the right group, creator has probably worked because c is before d from default, but I have no idea for master x)

and for the error, I have no idea why it's spamming, maybe NEZNAMY will know

**Comment by AymerickA** [comment]
Ok thanks for your reply.

Just how to desactivate nametag function, but keep the tier function in "change-nametag-prefix-suffix"

**Comment by Tanguygab** [comment]
if you want another plugin to override the nametags, then that's not possible without disabling `change-nametag-prefix-suffix`
and since it will break your sorting, I guess you wouldn't want to disable it. but You can remove the properties from the Groups and Users section though if you just want to not display anything

**Comment by AymerickA** [comment]
I have try that : 
change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true

  master:
    tabprefix: '§6'

And yes that work, but i explain the problem to not can't desactive nametag function.
I have a practice and when a player fighting an other player, the other player was normally in red, and with your plugin is naturally in &f or &7 if i configure.

and

  master:
    tabprefix: '§6'

**Comment by Tanguygab** [comment]
I understood that, but there's no way to do it except if your pvp plugin has placeholders for PlaceholderAPI and that you could use in TAB to change the player name's color, else you can't

**Comment by AymerickA** [comment]
Okay thanks

**Comment by NEZNAMY** [comment]
You can only have one nametag plugin active at a time. Can this be closed as simple assistance request instead of a bug report ? Except the error.

**Comment by AymerickA** [comment]
Yes thanks, i go to pull requets

**Comment by NEZNAMY** [comment]
Pull requests ? That's when you suggest code change. You just didn't configure your plugins correctly.
