### ISSUE TITLE
Option to use tierlist of tab on "change-nametag-prefix-suffix: true"

### ISSUE THREAD

**Issue by AymerickA** [NEZNAMY/TAB#148]
Hi,

Please can you add an option to use tierlist of tab on "change-nametag-prefix-suffix: true" and the prefix, BUT not use the nametag function above the nickname.

Thanks.

**Comment by NEZNAMY** [comment]
Don't configure tagprefix property for groups.

**Comment by AymerickA** [comment]
I have try, but your plugin take the priority, so a spigot plugin cannot make a nametag.

(I need that to practice server to distinguish enemies from allies)

**Comment by Tanguygab** [comment]
then either use TAB to handle nametags, either use that plugin. You can't use the 2
Or else ask the plugin's author to make a PlaceholderAPI relationnal placeholder that shows if the player is an ally or an enemy

**Comment by AymerickA** [comment]
You can just add option not to intervene on nametags and only on tablists, so that people could use their own nametag system and your plugin for the tab

**Comment by NEZNAMY** [comment]
Not possible, nametags handle sorting as mentioned at https://github.com/NEZNAMY/TAB/wiki/config.yml#change-nametag-prefix-suffix and https://github.com/NEZNAMY/TAB/wiki/config.yml#group-sorting-priority-list. You either use tab for nametag feature, or a different plugin.

**Comment by Tanguygab** [comment]
Nametags are needed to manage sorting in tablist
