### ISSUE TITLE
Crash 1.7 players

### ISSUE THREAD

**Issue by AymerickA** [NEZNAMY/TAB#149]
**Server version**
1.7-1.15 Travertine

**Plugin version** ("latest" is not a version)
2.7.4

**Describe the bug**
Players in 1.7 version crash on the server

**How to reproduce**
Change "change-nametag-prefix-suffix: false" to true

**Expected behavior**
Players in Badlion client can connect, because the client bypass the bug and make a report log

**Additional info** (errors, screenshots, ...)
Crash report of players : https://framabin.org/p/?ad0187de687da9b4#axemU0qO6WGJzzs+RUXnCjTqzBDpx8IAxgu5Po+NyOM=

https://framabin.org/p/?fcc79ccfe2e0a675#YBgqRufMdP9XCPOLbhV4gfqiDqH7sO25v2KEDwPDuKI=

**Comment by NEZNAMY** [comment]
Need more info how to reproduce it, just joining shouldn't crash.

**Comment by AymerickA** [comment]
Sorry, I can't have more information, the server don't give logs, and the clients have already same logs as mentioned above. 
I have temporarily disabled the function, if you need help with testing please feel free to tell me what to do.

**Comment by NEZNAMY** [comment]
Test on a 1.7.10 bukkit server if it happens.

**Comment by AymerickA** [comment]
1.7.10 spigot but the plugin in bungeecord ?

**Comment by NEZNAMY** [comment]
The plugin on spigot first, then bungee only (never do both at the same time).

**Comment by AymerickA** [comment]
Hmm the problem is i can't drop ip server of players or same staff, so i have create a dns proxy to private server. I'm french, i try and test tomorrow

**Comment by Foulest** [comment]
Paste has expired.

**Comment by AymerickA** [comment]
https://framabin.org/p/?b8cc79a13409313d#EmO4bLU2fmpCLeXN/wWOXtKF+fqoHLz8jR90M2BiF2k=

**Comment by Tanguygab** [comment]
any news ? did you test on a private server @AymerickA ?

**Comment by AymerickA** [comment]
Hi,

I have try new version 4.7.5 and if I remember it working, I think the bug in 1.7 comes from the fact that the characters in the tags are limited

**Comment by Tanguygab** [comment]
I think it should have cut it 🤔 
Anyways, if it's fixed then all good =)
(also, latest version is 2.7.6 :p)
