### ISSUE TITLE
Essentials join on vanish

### ISSUE THREAD

**Issue by Axer22** [NEZNAMY/TAB#150]
**Server version**
Paper-282 (MC:1.15.2)

**Plugin version** ("latest" is not a version)
2.7.4

**Describe the bug**
When I have permission "essentials.silentjoin.vanish" which allows me to be vanished on join, my nickname is still visible on the tab list. Only when I turn off and on vanish, my nickname disappear from tab list.

**How to reproduce**
Install EssentialsX and set this two thing in config.yml file and add permission "essentials.silentjoin.vanish".
`allow-silent-join-quit: true`
`hide-displayname-in-vanish: true`

**Expected behavior**
Nickname should not be visible on the tab list when I join on vanish.

**Actual behavior**
Nickname is visible on the tab list when I join on vanish.

**Additional info** (errors, screenshots, ...)

**Comment by Tanguygab** [comment]
it's Essentials's job to hide you from the tablist, not TAB

**Comment by Axer22** [comment]
But without TAB it's working fine.

**Comment by NEZNAMY** [comment]
Are you using per-world-playerlist in advancedconfig.yml ?

**Comment by Tanguygab** [comment]
someone on SpigotMC had an issue similar to this one which was cause by SkinRestorer (here's the thread https://www.spigotmc.org/threads/supervanish-vanished-player-seeable-in-tab-after-joining-with-setting-auto-vanish-on-join.438955/#post-3809691) maybe it's your case too ?

**Comment by Tanguygab** [comment]
@Axer22 are you still there ?

**Comment by Tanguygab** [comment]
hello ? @Axer22 👋

**Comment by Axer22** [comment]
Yes, SkinRestorer was the problem, thanks.
