### ISSUE TITLE
RedisBungee support

### ISSUE THREAD

**Issue by apatuka** [NEZNAMY/TAB#151]
Consider adding RedisBungee to this amazing plugin.

RedisBungee allows to connect multiple BungeeCords on the same Network, this provide Player Balancing and adding more Regions (EU, NA, SA, etc...) for reducing ping.

I installed this plugin on every BungeeCord and on every Spigot server, but i can see the players list inside a Bungee network and not from the player list from the other Bungee network.

Let's say i have two BungeeCords proxys connected with RedisBungee, Player A and Player B are inside on Proxy A, and Player C and Player D are inside on Proxy B, all of them are inside the same Server (Survival)

Proxy A -> Survival
--------
Player A
Player B

Proxy B -> Survival
--------
Player C
Player D

As you can see, Player A and B can see each other because they are on the same Proxy on the same server, but they can't see Player C and D because Player A and B are on another Proxy but all are inside the same server.

Of course disabling the BungeeCord Mode will let all of them see each other on the Tab List, but i need Bungee TabList because we grouped the servers player list on the same TAB.

Thank you so much !

**Comment by Tanguygab** [comment]
Use the PlaceholderAPI Bridge and use the PAPI placeholders for Redis https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#redisbungee
(I think there was a problem with this expansion, so you might want to join PlacheolderAPI's discord: HeplChat to get an updated version)

**Comment by apatuka** [comment]
Sorry i didn't explained well, i know about the playercount and it doesn't work i ended using SSX Connector and Math Placeholder Expansion. 

But on this case what i want is to see the player list from the other Bungee Proxy connected with RedisBungee.

Thanks !

**Comment by Tanguygab** [comment]
ah, then yeah that would be a suggestion for NEZNAMY
also, for the playercount from the Redis expansion for PlaceholderAPI, as I said above I think they fixed it but didn't upload the fix on the ecloud, you can try to get it on PAPI's discord server: HelpChat
(Actually I just realised it has been updated on April 5th https://api.extendedclip.com/expansions/redisbungee/versions/redisbungee-20/ so... idk x) at least you have an alternative)

**Comment by NEZNAMY** [comment]
Does anyone have an idea how to actually do this ?

**Comment by apatuka** [comment]
From plugins with Redis support i see they register the listener on Redis instead of BungeeCord, so RedisBungee does all the work
I don't know much about Java programming but i see most plugins create a "Provider/Messenger" class, and they expand that class with a listener could be BungeeCord or RedisBungee.

` private void setProvider(){
        if(getProxy().getPluginManager().getPlugin("RedisBungee") != null){
            provider = new RedisBungeeProvider();
            return;
        }
        provider = new BungeeCordProvider(getProxy());
    }`

[Listener](https://github.com/ProxyConn/UntamedChat/blob/master/src/main/java/net/portalblock/untamedchat/bungee/providers/RedisBungeeProvider.java)

[Provider Class](https://github.com/ProxyConn/UntamedChat/blob/master/src/main/java/net/portalblock/untamedchat/bungee/providers/Provider.java) This could be the PluginMessenger class you use.

[RedisBungee API](https://github.com/minecrafter/RedisBungee/wiki/API)

Let me know if i can help on testing

**Comment by PeterP12YT** [comment]
Hey was wondering if this would be happening anytime soon?

**Comment by NEZNAMY** [comment]
Not soon. Busy with bug reports currently.

**Comment by NEZNAMY** [comment]
How do I get permission group of player on another server (so I can display proper tablist format)?

**Comment by NEZNAMY** [comment]
But does it offer getting group of a player who is not online on that specific bungeecord?

**Comment by apatuka** [comment]
You can try with Vault (https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/permission/Permission.java)

```
    /**
     * Gets the list of groups that this player has
     * Supports NULL value for World if the permission system registered supports global permissions.
     * But May return odd values if the servers registered permission system does not have a global permission store.
     * 
     * @param world String world name
     * @param player OfflinePlayer
     * @return Array of groups
     */

```
`String[] getPlayerGroups(String world, OfflinePlayer player)`

**Comment by NEZNAMY** [comment]
Vault is not a bungeecord plugin.

**Comment by apatuka** [comment]
Well then you can fetch that with LuckPerms, it has a BungeeCord version.

https://github.com/lucko/LuckPerms/wiki/Developer-API:-Usage

**Comment by NEZNAMY** [comment]
Which goes back to my previous question - will LP return group of a user who is not online properly?

**Comment by apatuka** [comment]
Yes, getUser(UUID uuid) to check for offline users based on their UUID or Player name (String)

```
public class Test {
    private LuckPermsApi luckPerms;
    
    public String getChatMeta(UUID uuid, ChatMetaType type) {
        if (!luckPerms.getStorage().loadUser(uuid).join()) {
            // got an error whilst loading the user
            return null;
        }

        User user = luckPerms.getUser(uuid);
        if (user == null) {
            // user not loaded, even after requesting data from storage
            return null;
        }
        
        // the contexts for the lookup. if the prefix/suffix is set in a specific server, you'll need to add that here.
        Contexts contexts = Contexts.allowAll();

        MetaData metaData = user.getCachedData().getMetaData(contexts);
        String val = type == ChatMetaType.PREFIX ? metaData.getPrefix() : metaData.getSuffix();
        
        // cleanup the user now we're finished to prevent memory leaks.
        luckPerms.cleanupUser(user);
        
        return val;
    }
}
```

**Comment by RADICALAdrift** [comment]
Hi NEZNAMY,

is there any chance this could be added in a future update as i really like your plugin (i'd really prefer not having to change and set-up another tablist plugin), its just i have 2 different proxies now and overhead prifixes etc don't sync of course

Thanks
RADICAL

**Comment by NEZNAMY** [comment]
I will look into adding this within a month, keep watching this thread in case I have some questions about it.

**Comment by RADICALAdrift** [comment]
This is the redisbungee plugin i'm using: https://www.spigotmc.org/resources/redisbungee.87700/ By Ham1255Official on SpigotMC

**Comment by NEZNAMY** [comment]
Working on it and testing jar will be available in a few days on discord for buyers.

**Comment by quiquelhappy** [comment]
Hello, is this coming for the free version too?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/%5BDraft%5D-The-3.0.0-update it will be available for free to everyone.

**Comment by quiquelhappy** [comment]
nice, thanks :)
