### ISSUE TITLE
Nametags of Citizens NPCs do not show up if the NPC is of an online player.

### ISSUE THREAD

**Issue by TheRBZ** [NEZNAMY/TAB#152]
**Server version**
Paper 1.15.2 build 298

**Plugin version** ("latest" is not a version)
2.7.4

**Java version**
openjdk 11.0.7 2020-04-14

**Describe the bug**
When a player logs in to the server, any NPCs of them will have their name tags disappear

**How to reproduce**
Create a Citizens NPC with the name of an online player
The name tag won't show up.
This is the same if you create an NPC with an offline player's name and then they log back in, their name will disappear.

**Expected behavior**
NPCs have visible name tags regardless of whether or not the player is online.

**Actual behavior**
When a player logs in to the server, any NPCs of them will have their name tags disappear

**Additional info** (errors, screenshots, ...)
/plugins/TAB/config.yml: https://pastebin.com/w6aKr6Wv

I have a feeling it might be to do with _OTHER_ but I don't know.

**Comment by Tanguygab** [comment]
either don't rename NPCs with players' names, either enable unlimited-nametag-prefix-suffix-mode and modify-npcs

**Comment by TheRBZ** [comment]
unlimited-nametag-prefix-suffix-mode.enabled=true
unlimited-nametag-prefix-suffix-mode.modify-npc-names=false

**Comment by TheRBZ** [comment]
oh sorry

**Comment by TheRBZ** [comment]
Thank you, that worked!
