### ISSUE TITLE
BungeeCord command issue

### ISSUE THREAD

**Issue by Foulest** [NEZNAMY/TAB#153]
**Server version**
1.8.8 PaperSpigot, Latest FlameCord

**Plugin version** ("latest" is not a version)
2.7.4

**Describe the bug**
An error appears on the BungeeCord when using /time set day.

**Additional info** (errors, screenshots, ...)
https://pastebin.com/raw/X0w5N78P

**Comment by NEZNAMY** [comment]
Join discord for a version with temporary fix.

**Comment by NEZNAMY** [comment]
Added null check
