### ISSUE TITLE
Modified Tablist Not support on 1.5.2~1.7.10 in 1.8.8 server

### ISSUE THREAD

**Issue by Seanoo1** [NEZNAMY/TAB#155]
**Server version**
1.8.8 tacospigot

**Plugin version** ("latest" is not a version)
2.7.4

**Describe the bug**
Modified Tablist Not support on 1.5.2~1.7.10 client in 1.8.8 server when you use protocolsupport.

**Expected behavior**
Should show modified Tablist on 1.5.2 ~ 1.7.10 client.

**Actual behavior**
Show default tablist on 1.5.2 ~ 1.7.10 client.

**Comment by Tanguygab** [comment]
the header and footer was added in Minecraft 1.8

**Comment by Seanoo1** [comment]
then how this plugin support 1.5.2 server? 
https://www.spigotmc.org/resources/tab-1-5-x-1-15-x-free-version.57806/
it says this plugin support 1.5.2 server...

**Comment by Tanguygab** [comment]
Yes it does, because it works on it and has some features like the nametags above players and in tablist, but it's very limited.
Try to find any other tablist plugins that adds a real header and a real footer in the tablist, it won't be possible as it wasn't there in 1.7 and below

**Comment by Seanoo1** [comment]
oh...

**Comment by Tanguygab** [comment]
From the features on the plugin's page, I added the versions were the features works:
all:
Change prefix/suffix in name tags
Playerlist scoreboard display type (the yellow number in tablist)
Belowname scoreboard display type (below player name tags)
BossBar messages (limited to 1 purple bossbar in 1.8 and below)
Global playerlist on bungeecord
PlaceholderAPI support (relational placeholders supported too)
PlaceholderAPI support on bungeecord (needs to be set up)
Player sorting
PermissionsEx / GroupManager / LuckPerms / UltraPermissions support
Customizable animations working everywhere
Per player/group and per-world configuration (or both)
Per world playerlist option
Fully client-sided, server-side stays unaffected (scoreboards with their teams and objectives, bossbar entities)
Fully asynchoronous - plugin does not run in the main server thread and therefore has zero impact on your TPS (this is why it doesn't appear in timings - it only measures the main thread)
Check plugin's CPU usage any time (/tab cpu)
Disable vanilla feature making player prefixes appear on their tamed animals
Add additional line of text above and below player's nametag
Disable features in specific worlds
Text cutting based on client version, not server version (allows 1.13+ players on <1.13 server to see prefixes longer than 16 characters in nametag)
Possible errors moved into a separate file to not spam your console
Yaml error assistant for more user-friedly messages and fix suggestions
Many misconfiguration checks to help solve issues much faster

1.8+
Send header/footer (were added in 1.8)
Change prefix/suffix in tablist (very limited on 1.7 and below, it uses nametag instead)
Disable vanilla feature making players in spectator gamemode appear on the bottom of tablist (spectator mode was added in 1.8)
Additional code to fix vanilla bug making nametag visible even player is invisible (client sided 1.8.x bug)
Option for unlimited prefix length in nametags on <1.13 (it uses armor stands which were added in 1.8)

1.9+
Control player collision rule (collision was addded in 1.9)

**Comment by NEZNAMY** [comment]
Header/footer was added in 1.8
