### ISSUE TITLE
Unlimited nametags and ride players

### ISSUE THREAD

**Issue by En0tS** [NEZNAMY/TAB#157]
**Server version**

Paper-1618 (final 1.12.2 build)

**Plugin version** ("latest" is not a version)

TAB-2.7.4

**Describe the bug**

When you use plugins like AutoRide (https://www.spigotmc.org/resources/autoride-added-wasd-control-beta.57144/), nametag of rider remains on the place.

**How to reproduce**

Ride any player using AutoRide plugin or GadgetsMenu 'cowboy gadget'.

**Additional info** (errors, screenshots, ...)

Here you can see player and his nametag:
![image](https://user-images.githubusercontent.com/36606833/82912600-f514ea00-9f75-11ea-9794-cdfbeb1c47a8.png)

**Comment by NEZNAMY** [comment]
Join discord to get a build with fix.
