### ISSUE TITLE
Crash: Unlimited nametag crash with new 2.7.5 version

### ISSUE THREAD

**Issue by monikon22** [NEZNAMY/TAB#158]
**Server version**
Spigot v1_12_R1

**Plugin version** ("latest" is not a version)
2.7.5

**Describe the bug**
Unlimited tags crash the server, while on the old version this was not (2.7.0).

**How to reproduce**
Change unlimited tags enabled to true
Randomly quit the server (or get kicked for flying?)

**Additional info**
Crash log: [https://pastebin.com/Dtktfs1i](https://pastebin.com/Dtktfs1i)
Last player's action: [https://pastebin.com/SXu3jhiB](https://pastebin.com/SXu3jhiB)

**Comment by Tanguygab** [comment]
try to redownload 2.7.5, there was a hotfix some minutes after the release

**Comment by NEZNAMY** [comment]
Fixed. Join discord and ask for the fixed version.

**Comment by NEZNAMY** [comment]
Fixed
