### ISSUE TITLE
Adding LP groups to RANK

### ISSUE THREAD

**Issue by SheroxGG** [NEZNAMY/TAB#159]
Hello! I installed this plugin recently and Id love to know if I could the default tab roles that you have on the config files with my lp groups, so for example I can set on: Rank: GOD
id love to be able to link these two plugins, is it possible? Thanks!
![image](https://user-images.githubusercontent.com/34599826/83286556-6526a880-a1e0-11ea-8b68-5cfb5c43d88b.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/config.yml#rank-aliases

**Comment by Tanguygab** [comment]
did you fix it ?
