### ISSUE TITLE
Add 1.7.10 Via Rewind Support.

### ISSUE THREAD

**Issue by GibsonVS** [NEZNAMY/TAB#16]
Hello,

I was wondering if you could add some sort of 1.7.10 support. Any chance of this? I used Via Version and Via Rewind.

Thanks!

**Comment by NEZNAMY** [comment]
What are you looking for exactly ? It's the protocol hack plugin's job to translate packets if possible. Header/footer feature does not exist in 1.7, so this cannot be added.

**Comment by GibsonVS** [comment]
Hey! Thank you for the quick reply. I understand nothing will really work with it. Maybe just a feature so 1.7.10 users see the tab with no effects and is just a default tab.
