### ISSUE TITLE
New Crash: Unlimited nametag crash with new 2.7.6 version

### ISSUE THREAD

**Issue by monikon22** [NEZNAMY/TAB#160]
**Server version**
Spigot v1_12_R1

**Plugin version** ("latest" is not a version)
2.7.6

**Describe the bug**
Unlimited tags crash the server, while on the old version this was not (2.7.0).

**How to reproduce**
Change unlimited tags enabled to true
Join another world.

**Additional info**
Crash log: [https://pastebin.com/0UHg2CA6](https://pastebin.com/0UHg2CA6)
Last player's action: [https://pastebin.com/q0evpKMS](https://pastebin.com/q0evpKMS)

**Comment by NEZNAMY** [comment]
Join our discord and ask for a fixed build.
