### ISSUE TITLE
Staff online variable

### ISSUE THREAD

**Issue by eTiggs** [NEZNAMY/TAB#161]
It would be ideal to be able to edit who falls under the %staffonline% variable as I have a trialmod rank which isnt shown as a staff position through that, minor but qol

**Comment by Tanguygab** [comment]
give players the permission tab.staff

**Comment by NEZNAMY** [comment]
give them tab.staff permission

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#how-to-add-players-to-staffonline-placeholder- 
https://github.com/NEZNAMY/TAB/wiki/Placeholders

**Comment by Tanguygab** [comment]
did you get it to work ?
