### ISSUE TITLE
Cutoff Nametags and Citizens NPCs

### ISSUE THREAD

**Issue by LastNarrator** [NEZNAMY/TAB#162]
Hey, there are 2 citizen NPCs on my server that refuse to keep their names upon client restart, and the TAB nametag feature keeps cutting off, is there a way to either 
1. Remove Citizens from TAB's loadlist and then use Citizen's nametag feature
or
2. Fix this nametag issue?
Background:
We have the bypass limitations option in config set to true, and a long name like "&aTheAznInvasion &3Architect" is working, but our latest 2 NPCs, are not showing nametags, they  get cut off with color codes still active. For example, "&aSamanson &3Architect" gets cut off to "on99 Archite" once you relog or restart the server.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/config.yml#unlimited-nametag-prefix-suffix-modemodify-npc-names

**Comment by LastNarrator** [comment]
![image](https://user-images.githubusercontent.com/33186990/83358360-c907b900-a327-11ea-9eb4-3d4555ec35a1.png)
As you can see here, nametags being invisible isnt the issue, the issue is that only those two are cutting off, pictures attached.

![image](https://user-images.githubusercontent.com/33186990/83358376-e5a3f100-a327-11ea-989f-b1b23e9d9575.png)

**Comment by NEZNAMY** [comment]
What is the issue? The only issue i can see is two NPCs without names.

**Comment by LastNarrator** [comment]
also just realized that those are the only 2 with nametags that disappear in F1. (was editing the post as you responded). Here is a picture that shows the difference.
![image](https://user-images.githubusercontent.com/33186990/83358409-2a2f8c80-a328-11ea-99ce-a98ca74986b6.png)

**Comment by NEZNAMY** [comment]
Are their names identical to names of online players? If yes, that's why. Nametag prefix/suffix is bound to player name, not id or uuid.

**Comment by LastNarrator** [comment]
No, because the names of the players are "Dnizzle1033" and "Samanson99" not "Samanson99 Architect" plus as i showed in the very first picture, i can stand next to my npc while online and have no issues with nametags. plus even if the suffix/preifx is conflicting, the player is "prefix LastNarrator" vs the npc of "LastNarrator Technician".

**Comment by NEZNAMY** [comment]
So what is the problem again?

**Comment by LastNarrator** [comment]
The nametags are cutting off. From "Samanson99 Architect" to "son99 Archite" and only those 2 npcs.

**Comment by NEZNAMY** [comment]
Find out what real names of those NPCs are. Names are limited to 16 characters. What you can see there are likely invisible armor stands.

**Comment by LastNarrator** [comment]
As I said in the first post, i have already enabled the bypass for username limitations, and as you ccan see in the picture, TheAznInvasion has no issues whereas the shorter Dnizzle1033 does.

**Comment by NEZNAMY** [comment]
Yes i know you enabled bypass, i even said it's armor stands displayed there instead. You still didn't asnwer my question.

**Comment by LastNarrator** [comment]
the real names (I used /npc create "&aSamanson99 &3Architect") would be what I used to create the npc yes? if so, there you go. also deleting the npc and starting over again seems to be working so idk what broke on the first versions of these.

**Comment by NEZNAMY** [comment]
Real names are up to 16 characters long.

**Comment by LastNarrator** [comment]
Then why did Azn's work while Samanson's didnt?

**Comment by NEZNAMY** [comment]
I don't have enough information to answer that.

**Comment by LastNarrator** [comment]
>.> Well, idk what other info to provide, and upon a quick relog, the names broke again.
Realname of Azn: §aTheAznInvasion §3Architect
Realname of Sam: §aSamanson99 §3Architect

**Comment by NEZNAMY** [comment]
Real names cannot be longer than 16 characters.

**Comment by LastNarrator** [comment]
BUT. Azn's is **working** while Sam's **isn't**.

**Comment by NEZNAMY** [comment]
Try disabling tab's nametag feature if it gets fixed.

**Comment by LastNarrator** [comment]
But I would like to keep Tab nametags over the players, just not the npcs (it is going to be a sw:tor like server so players will need titles and nametags).

**Comment by NEZNAMY** [comment]
That's not the type of answer i was looking for.

**Comment by LastNarrator** [comment]
oh you mean disable TAB completely and test, solid. wait one.

**Comment by LastNarrator** [comment]
how would i go about removing TAB nametags without touching the tab list?

**Comment by NEZNAMY** [comment]
change-nametag-prefix-suffix: false

**Comment by LastNarrator** [comment]
solid thanks. testing now

**Comment by LastNarrator** [comment]
... it worked... wait so citizens was attempting to show the name at the same time as TAB so it just broke those 2? weird, so i just have to turn off the citizens nametag feature to make the TAB one work?

**Comment by NEZNAMY** [comment]
Looks like it's trying to use names of real players, making it either TAB or citizens and TAB wins.

**Comment by LastNarrator** [comment]
solid, testing to see if doing /npc name (turning off their nameplates) fixes TAB nametag

**Comment by LastNarrator** [comment]
so... after re-enabling the TAB nametag feature I am seeing no issues... I guess disabling and re-enabling it gives Citizens the final say on NPCs and TAB is still able to affect players? (only solution I can think of)

**Comment by NEZNAMY** [comment]
I still don't have enough information to perform any possibly needed code change.

**Comment by LastNarrator** [comment]
Any info you need lemme know i'll send it over, this whole situation is wonky.

**Comment by NEZNAMY** [comment]
Sure, join discord and i will send you a build to test.

**Comment by Tanguygab** [comment]
was this fixed on Discord ?
