### ISSUE TITLE
Conditionnal properties (+bossbar?) 

### ISSUE THREAD

**Issue by Tanguygab** [NEZNAMY/TAB#163]
(From Instilled's ticket on Discord:
conditionnal properties could be useful for:
- detecting events trigger
- what Instilled wants (make per MC versions tablist which are detected with the placeholder %player-version%)
- me and others with BedWars1058 or even other plugins so when a game starts it shows the team name, else the rank
- other people with more ideas

This system could replace the per-world-settings and make it way more customizable, and could aslo be useful for the bossbar ¯\_(ツ)_/¯

**Comment by NEZNAMY** [comment]
Will be added in next version.
