### ISSUE TITLE
settings from advancedconfig.yml for BungeeCord

### ISSUE THREAD

**Issue by Tanguygab** [NEZNAMY/TAB#164]
Add the advancedconfig.yml on Bungeecord and put in it:
 - global-playerlist
 - sort-players-by-permissions
 - use-primary-group settings 
 - the primary-group-finding-list
+Potential features with the bridge if they get added ? :
 - unlimited-nametag-bridge
 - fix-pet-names

**Comment by NEZNAMY** [comment]
I want to keep it in one file if possible
1 will stay
2-4 will be moved to normal config
5 will be in config when added
6 cannot be done from bungee (bridge would do it, probably still in config)

**Comment by Tanguygab** [comment]
Maybe add an option to get permissions groups from the bridge ?
