### ISSUE TITLE
Improve scoreboard API

### ISSUE THREAD

**Issue by AbattoirMC** [NEZNAMY/TAB#166]
Hello.
I would like to ask you if you can add a method like this to the scoreboard API?
`TabAPI.showScoreboard(player, "myscoreboardname");`
Thanks.

**Comment by NEZNAMY** [comment]
You can call method `sendTo(UUID)` in Scoreboard interface which API returns.

**Comment by AbattoirMC** [comment]
How can I get the scoreboard?
I have 5 different scoreboard set in my config and I would like to switch them from my plugin.
Example:
Player enter to a region then I switch his scoreboard to "forest" etc.

**Comment by NEZNAMY** [comment]
You can't switch to existing scoreboard using the API yet. It's not as easy as it sounds - should it prevent the plugin from changing the scoreboard after you called the method? How would you remove the scoreboard after? What if the scoreboard you forced is the same one as plugin would send?

**Comment by AbattoirMC** [comment]
I would like to use it like this (example):
I have 3 scoreboards set in my config (title, lines, etc.):
- "test_1" (default)
- "test_2"
- "test_3"
My plugin checks the player location and if it needs it replaces player scoreboard to "test_2".
When it needs it replaces it to "test_3" etc.

**Comment by NEZNAMY** [comment]
I know, however this does not answer my question about how to make it work internally.

**Comment by AbattoirMC** [comment]
I don’t know.
Is there any way to look into this plugin how they do it?
https://www.spigotmc.org/wiki/featherboard-api/#void-showscoreboard-player-player-string-scoreboard
I don’t know what is the exact problem with this?
I call the method then the API shows the scoreboard, not it?
If an other plugin call it then it shows that etc.

**Comment by NEZNAMY** [comment]
Should such API call make plugin stop to try to find new appropriate scoreboard based on permission or world changes? If yes, how to enable it back?

**Comment by AbattoirMC** [comment]
A config option would be good, not it?

**Comment by Tanguygab** [comment]
`conditionnal-scoreboards: true/false`
* When enabled, scoreboard will use conditions to determine which scoreboard will be displayed to the player.
* When disabled, the scoreboard will be assigned to players with /tab scoreboard <scoreboard name> by an operator, and player will be able to change its own scoreboard with `/<sb command> <board name>` if he has `tab.scoreboard.<boardname>` and that `player-can-change-scoreboard` is enabled.
**Note:** the scoreboard API can change the shown scoreboard to the player ONLY if this option is set to false  

`player-can-change-scoreboard: true/false`
When enabled, players will be able to change their scoreboard with `/<sb command> <board name>`
**Note:** Requires `conditionnal-scoreboards: false` !

**Comment by AbattoirMC** [comment]
Thanks!

**Comment by NEZNAMY** [comment]
Join discord and create a ticket, i will send you a version to try.
