### ISSUE TITLE
TAB(Bungee) suggests wrong placeholder replacement

### ISSUE THREAD

**Issue by FaberoM** [NEZNAMY/TAB#167]
**Server version**
Waterfall 346

**Plugin version** ("latest" is not a version)
2.7.7

**Describe the bug**
On startup I get this message:
`[TAB] Hint: Found used PlaceholderAPI placeholder "%premiumvanish_playercount%". Consider replacing it with plugin's internal "%canseeonline%" for better performance.`

That is incorrect as `%canseeonline%` displays the total player count on bungee network where as `%premiumvanish_playercount%` only shows the amount of players in the current server where player is.

**Expected behavior**
Either correct placeholder replacement would be there instead or the message completely gone.

**Actual behavior**
BTAB suggests wrong placeholder replacement

**Additional info**
N/A

**Comment by NEZNAMY** [comment]
Thanks for the report, will be fixed in next version.
