### ISSUE TITLE
Nick display does not work correctly

### ISSUE THREAD

**Issue by Denias3** [NEZNAMY/TAB#168]
**Server version**
paper-334

**Plugin version** ("latest" is not a version)
TAB v2.7.5

**Describe the bug**
When a player drinks an invisibility potion and 
reboots to the server, then after the potion is finished, the player becomes visible, But his nickname is still invisible. The problem is exactly in your plugin, without it everything works correctly

**How to reproduce**
Drink an invisibility potion, reboot to the server, remove the effect with a command and look at yourself from the side. Nick remains invisible

**Expected behavior**
Nick must be visible

**Actual behavior**
Nick is not visible

**Additional info** (errors, screenshots, ...)
![2020-06-11_18](https://user-images.githubusercontent.com/36571895/84407054-fe0ee800-ac12-11ea-8b3c-29d8e54328f4.png)

**Comment by MrGraycat** [comment]
May I ask you how you are looking at yourself? 
If you are doing this with mods then you're getting an incorrect vieuw of the reality (as you're unable to see your own username)
instead use /tab ntpreview to see how it does look for others. (if you're issue is still visible with that command then report it back here.

**Comment by MrGraycat** [comment]
This bug is only visible when unlimited-nametag-prefix-suffix-mode is disabled.
(Tested in 2.7.8 pre-3)

**Comment by Denias3** [comment]
Honestly, I do not really understand you. You can write in more detai? English is not my native language. Apparently the translator translates poorly

**Comment by Denias3** [comment]
where can I download the plugin already with this bug fixed?

**Comment by NEZNAMY** [comment]
Can you join discord?

**Comment by Denias3** [comment]
Yes

**Comment by MrGraycat** [comment]
Could you test if this jar fixes it?
https://cdn.discordapp.com/attachments/623576356776575006/720719349752791140/TAB_ONLY_USE_FOR_TESTING.jar

**Comment by NEZNAMY** [comment]
Fixed
