### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by CaszGamerMD** [NEZNAMY/TAB#17]
having the custom tag/prefix info in the same file as the config is a bad idea for servers, config will be big and unbearable!
toss it into a separate file or add mysql support

**Comment by NEZNAMY** [comment]
Separate file is kinda pointless, you can always just move the section to bottom of the config. Mysql support would be a better idea.

**Comment by NEZNAMY** [comment]
Note: message sfsfsfsf#6016, this guy, Bars (spigot) and Mr. Ceasar#0001 to test it when added.

**Comment by fjeddy** [comment]
Idea: You could also implement the file idea, and simply just include and use it if it exists. And by default leave it in the main config.

**Comment by tomkeuper** [comment]
Any updates on this? Its been over a year now.

**Comment by NEZNAMY** [comment]
Not really, until recently the code was not ready for this to be affectively added without unwanted side effects. I've also improved bungeecord support with placeholderapi support and global playerlist features to minimize need for this.

**Comment by tomkeuper** [comment]
Has it been inplemented? Have not seen any info regarding so im just asking

**Comment by Tanguygab** [comment]
if it got closed, then yes, it was added in TAB 3.0.0

**Comment by CaszGamerMD** [comment]
> Has it been inplemented? Have not seen any info regarding so im just asking

New features
MySQL Support
First major addition is MySQL support. This will store users and groups, instead of using the files. It can be enabled in new config section for mysql. Conversion is currently not available, but might be in the future.

its in the changelog which is on mc-market









he complains that people don't read his stuff, i agree, people in general don't read things.
