### ISSUE TITLE
Sorting by rang on the tab

### ISSUE THREAD

**Issue by Jaco0410** [NEZNAMY/TAB#170]
I'm changed flag 
change-nametag-prefix-suffix: false 
because I don't have name tag changes and after the change sorting by rang on the TAB stopped working.

**Comment by NEZNAMY** [comment]
Correct.
https://github.com/NEZNAMY/TAB/wiki/config.yml#change-nametag-prefix-suffix
https://github.com/NEZNAMY/TAB/wiki/config.yml#group-sorting-priority-list
https://github.com/NEZNAMY/TAB/wiki/Why-is-player-sorting-not-working-%3F
