### ISSUE TITLE
How to setup Ranks in Tab

### ISSUE THREAD

**Issue by ShreyasAyyengar** [NEZNAMY/TAB#171]
**Server version**
1.15.2

**Plugin version** ("latest" is not a version)
v2.7.7

**Describe the bug**
It's not really bug I just have a question about this amazing plugin!

I am using LuckPerms and I have about 10 ranks setup. When I click tab under the Server Name, there is Rank. How do I get the rank to show whatever the prefix is. The prefix next to my name is already recognised by the plugin. I just wanted to know how to match the prefix with the Rank in the config

Thank you so much!

Shreyas Ayyengar

**Comment by DrWurzeli** [comment]
Hello!
If you are using the default configuration there is an internal placeholder called %rank% there.
You can modify the output by configuring https://github.com/NEZNAMY/TAB/wiki/config.yml#rank-aliases.

You can also just replace the %rank% placeholder with the placeholder you use in front of your name/ for the prefix. For example %luckperms-prefix%.

Than just save, reload and you should be good to go.
Enjoy TAB.

**Comment by ShreyasAyyengar** [comment]
All good! I just have to say this is one of the best Tab plugins I've had in a long time. !!! So grateful for LuckPerms support
