### ISSUE TITLE
Disconnection of player on bungeecord

### ISSUE THREAD

**Issue by Elikill58** [NEZNAMY/TAB#172]
**Server version**
1.8.9 (v1_8_R3)

**Plugin version** ("latest" is not a version)
5.7.7 (download 10 minutes ago)

**Describe the bug**
I'm using Bungeecord.
I have a plugin on spigot which add a scoreboard. With TabAPI, some player can be kicked 30 seconds after they connect to the spigot player.

**How to reproduce**
I'm using this API: https://github.com/SamaGames/SamaGamesAPI/blob/master/src/main/java/net/samagames/tools/scoreboards/

**Question**
I'm currently using my own Scoreboard API. But i don't know which scoreboard system is compatible with TabAPI system, so if you know one of them, tell me !
Finally, will you add a Scoreboard API in your plugin ? :)

**Additional info** (errors, screenshots, ...)
This is the error (on bungeecord) :

`[Eliocrafteur] <-> DownstreamBridge <-> [MyServer] - encountered exception
java.lang.IllegalArgumentException: Objective sidebar1 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:149)
	at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:67)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by NEZNAMY** [comment]
`Objective sidebar1 already exists in this scoreboard` this name does not come from TAB.
Plugin has scoreboard API.

**Comment by Elikill58** [comment]
yes, my plugin create the scoreboard named "sidebar" (then a number according to player).
Really ? I didn't find it (and it's not see in spigotmc main page)
(Just, I'm talking to the scoreboard on the right)

**Comment by NEZNAMY** [comment]
TABAPI.createScoreboard(String title, List<String> lines)
Then you can use methods in the interface it returns.

**Comment by Elikill58** [comment]
Ok thanks you !
What is the update time recommanded ? each 10 ticks ?

**Comment by NEZNAMY** [comment]
10 ticks is fine. Make sure you set 10 ticks not milliseconds.

**Comment by Elikill58** [comment]
I have an error while calling TABAPI.createScoreboard :
`Task #2 for MyPlugin v1.0.1 generated an exception
java.lang.NullPointerException
        at me.neznamy.tab.api.TABAPI.createScoreboard(TABAPI.java:238) ~[?:?]`

**Comment by NEZNAMY** [comment]
Are you sure you have scoreboard feature enabled?

**Comment by Elikill58** [comment]
Oh, sorry I forget it.
Now i have a new problem. There is a "method" refresh, but we cannot send easily the new lines. Like i'm sure that i don't need to use reflection, how can I update lines ? I tried to update the list, but in the source code, it see to be copied so ...

**Comment by NEZNAMY** [comment]
The scoreboard API is very limited as everyone who requested it somehow got lost. I will add more in the future.

**Comment by Elikill58** [comment]
So there is no real way to update it ?

**Comment by NEZNAMY** [comment]
Use placeholders. Their output can be controlled.

**Comment by Elikill58** [comment]
Thanks you ! It works very well :) I close the issue :)
