### ISSUE TITLE
Tag (stand) dissapear when a player teleport through portals

### ISSUE THREAD

**Issue by Jozznak** [NEZNAMY/TAB#173]
**Server version**
PaperSpigot 1.12 (Paper-1618)
Using ViaVersion to accept from 1.9 -1.5
Bug happens with players that are in any version accepted

**Plugin version** ("latest" is not a version)
2.8.1

**Describe the bug**
When "unlimited-nametag-prefix-suffix-mode" is enabled, works fine untill a player teleports from one world to another through a portal (AdvancedPortal is the plugin im using). It seems the stand don't spawn again in player's head.

**How to reproduce**
teleport to other world through a portal makes the bug happend.

**Expected behavior**
The stand making the tag should not dissapear upon death

**Actual behavior**
Stand dissapear, I checked that in gmsp. If I do /tab reload, it fixes all tags untill player uses the again.

**Additional info** (errors, screenshots, ...)
No crash errors. No photo needed, players simply don't display tag in his head when they die. 
Here: https://drive.google.com/file/d/1eGW0nUtA5DZaOWT0GCkEAuuIEa99hna2/view?usp=sharing

**Comment by Jozznak** [comment]
EDIT: I found new info. In the last update 2.8.1, I descovered that this bug don't happens when few players are connected. It seems that it gets buggy when there are more than 5 players connected. I dont know if this helps in anything, but I just wanted to point it.

**Comment by Jozznak** [comment]
EDIT 2:
@NEZNAMY 
New discovery. The bug does not happen in player death event. It happens when a player teleports from one world to another. And the crazy thing is that if the player press shift it's fixes the bug.

Here: https://drive.google.com/file/d/1eGW0nUtA5DZaOWT0GCkEAuuIEa99hna2/view?usp=sharing

**Comment by NEZNAMY** [comment]
Are you able to reproduce the issue using the latest version?

**Comment by Jozznak** [comment]
> Are you able to reproduce the issue using the latest version?

Hello!
No. I wasn't able to reproduce the bug in version 2.8.4. 
It seems you fixed it. Thanx!
