### ISSUE TITLE
Weird BungeeCord Error

### ISSUE THREAD

**Issue by Foulest** [NEZNAMY/TAB#177]
**Server version**
FlameCord, a BungeeCord fork

**Plugin version** ("latest" is not a version)
2.8.1

**Describe the bug**
Errors appeared mid-reload.

**Additional info** (errors, screenshots, ...)
https://pastebin.com/raw/hjxzumya

**Comment by NEZNAMY** [comment]
Was /btab reload used at that time?

**Comment by Foulest** [comment]
Yes.

**Comment by NEZNAMY** [comment]
That explains it. I'll try to find a fix.

**Comment by NEZNAMY** [comment]
Can you join discord for a fixed build?

**Comment by NEZNAMY** [comment]
Fixed.
