### ISSUE TITLE
"fix-pet-names: true" makes tamed cats ignore player

### ISSUE THREAD

**Issue by Hugobert** [NEZNAMY/TAB#178]
**Server version**
1.16.1 (Paper-10, also tested with Spigot)

**Plugin version** ("latest" is not a version)
2.8.1

**Describe the bug**
Cats don't listen to sit down/stand up interactions if "fix-pet-names" is true.

**How to reproduce**
Set "fix-pet-names" in advancedconfig.yml to true.
Tame a cat, it will work as intended. Then tame additional cats, they won't listen to sit down/stand up interations. If you log out and back in, none of the cats will respond to interactions unless you hold certain items (tested positive with salmon and green dye).

**Expected behavior**
Tamed cats should respond to right click interaction by sitting down/standing up, regardless of the item the player is holding and regardless of the "fix-pet-names" setting.

**Actual behavior**
Having "fix-pet-names" set to true results in the reported issue.

**Additional info** (errors, screenshots, ...)
Tested without any additional plugins.

**Comment by NEZNAMY** [comment]
Are you able to test if this issue is present on 1.15 as well?

**Comment by Hugobert** [comment]
It is not present in 1.15.2. Everything working fine there.

**Comment by NEZNAMY** [comment]
Does 1.16.1 client on 1.15.2 server using viaversion work?

**Comment by Hugobert** [comment]
Yes. The issue only seems to be present in 1.16.1 server versions.

**Comment by NEZNAMY** [comment]
So it doesn't depend on client version?

**Comment by Hugobert** [comment]
doesn't seem so:
1.15.2 server + 1.15.2 client -> works.
1.15.2 server with viaversion + 1.16.1 client -> works.
1.16.1 server + 1.16.1 client -> does not work.

**Comment by NEZNAMY** [comment]
Tested on 1.16.1 client and server on a dog, could make it sit/stand with no problems.

**Comment by Hugobert** [comment]
Yes, dogs work fine. It's the cats that have that issue

**Comment by NEZNAMY** [comment]
I don't think there's much i can do if you are right and it really broke. That option simply changes owner UUID to something random to make it not copy anyone's prefix. It's one of the features which are either enable or disabled and they cannot be fixed/changed.

**Comment by Tanguygab** [comment]
seems to affect parrots too

**Comment by bartyrealms** [comment]
This issue is only present when TAB v2.8.2 is on our 1.16.1 server. It affects parrots and cats alike.

**Comment by NEZNAMY** [comment]
After some tests i confirm it affects 1.16.1 server with any client version. 1.16.1 client on older server version works. I have no idea why is this happening. 
Making the feature no longer enable on 1.16.1 servers until a fix is found.

**Comment by NEZNAMY** [comment]
I'm assuming this is caused by additional packets required from the client to make the sit/stand action valid. As we can see, with the feature enabled player no longer displays arm animation when interacting. This may be the packet server now requires as well (and maybe more).

**Comment by l3st4tPlugins** [comment]
Anything regarding this for 1.16.2?

**Comment by NEZNAMY** [comment]
Didn't test, but i believe it's still broken there.

**Comment by l3st4tPlugins** [comment]
This may be something related: Have no idea at the packet level, but the interact entity packet did change from 1.15 to 1.16.
https://wiki.vg/Pre-release_protocol#Interact_Entity

**Comment by NEZNAMY** [comment]
There's just an additional field which likely doesn't make any difference (as long as it's broken in both sneaking and not sneaking cases).

**Comment by l3st4tPlugins** [comment]
Welp. It doesn't affect me just yet, but this issue kinda affects me a lot if I update to 1.16, since pet naming is something my players do quite often and I use unlimited nametag mode.

**Comment by NEZNAMY** [comment]
I have no idea. Help wanted label is assigned, anyone willing to investigate this further is free to do so. Code can be modified to enable the feature on 1.16 servers by modifying [this line](https://github.com/NEZNAMY/TAB/blob/master/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitMethods.java#L123).

**Comment by Dream-cake** [comment]
what about 1.16.2?

**Comment by NEZNAMY** [comment]
Just tested, still present on 1.16.2.

**Comment by Dream-cake** [comment]
Dang. any way to fix this. My players cant see their pets nametags.

**Comment by NEZNAMY** [comment]
One way is to disable unlimited nametag mode which is a feature no other plugin has and switching to a plugin not having the feature instead of disabling it in this one makes no sense.

**Comment by l3st4tPlugins** [comment]
So I've seen other plugins that have something similar to unlimited nametag mode use an invisible living entity on top of the player, such as a silverfish to not render the nametag. Mind taking a look at this? https://github.com/iso2013/MultiLineAPI

**Comment by NEZNAMY** [comment]
> So I've seen other plugins that have something similar to unlimited nametag mode use an invisible living entity on top of the player, such as a silverfish to not render the nametag. Mind taking a look at this? https://github.com/iso2013/MultiLineAPI

I am not trying to make their names invisible. On top of that, this solution would likely have bugs and just feed the trolls on paper discord.

**Comment by l3st4tPlugins** [comment]
I proposed it as a rework of the unlimited nametags system. But that would be a good solution, since my players care a lot about their pets.

**Comment by NEZNAMY** [comment]
This feature is completely independent from unlimited nametag mode. Even if you have that disabled, your pets will still have same prefix as you, which you probably don't want.

**Comment by l3st4tPlugins** [comment]
Welp, there goes my idea. My idea was to rework the unlimited nametag mode, which would fix this issue, only for unlimited nametag users.

I just can't see why this shouldn't work. Have you tried contacting Paper devs? They're probably the best shot at this.
I tried looking through the protocol but I can only see the packet ID changing.

**Comment by NEZNAMY** [comment]
How would reworking unlimited nametag mode fix anything? Isn't what you suggest like an addon to the feature / this one?

**Comment by l3st4tPlugins** [comment]
Forget it. It was just an idea based on how MultilineAPI works, but that plugin had its fair share of issues as well.
And it's still better than asking Spigot devs.

**Comment by NEZNAMY** [comment]
> It was just an idea based on how MultilineAPI works, but that plugin had its fair share of issues as well.

Just like the original unlimited nametag feature itself as well. I got confused, were you referring to asking them how to do it with the multilineapi or actually fixing by finding out which packet it is?

**Comment by l3st4tPlugins** [comment]
Fixing the issue by finding out which packet changed. It's probably a server-side packet since it works on 1.16 clients but not servers.

**Comment by NEZNAMY** [comment]
It must be a packet sent by client. Server has no idea this info wad denied to client, therefore not listening is caused by insufficient packets from the client.

**Comment by Dream-cake** [comment]
So im using the unlimited nametag & i can see pets nametags. Seems that paper 1.16.2 has it fixed. Paper Build #168

**Comment by NEZNAMY** [comment]
> So im using the unlimited nametag & i can see pets nametags. Seems that paper 1.16.2 has it fixed. Paper Build #168

Are you sure you used nametag item to give them a custom name?

**Comment by Dream-cake** [comment]
yes ive done both. use a name tag and rename the spawn egg

**Comment by NEZNAMY** [comment]
> yes ive done both. use a name tag and rename the spawn egg

I just tested it on latest paper build, animals still copy nametag properties from their owner (https://prnt.sc/ua82pg), with this feature enable I cannot make them stand/sit.

**Comment by NEZNAMY** [comment]
I FIXED IT!
Anyone interested to test the fix can join discord and ask for the build, as long as you agree you will report possible bugs with the fix appropriately instead of trash talking the plugin on paper discord.

**Comment by Dream-cake** [comment]
how?

**Comment by NEZNAMY** [comment]
Apparently false information results in interact packets being sending twice, therefore toggling the animal twice which resulted in immediate revert of the first toggle.
