### ISSUE TITLE
TAB not showing prefix

### ISSUE THREAD

**Issue by thetechguy989** [NEZNAMY/TAB#179]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
v2.8.1

**Describe the bug**
When I go to the tablist, the tagprefix does not show up.

**How to reproduce**
Make a 1.12.2 server with TAB installed together with ViaVersion. Go to the server with 1.15.2 and press TAB.

**Expected behavior**
As per shown in additional info below, expected behaviour is to see the prefix together with the IGN (in-game name)

**Actual behavior**
As per shown in additional info below, actual behaviour is seeing only IGN (in-game name)

**Additional info** (errors, screenshots, ...)
![ExpectedBehaviour](https://user-images.githubusercontent.com/58862188/86004406-94b11680-ba13-11ea-827a-377f293ad49a.PNG)
![ActualBehaviour](https://user-images.githubusercontent.com/58862188/86004669-e78ace00-ba13-11ea-9a17-915631345203.PNG)

**Comment by NEZNAMY** [comment]
tagprefix is for nametag, not tablist

**Comment by thetechguy989** [comment]
Sorry, I meant tabprefix

**Comment by Tanguygab** [comment]
do /tab debug <player>
and send a screen of what it says

**Comment by thetechguy989** [comment]
![debug](https://user-images.githubusercontent.com/58862188/86009063-02604100-ba1a-11ea-8c7d-18097d95c210.PNG) 
![groups](https://user-images.githubusercontent.com/58862188/86009090-0db36c80-ba1a-11ea-9072-d488abef9ee5.PNG)

**Comment by thetechguy989** [comment]
The 1st image is the debug.
The 2nd is the config I put.
It looks like it's taking the tabprefix as "" and suffix as "%afk%", both of which I have set differently.

**Comment by Tanguygab** [comment]
the player is in the default group. set your weights/priorities correctly in your permission plugin

**Comment by thetechguy989** [comment]
done.
it works.
thanks :)
