### ISSUE TITLE
Player tags don't show RGB colours

### ISSUE THREAD

**Issue by lucyy-mc** [NEZNAMY/TAB#180]
**Server version**
Paper 1.16.1 git-Paper-32
Waterfall 1.16 357

**Plugin version** ("latest" is not a version)
2.8.1 (in bukkit bridge mode, unable to test standalone)

**Describe the bug**
Player name RGB colours are replaced with white in-game

**How to reproduce**
1) define a tagprefix using RGB
2) look at players' tags

**Expected behavior**
RGB colours to be displayed

**Actual behavior**
RGB colours are just white, legacy colours work fine

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/35287819/86394584-ba018700-bc96-11ea-8847-4e7799823d8f.png)

**Comment by Rodrigo178** [comment]
Try with 2.8.2

**Comment by NEZNAMY** [comment]
Did you disable change-tablist-prefix-suffix? Can you show output of /tab debug <some player it doesn't work on> ?

**Comment by lucyy-mc** [comment]
change-tablist-prefix-suffix is enabled.
output of /btab debug (ltags_prefix_tab provides the prefixes in the correct format):
![image](https://user-images.githubusercontent.com/35287819/86395019-752a2000-bc97-11ea-9d46-13b7ac5be16b.png)

**Comment by NEZNAMY** [comment]
That error file should be looked at. Try with 2.8.2 and delete errors file to check if you get any new errors.

**Comment by lucyy-mc** [comment]
in the errors.txt:
`8.06.2020 - 19:14:23 - java.lang.NullPointerException: null
28.06.2020 - 19:14:23 -        at me.neznamy.tab.shared.packets.IChatBaseComponent.optimizedComponent(IChatBaseComponent.java:354)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.shared.packets.PacketPlayOutScoreboardTeam.toBungee(PacketPlayOutScoreboardTeam.java:126)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.platforms.bungee.Main.buildPacket(Main.java:338)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.shared.PacketAPI.buildPacket(PacketAPI.java:19)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:406)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.shared.ITabPlayer.unregisterTeam(ITabPlayer.java:359)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.shared.features.NameTag16.onQuit(NameTag16.java:68)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.platforms.bungee.Main.lambda$0(Main.java:143)
28.06.2020 - 19:14:23 -        at java.util.ArrayList.forEach(ArrayList.java:1257)
28.06.2020 - 19:14:23 -        at me.neznamy.tab.platforms.bungee.Main.a(Main.java:143)
28.06.2020 - 19:14:23 -        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
28.06.2020 - 19:14:23 -        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28.06.2020 - 19:14:23 -        at java.lang.reflect.Method.invoke(Method.java:498)
28.06.2020 - 19:14:23 -        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
28.06.2020 - 19:14:23 -        at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
28.06.2020 - 19:14:23 -        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453)
28.06.2020 - 19:14:23 -        at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:65)
28.06.2020 - 19:14:23 -        at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:60)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
28.06.2020 - 19:14:23 -        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
28.06.2020 - 19:14:23 -        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
28.06.2020 - 19:14:23 -        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
28.06.2020 - 19:14:23 -        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
28.06.2020 - 19:14:23 -        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
28.06.2020 - 19:14:23 -        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
28.06.2020 - 19:14:23 -        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
28.06.2020 - 19:14:23 -        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
28.06.2020 - 19:14:23 -        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
28.06.2020 - 19:14:23 -        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
28.06.2020 - 19:14:23 -        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
28.06.2020 - 19:14:23 -        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
28.06.2020 - 19:14:23 -        at java.lang.Thread.run(Thread.java:748)`

**Comment by NEZNAMY** [comment]
That explains a lot. Try latest version.

**Comment by lucyy-mc** [comment]
no errors on this one, still no rgb though

**Comment by NEZNAMY** [comment]
Are you using viaversion on bungee?

**Comment by lucyy-mc** [comment]
Nope, all native 1.16.1

**Comment by NEZNAMY** [comment]
Just tested and it works http://prntscr.com/tang8t.

**Comment by lucyy-mc** [comment]
Could it be related to bukkit bridge mode?

**Comment by NEZNAMY** [comment]
No. That's only for placeholder support. Try updating waterfall? Or reproduce it on localhost with no other plugins.

**Comment by lucyy-mc** [comment]
alright, i'll see what i can come up with.

**Comment by lucyy-mc** [comment]
updating waterfall hasn't fixed it, i'll look into it later

**Comment by lucyy-mc** [comment]
Turns out this was an issue with my modded client, sorry about that
