### ISSUE TITLE
Tab keeping players from other servers when changing server ( bungee )

### ISSUE THREAD

**Issue by PapiCapi** [NEZNAMY/TAB#181]
**Server version**
paper-44

**Plugin version** ("latest" is not a version)
v2.8.2

**Describe the bug**
Players from other servers are shown in the tab of another server.

**How to reproduce**
Connect to a server, open the TAB. Switch server and open again the TAB.

**Expected behavior**
Show only the players who are on the server.

**Actual behavior**
It shows players from both servers ( if they didn't quit )

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Uninstall TAB to check if it keeps happening.

**Comment by PapiCapi** [comment]
Well, i just saw that the issue seems to come from BungeeCord. I'll try tomorrow to update to the latest build and close this issue if it is my fault
