### ISSUE TITLE
Failed to load scoreboard at reconnection

### ISSUE THREAD

**Issue by Elikill58** [NEZNAMY/TAB#182]
**Server version**
1.8.8 (v1_8_R3)

**Plugin version** ("latest" is not a version)
2.8.2

**Describe the bug**
I'm using the scoreboard API, as we said before (with placeholders API). When i'm login, I well have my plugin scoreboard, but when I disconnect then reconnect, I have default one ...

**How to reproduce**
I'm using this class: https://gist.github.com/Elikill58/65d39290a5b7ef384946b3a4e4837446 (and just calling "updateScoreboard").
Connect, disconnect, reconnat: default sb lines.

**Additional info** (errors, screenshots, ...)
No error. My config:
`scoreboards:
  admin:
    display-condition: permission:tab.scoreboard.admin
    if-condition-not-met: scoreboard1
    title: '&6Scoreboard'
    lines:
    - '&cError while loading scoreboard'`

**Comment by NEZNAMY** [comment]
Sounds about right. You need zo send the scoreboard to the player again when he reconnects.

**Comment by Elikill58** [comment]
Thanks, it works now !
