### ISSUE TITLE
RGB nicknames from EssentialsX not showing correctly

### ISSUE THREAD

**Issue by JuanDelPueblo** [NEZNAMY/TAB#183]
**Server version**
Paper-79 (MC: 1.16.1)

**Plugin version** ("latest" is not a version)
v2.8.2

**Describe the bug**
When setting a nickname with hex colors using EssentialsX 2.18.0.0, it does not show correctly in TAB, instead showing the color code from the last character of the hex color. Neither %displayname% nor %essentialsnick% show the hex color correctly.
The hex color that is supposed to be shown is in the first line, but the nickname shows magenta instead.

**How to reproduce**
Set a nickname on EssentialsX with &#f26c0d
Look at TAB

**Expected behavior**
Show the nickname with the correct hex color

**Actual behavior**
Shows the nickname with the wrong color

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/49998039/87209427-cd889f80-c2df-11ea-8437-ca139768ab45.png)

**Comment by NEZNAMY** [comment]
&x&r&r&g&g&b&b is not supported yet, join discord for a build with added support.
