### ISSUE TITLE
TAB does not parse RGB colors properly for %essentials_nickname% and %essentialsnick%

### ISSUE THREAD

**Issue by bartyrealms** [NEZNAMY/TAB#185]
**Server version**
1.16.1, Tuinity-3950d4b

**Plugin version** ("latest" is not a version)
2.8.2

**Explanation**
Tab:
![image](https://user-images.githubusercontent.com/42015460/87956021-7f606280-ca7c-11ea-83b7-548f1d0b49c0.png)

Parsing the placeholder with `/papi parse BartyRealms %essentials_nickname%`:
![image](https://user-images.githubusercontent.com/42015460/87956090-98691380-ca7c-11ea-9506-cbb73baae562.png)

**Comment by Tanguygab** [comment]
join Discord for a dev build which supports Essentials' RGB format

**Comment by NEZNAMY** [comment]
&x&r&r&g&g&b&b is not supported yet.
