### ISSUE TITLE
Relation placeholders not refreshing

### ISSUE THREAD

**Issue by TosieG** [NEZNAMY/TAB#186]
**Server version**
Paper-101 (MC: 1.16.1)

**Plugin version** ("latest" is not a version)
2.8.2

**Describe the bug**
After upgrading from 2.6.5 to 2.8.2, the %rel_factionsuuid_relation_color% placeholder from factions plugin is not refreshing. Only way is reconnect or write something on chat, but the second option is not working on tag prefix.

_The last working version is 2.7.7_

**Expected behavior**
It should change color of relation after few seconds

**Actual behavior**
I have to chat or reconnect to refresh it

**Additional info** (errors, screenshots, ...)
![](https://i.imgur.com/tSmgUQT.png)

**Comment by NEZNAMY** [comment]
Join discord for fixed build.
