### ISSUE TITLE
Lib's Disguise support

### ISSUE THREAD

**Issue by Gumpah** [NEZNAMY/TAB#187]
Hi!

**Server version**
Paper-379 1.15.2

**Plugin version** ("latest" is not a version)
v2.8.2

**Describe the bug**
The collision between the player and the mob creates an infinite moving. The option to fix it is to set the config line `enable-collision` to `false`, but it's overriding every other plugin and deactivation collisions globally, without being able to let it actived by the paper.yml file for example.

**How to reproduce**
Disguise with the plugin Lib's Disguise and TAB plugin, with the config `enable-collision` set to `true`.

**Actual behavior**
The collision between the player and the mob creates an infinite moving.

Thanks for your time!

**Comment by NEZNAMY** [comment]
Join discord for a fixed build

**Comment by Gumpah** [comment]
Fixed with the sent build, thank you!
