### ISSUE TITLE
How to add animations for TAB plugin

### ISSUE THREAD

**Issue by ShreyasAyyengar** [NEZNAMY/TAB#189]
Hi there,

I really like the animations aspect of this plugin and I was looking at the %animations:admin_prefix% and I was wondering if I could make my own animation because when I tried to place the individual animation texts, and when I put it into tab and tags for a group, it didn't always complete the text. 

Is there a way to make my own animation and make sure it completes all the text?

Best,
Shreyas

**Comment by Rodrigo178** [comment]
Check https://github.com/NEZNAMY/TAB/wiki/Animations
