### ISSUE TITLE
add TABS to PAPI

### ISSUE THREAD

**Issue by CaszGamerMD** [NEZNAMY/TAB#19]
you have papi support but there's no papi placeholder available.
trying to make a gui using Deluxe Menu but want the current tag to be highlighted... need to be able to check player tag pre/suffix to do that

**Comment by NEZNAMY** [comment]
Plugin has a hook into PAPI and offers you to use their placeholders anywhere. Are you talking about the plugin itself offering some ?

**Comment by CaszGamerMD** [comment]
yes, so we can use other plugins like DM and ect, to make GUI menus.
that way we can show the players which one they have on from there

**Comment by NEZNAMY** [comment]
Check discord
