### ISSUE TITLE
Feature Request | BossBar

### ISSUE THREAD

**Issue by roy0510** [NEZNAMY/TAB#195]
Could you implement "display-condition" and "if-condition-not-met", in BossBar ?, Same as what the ScoreBoard has, I hope they can implement it in BossBar

**Comment by NEZNAMY** [comment]
How about just the display-condition part and for a backup bossbar just create another one with the expression negated?
I don't want to alter the default file too much as any changes would need to be added manually as I don't want it to be i default file in free version and get questions and complaints.
