### ISSUE TITLE
Tab plugin does not reduce the numbers of (Players online & Staff Online) when using a vanish plugin

### ISSUE THREAD

**Issue by ShreyasAyyengar** [NEZNAMY/TAB#196]
**Server version**
1.16.1

**Plugin version** ("latest" is not a version)
v2.8.3

**Describe the bug**
Using PremiumVanish plugin and when doing /v it hides the players name in the tab list but doesn't change the Online Players and Offline Player Count

**How to reproduce**
Install PremiumVanish (Or SuperVanish because that's free)

**Expected behavior**
It should reduce the numbers of players online when going into vanish

**Actual behavior**
It doesn't. It keeps the players online the same.

**Additional info** (errors, screenshots, ...)
None

*I don't know if this is something to do with my Vanish plugin or my TAB plugin, so please let me know

**Comment by rodrigozamorad** [comment]
Use %canseeonline% or %canseestaffonline%

**Comment by ShreyasAyyengar** [comment]
@rodrigozamorad Lmao didn't even see that, Thank you!!!!

**Comment by ShreyasAyyengar** [comment]
Where do I find a list of all the placeholders?

**Comment by rodrigozamorad** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders
