### ISSUE TITLE
BossBar bug on 1.8

### ISSUE THREAD

**Issue by Macianka4** [NEZNAMY/TAB#197]
**Server version**
Paper 1.8.8 (Using ViaVersion)

**Plugin version** ("latest" is not a version)
2.8.4

**Describe the bug**
I've made custom BossBar. On versions lower than 1.9 it's really buggy. It just dissapears and appears.

**How to reproduce**

**Expected behavior**
Show it at every time

**Actual behavior**
It dissapers and appears 

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Limitation of the feature.

**Comment by Macianka4** [comment]
Is there any way to fix it?

**Comment by NEZNAMY** [comment]
Upgrade your server and client.

**Comment by Macianka4** [comment]
I'll just delete the bossbar. Thanks for help. I'll close the ticket in one minute. Thanks for fast response.
