### ISSUE TITLE
Feature Request (Or Clarification)

### ISSUE THREAD

**Issue by ShreyasAyyengar** [NEZNAMY/TAB#198]
**Server version**
1.16.2

**Plugin version** ("latest" is not a version)
v2.8.4

I was just wondering if there was a way to set up tab prefixes and tag prefixes for a specific player rather than a group. I have a few members in my server that have exclusive tags and the only way to do that at the moment is to create an entire luckperms group specifically for that user.

**Comment by Tanguygab** [comment]
/tab player <player> tabprefix <text>
next time, check the wiki 😉
