### ISSUE TITLE
[Unlimited nametags] Not compatible with disguise plugins

### ISSUE THREAD

**Issue by NEZNAMY** [NEZNAMY/TAB#2]
Disguised player has two nametags, his own + armor stands added by the plugin.

**Comment by Tanguygab** [comment]
Last night, I realized that I had an idea on how to fix this, it could be done with conditionnal properties that I suggested here #163
This way, the Disguise plugin would just need to make a placeholder for PlaceholderAPI and then you make a condition, if that placeholder returns true/yes, then the nametag doesn't show
