### ISSUE TITLE
Sponge [feature request]

### ISSUE THREAD

**Issue by nurdism** [NEZNAMY/TAB#20]
+1 ![sponge](https://i.imgur.com/ZkZENcO.png) xD
love the plugin btw its amazing, would love sponge support too :)

**Comment by NEZNAMY** [comment]
Well, i'll very likely need assistance with this one. I have no experience with sponge api.

**Comment by VOrlando520** [comment]
I would also like to request a sponge version as well. The api and it's documents have gotten been over the last couple of years and most of on site plugin devs are very helpful in porting plugins as well

**Comment by CorvetteCole** [comment]
I would also like to request a sponge version. Sponge has really gotten a ton better

**Comment by lukasdeveloper** [comment]
I would also like to see a Sponge version.

**Comment by bloodyearth** [comment]
Add sponge support pls. :)

**Comment by lolw0tm8** [comment]
pls sponge support i neeeeeeedddd ittttt

**Comment by NEZNAMY** [comment]
After 1 hour of getting into sponge i almost got cancer. I will not be able (and now even willing) to do this without assistance from someone who knows sponge well. I won't pay anyone for help as this is a free plugin. Anyone interested in sponge support is allowed to look for a sponge dev to help with this.

**Comment by CorvetteCole** [comment]
@NEZNAMY I'm going to look in to writing it myself, will get back to you.

**Comment by A248** [comment]
To be honest I've tried working the Sponge API before. It's... like NEZNAMY said.

**Comment by TheWackersKian** [comment]
Yeah please someone help him bring this to Sponge

**Comment by xqplc** [comment]
Well an f for that

**Comment by NEZNAMY** [comment]
F indeed. I will not add sponge support myself. This task is still open for anyone interested to give it a try.

**Comment by montlikadani** [comment]
You can use my [Sponge version of tablist](https://ore.spongepowered.org/montlikadani/%5BAnimated-Tab%5D---TabList) temporarily if you're interested. lmao

**Comment by NEZNAMY** [comment]
I guess it's too late now, but with external help I was able to add sponge support to the plugin.

**Comment by nurdism** [comment]
@NEZNAMY it took a while but I appreciate the update  👍🏻
