### ISSUE TITLE
NPE on basic TABAPI usage

### ISSUE THREAD

**Issue by Lezzio** [NEZNAMY/TAB#201]
**Server version**
PaperSpigot 1.8.8

**Plugin version** ("latest" is not a version)
v2.8.4

**Describe the bug**

Basic usage turns into NullPointerException

In an a PlayerJoinEvent EventHandler : 

TABAPI.setValuePermanently(player.getUniqueId(), EnumProperty.BELOWNAME, "Test");

![image](https://user-images.githubusercontent.com/7536802/91382239-920f4980-e829-11ea-920b-c40c2bcfdb6a.png)

It is added to the dependencies plugin.yml and compileOnly in Gradle

Otherwise the plugin works well on its own

**Comment by NEZNAMY** [comment]
Armor stands are initalized asynchronously in a task called in PlayerJoinEvent so i get less complaints about plugin "massively lagging the server" with a task which also says "count: 1" and didn't even take a full tick to process. You will need to delay your call a little bit. I could possibly queue API tasks to avoid NPEs.

**Comment by bertek41** [comment]
> Armor stands are initalized asynchronously in a task called in PlayerJoinEvent so i get less complaints from kids about plugin "massively lagging the server" with a task which also says "count: 1" and didn't even take a full tick to process. You will need to delay your call a little bit. I could possibly queue API calls to avoid NPEs.

So, should i check TABAPI#getPlayer is not null in timer and then do my job or delaying join event by 5 seconds enough?

**Comment by NEZNAMY** [comment]
Delaying by 1 tick should be enough. There will be an API method in the next version.
