### ISSUE TITLE
EazyNick Compatibility 

### ISSUE THREAD

**Issue by ShreyasAyyengar** [NEZNAMY/TAB#202]
**Server version**
1.16.2

**Plugin version** ("latest" is not a version)
v2.8.4

**Describe the bug**
Using the plugin, EazyNick (https://www.spigotmc.org/resources/eazynick-autonicksystem-api-src-bungeecord-multiworld-1-7-10-1-16-x.51398/) and TAB, does not change the name in tab or tag. Is this a compatibility issue?

**How to reproduce**
Download EazyNick, and TAB.

**Expected behavior**
When doing /nick and completing your nickname, the name in TAB, does not change and the Tag doesn't change either. The EazyNick config has been setup correctly to do so. 

**Actual behavior**
It does not display the nicked name in tab or tag

**Comment by rodrigozamorad** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-nick-plugins
