### ISSUE TITLE
[Feature Request] Add support for CMI for AFK status

### ISSUE THREAD

**Issue by NeuTraLZero** [NEZNAMY/TAB#204]
**Server version**
1.16.2

Add support for CMI for AFK status
[Plugin's Spigot page](https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/)

**Comment by Tanguygab** [comment]
it was already a thing before, but removed since CMI already has its `%cmi_user_afk_symbol%` placeholder, which does the same thing and can be change in CMI's language file

**Comment by NEZNAMY** [comment]
%cmi_user_afk% / %cmi_user_afk_symbol%
