### ISSUE TITLE
Upload packages to package repository for developers

### ISSUE THREAD

**Issue by kylejulian98** [NEZNAMY/TAB#208]
In order to access the API you provide I need to download a jar and maintain it in my own repository. It would be more ideal to have it readily available in a package repository, such as the one provided by [github](https://github.com/features/packages).  As you maintain an open source repository, you can benefit from the free features provided by github. This is more of a suggestion, as it does not greatly inconvenience me at the moment. However, whenever I need to update to the latest version of TAB it does get frustrating.

**Comment by NEZNAMY** [comment]
Wouldn't maven be a better solution?

**Comment by kylejulian98** [comment]
> 
> 
> Wouldn't maven be a better solution?

Maven, Artifactory, Nexus, any would be ideal. Whichever is more convient for you. I suggested the GitHub package repository since it's free 😀

**Comment by NEZNAMY** [comment]
Done https://github.com/NEZNAMY/TAB/blob/master/README.md
