### ISSUE TITLE
PremiumVanish

### ISSUE THREAD

**Issue by Foremast69** [NEZNAMY/TAB#209]
1.16.2

Does premiumvanish work?

**Comment by NEZNAMY** [comment]
%canseeonline%

**Comment by Foremast69** [comment]
Where do I have to add it? Sorry I'm not really good

**Comment by NEZNAMY** [comment]
instead of %online%
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions
https://github.com/NEZNAMY/TAB/wiki/Placeholders
next time read wiki first

**Comment by Foremast69** [comment]
I apologize for not reading the wiki first, thank you again for helping me.
