### ISSUE TITLE
Not all Staff are shown in the staff count

### ISSUE THREAD

**Issue by darrennrena** [NEZNAMY/TAB#21]
**Server version** 1.14.4 Paper

**Plugin version** ("latest" is not a version) 2.5.1

**Describe the bug** I have Staff "Owner" Headadmin" "helper" "Builder" the Builders and helpers are not showing in the staff count they are added in "staff-groups:" we have removed and added back in all groups and only Owner and Headadmin show in staff count

**How to teproduce** Just in Tab "Online Staff"

**Expected behavior** Helpers and builders not included in this count

**Actual behavior** Doesnt count staff as staff?

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
https://www.spigotmc.org/resources/tab-1-8-x-1-14-x-reborn.57806/updates
Read 2.5.0 update notes.
