### ISSUE TITLE
empty lines appear in the tab

### ISSUE THREAD

**Issue by NESTOWL** [NEZNAMY/TAB#210]
i using paperMC 189, plugin version 2.8.6
such bugs occur periodically, blank lines appear!
There was no such thing before, what could it be connected with?

![vIWogho7HT](https://user-images.githubusercontent.com/45520187/92977332-6630cc80-f495-11ea-89d1-9564ed157bc8.gif)

**Comment by NEZNAMY** [comment]
http://prntscr.com/uftmz7

**Comment by NESTOWL** [comment]
@NEZNAMY Thanks! I apologize for the carelessness ...
