### ISSUE TITLE
Hard ERROR Related to GroupManager

### ISSUE THREAD

**Issue by strahil211** [NEZNAMY/TAB#213]
**Server version**
Paper 1.16.3 #198

**Plugin version** ("latest" is not a version)
2.8.7

**Describe the bug**
After updating to TAB 2.8.7 from 2.8.6, an error appeared and does not seem fixable.

**How to reproduce**
Install latest GroupManager v2.8 and TAB 2.8.7, error should appear.

**Expected behavior**
TAB 2.8.6 did not have this error, I expect TAB 2.8.7 to not have it either.

**Actual behavior**
Guaranteed error on every launch. 

**Additional info** (errors, screenshots, ...)
Both plugins are functioning, everything works as intended. However here is the error:

17.09.2020 - 14:29:00 - [TAB v2.8.7] An error occurred when refreshing placeholders
17.09.2020 - 14:29:00 - java.lang.NullPointerException: null
17.09.2020 - 14:29:00 -        at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPermissions(WorldsHolder.java:548)
17.09.2020 - 14:29:00 -        at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerPrefix(Chat_GroupManager.java:272)
17.09.2020 - 14:29:00 -        at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67)
17.09.2020 - 14:29:00 -        at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91)
17.09.2020 - 14:29:00 -        at me.neznamy.tab.platforms.bukkit.placeholders.BukkitPlaceholderRegistry$10.get(BukkitPlaceholderRegistry.java:146)
17.09.2020 - 14:29:00 -        at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:20)
17.09.2020 - 14:29:00 -        at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:83)
17.09.2020 - 14:29:00 -        at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:119)
17.09.2020 - 14:29:00 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
17.09.2020 - 14:29:00 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17.09.2020 - 14:29:00 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
17.09.2020 - 14:29:00 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
17.09.2020 - 14:29:00 -        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by NEZNAMY** [comment]
Are you using the supported groupmanager plugin and not some cheap plugin with the same name?

**Comment by strahil211** [comment]
https://www.spigotmc.org/resources/groupmanager.38875/

**Comment by NEZNAMY** [comment]
The error goes through vault. Consider contacting them or GM directly.

**Comment by NEZNAMY** [comment]
This is an error in GroupManager code which was called from Vault, there is nothing I can do about it. If this persists consider not using %vault-prefix% or switching permission plugin.
