### ISSUE TITLE
question

### ISSUE THREAD

**Issue by NeonPine709** [NEZNAMY/TAB#214]
how do you make it so new players automatically get the [player] prefix?

**Comment by NEZNAMY** [comment]
`Groups:
  <permission group of new players>:
    tabprefix: "[player] "`

**Comment by NeonPine709** [comment]
thanks
i will try that now

**Comment by NeonPine709** [comment]
it didnt work

**Comment by NeonPine709** [comment]
what should i do??

**Comment by NEZNAMY** [comment]
Assign it to correct permission group.

**Comment by NeonPine709** [comment]
i have

**Comment by NeonPine709** [comment]
im using powrranks does it work if i use this?

**Comment by NEZNAMY** [comment]
Yes if you use method 3 https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups#method-3-permission-nodes

**Comment by NeonPine709** [comment]
I've done that

**Comment by NeonPine709** [comment]
But still nothing

**Comment by NeonPine709** [comment]
I've got to go now I will be back in the morning

**Comment by NEZNAMY** [comment]
Verify player group using /tab debug [player]. If it's wrong, check the wiki page again.
