### ISSUE TITLE
Support for 1.16.3

### ISSUE THREAD

**Issue by Vikertorpet** [NEZNAMY/TAB#215]
**Server version**
Paper_1.16.3

**Plugin version** ("latest" is not a version)
2.8.7

**Describe the bug**
not starting with server or reload i have the premium ed

**Comment by NEZNAMY** [comment]
Startup log? Any actually useful info?

**Comment by Vikertorpet** [comment]
tab isnt showing in logs didnt create a folder so idk
https://pastebin.com/0UxV9Xy8

**Comment by NEZNAMY** [comment]
The plugin is not in the log you sent. Your is incomplete or you did not install the plugin.

**Comment by Vikertorpet** [comment]
ok found it but dont know fix
https://pastebin.com/D4HcN1Tg

**Comment by NEZNAMY** [comment]
Download the jar from mcmarket again.

**Comment by Vikertorpet** [comment]
ok, works now
