### ISSUE TITLE
[Feature Request] An idea to fix invisibility issue of 1.8

### ISSUE THREAD

**Issue by Tomi010817** [NEZNAMY/TAB#217]
This idea would consist of adding a new option on the config, and when it is enabled, then everytime you get the invisibility effect, your tag prefix, name and suffix will be removed, setting back to your white default name until your invisibility option expires or gets removed. This option would totally fix the invisibility issues of 1.8 because for some reason when your tag name is set as default without any suffix or prefixes, it actually gets fixed and hidden when you have invisibility effect. 
I currently only use tab values on my 1.8.8 server since I want invisibility to work perfect so people can spy or steal silently other people without getting exposed by their modified tags, but if this option is possible and you accept it, then I would rely again on tag values :D
Have a very good day!, and thanks in advance for reading my suggestions.

**Comment by NEZNAMY** [comment]
Already added years ago.

**Comment by Tomi010817** [comment]
Cool! Thanks
