### ISSUE TITLE
API Request: Toggle Scoreboard

### ISSUE THREAD

**Issue by bertek41** [NEZNAMY/TAB#218]
Can i just toggle scoreboard in TABAPI or TabPlayer instead of copying this https://github.com/NEZNAMY/TAB/blob/master/src/main/java/me/neznamy/tab/shared/command/level1/ScoreboardCommand.java#L30-L45

**Comment by NEZNAMY** [comment]
If you purchased the plugin and usage is for a private plugin, you can join discord for a jar to try.
