### ISSUE TITLE
Enable Parts Of Unlimited Nametag Mode

### ISSUE THREAD

**Issue by MrApocalyptic** [NEZNAMY/TAB#22]
Yeah I Was Wondering If You Could Add An Option To Only Enable Certain Parts Of Unlimited Nametag Mode Like If We Wanted To Use The Vanilla Nametag But Still Wanted BelowName Or AboveName

**Comment by NEZNAMY** [comment]
That's not a good idea, you wouldn't be able to use belowname because plugin can't move your nametag higher. Why do you even want this ?

**Comment by MrApocalyptic** [comment]
Mainly to keep the nametag not visible when shifting behind a block

**Comment by NEZNAMY** [comment]
Are you talking about the removed 1.14 feature allowing armor stands to sneak ?

**Comment by MrApocalyptic** [comment]
Yeah

**Comment by NEZNAMY** [comment]
That's in my to-do list to make it invis on 1.14 clients.

**Comment by MrApocalyptic** [comment]
Oh Okay
