### ISSUE TITLE
[VISUAL BUG] Visual bug with Javascript Placeholders

### ISSUE THREAD

**Issue by Tomi010817** [NEZNAMY/TAB#220]
**Server version**
Minecraft 1.8.8
Spigot 1.8.8

**Plugin version**
v2.8.7

**Describe the bug**
When you use specifically a JavaScript placeholder that you made with PlaceHolderAPI on some place of the TAB plugin, apparently cause all JavaScript placeholders (specifically those who need to refresh constantly) to twinkle showing values that are not supposed to show. This visual bug happens on all circunstances, including Tablist, Tags, Scoreboard, Holograms... the visual error is caused in general by the plugin.
It started to happen to me when I set a javascript placeholder on the "tagsuffix" and "tabsuffix" values on my groups. I even tried setting 1 milliseconds to the refresh of those placeholders but my Javascripts placeholders would still twinklying.
It took me more than 3 hours to find that this plugin was the responsible for this visual glitch since I have over 80 plugins on my server, but at the same time I'm happy that this plugin was the cause of it because I know you are really active and helpful, so I know it is gonna go pretty well. Also at first I thought that the twinkle was due to my messy and awful code structure with which I made my Javascript placeholders, but apparently they worked flawlessly when removing all Javascript placeholders values from the TAB plugin.

**How to reproduce**
To reproduce this, the best way (I believe) would be to set in a prefix or suffix value, any JavaScript placeholder. Then you just need to add a **constant changing Javascript placeholder** on some part of your server where you could see it being updated constantly, in my case I used cooldown placeholders that I made with javascript. When you see those Javascript, you will notice that they sometimes twinkle showing a different value for like a few milliseconds, which visually bothers a lot.

**Expected behavior**
https://media.giphy.com/media/GBClYxfManX1QobXIc/giphy.gif
This is a gif showing on a scoreboard, one of my cooldown JavaScript placeholders. It contains Days and hours, so it should change every hour only. The issue doesn't happen here.

**Actual behavior**
https://media.giphy.com/media/8QzdVxHsHmzU7j1uM0/giphy.gif
The same placeholder, but in this case I included some random JavaScript placeholders on the TAB config, and this happens for some reason. It shouldn't twinkle like that... it even says "&cNo" for a few milliseconds.

**Additional info** (errors, screenshots, ...)
I really don't know what else to bring into this issue, but if you need, I can send you my full config file of TAB, and the JavaScript placeholders with a brief explanation of them. In case you are interested on that last thing, please DM me on discord and I will reply you asap. Hope I got clear on this github issue, also I hope that it could let you find out where the bug comes from. 
Regards!

Discord: `Tomi010817#8699`

**Comment by NEZNAMY** [comment]
I don't see how this would be caused by TAB. It is using PlaceholderAPI.setPlaceholders method for all placeholders no matter what the expansion is. TAB also does not handle output of placeholders, so that random "20h" text displaying must have it's source somewhere. 
Did you install the plugin on both bukkit and bungeecord accidentally? Can you try to debug your placeholders by printing out what they return? Eventually I could send you a jar that would do it.

**Comment by Tomi010817** [comment]
I currently have just 1 server, and it's Spigot 1.8.8. I tell you that I also really didn't expect this plugin to be the cause of it, because it didn't even make much sense to me, until I figured out this one was it.
The JavaScript that you saw on the gif, is a cooldown I made using the expiry placeholder of LuckPerms which originally would turn "1d 15h 49m 27s" (for example), and with the Javascript, it would turn something like "1&bDay&8,&r 15&3Hours", being much more clear, cool and shortened. Tho I'm not good at coding and that was one of my first javascripts, the code looks very messy and long, which made me think that this issue was my fault because I should I've coded it much more optimized...  but then it turned out that it wasn't because of my shitty code. Well I really don't know what more I can bring about this issue since it is really weird.
Also the issue is confirmed to not be caused by lag or low TPS, since the environment where I caught it, was a localhost and I only use that plugin with a scoreboard, PAPI and Luckperms to confirm that it wasn't caused by any other plugins.
If you need, I can send you a folder with the needed plugins ready to drag and drop so you can investigate more deeply where it does come from.

**Comment by NEZNAMY** [comment]
Can you join discord and create a ticket? I will send you a jar to try.

**Comment by Tomi010817** [comment]
Sure!

**Comment by NEZNAMY** [comment]
Caused by bug in user's javascript triggered when multiple plugins access it at the same time.
