### ISSUE TITLE
[TAB v2.8.7] Failed to deserialize json component

### ISSUE THREAD

**Issue by DJEsmerald** [NEZNAMY/TAB#221]
I having a problem with the plugin. 
Explication: All the users (Staff and Normal players) don´t have the prefix in the TAB, apper in the heads shows the Prefix, but in the tab do not shows. What can I do? I using the plugin Bungeecord.
Here is the link of the yml folder [http://www.mediafire.com/file/wuudgei759yv2h1/TAB.rar/file](url)

**Comment by NEZNAMY** [comment]
Does /tab debug <player> show tabprefix is configured?

**Comment by DJEsmerald** [comment]
The command doesn't works in Bungeecord

**Comment by DJEsmerald** [comment]
[http://www.mediafire.com/file/2yj6oly8sjq1goq/TAB.rar/file](url)
This is the config of the plugin now, I tried to delete all the config and keeps the problem

**Comment by DJEsmerald** [comment]
![Captura](https://user-images.githubusercontent.com/61849445/95263660-82115f00-0804-11eb-803a-16d00da92930.PNG)
I tried to put in a Server, and shows this

**Comment by NEZNAMY** [comment]
Do you still not have prefix with tab on bukkit? And if you have it on bungee, use /btab instead.

**Comment by DJEsmerald** [comment]
Ok, the tabprefix shows 0

**Comment by NEZNAMY** [comment]
Then you did not configure it.
