### ISSUE TITLE
how to set up pre/suffixes from multiple ranks

### ISSUE THREAD

**Issue by tipakA** [NEZNAMY/TAB#222]
**Server version**
1.16.3

**Plugin version**
2.8.7

Hello, i recently wanted to start a small server for friends, but ran into issues while trying to set up prefixes and suffixes.  
Idea is to have a prefix basing on team someone is in, and eventually add a suffix if someone is a mod. Ideally, it would look like this:
```
[Team 2] NotAMod
[Team 3] tipakA [Mod]
```
I have set-up luckperms, but tab was just a major wall, and i have absolutely no clue what i am supposed to do.

- Since tab uses only one group with highest priority, it's either Team or Mod. No matter if highest priority rank has any data or not.
- Despite claiming "compatibility" with luckperms, it appears that the "compatibility" is enforced by completely ignoring whatever luckperms offers. From what i can tell, luckperms exposes meta properties, including pre/suffixes, but i wasn't able to make tab make any use of such properties.
- User prefixes take priority over group prefixes. This means that i cannot go on a compromise and set a `[Mod]` suffix per user.
- I have absolutely no clue if it's possible to have own placeholders, from what i played around looks like all mentioned in config are just internal.
- Disabling `change-tablist-prefix-suffix` makes tab absolutely not care about anything, so setting meta in luckperms didn't do anything at all.
- `%rank%` is completely useless, as rank is highest priority group - which already has own prefix in tab, so suffix with `%rank%` for team3 uses team3 rank.

Is there anything else i (and wiki) missed? something i don't get, or is just broken?

**Comment by Tanguygab** [comment]
Well of course if it's not configured it won't be working correctly with LuckPerms 🙃

You have to use LuckPerms' placeholders in the tabprefix and tabsuffix to display your players' prefixes/suffiwes from LuckPerms.
You can achieve this by using PlaceholderAPI. 
Also, when you are in 2 groups and want 2 metas, you can use LP's Meta Stacking feature and use its placeholders. Explained here: https://luckperms.net/wiki/Prefix-&-Suffix-Stacking

**Comment by tipakA** [comment]
Ok, thanks for the nudge in the right direction, allowed me to solve the issue.

For anyone reading this in future (probably even me), solved this by setting meta stacking to highest prefix from team track, and highest suffix from staff track, and readded prefixes and suffixes for ranks in luckperms.
Then i removed all groups from tab's config, and set `tabprefix: '%luckperms_prefix%'` and `tabsuffix: '%luckperms_suffix%'`  for group `_OTHER_`.

Works like a charm.
