### ISSUE TITLE
Sort the players by placeholders alphabetic

### ISSUE THREAD

**Issue by SiphMC** [NEZNAMY/TAB#228]
Hello, is it possible to sort the players with their placeholders + name alphabetic?

**Comment by MrGraycat** [comment]
Hello

This is possible using the premium version of TAB.
Can be found here:
https://www.spigotmc.org/resources/tab-1-5-x-1-16-x-premium.83967/
or here:
https://www.mc-market.org/resources/14009/

If you've purchased it you can verify on discord for premium support.
(as we never provide premium support to unverified people to prevent piracy)

Thanks
