### ISSUE TITLE
Cannot compile using Maven

### ISSUE THREAD

**Issue by MRtecno98** [NEZNAMY/TAB#229]
Tried to compile the plugin from sources using Apache Maven 3.6.3, several dependencies were missing, like NetworkManager or Velocity. I tried to fill the gaps where i could and tried to compile again, maven fails with unknown symbol error for many bungeecoord components in the platform/proxy/bungee package, any fix? Maybe an update to the POM?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/.dependencies
You must download them manually into folder defined in pom.xml

**Comment by MRtecno98** [comment]
I already put Velocity in there, NetworkManager is still missing tough and it's a paid plugin

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/.dependencies
It has download link.

**Comment by MRtecno98** [comment]
Yes.. i said i already downloaded velocity. In that file there isn't an url for NetworkManager tough, and it too is a required local dependency.

**Comment by NEZNAMY** [comment]
Meanwhile I dropped NM support and removed the link. Get latest source.

**Comment by MRtecno98** [comment]
Oh got it, thanks.
