### ISSUE TITLE
Health Below Players Name

### ISSUE THREAD

**Issue by ItsAwaken** [NEZNAMY/TAB#23]
Hey! would be cool if you could add a feature that does something like this
https://user-images.githubusercontent.com/53785299/63692771-53a41080-c80a-11e9-80ab-883767a52b0b.png

**Comment by ItsAwaken** [comment]
Oh ty :P, is there any way to change the 'Health' to a symbol?

**Comment by NEZNAMY** [comment]
Yes, just put the symbol there.

**Comment by ItsAwaken** [comment]
Oh shit im backward Ty!!!
