### ISSUE TITLE
me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:78)

### ISSUE THREAD

**Issue by darkmage4** [NEZNAMY/TAB#237]
**Server version**
Paper 1.16.4

**Plugin version** ("latest" is not a version)
v2.8.8

**Describe the bug**
Kicks you from the server

**How to reproduce**
just log in. 

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)
`04.11 16:53:07 [Server] ERROR java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Optional
04.11 16:53:07 [Server] WARN java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Optional
04.11 16:53:07 [Server] WARN at net.minecraft.server.v1_16_R3.DataWatcherRegistry$16.a(SourceFile:112)
04.11 16:53:07 [Server] WARN at net.minecraft.server.v1_16_R3.DataWatcher.a(DataWatcher.java:219)
04.11 16:53:07 [Server] WARN at net.minecraft.server.v1_16_R3.DataWatcher.a(DataWatcher.java:156)
04.11 16:53:07 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayOutEntityMetadata.b(SourceFile:37)
04.11 16:53:07 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:42)
04.11 16:53:07 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:12)
04.11 16:53:07 [Server] WARN at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
04.11 16:53:07 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04.11 16:53:07 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
04.11 16:53:07 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
04.11 16:53:07 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
04.11 16:53:07 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
04.11 16:53:07 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
04.11 16:53:07 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
04.11 16:53:07 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
04.11 16:53:07 [Server] WARN at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:78)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
04.11 16:53:07 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
04.11 16:53:07 [Server] WARN at su.fogus.engine.nms.packets.PacketManager$1.write(PacketManager.java:107)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
04.11 16:53:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)`

**Comment by NEZNAMY** [comment]
Remove TAB and try again.

**Comment by NEZNAMY** [comment]
Remove TAB and try again.

**Comment by darkmage4** [comment]
Yeah didn't work, but now i get a different error when the plugin is no longer there, looking it up, it seems to point to ProtocolLib. So I'll  have to wait until they update that plugin and then I will try again! Another protocolLib dependent plugin also threw out errors too. 

Once they update that, I'll come back with what happens! 

Thanks for your time!

**Comment by coralpapa** [comment]
@darkmage4 not sure if you found but they have a dev version @ https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

I was having same issue as you and just updated to this dev version and no longer having issue

**Comment by darkmage4** [comment]
Yes, its all working! :D
