### ISSUE TITLE
Essentials displayname bug in nametag

### ISSUE THREAD

**Issue by Nximus** [NEZNAMY/TAB#238]
**Server version**
Paper build #261 | 1.16.4

**Plugin version** ("latest" is not a version)
2.8.8

**Describe the bug**
The essentials displayname, in the nametag, shows up accompanied by the regular vanilla name. I want to remove the vanilla name so that I can just have the essentials displayname as the nametag.

**How to reproduce**
Use the essentials %displayname% placeholder for  "tagprefix"

**Expected behavior**
Show essentials displayname above head like in tablist

**Actual behavior**
Shows essentials displayname along with the vanilla Minecraft name

**Additional info** (errors, screenshots, ...)
https://prnt.sc/vdt4b0 (What the nametag looks like currently)
http://prntscr.com/vdta17 (The tablist for an example of what I want the nametag to look like)
My config:
Groups:
  Owner:
    tabprefix: "&2&lOWNER "
    tagprefix: "%displayname%&r"

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-nick-plugins
Putting player's name into prefix resulting in double name is not a bug, but obvious behavior.
