### ISSUE TITLE
"belowname" text doesn't follow the player.

### ISSUE THREAD

**Issue by PanIntegralus** [NEZNAMY/TAB#24]
**Server version**
1.14.4

**Plugin version** ("latest" is not a version)
2.5.1

**Describe the bug**
"belowname" text stays on the sites without following the player.

**How to teproduce**
I don't know how to reproduce it.

**Expected behavior**
"belowname" text following the player.

**Actual behavior**
"belowname" text stays on the sites without following the player.

**Additional info** (errors, screenshots, ...)
https://i.imgur.com/LsglOfj.png

**Comment by NEZNAMY** [comment]
Update the plugin

**Comment by PanIntegralus** [comment]
I updated the plugin. Still doesn't work
Actual version: 2.5.1

**Comment by NEZNAMY** [comment]
Try reconnecting and check errors.txt for more info.

**Comment by PanIntegralus** [comment]
There's nothing from today in errors.txt

**Comment by NEZNAMY** [comment]
Are you still experiencing the issue ? Have you found a way to reproduce it reliably ?

**Comment by PanIntegralus** [comment]
It's now fixed, I blocked all the features in all of the worlds 🤦‍♂️

**Comment by NEZNAMY** [comment]
So it looks like unloading issue. Alright then,
