### ISSUE TITLE
Below name and Above name

### ISSUE THREAD

**Issue by fineryx** [NEZNAMY/TAB#241]
**Server version**
1.16.4

**Plugin version** ("latest" is not a version)
2.8.8

**Describe the bug**
Hi, is it possible to add below name and above name to a group? I want all players to have their faction above their names. but it doesn't show up.

**How to reproduce**
Set abovename to a group, save and reload the plugin

**Expected behavior**
Should show up

**Actual behavior**
Doesn't show up

**Additional info** (errors, screenshots, ...)
I tried to set the server offline and connecting with _NEZNAMY_ name with the preset above and below name but it didn't show up too.

Thanks

**Comment by Tanguygab** [comment]
you need to enable the unlimited nametag mode

**Comment by fineryx** [comment]
yeah ty, it works now :) 
Also unrelated question: where are you from?

**Comment by Tanguygab** [comment]
France, why ? :D

**Comment by fineryx** [comment]
Ignore it :D 
![Minecraft Screenshot 2020 11 16 - 17 50 46 82](https://user-images.githubusercontent.com/61429003/99282753-64d4a500-2834-11eb-95b0-737b1606b1a2.png)
Well, I fixed it but do you know how to implement this? I use [these factions](https://www.spigotmc.org/resources/saberfactions-1-8-1-16-x-discord-saber-pw-the-complete-factions-solution.69771/) and i want to show the players faction abowe them, is there any way? Thanks.

**Comment by Tanguygab** [comment]
You have to use PlaceholderAPI placeholders if this plugin provides some. Check the plugin's wiki if it has one or ask the author.
Also wtf is that player name x)

**Comment by fineryx** [comment]
That was the first thing that I thought of

That's even weirder when I think about it

**Comment by fineryx** [comment]
Update: I used [this](https://github.com/SaberLLC/Saber-Factions/wiki/PlaceHolders), but it still doesn't work. :/ Should I  ask the factions Devs?
![Minecraft Screenshot 2020 11 16 - 18 06 25 54](https://user-images.githubusercontent.com/61429003/99284490-9e0e1480-2836-11eb-8d22-3708d756bfc5.png)

**Comment by Tanguygab** [comment]
I guess, yeah, but make sure you have the PlaceholderAPI plugin first

**Comment by fineryx** [comment]
I never used this placeholders thing, so sorry for being annoying

**Comment by fineryx** [comment]
https://www.spigotmc.org/resources/factionsuuid.1035/ I think I found it but it's 15$.

**Comment by Tanguygab** [comment]
no, that's not it,
SaberFactions is a fork of FactionsUUID, and it uses the same placeholders
What you need to do is install the plugin PlaceholderAPI.
If you already have it, go ask SaberFactions's dev why the placeholders don't work

**Comment by fineryx** [comment]
They still didn't respond to me, but I think I could add the config part of it
![Capture](https://user-images.githubusercontent.com/61429003/99292927-33fb6c80-2842-11eb-8000-2546d2ff26b6.PNG)

**Comment by fineryx** [comment]
![2020-11-17_13 06 53](https://user-images.githubusercontent.com/61429003/99388462-e7fa0780-28d5-11eb-8d4e-e8b869c9ee00.png)
Nice! Thanks for the help :) it works now.

**Comment by booboojp** [comment]
Can I have some help, IDK why below name is not working for me
`lieutenant-colonel:
  tabprefix: "#992d22&lLieutenant &lColonel&r "
  tagprefix: "#992d22&lLieutenant &lColonel&r "
  customtabname: "%essentials_nickname%"
  customtagname: "%essentials_nickname%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: "%luckperms-suffix%%afk%"
  tagsuffix: "%luckperms-suffix%%afk%"
  belowname: "NANI"
  abovename: "HELLO!"`

**Comment by NEZNAMY** [comment]
No, issue tracker is not for support.

**Comment by booboojp** [comment]
Ok, sorry.

**Comment by booboojp** [comment]
Is there a discord server I can join?

**Comment by NEZNAMY** [comment]
Readme contains link for buyers.

**Comment by booboojp** [comment]
Got it, thank you.

**Comment by Rogirek** [comment]
Ahoj, potřeboval bych poradit s jednou maličkostí.
Potřebuji nastavit barevně placeholder který je umístěný pod Nickem.
"belowname-objective:"

Děkuji předem za odpoved.
![flodyy](https://user-images.githubusercontent.com/121316140/209400283-2fc873ed-3381-4fca-814b-df051c59dac1.PNG)

**Comment by Tanguygab** [comment]
> Ahoj, potřeboval bych poradit s jednou maličkostí. Potřebuji nastavit barevně placeholder který je umístěný pod Nickem. "belowname-objective:"
> 
> Děkuji předem za odpoved. ![flodyy](https://user-images.githubusercontent.com/121316140/209400283-2fc873ed-3381-4fca-814b-df051c59dac1.PNG)

https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname#limitations
![image](https://user-images.githubusercontent.com/45695833/209400518-2907cddb-96c2-4ad3-bf30-b9f335cf527a.png)
And support isn't provided on GitHub, if you need help, use the Discord server, just like NEZNAMY told the other user a few messages above your message.

**Comment by Rogirek** [comment]
Oukej, díky moc. opravil jsme to, ale ještě se mi vyskytla chybka, že u dalšího hráče to vidím a u sebe ne, to stejné daný hráč to na mě vidí a u sebe ne.

**Comment by Tanguygab** [comment]
> And support isn't provided on GitHub, if you need help, use the Discord server, just like NEZNAMY told the other user a few messages above your message.

Thank you for completely ignoring half of my message

**Comment by Rogirek** [comment]
chill bro

**Comment by Rogirek** [comment]
Kde najdu odkaz na discord?
