### ISSUE TITLE
java.lang.IllegalArgumentException: Team already exists in this scoreboard

### ISSUE THREAD

**Issue by bartymc** [NEZNAMY/TAB#242]
**Server version**
1.16.4, Purpur 930
Waterfall 384

**Plugin version** ("latest" is not a version)
v2.8.8

**Describe the bug**
Occasionally no one can connect to my server due to a scoreboard error. Error is linked below. Have to delete my scoreboard.dat to fix it. Seems to happen randomly. Problem began occurring upon updating to 1.16.4 and updating TAB. Never happened prior to updating.

**How to reproduce**
Unable to reproduce, happens randomly.

**Additional info** (errors, screenshots, ...)
Error:
https://gist.github.com/bartymc/8053840650205c18b1693a8ff9eda256

**Comment by NEZNAMY** [comment]
Every single team created by TAB ends with an "A". TAB has no impact on server side which includes scoreboard.dat file, since it uses packets.

**Comment by bartymc** [comment]
You're right, it ended up being unrelated I believe.
