### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by GoaTTheGoat** [NEZNAMY/TAB#244]
https://imgur.com/a/chZHFHu 
I have downloaded the placeholders but still not working.

**Comment by NEZNAMY** [comment]
This is not a bug, but an issue on your end. Join discord for faster assistance.

**Comment by GoaTTheGoat** [comment]
I don't use discord though. You can try to send a solution here. I'm trying to get this over with for an hour.

**Comment by NEZNAMY** [comment]
Install placeholderapi if you don't have it. If tab is on bungee, https://github.com/NEZNAMY/TAB/wiki/How-to-set-up-PlaceholderAPI-support-on-bungeecord. That's as much as I can help without further info.

**Comment by GoaTTheGoat** [comment]
I do have PlaceholderAPI. And installed the extension of Luckperms, Player, and Vault. https://pastebin.com/r2Uj7tuq This is the premiumconfig. I don't know what's wrong in there.

**Comment by Tanguygab** [comment]
your preliumconfig doesn't have the scoreboard in the screenshot you sent, so it doesn't come from TAB

**Comment by GoaTTheGoat** [comment]
https://pastebin.com/PaUTqGxV

**Comment by Tanguygab** [comment]
execute /papi parse me %luckperms_groups%
then /tab parse %luckperms_groups%
and send a screenshot of both commands in the chat

**Comment by GoaTTheGoat** [comment]
https://imgur.com/a/ZvDqo1b

**Comment by Tanguygab** [comment]
does /tab reload fixes it?

**Comment by GoaTTheGoat** [comment]
> does /tab reload fix it?

Nope

**Comment by Tanguygab** [comment]
what does /btab return?

**Comment by GoaTTheGoat** [comment]
> what does /btab return?

Unknown command. Type "/help" for help.

**Comment by Tanguygab** [comment]
what's your TAB version and server version?

**Comment by GoaTTheGoat** [comment]
TAB v2.8.9 by _NEZNAMY_
This server is running Paper version git-Paper-288 (MC:1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Tanguygab** [comment]
send a screen of the orange part of /tab debug

**Comment by GoaTTheGoat** [comment]
https://imgur.com/a/U9KThnw

**Comment by Tanguygab** [comment]
I don't have any other ideas =/ I'll let NEZNAMY handle

**Comment by NEZNAMY** [comment]
Do internal placeholders work? Did you get an error file in tab's folder?

**Comment by GoaTTheGoat** [comment]
> Do internal placeholders work? Did you get an error file in tab's folder?

What kind of internal? Nope I didn't get an error file in tab's folder

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders

**Comment by GoaTTheGoat** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Placeholders

It works. But the Guilds is not

**Comment by NEZNAMY** [comment]
so placeholderapi placeholders don't work? do they work elsewhere in the plugin? can you try to reset your premiumconfig?

**Comment by GoaTTheGoat** [comment]
> so placeholderapi placeholders don't work? do they work elsewhere in the plugin? can you try to reset your premiumconfig?

No they don't work. Yes they work in other plugins. What do you mean reset? /tab reload? I've done that and it works the internal placeholders.

**Comment by NEZNAMY** [comment]
I mean in tablist, header/footer or prefixes. Resetting means deleting the file to let plugin generate it again.

**Comment by GoaTTheGoat** [comment]
> I mean in tablist, header/footer or prefixes. Resetting means deleting the file to let plugin generate it again.

Done. And then what?

**Comment by NEZNAMY** [comment]
Try if it works when adding placeholders into scoreboard again. You didn't say if they work in tablist or not.

**Comment by GoaTTheGoat** [comment]
Nope still not working

**Comment by NEZNAMY** [comment]
Can you upload your tab folder somewhere and share it?

**Comment by GoaTTheGoat** [comment]
https://files.fm/u/zf8yx26ej

**Comment by NEZNAMY** [comment]
Works for me. Are you using the official jar file?

**Comment by GoaTTheGoat** [comment]
yes

**Comment by NEZNAMY** [comment]
You still didn't answer if placeholderapi placeholders work in different parts of the plugin than scoreboard or not.

**Comment by GoaTTheGoat** [comment]
yes it works fine on my chat plugin.

**Comment by NEZNAMY** [comment]
TAB is not a chat plugin.

**Comment by GoaTTheGoat** [comment]
Yes Guild Plugin Placeholder works in Tablist

**Comment by NEZNAMY** [comment]
I am not able to reproduce your issue with latest public release. You must be using an unofficial jar. Did you buy it?

**Comment by NEZNAMY** [comment]
Looks like user didn't buy it, we already had 3 people complain about this same issue, none of them willing to get verified for purchase.
