### ISSUE TITLE
Where are the styles?

### ISSUE THREAD

**Issue by ShiraDev** [NEZNAMY/TAB#245]
**Server version**
latest BungeeCord (git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539)

**Plugin version** ("latest" is not a version)
v2.8.9

**Describe the bug**
Styles, such as bold, italic or underlined, are not taken over from the prefix in the name

**How to reproduce**
Install LuckPerms without MySQL on the BungeeCord, so that tab gets the prefixes from LuckPerms with a hardcoded sorting

**Expected behavior**
Styles are also visible in the name

**Actual behavior**
No styles, only colors are taken from the prefix in the name

**Additional info** (errors, screenshots, ...)
https://prnt.sc/vuj3cu

**Comment by NEZNAMY** [comment]
Gone since 1.13 https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags
