### ISSUE TITLE
Tab plugin uses PEX for permisssion plugin but using %rank% in footer says "No Rank"

### ISSUE THREAD

**Issue by Ben569483** [NEZNAMY/TAB#247]
I have the Owner rank in PEX, /tab debug recognises it as permission plugin but doesn't use it in footer, sorting system is groups (which is what PEX is, a group manager)

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#why-does-rank-say-no-rank-

**Comment by Ben569483** [comment]
How do I define it?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/config.yml#rank-aliases

**Comment by Ben569483** [comment]
It’s working now, thanks
