### ISSUE TITLE
Two suggestions for the animations

### ISSUE THREAD

**Issue by Tomi010817** [NEZNAMY/TAB#250]
### First Suggestion
This suggestion would not only make it more comfortable, it would also decrease a lot of cases where people tend to put animations, inside of animations, inside of more animations, making the code insanely complex. It would consist of letting us put an interval for each animation's message (in case you don't define an interval for a message of an animation, then it will use the default interval set for that animation).

### Second Suggestion
This one would only make it more comfortable for its usage. It would consist on using "ticks" for intervals, so this way you don't have to strictly put divisible or multiple numbers on it, because using "ticks" it would all consist on consecutive numbers, so you don't have to make any calculations. And the quotes are because it would only be visual ticks, when actually it would work as milliseconds by multiplying the interval set by 50. (i.e.: If an interval is 25 ticks, then the plugin will multiply it by 50 and it would handle it as 1250 milliseconds)

**Comment by NEZNAMY** [comment]
The first one would make it much more complicated for everyone to use. Most users won't take advantage of this. You can also achieve this by putting a line several times into the animation.

The second one would be misleading as it wouldn't use tick system at all, making it static 50 even if tickrate is lower. Also would break config of everyone for no reason at all.

**Comment by Tomi010817** [comment]
Thanks for answering and giving your opinion Neznamy
