### ISSUE TITLE
group-sorting-priority-list doesn't support luckperms

### ISSUE THREAD

**Issue by jiajiaxd** [NEZNAMY/TAB#254]
**Server version**1.12.2

**Plugin version** ("latest" is not a version)

2.8.2
**Describe the bug**
group-sorting-priority-list doesn't support luckperms

**How to reproduce**
use luckperms

**Expected behavior**
support luckperms

**Comment by NEZNAMY** [comment]
It supports luckperms and you're very outdated. Read https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist.
