### ISSUE TITLE
URGENT Kicking players on join whenever the plugin is installed

### ISSUE THREAD

**Issue by FATGUY46** [NEZNAMY/TAB#256]
Paper 1.16.4

TAB v2.8.9

Kicks players automatically no matter what when they join the server, after a few seconds. No idea why this happens. 

Recreation: Install the plugin I guess.

Expected behavior: For it to not do this

Actual Behavior: It's Kicking players

There is no error on the spigot server other than "name lost connection: Disconnected". But there is an error on bungee. https://pastebin.com/EbWfuDE3

**Comment by FATGUY46** [comment]
Seems to have magically fixed itself. Reinstalled the plugin like twice and now it's acting as expected. Very strange.

**Comment by Tanguygab** [comment]
yeah this issue is completely random. You can have more info https://github.com/NEZNAMY/TAB/wiki/config.yml#unregister-before-register
