### ISSUE TITLE
Compatibility with LibsDisguises

### ISSUE THREAD

**Issue by CaptainAmpersand** [NEZNAMY/TAB#26]
The current TAB plugin completely overrides hitboxes with its features. I disabled the hitbox control in TAB, which effectively fixed LibsDisguises (the mob you're disguising as's hitbox trying to get into your hitbox), but now everyone is a ghost when they aren't disguised, and able to walk through one another.

Would it be possible to request 1.14.4 TAB support with LibsDisguises?

**Comment by NEZNAMY** [comment]
How should it work ? When a player is disguised, disable his collision, otherwise enable if it's enabled in config ?

**Comment by CaptainAmpersand** [comment]
That indeed would be the perfect way to do it. I just don’t know if you want to go that extra mile because of someone else’s plugin 😅

**Comment by NEZNAMY** [comment]
I already had to make a lot of changes in code because of other plugins, this would just be another one.

**Comment by CaptainAmpersand** [comment]
If that’s not too much effort, that’d be amazing. Not too many devs have that kind of work ethic. I appreciate your time and effort :)

**Comment by NEZNAMY** [comment]
Added in latest build.
