### ISSUE TITLE
Tab Error

### ISSUE THREAD

**Issue by ImperatusMaximus** [NEZNAMY/TAB#261]
1.16.4

[TAB v2.8.10]

Tab won't load after updating to above mentioned version, it shows the Vanilla Tab.

![hmmm](https://user-images.githubusercontent.com/71344054/103808286-0bc90680-5058-11eb-9746-831576e1efc3.PNG)

**Comment by NEZNAMY** [comment]
Looks like you did something unexpected in your groups section. Show your config.

**Comment by ImperatusMaximus** [comment]
https://pastebin.com/N0F5KfYp

**Comment by NEZNAMY** [comment]
Delete line 91

**Comment by ImperatusMaximus** [comment]
although i never changed anything within the config before updating...

**Comment by ImperatusMaximus** [comment]
![unknown](https://user-images.githubusercontent.com/71344054/103824850-fd3d1800-5074-11eb-9669-319db1a86f8e.png)


moderator reported that "%animation:servername%" and "Time Played:" stopped working.

Guess users need to reset their config for this update

**Comment by NEZNAMY** [comment]
No config reset is needed, unless it intentionally contains null values. That animation may not be valid, otherwise check errors.txt file in tab's folder.

**Comment by ImperatusMaximus** [comment]
Why did it stop working after updating? I mean if i go back one Version both values start working again

But sure, i check error.txt again

**Comment by NEZNAMY** [comment]
The error was thrown due to a new misconfiguration check which did not expect null value there so it failed completely.
