### ISSUE TITLE
Hex Bold Bug on Tab

### ISSUE THREAD

**Issue by zainmz** [NEZNAMY/TAB#263]
**Server version**
1.16.4 Paper Spigot

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**

When using hex color codes with &l causes the entire row to be bold and &r does not function

example line of config:

`tabprefix: "&#B03A2E&lTEST &r "`

**How to reproduce**
Use a hex colour code and bold to a text

**Expected behavior**
Hex colored part should be bold where as the remaining should not when using &r

**Actual behavior**
&r Does not work with hex can be seen in image

**Additional info** (errors, screenshots, ...)
Config https://i.imgur.com/sCYRPbj.png
In- game  https://i.imgur.com/HHy0mnC.png

**Comment by NEZNAMY** [comment]
Can you join discord and ask for a fixed version?

**Comment by zainmz** [comment]
Alright will do
