### ISSUE TITLE
LuckPerms prefixes not showing if TAB is installed on Waterfall

### ISSUE THREAD

**Issue by ParicBat** [NEZNAMY/TAB#264]
**Server version**
Paper 1.8.8-R01 and Waterfall 1.16-R0.4

**Plugin version** 
2.8.10

**Describe the bug**
LuckPerms prefixes not showing if TAB is installed on Waterfall (Paper Bungeecord)

**How to reproduce**
Install LuckPerms on both proxy and backend, and install TAB on the proxy. (PAPI and TAB-BukkitBridge on backend too)

**Expected behavior**
Show the prefixes in the Tab menu.

**Actual behavior**
Prefixes aren't showing in the Tab menu.

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/47944384/104121624-0281b780-5340-11eb-9356-a04face17d45.png)

![image](https://user-images.githubusercontent.com/47944384/104121610-ebdb6080-533f-11eb-812c-7c9cb33ece81.png)

**Comment by NEZNAMY** [comment]
As debug says, you did not configure ANYTHING.

**Comment by ParicBat** [comment]
Where can i configure to fetch the prefixes from LuckPerms or use the %luckperms_prefix% placeholder then?

**Comment by NEZNAMY** [comment]
Yes, or %luckperms-prefix% if you have LP on bungee and want TAB to take prefixes from there.

**Comment by ParicBat** [comment]
I get it all now, thanks!
