### ISSUE TITLE
NameTags

### ISSUE THREAD

**Issue by s7an1slaw** [NEZNAMY/TAB#265]
**Server version**
1.16.4

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
how can i make nametags visible by default. Before you tame a wolf and put a nametag, it is visible when you tame it and disappears, I tried a few settings in cfg and its work, but they shift the rank priorities in the tab list.
change-nametag-prefix-suffix: true -> false

**Additional info** (errors, screenshots, ...)
![2021-01-12_11 56 19](https://user-images.githubusercontent.com/67442642/104300016-9bded400-54ce-11eb-9cf0-a6a1e5b6aaf6.png)
![Screenshot_1574](https://user-images.githubusercontent.com/67442642/104300148-c6309180-54ce-11eb-8deb-bee5f84cd4d1.png)
![Screenshot_1573](https://user-images.githubusercontent.com/67442642/104300251-e8c2aa80-54ce-11eb-86c9-1669a4fc5508.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
