### ISSUE TITLE
Bungee: server-group %serveronline% placeholder is not showing player online count of server group

### ISSUE THREAD

**Issue by galexrt** [NEZNAMY/TAB#266]
**Server version**
PaperMC 1.16.4 build 416

**Plugin version** ("latest" is not a version)

2.8.10 Premium

**Describe the bug**

The `%serveronline%` placeholder is the player online count of the server the user is on and not the player online count of the server-group the server is part of.

E.g., server-123 and server-456 are part of the `server-group` `myservers`.

Is this expected behavior or is there a way to display the online player count of the server-group instead of just the server the user is online?

**Comment by Tanguygab** [comment]
this is the expected behavior
> %serveronline%              - amount of online players on server where the player is

**Comment by NEZNAMY** [comment]
This is intended behavior. The placeholder has nothing to do with global playerlist feature.

**Comment by galexrt** [comment]
I see. Thanks for the quick responses!
