### ISSUE TITLE
Plugins variable

### ISSUE THREAD

**Issue by ItzMarniiiii** [NEZNAMY/TAB#267]
**Server version** 1.16.4

**Plugin version** 2.8.10

How do i get a variable that shows how many plugins the server uses

**Comment by NEZNAMY** [comment]
TAB does not have such placeholder.

**Comment by ItzMarniiiii** [comment]
Can i create one?

**Comment by NEZNAMY** [comment]
You can using PlaceholderAPI https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by ItzMarniiiii** [comment]
And how do i use the plugins variable from PlaceholderAPI

**Comment by NEZNAMY** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion

**Comment by ItzMarniiiii** [comment]
So i need to code? bcuz im rlly bad at coding XD

**Comment by NEZNAMY** [comment]
Yes.

> TAB does not have such placeholder.

**Comment by ItzMarniiiii** [comment]
I guess no Plugins variable for me ;p

**Comment by NEZNAMY** [comment]
Not adding placeholders only one person will use.
