### ISSUE TITLE
Not working with luckperms 

### ISSUE THREAD

**Issue by RobellaRose** [NEZNAMY/TAB#272]
**Server version**
1.16.4

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
I'm using LuckPerms, and my default rank is set up with the correct parents/priority, but no matter what I do in the config it won't let donor/staff tags show up over default tags. 

**How to reproduce**
N/A

**Expected behavior**
To have VIP/Staff rank tags show up when they're promoted to those ranks and not have the default rank be pushing. 

**Actual behavior**
Default rank is pushing priority. 

**Additional info** (errors, screenshots, ...)
Unclear how to submit a ticket from the Discord and Spigot website, so I'm not sure if this is the correct way to do it and I apologize if it's incorrect and I can submit it however I'm supposed to.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist

**Comment by RobellaRose** [comment]
I set my group list as this:
group-sorting-priority-list:
  - owner
  - admin
  - mod
  - vip
  - member
  - default
  
And enabled permissions sorting in the config. 
  
I think the problem has something to do with my default ranks? If staff/VIPs are within that track the tag defaults and the animated tag isn't working. The tag is showing up it seems now, but the animation isn't working. 

http://prntscr.com/xvouay - without default rank
http://prntscr.com/xvovcp - with default rank

**Comment by RobellaRose** [comment]
Also gave players permissions nodes: tab.sort.<group> as well with no luck.

**Comment by NEZNAMY** [comment]
Just sort by groups if you don't know how to negate permissions in your permission plugin.

**Comment by RobellaRose** [comment]
I sorted by groups in the config, but the animated tags still aren't working. Seems everyone has the proper tag now, but I'm not sure what to do about the animations.

**Comment by NEZNAMY** [comment]
Did you actually configure it to show animations? 
https://github.com/NEZNAMY/TAB/wiki/Animations
Check /tab debug <player> to see group, prefix source and other useful info.

**Comment by RobellaRose** [comment]
I did make animations for the tags, and they work only if players aren't in the default group for whatever reason. If they're in the default group, it sets it to their tag in chat, not the tab prefixes.

**Comment by NEZNAMY** [comment]
Find out why using /tab debug <player>

**Comment by RobellaRose** [comment]
Thank you so much for your time, I figured it out. Thank you again so much for your help!
