### ISSUE TITLE
customtagname: "%essentialsnick%" doesn't work

### ISSUE THREAD

**Issue by KillsT3aler69** [NEZNAMY/TAB#273]
**Server version** 
1.16.1

**Plugin version** 
2.8.4

**Describe the bug**
In the config the 'customtagname' is set to "%essentialsnick%", but it doesn't work. When I change 'customtagname' to "test" for example the changes do apply. The line above is 'customtabname' and this is also set to "%essentialsnick%" and this works as intended.

**How to reproduce**
Set the 'customtagname' to "%essentialsnick%" and afterwars set it to something else (for exampe "test").

**Expected behavior**
When 'customtagname' is set to "%essentialsnick%" it should show the nickname of the player and when it is et to "test" it should show test above the player's head.

**Actual behavior**
When 'customtagname' is set to "%essentialsnick%" it shows the username of the player (not the nickname) and when it is et to "test" it does show test above the player's head.

**Additional info** (errors, screenshots, ...)
 PlaceholderAPI is installed. And the nickname does work on the tablist.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-nick-plugins
http://prntscr.com/yiyjmc "Note: customtagname requires unlimited nametag mode enabled to work."

**Comment by P1ticko** [comment]
Hello, how can i now have white name and using plugins like eGlow, FancyGlow? I do not have in config unlimited-nametag-mode, and customtagname in groups doesnt work... :( Please help

**Comment by NEZNAMY** [comment]
> Hello, how can i now have white name and using plugins like eGlow, FancyGlow? I do not have in config unlimited-nametag-mode, and customtagname in groups doesnt work... :( Please help

https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins

**Comment by NEZNAMY** [comment]
You cannot do that anymore with only TAB. You'll need to find another plugin.

**Comment by P1ticko** [comment]
> You cannot do that anymore with only TAB. You'll need to find another plugin.

Oh, and that must be another plugin of TAB, or TAB + something? Do u know some? It can be paid please 🥹

**Comment by NEZNAMY** [comment]
https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c#what-can-you-do
some are linked on the bottom.

**Comment by P1ticko** [comment]
> https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c#what-can-you-do some are linked on the bottom.

Thank you! Il try it! 😊
