### ISSUE TITLE
Could not load 'plugins/TAB-BukkitBridge v1.3.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Martinko366** [NEZNAMY/TAB#275]
**Server version**
BungeeCord 1.8.x - 1.16.x (Servers: Paper 1.8.8 and Paper 1.16.5)

**Plugin version**
TAB v2.8.10 and TAB-BukkitBridge v1.3

**Describe the bug**
Sorting and nicknames in the TAB are normal, however it's not showing the header and footer and some things don't work eather. I checked console: [ERROR] Could not load 'plugins/TAB-BukkitBridge v1.3.jar' in folder 'plugins'

**How to reproduce**
Add TAB to Bungee, set sorting groups, tag and tab prefixes and then add Bridge to all Paper Spigot servers.

**Expected behavior**
Should show Header and Footer and make tag prefixes

**Actual behavior**
Header and Footer did not showed up, instead it is showing blank line - space between list and tablist border. Tag prefixes don't work too.

**Comment by NEZNAMY** [comment]
I followed your steps and everything works.
TAB is on bungeecord, header and footer displaying correctly http://prntscr.com/yyfh6b
bridge enabled successfully (no error, only having this one message http://prntscr.com/yyflwg)
tagprefix works http://prntscr.com/yyfrk3

**Comment by Martinko366** [comment]
Weird, I have PAPI on the server - working, here's the screenshot of how the TAB looks like, however, the tagprefix works now
[https://ctrlv.sk/ESxL](url)

**Comment by NEZNAMY** [comment]
Send your config of tab & the full bridge error.

**Comment by Martinko366** [comment]
`# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - Lobby
    - Auth
header:
- '&3&lGalaxySide.eu'
footer:
- '&7Nezabudnite navštíviť náš web: www.galaxyside.eu'
yellow-number-in-tablist: '%ping%'
group-sorting-priority-list:
- hl.admin
- admin
- hl.developer
- hl.helper
- hl.builder
- developer
- el.helper
- helper
- el.builder
- builder
- zk.developer
- zk.helper
- zk.builder
- vip+
- vip
- default
Groups:
  hl.admin:
    tabprefix: '&4&lHL.ADMIN &c'
    tagprefix: '&4&lHL.ADMIN &f'
  admin:
    tabprefix: '&4&lADMIN &c'
    tagprefix: '&4&lADMIN &f'

  hl.developer:
    tabprefix: '&6&lHL.DEV &e'
    tagprefix: '&6&lHL.DEV &f'
  hl.helper:
    tabprefix: '&2&lHL.HELPER &a'
    tagprefix: '&2&lHL.HELPER &f'
  hl.builder:
    tabprefix: '&5&lHL.BUILDER &d'
    tagprefix: '&5&lHL.BUILDER &f'

  el.helper:
    tabprefix: '&a&lEL.HELPER &f'
    tagprefix: '&a&lEL.HELPER &f'
  el.builder:
    tabprefix: '&d&lEL.BUILDER &f'
    tagprefix: '&d&lEL.BUILDER &f'

  developer:
    tabprefix: '&e&lDEV &f'
    tagprefix: '&e&lDEV &f'
  helper:
    tabprefix: '&a&lHELPER &f'
    tagprefix: '&a&lHELPER &f'
  builder:
    tabprefix: '&d&lBUILDER &f'
    tagprefix: '&d&lBUILDER &f'

  zk.developer:
    tabprefix: '&7&lZK.DEV &f'
    tagprefix: '&7&lZK.DEV &f'
  zk.helper:
    tabprefix: '&7&lZK.HELPER &f'
    tagprefix: '&7&lZK.HELPER &f'
  zk.builder:
    tabprefix: '&7&lZK.BUILDER &f'
    tagprefix: '&7&lZK.BUILDER &f'

  vip+:
    tabprefix: '&5&lVIP+ &f'
    tagprefix: '&5&lVIP+ &f'
  vip:
    tabprefix: '&2&lVIP &f'
    tagprefix: '&2&lVIP &f'
  default:
    tabprefix: '&8'
    tagprefix: '&8'

  example_group:
    header:
    - This is an example of per-group header/footer
    footer:
    - applied to a group
  _OTHER_:
    tabprefix: '&7'
    tagprefix: '&7'
Users:
  _NEZNAMY_:
    tabprefix: '&6&lTAB Author &a'
    tagprefix: '&6&lTAB &r&a'
classic-vanilla-belowname:
  enabled: false
  number: '%ping%'
  text: Ping
enable-collision: true
revert-collision-rule-in-worlds:
- revertedworld
do-not-move-spectators: false
allow-spectator-bypass-permission: false
per-server-settings:
  server1:
    header:
    - an example of world with custom
    footer:
    - header/footer and prefix/suffix
    Groups:
      Owner:
        tabprefix: '&0&l[&a&lOwner&0&l] &a'
        tagprefix: '&2&lOwner &a'
  server2-server3:
    header:
    - This is a shared header for
    - server2 and server3
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  remove-strings:
  - '[]'
  - < >
server-aliases:
  Lobby: 'Lobby'
  Auth: 'Auth'
  Survival: 'Survival'
  KBFFA: 'KnockbackFFA'
rank-aliases:
  Admin: '&4&lADMIN'
  Mod: '&b&lMOD'
  Premium: '&6&lPREMIUM'
  Ultra: '&b&lULTRA'
  Legend: '&a&lLEGEND'
  Titan: '&c&lTITAN'
  Youtuber: '&c&lYOUTUBE'
  _OTHER_: '&7No Rank'
disable-features-in-servers:
  header-footer:
  - disabledserver
  tablist-names:
  - disabledserver
  nametag:
  - disabledserver
  yellow-number:
  - disabledserver
  bossbar:
  - disabledserver
  belowname:
  - disabledserver
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 500
sort-players-by-permissions: false
use-primary-group: true
primary-group-finding-list:
- Owner
- Admin
- Helper
- default
assign-groups-by-permissions: false
revert-collision-rule-in-servers:
- revertedserver
`

With bridge, there is no error, there is just **Could not load 'plugins/TAB-BukkitBridge v1.3.jar' in folder 'plugins'**

**Comment by NEZNAMY** [comment]
Send the full log then, I will read the error message myself. Header/footer works http://prntscr.com/yzs9e2

**Comment by Martinko366** [comment]
I realized that the plugin loaded after 3 restarts. But it's still not working like it should... https://pastebin.com/z1PS8TcT

**Comment by NEZNAMY** [comment]
Bridge is enabled. Header/footer works for me with your config.

**Comment by Martinko366** [comment]
I'll try to remove TAB from plugins and then again adding it back

**Comment by Martinko366** [comment]
I found problem in the plugin on Bungee - once I set header and footer, it'll show for split of a second.

**Comment by Martinko366** [comment]
After reload it's for few seconds it looks normal but placeholders not work, then it will change to nothing: https://ctrlv.sk/Oomu then it

**Comment by NEZNAMY** [comment]
Some plugin is probably overriding tab. Try latest build from https://github.com/NEZNAMY/TAB/releases which introduces anti-override for header/footer. Placeholders are not working because you are missing ending % after "%online".

**Comment by NEZNAMY** [comment]
At this point you should just join discord for faster help.

**Comment by NEZNAMY** [comment]
Solved on discord, issue fixed itself.
