### ISSUE TITLE
Correct RGB in prefix but not in username

### ISSUE THREAD

**Issue by Artuto** [NEZNAMY/TAB#276]
**Server version** 1.16.5

**Plugin version** ("latest" is not a version) 2.8.10

How it should look;

![image](https://user-images.githubusercontent.com/9273973/108019074-00fe7b80-6fdf-11eb-8e92-9c465c0a9047.png)

How it is on nametag (notice the darker red of the name):

![image](https://user-images.githubusercontent.com/9273973/108019116-1673a580-6fdf-11eb-83eb-5a9c81bb85ee.png)

The hex is #ff0e00

**Comment by NEZNAMY** [comment]
Read limitations page on wiki.
