### ISSUE TITLE
Spyservers don't respect vanished users

### ISSUE THREAD

**Issue by ChipWolf** [NEZNAMY/TAB#278]
As this line of code runs after the assertion that a user in a spyservers world, all users in spyservers see vanished users in the tablist despite not having permission to
https://github.com/NEZNAMY/TAB/blob/0e7a445fbeb76d9ab89d96731621da8b4e7f55b3/src/main/java/me/neznamy/tab/shared/features/GlobalPlayerlist.java#L57

**Comment by NEZNAMY** [comment]
I am assuming swapping lines 56 and 57 would fix this, right?

**Comment by ChipWolf** [comment]
I reckon so @NEZNAMY based on my 5 seconds of looking at it :joy:
There may be more to it
