### ISSUE TITLE
Not really an issue but i wanted to say thank you

### ISSUE THREAD

**Issue by CEbbinghaus** [NEZNAMY/TAB#279]
You have no idea how happy I was to find out that this project is open source. I was trying to figure out how exactly one part, in particular, worked because there was hardly any documentation about it but thanks to its open-source nature I can just read up what happens and infer the rules around it from that. 

in the README you said
> It's already been a year and I still can't see any positives of it. This way I just made it easier for everyone to make a plugin as good, so people can stop using it and switch to something better.

But I truly believe that making it open source doesn't make it any more likely for someone to steal the idea. In fact in my experience, either someone creates the same thing without realizing that something already exists or they contribute to the thing that does exist adding functionality that wasn't there previously.

So I guess what I am saying is Thank you. For creating this awesome plugin in the first place, and open-sourcing it to give the community the ability to help and work on making a better plugin alongside you. 

Regards,

A Programming enthusiast and Minecraft fan

**Comment by NEZNAMY** [comment]
> because there was hardly any documentation about it
May I know which part are you referring to?

**Comment by CEbbinghaus** [comment]
Oh it had to do with the replacement of placeholders. Took 200 google searches and i ended up finding it in a readme

**Comment by NEZNAMY** [comment]
This https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements-(premium-only) ?

**Comment by CEbbinghaus** [comment]
> This https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements-(premium-only) ?

did not see that you had sent a message. yes, it had to do with the placeholder output. IIRC it was about coloring or something similar but its been so long ago
