### ISSUE TITLE
Sort alphabetically when not sorting by rank

### ISSUE THREAD

**Issue by TheMattVid** [NEZNAMY/TAB#28]
Hello, my server involves a gamemode where one player has a secret rank for a week. I also like having the server's staff sorted at the top. Under the "group-sorting-priority-list:", I have only listed the four staff ranks as what I want sorted. Ideally, those who do not fall within these four ranks get sorted alphabetically. However, ranks not specified in the priority list are still getting sorted by rank, resulting in the secret rank potentially not being such a secret. The workaround for now is to just have the entire list sorted alphabetically, but it would be nice if I could stick with the rank-based sorting without having non-specified ranks be sorted.

**Comment by NEZNAMY** [comment]
You have two options:
- make player's primary group something different than the secret group (either in you perm plugin or enable the option in advancedconfig if player is in more groups)
- clear sorting list and players will be sorted alphabetically by their (replaced) tabprefix.
