### ISSUE TITLE
Issue with suffix.

### ISSUE THREAD

**Issue by Uzomezo** [NEZNAMY/TAB#280]
Hello i'm doing a bungee server and i have and issue. I've made a donator rank with only a suffix and i want that when you're have it there is only a star showing. But i can't find a way to have this star on the other ranks without creating 100 ranks

**Comment by NEZNAMY** [comment]
tabsuffix: "%luckperms-suffix%" for `_OTHER_` group to make it default tabsuffix for all groups.

**Comment by Uzomezo** [comment]
Thanks!

**Comment by Uzomezo** [comment]
I have another issue. The symbol that I use is ☆. It doesn't show when i'm using the %luckperms-suffix% placeholder

**Comment by NEZNAMY** [comment]
Configure the symbol in luckperms.

**Comment by Uzomezo** [comment]
The problem is that the symbol is configured. Like it shows on chat but not in tab

**Comment by NEZNAMY** [comment]
Find out using /lbp user <player> info. If suffix shows the symbol, you did not configure TAB correctly. You can check tabsuffix and it's source using /btab debug <player>.

**Comment by Uzomezo** [comment]
![2021-02-27_12 58 00](https://user-images.githubusercontent.com/79749082/109386526-7893ab00-78fb-11eb-8688-17ce95357c82.png)

**Comment by NEZNAMY** [comment]
Did you find out using /lpb user info and /btab debug?

**Comment by Uzomezo** [comment]
Kind of

**Comment by Uzomezo** [comment]
Yes sure, where do i need to go to close it
