### ISSUE TITLE
Nametag is not affected by crawling or gliding

### ISSUE THREAD

**Issue by VoltroXP** [NEZNAMY/TAB#282]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
When players are given custom nametags to where they become invisible armor stands, if they enter a state of crawling or gliding their nametag does not lower. However, it does lower when players enter a state of swimming.

**How to reproduce**
Apply a custom prefix, suffix, or above name to a player's name, have them stand under an open trapdoor, and close it. Their name doesn't lower and will remain well over a block above them.

**Expected behavior**
The player's name should lower when they crawl/glide, as it does when a player swims.

**Actual behavior**
It doesn't lower, just stays in the same place.

**Additional info** (errors, screenshots, ...)
As a side now, it would be nice if the plugin provided the option to keep the username as vanilla (so, not an armor stand), but add the abovename as an armor stand.

**Comment by NEZNAMY** [comment]
Adding abovename as armor stand but keeping vanilla name would just make the bug that much more visible. And the rest of the code more complicated as it wouldn't even allow belowname as vanilla name's height cannot be changed,

**Comment by NEZNAMY** [comment]
When was this added? In 1.13?

**Comment by VoltroXP** [comment]
Crawling was added in I believe 1.14, while gliding was added earlier in
1.9. Not sure if the name tag being moved down while flying was added back
then though
