### ISSUE TITLE
Setting a vanilla scoreboard to display to certain teams with sidebar.team.<color> does not work properly

### ISSUE THREAD

**Issue by RavingPlatypi** [NEZNAMY/TAB#287]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
Scoreboards that are set to display on the sidebar only to a specific team display to all players instead.

**How to reproduce**
Create a new team and scoreboard objective:
`/team add challenge`
`/scoreboard objectives add snowballsThrown minecraft.used:minecraft.snowball`

Modify the team and set the color to white for the team. Then join the team:
`/team modify challenge color white`
`/team join challenge RavingPlatypi`

Set the sidebar for team white to display snowballsThrown:
`/scoreboard objectives setdisplay sidebar.team.white snowballsThrown`

**Expected behavior**
Leaving the team should mean the scoreboard is not displayed to you.

**Actual behavior**
Leaving the team has no effect on the display of the scoreboard. Every player can see the scoreboard despite not being on that team. I have tested it with other team colors, like gray, and I got the same thing.

**Additional info** (errors, screenshots, ...)
Let me know if you need any more information. I know for a fact that this is caused by TAB because I enabled and disabled plugins until I could find the issue. When only TAB was running I got this behavior. Disabling TAB meant the scoreboard behaved how it was supposed to.

Thanks!

**Comment by Tanguygab** [comment]
TAB manages teams, so yeah it can't work.
If you want a fix, disable change-nametag-prefix-suffix in config.

**Comment by RavingPlatypi** [comment]
> TAB manages teams, so yeah it can't work.
> If you want a fix, disable change-nametag-prefix-suffix in config.

Gotcha. I tried that and I get my intended behavior with the scoreboard, but my TAB group sorting order is completely messed up. Is that supposed to happen?

**Comment by Tanguygab** [comment]
yeah, players are sorted by thanks to teams, if TAB doesn't manage teams, then it won't sort players

**Comment by RavingPlatypi** [comment]
Dang :/ any workarounds? I want my tab list sorted but I also want my players to be able to toggle the scoreboard visibility on and off. Can I make due with what I have already or do I need to find a plugin to handle the scoreboard separately?

**Comment by Tanguygab** [comment]
maybe you could use TAB's scoreboard feature, but it would require premium tho. else, idk what could be done.

**Comment by RavingPlatypi** [comment]
Alright. Well thanks for the help; I really appreciate the quick responses!

**Comment by Tanguygab** [comment]
actually, it may not work, I don't know how you would be able to link it with vanilla statistics
