### ISSUE TITLE
[Feature Request] Libs Disguises Support

### ISSUE THREAD

**Issue by Leomelonseeds** [NEZNAMY/TAB#288]
Hello there,

It would be very nice if disguising as a player using Libs Disguises also included the custom nametag found in the TAB plugin. Would this be possible to integrate?

Thank you very much.

**Comment by NEZNAMY** [comment]
No, since you can disguise as any player and TAB wouldn't know what value to apply, especially for offline/non-existng players.

**Comment by Leomelonseeds** [comment]
Ah, it would not be necessary for offline/non-existing players. Only online players. The nametag could then be disabled if the player you are disguised as logs off.

**Comment by NEZNAMY** [comment]
Future version will have an option to disable function preventing other plugins from changing player names so it should work for you then.

**Comment by Leomelonseeds** [comment]
Sounds good, thank you!

**Comment by NEZNAMY** [comment]
Done https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre9
