### ISSUE TITLE
Tab complete

### ISSUE THREAD

**Issue by iGabyTM** [NEZNAMY/TAB#290]
Make tab complete only work for people with permission because players can use commands such as `/tab player <tab>` to see who is on vanish (I'm using SuperVanish).

**Comment by NEZNAMY** [comment]
Which permission specifically should allow this one? Since there's a different permission for each property, we can't know in advance what will user want.

**Comment by iGabyTM** [comment]
According to [wiki](https://github.com/NEZNAMY/TAB/wiki/Commands-&-Permissions) there is a permission for commands that accept `player` as first argument. [Here](https://github.com/NEZNAMY/TAB/blob/master/src/main/java/me/neznamy/tab/shared/command/level1/PlayerCommand.java#L84) you can add a check for permission, but you are right, you need to know which command they are willing to use.
I haven't used TAB for too long but if I'm not wrong, commands such as `/tab <player/group/playeruuid> <name> <property> [value]` are for admins only, so could probably require the player to have an extra permission called `tab.admincommands`.

**Comment by piotrskibapl** [comment]
@NEZNAMY I would also suggest making tab completions show only players that you can actually see. Right now it is exposing vanished players.

**Comment by Tanguygab** [comment]
I guess you could add a check if the player is vanished or add an argument for the player who tab-completes and check if he can see the player in the list [here](https://github.com/NEZNAMY/TAB/blob/8805d0666b72a3c188b2c1964cbe3539e55661de/src/main/java/me/neznamy/tab/shared/command/SubCommand.java#L111)

**Comment by iGabyTM** [comment]
> I guess you could add a check if the player is vanished or add an argument for the player who tab-completes and check if he can see the player in the list [here](https://github.com/NEZNAMY/TAB/blob/8805d0666b72a3c188b2c1964cbe3539e55661de/src/main/java/me/neznamy/tab/shared/command/SubCommand.java#L111)

That would also work but why not disable the completion at all for admin related commands?

**Comment by Tanguygab** [comment]
could work aswell I guess, idk

**Comment by Tanguygab** [comment]
because it's true that you can't check if you have a permissions that starts with a specific string, only chefk if you have the exact perm

**Comment by NEZNAMY** [comment]
There already is tab.admin permission, should that one be used? Or another separate permission for tabcomplete?

**Comment by piotrskibapl** [comment]
I guess tab.admin would be ideal, I don't see a need to add another permission for that.

**Comment by NEZNAMY** [comment]
So basically replacing this line https://github.com/NEZNAMY/TAB/blob/master/src/main/java/me/neznamy/tab/shared/command/TabCommand.java#L109 with a permission check would do it, right? It would disable tabcomplete entirely.

**Comment by iGabyTM** [comment]
That sounds good

**Comment by NEZNAMY** [comment]
Done https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre10
