### ISSUE TITLE
Change name with our API

### ISSUE THREAD

**Issue by xHyroM** [NEZNAMY/TAB#291]
Hello,
How change displayName and nametag with out API?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Developer-API#changing-prefixnamesuffix

**Comment by xHyroM** [comment]
How change player priority in tablist?

**Comment by NEZNAMY** [comment]
Will be added in next version https://github.com/NEZNAMY/TAB/commit/b375c2434077f5a245146af61567d072aad3fa02
