### ISSUE TITLE
Nametag appears be standing after player disconnect

### ISSUE THREAD

**Issue by fra130701** [NEZNAMY/TAB#292]
**Server version**
This server is running Yatopia version git-Yatopia-ver/1.16.5-42 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin version**
2.8.11-pre9

**Describe the bug**
Sometimes it happens that when the server drops in TPS and the players disconnect the names above the skin remain anyway, to make them disappear just re-join the server

https://imgur.com/a/Tx3Pg31
https://imgur.com/ePR8AkQ

**Comment by NEZNAMY** [comment]
Is it related to switching worlds?

**Comment by fra130701** [comment]
I don't know, but i thing no

**Comment by fra130701** [comment]
I have TAB on 3 different servers, one 20 tps 1.16.5, one 12-16 tps with 1.16.5 and one 1.12.2 with 20* tps, but the 12-16tps has this problem

**Comment by NEZNAMY** [comment]
@fra130701 can you try with latest build?

**Comment by zeterm0d** [comment]
> @fra130701 can you try with latest build?

I have the same problem. It really sometimes happends.

**Comment by fra130701** [comment]
Problem has been fixed with latest dev builds.
Thanks!
