### ISSUE TITLE
Deluxe Tags and Factionuuid Prefixes

### ISSUE THREAD

**Issue by sisilic96** [NEZNAMY/TAB#293]
Hello NEZNAMY, i wish for you help.
I don't know what i am doing wrong. Deluxe tags ands faction tag never shown on tab list.
I will show you what i did do and i will send you the config file.

PlaceholderAPI last version downloaded.
Deluxe Tags last version downloaded.
Deluxe Tags hooked PAPI with '/papi ecloud download DeluxeTags'.
Unlimitednametag prefix/suffix mode enabled.
But when i write ("%vault-prefix%%deluxetags_tag%") to tab prefix section, prefix is just being (%deluxetags_tag%).
I also want to see faction names(%factionsuuid_faction_name%) as tagprefix and also this isn't working for me.
I did try every variables in my mind.
I did look the issues section one by one and i didn't see anybody with having this issue.
I've been working for this job for two days and i am tired. I don't know am i doing a little mistake or something else.
Can you help me to figure it out please. Have a good day.

a deep note: i am not using groups section because it's useless for my server.

![1](https://user-images.githubusercontent.com/82086333/113847208-e73c1200-979f-11eb-86d7-ff10437f0cdb.png)
![2](https://user-images.githubusercontent.com/82086333/113847211-e7d4a880-979f-11eb-826e-48967c209ebe.png)
![3](https://user-images.githubusercontent.com/82086333/113847213-e7d4a880-979f-11eb-8cc7-f90ce96ec3bf.png)

Config:
# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

#changing nametags, affecting sorting, collision rule
change-nametag-prefix-suffix: true

#prefix/suffix in tablist
change-tablist-prefix-suffix: true

#header/footer
enable-header-footer: true

header:
  - "&4&lAKİRACRAFT"
  - "    &7&l>> &7Hoşgeldin &4%nick%&7! &7&l<<"
  - "&7Aktif Oyuncu: &f%online%"
  - "%animation:MyAnimation1%"
footer:
  - "%animation:MyAnimation1%"
  - '&7Geliştirmeler Devam Ediyor'
  - '&4www.akiraminecraft.com'
  - '&f%time%'

#supports any numeric placeholder, set to "" to disable the feature
yellow-number-in-tablist: "%ping%"

#literally what it says
group-sorting-priority-list:
  - kurucu
  - admin
  - mod
  - helper
  - builder
  - premium
  - oyuncu
  - default

Groups:
  O:
    tabprefix: "&0&l[&a&lOwner&0&l] &a"
    tagprefix: "&2&lOwner &a"
  A:
    tabprefix: "&0&l[&4&lAdmin&0&l] &1"
    tagprefix: "%animation:admin_prefix%"
  P:
    tabprefix: "&0&l[&7&lPlayer&0&l] &3"
    tagprefix: "&2&lPlayer &3"
  example_group:
    header:
      - "This is an example of per-group header/footer"
    footer:
      - "applied to a group"
      
  #default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
  _OTHER_:
    tabprefix: "%vault-prefix%%deluxetags_tag%"
    tagprefix: "%vault-prefix%%factionsuuid_faction_name%"
    tabsuffix: ""
    tagsuffix: ""
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"

Users:
  _NEZNAMY_:
    tabprefix: "&6&lTAB Author &a"
    tagprefix: "&6&lTAB &r&a"
    abovename: "&bOh look, 3 lines of text !"
    belowname: "&eThere's only one plugin out there supporting it"

#additional very limited line of text below nametag
#don't forget this enables on all player entities, which includes NPCs
#tags so you can find this section using the mighty ctrl + f feature: [NPC, Citizens, below_name, health]
classic-vanilla-belowname:

  #enabling the feature
  enabled: false
  
  #number or numeric placeholder, supports per-player placeholders
  number: "%health%"
  
  #text after number, must be same on all players
  text: "Health"

#controlling the collision rule
enable-collision: true

#using the opposite of the setting above for worlds
revert-collision-rule-in-worlds:
  - revertedworld
  
#preventing players with spectator gamemode from being moved to the bottom of tablist with transparent name
do-not-move-spectators: false

#allows players with tab.spectatorbypass permission to see spectators moved despite the option above enabled
allow-spectator-bypass-permission: false

#using armor stands for nametags, bypassing all limits
#THEY ARE CLIENT SIDED AND DO NOT EXIST ON SERVER SO STOP SAYING YOUR SERVER IS LAGGING FROM THIS
unlimited-nametag-prefix-suffix-mode:

  #enabling the feature
  enabled: true
  
  #enabling will result in NPCs ignoring nametag prefix/suffix/visibility to prevent NPCs with names of online players from being invisible
  modify-npc-names: false
  
  #using a feature introduced in 1.8.1 to make hitbox zero so you can't cry it affects pvp despite hit redirection
  #1.8.0 clients will see wild things
  #automatically enabled for 1.9+
  use-marker-tag-for-1-8-x-clients: false
  
  #disabling the feature for players riding boats to prevent massive desync
  disable-on-boats: true

per-world-settings:
  world1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
        
  #separating multiple worlds with "-"
  world2-world3:
    header:
      - "This is a shared header for"
      - "world2 and world3"

placeholders:
  #output of %afk%
  afk-yes: " &4*&4&lAFK&4*&r"
  afk-no: ""
  
  #%date%
  date-format: "dd.MM.yyyy"
  
  #%time%
  time-format: "[HH:mm:ss / h:mm a]"
  
  #in hours, in case of wrong timezone
  time-offset: 0
  
  #don't forget color codes
  remove-strings:
    - "[]"
    - "< >"
    
#aliases for %rank%, this is not the place where group prefix is defined!
rank-aliases:
  Admin: "&4&lADMIN"
  Mod: "&b&lMOD"
  Premium: "&6&lPREMIUM"
  Ultra: "&b&lULTRA"
  Legend: "&a&lLEGEND"
  Titan: "&c&lTITAN"
  Youtuber: "&c&lYOUTUBE"
  _OTHER_: "&7No Rank"
  
disable-features-in-worlds:
  header-footer:
    - disabledworld
  tablist-names:
    - disabledworld
  nametag:
    - disabledworld
  yellow-number:
    - disabledworld
  bossbar:
    - disabledworld
  belowname:
    - disabledworld

placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 500
    
#different playerlist in different worlds
per-world-playerlist:

  #to enable the feature
  enabled: false
  
  #allows players with tab.bypass permission to see everyone in tablist despite this option enabled
  allow-bypass-permission: false
  
  #players in these worlds will see everyone despite the feature enabled
  ignore-effect-in-worlds:
    - ignoredworld
    - build
    
  #groups of worlds to share playerlist
  shared-playerlist-world-groups:
    #group name, can be anything
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars

#permission node is tab.sort.<permission group from sorting list>
sort-players-by-permissions: false

#making tamed animals no longer copy nametag properties from their owner (prefix/suffix/visibility)
#do not enable this if you're on paper, you'll feed the trolls even more
fix-pet-names: false

#taking primary group from permission plugin
use-primary-group: true

#if the option above is false, all groups are taken from permission plugin and the one higher in this list is used as primary
primary-group-finding-list:
  - Owner
  - Admin
  - Helper
  - default
  
#if none of the above fits your needs, you can enable this to give groups using tab.group.<group name from the list above> permission
assign-groups-by-permissions: false

**Comment by NEZNAMY** [comment]
Try /papi parse me %deluxetags_tag% and /papi parse me %factionsuuid_faction_name%. Do they work?

**Comment by sisilic96** [comment]
Not working thanks for fast reply:)

**Comment by NEZNAMY** [comment]
Then it's not a TAB issue if they don't work in papi parse command.

**Comment by sisilic96** [comment]
thanks for reply. have a good day.
