### ISSUE TITLE
[Suggestion] TAB BukkitBridge for Velocity.

### ISSUE THREAD

**Issue by satyrnhub** [NEZNAMY/TAB#294]
Would it be possible to make TAB BukkitBridge work on Velocity?

**Comment by NEZNAMY** [comment]
What should it do differently and what exactly is not working there?

**Comment by Tanguygab** [comment]
I think it should work, and if it doesn't, Velocity is unsupported by TAB anyways. The latest release still works on it but we do not provide any further support for it.

**Comment by satyrnhub** [comment]
Appears I had it setup incorrectly. I changed some things and TAB seems to work with Velocity just fine.
