### ISSUE TITLE
Change UPDATE_STYLE in Velocity platforms

### ISSUE THREAD

**Issue by HookWoods** [NEZNAMY/TAB#295]
Not a bug but actually a code change from velocity.
While reading the code in the velocity platform, I just saw this comment part:
https://github.com/NEZNAMY/TAB/blob/046366727035f661f3d07085648ccc401334defe/src/main/java/me/neznamy/tab/platforms/velocity/VelocityTabPlayer.java#L115

And Velocity recently push a commit that normally fix that bug, so the approach can be changed in the code I think now
https://github.com/VelocityPowered/Velocity/commit/4de71fe9426038ca7d0570c5968157c3a7a9cbad#diff-f57e1052d05e11f9ef85d9d0f97012f6f9c3a9a586a7119751f4904804a27086

**Comment by NEZNAMY** [comment]
I saw it, but it will take a while until last server stops using the affected versions (literally all of them), so I will keep the workaround code there for some time.

**Comment by HookWoods** [comment]
Ok, no problem!
