### ISSUE TITLE
Errors TAB

### ISSUE THREAD

**Issue by fra130701** [NEZNAMY/TAB#296]
**Server version**
1.12.2 paperspigot

**Plugin version** ("latest" is not a version)
2.8.12-pre12

**Describe the bug**
https://paste.lucko.me/oQKO9sq4oG

**Comment by NEZNAMY** [comment]
Looks like I didn't upload the fix yet.

**Comment by NEZNAMY** [comment]
Fixed https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre13
