### ISSUE TITLE
Online staff shows staff in vanish

### ISSUE THREAD

**Issue by jacobvd0** [NEZNAMY/TAB#297]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
v2.8.10

**Describe the bug**
I am using SuperVanish and when my staff vanish they still show in the online staff counter.

**How to reproduce**
Type /v when TAB and SuperVanish are installed

**Expected behavior**
Removes the staff member from the staff online count.

**Actual behavior**
Still shows the staff in the online staff counter

**Additional info** (errors, screenshots, ...)
![ss](https://user-images.githubusercontent.com/46667568/115142166-6c1c0b00-a07f-11eb-900e-8af1e6b86480.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#how-do-i-make-online-not-count-vanished-players-

**Comment by jacobvd0** [comment]
When I tried that still showed.
I reloaded the plugin when I did that. Does the server need a reboot for it
to work?

**Comment by NEZNAMY** [comment]
You need another player to look. You can see yourself.

**Comment by Jeffrey-H** [comment]
I also have an issue where players can see people in vanish in de first 0.5 seconds after they join. Maybe related?

**Comment by NEZNAMY** [comment]
TAB does not show/hide players.

**Comment by jacobvd0** [comment]
> You need another player to look. You can see yourself.

yes this worked, thank you.
