### ISSUE TITLE
Errors with pre13

### ISSUE THREAD

**Issue by fra130701** [NEZNAMY/TAB#298]
**Server version**
Paperspigot 1.12.2

**Plugin version** ("latest" is not a version)
2.8.11-pre13

**Describe the bug**
https://paste.lucko.me/DuMjVq8SZI

**Comment by NEZNAMY** [comment]
Reuploaded the version with fix, download it again https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre13.
