### ISSUE TITLE
There is a way to order this prefix parsed by placeholderapi?

### ISSUE THREAD

**Issue by fra130701** [NEZNAMY/TAB#299]
**Server version**
1.12.2 paperspigot

**Plugin version** ("latest" is not a version)
TAB pre13

There is a way to order this sufffixes?
![2021-04-18_15 25 13](https://user-images.githubusercontent.com/80008144/115147285-9a3b2400-a05a-11eb-8d22-e71dd9c66821.png)

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
You can sort by a placeholder with premium version.
