### ISSUE TITLE
Permissions EX bug

### ISSUE THREAD

**Issue by calaetare** [NEZNAMY/TAB#30]
07.09.2019 - 14:15:59 - [TAB v2.5.1] An error occured when setting placeholders(2) (player=Pericol123, online=true)
07.09.2019 - 14:15:59 - ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
07.09.2019 - 14:15:59 -        at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
07.09.2019 - 14:15:59 -        at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getUser(Chat_PermissionsEx.java:108)
07.09.2019 - 14:15:59 -        at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getPlayerPrefix(Chat_PermissionsEx.java:292)
07.09.2019 - 14:15:59 -        at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.bukkit.Placeholders.replaceSimplePlaceholders(Placeholders.java:151)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.bukkit.Placeholders.replace(Placeholders.java:106)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.shared.Placeholders.replace(Placeholders.java:123)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.shared.Placeholders.replaceMultiple(Placeholders.java:101)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.shared.ITabPlayer.updateTeamPrefixSuffix(ITabPlayer.java:348)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.shared.ITabPlayer.updateTeam(ITabPlayer.java:110)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.shared.NameTag16$1.run(NameTag16.java:22)
07.09.2019 - 14:15:59 -        at me.neznamy.tab.shared.Shared$2.run(Shared.java:149)
07.09.2019 - 14:15:59 -        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
07.09.2019 - 14:15:59 -        at java.util.concurrent.FutureTask.run(Unknown Source)
07.09.2019 - 14:15:59 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
07.09.2019 - 14:15:59 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
07.09.2019 - 14:15:59 -        at java.lang.Thread.run(Unknown Source)

**Comment by NEZNAMY** [comment]
Is the PermissionsEx plugin enabled?

**Comment by calaetare** [comment]
Yes

**Comment by calaetare** [comment]
iled to get permission group of samimilitariw0w (permission plugin: PermissionsEx)

**Comment by NEZNAMY** [comment]
This is a PEX bug i believe, multiple people reported this already. I'm not using instance of pex's main class that could change if reloaded for example, i'm using static access to pex. Because of that, i can't see what could i possibly do better to not get that error. I would consider this a pex bug.

**Comment by calaetare** [comment]
ok thanks
