### ISSUE TITLE
cant connect luckperms to tab

### ISSUE THREAD

**Issue by crazyfoxrider3** [NEZNAMY/TAB#302]
**Server version**
1.16
**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
i cant get tab to work with the perfixes i have in luck perms

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)

**Comment by MrGraycat** [comment]
[](https://github.com/NEZNAMY/TAB/wiki/Placeholders)

%luckperms-prefix% - prefix from LuckPerms
%luckperms-suffix% - suffix from LuckPerms

**Comment by crazyfoxrider3** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Placeholders
> 
> 

> https://github.com/NEZNAMY/TAB/wiki/Placeholders
> 
> %luckperms-prefix% - prefix from LuckPerms
> %luckperms-suffix% - suffix from LuckPerms

How do I do this do I just throw it into the bottom of the config file?

**Comment by crazyfoxrider3** [comment]
> **Server version**
> 1.16
> **Plugin version** ("latest" is not a version)
> 2.8.10
> 
> **Describe the bug**
> i cant get tab to work with the prefixes i have in luckperms
> 
> **How to reproduce**
> 
> **Expected behavior**
> 
> **Actual behavior**
> 
> **Additional info** (errors, screenshots, ...)

**Comment by MrGraycat** [comment]
> 
> 
> > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> 
> > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > %luckperms-prefix% - prefix from LuckPerms
> > %luckperms-suffix% - suffix from LuckPerms
> 
> How do I do this do I just throw it into the bottom of the config file?

Just use the placeholder wherever you want it to have

**Comment by crazyfoxrider3** [comment]
> > > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > 
> > 
> > > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > > %luckperms-prefix% - prefix from LuckPerms
> > > %luckperms-suffix% - suffix from LuckPerms
> > 
> > 
> > How do I do this do I just throw it into the bottom of the config file?
> 
> Just use the placeholder wherever you want it to have

What do you mean by this like how would I do it?

**Comment by MrGraycat** [comment]
> 
> 
> > > > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > > 
> > > 
> > > > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > > > %luckperms-prefix% - prefix from LuckPerms
> > > > %luckperms-suffix% - suffix from LuckPerms
> > > 
> > > 
> > > How do I do this do I just throw it into the bottom of the config file?
> > 
> > 
> > Just use the placeholder wherever you want it to have
> 
> What do you mean by this like how would I do it?

I'm not sure what you are expecting here, we can't read your mind neither are we going to configure the plugin for you.

Use the placeholder under any/all groups under Groups.

**Comment by crazyfoxrider3** [comment]
> > > > > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > > > 
> > > > 
> > > > > https://github.com/NEZNAMY/TAB/wiki/Placeholders
> > > > > %luckperms-prefix% - prefix from LuckPerms
> > > > > %luckperms-suffix% - suffix from LuckPerms
> > > > 
> > > > 
> > > > How do I do this do I just throw it into the bottom of the config file?
> > > 
> > > 
> > > Just use the placeholder wherever you want it to have
> > 
> > 
> > What do you mean by this like how would I do it?
> 
> I'm not sure what you are expecting here, we can't read your mind neither are we going to configure the plugin for you.
> 
> Use the placeholder under any/all groups under Groups.

Alright I’ll try that

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#taking-prefixessuffixes-from-permission-plugin
