### ISSUE TITLE
TAB doesn't updates the prefixes/config

### ISSUE THREAD

**Issue by DeathMario** [NEZNAMY/TAB#303]
Server Version:1.16.5

TAB version: 2.8.10

Describe the bug

Tab doesn't updates the config/prefixes

**Comment by NEZNAMY** [comment]
It does.

**Comment by DeathMario** [comment]
> It does.

Im trying to update a group prefix but it keeps showing the default

**Comment by DrWurzeli** [comment]
please join the discord and create a ticket to see whats wrong https://discord.gg/EaSvdk6
this will take ages to sort out on GitHub

**Comment by DeathMario** [comment]
> please join the discord and create a ticket to see whats wrong https://discord.gg/EaSvdk6
> this will take ages to sort out on GitHub

Okay

**Comment by DrWurzeli** [comment]
problems fixed themselves upon running the debug command. support tickets must really scare some servers.
