### ISSUE TITLE
Not an issue persay, More of a how to

### ISSUE THREAD

**Issue by L33B0B** [NEZNAMY/TAB#304]
Hi,
First off, been using your plugin for about 3/4months now and i love it! Without a doubt the best i've used!

Recently added Blaze And Caves advancement pack to my server and it allows the numberical placeholder to track the total advancements. But every time some one leaves or reconnects they get the default placeholder. In order to get it back on the TAB screen i have to turn the tab option off in the advancement pack then turn it back on.

Is there anyway to put the placeholder in the TAB config to point towards the advancement pack?

Thanks!

**Comment by MrGraycat** [comment]
TAB supports placeholderAPI placeholders

**Comment by NEZNAMY** [comment]
Or disable the feature in TAB by setting `yellow-number-in-tablist: ""`
