### ISSUE TITLE
Reload fail, what happen?

### ISSUE THREAD

**Issue by wudixiaoqiang** [NEZNAMY/TAB#305]
My server minecraft's ver. is Mhoist.  When i run "TAB reload", it tell to me :

27.04.2021 - 18:00:42 - [TAB v2.8.10] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
27.04.2021 - 18:00:42 - java.lang.IllegalAccessError: tried to access class me.neznamy.tab.shared.features.UpdateChecker$1 from class me.neznamy.tab.shared.features.UpdateChecker
27.04.2021 - 18:00:42 -        at me.neznamy.tab.shared.features.UpdateChecker.<init>(UpdateChecker.java:19)
27.04.2021 - 18:00:42 -        at me.neznamy.tab.shared.Platform.loadUniversalFeatures(Platform.java:263)
27.04.2021 - 18:00:42 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform.loadFeatures(BukkitPlatform.java:95)
27.04.2021 - 18:00:42 -        at me.neznamy.tab.shared.Shared.load(Shared.java:136)
27.04.2021 - 18:00:42 -        at me.neznamy.tab.shared.command.DisabledCommand.execute(DisabledCommand.java:16)
27.04.2021 - 18:00:42 -        at me.neznamy.tab.platforms.bukkit.Main.lambda$onEnable$0(Main.java:30)
27.04.2021 - 18:00:42 -        at pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
27.04.2021 - 18:00:42 -        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43)
27.04.2021 - 18:00:42 -        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
27.04.2021 - 18:00:42 -        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752)
27.04.2021 - 18:00:42 -        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:738)
27.04.2021 - 18:00:42 -        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:510)
27.04.2021 - 18:00:42 -        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
27.04.2021 - 18:00:42 -        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
27.04.2021 - 18:00:42 -        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
27.04.2021 - 18:00:42 -        at java.lang.Thread.run(Unknown Source)

**Comment by Tanguygab** [comment]
can you try pre-releases? https://github.com/NEZNAMY/TAB/releases

**Comment by NEZNAMY** [comment]
Try without this software whatever it is:
`27.04.2021 - 18:00:42 - at pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)`

**Comment by wudixiaoqiang** [comment]
> can you try pre-releases? https://github.com/NEZNAMY/TAB/releases

I‘ll try, thanks.

**Comment by NEZNAMY** [comment]
Any news @wudixiaoqiang ?
