### ISSUE TITLE
Nickname bug on player leave

### ISSUE THREAD

**Issue by zeterm0d** [NEZNAMY/TAB#306]
I have minecraft server with bedwars and there is on each world its own tab. When player leave from one world in the other his nick is shown with white color, while its not on the server.
![2021-04-28_13 23 47](https://user-images.githubusercontent.com/59437511/116388915-079e4000-a825-11eb-9c99-8cd218b1461b.png)

**Comment by NEZNAMY** [comment]
Player is not on the server when switching worlds? What?

**Comment by zeterm0d** [comment]
Look:
1. Player is on the server in the other world (BedWars launched game).
2. Player leaves from that world not going to lobby where i am. (BedWars Lobby)
3. In Lobby is shown like he is there, like in screen.

**Comment by zeterm0d** [comment]
But healready have left from server when in lobby his nick is shown...

**Comment by NEZNAMY** [comment]
Try uninstalling TAB if the bug persists.

**Comment by zeterm0d** [comment]
This error is with the TAB plugin because when i had TitleManager i didnt have any errors. Your advise is to reinstall the plugin?

**Comment by NEZNAMY** [comment]
Can you try removing it anyway? You did not even follow the template, so I can't attempt to reproduce it either.

**Comment by zeterm0d** [comment]
Ok i will check if error appears without it.

**Comment by zeterm0d** [comment]
I checked all problem. If i dont have TAB enabled when player leaves from one world, player in other world see him left. Of course, by default tab is common of all worlds, but anyway it cant appear without tab. If i have plugin TAB enabled and player leave from one world when i am in other, i can see his name white colored in tab but he isnt on the server :/ I can drop my config if its neccessary.

**Comment by zeterm0d** [comment]
[config.txt](https://github.com/NEZNAMY/TAB/files/6391315/config.txt)
I am trying to do per world tablist.

**Comment by zeterm0d** [comment]
I am waiting your answer. Can you give me some information what you will do? My players dont like this bug, thats why i am asking answer.

**Comment by NEZNAMY** [comment]
Try disabling per-world-playerlist.

**Comment by zeterm0d** [comment]
> Try disabling per-world-playerlist.

Fucken genious... I said that in bedwars i NEED per-world-playerlist.

**Comment by NEZNAMY** [comment]
You did not follow the template so I have to steps to try to reproduce it.

**Comment by zeterm0d** [comment]
> You did not follow the template so I have to steps to try to reproduce it.

Where or how i can find template?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/new/choose

**Comment by zeterm0d** [comment]
> https://github.com/NEZNAMY/TAB/issues/new/choose

https://github.com/NEZNAMY/TAB/issues/307 
There is.
