### ISSUE TITLE
Nickname bug on player leave

### ISSUE THREAD

**Issue by zeterm0d** [NEZNAMY/TAB#307]
**Server version**
Paper 1.12.2

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
If player from one world leaves, player in other sees him in tab. But how? Firstly he left. Secondly he is in other world.

**How to reproduce**
One player is situated in one world (lobby). Other in other (bedwars launched game). "per-world-playerlist" is enabled, so they can't see each other in tab. If player who is in bedwars launched game leaves, player in lobby sees his nickname colored with white. The problem is that player is not on a server but after quit he anyway is shown.

**Expected behavior**
Player leaves from server without any problems and on rejoin again his username will be showed in tab. Other players don't see that he has left. Only they are able to see online.

**Actual behavior**
Player leaves from server without any problems and on rejoin again his username will be showed in tab. But brfore he joins again or player in lobby rejoins nickname of player in previous game is shown in tab.

**Additional info** (errors, screenshots, ...)
![116388915-079e4000-a825-11eb-9c99-8cd218b1461b](https://user-images.githubusercontent.com/59437511/116433783-8067c100-a852-11eb-8af2-81432bebfa9d.png)

**Comment by NEZNAMY** [comment]
Just in case, can you try to add `remove-ghost-players: true` into your config?

**Comment by zeterm0d** [comment]
> Just in case, can you try to add `remove-ghost-players: true` into your config?

It fixed it 0_0

**Comment by NEZNAMY** [comment]
Then it's https://github.com/NEZNAMY/TAB/wiki/Compatibility#compatibility-issues-with-other-plugins

**Comment by zeterm0d** [comment]
Thanks very much!

**Comment by NEZNAMY** [comment]
You can close the issues if that worked for you.
