### ISSUE TITLE
Unlimited name tag

### ISSUE THREAD

**Issue by jarek123442** [NEZNAMY/TAB#308]
**Server version**
PaperSpigot 1.8.8

**Plugin version** ("latest" is not a version)
2.8.11-pre15

**Describe the bug**
Unlimited name tag sometimes not display on teleport 

https://imgur.com/ttcJqJS

**Comment by NEZNAMY** [comment]
Any steps to reproduce it? Who is supposed to teleport? The player not having nametag or the one not seeing it?

**Comment by NEZNAMY** [comment]
Try pre16 https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre16

**Comment by NEZNAMY** [comment]
@jarek123442

**Comment by jarek123442** [comment]
> Any steps to reproduce it? Who is supposed to teleport? The player not having nametag or the one not seeing it?

It happens when I teleport 2 players at the same time. I will checking the newest version but i have new error, i use tab api to register placeholder.

30.05.2021 - 13:57:25 - [TAB v2.8.11-pre17] An error occurred when refreshing placeholders
30.05.2021 - 13:57:25 - java.lang.NullPointerException: null
30.05.2021 - 13:57:25 -        at java.util.AbstractCollection.addAll(Unknown Source)
30.05.2021 - 13:57:25 -        at me.neznamy.tab.shared.features.PlaceholderManager.updatePlayerPlaceholder(PlaceholderManager.java:121)
30.05.2021 - 13:57:25 -        at me.neznamy.tab.shared.features.PlaceholderManager.access$200(PlaceholderManager.java:35)
30.05.2021 - 13:57:25 -        at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:83)
30.05.2021 - 13:57:25 -        at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:166)
30.05.2021 - 13:57:25 -        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
30.05.2021 - 13:57:25 -        at java.util.concurrent.FutureTask.run(Unknown Source)
30.05.2021 - 13:57:25 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
30.05.2021 - 13:57:25 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
30.05.2021 - 13:57:25 -        at java.lang.Thread.run(Unknown Source)

**Comment by NEZNAMY** [comment]
Is the issue fixed in new build tho? For the error I will just fix it.

**Comment by jarek123442** [comment]
Yes, is fixed

**Comment by NEZNAMY** [comment]
Error should be fixed. Can you join discord to get a jar? I don't want to upload a release just for this.
