### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by XiNaru** [NEZNAMY/TAB#309]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
with me it doesn't work at all.
my group is König
I have registered:

Groups:
  König:
    tabprefix: "&f[&4König &f] &r"
    tag prefix: "&f[&4König &f] &r"

but it doesn't work. ingame, of course, before / tab reload.

even using placeholder api vault prefix or luckperms prefix does not work.
**How to reproduce**
no idea? just install?

**Expected behavior**
expected? that in the chat and in the tablist have a prefix that is set, but that does not work.

**Actual behavior**
this is a pointless point. the current behavior is already mentioned above with the bugs.

**Additional info** (errors, screenshots, ...)

**Comment by DrWurzeli** [comment]
join the discord and open a ticket. we even have german support should you happen to be german.
if you dont want to join, send debug for someone that is supposed to be in group König with /tab debug <playername> (/btab on proxy). also: TAB is not a chat plugin.

**Comment by NEZNAMY** [comment]
If the plugin didn't work at all don't you think we would get more than just a single report after 4 months?
