### ISSUE TITLE
Compilation error "libs:Velocity:2.0.0 not found"

### ISSUE THREAD

**Issue by PerchunPak** [NEZNAMY/TAB#310]
**Plugin version**
2.8.11-pre15

**Describe the bug**
My IDE (intellij idea) can't see dependency in https://github.com/NEZNAMY/TAB/blob/master/velocity-2.0.0/pom.xml#L40
I also tryed compilate commit [when add velocity2.0.0 folder](https://github.com/NEZNAMY/TAB/commit/bbf9aaed6491f521c5bfa637effa0b3f5d8a9306#diff-e2faab822f57c40bb146a199ca4dc38a67123a1418eaa2050e6ce044595ea514), and it is give same error
[Commit before](https://github.com/NEZNAMY/TAB/commit/13d36457af0d70d9aec2e88764f9a89cc8931097) didn't give this, or any other errors

**Comment by NEZNAMY** [comment]
Yes, you must add it manually into your system path.

**Comment by NEZNAMY** [comment]
https://ci.velocitypowered.com/job/velocity-2.0.0/

**Comment by NEZNAMY** [comment]
Solved by dropping v2 support entirely, you can now compile it and get that scoreboard for free :TriHard:
