### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by SpeeeDCraft** [NEZNAMY/TAB#312]
**Server version** 1.16.5

**Plugin version** 2.8.10

**Describe the bug**
Spam in console

**How to reproduce**
Install Mohist server and tab plugin, start server.

**Additional info** (errors, screenshots, ...)
https://github.com/Mohist-Community/Mohist/issues/1319

**Comment by MrGraycat** [comment]
idk how you thing "Caused by MOTD plugin" is TAB? This isn't caused by TAB go to your motd plugin dev

**Comment by SpeeeDCraft** [comment]
Lil, sorry😂
