### ISSUE TITLE
[SUGGESTION] Premium vanish support

### ISSUE THREAD

**Issue by Greazi-Times** [NEZNAMY/TAB#313]
So when a player is in super vanish you get a scoreboard on the right.
When the player goes out of premium vanish that board will disapear but there will not be displayed any scoreboard. 

So is it possible to get it so when someone leaves premium vanish it will check its perms and set a scoreboard?

**Comment by NEZNAMY** [comment]
Yes, those who purchased the plugin have access to version with this added.

**Comment by Greazi-Times** [comment]
> Yes, those who purchased the plugin have access to version with this added.

Maybe I am stupid but I have the bought one from mc-market and it doesn't work / doesn't appear to happen

**Comment by NEZNAMY** [comment]
Premium pre-release versions are available on discord for verified buyers.

**Comment by Greazi-Times** [comment]
But shouldn't it already work with the one from mc-market?

**Comment by NEZNAMY** [comment]
Detection was added in a version which is not released yet.

**Comment by Greazi-Times** [comment]
o oke no problem will wait for the update than

**Comment by Greazi-Times** [comment]
I have bought it.
Only it is not a update that is necessary because we are not opening yet. Therefor I would rather wait for the release on mc-market.

**Comment by NEZNAMY** [comment]
Next version is planned to release with MC 1.17.

**Comment by Greazi-Times** [comment]
Well I am making a themepark server and all technical stuff needs to be done (That will take around ±4 months) 
Than we need to test and setup the events so ±3 more months. so we can safely say almost over a year of work that needs to be done.

**Comment by Greazi-Times** [comment]
And I think 1.17 will be released by then (I hope) because we are going to open with 1.17 because of the higher build highd for our drop tower and our attractions than can go deeper
