### ISSUE TITLE
classic-vanilla-belowname.text bug

### ISSUE THREAD

**Issue by deHasher** [NEZNAMY/TAB#314]
**Server version:** 1.16.5 Tuinity

**Plugin version:** 2.8.11-pre15

**Describe the bug:** "classic-vanilla-belowname.text" displays incorrect placeholders over the player's head

**How to reproduce:** see screenshots

**Expected behavior:** Placeholders must be displayed correctly as "classic-vanilla-belowname.number"

![image](https://user-images.githubusercontent.com/47824475/118182401-659c6b80-b452-11eb-8c2a-fb51503696dd.png)

_I apologize for my terrible English, I used a translator. I hope for your response_

**Comment by NEZNAMY** [comment]
That's not a bug, but minecraft limitation https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname#limitations
