### ISSUE TITLE
this is not a bug report :)

### ISSUE THREAD

**Issue by PortableGames** [NEZNAMY/TAB#315]
Hi do you want to think about adding mod loader support like fabric or forge. and be a god if you make it a server-side only mod😎

Ps: mohl jsem to napsat cesky!

**Comment by Tanguygab** [comment]
you can't use it as a Forge or Fabric mod, but you can use iy with server softwares like Magma or Mohist which allow Bukkit+Forge

**Comment by PortableGames** [comment]
I'm talking about pure fabric mod server side... not about using bukkit plugin over software that runs on 1.16 experimental .. my point is that it can be used on the latest snapshot versions of mc .. 1.17 21w19a+

**Comment by Tanguygab** [comment]
then no, I don't think it's planned, idk if NEZ wants to

**Comment by NEZNAMY** [comment]
Never worked with fabric, no idea how to make plugins for it.

**Comment by PortableGames** [comment]
so this is inspiration xD https://github.com/jukefr/fabric-tab
and I need to run this on the server side as a mod for 1.17 21w19a API https://github.com/FabricMC/fabric

I'm willing to invest in the development ;)
