### ISSUE TITLE
Unlimited Tag PlayerJoinEvent Error

### ISSUE THREAD

**Issue by Kovalski4** [NEZNAMY/TAB#316]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
In my server, players teleport on join and this cause throwing IllegalArgumentException from this plugin

**How to reproduce**
Lowest priority isn't enough. Can be delayed. 

**Expected behavior**
Live in peace with other join events contains teleport function

**Actual behavior**
Sometimes it throws an error.

**Additional info** (errors, screenshots, ...)
[errors.txt](https://github.com/NEZNAMY/TAB/files/6527361/errors.txt)

**Comment by NEZNAMY** [comment]
Fixed in https://github.com/NEZNAMY/TAB/releases
