### ISSUE TITLE
Per-world-tab bugs when you leave the server

### ISSUE THREAD

**Issue by AyhamAl-Ali** [NEZNAMY/TAB#317]
**Server version**
Paper 1.16.5-ae892dc

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
If you enable `per-world-tab` and you leave the server then rejoin you will have an empty tab and all players are hidden but you can see like arrows being shot and everything

**How to reproduce**
1- Be in a server with multiple players
2- Set `enabled` of `per-world-tablist` to `true`
3- Reload the plugin
4- Be in a world alone, other players in any other world
5- Quit the server
6- You need to have a plugin that will teleport you to a specific world `on join` where all players are in such as `Hub` world
7- Rejoin and you will be alone in tab and all players hidden even though they are beside you unless you reload the plugin *(or change the world again not sure I forgot to test)*

**Expected behavior**
Players should be visible again when you rejoin and spawn in their world

**Actual behavior**
All players will be hidden and only players that where in your world when you left will be visible

**Additional info** (errors, screenshots, ...)
None.

**Comment by NEZNAMY** [comment]
Try https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre17

**Comment by AyhamAl-Ali** [comment]
Works as expected 👍 Thank you
