### ISSUE TITLE
ARMORSTAND DISTANCE FROM SKIN

### ISSUE THREAD

**Issue by fra130701** [NEZNAMY/TAB#318]
Can be a way to increase this distance?
![image](https://user-images.githubusercontent.com/80008144/119692140-733af380-be4b-11eb-96dc-fbf44f7109d7.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/releases https://github.com/NEZNAMY/TAB/blob/master/bukkit/src/main/resources/bukkitconfig.yml#L116

**Comment by fra130701** [comment]
no..
I mean the distance from skin and hd

**Comment by NEZNAMY** [comment]
No, it's (supposed to be) exactly the same as vanilla nametags.

**Comment by NEZNAMY** [comment]
Actually it's possible already https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-line-count-in-nametag-(premium-only)#static-lines
