### ISSUE TITLE
Incorrect/rounded parsing of doubles

### ISSUE THREAD

**Issue by ArcticRaven** [NEZNAMY/TAB#321]
**Server version**
PurPur-1144 (1.16.5)

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
Doubles are not parsed in the vanilla-belowname

**How to reproduce**
Attempt to use a placeholder that parses a double in the vanilla-belowname options

**Expected behavior**
Parsing of doubles...

**Actual behavior**
Doubles are not parsed

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/43667891/120911827-3e534b80-c658-11eb-9d18-625967f7bff4.png)

**Comment by MrGraycat** [comment]
Hello

This is correct behavior as the vanilla belowname only supports integers (so it converts these doubles intro an integer) as explained here: [Vanilla belowname](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname#configuration)
To bypass this issue you can use the unlimitednametagmode's belowname option which you can find more info about here: [Unlimited nametag belowname](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#adding-more-lines)

**Comment by ArcticRaven** [comment]
Ah cheers, looks like I just don't know how to read. Thanks!
