### ISSUE TITLE
Tag and nick bug on cmi

### ISSUE THREAD

**Issue by mantrakp** [NEZNAMY/TAB#324]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
TAB-2.8.11-pre17.jar

**Describe the bug**
NickName not showing up on nametag

**How to reproduce**
Use cmi placeholder %cmi_user_nickname%

**Expected behavior**
Show nick name instead of real name on tag 

**Actual behavior**
It is showing real name instead of using the nick placeholder on both tab and tag

![image](https://user-images.githubusercontent.com/73872531/121437985-d6c33600-c9a0-11eb-9416-d3a31b6d7c23.png)

**Comment by mantrakp** [comment]
the players name is 
CoOwnerSteel
nick: steel

**Comment by MrGraycat** [comment]
Nametags can't be changed [https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags](https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags)
A way to bypass is also listed on that page

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-nick-plugins

**Comment by mantrakp** [comment]
tnx man :P
