### ISSUE TITLE
update minecraft 1.17

### ISSUE THREAD

**Issue by TATA82** [NEZNAMY/TAB#326]
**Server version** 1.17

**Plugin version** ("latest" is not a version) last

**Describe the bug** disable plugin 

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)

**Comment by MrGraycat** [comment]
We're sorry but the stuff you call 'magic' takes a lot of time to update to 1.17 due to Spigot changing a lot of things internally.

**Comment by DrWurzeli** [comment]
you can watch the process live if you want to on discord. it will be ready when its ready.
also "last" is not a version.
