### ISSUE TITLE
Not working in luckperms contexts

### ISSUE THREAD

**Issue by QC-Development** [NEZNAMY/TAB#327]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
latest

**Describe the bug**
I want to make per server tab sorting player, but the plugin cannot detect permissions in luckperms context. No matter I use permission node or primary group, if it is in contexts, it can't work. Player can inherit the permission nodes, but the plugin cannot detect it.

**Expected behavior**
The primary permission group for that player actually will be "player_survival_builder" if he/she is in the server "survival"

**Actual behavior**
The primary permission group for that player is "player"

**Additional info** (errors, screenshots, ...)
![not work 2](https://user-images.githubusercontent.com/51996408/121768647-dccc3900-cb91-11eb-88c4-c20879e0b1a1.PNG)
![not work](https://user-images.githubusercontent.com/51996408/121768661-ebb2eb80-cb91-11eb-8129-7e82ef674a7a.PNG)

Hopefully this can be fixed. Thanks.

**Comment by NEZNAMY** [comment]
Show output of /lpb user LookForwardTo info. It will say primary group is player.

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-setup-weights-priorities

**Comment by QC-Development** [comment]
> Show output of /lpb user LookForwardTo info. It will say primary group is player.

Can the plugin using the primary group of the luckperms(bukkit) instead of luckperms(bungee)? Because if I use `/lp user LookForwardTo info` it will be "player_survival_builder"

**Comment by NEZNAMY** [comment]
Will be added in the next version.
