### ISSUE TITLE
having this strange error

### ISSUE THREAD

**Issue by cicatrice74** [NEZNAMY/TAB#328]
1.17 spigot

2.18pre18

I'm having this error log

13.06.2021 - 15:45:59 - [TAB v2.8.11-pre19] An error occurred when reading packets
13.06.2021 - 15:45:59 - java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "players" is null
13.06.2021 - 15:45:59 -        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector.modifyPlayers(BukkitPipelineInjector.java:70)
13.06.2021 - 15:45:59 -        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector.access$600(BukkitPipelineInjector.java:17)
13.06.2021 - 15:45:59 -        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:121)
13.06.2021 - 15:45:59 -        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
13.06.2021 - 15:45:59 -        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
13.06.2021 - 15:45:59 -        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
13.06.2021 - 15:45:59 -        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
13.06.2021 - 15:45:59 -        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
13.06.2021 - 15:45:59 -        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
13.06.2021 - 15:45:59 -        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
13.06.2021 - 15:45:59 -        at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
13.06.2021 - 15:45:59 -        at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
13.06.2021 - 15:45:59 -        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
13.06.2021 - 15:45:59 -        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
13.06.2021 - 15:45:59 -        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
13.06.2021 - 15:45:59 -        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
13.06.2021 - 15:45:59 -        at java.base/java.lang.Thread.run(Thread.java:831)

simply have spigot 1.17
and default tab 2.18pre18

**Comment by NEZNAMY** [comment]
Thanks for the report, will be fixed in next version.

**Comment by cicatrice74** [comment]
Is there a temporary fix to disable logging ? It's enormous !

**Comment by NEZNAMY** [comment]
It's only 1MB. Error file is limited to that size.
