### ISSUE TITLE
Bug with unlimited prefix and mod for displaying nicknames and prefixes for creatures

### ISSUE THREAD

**Issue by Duioka** [NEZNAMY/TAB#33]
**Server version**
1.12

**Plugin version** ("latest" is not a version)
2.5.1

**Describe the bug**
I turned on the experimental mode for unlimited prefix characters, everything works fine, the prefix is displayed as it should, but in creature nicknames everything is displayed the same way as without this mode

**How to teproduce**
Just install the Neat mod, put a long prefix (for example: Administrator), turn on the unlimited number of characters in the prefix mode and you will see that in the Neat mode, it is displayed as well as without the mode

**Expected behavior**
I do not know what to write here :p

**Actual behavior**
And here too :(

**Additional info** (errors, screenshots, ...)
 screenshot: https://prnt.sc/p6wfxr

**Comment by NEZNAMY** [comment]
Not a bug, read FAQ. http://prntscr.com/p6wh5y

**Comment by Duioka** [comment]
> Not a bug, read FAQ. http://prntscr.com/p6wh5y

Ok ... By the way, as I understand it, there are no other options for implementing long prefixes? And then I tormented for an hour :(

**Comment by NEZNAMY** [comment]
There's no other way.

**Comment by Duioka** [comment]
> There's no other way.

Okay I understand that minecraft hardly supports so long nicks

Thanks for the great plugin! :D

**Comment by NEZNAMY** [comment]
It does support since 1.13

**Comment by Duioka** [comment]
> It does support since 1.13



> It does support since 1.13

I have a multi-version, it supports up to 1.14. Or do I need to keep the kernel itself at 1.13?

**Comment by NEZNAMY** [comment]
1.13+ players will see long prefixes, 1.12- short.

**Comment by Duioka** [comment]
> 1.13+ players will see long prefixes, 1.12- short.

Does this apply to mods as well? Or do you mean without an experimental mod?

**Comment by NEZNAMY** [comment]
The above rule applies for hacked clients which allow you to see your own nametag. When looking at someone else, you will see long prefixes all the time.

**Comment by Duioka** [comment]
> The above rule applies for hacked clients which allow you to see your own nametag / with the mode disabled. When looking at someone else, you will see long prefixes all the time.

I don’t use a hacked client. I logged in with two accounts :D

**Comment by NEZNAMY** [comment]
Then it works.

**Comment by Duioka** [comment]
> Then it works.

Thanks for the useful information :)
