### ISSUE TITLE
AFK rank remoed

### ISSUE THREAD

**Issue by TheKingXP** [NEZNAMY/TAB#331]
**Server version** 
1.16.4

**Plugin version** ("latest" is not a version)
2.8.10

**Describe the bug**
after a certain amount of time being AFK names are reset to default white and ranks and prefixes are being removed from tab

**How to reproduce**
go afk for a few minutes
sometime around 5 minutes

**Expected behavior**
adding prefix &8[&cAFK&8]

**Actual behavior**
gets rid of prefix and server ranks and changes names to white with no ranks/prefixes 

**Additional info** (errors, screenshots, ...)
![prefix working](https://user-images.githubusercontent.com/86200867/122682491-41554c80-d1bf-11eb-896f-88c491a286e5.png)

![broken afk ](https://user-images.githubusercontent.com/86200867/122682642-59799b80-d1c0-11eb-8fe6-22ac88114935.png)

**Comment by DrWurzeli** [comment]
not a TAB issue, since NTE is being used to format tablist names and nametags.
since TAB is disabled for those, essentials afk is overwriting tablist names.
with TAB, there would be two easy ways of achieving the goals without NTE even. send to NTE support, where this issue belongs.
cheers
