### ISSUE TITLE
SuperVanish plugin support

### ISSUE THREAD

**Issue by cryokesh34** [NEZNAMY/TAB#332]
Hello, could you please add the support for SuperVanish plugin? It does not hide me from the tab when i vanish myself.

**Comment by Tanguygab** [comment]
any vanish plugin is supported, what's your TAB version? also, note that you can always see yourself

**Comment by Tanguygab** [comment]
oh and if you're just asking about the player count, find %online% in your config and replace it by %canseeonline%

**Comment by cryokesh34** [comment]
Oh, okay... I just thouht there was no support for vanish because i could see myself... Thanks.

**Comment by Tanguygab** [comment]
try to check from another player's perspective =)

**Comment by cryokesh34** [comment]
It just didn´t say anywhere about SuperVanish support, so I thought it just wasn´t implemented (or I couldn´t find it on the main page).

**Comment by Tanguygab** [comment]
yeah true, welp, now you know ¯\_(ツ)_/¯
