### ISSUE TITLE
Cant assign Players into group

### ISSUE THREAD

**Issue by davigamer987** [NEZNAMY/TAB#333]
**Server version** 1.16.5

**Plugin version** ("latest" is not a version)  2.8.10

**Describe the bug** I am trying to Add a player into a group using permission And it wont work, I have assign-groups-by-permissions: true and the player has the permission tab.group.coowner and the group is also on the config.yml

**How to reproduce** 

**Expected behavior** Player is added to group

**Actual behavior**

**Additional info** (errors, screenshots, ...) 
[config.txt](https://github.com/NEZNAMY/TAB/files/6689263/config.txt)
![image](https://user-images.githubusercontent.com/68574209/122822233-cd44a280-d2ab-11eb-90a5-d6bc6ec910c9.png)

**Comment by NEZNAMY** [comment]
Show output of /tab debug <player>

**Comment by davigamer987** [comment]
![image](https://user-images.githubusercontent.com/68574209/122825605-27dffd80-d2b0-11eb-97a9-5f7a5a9191f1.png)

**Comment by NEZNAMY** [comment]
tab.group.owner is player's highest permission from the config list. Don't forget OP = all permissions.

**Comment by davigamer987** [comment]
Wait im gonna try denying it

**Comment by davigamer987** [comment]
yay it works now
