### ISSUE TITLE
Can't buy plugin

### ISSUE THREAD

**Issue by VINRED5** [NEZNAMY/TAB#336]
I'm banned from the discord backend and can't write to it

Text in the screenshot: "It looks like there's a problem on our side. Please try again later."
https://wmpics.pics/di-OXHV.png

And before buying, it writes "inactive. resource"
https://wmpics.pics/di-GYJC.png

**Comment by NEZNAMY** [comment]
They took the plugin from me on spigot so I can't update it anymore to screw up buyers who want updates.

**Comment by VINRED5** [comment]
Can I buy a plugin in another shop?

**Comment by Tanguygab** [comment]
https://www.mc-market.org/resources/14009/
https://polymart.org/resource/tab-1-5-x-1-16-4-premium.484

**Comment by VINRED5** [comment]
Thanks
