### ISSUE TITLE
1.17, TAB 2.9.1, fix-pet-names breaks pet interaction

### ISSUE THREAD

**Issue by radiant-ai** [NEZNAMY/TAB#337]
**Server version**
1.17

**Plugin version** ("latest" is not a version)
2.9.1

**Describe the bug**
When `fix-pet-names: true` any NEW tamed cat DOES NOT sit or stand down on right click. With `fix-pet-names: false` works as intended.

**How to reproduce**
Enable `fix-pet-names` and tame the cat.

**Expected behavior**
Cat can be made sitting or standing by interaction.

**Actual behavior**
Cat does not react to right clicks.

**Additional info** (errors, screenshots, ...)
Tested on a server with no plugin with default TAB config and by switching `fix-pet-names` option.

**Comment by NEZNAMY** [comment]
Should be fixed in https://github.com/NEZNAMY/TAB/releases/
