### ISSUE TITLE
[Suggestion] Add multiple commands to turn off the scoreboard

### ISSUE THREAD

**Issue by Thin-Troll** [NEZNAMY/TAB#338]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
2.9.1

**Describe the SUGGEST**
There is a need for several commands to turn off the scoreboard.
I wish to leave / sb and add my own custom one.
commands.yml does not see / sb as a registered command.
therefore I cannot make a custom command myself.

**Comment by NEZNAMY** [comment]
Create an alias for /tab scoreboard using commands.yml

**Comment by Thin-Troll** [comment]
It is absent in /tab help, I did not find information anywhere.
perhaps he was inconsiderate. Thank you
