### ISSUE TITLE
[Unlimited nametags] Desynced when riding boats

### ISSUE THREAD

**Issue by NEZNAMY** [NEZNAMY/TAB#34]
Unlimited nametag mode's armor stands are out of sync when player is riding boats due to movement packets (or just the animation) being delayed while position on server side is not. I don't see a way to fix this anytime soon.

**Comment by Tanguygab** [comment]
can't you make the armorstand ride the player ? (don't judge me if that sounds stupid x))

**Comment by NEZNAMY** [comment]
That would result in different height of the name, which people would notice and a limit of 1 line only, which would make the entire feature pointless.

**Comment by fjeddy** [comment]
Are you able to figure out when it's likely out of sync? Could it be an idea to show nothing when that occurs, instead of having the ridiculous looking movement of the tags?

**Comment by NEZNAMY** [comment]
You mean disabling the feature for players who are riding a boat?

**Comment by fjeddy** [comment]
Yes?

**Comment by NEZNAMY** [comment]
And then having complaints it disables when riding boats.

**Comment by fjeddy** [comment]
Then you reference this issue.

It's pretty much the same thing, have people complain it is out of sync when in boats, or have people ask why it's different when in boats. Neither of them are a solution, the question is, which of the two is the best looking evil?

The server owners / staff might know and realize why it is like it is, but the players? Which of the two options is the better user experience until an actual fix can be made, if one can be made.

**Comment by NEZNAMY** [comment]
Fixed by disabling the feature for players on boats.
