### ISSUE TITLE
%server_tps% always shows 0

### ISSUE THREAD

**Issue by ogohogo** [NEZNAMY/TAB#340]
**Server version**
Purpur 1.17 (Build 1204)

**Plugin version** ("latest" is not a version)
2.9.1

**Describe the bug**
%server_tps% on Tab always shows value of 0.

**How to reproduce**
Set %server_tps% on Tab

**Expected behavior**
Show actual server's tps (available under /tps command)

**Actual behavior**
Shows 0 no matter what.

**Additional info** (errors, screenshots, ...)
https://i.imgur.com/8M9YFA5.png

**Comment by NEZNAMY** [comment]
%server_tps% comes from PlaceholderAPI, report it to them.

**Comment by Tanguygab** [comment]
they got a dev build for 1.17 on their Discord server
