### ISSUE TITLE
Bug Tab

### ISSUE THREAD

**Issue by StormzGanz2008** [NEZNAMY/TAB#341]
So I'm using bungeecord for my server, when I move from hub to buildbattle
![2021-07-02_09 38 23](https://user-images.githubusercontent.com/86810901/124212502-426c6f00-db19-11eb-81e0-fd0bd1d7d5c8.png)

**Comment by MrGraycat** [comment]
https://github.com/NEZNAMY/TAB/wiki/Behind-the-scenes:--Why-you-can-still-see-header%7Cfooter-on-a-bungeecord-subserver-where-TAB-isn't-installed
