### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by benfiratkaya** [NEZNAMY/TAB#344]
**Server version**
Paper 1.8.8

**Plugin version** ("latest" is not a version)
v2.9.2-pre1

**Describe the bug**
06.07.2021 - 10:03:13 - [TAB v2.9.2-pre1 Premium] An error occurred when reading packets
06.07.2021 - 10:03:13 - java.lang.NullPointerException: null
06.07.2021 - 10:03:13 -        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.modifyPlayers(BukkitPipelineInjector.java:134)
06.07.2021 - 10:03:13 -        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:93)
06.07.2021 - 10:03:13 -        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
06.07.2021 - 10:03:13 -        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
06.07.2021 - 10:03:13 -        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
06.07.2021 - 10:03:13 -        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
06.07.2021 - 10:03:13 -        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
06.07.2021 - 10:03:13 -        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
06.07.2021 - 10:03:13 -        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
06.07.2021 - 10:03:13 -        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
06.07.2021 - 10:03:13 -        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
06.07.2021 - 10:03:13 -        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
06.07.2021 - 10:03:13 -        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
06.07.2021 - 10:03:13 -        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
06.07.2021 - 10:03:13 -        at java.lang.Thread.run(Thread.java:748)

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Line 134 of pre1 is https://github.com/NEZNAMY/TAB/blob/341b552d0be78bb8b5299eca692a33b01a5d44cf/bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/BukkitPipelineInjector.java#L134
