### ISSUE TITLE
Emoticons show as a ?

### ISSUE THREAD

**Issue by davigamer987** [NEZNAMY/TAB#346]
**Server version** 1.17.1 (purpur)

**Plugin version** 2.9.0

**Describe the bug** Emoticons Show as a ? (I have also tried various combinations of \u26A1 which is the unicode for the emoticon) Emoticons show fine in chat

**How to reproduce**  Use ⚡ in a tab config (Or try with the unicode)

**Expected behavior** Emoticon Shows as normal (Like it is on the Chat)

**Actual behavior** Shows a ?

**Additional info** (errors, screenshots, ...) Tell me if u need any more info

**Comment by Tanguygab** [comment]
save TAB's config with the UTF-8 encoding

**Comment by davigamer987** [comment]
thanks
