### ISSUE TITLE
[Feature Request] Per-player tab menu slot widths

### ISSUE THREAD

**Issue by TheosisOfficial** [NEZNAMY/TAB#347]
**Server version**
1.16.5

**Plugin version**
2.9.1

**Feature**
Make it so that when the `align-tabsuffix-on-the-right` is enabled, players hidden from the tab menu from the perspective of a player do not affect the width of tab menu slots from the perspective of that player.

The reason I believe this feature is a good idea is because it would prevent "vanished" players from affecting the width of tab menu slots. This means that a clever player wouldn't be able to use that fact (example shown in "Additional info") to deduce that a vanished player is currently online.

**Additional info**
When vanished player _is not_ online (normal):
![image](https://user-images.githubusercontent.com/26799016/125110716-da032c00-e0dc-11eb-9efe-4e380d8a2607.png)
When vanished player _is_ online (clearly not normal):
![image](https://user-images.githubusercontent.com/26799016/125110767-eab3a200-e0dc-11eb-83cb-7ea8548bb538.png)
Vanished player's perspective:
![image](https://user-images.githubusercontent.com/26799016/125110790-f737fa80-e0dc-11eb-9ee3-bdc24fa97e33.png)

**Comment by NEZNAMY** [comment]
A minor improvement to this will be made in 3.0.1 as a result of a small optimization which will, however, only solve this specific case when visible players don't have suffix.

**Comment by TheosisOfficial** [comment]
> A minor improvement to this will be made in 3.0.1 as a result of a small optimization which will, however, only solve this cases when visible players don't have suffix.

That's awesome! Can't wait to see it work with prefixes though! :P
