### ISSUE TITLE
[Feature Request] Velocity Support

### ISSUE THREAD

**Issue by Stixil** [NEZNAMY/TAB#348]
Hello, I am writing in just to make a short simple request to add Velocity support for Tab. Right now there is no global tablist plugin for Velocity (many for Bungeecord) and having this on the platform would be fantastic, thanks!

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/tree/master/velocity-1.1.0

**Comment by Stixil** [comment]
Ah, my mistake, excellent. I didn't see anything on that on the Spigot page, thanks for the info!
