### ISSUE TITLE
Remove a player from the tab list

### ISSUE THREAD

**Issue by pgmann** [NEZNAMY/TAB#35]
How would I make a player invisible in the tab list? If it's not currently possible I would like this added as a feature. Would like the option to hide players based on a permission node or if they are invisible in essentials/CMI.

**Comment by NEZNAMY** [comment]
Use vanish plugins, they hide in tablist too.

**Comment by pgmann** [comment]
Thanks! Is it also possible to hide a player from the tablist without being invisible (the permission node option)?

**Comment by NEZNAMY** [comment]
No. I don't see a reason for it.

**Comment by pgmann** [comment]
Our use case is a player acting as a boss monster. We want the custom name over the player's head  (which this plugin does very well, thank you!) but ideally they shouldn't appear in the tab list.

**Comment by NEZNAMY** [comment]
Feels like the boss plugin's job to hide player from tablist. This is really just plugin compatibility request which can be done by the other plugin.
