### ISSUE TITLE
Nametag and tablist placeholder problem

### ISSUE THREAD

**Issue by TheSloPro** [NEZNAMY/TAB#350]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
TAB.v2.9.2

**Describe the bug**
So basically it doesn't update placeholders in the prefix of a player in the tablist and in nametag (I am using LuckPerms and Vault to manage prefixes and suffixes)

**How to reproduce**
just put a placeholder into prefix of a player

**Expected behavior**
It should parse the placeholder automatically after X of time set in config.yml

**Actual behavior**
It doesn't update the nametag at all!

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/37777261/125208363-22177f80-e292-11eb-81c1-f2d98fc3bc31.png)

**Comment by NEZNAMY** [comment]
Did you install PlaceholderAPI?

**Comment by TheSloPro** [comment]
yes lol

**Comment by TheSloPro** [comment]
running PlaceholderAPI-2.10.10

**Comment by NEZNAMY** [comment]
What does /papi parse me %player_ping% say?

**Comment by TheSloPro** [comment]
![image](https://user-images.githubusercontent.com/37777261/125208519-4031af80-e293-11eb-93aa-a65d3e8ec9e0.png)

**Comment by NEZNAMY** [comment]
Did you get error file in tab's folder? Anything that could help reproduce it? "Just use placeholders" did not do it for me, it worked, as well as for everyone else using the plugin.

**Comment by TheSloPro** [comment]
hmm did not get any error in the tab folder...

do you know which plugins may interrupt TAB?

**Comment by NEZNAMY** [comment]
All of them should work, try on a fresh localhost and reproduce it there.

**Comment by TheSloPro** [comment]
so you suggesting that i should try make another server and then put only that plugin into plugin folder? (and papi)

**Comment by NEZNAMY** [comment]
Yes

**Comment by TheSloPro** [comment]
ok a sec

**Comment by TheSloPro** [comment]
so i tried with just papi and tab but it didn't go well so i put these plugins in:
vault
luckperms
alonsolevels

**Comment by TheSloPro** [comment]
so all 5 working

**Comment by TheSloPro** [comment]
but none of the placeholders
![image](https://user-images.githubusercontent.com/37777261/125208806-fd70d700-e294-11eb-8e9a-dc05ca0dd02d.png)

**Comment by TheSloPro** [comment]
they are marked as perm:
prefix.0.&7[%alonsolevels_level%✫] &e%player_ping% %alonsolevels_developer% &7
in luckperms

**Comment by TheSloPro** [comment]
i have set mysql database for lp but at least %player_ping% should work

**Comment by NEZNAMY** [comment]
That's it, TAB does not currently support unpredictable nested placeholders.

**Comment by TheSloPro** [comment]
that means i can have only 1 placeholder in the name?

**Comment by NEZNAMY** [comment]
It means you can't use placeholders inside placeholders, I'm assuming you used a placeholder that return LP prefix.

**Comment by TheSloPro** [comment]
ooh so %luckperms_prefix% in the config is considered as placeholder in this case?

**Comment by NEZNAMY** [comment]
Yes

**Comment by TheSloPro** [comment]
well thanks. I at least know where am I

**Comment by NEZNAMY** [comment]
Support is planned.

**Comment by TheSloPro** [comment]
for placeholders in placeholder?

**Comment by TheSloPro** [comment]
that would be so awesome

**Comment by TheSloPro** [comment]
nested placeholders

**Comment by TheSloPro** [comment]
u can close this 'issue' now if you want
