### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Georgy123456** [NEZNAMY/TAB#351]
**Server version**1.17.1

**Plugin version** ("latest" is not a version)2.8.10

**Describe the bug**the whole plugin doesn't work

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
It works. If it didn't, we would get more than just a single complaint half a year after release. You probably broke yaml syntax. Who knows, you provided absolutely no info.
