### ISSUE TITLE
Change the nametag of a player above his head?

### ISSUE THREAD

**Issue by Grizzlypfanne** [NEZNAMY/TAB#352]
Minecraft 1.17 (Paper 79), TAB.v2.9.2

Can i change the name of a player above his head? Is it cusotmtagname?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-nick-plugins

**Comment by Grizzlypfanne** [comment]
Nice. Thank u
