### ISSUE TITLE
TAB installed on one backend server, shows custom TAB on all other servers without TAB

### ISSUE THREAD

**Issue by TheMonBonGH** [NEZNAMY/TAB#355]
**Server version**
The server with TAB installed is running `Airplane version git-Airplane-9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

**Plugin version** ("latest" is not a version)
TAB.v2.9.2.jar

**Describe the bug**
On a backend server (BUNGEECORD), I use the TAB plugin to show a custom TAB with its own information (playing on this game). The other backend servers when switching from the server to another, it still shows.

**How to reproduce**
Install TAB on one backend server, and leave the other backends and bungee without the TAB plugin.

**Expected behavior**
I expected the TAB to clear with just the player names on the servers without TAB.

**Actual behavior**
The custom TAB still shows on the other backend servers, such as the lobby.

**Additional info** (errors, screenshots, ...)
MINIGAMES LOBBY: https://rory.reeee.ee/54UZSa3H0.png

SERVER WITH TAB: https://rory.reeee.ee/54U_1yfyV.png

Would I have to install TAB on the bungee proxy?

**Comment by NEZNAMY** [comment]
Sounds like https://github.com/NEZNAMY/TAB/wiki/Behind-the-scenes:--Why-you-can-still-see-header%7Cfooter-on-a-bungeecord-subserver-where-TAB-isn't-installed

**Comment by TheMonBonGH** [comment]
> Sounds like https://github.com/NEZNAMY/TAB/wiki/Behind-the-scenes:--Why-you-can-still-see-header%7Cfooter-on-a-bungeecord-subserver-where-TAB-isn't-installed

wow fast! thanks.
