### ISSUE TITLE
Seeing player 2x while lying with Gsit v6

### ISSUE THREAD

**Issue by Chris6ix** [NEZNAMY/TAB#356]
**Server version**
Paper-1.17.1-124

**Plugin version** ("latest" is not a version)
2.9.2

**Describe the bug**
When using `/lay` or `/bellyflop` with [Gsit](https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-13-x-1-17-x.62325/) v.6.x.x.x you can see the player 2x,1x laying (normal) and 1x transparent sitting inside the other one (not normal) like [this](https://imgur.com/a/CDYmeb7).

I have spoken to the Gsit Author, and he said that this is caused by plugins that manage Tablists/Scoreboards...so to test i removed TAB from my server and the bug was gone (You can only see yourself 1x lying)

I have also tried disabling the option to show the "20❤" you see in the screenshot, but that did not fix the issue...

**How to reproduce**
Install Gsit v6 and TAB 2.9.2 and do `/lay` or `/bellyflop`

**Expected behavior**
Seeing only 1 player model (lying)

**Actual behavior**
Seeing 2 player models (1 lying and 1 transparent sitting)

**Additional info** (errors, screenshots, ...)
No Errors, screenshots link is above

**Comment by NEZNAMY** [comment]
Try disabling nametags if that solves it.

**Comment by Chris6ix** [comment]
`invisible-nametags` was already set to `false` but setting it to `true` removed my nametag ([Owner] Chris6ix) but i could still see myself transparent sitting on the other model like this:
![2021-07-24_16 07 12](https://user-images.githubusercontent.com/65610536/126870984-c9bb4adc-2ca4-4c66-8c3a-cb8755f3defb.png)
![2021-07-24_16 07 09](https://user-images.githubusercontent.com/65610536/126870989-595808c4-4eeb-4546-85d6-4a28ccf15f65.png)

**Comment by NEZNAMY** [comment]
No, I mean `change-nametag-prefix-suffix: false`. Generally can you disable features until it works and tell which one was it?

**Comment by Chris6ix** [comment]
Okay, that worked to remove the transparent player model, it now looks like this:
Is it possible to remove this text for yourself? (Because normally you cannot see your own name and "20❤" like this...only of other players)
![2021-07-24_16 17 57](https://user-images.githubusercontent.com/65610536/126871316-948b26b8-fc15-48d6-9001-e6e998b95547.png)

**Comment by NEZNAMY** [comment]
You can't see your own nametag with vanilla client, only with modifications. What that option does is it just adds players into teams. I don't see how is that a bug or something I could "fix".

**Comment by Chris6ix** [comment]
Oh okay, the only client "modification" I use is OptiFine...
So if this is not a bug of your Plugin or not something that you can fix than you can close this issue as the main problem (transparent player model) has been "fixed"
I thank you for your help :)

**Comment by NEZNAMY** [comment]
You can play with vanilla /team command and see if that reproduces it.

**Comment by Chris6ix** [comment]
What exactly do you mean by that?

**Comment by NEZNAMY** [comment]
I am assuming teams were the issue, try to create a team and add a player to it, does that reproduce it?

**Comment by NEZNAMY** [comment]
Since Gsit author asked for tablist plugins immediately, it means he knows more about this issue. You should ask him for more info.
