### ISSUE TITLE
TAB Free version not on spigot anymore?

### ISSUE THREAD

**Issue by Chris6ix** [NEZNAMY/TAB#357]
I wanted to message you on spigot about the Gsit bug, but I couldn't find the plugin on spigot anymore...even with the direct link that I keep for every plugin I use...

Using the direct link shows this error: 

> You do not have permission to view this page or perform this action.

**Comment by Tanguygab** [comment]
you can download it from the releases tab on GitHub

**Comment by Chris6ix** [comment]
Yeah, I saw that, but like is it coming back to spigot (just temporarily) or is it gone?

**Comment by NEZNAMY** [comment]
Gone from spigot, you can get it at https://www.mc-market.org/resources/20631/ and https://github.com/NEZNAMY/TAB/releases

**Comment by Chris6ix** [comment]
Okay thanks
