### ISSUE TITLE
Add an option to edit the animals' sufix and nametag.

### ISSUE THREAD

**Issue by TheSensif** [NEZNAMY/TAB#362]
Add an option like this but animals

![image](https://user-images.githubusercontent.com/79162240/127517120-599e0f89-e1ad-4777-acfc-70f77a5267ff.png)

I suggest this so that if you put a tag plugin and have to add a papi do not disturb the defalut permission for animals.

![image](https://user-images.githubusercontent.com/79162240/127517581-aa796207-6667-49b3-9653-049e7127ad67.png)

Sorry if there is something misspelled as my English is bad.

**Comment by NEZNAMY** [comment]
Animals take nametag properties from their owner. Can't override that.

**Comment by TheSensif** [comment]
Ok thank you
