### ISSUE TITLE
unlimited-nametag-prefix-suffix-mode not found for a cats

### ISSUE THREAD

**Issue by TheSensif** [NEZNAMY/TAB#363]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
2.9.2

**Describe the bug**
unlimited-nametag-prefix-suffix-mode not found for a cats

**How to reproduce**
You tame a cat and you put a nametag on it and the name doesn't appear.

**Expected behavior**
name doesn't appear.

**Actual behavior**

**Additional info** (errors, screenshots, ...)
![2021-07-29 17-50-10](https://user-images.githubusercontent.com/79162240/127524710-08436a0b-636e-4fe9-bf89-8c08157bc2e0.gif)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix

**Comment by TheSensif** [comment]
This does not work on true and does not display the name

**Comment by Tanguygab** [comment]
did you relog ?

**Comment by TheSensif** [comment]
Yes

**Comment by TheSensif** [comment]
![2021-07-29 17-59-43](https://user-images.githubusercontent.com/79162240/127525953-766d9e4f-7b01-4be8-ad72-191ca7a33c54.gif)

**Comment by Tanguygab** [comment]
you have to relog, not just reload, quit and join back the server

**Comment by TheSensif** [comment]
Thanks a lot
