### ISSUE TITLE
Wrong user glow color

### ISSUE THREAD

**Issue by VanyaNexus** [NEZNAMY/TAB#367]
**Server version**
Paper 1.12.2 1618

**Plugin version** ("latest" is not a version)
2.9.1 Premium

**Describe the bug**
I have issue with plugin on glow players with unlimited tags. Glow plugin have placeholder with color code. I place his on end on prefix (&6&lDIVINE &r&f%rel_gm_color%)
Player's tag overhead has true color (from glow plugin), but his glow color is orange. I think reason in his scoreboard team, TAB substring prefix on 16 symbols and delete color code.
When player prefix is &6&lDIVIN &r&f%rel_gm_color%, then glow color is true (from glow plugin)

**Additional info** (errors, screenshots)

show player and output command /tab debug Vanyya1
![unknown](https://user-images.githubusercontent.com/60396560/128381717-ae03f1c4-99db-4ad8-9e4b-a573d3119256.png)
![unknown2](https://user-images.githubusercontent.com/60396560/128381761-f036a391-14a5-42cf-bfe0-365102f84311.png)

**Comment by NEZNAMY** [comment]
Sounds like 16 character limit, not a bug.
