### ISSUE TITLE
Disable features bug

### ISSUE THREAD

**Issue by pabloalba16** [NEZNAMY/TAB#37]
**Server version**
PaperSpigot 1.8.8 latest

**Plugin version** ("latest" is not a version)
TAB v2.5.2

**Describe the bug**
I have a list that indicates what worlds have to be disabled NameTag and TablistNames. It doesnt disables on that world but when i go to the lobby it applies the disabled nametag and tablist-feature.

**How to teproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)
https://imgur.com/6bVB09j (config)
https://imgur.com/oKw7Kcp (world that has to be disabled the features named before) this world is PlayCraft
https://imgur.com/LZhU9z7 (when you go back to the lobby) This world is SkyWarsLobby

**Comment by NEZNAMY** [comment]
Try new build on discord.
