### ISSUE TITLE
Bug with nickname "null"

### ISSUE THREAD

**Issue by Ynfuien** [NEZNAMY/TAB#373]
**Server version**
Airplane-Purpur 1.16.5

**Plugin version**
2.9.2

**Describe the bug**
Player with nickname "null" doesn't have nick shown on tab or in tag.

**Screens**
![image](https://user-images.githubusercontent.com/88110072/128875614-e0f24c04-d746-4302-9417-e5a6245a0d65.png)
![image](https://user-images.githubusercontent.com/88110072/128875921-949720c5-b2a3-4c47-bd52-6c9d67ab3f9d.png)

**Comment by NEZNAMY** [comment]
Show output of `/tab debug <player>`

**Comment by Ynfuien** [comment]
![image](https://user-images.githubusercontent.com/88110072/128914391-e4a5763e-48d9-4e34-8bb0-b1b11c70d08b.png)
![image](https://user-images.githubusercontent.com/88110072/128914557-223c7408-4c2d-4fab-9766-16f8d478fc49.png)

**Comment by NEZNAMY** [comment]
How does someone have such name in the first place?

**Comment by Ynfuien** [comment]
I'm running cracked server, so this player just use that nickname

**Comment by NEZNAMY** [comment]
Try to remove custom tab/tag name from `_OTHER_` group, essentials might be returning that.

**Comment by Ynfuien** [comment]
Uh, right, that's because custom tag/tab name. Thanks for help
