### ISSUE TITLE
Player's name still in place when disconnects, dies, teleported

### ISSUE THREAD

**Issue by MandelV** [NEZNAMY/TAB#374]
Serveur Version: 1.16.5 | 1.17.1 

Plugin version:  2.9.1.

**Description**
The player's name (above him) still in place when player disconnects, dies, teleported and so on...

**How to reproduce**
- Kill the player
- Player Disconnect
- teleportation
- change server (bungee)

**Expected behavior**

Player's name disappears

**Actual behavior**

Player's name still in place

**Additional info** 
before disconnection
![image](https://user-images.githubusercontent.com/22980065/129079386-386cb080-3236-4a29-85ae-f9d885dc71ba.png)

After :
![image](https://user-images.githubusercontent.com/22980065/129079457-957e285d-7ab7-47fb-aaca-c59e8a606a5b.png)

Note:
- if I disconnect / reconnect the players name disappears. Also,
- I do not have any errors in console about TAB.
- if the player is teleported from chunk that is not loaded for observer and observer comes into this chunk the bug will not be present as usual ^^

**Comment by NEZNAMY** [comment]
2.9.1 does not support 1.17.1, update.

**Comment by MandelV** [comment]
@NEZNAMY 
it work for other server, also it work fo one of my server so I will investigate what would cause that ^^

**Comment by Tanguygab** [comment]
he litteraly gave you the answer.... you need to update the plugin, you're using a version that doesn't support 1.17.1, 2.9.2 has been released and supports it

**Comment by Tanguygab** [comment]
si tu veux en français, t'as juste à mettre à jour le plugin, 2.9.1 ne supporte pas MC 1.17.1 alors que 2.9.2 si

**Comment by MandelV** [comment]
> 
> 
> si tu veux en français, t'as juste à mettre à jour le plugin, 2.9.1 ne supporte pas MC 1.17.1 alors que 2.9.2 si

Yep my fault I though I updated with 2.9.2... My bad...
