### ISSUE TITLE
Dev question

### ISSUE THREAD

**Issue by TheMG95** [NEZNAMY/TAB#375]
Hello, I recently tried to implement TAB support in my plugin. I followed the guide in the wiki. But when i use it, It says it cant find the TAB instance. How can i fix this?

Thanks

**Comment by NEZNAMY** [comment]
That means you shaded TAB's classes into your plugin jar, which is not allowed.

**Comment by TheMG95** [comment]
Thanks for the answer,
I really dont understand how i can use the api because the resources are limited. Can you give me an example of how i can change a players suffix?

Thanks

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Developer-API

**Comment by TheMG95** [comment]
I have already read the docs but i still cant understand how i can add a suffix to a player's name. 

Thanks.

**Comment by NEZNAMY** [comment]
`TABAPI.getPlayer(uuid).setValueTemporarily(EnumProperty.TABSUFFIX, "suffix")`
https://github.com/NEZNAMY/TAB/wiki/Developer-API#changing-prefixnamesuffix

**Comment by TheMG95** [comment]
I tried it but i still get this error:
`Cannot invoke "me.neznamy.tab.shared.TAB.getPlayer(java.util.UUID)" because the return value of "me.neznamy.tab.shared.TAB.getInstance()" is null`

**Comment by Tanguygab** [comment]
seems like TAB isn't loaded yet, did you add it to your plugin.yml's dependencies?

**Comment by TheMG95** [comment]
Oh yeah i forgot to thank you!!

**Comment by TheMG95** [comment]
I added `depend: [TAB]` to my plugin.yml but it still doesnt work.

**Comment by MrGraycat** [comment]
> 
> 
> I added `depend: [TAB]` to my plugin.yml but it still doesnt work.

Are you sure you didn't compile TAB's classes in your plugin?

**Comment by Tanguygab** [comment]
to make sure you didn't, you can open your plugin's jar file with 7Zip or WinRar and check if you have TAB's classes or not.

**Comment by TheMG95** [comment]
Oh yeah i think i compiled them in my plugin. How can i fix it?

**Comment by NEZNAMY** [comment]
In your compiler. We don't know what you're using and how to configure, check it's documentation or online discussions.

**Comment by TheMG95** [comment]
I'm using Maven and Intellij with the Minecraft Development plugin and just using the build configuration.

**Comment by NEZNAMY** [comment]
We don't know how to configure it. Try asking on a better place.
