### ISSUE TITLE
Player disappearing on server switch while using global playerlist and Velocity

### ISSUE THREAD

**Issue by Kikisito** [NEZNAMY/TAB#379]
**Server version**
[Paper build 210 and Velocity 3.0.0](https://user-images.githubusercontent.com/35898087/130699186-a9b1b56a-b012-41e3-9cc5-00bff11d961c.png)

**Plugin version** ("latest" is not a version)
TAB 2.9.2

**Describe the bug**
Players disappear from the tablist when they switch to another server.

**How to reproduce**
To reproduce this, you need to enable the global-playerlist option in config.yml and at least two servers. Once you have it enabled, join the server with two different accounts (**let's call these accounts Player1 and Player2**) and switch the server of Player2. Then, you will see from Player1 (the one that didn't switch) that Player2 has disappeared from the tab.

If Player1 disconnects and logs in again to the proxy, he will be able to see Player2, but as soon as Player2 switches again, Player1 will have again the same problem.

**Expected behavior**
It is expected to have both players in the tablist after the switch.

**Actual behavior**
Player2 disappears from Player1's tablist after the server switch. Player1 can only see players from his server.

**Additional info** (errors, screenshots, ...)
[What Player1 sees after Player2 switches server](https://user-images.githubusercontent.com/35898087/130699807-9b507767-d6a1-4629-b1b0-b3b1f3f898e9.png)
[What Player2 sees](https://user-images.githubusercontent.com/35898087/130699825-a64113f1-ef59-4849-bd96-bb4ea6a224c8.png)

**Comment by NEZNAMY** [comment]
Velocity options are very limited and don't allow an effective way of preventing proxy itself from clearing playerlist on server switch. I guess I could add a delay in server switch event listener and resend all entries.

**Comment by Kikisito** [comment]
Thanks for the quick support! I didn't see the Compatibility page, sorry for that. If it is possible to receive some help, is it possible [that this line](https://github.com/VelocityPowered/Velocity/blob/9a15c7e170ba12ed3acb71257365ff7d1c775443/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java#L372) is causing this issue? I couldn't find anything else.

**Comment by NEZNAMY** [comment]
Yes, that's the line clearing players on server switch.

**Comment by Kikisito** [comment]
I have tested a Velocity build without that line and the issue persists. Anyways, it seems that the tablist entries are sent before a clear (exactly as you say), and I can't find any other solution than adding a delay. This would be possible to add?

**Comment by NEZNAMY** [comment]
Technically it would, you can try it.

**Comment by Kikisito** [comment]
I tried a delay of 100ms and it seems to work correctly. I mean if it would be possible to add in the original plugin so other players don't have this problem.

**Comment by NEZNAMY** [comment]
Velocity is not officially supported, they should not even try to use TAB on it. I am still waiting for API improvements, for now, I don't really care if the plugin works on velocity or not.

**Comment by Kikisito** [comment]
Understood. Thanks for helping locating the issue^^

**Comment by Thefirstalpha** [comment]
Hello, I'm just reopening this issue because I currently have the same, and I understand how I can fix it by myself.
But I see that you said that your thinking of dropping Velocity support. Now that PaperMC team decide to include Velocity project and will maybe replace the waterfall fork of bungeecord by velocity (maybe ^^), are you steel on the same thinking way ?
My question is more, is this issue will be fix in the next update for version 1.18 ?

**Comment by NEZNAMY** [comment]
> Hello, I'm just reopening this issue because I currently have the same, and I understand how I can fix it by myself. But I see that you said that your thinking of dropping Velocity support. Now that PaperMC team decide to include Velocity project and will maybe replace the waterfall fork of bungeecord by velocity (maybe ^^), are you steel on the same thinking way ? My question is more, is this issue will be fix in the next update for version 1.18 ?

Whether or not they will add API methods is not a question on me.

**Comment by Thefirstalpha** [comment]
I hope they will add some more ! Ok thanks you for your super fast answer :)
