### ISSUE TITLE
Luckperms

### ISSUE THREAD

**Issue by Kirito1786** [NEZNAMY/TAB#381]
im on 1.17 and i dont know how to sort out ranks like i dont want default rank to be above owner rank can you fix that?

**Comment by NEZNAMY** [comment]
No, I can't hack your server and configure luckperms weights for you, you must do that yourself.

**Comment by Kirito1786** [comment]
ok but like the luckperms im using is fine but when i op somone they auto go top but a rank for op people also go above owner 
and i want to order them how to do?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
