### ISSUE TITLE
left side of < condition only accepts numeric values! (Attempted to use "%health%")

### ISSUE THREAD

**Issue by Beoo-666** [NEZNAMY/TAB#382]
It prompts in bungeecord, and I have turned it off in bungeecord.
![image](https://user-images.githubusercontent.com/55978588/131256952-9fcc2dd9-52ab-4667-9622-5409b10c79a6.png)

**Comment by NEZNAMY** [comment]
You didn't. You still use the placeholder somewhere. That's not a valid bungeecord placeholder either.

**Comment by Beoo-666** [comment]
I use it in the sub-server, and I am now testing it off in the sub-server

**Comment by NEZNAMY** [comment]
Can you move this to discord? It will be faster.

**Comment by Beoo-666** [comment]
可以
