### ISSUE TITLE
Riding players nametag bug

### ISSUE THREAD

**Issue by TheBeefDev** [NEZNAMY/TAB#385]
Hello, I have created a simple player-carry plugin for someone where you can type /carry to send a carry request to the player you are looking at. If they accept they ride you (Entity#addPassenger). The person I made the plugin for uses TAB on their server. It worked fine at the start but when I enabled unlimited-nametag-prefix-suffix-mode the nametag struggles to keep up with the player. This issue does not happen when riding a horse the vanilla way. In the config I just put some random stuff they told me to paste in, but here it is just incase you find it useful.

[config.yml.zip](https://github.com/NEZNAMY/TAB/files/7111004/config.yml.zip) 

Server version: 1.16.5
TAB version: v2.9.2 

Here is a video showcasing the bug: https://youtu.be/Yl-AWuFhNto

Also, my carrying method is just the normal Entity#addPassenger but here it is anyway.
```java
public static void carry(final Player carrier, final Player target) {
        CARRYING.put(carrier.getUniqueId(), target.getUniqueId()); //HashMap<UUID,UUID>
        carrier.addPassenger(target);
}
```

**Comment by NEZNAMY** [comment]
The youtube is not available at this time, is the issue delayed movement? If yes, it's caused by player movement animation which other players see, but moving player doesn't. Is it same as when using /tab ntpreview? If yes, this is not really fixable, since armor stands are on player's server-side location, which doesn't match what moving player sees.

**Comment by TheBeefDev** [comment]
Hey, sorry for the late reply, also sorry for the yt video it was my fault it should be visible now. It is indeed the same when I type /tab ntpreview. If that means its not fixable, then sorry for wasting your time.

**Comment by NEZNAMY** [comment]
This isn't fixable, as I said already.

**Comment by TheBeefDev** [comment]
Ok then
