### ISSUE TITLE
Check the status of the placeholder and display the different information I set

### ISSUE THREAD

**Issue by FZDNSZYT** [NEZNAMY/TAB#386]
Is there a way to detect the status of the placeholder, and then display it on the top of the player's head and in the tab, I set it in advance, and output different information according to different status. For example, the player's online status, afk status.

**Comment by NEZNAMY** [comment]
I don't understand this question. Placeholders display whatever they are made to display.

**Comment by FZDNSZYT** [comment]
I mean, check the placeholder, and then display the information according to the placeholder

**Comment by FZDNSZYT** [comment]
After all, some plug-in placeholders can only output signals and cannot display intuitive information.

**Comment by FZDNSZYT** [comment]
For example, the CMI placeholder %cmi_user_afk% will only output "true" and "false". But I want to make his display more intuitive, according to "true" and "false", respectively display "online" and "away"

**Comment by Tanguygab** [comment]
the premium version already has this feature, it's called placeholder-output-replacements.
otherwise, it's not TAB's job to change placeholders outputs
also, I'm pretty sure CMI has a language file where you can change the output of all of its placeholders.

**Comment by FZDNSZYT** [comment]
Does this plugin support MySQL database reading? The permission group I set with the LuckPerms plug-in cannot be read by TAB at all. No matter how it is set, only the administrator’s default information will be displayed. The information of other players is not displayed at all.

**Comment by FZDNSZYT** [comment]
I struggled with this problem for three days, and then I began to wonder if it was because I used the MySQL database to save the data of other plug-ins. So the group information I set here in TAB will not be displayed at all.

**Comment by Tanguygab** [comment]
is TAB on Spigot or BungeeCord? and LuckPerms?
make sure LuckPerms is detected by TAB in /tab debug (/btab when TAB is on Bungee)

**Comment by FZDNSZYT** [comment]
It is the core of paper and is not installed in BungeeCord. Not only the group set by LuckPerms, the default group also has no response.

**Comment by FZDNSZYT** [comment]
I use /tab reload, and restarting the server cannot take effect.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups might help

**Comment by FZDNSZYT** [comment]
> https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups可能有帮助
Both methods have been tried, but none of them work. Maybe you can consider adding MySQL database support

**Comment by FZDNSZYT** [comment]
Wait, it seems that not all groups are impossible. The default I set does not work, but the Player group works. I don't understand this mysterious error.

**Comment by FZDNSZYT** [comment]
You know, only the default group will automatically add permissions, so

**Comment by Tanguygab** [comment]
send the output of /tab debug <player>
on a plyer which doesn't have the right group
