### ISSUE TITLE
Prefixes and sorting don't work on Velocity

### ISSUE THREAD

**Issue by SlenkyDev** [NEZNAMY/TAB#390]
**Server version**
Velocity 3.0.1

**Plugin version** ("latest" is not a version)
2.9.2

**Describe the bug**
The prefixes don't show, nor does the sorting work.

**How to reproduce**
Make a LPV group, put the group with a prefix into the TAB plugin, restart the server.

**Expected behavior**
You see your prefix in the tablist and your name is sorted

**Actual behavior**
Your name stays the same

**Additional info** (errors, screenshots, ...)

**Comment by SlenkyDev** [comment]
Okay, are there any alternatives for the sorting?

**Comment by NEZNAMY** [comment]
Bungeecord or backend installation.

**Comment by SlenkyDev** [comment]
Okay, thanks!
