### ISSUE TITLE
Players can see vanished players on the tablist (bungee)

### ISSUE THREAD

**Issue by ryzech** [NEZNAMY/TAB#391]
**Server version**
Waterfall Build 449 1.17.1

**Plugin version** ("latest" is not a version)
2.9.2

**Describe the bug**
When i'm vanished every player can see me in the tablist, i'm using SuperVanish and its installed on every server. And no they don't have the permission to see me

**How to reproduce**
Install SuperVanish on spigot servers, and install tab on a bungee server. Players will then see you while youre vanished.

**Expected behavior**
Players don't see me when i'm vanished

**Actual behavior**
Players can see me on the tablist when im vanished, i tested it myself on an alt and i could see my username.

**Comment by Tanguygab** [comment]
do you use the Global-playerlist? if yes, install the Bukkit-bridge on all servers

**Comment by ryzech** [comment]
i do use global playerlist, i tried the bridge but it caused a bit of lag, i can try it again though and hope it doesnt this time

**Comment by Tanguygab** [comment]
well it's the only way to detect the vanish status of a player from a vanish plugin on Spigot with TAB on BungeeCord, also I don't think it would impact the TPS at all, or at least it wouldn't cause any lags
