### ISSUE TITLE
scoreboard bug

### ISSUE THREAD

**Issue by xsorencoolx** [NEZNAMY/TAB#394]
**1.16.5**

**Plugin version** (2.9.2)

**so there is bug like when your player join with 1.8 in server scoreboard won't show I mean half of the score board will show to him
![image](https://user-images.githubusercontent.com/51112473/136741379-6de394f0-7123-4397-9cee-726549e36115.png)

it shows like this but when he joins with 1.16.5 or higher version it's okay and show this

![image](https://user-images.githubusercontent.com/51112473/136740440-435ff8ce-5d40-487d-8922-568417f48b39.png)

**Comment by MrGraycat** [comment]
Hello

This doesn't look like a bug but more like a minecraft limitation.
Check out: https://github.com/NEZNAMY/TAB/wiki/Limitations#scoreboard
