### ISSUE TITLE
[Bug Report] PremiumVanish Still Showing in "Online Staff:" Area. 

### ISSUE THREAD

**Issue by ghost** [NEZNAMY/TAB#398]
**Server version**
1.17.1 Paper Spigot

**Plugin version** ("latest" is not a version)
TAB v2.9.2

**Describe the bug**
"Online Staff: 1" When staff go in vanish with the PremiumVanish Plugin

**How to reproduce**
Install PremiumVanish, give staff the permission tab.staff, go in /vanish

**Expected behavior**
Online Staff should show 0 if 1 staff is online and they are vanished

**Actual behavior**
Online Staff shows 1 if 1 staff is online and they are vanished

**Additional info** (errors, screenshots, ...)
(Unable to grab screenshot at the moment)

**Comment by gelsbern** [comment]
So I followed the link because I want staff who are not visible to not show in the count.  The FAQ you linked is not there anymore.  How can this be done currently?

**Comment by NEZNAMY** [comment]
%online%
