### ISSUE TITLE
Add option to show all players on bungee

### ISSUE THREAD

**Issue by NEZNAMY** [NEZNAMY/TAB#4]
Bungee version needs a feature to show all players from all servers instead of just the player's current server.

**Comment by fjeddy** [comment]
+1

**Comment by HugoMauricio72** [comment]
It is a good idea for me can you do this Neznamy, I think you can be based on BungeeTablist but with your ideas, you are the best Dev

**Comment by Louuuwh** [comment]
Good idea

**Comment by iamharak** [comment]
+1

**Comment by NEZNAMY** [comment]
I wonder how many of you +1's will actually agree to test the jar once i do it.

**Comment by fjeddy** [comment]
Considering I'm the only +1 then well! :P I'm using BTLP at the moment, to get this feature, literally just waiting for you to support it so I can switch 💃

**Comment by lokipea** [comment]
I'm down to test the jar aswell. :)
