### ISSUE TITLE
Empty above name visible

### ISSUE THREAD

**Issue by pgmann** [NEZNAMY/TAB#40]
**Server version**
1.13.2

**Plugin version** ("latest" is not a version)
2.5.3-pre2

**Describe the bug**
An empty background is visible in the above player name slot when relational placeholders are evaluated to an empty string for this position (may affect other positions too, didn't test).

**How to teproduce**
Set above name to a relational placeholder which evaluates to an empty string.

**Expected behavior**
The above name line should be completely invisible.

**Actual behavior**
The above name line has an armour stand with an empty name string.

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Try new build.
