### ISSUE TITLE
An error occurred when reading packets

### ISSUE THREAD

**Issue by SrBedrock** [NEZNAMY/TAB#400]
**Server version:** 1.16.5 and 1.17.1

**Plugin version:** TAB v2.9.2 Premium

Server v1.16.5 error.log: https://gist.github.com/SrBedrock/300316627618eb8a4ef074c68d50ce3e
Server v1.17.1 error.log: https://gist.github.com/SrBedrock/d1749170057729f03586ef48b5eb6c0d

**Comment by MrGraycat** [comment]
Hello

This issue has been fixed already, please join the discord and open a ticket so we can send you a fixed premium jar.

Thanks
MrGraycat
