### ISSUE TITLE
Capitalization sorting 

### ISSUE THREAD

**Issue by elenyi** [NEZNAMY/TAB#401]
Is there a way to ignore the capitalization when it comes to sorting? It sorts people with uppercase letters first then lowercase after

**Comment by MrGraycat** [comment]
Hello

This is the default way sorting works, this could technically be bypassed using the premium version of TAB.
Then you can also sort by placeholders which if they just returned the lowercase playername should ignore the capitalization.

MrGraycat

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/resources/premiumconfig.yml#L21
