### ISSUE TITLE
Belowname doesn't works...

### ISSUE THREAD

**Issue by FakeKoktis** [NEZNAMY/TAB#403]
**Server version**
1.12.2 (With ViaVersion 1.8 - 1.17) / Using Minecraft Lunar client with version 1.8...

**Plugin version** ("latest" is not a version)
2.9.2

**Describe the bug**
Even when I have everything enabled like `unlimited-nametag-prefix-suffix-mode:
  enabled: true` still can't see my belowname...

**How to reproduce**

**Expected behavior**
Can see the belowname

**Actual behavior**
Can't see it...

**Additional info** (errors, screenshots, ...)
I've used a command to create belowname too... (/tab group _OTHER_ belowname...)
![image](https://user-images.githubusercontent.com/25692574/141337216-2d2ecad3-e90c-4c15-8a44-70d5be70b3fc.png)

**Comment by NEZNAMY** [comment]
Because you did not use /tab ntpreview to see your own armor stands.

**Comment by FakeKoktis** [comment]
> Because you did not use /tab ntpreview to see your own armor stands.

Musí to používat každý hráč?

**Comment by FakeKoktis** [comment]
Thank you.

**Comment by FakeKoktis** [comment]
It's solved now...
