### ISSUE TITLE
[v3] Global scoreboard disappears when switching servers

### ISSUE THREAD

**Issue by Yurinann** [NEZNAMY/TAB#408]
**Server version**
Paper 1.17.1 381 with FlameCord (Waterfall Fork) https://github.com/2lstudios-mc/FlameCord/commit/52117070459346d57e48da401f82c0a2bf6e1d96

**Plugin version** ("latest" is not a version)
3.0.0-pre2 (https://github.com/NEZNAMY/TAB/commit/3688e4d938fd0162a03fafed71031e9bc82d90d8)

**Describe the bug**
The scoreboard disappears when I switch servers, and turns off and then on after using the custom toggle scoreboard display command.
I didn't have their separate scoreboard for subservices (and don't seem to have one now), and this one is global.

**How to reproduce**
1. Switch servers (BungeeCord)

**Expected behavior**
It can also be displayed normally when switching servers.

**Actual behavior**
Disappears when switching servers (in other words, any connection switch without the player disconnecting from the connection provided by Bungee will cause the scoreboard to disappear)

**Additional info** (errors, screenshots, ...)
No errors

Thank you for your help!

**Comment by NEZNAMY** [comment]
Can you set debug: true and check console output when scoreboard disappears?

**Comment by Yurinann** [comment]
Of course! Here they are:
```
[18:36:02 INFO]: [TAB v3.0.0-pre2] Something just tried to add player Yurinann into team 999997e8a7f3e-1 (expected team: 2YurinannA)
[18:36:02 INFO]: [TAB v3.0.0-pre2] Something just tried to add player Yurinann into team 07e8a7f3e-1 (expected team: 2YurinannA)
```

**Comment by NEZNAMY** [comment]
Is that all? Nothing related to scoreboard?

**Comment by Yurinann** [comment]
> Is that all? Nothing related to scoreboard?

When joining the server for the first time, some information about detected variables is shown, but they only appear at the very beginning (when the scoreboard is displayed). These are the only messages that appear in the background after the scoreboard disappears.

**Comment by NEZNAMY** [comment]
Are you using plugin SkBee? Packet detection doesn't always work on proxy, try putting TAB on backend server, it might give better results.

**Comment by Yurinann** [comment]
I am not using this plugin.
In testing, this problem also occurs when no other bc plugins are installed.

I will install the plugin to the subserver to see if the issue exists.

**Comment by Yurinann** [comment]
As expected, this problem disappears.

**Comment by Yurinann** [comment]
So what should we do now?

**Comment by NEZNAMY** [comment]
I was able to reproduce the issue, investigating.

**Comment by Yurinann** [comment]
The problem has been solved, thank you for your help.
