### ISSUE TITLE
Vanished players (moderators) can be seen because of their plate

### ISSUE THREAD

**Issue by RSLuke** [NEZNAMY/TAB#41]
**Server version**

**Plugin version** ("latest" is not a version) : 2.5.2

**Expected behavior**
Players tags shouldn't be seen when vanished

**Actual behavior**
Players can see them, screenshot ->

**Additional info** (errors, screenshots, ...)
https://media.discordapp.net/attachments/614102652615393283/626053914277576715/unknown_6.png?width=1086&height=611

**Comment by NEZNAMY** [comment]
Bug related to unlimited nametag mode.

**Comment by NEZNAMY** [comment]
Could you please make a guide how to reproduce it ? As simple as possible.

**Comment by AntoineHrn** [comment]
Well,
I use the plugin CMI which includes a vanish mode which I give to my moderators.
I'm under Bungee and PaperSpigot servers in 1.13.2 and 1.14.4
Moderators just teleport to players vanished to patrol the player but can be seen (with the tag) like 1/3 times.
I'll use an older version while this is fixed !

**Comment by NEZNAMY** [comment]
Can you find out how or if is this related to sneaking while being vanished ?

**Comment by AntoineHrn** [comment]
Nothing related to sneaking

**Comment by NEZNAMY** [comment]
I was unable to reproduce this with the latest plugin build. Can you try it ?

**Comment by AntoineHrn** [comment]
Hello there, it's still here after the update, when I'm teleporting to a player, he can see my nametag but it doesn't move when I move.

**Comment by NEZNAMY** [comment]
Does it happen when you teleport to the player cross-world, long distance or even short distance ?

**Comment by AntoineHrn** [comment]
It happened long distance, I couldn't reproduce yet for the cross-server or short distance

**Comment by NEZNAMY** [comment]
Can you try new build from discord ?
