### ISSUE TITLE
[ISSUE] Scoreboard not turning on automatically.

### ISSUE THREAD

**Issue by uruhara** [NEZNAMY/TAB#412]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
TAB_Premium_v2.9.2

**Describe the bug**
scoreboard

**How to reproduce**
1) Bungeecord proxy redirects you to AuthMe server
2) AuthMe world (server) is disabled in premiumconfig

  **disable-in-worlds:**
     - AuthMe
     
3) remember-toggle-choice: true
4) hidden-by-default: false
5) On lobby, scoreboard is toggled off automatically, even if hidden-by-default is false
6) After authenticating on AuthMe, you are teleported to Lobby

**Expected behavior**
Scoreboard is disabled on AuthMe, however, once I am teleported from AuthMe to Lobby, it is now enabled (or disabled accordingly to remember-toggle-choice)

**Actual behavior**
Scoreboard is disabled on AuthMe and once I am teleported to Lobby, it remains disabled regardless of hidden-by-default being false and being previously toggled ON by me.

**Additional info** (errors, screenshots, ...)
You can fix this by setting disable-in-worlds to no worlds (servers), setting default-scoreboard to NONE and use per-world scoreboards.

**Comment by NEZNAMY** [comment]
Will be fixed in the next version.
