### ISSUE TITLE
Essentials API is called before Essentials is loaded

### ISSUE THREAD

**Issue by uruhara** [NEZNAMY/TAB#419]
**Server version**
1.16.5

**Plugin version** ("latest" is not a version)
2.9.2 Premium

**Describe the bug**
TAB tries to access Essentials's placeholders before the essentials is actually loaded.

**How to reproduce**
Start the server and see it?

**Expected behavior**
-

**Actual behavior**
-

**Additional info** (errors, screenshots, ...)
28.11.2021 - 19:38:39 - [TAB v2.9.2 Premium] PlaceholderAPI v2.10.10 generated an error when setting placeholder %vault_eco_balance_formatted% for player NoxTea
28.11.2021 - 19:38:39 - java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
28.11.2021 - 19:38:39 -        at com.earth2me.essentials.api.Economy.getUserByUUID(Economy.java:107)
28.11.2021 - 19:38:39 -        at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:158)
28.11.2021 - 19:38:39 -        at com.earth2me.essentials.economy.vault.VaultEconomyProvider.getBalance(VaultEconomyProvider.java:116)
28.11.2021 - 19:38:39 -        at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:223)
28.11.2021 - 19:38:39 -        at com.extendedclip.papi.expansion.vault.VaultEcoHook.onPlaceholderRequest(VaultEcoHook.java:177)
28.11.2021 - 19:38:39 -        at com.extendedclip.papi.expansion.vault.VaultExpansion.onRequest(VaultExpansion.java:108)
28.11.2021 - 19:38:39 -        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
28.11.2021 - 19:38:39 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
28.11.2021 - 19:38:39 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform.setPlaceholders(BukkitPlatform.java:240)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.platforms.bukkit.BukkitPlatform$2.get(BukkitPlatform.java:205)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:36)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.shared.features.PlaceholderManager.updatePlayerPlaceholder(PlaceholderManager.java:116)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.shared.features.PlaceholderManager.lambda$new$0(PlaceholderManager.java:81)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.shared.cpu.CPUManager.lambda$startRepeatingMeasuredTask$2(CPUManager.java:146)
28.11.2021 - 19:38:39 -        at me.neznamy.tab.shared.cpu.CPUManager.lambda$submit$4(CPUManager.java:180)
28.11.2021 - 19:38:39 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
28.11.2021 - 19:38:39 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
28.11.2021 - 19:38:39 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
28.11.2021 - 19:38:39 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
28.11.2021 - 19:38:39 -        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by NEZNAMY** [comment]
TAB is trying access PlaceholderAPI as you can see. It has no control over further behavior.
