### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#420]
**Server version**
1.17

**Plugin version** ("latest" is not a version)
3.0

**Describe the bug**
After restarting the server, logs displays me this error with placeholder sorting.
And that's why sorting player isn't working.
Im using bungee tab version
**How to reproduce**
putting this into the placeholder sorting:
    - "PLACEHOLDER:%player_name%:Feuerelfe,SuperMem,NetzkroneHD"
and restart btab

**Expected behavior**
it shouldn't appear as issue. 

**Actual behavior**
tab wont be sorted for these players listed up

**Additional info** (errors, screenshots, ...)
[https://gyazo.com/97296fec20b1a1e305f2abb4681fa15c](https://gyazo.com/97296fec20b1a1e305f2abb4681fa15c)

[https://gyazo.com/ce9ee833edf2b4a200c2e82181f362f8](https://gyazo.com/ce9ee833edf2b4a200c2e82181f362f8)
here you can see if you execute /btab parse %placeholderr% (which is valid)

[https://gyazo.com/6166f0b9d1f9539ad6ab1f75af5a0149](https://gyazo.com/6166f0b9d1f9539ad6ab1f75af5a0149)
if reload the plugin this will be shown

**Comment by supermem99** [comment]
[https://gyazo.com/f8ba3f4474f5c44fdfcbd67ab5d07824](https://gyazo.com/f8ba3f4474f5c44fdfcbd67ab5d07824)
but I noticed, that if I join with my name which is ordered, it will be shown as null. other normal users will shown as their names not as null.
[https://gyazo.com/195aba97da2d36ab95930497f5ec740e](https://gyazo.com/195aba97da2d36ab95930497f5ec740e)

**Comment by supermem99** [comment]
btw. if i parse a placeholder from my plugin, it will show me null with color and without null

**Comment by Tanguygab** [comment]
did you install the BukkitBridge on your backend server?

**Comment by supermem99** [comment]
ya

**Comment by NEZNAMY** [comment]
Use "PLACEHOLDER_A_TO_Z" instead.

**Comment by supermem99** [comment]
but It should be like the order. i have written

**Comment by NEZNAMY** [comment]
That sorting type only works for finite amount of possible outputs. It is not applicable for your case. Use permission groups or sorting by permissions instead.
