### ISSUE TITLE
Nicknames broken after update

### ISSUE THREAD

**Issue by Baggette** [NEZNAMY/TAB#423]
**Server version**
1.17.1

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
essentials nicknames not working after the update. it worked when I used 2.9.2

**How to reproduce**
update to 3.0.0 and nicknames in the tablist are broken

**Expected behavior**
nicknames work and show in the tablist

**Actual behavior**
nicknames do not work and display %essentialsnick%

**Additional info** (errors, screenshots, ...)
theres no errors from the console
https://drive.google.com/file/d/1OU4xuqbTzZmaFVvrUgM05Zoa98mL5psT/view?usp=sharing

**Comment by NEZNAMY** [comment]
You just didn't even bother reading changelog and straight up replaced the jar. I will add the placeholder back in next version to avoid issues like this.

**Comment by Baggette** [comment]
> You just didn't even bother reading changelog and straight up replaced the jar. I will add the placeholder back in next version to avoid "issues" like this.

oh sorry my bad. Ill close this issue then.
