### ISSUE TITLE
Nickname placeholder does not work

### ISSUE THREAD

**Issue by Jonehej** [NEZNAMY/TAB#424]
**Server version**
1.18

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
When I use an essentials nickname it says "%essentialsnick% in the tab instead of my name.

**How to reproduce**
Use a nickname in essentials with "/nick"

**Expected behavior**
My nickname should be displayed.

**Actual behavior**
%essentialsnick% is displayed instead of my essentials nickname.

**Additional info** (errors, screenshots, ...)
![2021-12-04_23 53 54](https://user-images.githubusercontent.com/91684119/144727015-8747f8f2-c49a-4ea0-9034-938a24bc097b.png)

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/issues/423

**Comment by SrathYT** [comment]
**Hello, I Will Help You Fix It**

**First Step:**

**You Open Tab Folder And Open group.yml scroll down
until you see %essentialsnick%**

**Second Step:**

**You Change %essentialsnick% to %player_name% make sure you have placeholderapi-expansions-player**

**Finish, Enjoy**
