### ISSUE TITLE
Nametag with unlimited mode

### ISSUE THREAD

**Issue by exzolink** [NEZNAMY/TAB#425]
**Server version**
Aiplane 1.16.5

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
So, if enable unlimited mode and remove nametag from dynamic lines it will fully disappear

**Comment by NEZNAMY** [comment]
Makes sense. What do you want to happen instead?

**Comment by exzolink** [comment]
Show vanilla nametag (not armorstand)

**Comment by NEZNAMY** [comment]
That's not how the feature works. You either use armor stands or vanilla names. You can't choose it per-line, moslty because vanilla name's height cannot be changed.

**Comment by exzolink** [comment]
It is logical that if I remove the nametag from dynamic lines, then I want to show the vanilla nametag and will customize belowname/abovename height

**Comment by NEZNAMY** [comment]
If you did that, belowname would collide with the name. There is absolutely no benefit from implementing this, just giving me more work to do and possibly more bugs.

**Comment by exzolink** [comment]
Ok, its up to you. Anyway thanks.
