### ISSUE TITLE
Players randomly not sorted correctly

### ISSUE THREAD

**Issue by haeiven** [NEZNAMY/TAB#426]
**Server version**
1.8.9

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
Players are randomly not sorted correctly and placed at the top of the tablist without any reason.
It's not on connected / disconnect event, i can't rly figure this out...

**Additional info** (errors, screenshots, ...)
no errors in console, nothing in TAB errors.log

**Comment by NEZNAMY** [comment]
You didn't send your config.

**Comment by haeiven** [comment]
Sorry, i missed to paste the link: https://paste.soleria.eu/duzolizogu.yaml

**Comment by NEZNAMY** [comment]
If this is a bug report then I need steps to reproduce it.

**Comment by NEZNAMY** [comment]
I was unable to reproduce the issue and therefore need more steps.

**Comment by NEZNAMY** [comment]
Does /tab reload fix it? If not, then you didn't configure sorting correctly.

**Comment by haeiven** [comment]
Hello,

Yes tab reload fix the issue. I'm still not able to provide more information since the tab debug doesn't give me anything about the players being not sorted correctly ::

**Comment by NEZNAMY** [comment]
Check TAB's folder for .log files and send them if you got any.

**Comment by NEZNAMY** [comment]
Sounds like another plugin is overriding TAB. Try to find out which one.

**Comment by haeiven** [comment]
Huh, it wasn't happening before i update to TAB v3... i don't have any plugin managing this.

**Comment by Tanguygab** [comment]
do you use eGlow ? if yes, you should update it

**Comment by haeiven** [comment]
No, i'm not

**Comment by NEZNAMY** [comment]
Are you using a nick plugin?

**Comment by haeiven** [comment]
nop

**Comment by NEZNAMY** [comment]
Try to find steps to reproduce it.

**Comment by haeiven** [comment]
Players who are not sorted aren't updated. Belowname placeholders don't works for them until i reload tab or they disconnect/reconnect. 

But i do not have any logs / errors...

**Comment by haeiven** [comment]
Bump?

**Comment by NEZNAMY** [comment]
Not sure how that will help, I am not able to reproduce your issue, therefore I can't do anything right now.

**Comment by haeiven** [comment]
Could you add some debug? i don't know what is happening, but it's happening to 5-10% of the players on the server :/

**Comment by NEZNAMY** [comment]
If you're interested in that way, open a ticket on discord.

**Comment by NEZNAMY** [comment]
Caused by misconfiguration.
