### ISSUE TITLE
PAPI placeholder reads as null on server login

### ISSUE THREAD

**Issue by zeiinsito** [NEZNAMY/TAB#428]
**Server version**
Waterfall (build 465)
Paper 1.18 (Paper build 54)

**Plugin version** ("latest" is not a version)
TAB 3.0.0
TAB BukkitBridge 1.5.2

**Describe the bug**
"Belowname" and "Yellow-number" seem to initialize their values before reading the PlaceholderAPI's given value, making it to return "null" and making the plugin prints out the "yellow number only accepts numeric values! (Attempted to use "null")" and "belowname number only accepts numeric values! (Attempted to use "null")" errors.
Then, the placeholder value is read by TAB and printed correctly, but the errors.log file has alredy been created and written.

**How to reproduce**
1. Set "Belowname" or "Yellow-number" values to a valid PAPI placeholder like "player_health".
2. Log-in into the server.
3. An error is printed as the placeholder value is null for an instant.

**Expected behavior**
The placeholder value shouldn't never be read as "null", so the errors.log file shouldn't be never created with the above mentioned errors.

**Actual behavior**
The placeholder value is read as "null", so the plugin creates the errors.log file with the above mentioned errors on it.

**Comment by NEZNAMY** [comment]
How should a placeholder value be read before initial response comes from bridge?

**Comment by zeiinsito** [comment]
> How should a placeholder value be read before initial response comes from bridge?

I know that it doesn't have any sense, as TAB located in the proxy has to wait to the server's PAPI value, but on previous versions to the 3.0.0, this didn't ever happen, as the plugin never printed out the error telling that the value is "null".

**Comment by NEZNAMY** [comment]
Before it returned the identifier itself. "null" is a mini-bug which will be fixed in the next version.

**Comment by zeiinsito** [comment]
Now that I remember, it is true that before the plugin returned the string of the placeholder directly until PAPI gave TAB the real value.
I understand that this has been removed, so now TAB only expects the placeholder value defaulting to null.

This could be solved by having TAB wait more time for the value before it tries to render it out, or by changing the default value from null to something else.
Anyway, as I understood, you already have in mind a solution to this problem.
