### ISSUE TITLE
Tablist not being auto-refreshed on server switching

### ISSUE THREAD

**Issue by Boy0000** [NEZNAMY/TAB#429]
**Server version**
Velocity 3.1.0
Paper-108 (MC: 1.17.1)

**Plugin version** ("latest" is not a version)
TAB.v3.0.0

**Describe the bug**
Whenever a player logs in/switches servers on the proxy, the tablist is not displayed correctly.
When a staff member `/vtab reload`'s it shows correctly, until one rejoins or switches server.

**How to reproduce**
1. Join server
2. Tablist is not correctly displayed
3. `/vtab reload`
4. Switch server or relog
5. Broken again

**Expected behavior**
Should get same result as after running `/vtab reload`

**Actual behavior**
Server prefixes are not displayed correctly.

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/62521371/144947010-76866558-7ee5-49b0-8268-14dc494bed61.png)
Intended result and one achieved after doing `/vtab reload`
![image](https://user-images.githubusercontent.com/62521371/144947040-f42d1804-8d5f-44d4-ae31-559f6064cbe9.png)
Result whenever one switches server or logs on. Server prefixes are missing from most players.

[Config](https://paste.soleria.eu/yekagutohe.yaml)
**Sidenote**: It is not actually sorted correctly either but as I understood its due to Velocity not having Scoreboard API

**Comment by Tanguygab** [comment]
Velocity issue, NEZ already tried to kinda fix it, but it didn't seem to work.
