### ISSUE TITLE
Maven Support

### ISSUE THREAD

**Issue by FeaturedSpace** [NEZNAMY/TAB#43]
Hello! After having several issues with so many other plugins, I've been trying to use your API in our core development. However, since your project is not hosted on maven, we are unable to use it in our projects.

Would it be possible to convert to maven? (We've tried self hosting and it doesn't appear to work :/)

**Comment by HugoMauricio72** [comment]
Hello, If you have more support or you can talk with Nez please join to his discord: https://discord.gg/ZZDcrD8

**Comment by HugoMauricio72** [comment]
I forgot to tell you, you can download the latest build on a Discord server and you can try it if it is working

**Comment by NEZNAMY** [comment]
Can you PM me on discord ?

**Comment by fjeddy** [comment]
@FeaturedSpace Why don't you just import the plugin as a local file directly in your maven project? I get that it's simpler for you to just include a repository in your config file and have Maven handle the imports, but there is nothing stopping you from manually including it yourself..

Or?

**Comment by FeaturedSpace** [comment]
@fjeddy I've yet to be able to successfully import a file into a maven project on IntelliJ. I can only use maven repositories (so I'd have to make an offline one?)

**Comment by NEZNAMY** [comment]
Have you found a workaround ?

**Comment by FeaturedSpace** [comment]
There are little workarounds besides recompiling under maven. Which was just the same as rewriting my own system

**Comment by NEZNAMY** [comment]
Do you still want this ?

**Comment by NEZNAMY** [comment]
I guess not.

**Comment by FeaturedSpace** [comment]
@NEZNAMY I do not require it, as we decided to build an in-house solution. Thanks again!

**Comment by A248** [comment]
For others wanting to use TAB as a dependency, you can use a system scope dependency and specify the path, or use a file repository so you don't have to deal with warnings about dependencies inside the project path.
