### ISSUE TITLE
TAB's Sorting system not working.

### ISSUE THREAD

**Issue by GaetanoXD** [NEZNAMY/TAB#431]
**Server version**
- Pufferfish 1.18

**Plugin version** ("latest" is not a version)
 - TAB v3.0.0

**Describe the bug**

The TAB sorting system is not consistent with the configuration, users are assigned in random places on the tablist, changing luckperms parents on the player has no effect, and re-accessing the server does not resolve the error.

**How to reproduce**

There is no real method of reproduction being that this is done automatically, you can try it through: setting a parent from luckperms lower at the sorting level.

**Expected behavior**

Correct use of sorting through configuration, example: [founder,admin,mod,helper] (from left to right for priority)

**Actual behavior**

Players are assigned to a random place on the tablist not respecting sorting

**Additional info** (errors, screenshots, ...)

Screenshot: https://i.imgur.com/C17mY5T.png
Configuration: https://pastebin.com/itKS9nxs
(NOTE: anti-ovverride on true don't fix the bug)

**Comment by NEZNAMY** [comment]
I am guessing you didn't configure weights in luckperms.

**Comment by GaetanoXD** [comment]
The weights of the tags are configured by group on luckperms by priority, the only thing is that some groups are in parent with lower groups, I leave you a short summary video.
https://novasurvival.it/video.mp4

**Comment by NEZNAMY** [comment]
Again, check tab's debug command if primary group was detected correctly.

**Comment by GaetanoXD** [comment]
Seems ok for all groups! But nothing change.
Screenshot: https://i.imgur.com/8QG8lol.png

**Comment by Tanguygab** [comment]
nametags are disabled = sorting disabled

**Comment by Tanguygab** [comment]
you should always check the wiki https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist

**Comment by NEZNAMY** [comment]
And top of the debug screaming "sorting is disabled".
