### ISSUE TITLE
Placeholder %rank% is not working

### ISSUE THREAD

**Issue by StasyQ123** [NEZNAMY/TAB#434]
**Server version**
1.18

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
In 2.9.3 the %rank% placeholder worked correctly and it was possible to add rank-aliases in config file, but now it does not work
![S1](https://user-images.githubusercontent.com/95924265/145590068-ca3dcb07-c16a-4482-be5e-85b102e1d18a.PNG)
![S2](https://user-images.githubusercontent.com/95924265/145590076-66be813c-5ecb-4b16-82dd-cea24b3c2494.PNG)

**Comment by NEZNAMY** [comment]
The placeholder was removed. See update notes. Use %group% with placeholder output replacements, configure prefixes for groups directly or use placeholder from your permission plugin.
