### ISSUE TITLE
Placeholder %rank% is not working

### ISSUE THREAD

**Issue by StasyQ123** [NEZNAMY/TAB#435]
**Server version**
1.18

**Plugin version** ("latest" is not a version)
3.0.0

**Describe the bug**
In version 2.9.3 the %rank% placeholder worked correctly and it was possible to add rank aliases. Now it does not work

**Additional info** (errors, screenshots, ...)
![S1](https://user-images.githubusercontent.com/95924265/145590496-29be1dc1-7bdf-4fc1-8f08-0a10b887f795.PNG)
![S2](https://user-images.githubusercontent.com/95924265/145590501-41b09a54-24ff-4f6d-91b9-7c7c746b0e72.PNG)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/434 ?

**Comment by krassekatze** [comment]
If you're using Luckperms you can use %luckperms_prefix% instead
