### ISSUE TITLE
TabPlayerLoadEvent missing in API

### ISSUE THREAD

**Issue by Pelfox** [NEZNAMY/TAB#436]
This is my `build.gradle`:
```gradle
plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.0'
}

compileJava {
    options.encoding = 'UTF-8'
}

group = 'ru.libremc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
    maven { url 'https://repo.kryptonmc.org/releases' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly 'me.neznamy:tab-api:3.0.0'
    compileOnly 'net.md-5:bungeecord-api:1.18-R0.1-SNAPSHOT'
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release = targetJavaVersion
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    expand props
    filteringCharset 'UTF-8'
    filesMatching('bungee.yml') {
        expand props
    }
}
```

I tried to set player's prefix and suffix, but I can't because of `java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TabPlayer.getProperty(String)" because "player" is null`. I read, that TAB has `TabPlayerLoadEvent`, so I can get player. 

This is my code:
```java
@EventHandler(priority = EventPriority.LOWEST)
    public void onPlayerJoin(ServerConnectedEvent event) {
        TabPlayer player = TabAPI.getInstance().getPlayer(event.getPlayer().getUniqueId()); // NullPointerException throws here
        TablistFormatManager manager = TabAPI.getInstance().getTablistFormatManager();
        ... 
```

**Comment by BomBardyGamer** [comment]
Add `compileOnly 'me.neznamy:tab-bungeecord:3.0.0'` for now. In the future, that event will be removed, and replaced with an event in the API itself, that isn't dependent on platforms.

**Comment by Pelfox** [comment]
Now it throws error
```gradle
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find me.neznamy:tab-bungeecord:3.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/me/neznamy/tab-bungeecord/3.0.0/tab-bungeecord-3.0.0.pom
       - https://oss.sonatype.org/content/groups/public/me/neznamy/tab-bungeecord/3.0.0/tab-bungeecord-3.0.0.pom
       - https://repo.kryptonmc.org/releases/me/neznamy/tab-bungeecord/3.0.0/tab-bungeecord-3.0.0.pom
       - https://jitpack.io/me/neznamy/tab-bungeecord/3.0.0/tab-bungeecord-3.0.0.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by BomBardyGamer** [comment]
Sorry, try version `3.0.1-pre1`.

**Comment by Pelfox** [comment]
Okay, now it throws another error:
```log
java.lang.LinkageError: loader constraint violation: loader net.md_5.bungee.api.plugin.PluginClassloader @1af05b03 wants to load interface me.neznamy.tab.api.TabPlayer. A different interface with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @b09fac1. (me.neznamy.tab.api.TabPlayer is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @b09fac1, parent loader 'app')
```
I also changed my code to this:
```java
@EventHandler(priority = EventPriority.LOWEST)
public void onPlayerJoin(TabPlayerLoadEvent event) {
        TabPlayer player = TabAPI.getInstance().getPlayer(UUID.fromString(event.getPlayer().getUniqueId()));
        TablistFormatManager manager = TabAPI.getInstance().getTablistFormatManager();
        ...
```

**Comment by NEZNAMY** [comment]
Sounds like you are shading TAB's classes into your project. Also you can just call `event#getPlayer()` to get the player.

**Comment by Pelfox** [comment]
Ok, seems to be fixed right now. Thank you!

**Comment by MrEAlderson** [comment]
Your docs are incorrect.
TabPlayerLoadEvent is not a part of the API.

**Comment by BomBardyGamer** [comment]
Maybe you should have another read of the documentation. I have no idea what version of the documentation you are reading, but we replaced that event with a new `PlayerLoadEvent` ages ago, and it has been deprecated for a while. [The updated events page shows the new system](https://github.com/NEZNAMY/TAB/wiki/Developer-API#events), and I am unsure if those old deprecated events have been removed yet or not, but either way, they should not be used.

If you have other issues finding these events, or other issues using the API, please open another issue.

**Comment by MrEAlderson** [comment]
> Maybe you should have another read of the documentation. I have no idea what version of the documentation you are reading, but we replaced that event with a new `PlayerLoadEvent` ages ago, and it has been deprecated for a while. [The updated events page shows the new system](https://github.com/NEZNAMY/TAB/wiki/Developer-API#events), and I am unsure if those old deprecated events have been removed yet or not, but either way, they should not be used.
> 
> If you have other issues finding these events, or other issues using the API, please open another issue.

https://github.com/NEZNAMY/TAB/issues/630
