### ISSUE TITLE
PlaceholderAPI placeholders aren't parsed when running on a Bungee instance

### ISSUE THREAD

**Issue by Apocalypsing** [NEZNAMY/TAB#44]
**Server version**
Waterfall (build 295) and BungeeCord (build 1420)

**Plugin version** ("latest" is not a version)
2.5.2, running alongside PAPI version 2.10.3
Also tested on 2.5.3-pre13

**Describe the bug**
When running on a Spigot or Paper server, PAPI placeholders work perfectly fine, but when running on a Bungee or Waterfall (Paper's fork of Bungee) server, they aren't parsed at all, instead the errors.txt file is flooded with stack traces related to analysing packets (on non-prerelease versions). This happens when a player joins the server.

Initially I had moved the plugin and config files from my survival server to my Waterfall server since the plugin was originally running on survival and I figured it'd be better letting Waterfall handle the tablist globally. My original config was somewhat out of date so I deleted it to start fresh with a new file, but the issue still persists.

Checking on Discord I saw an issue related to Bungee that was fixed in a recent prerelease. I tested 2.5.3-pre13 and although I no longer see a flood of stacktraces in the logs now, placeholders still aren't being parsed properly it seems.

**How to reproduce**
Install TAB onto a BungeeCord or Waterfall server, insert any PAPI placeholder in the config, connect to the server and observe.

**Expected behavior**
Placeholders should be parsed, just like they would if TAB was running on a standalone server

**Actual behavior**
PAPI placeholders aren't being parsed

**Additional info** (errors, screenshots, ...)
Example config.yml: https://gist.github.com/Apocalypsing/cb7de8b4bfd37be9a7f82f00bcedaccd

**Comment by Apocalypsing** [comment]
Only just realised the lack of PAPI for Bungee isn't a bug, at least according to a page on the wiki I overlooked. Guess I'll close this

**Comment by NEZNAMY** [comment]
Can you upload the errors file on discord ?
