### ISSUE TITLE
Sorting System Issue

### ISSUE THREAD

**Issue by TheNylox** [NEZNAMY/TAB#441]
**Server version**
 - gitPaper 398 1.17.1

**Plugin version** 
- 3.0.1 premium

**Describe the bug** 
Sorting system is not working. I tried both with GROUPS and PLACEHOLDER_A_TO_Z but players are sorted randomly and every player got a different sorting in his screen. I tried both following the: 

- generated-config syntax like this https://pastebin.com/gvdfm9T6 
- wiki syntax like this https://pastebin.com/tWGxZv57. 

All my luckperm weight are setted correctly and i use /tab debug it detect the correct parent with the correct #number of sorting list:

- https://imgur.com/a/RssQSAg

My eglow plugin is updated to the last version (3.1.3)

**Expected behavior**
Correctly sorting by group

**Comment by TheNylox** [comment]
Update: After unload eGlow the sorting system work

**Comment by NEZNAMY** [comment]
You probably have an outdated version of eGlow.

**Comment by TheNylox** [comment]
Read what i wrote, i'm last version

**Comment by NEZNAMY** [comment]
Then the issue is clearly in eGlow, as you said already and I can't do anything about it.

**Comment by TheNylox** [comment]
Ok, i'm opening an issue on his github

**Comment by TheNylox** [comment]
Its not necessary, mr.gray allready fixed it https://discord.com/channels/526810580950974484/698758165382299659/919520215824470036

**Comment by analogged** [comment]
I have this problem but havent been using eglow at all? Will getting eglow fix this and why do i need another plugin to fix sorting in TAB? Thanks

**Comment by NEZNAMY** [comment]
You don't need another plugin. This issue is about compatibility issue with another plugin. You probably just didn't configure sorting correctly.
