### ISSUE TITLE
[Bug] RGB Colors not working in player's nametags

### ISSUE THREAD

**Issue by NoboKik** [NEZNAMY/TAB#443]
**Server version**
Waterfall 1.18.1

**Plugin version** ("latest" is not a version)
BTAB v2.9.2

**Describe the bug**
RGB Colors are not working in nametag names. They are working in prefixes, suffixes but not in player's name. It becomes a legacy color for me

**Screenshots**
![image](https://user-images.githubusercontent.com/74139933/145971093-78ae7bdb-ba0b-4bb9-bc54-293f1fe81297.png)
![image](https://user-images.githubusercontent.com/74139933/145971121-539c96b5-e02a-4927-9b0e-6e8611d08085.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags ?

**Comment by NoboKik** [comment]
i have seen servers like OriginRealms fixing this bug without adding a fake hologram (they have vanilla below name)

**Comment by NEZNAMY** [comment]
Ask them how and then you can PR it into TAB.

**Comment by NEZNAMY** [comment]
Not a bug, but minecraft limitation.
