### ISSUE TITLE
Add the option "disabled-servers" for ping spoof

### ISSUE THREAD

**Issue by SlenkyDev** [NEZNAMY/TAB#444]

**Comment by NEZNAMY** [comment]
But.. why?

**Comment by SlenkyDev** [comment]
> But.. why?

I like to have all of my servers ping spoofed, but I have a server that's on 1.18 where I have one of those 1.7 style tablists and have the empty slots ping's set as -1 and hide the ping red X icon from the pack so the slots appear more vanilla and stuff I guess..

I currently need to have it off so that it doesn't interfere and adding this what seems like a simple config option would be really appreciated.

**Comment by NEZNAMY** [comment]
Empty slots ping? What's that and how is it related to players?

**Comment by SlenkyDev** [comment]
> Empty slots ping? What's that and how is it related to players?

It's tough to explain, if you really want, you can check it out on our oneblock server at mc.lendmark.sk
(or just look up the plugin "AdvancedTabOverlay")

**Comment by NEZNAMY** [comment]
This feature is actually not supposed to affect those. I will fix that.

**Comment by SlenkyDev** [comment]
> This feature is actually not supposed to affect those. I will fix that.

I don't think that it's broken.
Because it works in a way that it sets the empty slots to -1 (so it's the red X thingy), but the ping spoof (as intended) sets it to 1 (or any other ping), so the pings appear (because 1 is not hidded by the pack, unlike the red X)

**Comment by SlenkyDev** [comment]
> > This feature is actually not supposed to affect those. I will fix that.
> 
> I don't think that it's broken. Because it works in a way that it sets the empty slots to -1 (so it's the red X thingy), but the ping spoof (as intended) sets it to 1 (or any other ping), so the pings appear (because 1 is not hidden by the pack, unlike the red X)
![2021-12-14_18 45 43](https://user-images.githubusercontent.com/71548884/146052054-8e5d0e38-9208-4d7e-b7f1-6fae386a6be1.png)

**Comment by NEZNAMY** [comment]
Still, ping from fake slots should be handled by the plugin adding them.

**Comment by SlenkyDev** [comment]
> Still, ping from fake slots should be handled by the plugin adding them.

I have my thing on bungee

**Comment by SlenkyDev** [comment]
And have everything I can set as disabled for that server because the backend server has that plugin

**Comment by NEZNAMY** [comment]
Ping spoof feature should not touch fake player slots. I will fix that. Configure their ping in the plugin adding fake players.

**Comment by SlenkyDev** [comment]
> Ping spoof feature should not touch fake player slots. I will fix that. Configure their ping in the plugin adding fake players.

Okay

**Comment by SlenkyDev** [comment]
> Done, is this enough @SlenkyDev or anything else?

I'll wait for the next release to try it and I'll get back to you after I've done so

**Comment by NEZNAMY** [comment]
You can also compile it yourself or get someone to compile it for you and you don't need to wait.
