### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by 0Neil** [NEZNAMY/TAB#446]
**Server version**
1.18.1

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
Players see excess Scoreboard and players with OP don't see him

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/69084241/146436438-bc33d8cc-8bae-4450-a8c2-a4e2664182de.png)

**Comment by NEZNAMY** [comment]
If a feature is enabled it is enabled, that's all.
