### ISSUE TITLE
Yellow Number Tab Inconsistencies

### ISSUE THREAD

**Issue by RedZephon** [NEZNAMY/TAB#447]
I have my yellow number in tab set to:

yellow-number-in-tablist:
  enabled: true
  value: '%ecoskills_combat%'

For the purposes of this post/example the actual values for the users in this post are:
RedZephon 50
Auralain 13

The problem is that when viewing TAB, the number is always 0 for "me"

So if I view from the account "RedZephon" the number shows 0. But for other players it shows 50. This seems to just be a visual issue. 

Auralain's POV
![image](https://user-images.githubusercontent.com/16528824/146862405-014806ac-fd46-4c83-9569-5ba3682d9cd9.png)

RedZephons POV
![image](https://user-images.githubusercontent.com/16528824/146862429-c8d023a1-4254-40ce-8773-450a2b1ba914.png)

**Comment by NEZNAMY** [comment]
Reopening to avoid more duplicates before it's released.
