### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Wgis** [NEZNAMY/TAB#448]
Hello, can you add feature for supporting translation?
Customize help and commands from file will be helpfull!
I ask, because you make regular updates and it's so cool, but every time it's need retranslation...

**Comment by Tanguygab** [comment]
there's a messages.yml file?

**Comment by Wgis** [comment]
Yes, this is not full

**Comment by Tanguygab** [comment]
which messages are missing?

**Comment by Wgis** [comment]
![image](https://user-images.githubusercontent.com/20740613/146912183-13dba558-8b51-4791-a865-56537fe2a516.png)
all this in jar.

**Comment by Tanguygab** [comment]
why would you want this translated? it isn't shown to players, only staff members with the permission

**Comment by Tanguygab** [comment]
this was editable in the past, but since it was useless, it got removed from the translation file

**Comment by Wgis** [comment]
it's being good for adding some perminitions for this

**Comment by Wgis** [comment]
i think if dev don't need this, he don't touch it

**Comment by NEZNAMY** [comment]
What if a command is added? In fact, the list there is actually outdated. Adding a new one will not be reflected in the change, because configuration will not automatically update with new lines in the list.

**Comment by Wgis** [comment]
Simply fill lines by commads. If help.yml not exist - get from plugin. if exists - get from file.
In file we can write all or part of all commands. Or fill by perminisions...

**Comment by NEZNAMY** [comment]
If it does not exist, it will be added and then exist, which will break the check for the future.

**Comment by Wgis** [comment]
adding variable looks like Version: 001 
solve this problem bruh

**Comment by NEZNAMY** [comment]
Instead of solving a problem that sounds more like creating problems.
