### ISSUE TITLE
Pet Names

### ISSUE THREAD

**Issue by RobisjustacoolerRobin** [NEZNAMY/TAB#449]
**Server version**
Spigot 1.18.1

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
My pets (cats/dogs) names are invisible. Only mine. If it's another players and I name it, it's still visible. This is only when unlimited name tag mode is on. 

**How to reproduce**
Install this stupid plugin:
https://www.curseforge.com/minecraft/bukkit-plugins/healthbarmc

**Expected behavior**
My pets names to show up.

**Actual behavior**
It doesn't show up.

**Additional info** (errors, screenshots, ...)

**Comment by RobisjustacoolerRobin** [comment]
I know this is majorly my fault but I really want to fix it.

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix

**Comment by RobisjustacoolerRobin** [comment]
@Tanguygab I don't think this is my issue? They're not copying my name properties. Their names are just not shown entirely.

**Comment by RobisjustacoolerRobin** [comment]
I tested with that fix and it works so I guess that's fine.

**Comment by Tanguygab** [comment]
> @Tanguygab I don't think this is my issue? They're not copying my name properties. Their names are just not shown entirely.

if you have unlimited nametag mode enabled, then it still cause the issue

**Comment by RobisjustacoolerRobin** [comment]
Why only me and not other players though? 


> > @Tanguygab I don't think this is my issue? They're not copying my name properties. Their names are just not shown entirely.
> 
> if you have unlimited nametag mode enabled, then it cause the issue, thus the pet fix feature is needed

**Comment by Tanguygab** [comment]
no idea 🤷

**Comment by RobisjustacoolerRobin** [comment]
So that shitty plugin fucked me and not them. Kekw. 
Well, as long as it's working, am happy. Thanks.
