### ISSUE TITLE
Incompatible with Hskywars plugin

### ISSUE THREAD

**Issue by XDRmc** [NEZNAMY/TAB#451]
1.8.8

3.0.0 and above

makes /leave not work

setup a arena on hskywars and use it to get this error: 
[thiserror.txt](https://github.com/NEZNAMY/TAB/files/7760289/thiserror.txt)

**Expected behavior**
/leave to send you to lobby

**Actual behavior**
does nothing and gets you trapped

**Additional info** (errors, screenshots, ...)
[thiserror.txt](https://github.com/NEZNAMY/TAB/files/7760292/thiserror.txt)

**Comment by Tanguygab** [comment]
that plugin os using an outdated version of the API, contact the dev and ask him to update the plugin to support TAB 3.0

**Comment by NEZNAMY** [comment]
The API changed and author of the plugin must update the hook.
