### ISSUE TITLE
Unlimited-nametag-mode fails to reload

### ISSUE THREAD

**Issue by bumpyJake** [NEZNAMY/TAB#453]
**Server version**
1.18.1

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
Enabling unlimited-nametag-mode gives this error in errors.log - https://paste.dedimc.io/ehanujasin.cs

**How to reproduce**
Enable unlimited-nametag-mode with this config.yml https://paste.dedimc.io/upejonuvis.cs and this groups.yml https://paste.dedimc.io/kuyugamuco.makefile
(These were the only things that had been changed

**Expected behavior**
Unlimited nametag mode would have been turned on, and allowed essentials nicknames to show above playerheads

**Actual behavior**
I get the error message "Failed to enable due to an internal plugin error", and an error generates in the console/logs

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Works completely fine for me with your configuration.
