### ISSUE TITLE
[Suggestion] Per-server bossbar and scoreboard

### ISSUE THREAD

**Issue by Yurinann** [NEZNAMY/TAB#457]
TAB version: 3.0.2-pre1 (on bungee mode)

This is an enhanced suggestion for the plugin to handle subservers' settings in a more friendly way on Bungee.
(It looks like Tablist currently has this feature.)

**Comment by Tanguygab** [comment]
this was a thig in previous versions but it was removed because it made the configuration more messy. Also, we don't accept feature requests anymore.

**Comment by NEZNAMY** [comment]
Already doable with conditions, which is why it was removed.

**Comment by Yurinann** [comment]
> Already doable with conditions, which is why it was removed.

In fact, when I installed TAB only on the BungeeCord environment, I did not find a way to enable different servers to use different scoreboard settings.

**Comment by NEZNAMY** [comment]
Just use `display-condition: "%server%=name"` and you'll achieve the same effect.
