### ISSUE TITLE
Bungeecord Placeholder %online_<server_name>% Not Working

### ISSUE THREAD

**Issue by runningute72** [NEZNAMY/TAB#458]
**Server version**
Paper 1.16.5

**Plugin version** ("latest" is not a version)

3.0.1

**Describe the bug**
I have the placeholder %online_dupes% on my scoreboard, but it isn't working. I'm not sure if I'm missing something. It just displays it as "%online_dupes%" rather than the number. I've tried to use the Tab Bridge, but that doesn't work either. Thanks!

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
You do not have a server with that name on the bungeecord.

**Comment by runningute72** [comment]
I have the server named "dupes" on my proxy server. 

server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: hub
  host: 0.0.0.0:25565
  max_players: 500
  motd: CoolMCGames
  ping_passthrough: false
  priorities:
  - hub
  proxy_protocol: false
  query_enabled: false
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  FroostySnoowman:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: ef5c8c73-a5a3-4501-85ec-e87f05df4b8b
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  duels:
    address: 144.172.80.38:25566
    motd: CoolMCDuels
    restricted: false
  dupes:
    address: 51.222.10.2:25660
    motd: CoolMCDupes
    restricted: false
  hub:
    address: 144.172.80.38:25567
    motd: CoolMCHub
    restricted: false

**Comment by runningute72** [comment]
I fixed it via doing %bungee_online_dupes%.
