### ISSUE TITLE
Nametag doesn't add colour (if player hasn't moved when they received the rank)

### ISSUE THREAD

**Issue by Forbidden-Duck** [NEZNAMY/TAB#46]
**Server version**
PaperSpigot 1.8.8

**Plugin version** ("latest" is not a version)
2.5.2

**Describe the bug**
Nametag (abovename by the looks of it, I don't use belowname) will not add colour and will only show the colour tags (I.E. &4) in white text.

**How to reproduce**
1.  Make sure you have a group which has colour in it's abovename:
2.  Put the user in the group which has the abovename:
3.  Reload the plugin
4.  Remove them from the group
5.  Add them back to the group

**Expected behavior**
[Imgur](https://i.imgur.com/27kZKF1.png)

**Actual behavior**
[Imgur](https://i.imgur.com/Hh8ByE0.png)

**Additional info** (errors, screenshots, ...)
Screenshots taken on Optifine Client 1.8.9

**Comment by NEZNAMY** [comment]
Fixed in 2.5.3
