### ISSUE TITLE
Underscore...

### ISSUE THREAD

**Issue by strich3** [NEZNAMY/TAB#461]
**Server version**

1.8.9 

**Plugin version** ("latest" is not a version)

3.0.1

**Describe the bug**

When someone has an "_" in the name then the group doesn't assign

**Comment by NEZNAMY** [comment]
My IGN is `_NEZNAMY_` and it works fine.

**Comment by strich3** [comment]
I use CloudNet permissions. Is that the problem?

**Comment by NEZNAMY** [comment]
If this was a TAB issue, we would get more than just a single complaint.

**Comment by NEZNAMY** [comment]
Probably caused by your permission system. TAB does not perform any name checks, especially for `_` symbol.
