### ISSUE TITLE
BossBar sending and announcing doesn't work

### ISSUE THREAD

**Issue by TheJoshue** [NEZNAMY/TAB#462]
**Server version**
![image](https://user-images.githubusercontent.com/56804505/147423018-e9af8958-d398-4651-899f-5843b86f7ab8.png)

**Plugin version** ("latest" is not a version)
![image](https://user-images.githubusercontent.com/56804505/147423024-df0f8591-0720-4466-b326-0ce5f6dfdead.png)

**Describe the bug**
`/tab send bar <player> <bossbar-name> <seconds>`, or
`/tab announce bar <bossbar-name> <seconds>`,
you get:
- No errors in console/logged in file (at all),
- No message is returned neither to player who executed the command,
- No bossbar will appear to a target player (basically nothing happens).

However, when you do `/tab announce bar` or `tab send bar`, you get the "usage" message, that's it.

**How to reproduce**
Execute either:
`/tab send bar <player> <bossbar-name> <seconds>`, or
`/tab announce bar <bossbar-name> <seconds>`.

**Expected behavior**
Should send bossbar defined in `config.yml` (mentioned in the command arguments) to all/specific player.

**Actual behavior**
Not sending bossbar defined in the `config.yml` (mentioned in the command arguments) to all/specific player.

**Additional info** (errors, screenshots, ...)
///

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by TheJoshue** [comment]
> Send your config.

it's default, i can send if you want but i didn't modify anything.

I tried it on my server (i edited that config)

Then i dropped .jar in test server, started server, joined, tried both from player and console to do commands i stated in the post above, so config is basically default and this issue still persists (i had only basic plugins like viaversion, protocollib, vault, papi and some other (essentials)), only very basic plugins

**Comment by yannicklamprecht** [comment]
That's "fun" when supporting 1.8.8. 😂😂

**Comment by TheJoshue** [comment]
> That's "fun" when supporting 1.8.8. 😂😂

Idk but `/bossbar` (or any dedicated command that you set for toggling BossBar in `config.yml`) works flawlessly everytime
Also the `/tab bossbar` works flawlessly.

**Comment by yannicklamprecht** [comment]
> > That's "fun" when supporting 1.8.8. 😂😂
> 
> Idk but `/bossbar` (or any dedicated command that you set for toggling BossBar in `config.yml`) works flawlessly everytime Also the `/tab bossbar` works flawlessly.

I personally would say: "Try to reproduce on 1.18.1" but as it isn't my project, it's not my business.

**Comment by NEZNAMY** [comment]
I used default config and added `announcement-bar` attribute to the bossbar to make it not appear permanently:

```bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"
      announcement-bar: true```

Announce command shows the bossbar correctly and hides it after specified amount of time.

**Comment by NEZNAMY** [comment]
@TheJoshue if you still believe you configured everything correctly, try latest build from https://github.com/NEZNAMY/TAB/actions, I added more command feedback showing what's wrong.

**Comment by TheJoshue** [comment]
> @TheJoshue if you still believe you configured everything correctly, try latest build from https://github.com/NEZNAMY/TAB/actions, I added more command feedback showing what's wrong.

![image](https://user-images.githubusercontent.com/56804505/149540960-54fec4ae-aa25-4983-8095-3ad8ad900719.png)
ok so i found it out now
