### ISSUE TITLE
yellow-number-in-tablist Heart does not display properly

### ISSUE THREAD

**Issue by SeaSon2002** [NEZNAMY/TAB#463]
**Server version**
1.17.1 purpur lastest build

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
using %health% for yellow number in tab list doesnt shows the hearts for the newest player joining the server

**How to reproduce**
run TAB with a clean setup: no other plugins, default config generated by TAB itself(with yellow-number-in-tablist change to %health%), java 17, let 1 account joining the server, then 2nd account, observe the tablist during the process

**Expected behavior**
Hearts should shows up

**Actual behavior**
Heart doesnt show for the newest joining player, the newest player must heal or get damaged to get the heart row showing up

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/61407079/147573205-7f516a75-888e-437e-92d7-86971fa69230.png)

**Comment by NEZNAMY** [comment]
Duplicate of #447 and #459 ?

**Comment by SeaSon2002** [comment]
oh sorry i didnt paying attention to the closed issues
