### ISSUE TITLE
Trigger Placeholderrefresh

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#464]
**Server version**
1.18.1

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the feature**
Many Plugins provide Placeholder which have its own refreshinterval. It will be nice if this will be used as an option to let the plugin refreshes the placeholder. Like if in example a "1" becomes to a "2", Tab should refresh it.

For rainbow tag in tab its good too, to recognize if rainbow feature is enabled.

This will be good to avoid useless and inperformant intervals.

**Comment by NEZNAMY** [comment]
How is plugin supposed to know when a placeholder changes? Which event should it listen to?

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Optimizing-the-plugin#2---placeholder-refresh-intervals

**Comment by Tanguygab** [comment]
oops, miss clcik

**Comment by supermem99** [comment]
Maybe if an objective/scoreboard will update.

**Comment by NEZNAMY** [comment]
And how to detect that and actually integrate into the plugin?

**Comment by supermem99** [comment]
I'm not a developer, but I can imagine that placeholders have their own delay of refreshing. And if they refresh, the scoreboard can refresh too.

btw. if this idea isn't possible and not codeable then its okay

**Comment by NEZNAMY** [comment]
I am doing this for some placeholders where it's possible, but for majority of internal and all placeholderapi it's just not possible as it lacks the way.

**Comment by supermem99** [comment]
My developer created some methods for his plugin for this kind of triggering. If you integrate this possibility to your api, it will be very useful and nice.

**Comment by NEZNAMY** [comment]
Already possible.

**Comment by supermem99** [comment]
Ah i see, if you add placeholderapi support this triggering can be finished by it.

**Comment by NEZNAMY** [comment]
PlaceholderAPI support was added 4 years ago. It doesn't support trigger placeholders, so I have no idea what are you talking about.

**Comment by supermem99** [comment]
I have some placeholders which only be visible,  if  you execute a command.
Like /vanish for "[V]"
Or /blink for rgb colors rainbow name
Or clan tag enable

**Comment by NEZNAMY** [comment]
Yes, but PlaceholderAPI support consists of calling one method, which doesn't offer this.

**Comment by supermem99** [comment]
Last question: you are not able to add, that commands are activating placeholders like them above?

**Comment by NEZNAMY** [comment]
I will not do that.

**Comment by supermem99** [comment]
Ok all right sir
