### ISSUE TITLE
Per-World Sorting.

### ISSUE THREAD

**Issue by SreyasIN** [NEZNAMY/TAB#469]
Please add per-world sorting so that we can sort the players according to their team letter/name in Bedwars1058 and other plugins

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#bedwars1058-compatibility

**Comment by SreyasIN** [comment]
I want it to sort the players according to rank in lobby and according to team in game.

**Comment by NEZNAMY** [comment]
Team will return same value in lobby, making it not affect anything and secondary sorting type (rank) will take effect instead. Sounds good to me.

**Comment by SreyasIN** [comment]
ok thanks
