### ISSUE TITLE
SuperVanish placeholder

### ISSUE THREAD

**Issue by lolw0tm8** [NEZNAMY/TAB#47]
I want placeholder to show nothing if user is not vanished and &7[V] if user IS vanished.
I tried %supervanish_isvanished% but that just shows "No" all the time.

**Comment by NEZNAMY** [comment]
Placeholderapi has config.yml where you can configure default output of boolean results. You can change the default "Yes" and "No" to values which you want to be used for vanishing. This will obviously only work correctly for one placeholder, but you don't seem to be using one yet.

**Comment by Rodrigo178** [comment]
PlaceholderAPI allows you to create custom placeholders using JavaScript.
Here is an example of how to create a custom placeholder for a vanish plugin:
1.	Make sure you have PlaceholderAPI
2.	Download JavaScript expansion /papi ecloud download JavaScript
3.	Reload PlaceholderAPI /papi reload
4.	Go to PlaceholderAPI folder, and open the file javascript_placeholders.yml
5.	Add your JavaScript name:
 
![image](https://user-images.githubusercontent.com/20385703/65835896-b0836280-e2b1-11e9-8820-7cfd243e67cc.png)

6.	Save the file
7.	Go to the folder PlaceholderAPI > javascripts
8.	Create a new file for your javascript, remember it must be the same as you set it in file javascript_placeholders
![image](https://user-images.githubusercontent.com/20385703/65835894-ac574500-e2b1-11e9-9c61-5aba6feacdc0.png)

9.	Open your javascript using Notepad++
10.	Here is an example of the new placeholder using PremiumVanish
 
![image](https://user-images.githubusercontent.com/20385703/65835883-934e9400-e2b1-11e9-9d23-13c381ac4a4c.png)

 If you want to do it with another vanish plugin, change %premiumvanish_isvanished% with your plugins placeholder that has an output true or false. You can know the output of a placeholder using /papi bcparse me %your_vanish_plugin_placeholder%. 
For changing the output of our placeholder, we have to edit the answer. The first answer is what the placeholder will say if you are not vanished, the second is the output when you’re vanished.
11.	Once you created your javascript, save the file and reload PlaceholderAPI
12.	You’ve created your custom placeholder! To use it, you need to use the placeholder %javascript_your_javascript_name%. If you used the same name as in this config, the placeholder would be %javascript_vanishtag%
