### ISSUE TITLE
Sorting system isn't working

### ISSUE THREAD

**Issue by acrylic-style** [NEZNAMY/TAB#473]
**Server version**
Velocity 3.1.1 / Paper 1.12.2 (build 1620)

**Plugin version** ("latest" is not a version)
884b5755ece5ca7ed16aa9dbdaa38bc7e1c16c38

**Describe the bug**
The sorting system isn't working and it seems always sorted by player name A->Z.

**How to reproduce**
1. Let TAB generate the default configuration
2. Edit `plugins/TAB/config.yml` and change `scoreboard-teams.sorting-types` to:
  ```yml
  sorting-types:
  - PLACEHOLDER_Z_TO_A:%player%
  ```
3. Type `/vtab reload`

**Expected behavior**
`zzzyyyxxxwwwvvvv` is at the top, and `aaabbbcccdddeeee` is at the bottom

**Actual behavior**
`zzzyyyxxxwwwvvvv` is at the bottom, and `aaabbbcccdddeeee` is at the top

**Additional info** (errors, screenshots, ...)

Installed plugins on velocity:
- LuckPerms (5.3.75)
- TAB

Paper:
- `This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`
- No plugins installed

Result of `/vtab debug zzzyyyxxxwwwvvvv`:
![2022-01-04_15 23 38](https://user-images.githubusercontent.com/19150229/148018016-0b0d1be6-00b5-4010-bf6f-e7a92600a2fa.png)

Result of `/vtab debug aaabbbcccdddeeee`:
![image](https://user-images.githubusercontent.com/19150229/148018964-1de82ad7-55c8-4e81-9614-1aa49dbacede.png)

**Comment by NEZNAMY** [comment]
Velocity does not support sorting.

**Comment by acrylic-style** [comment]
Oh... okay.
