### ISSUE TITLE
Refresh bug

### ISSUE THREAD

**Issue by Pierrot-la-menace** [NEZNAMY/TAB#479]
**Server version**
Velocity 3.1.2 -  Paper 1.18.1 build 147

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
The bar display doesn't refresh when the player just logged in the server. The ping stays at -1 in the beginning of the connection during 2-3 seconds (it's normal) and when it is rightly computed, the bars stay crossed. 

**How to reproduce**
Restart your infra, connect 2 players and display the tab list

**Expected behavior**
the bar must be green

**Actual behavior**
the bar are red crossed

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/45047908/149422118-393d43f1-c53c-4add-8a1b-0bddd72b1e47.png)

**Comment by NEZNAMY** [comment]
Ping is calculated by velocity and TAB is just retrieving that value and displaying it. Ping bar is completely out of control of TAB.

**Comment by Pierrot-la-menace** [comment]
Ok thank you, I will open an issue on Velocity !
