### ISSUE TITLE
vanilla belowname does not work if unlimited-nametag-mode is enabled

### ISSUE THREAD

**Issue by CryLegende** [NEZNAMY/TAB#48]
**Server version**
1.12

**Plugin version** ("latest" is not a version)
2.5.3

**Describe the bug**
The vanilla belowname does not work if unlimited-nametag-mode is enabled in the config ^^

**How to reproduce**
Enable unlimited-nametag-prefix-suffix-mode

**Expected behavior**
the vanilla belowname is just disabled even when there is no custom belowname

Thanks for your help ^^

**Comment by NEZNAMY** [comment]
Not a bug. Unlimited mode hides your normal nametag and uses armor stands instead.
