### ISSUE TITLE
Color Gradients do not render correctly on users own Nametag

### ISSUE THREAD

**Issue by Nisutec** [NEZNAMY/TAB#480]
**Server version**
Paper 1.18.1 (152)

**Plugin version** ("latest" is not a version)
v3.0.1

**Describe the bug**
On the Client from the User with the color gradient in the Nametag it will not be render the color gradient correctly it will only display a placeholder for it. For reference i have used a color gradieant form #1C8E46 to #4AFD6C and have also tested fixed group definitions in the groups.yml and dynamic color gradiants with placeholders. I have also tried the following gradients options:

```
<#1C8E46>Username</#4AFD6C>
{#1C8E46>}Username{#4AFD6C<}
<$#1C8E46>Username<$#4AFD6C>
<gradient:#1C8E46:#4AFD6C>Username</gradient>
```

**How to reproduce**

- Run a Server with Paper 1.18.1 and PL Version v3.0.1
- Configure a Prefix and Suffix with a color gradient for a Nametag (all four versions have the same problem)
- Start a MC Client with the possibility to show your own Nametag (example Badlion, Lunar or Modded Client)
- Join the Server and look in F5 your Nametag

**Expected behavior**
You should see the same Nametag all other players also see and not a Placeholder (look at Additional info “normal nametag”)

**Actual behavior**
The User only get for example a <$>username<$> and not the color gradient (look at Additional info “gradient option 1-4”).

**Additional info** (errors, screenshots, ...)
Normal Nametag (correct Nametag form the view of a other User):
![Normal Nametag](https://p52.p0.n0.cdn.getcloudapp.com/items/wbuYPd9Q/410ba6a2-5a0a-48b2-bfb2-48b9011745b6.png?v=aead9bbbebe20538a6ae4c2cdc30cafc)
Nametag with gradients option 1 (own Nametag):
![gradients option 1](https://p52.p0.n0.cdn.getcloudapp.com/items/xQuzAmnR/ddc86f23-302c-40ec-825b-3e6b3bd8a6a9.png?v=f210d2549103566406645c7da54cbd38)
Nametag with gradients option 2 (own Nametag):
![gradients option 2](https://p52.p0.n0.cdn.getcloudapp.com/items/YEuByYXw/b3b8986a-62a0-4b41-8f0c-1ccd09a80454.png?v=1e823e2652a8a911d8294ce33f2eff75)
Nametag with gradients option 3 (own Nametag):
![gradients option 3](https://p52.p0.n0.cdn.getcloudapp.com/items/4guZJv1p/dde4b851-f000-4c9b-b509-8179d1668b68.png?v=f3f76655c22d3e03fd2dca4e4f9b034f)
Nametag with gradients option 4 (own Nametag):
![gradients option 4](https://p52.p0.n0.cdn.getcloudapp.com/items/jkumDBeb/cd9cb46b-d717-4a0f-a8e0-f87b4e7a22b9.png?v=86decfdcde4acaf18acce4fc865029f0)

**Comment by NEZNAMY** [comment]
We already told you on discord that name cannot be changed and if you want to see it, you'll need to enable unlimited nametag mode and use /tab ntpreview to see it.

**Comment by Nisutec** [comment]
> We already told you on discord that name cannot be changed and if you want to see it, you'll need to enable unlimited nametag mode and use /tab ntpreview to see it.

That means your Plugin has no possibility to change the Username of a user for itself only for other Users. Ok when this the limitation is I understand the problem than you can’t fix this problem.

**Comment by Tanguygab** [comment]
btw, even if the plugin modified the nametags (which would cause issues anyways), the name wouldn't support RGB colors, so no gradients either, another MC limitation

**Comment by Nisutec** [comment]
> btw, even if the plugin modified the nametags (which would cause issues anyways), the name wouldn't support RGB colors, so no gradients either, another MC limitation

Oh ok thank you for the additional information’s that is sad but when it is a current MC limitation I understand that this is not fixable.
