### ISSUE TITLE
playercount not changing when staff goes in vnaish 

### ISSUE THREAD

**Issue by knifemaster474** [NEZNAMY/TAB#481]
When my staff goes into vanish the player count isn't changing at all

**Comment by MrGraycat** [comment]
Hello

Seems you're using an online placeholder that doesn't check if the player is in vanish...
Check this page for a proper placeholder that does check for this
[https://github.com/NEZNAMY/TAB/wiki/Placeholders](https://github.com/NEZNAMY/TAB/wiki/Placeholders)

This is also mentioned in the FAQ so please read it
