### ISSUE TITLE
You can't use 64 characters when the scoreboard line contains a percent symbol "%"

### ISSUE THREAD

**Issue by TheGaming999** [NEZNAMY/TAB#483]
**Server version**  
Spigot 1.8.8  
  
**Plugin version ("latest" is not a version)**  
TAB.v3.0.2-pre5  
  
**Describe the bug**  
If a line has this symbol "%" it won't show the entire line.  
  
**How to reproduce**  
Add a scoreboard line consisting of 33 characters or more, and the %.  
  
**Expected behavior**  
Show the entire line regardless of what the line contains.  
  
**Actual behavior**  
Show only a part of the line.  

Additional info (errors, screenshots, ...)

https://user-images.githubusercontent.com/14120627/150808337-198aaae7-6ecf-4d8d-83c8-4ab97d54b5ad.mp4

**Comment by NEZNAMY** [comment]
Correct, minecraft limitation.

**Comment by TheGaming999** [comment]
Oh God... There is nothing to do I guess. Please don't remove this feature just because of this limitation.

**Comment by NEZNAMY** [comment]
Nothing is going to be removed, but added either.

**Comment by NEZNAMY** [comment]
Lines are limited to 32 characters. Limit being 64 when not using placeholders is not even an advertised feature. Placeholder format will stay as %% and will not be changed. Update your game and it will magically solve all of your problems.

**Comment by TheGaming999** [comment]
Never. I'm gonna edit the plugin. The question is will it work?

**Comment by TheGaming999** [comment]
Sure thing
