### ISSUE TITLE
Bossbar display-condition option doesn't work properly

### ISSUE THREAD

**Issue by TheJoshue** [NEZNAMY/TAB#484]
**Server version**
(Latest Paperfor 1.8.8)
![image](https://user-images.githubusercontent.com/56804505/151285767-82de9c04-895a-4190-9d82-99398b92d2af.png)

**Plugin version** ("latest" is not a version)
Latest current (3.0.1) github release
![image](https://user-images.githubusercontent.com/56804505/151285819-c1db968a-6494-41c0-8c66-2f15bd2729b0.png)

**Describe the bug**
Using any placeholder as `display-condition` for some defined bossbar doesn't **UPDATE**.

**How to reproduce**
Add any placeholder to `display-condition` option for some defined bossbar.

**Expected behavior**
Should update for example if you set `display-condition` to `%server_online%=2`, if 2 players are online it'll be shown, but when someone leaves the server it should update.

**Actual behavior**
Bossbar never gets updated (show/hide) on placeholder change

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
You could have been looking into ground which makes wither not visible. Update to at least 1.9.
