### ISSUE TITLE
customtagname works, however customtabname does not

### ISSUE THREAD

**Issue by ImKatz** [NEZNAMY/TAB#485]
**Server version**
1.18.1

**Plugin version** ("latest" is not a version)
3.0.1

**Describe the bug**
customtagname in groups.yml does not update tag.

**How to reproduce**
Be on 1.18.1, ensure placeholders plugin is installed, ensure essentials is installed. Attempt to enable customtagname: %essentials_nickname%

I can assure it does not work based off customtabname working perfectly fine. When customtabname is set to %essentials_nickname% it updates correctly, however same cannot be said about customtagname.

**Expected behavior**
Update the customtagname as essentials nickname on scoreboards.

**Actual behavior**
Does not update the customtagname as the essentials nickname on scoreboards.

**Additional info** (errors, screenshots, ...)
tagprefix DOES work, I am able to use %vault-prefix% to enable my prefix in the scoreboard, however when it comes to customtagname for %essentials_nickname% it does not work. %essentials_nickname% does work for customtabname indicating that the placeholder does indeed work.

Images:
![TABPluginBug](https://user-images.githubusercontent.com/30894069/151487665-2ab75d3e-b88a-4ffa-ba8a-177e441720a1.png)
![TABPluginBugInGame](https://user-images.githubusercontent.com/30894069/151487670-69229aca-060b-4173-9c6b-5df021b46cf2.png)

**Comment by ImKatz** [comment]
In the images you can see that the nametag over the head and the tag prefix are applied, however when it comes to displaying it on the scoreboard, it displays the prefix when tagprefix is enabled however does not enable the essentials nickname.

**Comment by Tanguygab** [comment]
customtagname requires unlimited-nametag-mode to he enabled

**Comment by ImKatz** [comment]
> customtagname requires unlimited-nametag-mode to be enabled

unlimited-nametag-mode is enabled! My apologies, I forgot to mention this.

**Comment by Tanguygab** [comment]
can you do /tab debug <player> and send a screenshot of the output in chat?

**Comment by ImKatz** [comment]
> can you do /tab debug and send a screenshot of the output in chat?

![image](https://user-images.githubusercontent.com/30894069/151528683-2c06421e-fe47-40ba-9ee9-174ccd9c5052.png)
Interestingly enough, it shows as disabled. Here's a screenshot of the plugins I am current using as well.

![image](https://user-images.githubusercontent.com/30894069/151528868-ff34e7be-fa83-4ca7-933a-b711988c2478.png)

**Comment by ImKatz** [comment]
> I can't see what went wrong, but customtagname works when enabled. You probably did something wrong, such as looking at yourself and not another player or the nick placeholder returning original name.

Seeing as how customtagname works then how would the nick placeholder be returning the original name? Also, the original screenshot is of another player. Their nametag above their head does change to the essentials nickname, however the scoreboard does not.

tabprefix works as well, but tagprefix seems to not be working either or at least I do not see it do anything.

**Comment by NEZNAMY** [comment]
Title says tag is not working and now it is? Tablist name is not working because you disabled the feature, as you can clearly see from debug output. I see nothing wrong with the plugin.

**Comment by ImKatz** [comment]
> Title says tag is not working and now it is? Tablist name is not working because you disabled the feature, as you can clearly see from debug output. I see nothing wrong with the plugin.

I am a complete idiot.
I meant CUSTOMTABNAME doesn't work. If you'd like I can resubmit the ticket. I am very sorry ugh.

**Comment by NEZNAMY** [comment]
As I said and so did debug, you disabled the feature so it obviously won't work.

**Comment by ImKatz** [comment]
> Title says tag is not working and now it is? Tablist name is not working because you disabled the feature, as you can clearly see from debug output. I see nothing wrong with the plugin.

You can see in my screenshots that I have enabled customtabname though.

**Comment by NEZNAMY** [comment]
Screenshot says disabled.

**Comment by ImKatz** [comment]
> Screenshot says disabled.

In the debug correct, however in the groups.yml, I have it enabled?

**Comment by NEZNAMY** [comment]
That's configuration of the feature, not enabling it.

**Comment by ImKatz** [comment]
> That's configuration of the feature, not enabling it https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting#enabling

Aha.... my goodness. Thank you so much, I am a bit new to running through these yml files. That was a silly oversight on my part. Thank you very much! Fantastic dev.

**Comment by ImKatz** [comment]
> That's configuration of the feature, not enabling it https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting#enabling

Maybe I am still being dumb but...

![2022-01-28_02 49 18](https://user-images.githubusercontent.com/30894069/151534340-a5daf919-45ad-498d-9892-789663f5b07c.png)
![bug](https://user-images.githubusercontent.com/30894069/151534352-580e6d3f-0a6f-40c6-bece-81d014e38bc3.png)
![bug2](https://user-images.githubusercontent.com/30894069/151534367-2237f582-3e7a-4b3d-b935-8e9e5036b2e0.png)
![image](https://user-images.githubusercontent.com/30894069/151534476-253f895b-5760-4175-808b-e6d378dc0775.png)

**Comment by NEZNAMY** [comment]
I see nothing wrong. Support is not provided in github issues.

**Comment by ImKatz** [comment]
> I see nothing wrong. Support is not provided in github issues.

Oh, I apologize, but it's not showing on the scoreboard? I am able to show prefixes on the scoreboard by enabled tagprefix, however customtabname nor customtagname update the scoreboard names from the original usernames.

**Comment by ImKatz** [comment]
> I see nothing wrong. Support is not provided in github issues.

Where can I get support if you do not mind me asking? I saw the issues tab and assumed that would be the correct spot.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB#links

**Comment by ImKatz** [comment]
> https://github.com/NEZNAMY/TAB#links

Aha I see. That's unfortunate. Thank you for taking the time out of your day in attempting to help me.
