### ISSUE TITLE
seeFriendlyInvisibles not working when TAB installed

### ISSUE THREAD

**Issue by UsainSrht** [NEZNAMY/TAB#489]
Server version
1.18.1 - purpur

TAB version
3.0.2

Description
When TAB installed you can't see yourself and other players in your team when they are invisible.

Reproduce
create a team /team add name
join the team /team join name yourname
give yourself invisibility

expected behaviour
See semi transparent body

With TAB installed
![image](https://user-images.githubusercontent.com/59025999/151999948-463eb9f4-765d-4631-8a59-f1df6c203d20.png)

Without TAB
![image](https://user-images.githubusercontent.com/59025999/151998783-25345b56-d597-4198-8d77-a8b698b1dbf1.png)

**Comment by NEZNAMY** [comment]
Disable team handling in TAB and you can use vanilla commands again to assign teams.

**Comment by UsainSrht** [comment]
> Disable team handling in TAB and you can use vanilla commands again to assign teams.

How do I do that?
Is this? `scoreboard-teams.enabled`

**Comment by NEZNAMY** [comment]
Yes, pretty self-explanatory.
