### ISSUE TITLE
space between prefix and the name in the nametag

### ISSUE THREAD

**Issue by CryLegende** [NEZNAMY/TAB#49]
Hello ^^
Can you add more space between prefix (above name) and the name in the nametag please ? Or just allow to change the default space
![2019-10-01_05 07 06](https://user-images.githubusercontent.com/25080946/65931416-d6bc1600-e409-11e9-8f56-8cfa0b9320b9.png)

Thanks for your help ^^

**Comment by NEZNAMY** [comment]
Config.yml

**Comment by NEZNAMY** [comment]
Option used to exist but no one was using it so i removed it. Why do you need to change it ?

**Comment by CryLegende** [comment]
I would like to use the function to make a "title" and I think it's weird that it's so close to the nickname ^^

**Comment by NEZNAMY** [comment]
You can edit source code for now, it's just one number.

**Comment by NEZNAMY** [comment]
Can you PM me on discord ? I have a jar for you to test.
