### ISSUE TITLE
Tab list and scoreboard not working on 3.0.2

### ISSUE THREAD

**Issue by UsainSrht** [NEZNAMY/TAB#491]
Server version
1.18.1-purpur

I just updated TAB from 3.0.1 to 3.0.2(in survival server) and tablist/scoreboard stopped working on join.

Lobby - TAB 3.0.1
![image](https://user-images.githubusercontent.com/59025999/152136457-3902567a-2bc2-435e-9652-2df744048082.png)

Survival - TAB 3.0.2
![image](https://user-images.githubusercontent.com/59025999/152136505-b1338679-1f14-4bc2-8efe-13f0225d9781.png)
(header and footer was lobby's)

When I do /tab reload it gives all players scoreboard and fixed tablist but new players stay same.

I've tried delay on join setting but it didn't work.

my config.yml
`scoreboard-teams:
  enabled: true
  invisible-nametags: false
  anti-override: true
  enable-collision: true
  sorting-types:
  - GROUPS:yönetici,moderatör,yayıncı,pvip,vip+,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  header:
  - ''
  - '%animation:ip%'
  - ''
  footer:
  - ''
  - '&7Toplam Aktif: &e%bungeeonline_% &8| &7Hayatta Kalma Aktif: &e%online%'
  - ''
  - '&7Destek talebi açmak veya mağazaya göz atmak için'
  - '%animation:web%'
  - ''
  per-world:
    world2-world3:
      header:
      - This is a shared header for
      - world2 and world3
    world1:
      footer:
      - header/footer and prefix/suffix
      header:
      - an example of world with custom
yellow-number-in-tablist:
  enabled: false
  value: ''
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: true
  number: '%health%'
  text: '&c♥'
  disable-in-worlds:
  - disabledworld
prevent-spectator-effect:
  enabled: true
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  default-bars:
  - ServerInfo
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '%animation:purpur%'
    test:
      display-condition: permission:tab.bossbar.test;%world%=testworld
      style: PROGRESS
      color: WHITE
      progress: '100'
      text: test
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  disable-in-worlds:
  - disabledworld
  scoreboards:
    default:
      title: '&dPurpurMC'
      lines:
      - '&8%date% %time%'
      - ''
      - '&7pp: <gradient:#FBFF00:#FFC100>%vault_eco_balance_formatted%</gradient>'
      - '&7Boyut: %getworld_%'
      - '&7Gecikme: %player_colored_ping%ms'
      - ''
      - '%animation:ip%'
    quest:
      title: '&dPurpurMC'
      lines:
      - '&8%date% %time%'
      - ''
      - '%quest_line_1%'
      - '%quest_line_2%'
      - '%quest_line_3%'
      - '%quest_line_4%'
      - '%quest_line_5%'
      - '%quest_line_6%'
      - '%quest_line_7%'
      - '%quest_line_8%'
      - '%quest_line_9%'
      - ''
      - '%quest_progress%'
      - ''
      - '%animation:ip%'
  respect-other-plugins: true
  delay-on-join-milliseconds: 1
ping-spoof:
  enabled: false
fix-pet-names:
  enabled: true
placeholders:
  date-format: dd/MM/yyyy
  time-format: HH.mm.ss
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%tps%':
    '20': '&aPerfect'
  '%afk%':
    'true': ' &4*&4&lAFK&4*&r'
    'false': ''
conditions:
  health:
    conditions:
    - '%health%<21'
    - '%health%>15'
    type: AND
    true: Healthy!
    false: Damaged!
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 500
assign-groups-by-permissions: false
primary-group-finding-list:
- yönetici
- moderatör
- yayıncı
- pvip
- vip+
- vip
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
`

**Comment by NEZNAMY** [comment]
You may have an error logged in errors.log file.

**Comment by UsainSrht** [comment]
> You may have an error logged in errors.log file.

```
02.02.2022 - 13:59:56 - [TAB v3.0.2] An error occurred when refreshing placeholders
02.02.2022 - 13:59:56 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.Property.updateAndGet()" because the return value of "me.neznamy.tab.api.TabPlayer.getProperty(String)" is null
02.02.2022 - 13:59:56 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.features.HeaderFooter.refresh(HeaderFooter.java:89)
02.02.2022 - 13:59:56 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:88)
02.02.2022 - 13:59:56 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68)
02.02.2022 - 13:59:56 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$2(CpuManager.java:108)
02.02.2022 - 13:59:56 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$5(CpuManager.java:155)
02.02.2022 - 13:59:56 -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02.02.2022 - 13:59:56 -        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02.02.2022 - 13:59:56 -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02.02.2022 - 13:59:56 -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02.02.2022 - 13:59:56 -        at java.base/java.lang.Thread.run(Thread.java:833)
02.02.2022 - 14:11:10 - [TAB v3.0.2] An error occurred when refreshing placeholders
02.02.2022 - 14:11:10 - java.lang.NullPointerException: null
02.02.2022 - 14:51:20 - [TAB v3.0.1] Tried to register duplicated team TAB-SB-TM-4 to player alierenatik

```

**Comment by NEZNAMY** [comment]
3.0.2 and then 3.0.1? What is that order? Either way this error specifically is not the cause, must be something else. If no one else reports this, there is something specific with your setup causing it.

**Comment by UsainSrht** [comment]
I just switched back to 3.0.1 to make it work for now dont mind it

**Comment by NEZNAMY** [comment]
3.0.2 works fine for me and 500 others (according to bStats) with the steps you provided.

**Comment by UsainSrht** [comment]
I also updated protocollib to 4.8.0 build 540 could be because of it?

**Comment by NEZNAMY** [comment]
I have no idea, as you can see, no one else reported this issue, so I only know as much as you said in this issue.

**Comment by UsainSrht** [comment]
Alright then, I will take look at this. Thanks.
