### ISSUE TITLE
[Wiki] Improve spelling of "Progress" explanation

### ISSUE THREAD

**Issue by Andre601** [NEZNAMY/TAB#493]
First of: This is not a bug with the plugin, so forgive me for not using the template here.

I'm writing this post because the wiki has a IMO badly written description for the progress example of the bossbar feature. [[Link](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar#progress)]

I would like to recommend the following changes:
```markdown
If you want to show the progress of a placeholder's value relative to a maximum one, you can use the [Math Expansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#math) from PlaceholderAPI and use a placeholder like this one: `%math_{placeholder_current_value}/{placeholder_max_value}*100%` or `%math_{placeholder_current_value}/<max_value>*100%` if your max value is fixed.

Notes:  
Replace the text in between the `{}` with the actual placeholder you want to use and `<max_value>` with a valid number (i.e. 20).  
You cannot use the `%placeholder%` format inside the math placeholder.

Example for showing a player's heath: `%math_{player_health}/20*100%`
```

This is only a suggestion, but I think it could improve the understanding of how placeholders in the bossbar would work...

**Comment by NEZNAMY** [comment]
Done.
