### ISSUE TITLE
Can't convert to new config "java.nio.file.NoSuchFileException: plugins/TAB/old_configs/animations.yml"

### ISSUE THREAD

**Issue by markaabo** [NEZNAMY/TAB#494]
**Server version**
Paper 1.18.1-187

**Plugin version** ("latest" is not a version)
3.0.2

**Describe the bug**
TAB doesn't convert the config file correctly leaving the new config file completely empty and generates the error provided below.

**How to reproduce**
Install TAB 3.0.2, with config from before 3.0.0 

**Expected behavior**
TAB converting the config file to work with the new config setup

**Actual behavior**
It error out and doesn't convert the config structure.

**Additional info** (errors, screenshots, ...)
`08.02.2022 - 22:46:02 - [TAB v3.0.2] Failed to enable. Did you just invent a new way to break the plugin by misconfiguring it?
08.02.2022 - 22:46:02 - java.nio.file.NoSuchFileException: plugins/TAB/old_configs/animations.yml
08.02.2022 - 22:46:02 -        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
08.02.2022 - 22:46:02 -        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
08.02.2022 - 22:46:02 -        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
08.02.2022 - 22:46:02 -        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
08.02.2022 - 22:46:02 -        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
08.02.2022 - 22:46:02 -        at java.base/java.nio.file.Files.copy(Files.java:1305)
08.02.2022 - 22:46:02 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.config.Converter.convertToV3(Converter.java:68)
08.02.2022 - 22:46:02 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.config.Configs.loadConfig(Configs.java:91)
08.02.2022 - 22:46:02 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.config.Configs.loadFiles(Configs.java:74)
08.02.2022 - 22:46:02 -        at TAB.v3.0.2.jar//me.neznamy.tab.shared.TAB.load(TAB.java:151)
08.02.2022 - 22:46:02 -        at TAB.v3.0.2.jar//me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:47)
08.02.2022 - 22:46:02 -        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
08.02.2022 - 22:46:02 -        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
08.02.2022 - 22:46:02 -        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
08.02.2022 - 22:46:02 -        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
08.02.2022 - 22:46:02 -        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
08.02.2022 - 22:46:02 -        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
08.02.2022 - 22:46:02 -        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
08.02.2022 - 22:46:02 -        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
08.02.2022 - 22:46:02 -        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
08.02.2022 - 22:46:02 -        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
08.02.2022 - 22:46:02 -        at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by NEZNAMY** [comment]
Your old folder was missing animations.yml file.
