### ISSUE TITLE
pluginmessage spam

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#495]
**Server version**
1.18.1 Paperspigot

**Plugin version** ("latest" is not a version)
3.0.2

**Describe the bug**
My console will be spammed with messages after joins and rejoins

**How to reproduce**
i activated debug mode for packets
after that i looked into my bungeelogs
log shows me a mass of messages about placeholder things

**Expected behavior**
it shouldnt be much plugin messages

**Actual behavior**
there are lot of messages in bungeelog when i join and leave
logsize raise imediently

**Additional info** (errors, screenshots, ...)
![Screenshot_2](https://user-images.githubusercontent.com/32147021/153296513-1e2be6c3-8a56-4880-96d1-68c7697a915c.png)

**Comment by NEZNAMY** [comment]
Deactivate debug mode for packets. Bridge will be recoded in the next version to avoid packet spam.
