### ISSUE TITLE
Autocomplete command

### ISSUE THREAD

**Issue by NoltoxGit** [NEZNAMY/TAB#497]
### Server version

Pufferfish 1.17.1

### TAB version

3.0.2

### Describe the bug

When you configure a command to toggle the scoreboard/bossbar the command does not appear in the autocomplete.

### Expected behavior

Commands indicated as `toggle-command:` would be expected to appear in the autocomplete.

### Steps to reproduce

Step 1: Add a command to toggle
Step 2: Restart the server
Step 3: Try it, and it doesn't appear

### Checklist

- [X] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration

**Comment by NEZNAMY** [comment]
Dynamic (fake) commands do not appear in tabcomplete, because they don't actually exist. For a command to get registered it has to be defined in plugin.yml, which cannot be dynamically edited in config.

**Comment by NEZNAMY** [comment]
Added this info to the wiki.
