### ISSUE TITLE
[Suggestion] Support Chocolate (Alternative RedisBungee for Velocity)

### ISSUE THREAD

**Issue by Euphillya** [NEZNAMY/TAB#498]
### Server version

git-Purpur-1560 (MC: 1.18.1)

### TAB version

TAB v3.0.2

### Describe the bug

Hello, sorry it's not a bug, but no section exists for suggestions :/

I propose for Velocity, a Chocolate support which is like RedisBungee but for Velocity

Chocolate : https://github.com/GiansCode/Chocolate

### Expected behavior

null

### Steps to reproduce

null

### Checklist

- [x] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
There is no feature requests template, because they are closed https://github.com/NEZNAMY/TAB#issues. On top of that, velocity is not officially supported https://github.com/NEZNAMY/TAB/wiki/Compatibility#proxies.

**Comment by NEZNAMY** [comment]
https://github.com/GiansCode/Chocolate/blob/master/spigot/src/main/java/io/alerium/chocolate/hook/PAPIExpansion.java#L32 ;)
