### ISSUE TITLE
CMI-Glow doesn't work with TAB.

### ISSUE THREAD

**Issue by xISHRAKx** [NEZNAMY/TAB#499]
### Server version

Paper 1.18.1

### TAB version

3.0.2

### Describe the bug

CMI Glow doesn't work with TAB. I know There is a fix for Glow plugins in Wiki, But this issue is different then that.

Inorder to put custom color on people's glow CMI uses Team to change color. But When CMI tries to put a person in a TEAM Tab overrides it, Making CMI unable to put custom glow color on the person.

Also if i try to turn of Anti-Override in TAB config, Tab stops sorting Player.

### Expected behavior

I don't know what behaviour to expect. Expected behaviour is to let CMI manage its team But make it as it won't conflict with Tab team maybe?

Maybe if there is CMI plugin present on a Server, use the CMI's Team for sorting and let CMI make Team, I dont know im total noob at this stuff.

### Steps to reproduce

Step 1: Have CMI ...
Step 2: Just put Tab and CMI together in Server.
Step 3: Go ingame and do /glow [color]

It will only let you have White color.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
Based on the info given here you should follow the wiki page of making TAB compatible with glow plugins.
You said it isn't that issue but I can confirm it is...

**Comment by NEZNAMY** [comment]
Just from the fact that you can't describe how it's supposed to work it implies there is no solution other than the one of the wiki. Players can only be in one team and that team can only be managed by one plugin. Decide which plugin you want to handle teams and configure that one.

**Comment by xISHRAKx** [comment]
> Just the fact that you can't describe how it's supposed to work implies there is no solution other than the one on the wiki. Players can only be in one team and that team can only be managed by one plugin. Decide which plugin you want to handle teams and configure that one.

The wiki's fix shows how to fix Name tag now showing the glow color, But This problem revolves around the actual glow effect color, Not Name Tag

**Comment by MrGraycat** [comment]
> > Just the fact that you can't describe how it's supposed to work implies there is no solution other than the one on the wiki. Players can only be in one team and that team can only be managed by one plugin. Decide which plugin you want to handle teams and configure that one.
> 
> The wiki's fix shows how to fix Name tag now showing the glow color, But This problem revolves around the actual glow effect color, Not Name Tag

Glow plugins use the team prefix to display glow colors when applying the fix mentioned on that wiki page it will be put in TAB's team prefix which internally results in the proper glow color

**Comment by xISHRAKx** [comment]
> > > Just the fact that you can't describe how it's supposed to work implies there is no solution other than the one on the wiki. Players can only be in one team and that team can only be managed by one plugin. Decide which plugin you want to handle teams and configure that one.
> > 
> > 
> > The wiki's fix shows how to fix Name tag now showing the glow color, But This problem revolves around the actual glow effect color, Not Name Tag
> 
> Glow plugins use the team prefix to display glow colors when applying the fix mentioned on that wiki page it will be put in TAB's team prefix which results in the proper glow color

I have already tried it, But it doesnt work, I can show proofs too.

**Comment by NEZNAMY** [comment]
If you think so, show your configuration and explain how it should look like and how it looks instead.

**Comment by xISHRAKx** [comment]
This are the Config.yml and groups.yml

But when i disable the scoreboard-teams CMI glow works fine, But when i turn it on cmi only gives white color.

**Comment by NEZNAMY** [comment]
You completely forgot to use the glow placeholder in tagprefix.

**Comment by xISHRAKx** [comment]
> You completely forgot to use the glow placeholder in tagprefix.

oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooof, In the wiki i saw Tab instead of Tag ;-;;;;;
