### ISSUE TITLE
Separate unlimited nametag prefix and suffix

### ISSUE THREAD

**Issue by CryLegende** [NEZNAMY/TAB#50]
Can you separate the unlimited nametag prefix and the unlimited nametag suffix please ? ^^
Like that, only the prefix is in armorstand and the nickname stay normal :)

(Or you can just keep the normal nickname when the vanilla belowname feature is enabled)

Thanks for your help ^^

**Comment by NEZNAMY** [comment]
Not possible, that would look too weird.
