### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ZDaPlaY** [NEZNAMY/TAB#500]
### Server version

Purpur-1557

### TAB version

TAB version 3.0.1

### Describe the bug

![image](https://user-images.githubusercontent.com/88196950/154995755-ca2eaa0e-1470-4f91-afb2-e8a24ded9f67.png)
![image](https://user-images.githubusercontent.com/88196950/154995792-bd654ec5-5460-4880-a7cd-c836d4ab3d1e.png)

When I use several lines above the player, armor stands are created and when I go into spectator mode and enter first person you see the armor stands, plugins like hmc cosmetics have already fixed that, they also had armor stands and made them invisible.

### Expected behavior

When I use several lines above the player, armor stands are created and when I go into spectator mode and enter first person you see the armor stands, plugins like hmc cosmetics have already fixed that, they also had armor stands and made them invisible.

### Steps to reproduce

When I use several lines above the player, armor stands are created and when I go into spectator mode and enter first person you see the armor stands, plugins like hmc cosmetics have already fixed that, they also had armor stands and made them invisible.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You are **not** running latest version of the plugin.
Armor stands already are invisible. Spectator mode works the way that it shows invisible entities. If you don't want it, disable unlimited nametag mode.

**Comment by ZDaPlaY** [comment]
If I remove the unlimited nametag mode then I won't be able to put multiple lines right?
