### ISSUE TITLE
Fix tablist-name-formatting?

### ISSUE THREAD

**Issue by RedrDevConfig** [NEZNAMY/TAB#501]
### Server version

1.8.9

### TAB version

3.0.2

### Describe the bug

https://www.youtube.com/watch?v=c872UgUdxPQ

### Expected behavior

test

### Steps to reproduce

test

### Additional info

![image](https://user-images.githubusercontent.com/98342202/155052004-5a537fbe-213d-4f1b-8248-fc437df9e635.png)
![image](https://user-images.githubusercontent.com/98342202/155052020-5bc64e0a-5fa0-456d-8984-b4a72a85c925.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by RedrDevConfig** [comment]
Hello!

Config.yml -> https://paste.helpch.at/odepufamuc.cs
Groups.yml -> https://paste.helpch.at/ijivofafom.pl

**Comment by NEZNAMY** [comment]
Are you sure youe client is 1.8.9 and not the buggy 1.8.0?

**Comment by RedrDevConfig** [comment]
> Are you sure your client is 1.8.9 and not the buggy 1.8.0?

not client bug 1.8.9 and labymod, you plugin TAB 

Fix tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: true
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - Maps all

**Comment by RedrDevConfig** [comment]
No bug TAB 2.9.2, Yes Fixed 3.0.2
![image](https://user-images.githubusercontent.com/98342202/155178697-e4c419f2-afaf-4150-a04c-dceb390c0c71.png)

**Comment by NEZNAMY** [comment]
Yes, I accidentally removed the fix code in 3.0.0.

**Comment by RedrDevConfig** [comment]
tablist-name-formatting TAB version ¿?

- 3.0.1
- 3.0.0

**Comment by NEZNAMY** [comment]
The feature works, except compensation for 1.8.0 bug will be fixed in the next version.
