### ISSUE TITLE
How do i make scoreboard per-world?

### ISSUE THREAD

**Issue by FrostX-Official** [NEZNAMY/TAB#502]
There's no per-world function in scoreboard in config.yml,
but on spigot page it saying there is per-world support
![image](https://user-images.githubusercontent.com/76787958/155265749-d54396f3-624c-4a21-a6ac-845edcf4d570.png)

**Comment by NEZNAMY** [comment]
Spigot page is outdated. Use display conditons. Github issues are not for support, see readme.
