### ISSUE TITLE
Groups not working correctly

### ISSUE THREAD

**Issue by mitchngwen** [NEZNAMY/TAB#503]
### Server version

purpur 1.18.1

### TAB version

3.0.2

### Describe the bug

So the placeholder shows up instead of the information that the placeholder gives. I'm too stupid to figure this out and can not tell if it's me or a bug.
![Screenshot_20220224_134539](https://user-images.githubusercontent.com/45637150/155605243-32636bb5-16c8-4b9d-ad8a-d73d7b17eaa3.png)
[config.txt](https://github.com/NEZNAMY/TAB/files/8136133/config.txt)
[groups.txt](https://github.com/NEZNAMY/TAB/files/8136177/groups.txt)

### Expected behavior

expected behavior is that I expect the placeholders to work.

### Steps to reproduce

Use the plugin on bungee and setup groups with placeholders.

### Additional info

This is on bungeecord.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Internal bukkit-only placeholders don't work on bungeecord. You did not read the wiki despite stating you did.

**Comment by mitchngwen** [comment]
I had to say I read all of you 6,000,000,000 words on your wiki to open a bug/support ticket! I read most of it, I would not donate to because your attitude.

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/155614856-efd4f1a9-b5c6-4977-894d-0d7681a3a4c9.png)
![image](https://user-images.githubusercontent.com/45695833/155614859-cbf84c43-f6c5-4495-8ee8-ea5e13d933ec.png)

**Comment by mitchngwen** [comment]
Also what the hell is the TAB bridge for then?

**Comment by Tanguygab** [comment]
for PlaceholderAPI placeholders, not internal ones, as stated on its plugin page

**Comment by NEZNAMY** [comment]
> I had to say I read all of you 6,000,000,000 words on your wiki to open a bug/support ticket! I read most of it, I would not donate to you because your attitude.

Thanks, don't donate, you'll make it easier for me to quit this project which I wasted years on just so you can download it for free.

**Comment by mitchngwen** [comment]
lol, dude I get it it take hours to code this stuff and it's not easy. I have way too much too read at the moment and just needed a quick answer. Thanks for getting back to me.
