### ISSUE TITLE
Health Display is not working correctly

### ISSUE THREAD

**Issue by Dante5657** [NEZNAMY/TAB#505]
### Server version

1.8.8

### TAB version

3.0.2

### Describe the bug

- The health display is not updating when a player eats a golden apple or gets his health generated by any other means and updates only if the player gets damaged
- When the player eats a golden apple and he has absorption hearts it still shows as 20 HP on health display instead of 24

### Expected behavior

The below name should update anytime when the player health is changed including regen, apple consumption, API health calls, and natural regeneration

### Steps to reproduce

Use 3.0.2 
Enable health displays
Nothing else to do. It is broken overall

### Additional info

The health display was working completely fine on version 2.8.8 or even 2.9.2 so maybe reverting the logic to those versions can help this to be fixed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with the configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
yeah, the %health% placeholder isn't updating perfectly. Until it's fixed, you can use its PAPI alternative %player_health_rounded%

**Comment by Dante5657** [comment]
You can't imagine how much that helps, Thanks a lot for the response!
