### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by AdhityaXD1604** [NEZNAMY/TAB#507]
### Server version

Purpur 1.18.1

### TAB version

3.0.2

### Describe the bug

*So the bug is that I made animation at https://www.simplymc.art/AnimTAB when I put it in the plugin tab when I saw it in the ingame how come the animation isn't smooth, right? even though the interval is in accordance with the simplymc*

Uploading 2022-02-26 08-48-25.mp4…

### Expected behavior

-

### Steps to reproduce

-

### Additional info

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://gyazo.com/cdae8808a9868ea4a58dc79cdf8ffe62 this is what I get with the default animation from the website. Looks fine.

**Comment by AdhityaXD1604** [comment]
> https://gyazo.com/cdae8808a9868ea4a58dc79cdf8ffe62 this is what I get with the default animation from the website. Looks fine.

how come it's smooth? on my server how come it doesn't work? even though my tps is 20 plugins 78 and my server is dedicated 14GB Ram

**Comment by NEZNAMY** [comment]
It's smooth because it works as expected. It has nothing to do with plugin count or TPS, because refreshing and packet sending is async. You did not show any video how it looks for you.

**Comment by AdhityaXD1604** [comment]
> It's smooth because it works as expected. It has nothing to do with plugin count or TPS, because refreshing and packet sending is async. You did not show any video how it looks for you.

can you help me fix this animation not smooth pls

**Comment by NEZNAMY** [comment]
You did not show any video how it looks for you.

**Comment by AdhityaXD1604** [comment]
> You did not show any video how it looks for you.

i show my video bruh here is link https://cdn.discordapp.com/attachments/930746820471160883/946931790591975514/2022-02-26_08-48-25.mp4

**Comment by Tanguygab** [comment]
lunar bug

**Comment by AdhityaXD1604** [comment]
> lunar bug

u sure lunar problem?

**Comment by NEZNAMY** [comment]
You can try vanilla client to find out.

**Comment by Tanguygab** [comment]
![20220226_123126.jpg](https://user-images.githubusercontent.com/45695833/155841545-0d15294c-9a8b-47c2-b397-31c22bdeb4c0.jpg)

**Comment by AdhityaXD1604** [comment]
> Sounds like an issue you may get if you use the animation as a nested placeholder, not directly. Show your configuration, so I can copy it and try.

ok wait

**Comment by AdhityaXD1604** [comment]
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  header:
    - "%animation:Survival%"
    - "%animation:MyAnimation1%"
  footer:
    - "%animation:MyAnimation1%"
    - "%animation:time%"
    - "%animation:ping-tps%"
    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "&7Visit our webpage %animation:web%"
  per-world:
    world1:
      header:
        - "an example of world with custom"
      footer:
        - "header/footer and prefix/suffix"
    world2;world3:
      header:
        - "This is a shared header for"
        - "world2 and world3"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "GROUPS:owner,admin,mod,helper,builder,vip,default"
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
  disable-in-worlds:
    - disabledworld
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: 0.22
    disable-in-worlds:
      - disabledworld
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Yellow-number
yellow-number-in-tablist:
  enabled: true
  value: "%ping%"
  disable-in-worlds:
    - disabledworld

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname
belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds:
    - disabledworld

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix
prevent-spectator-effect:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Per-world-playerlist
per-world-playerlist:
  enabled: false
  # players with tab.staff will always see all players
  allow-bypass-permission: false
  # players in these worlds will always see all players
  ignore-effect-in-worlds:
    - ignoredworld
    - build
  shared-playerlist-world-groups:
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds: 
    - disabledworld
  scoreboards:
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "%animation:MyAnimation1%"
        - "&6Online:"
        - "* &eOnline&7: &f%online%&7/&4%maxplayers%"
        - "* &eCurrent World&7: &f%worldonline%"
        - "* &eStaff&7: &f%staffonline%"
        - " "
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
        - "%animation:MyAnimation1%"
    scoreboard1:
      title: "Default"
      lines:
        - "%animation:MyAnimation1%"
        - "&6My Stats:"
        - "* &eKills&7: &f%statistic_player_kills%"
        - "* &eDeaths&7: &f%statistic_deaths%"
        - "* &eHealth&7: &f%health%"
        - " "
        - "&6Personal Info:"
        - "* &bRank&7: &f%group%"
        - "* &bPing&7: &f%ping%&7ms"
        - "* &bWorld&7: &f%world%"
        - "%animation:MyAnimation1%"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Ping-Spoof
ping-spoof:
  enabled: false
  value: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
fix-pet-names:
  enabled: false

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  "%afk%":
    true: " &o[AFK]&r"
    false: ""
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" #placeholder did not parse correctly, show real name instead

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
    "%server_unique_joins%": 5000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

# assigning groups by permission nodes instead of taking them from permission plugin
assign-groups-by-permissions: false

# if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
# Warning! This is not sorting list and has nothing to do with sorting players in tablist!
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

# https://github.com/NEZNAMY/TAB/wiki/MySQL
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password

**Comment by AdhityaXD1604** [comment]
> > ![20220226_123126.jpg](https://user-images.githubusercontent.com/45695833/155841545-0d15294c-9a8b-47c2-b397-31c22bdeb4c0.jpg)
> 
> wait let me using tlauncher

im using tlauncher now and still not smooth :(

**Comment by NEZNAMY** [comment]
This is not a valid paste I could use. Try using the animation directly and not inside any palceholder.

**Comment by AdhityaXD1604** [comment]
> This is not a valid paste I could use. Try using the animation directly and not inside any placeholder.

what you mean?

**Comment by NEZNAMY** [comment]
Try to copypaste the text you sent above and you'll quickly notice it's not copy-able into valid yaml syntax. You also did not include animation file.

**Comment by AdhityaXD1604** [comment]
> Try to copypaste the text you sent above and you'll quickly notice it's not copy-able into valid yaml syntax. You also did not include animation file.

wait

**Comment by NEZNAMY** [comment]
Any working paste website.

**Comment by AdhityaXD1604** [comment]
> Any working paste website.

animation.yml > https://paste.gg/p/anonymous/6e71425960944113a8b3ada19648ea7f
config.yml > https://paste.gg/p/anonymous/0d9b078a3ab94b579047e28d02674135

**Comment by NEZNAMY** [comment]
You called the animation `Survival` in config but `survival` in animations, which causes it to not work at all. After fixing that, it works perfectly. The only possible cause could be related to cpu overload, which is unlikely on a test server with 1 player, but just in case, can you check output of /tab cpu to make sure it's not at 100%?
