### ISSUE TITLE
Placeholderapi_ERROR related to towny

### ISSUE THREAD

**Issue by enterih** [NEZNAMY/TAB#508]
### Server version

PaperSpigot 1.18.1 

### TAB version

3.0.2

### Describe the bug

Hello 
i have an issue related with Papi.
`[PlaceholderAPI] Loaded class com.palmergames.bukkit.towny.exceptions.NotRegisteredException from Towny v0.98.0.0 which is not a depend or softdepend of this plugin.`

Could this warning be the reason for this placeholderapierror?

Server is running on Paper 1.18 214 in a Waterfall 478 network.
Plugins who are related to the issue:
Townyadvanced 0.98
Tab (bungeecord) 3.0.2
Placeholderapi 2.11.1 

I didnt find any more warnings or errors in logs also with debugmode in Papi, Towny and Tab

https://media.discordapp.net/attachments/581163022874050569/947093950995496960/unknown.png

### Expected behavior

It should display the correct placeholder. 

%townyadvanced_towny_tag%

### Steps to reproduce

Install Towny 0.98
Install Papi 2.11.1
Install Tab 3.0.2 on a Bungeecordserver with the bridge on the server

I'm  Using this in the groups.yml. replace the servername
https://www.toptal.com/developers/hastebin/ekojiboqeq.less

### Additional info

The guys on the townydiscord, that the issue don't come fron Towny so i comming here to ask, if the issue comes from here and if yes or no maybe have a guide how fix it. 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Where in the harmless console message does it say tab?

**Comment by enterih** [comment]
Thanks. I got the issue and could fix it with your help.
