### ISSUE TITLE
How To Set Player DeluxeTags In To TAB

### ISSUE THREAD

**Issue by AdhityaXD1604** [NEZNAMY/TAB#509]
How To Set Player Tags In TAB like this 
like this > https://cdn.discordapp.com/attachments/869377929786818651/945973532821704704/Screenshot_2322.png
next to the player's name

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting
Github issues are not for support.

**Comment by AdhityaXD1604** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting Github issues are not for support https://github.com/NEZNAMY/TAB#issues

so where i want to need help with question.
i dont understand how to add deluxe tags pls help me

**Comment by NEZNAMY** [comment]
Support for buyers is provided on discord, as the only advantage they have.
