### ISSUE TITLE
TAB Does not like Kettle Servers.

### ISSUE THREAD

**Issue by VanillaChan6571** [NEZNAMY/TAB#51]
**Server version** 
1.12.2 - Kettle

**Plugin version**
 2.5.3

**Describe the bug** 
Doesn't Enable even if set to none

**How to reproduce**
Get kettle server and add TAB plugin in the plugins folder.
Launch server with mods.
PING is not a valid type of tablist-objective.

**Expected behavior**
Work like a normal server.

**Actual behavior**
Errors when there is forge mods etc.

**Additional info** 
https://hastebin.com/anifacorid.sql

**Comment by NEZNAMY** [comment]
Are you able to join discord and PM me ? I will send you jar(s) to test.

**Comment by NEZNAMY** [comment]
From Kettle dev: http://prntscr.com/pejw99
