### ISSUE TITLE
Rank Position Bug

### ISSUE THREAD

**Issue by AdhityaXD1604** [NEZNAMY/TAB#511]
### Server version

1.18.1

### TAB version

3.0.2

### Describe the bug

how come my rank and donor rank and staff rank are below the member rank in the tablist, how do I fix it?

Image > https://cdn.discordapp.com/attachments/940219602296774666/947421106460033024/Screenshot_2347.png

### Expected behavior

-

### Steps to reproduce

-

### Additional info

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Sorting works. This report is invalid. Support is not provided in github issues.

**Comment by AdhityaXD1604** [comment]
> Sorting works. This report is invalid. Support is not provided in github issues.

why pls help me fix it :(

**Comment by AdhityaXD1604** [comment]
> Sorting works. This report is invalid. Support is not provided in github issues.

sho where i get support bro

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/509#issuecomment-1052121778
