### ISSUE TITLE
RHideTags fix?

### ISSUE THREAD

**Issue by ArtemBay** [NEZNAMY/TAB#513]
### Server version

Spigot 1.18.1

### TAB version

3.0.2

### Describe the bug

All working good but RHideTags didnt works

### Expected behavior

Will hide tags above head

### Steps to reproduce

Step 1. Install Tab
Step 2. Install RHideTags

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Only one plugin can handle teams at a time. If you don't want TAB to handle them, disable the feature in config.

**Comment by ArtemBay** [comment]
Oh, where i can disable this?

**Comment by NEZNAMY** [comment]
```
scoreboard-teams:
  enabled: false
```
Pretty self-explanatory.

**Comment by ArtemBay** [comment]
Sorry for disturbing
