### ISSUE TITLE
tag freezes when someone gets on a modelengine/mythicmobs mob

### ISSUE THREAD

**Issue by ZDaPlaY** [NEZNAMY/TAB#514]
### Server version

1.18.1 Purpur-1565

### TAB version

TAB version 3.0.2

### Describe the bug

![image](https://user-images.githubusercontent.com/88196950/156018063-02fc42be-b98f-4e48-978e-afc748450e0f.png)
when someone rides a modelengine mob, the tag floats where the player mount
![image](https://user-images.githubusercontent.com/88196950/156018366-ed136a60-ddc7-420e-b145-57a72d8f8ee9.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/88196950/156018057-cd85f18a-b957-4c5d-91e2-047d4853f72a.png)
![image](https://user-images.githubusercontent.com/88196950/156018380-8c71264b-7896-488b-8456-102ae9c3195c.png)
when someone rides a modelengine mob, the tag floats where the player mount

### Steps to reproduce

![image](https://user-images.githubusercontent.com/88196950/156018053-796cd66c-4544-4f7a-9b04-944b6ff4425a.png)
![image](https://user-images.githubusercontent.com/88196950/156018388-ef43513b-0e37-4a22-b464-ec6e607ce51d.png)
when someone rides a modelengine mob, the tag floats where the player mount

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by ZDaPlaY** [comment]
It also happens with itemadder planes, cars, etc.

**Comment by ZDaPlaY** [comment]
I think it happens with the mountable that is not from minecraft vanilla

**Comment by NEZNAMY** [comment]
Try 3.1.0

**Comment by NEZNAMY** [comment]
@ZDaPlaY

**Comment by NEZNAMY** [comment]
Likely fixed in 3.1.0, reopen if not.
