### ISSUE TITLE
Sorting of tablist does not work

### ISSUE THREAD

**Issue by ZypoSyna** [NEZNAMY/TAB#519]
### Server version

purpur 1.18.2

### TAB version

3.1.0

### Describe the bug

So I have been using this plugin for a while now,

But when switching servers and version the tab sorting does not work anymore ( I have updated from purpur 1.18.1 to purpur 1.18.2 and from TAB 3.0 )

When doing /tab debug koekie_w ( Owner ) It says "Primary group is #1 in sorting list." 
When doing /tab debug Duules ( helper ) It says "Primary group is #6 in sorting list." 
-> Eventhough this info is correct the tab does not sort correctly

The Prefixes also do not show above the players ( Before it was f.e: "owner koekie_w" now it is just "koekie_w"

**CONFIG**
https://pastebin.com/WTRL0Umy

**GROUPS**
https://pastebin.com/nW0PaYFN

_Note: For some reason the tab keeps sorting on player name_

### Expected behavior

So the Tab should be ordered from
Owner > manager > admin > srmod >mod > helper > default

### Steps to reproduce

I have linked my config and group yml ( It just happends )

**CONFIG**
https://pastebin.com/WTRL0Umy

**GROUPS**
https://pastebin.com/nW0PaYFN

### Additional info

![2022-03-07_22 23 57](https://user-images.githubusercontent.com/101146922/157122196-fb90a123-f27d-464f-b664-5e1892e054d9.png)
![2022-03-07_22 26 32](https://user-images.githubusercontent.com/101146922/157122199-71557f3b-ec1b-4ab4-89a7-301033f68c71.png)
![2022-03-07_22 23 12](https://user-images.githubusercontent.com/101146922/157122207-eecfa028-678b-4ce8-8373-26f81c14f9f6.png)
![Screenshot 2022-03-07 223907](https://user-images.githubusercontent.com/101146922/157122212-1d31744d-bc57-4659-9abe-7a11be0934cb.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Update/delete eGlow.

**Comment by ZypoSyna** [comment]
I spent 4 hours trying to figure out the Issue by deleting the newly added plugins!

When I can I will leave some support on the paypal!

I am so thankfull right now!
