### ISSUE TITLE
Crash server error

### ISSUE THREAD

**Issue by CaoTrongThang** [NEZNAMY/TAB#52]
**Server version**
1.12.2

**Plugin version** ("latest" is not a version)
2.5.3

**Describe the bug**

**How to reproduce**

**Expected behavior**

**Actual behavior**

**Additional info** (errors, screenshots, ...)
https://pastebin.com/ijPLCpFb

**Comment by NEZNAMY** [comment]
And where do you see it's caused by TAB ?
