### ISSUE TITLE
essentials nick on tab with hex

### ISSUE THREAD

**Issue by Trinchezito** [NEZNAMY/TAB#523]
### Server version

spigot 1.18.1

### TAB version

3.1.0

### Describe the bug

when i do /nick &#8985fbJ&#8990eeu&#899be2g&#8aa6d5a&#8ab1c9d&#8abcbco&#8ac6b0r&#8ad1a3N&#8adc97i&#8be78an&#8bf27ej&#8bfd71a

The %essentials_nickname% works on the chat but not on the tab. 
![image](https://user-images.githubusercontent.com/98068350/157363587-a464da41-3504-41fb-93f8-40383783a042.png)

### Expected behavior

%essentials_nickname% does not properly work when using hex colors.

### Steps to reproduce

use %essentials_nickname% placeholder

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
How does it display in `/tab parse me <placeholder>` ?

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/157392105-021d78ed-5910-44ab-b0f2-f80c51cf404b.png)

**Comment by NEZNAMY** [comment]
Works for me on 1.18.2 server with 1.18.2 client. There must be something deeper behind this what you didn't say.
![image](https://user-images.githubusercontent.com/6338394/157407440-0acf5df5-695b-4cc3-b1e7-8a9e7eecc259.png)

**Comment by Trinchezito** [comment]
> Works for me on 1.18.2 server with 1.18.2 client. There must be something deeper behind this what you didn't say. ![image](https://user-images.githubusercontent.com/6338394/157407440-0acf5df5-695b-4cc3-b1e7-8a9e7eecc259.png)

![image](https://user-images.githubusercontent.com/98068350/157460401-8f792145-c8fb-4fdb-8a7e-b80339f84362.png)
So without any hex colors to modify the names it works. But when i put it like that <#FD6035>%essentials_nickname%</#FB2D2D> it doesn't work.

This is how it looks when the player doesn't have a nickname with hexcolor which is how <#FD6035>%essentials_nickname%</#FB2D2D> looks. So it gets messed up when the player uses /nick &#8985fbJ&#8990eeu&#899be2g&#8aa6d5a&#8ab1c9d&#8abcbco&#8ac6b0r&#8ad1a3N&#8adc97i&#8be78an&#8bf27ej&#8bfd71a
![image](https://user-images.githubusercontent.com/98068350/157460800-75913b3a-71f8-400d-a36a-6339e0eeaaf6.png)

**Comment by NEZNAMY** [comment]
Then it works as expected. You are trying to use gradient inside gradient, which doesn't make sense.

**Comment by Trinchezito** [comment]
> Then it works as expected. You are trying to use gradient inside gradient, which doesn't make sense.

So it's either use default server gradients and don't let players use gradients in /nick

Or allow /nick with gradient but don't use default server gradient color :( 

Well, okay thank you for clarifying this problem.

**Comment by NEZNAMY** [comment]
Or use [conditions](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders), but that's out of scope of issues section.
