### ISSUE TITLE
Groups are not sorted in latest update

### ISSUE THREAD

**Issue by Villmarksjenta** [NEZNAMY/TAB#526]
### Server version

Paper 1.18.2

### TAB version

3.1.0

### Describe the bug

After updating, the groups no longer gets sorted. Sorting from A to Z still works, but not groups. With /tab debug it tells me I am number #2 in sorting, but it still puts me below people that are in number #9 etc.

### Expected behavior

Put me in the correct position, and sort them by the groups listed in config.

### Steps to reproduce

Step 1: Log in
Step 2: Look at the tab seeing the ranks being all over the place.

### Additional info

Sorting:
  sorting-types:
  - GROUPS:eier,admin,mod,prøve-mod,vip,diamant,gull,sølv,default
  - PLACEHOLDER_A_TO_Z:%player%

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Plugin list?

**Comment by Villmarksjenta** [comment]
![image](https://user-images.githubusercontent.com/59545209/157744221-fd10bb40-844c-4722-8252-b557139a1feb.png)

**Comment by NEZNAMY** [comment]
I am unable to fix this eGlow bug from my side.

**Comment by Villmarksjenta** [comment]
Ok, so this is a bug from eGlow?

**Comment by MrGraycat** [comment]
The latest eGlow version should fix this issue once and for all.

**Comment by Villmarksjenta** [comment]
Ok, thank you guys for fast support! I appreciate it.
