### ISSUE TITLE
TAB list ranks unorganized instead of being in the order given

### ISSUE THREAD

**Issue by TuckerAndrews3** [NEZNAMY/TAB#527]
### Server version

Paper 1.18.2

### TAB version

3.1.0

### Describe the bug

Typically the TAB list is like, in order of ranks from Owner to Player, but now it's just random and jumbled up. Haven't touched my config, went from  3.0.1 to 3.1.0

### Expected behavior

Expecting the tablist to appear with the ranks in order

### Steps to reproduce

Honestly unsure, I can send you my configuration if you would like

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by TuckerAndrews3** [comment]
Also wanted to add that my default rank's prefix is not appearing their heads in game. Why is this happening ?

**Comment by MrGraycat** [comment]
update eGlow if you're using it

**Comment by TuckerAndrews3** [comment]
> update eGlow if you're using it

I am not using that

**Comment by MrGraycat** [comment]
In that case please do send your config also 2 debugs of player sorted properly and incorrect.

Thanks
MrGraycat

**Comment by TuckerAndrews3** [comment]
https://www.dropbox.com/s/qz0d6zcnf2exw5a/config.yml?dl=1

How do I get debugs?

**Comment by TuckerAndrews3** [comment]
It has magically fixed itself.. no idea what happened here. I will keep this open in case it happens again

**Comment by TuckerAndrews3** [comment]
Both of these are still happening at random

**Comment by NEZNAMY** [comment]
Maybe you disabled anti-override in config? Hard to say without any information.

**Comment by TuckerAndrews3** [comment]
Anti-Override is on

**Comment by NEZNAMY** [comment]
You still didn't show debug output of players in wrong order.

**Comment by TuckerAndrews3** [comment]
> [18:35:05 INFO]: [TAB] [TAB] Showing debug information
> [18:35:05 INFO]: [TAB] >-------------------------------<
> [18:35:05 INFO]: [TAB] Server version: 1.18.2 (v1_18_R2)
> [18:35:05 INFO]: [TAB] Plugin version: 3.1.0
> [18:35:05 INFO]: [TAB] Permission plugin: LuckPerms
> [18:35:05 INFO]: [TAB] Permission group choice logic: Primary group
> [18:35:05 INFO]: [TAB] Sorting system: GROUPS then PLACEHOLDER_A_TO_Z
> [18:35:05 INFO]: [TAB] >-------------------------------<
> [18:35:05 INFO]: [TAB] Player: Murdoc_Niccals
> [18:35:05 INFO]: [TAB] Primary permission group: owner
> [18:35:05 INFO]: [TAB] Team name: 1Murdoc_NiccalsA
> [18:35:05 INFO]: [TAB] Team name note: Primary group is #1 in sorting list. %player% returned "Murdoc_Niccals". 
> [18:35:05 INFO]: [TAB] tabprefix: "&#5457edOwner&f " (16) (Source: group=owner)
> [18:35:05 INFO]: [TAB] tabsuffix: "%afk%" (5) (Source: group=_DEFAULT_)
> [18:35:05 INFO]: [TAB] customtabname: "%essentials_nickname%" (21) (Source: group=_DEFAULT_)
> [18:35:05 INFO]: [TAB] tagprefix: "&#5457edOwner&f " (16) (Source: group=owner)
> [18:35:05 INFO]: [TAB] tagsuffix: "%afk%" (5) (Source: group=_DEFAULT_)
> [18:35:05 INFO]: [TAB] >-------------------------------<

Here is one of me. They are all out of order, do you want everyone online's?

**Comment by NEZNAMY** [comment]
Based on that you should be first. Does /tab reload fix it?

**Comment by TuckerAndrews3** [comment]
TAB reload reorganizes it randomly like shuffle

**Comment by TuckerAndrews3** [comment]
> [20:22:23 INFO]: [TAB] [TAB] Showing debug information
> [20:22:23 INFO]: [TAB] >-------------------------------<
> [20:22:23 INFO]: [TAB] Server version: 1.18.2 (v1_18_R2)
> [20:22:23 INFO]: [TAB] Plugin version: 3.1.0
> [20:22:23 INFO]: [TAB] Permission plugin: LuckPerms
> [20:22:23 INFO]: [TAB] Permission group choice logic: Primary group
> [20:22:23 INFO]: [TAB] Sorting system: GROUPS then PLACEHOLDER_A_TO_Z
> [20:22:23 INFO]: [TAB] >-------------------------------<
> [20:22:23 INFO]: [TAB] Player: ASTRANOMICON
> [20:22:23 INFO]: [TAB] Primary permission group: supporter
> [20:22:23 INFO]: [TAB] Team name: 5ASTRANOMICONA
> [20:22:23 INFO]: [TAB] Team name note: Primary group is #5 in sorting list. %player% returned "ASTRANOMICON". 
> [20:22:23 INFO]: [TAB] tabprefix: "&#ff6100Supporter&f " (20) (Source: group=supporter)
> [20:22:23 INFO]: [TAB] tabsuffix: "%afk%" (5) (Source: group=_DEFAULT_)
> [20:22:23 INFO]: [TAB] customtabname: "%essentials_nickname%" (21) (Source: group=_DEFAULT_)
> [20:22:23 INFO]: [TAB] tagprefix: "&#ff6100Supporter&f " (20) (Source: group=supporter)
> [20:22:23 INFO]: [TAB] tagsuffix: "%afk%" (5) (Source: group=_DEFAULT_)
> [20:22:23 INFO]: [TAB] >-------------------------------<
> [20:22:24 INFO]: <Undead corpse> does someone have a base on queb

This is the only player out of order right now

**Comment by NEZNAMY** [comment]
Can you just show your plugin list?

**Comment by TuckerAndrews3** [comment]
> [09:00:48 INFO]: Plugins (90): AdvancedNMotd, ArmorStandEditor, BannerMaker, BetterRTP, BlockParticles, BountyHunters, Buttontp*, BuycraftX, Cannons, Citizens, CMILib, Coins, ColoredEnderChests, ColoredSigns, CoreProtect, CustomCrafting, DeluxeMenus, Denizen, DiscordSRV, DyedBackpacks, dynmap, Dynmap-Towny, EcoPower, EffectLib, emotecraft*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventWar, ExoticGarden, FarmControl, HatCosmetics, HeadDatabase, HolographicDisplays, ImageOnMap, Images, InfinityStones, Jobs, LibsDisguises, LockettePro, LuckPerms, LuckPermsCompat*, MelooonCensor*, MessageAnnouncer, MiniaturePets, ModelEngine, Movecraft, Movecraft-Repair, Movecraft-Space, Movecraft-WorldGuard, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MythicCrucible, MythicMobs, neoPaintingSwitch*, NoteBlockAPI, PL-Hide, PlaceholderAPI, PlayerParticles, PluginConstructorAPI, ProtocolLib, QualityArmory, Quests, Shop, Slimefun, SlimefunWarfare, Space, spark, StaffChatReloaded, StructureBoxes, TAB, TARDIS, TARDISChunkGenerator, The_Gate, Towny, VanishNoPacket, Vault, Vehicles, VoidGen, Votifier, VotingPlugin, VoxelSniper, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, WorldGuard-Towny

**Comment by NEZNAMY** [comment]
Try downgrading / removing protocollib, you may be using a broken build.

**Comment by lChrisjm** [comment]
Got the same issue, in the debug it show my TEam name too weird:`[14:22:21 INFO]: lChrisJm issued server command: /tab debug
tab debug lchrisjm
[14:22:38 INFO]: [TAB] [TAB] Showing debug information
[14:22:38 INFO]: [TAB] >-------------------------------<
[14:22:38 INFO]: [TAB] Server version: 1.17.1 (v1_17_R1)
[14:22:38 INFO]: [TAB] Plugin version: 3.1.0
[14:22:38 INFO]: [TAB] Permission plugin: LuckPerms
[14:22:38 INFO]: [TAB] Permission group choice logic: Primary group
[14:22:38 INFO]: [TAB] Sorting system: GROUPS then PLACEHOLDER_Z_TO_A
[14:22:38 INFO]: [TAB] >-------------------------------<
[14:22:38 INFO]: [TAB] Player: lChrisJm
[14:22:38 INFO]: [TAB] Primary permission group: owner
[14:22:38 INFO]: [TAB] Team name: 01oxsirhqnA
[14:22:38 INFO]: [TAB] Team name note: Primary group is #1 in sorting list. %displayname% returned "lChrisJm".
[14:22:38 INFO]: [TAB] tabprefix: "&b%simpleclans_tag_label% &#35f6ee&lD&#4df2f2&lU&#65eef6&lE&#7deafa&l?&#95e6ff&lO &f" (84) (Source: group=owner)
[14:22:38 INFO]: [TAB] tabsuffix: "%afk%" (5) (Source: group=_DEFAULT_)
[14:22:38 INFO]: [TAB] customtabname: "%essentials_nickname%" (21) (Source: group=_DEFAULT_)
[14:22:38 INFO]: [TAB] tagprefix: "&#35f6ee&lD&#4df2f2&lU&#65eef6&lE&#7deafa&l?&#95e6ff&lO &f" (58) (Source: group=owner)
[14:22:38 INFO]: [TAB] tagsuffix: "%afk%" (5) (Source: group=_DEFAULT_)
[14:22:38 INFO]: [TAB] >-------------------------------<`

**Comment by lChrisjm** [comment]
> Plugin list?

`[16:19:48 INFO]: Plugins (83): AdvancedEnchantments, AdvancedPets, AdvanceParticle, AnnouncerPlus, AntiLavaCast, ArmorStandTools, asCMD*, AuctionHouse, BanItem, BanMobPlugin, BCommons*, BetterRTP, BungeeGuard, BuycraftX, CharacterDialogue*, ChatBrawl, ChatManager, Citizens, CMILib, CommandPanels, CommandWhitelist, ConditionalEvents, CoreProtect, DeathMessages, DecentHolograms, DiscordSRV, EconomyShopGUI, eGlow, EliteMobs, Essentials, EssentialsSpawn, ExtraContexts, EZColors, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, floodgate, GoldenCrates, GSit, HeadDB, Images, InvSeePlusPlus, Jobs, Landlord, LibsDisguises, LuckPerms, MarriageMaster, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MythicMobs, NBTAPI, NexEngine, PlaceholderAPI, PlayerKits, PlayTime*, ProtectionStones, ProtocolLib, PvPManager, SetTheSpawn, Shopkeepers, SimpleClans, SimpleMaintenance, SkinsRestorer, spark, StaffPlus, TAB, TimedRewards*, TimeIsMoney, TimeVote, TradeSystem, TrElytra, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Vulcan, WDLCompanion*, WGRegionEvents, WorldGuard, WorldGuardExtraFlags`

**Comment by Tanguygab** [comment]
> Try downgrading / removing protocollib, you may be using a broken build.

**Comment by MrGraycat** [comment]
> > Plugin list?
> 
> `[16:19:48 INFO]: Plugins (83): AdvancedEnchantments, AdvancedPets, AdvanceParticle, AnnouncerPlus, AntiLavaCast, ArmorStandTools, asCMD*, AuctionHouse, BanItem, BanMobPlugin, BCommons*, BetterRTP, BungeeGuard, BuycraftX, CharacterDialogue*, ChatBrawl, ChatManager, Citizens, CMILib, CommandPanels, CommandWhitelist, ConditionalEvents, CoreProtect, DeathMessages, DecentHolograms, DiscordSRV, EconomyShopGUI, eGlow, EliteMobs, Essentials, EssentialsSpawn, ExtraContexts, EZColors, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, floodgate, GoldenCrates, GSit, HeadDB, Images, InvSeePlusPlus, Jobs, Landlord, LibsDisguises, LuckPerms, MarriageMaster, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MythicMobs, NBTAPI, NexEngine, PlaceholderAPI, PlayerKits, PlayTime*, ProtectionStones, ProtocolLib, PvPManager, SetTheSpawn, Shopkeepers, SimpleClans, SimpleMaintenance, SkinsRestorer, spark, StaffPlus, TAB, TimedRewards*, TimeIsMoney, TimeVote, TradeSystem, TrElytra, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Vulcan, WDLCompanion*, WGRegionEvents, WorldGuard, WorldGuardExtraFlags`

update eGlow if you're not using version 3.1.4 of eGlow

**Comment by NEZNAMY** [comment]
Both issues are caused by outdated eGlow / broken ProtocolLib build.

**Comment by Netherwhal** [comment]
which versions of ProtocolLib are affected?

**Comment by NEZNAMY** [comment]
5.0.0 snapshot
