### ISSUE TITLE
Nametag dissapears when player is in boat

### ISSUE THREAD

**Issue by PovilasLT** [NEZNAMY/TAB#528]
### Server version

Paper 1.18.2

### TAB version

3.1.0

### Describe the bug

When player is in boat his custom nametag dissapears.

### Expected behavior

Nametag should always be visible.

### Steps to reproduce

Get in boat.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by DrWurzeli** [comment]
theres a config option thats literally called `disable-on-boats: `. might wanna change that to false..

**Comment by DrWurzeli** [comment]
additional information can be found at: https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-settings
let us know if that solves your problem
