### ISSUE TITLE
Add the placeholder %countdown% to /tab send bar command

### ISSUE THREAD

**Issue by thedarkonekiller** [NEZNAMY/TAB#529]
### Server version

papermc 1.18.1

### TAB version

3.1

### Describe the bug

Add the placeholder %countdown% to /tab send bar command please ;)

### Expected behavior

Add the placeholder %countdown% to /tab send bar command

### Steps to reproduce

Add the placeholder %countdown% to /tab send bar command

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What kind of a bug report is this?

**Comment by thedarkonekiller** [comment]
there is no request feature as a label so I bugged 
![2022-03-13_13 14 18](https://user-images.githubusercontent.com/76535453/158058904-7885006c-e0f8-4d11-987f-75b0c837226a.png)
because when we do a /tab send bar playername barname time we get this

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/158058938-ec94d5db-2d45-41a7-83b9-a59e926679a5.png)

**Comment by thedarkonekiller** [comment]
so no solution to this problem?

**Comment by NEZNAMY** [comment]
Correct.

**Comment by thedarkonekiller** [comment]
ok thanks ;)
