### ISSUE TITLE
Constant "checked for permission 'tab.staff' in console?

### ISSUE THREAD

**Issue by 3DKaii** [NEZNAMY/TAB#53]
**Server version**
1.14.4

**Plugin version**
v2.5.3

**Describe the bug**
While I am on the server my console constantly (1 to 3 times a _second_ or more!) says:
`[Server] INFO [PermissionsEx] User 3DKaii checked for permission 'tab.staff', regex-matched a value of true from cache.`

I _think_ this might be an issue with TAB but it might be a PermissionsEx issue too, not entirely sure so I'm checking here first. I have checked my Permissions file in a Parser and it gives no errors, and I added "tab.staff" to my permissions and it's saying "value true" but it keeps running 3 times a second on repeat, as if it's checking for the same permission even though it's already responded true? It only runs while I myself am on the server.

**How to reproduce**
It happens every time I log into the server and keeps happening constantly until I disconnect. I don't know where it's going wrong exactly so I'm not sure how to reproduce it.

**Expected behavior**
Running the line once, I suspect, would be normal.

**Actual behavior**
Literally between 1 to 10 lines per second of the exact same response, usually 3 times a second or more, just spamming my console messages despite it already having returned as "value true". It starts when I join the server and stops when I either stop the server or disconnect.

**Additional info**
The error.txt in TAB is not reporting this as an issue and has no mention of this occurring. Here's a copy of my current Permissions if that'll help (saved as a .txt for viewing, but is of course in my server files as a .yml):
[permissions.txt](https://github.com/NEZNAMY/TAB/files/3703243/permissions.txt)

![TAB or Permission Bug](https://user-images.githubusercontent.com/56101965/66409385-24aabe00-e9b6-11e9-9878-8cff869ca3a0.PNG)

**Comment by NEZNAMY** [comment]
This is correct. The only problem is that the message is displayed in console. I'm pretty sure you accidentally enabled some debug mode in pex config. Try disabling it. If you don't know how, try resetting your config.

**Comment by 3DKaii** [comment]
Setting my Pex debug to false in the config seems to have fixed it for now. Thank you!
