### ISSUE TITLE
[Feature] Conditional Nametags

### ISSUE THREAD

**Issue by NegativeKB** [NEZNAMY/TAB#531]
If this is already a feature please point me to the right documentation for this. If not, I would definitely love to see this become a feature if possible! We already have conditional scoreboards and tablists. I would definitely love to see conditional nametags and names in the tablist!

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/158610191-d11579ab-99fa-4620-b980-34694a485db3.png)
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders

**Comment by Tanguygab** [comment]
feature requests are currently closed, howewer, my TAB-Additions plugin supports conditional nametags https://github.com/Tanguygab/TAB-Additions/releases/

**Comment by NegativeKB** [comment]
Ah. So sorry! Thank you.
