### ISSUE TITLE
the tab list becomes weird

### ISSUE THREAD

**Issue by Xing-C** [NEZNAMY/TAB#533]
### Server version

paper-1.18.1

### TAB version

3.1.0

### Stack trace

I didn't see the error log.

In version 1.12.2, the tab list works normally

But when working in version 1.18.1, it becomes weird, the left side is always repeated, and the order is incorrect

The tab list is implemented through Waterfall

### Steps to reproduce (if known)

I didn't see the error log

### Additional info

![126](https://user-images.githubusercontent.com/39401415/159123547-d60703a7-b6f9-4cad-b009-8541c3924788.jpg)
![12326](https://user-images.githubusercontent.com/39401415/159123551-71b0dd4c-90d4-47f1-9692-3cdd0e1e4c6f.jpg)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
check /teams list

**Comment by Xing-C** [comment]
Yes, I try to check the team list
And tried to delete all teams, but the problem was not solved
I can only see this when I press tab

![image](https://user-images.githubusercontent.com/39401415/159127478-d87bc0f2-2689-4b37-9eda-a03e10965595.png)

**Comment by NEZNAMY** [comment]
Deleting team LD_NoName will solve it.

**Comment by Xing-C** [comment]
I restarted the server, but it didn't get better
![0O)K_)SYLC4HYTTZ`~ X@ V](https://user-images.githubusercontent.com/39401415/159127851-6bbc040a-5278-4a95-8d93-65d869efa142.png)

**Comment by NEZNAMY** [comment]
Is the issue still there?

**Comment by Xing-C** [comment]
The problem remains 😥

**Comment by NEZNAMY** [comment]
The core of the issue is that some plugin registers a team with a dummy player with empty name, which is the same name TAB uses for the fake players to make them not appear in autocomplete in chat. There is no efficient solution to this, other than reverting to original names, but that would introduce unwanted autocomplete in chat, which others wouldn't want. You will need to find out which plugin does that and solve it.

**Comment by Xing-C** [comment]
It looks like a conflict. I'll try to eliminate the problem
If the problem is solved, I'll let you know. Thank you

**Comment by Xing-C** [comment]
@NEZNAMY  Hi.
The problematic plug-in is multiverse-core-v4.3.2
It's the latest version. I don't know what to do...
version: 4.3.2-SNAPSHOT-b870

**Comment by NEZNAMY** [comment]
Multiverse is not the cause, but teams stored in your main world.

**Comment by NEZNAMY** [comment]
Can we look into this again @Xing-C ?

**Comment by NEZNAMY** [comment]
We know the cause and there is nothing efficient I can do to solve this without creating even more problems (such as changing player names and cause them to appear in chat complete). 
Added this info to the wiki https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Layout#additional-note-4---incompatibility-with-other-plugins
