### ISSUE TITLE
On startup and join placeholder issue

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#535]
### Server version

Paper 1.18.2

### TAB version

3,1.0

### Describe the bug

if i restart the server and join all placeholders from tab will not be refreshed.

### Expected behavior

everything should be refreshed

### Steps to reproduce

1. Restart server
2. join on server
3. see issue
4. [https://just-paste.it/tmv54rydY3](https://just-paste.it/tmv54rydY3)

### Additional info

[https://just-paste.it/tmv54rydY3](https://just-paste.it/tmv54rydY3)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
#522

**Comment by NEZNAMY** [comment]
Fixed.
