### ISSUE TITLE
when you go to this version 1.13.2

### ISSUE THREAD

**Issue by Melvin3332** [NEZNAMY/TAB#536]
### Server version

1.13.2

### TAB version

TAB.v3.1.0.jar

### Describe the bug

when I join this version  1.13.2  when I join my hub I saw this ![This is an image](https://cdn.discordapp.com/attachments/952192178652840046/956762239807926352/2022-03-25_13.49.43.png)
hopefully it's not a bug and you can update it

it works fine with 1.1.8 I do want to support other versions

### Expected behavior

when I join this version  1.13.2  when I join my hub I saw this ![This is an image](https://cdn.discordapp.com/attachments/952192178652840046/956762239807926352/2022-03-25_13.49.43.png)
hopefully it's not a bug and you can update it

it works fine with 1.1.8 I do want to support other versions

### Steps to reproduce

I believe it's Minecraft version

### Additional info

no

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That's all? No description whatsoever, just a random screenshot?

**Comment by Trinchezito** [comment]
Is your server using hex colors? If so, that's why.

**Comment by NEZNAMY** [comment]
Also send plugin list.

**Comment by NEZNAMY** [comment]
Closing due to insufficient info and inactivity from user.
