### ISSUE TITLE
Players can disappear from the Tab list when reconnecting too quickly

### ISSUE THREAD

**Issue by DaMarine** [NEZNAMY/TAB#539]
### Server version

Bungeecord 1.18.2, connecting two Paper 1.18.2 servers

### TAB version

3.1.0

### Describe the bug

Players who connect and disconnect then reconnect again in a very quick period of time can leave the TAB plugin thinking a player is offline when they are not.

### Expected behavior

Tab should be an accurate reflection of the players currently connected to the server.

### Steps to reproduce

1. Launch two Minecraft clients logged onto the same account
2. Join a server on both clients as quickly as possible
3. One client will log in first, then be promptly kicked off by the joining of the other client.
4. If the issue occurs, you will not be visible on the Tab list.

### Additional info

Code analysis from one of our admins:

The issue seems to be that `PlayerDisconnectEvent` does not necessarily precede a `ServerSwitchEvent` (representing a new join), however a `ServerDisconnectEvent` does. So changing [`BungeeEventListener#onQuit`](https://github.com/NEZNAMY/TAB/blob/master/bungeecord/src/main/java/me/neznamy/tab/platforms/bungeecord/BungeeEventListener.java#L29) to use `ServerDisconnectEvent` instead of `PlayerDisconnectEvent` should fix the issue.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
So you are using TAB on paper, but think changing bungee code will solve it?

**Comment by DaMarine** [comment]
Made our server arrangement clearer in the version setup.

**Comment by NEZNAMY** [comment]
Bungeecord declines connections with names of already connected players, at least it did last time I checked. Because of that, joining with two accounts at the same time will only let 1 account in, which isn't a problem I believe.

**Comment by DaMarine** [comment]
We've definitely been able to reproduce it with that in the past, but the same scenario can be seen just by disconnecting and reconnecting quick enough with the same account.

**Comment by NEZNAMY** [comment]
Are you using global playerlist feature?

**Comment by DaMarine** [comment]
We are, yep

**Comment by NEZNAMY** [comment]
Try without it.

**Comment by NEZNAMY** [comment]
Try https://github.com/NEZNAMY/TAB/actions/runs/2054301587
