### ISSUE TITLE
Per World Playerlist does not allow private messaging

### ISSUE THREAD

**Issue by Leomelonseeds** [NEZNAMY/TAB#541]
### Server version

git-Paper-267 (MC: 1.18.2)

### TAB version

3.1.0

### Describe the bug

Not sure if this is fixable or has been mentioned in the wiki. Players are unable to private message other players in different worlds through essentials when the per world playerlist option is enabled. The players don't show up in tab-complete, and essentials gives a "player not found" error when attempting to send a message.

### Expected behavior

Players should be able to message others across the server. This is useful for players who want others to join the same world as them, as presumably per world chat would be enabled from some other plugin given the per world playerlist feature.

### Steps to reproduce

1. Install EssentialsX and TAB
2. Enable per-world-playerlist.enabled and reload
3. Attempt to message a player in a different world

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Could be an esssntials feature. Have you tried vanilla private messaging?

**Comment by NEZNAMY** [comment]
https://github.com/EssentialsX/Essentials/blob/1e0d7fb0a3545d15c3b0cc1d180b47551f98cb22/Essentials/src/main/java/com/earth2me/essentials/commands/EssentialsLoopCommand.java#L79 Indeed an essentials feature.

**Comment by Leomelonseeds** [comment]
Oh I see, thank you for bringing this to my attention, apologies for not looking into it further.
