### ISSUE TITLE
Per world scoreboard conditions didn't work.

### ISSUE THREAD

**Issue by SwartZCoding** [NEZNAMY/TAB#542]
### Server version

Spigot 1.18.1

### TAB version

3.1.0

### Describe the bug

When i put conditions for scoreboard like this, all scoreboard desappear : 
`scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  disable-in-worlds:
  - disabledworld
  delay-on-join-milliseconds: 0
  scoreboards:
    scoreboard1:
      display-condition: "%world%=SuperiorWorld;%world%=SuperiorWorld_nether;%world%=SuperiorWorld_the_end"
      title: 堂
      lines:
      - ''
      - ''
      - <#9066EB>&l%player_name%</#FF9301>
      - ' &#FFBD1C▪ &fGrade: %earthbasics_rank%'
      - ' &#FFBD1C▪ &fArgent: #FFBD1C%vault_eco_balance_formatted% &r㊋'
      - ' &#FFBD1C▪ &fShell: #FFBD1C%earthsky_money% &r杓'
      - ' &#FFBD1C▪ &fCrédits: #FFBD1C%earthsky_credits%&r二'
      - ''
      - <#9066EB>&lVotre île</#FF9301>
      - ' &#B599F3▪ &fNiveau: #B599F3%superior_island_level_int%'
      - ' &#B599F3▪ &fRang: #B599F3#%superior_island_top_level_position%'
      - ' &#B599F3▪ &fMembres: #B599F3%superior_island_team_size_online%&f/#B599F3%superior_island_team_size%'
      - ' &#B599F3▪ &fEre : %earthsky_ere_name%'
      - ''
      - '    俺'
    default:
      title: 堂
      lines:
      - ''
      - ''
      - <#9066EB>&l%player_name%</#FF9301>
      - ' &#FFBD1C▪ &fGrade: %earthbasics_rank%'
      - ' &#FFBD1C▪ &fArgent: #FFBD1C%vault_eco_balance_formatted% &r㊋'
      - ' &#FFBD1C▪ &fShell: #FFBD1C%earthsky_money% &r杓'
      - ' &#FFBD1C▪ &fCrédits: #FFBD1C%earthsky_credits% &r二'
      - ''
      - ' &#FF6E44▪ <#FFF1D8>VoteParty</#FF6E44>: #FD9F5B%earthevents_voteparty_current%&f/#FD9F5B%earthevents_voteparty_max%'
      - ''
      - '    &f俺'
    largageboard:
      display-condition: "%world%=largage"
      title: 堂
      lines:
      - ''
      - ''
      - <#9066EB>&l%player_name%</#FF9301>
      - ' &#FFBD1C▪ &fGrade: %earthbasics_rank%'
      - ' &#FFBD1C▪ &fArgent: #FFBD1C%vault_eco_balance_formatted% &r㊋'
      - ' &#FFBD1C▪ &fShell: #FFBD1C%earthsky_money% &r杓'
      - ' &#FFBD1C▪ &fCrédits: #FFBD1C%earthsky_credits% &r二'
      - ''
      - <#9066EB>&lLargage</#FF9301>
      - ' &#DE29CD▪ &fRestants: #DE29CD%earthevents_largage_left%&f/#DE29CD%earthevents_largage_max%'
      - ''
      - ' &#FF6E44▪ <#FFF1D8>VoteParty</#FF6E44>: #FD9F5B%earthevents_voteparty_current%&f/#FD9F5B%earthevents_voteparty_max%'
      - ''
      - '    &f俺'`

### Expected behavior

I want a specific scoreboard for each worlds add to the configuration. I already follow the documentation, but i don't think forgot something.

### Steps to reproduce

Just put this config on your and try

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You did not read the wiki, it **is** an issue with your configuration. See conditions page on how to make an OR condition. You are trying to use AND type, which doesn't for in your case.

**Comment by SwartZCoding** [comment]
> You did not read the wiki, it **is** an issue with your configuration. See conditions page on how to make an OR condition. You are trying to use AND type, which doesn't work in your case.

Ok, i close this. But check about your convert of previous config, because it's when i convert this is generate.
