### ISSUE TITLE
unlimited-nametag-mode: true causes animations to slow down

### ISSUE THREAD

**Issue by BakiDance** [NEZNAMY/TAB#543]
### Server version

Paper 1.18.2

### TAB version

3.1.0

### Describe the bug

With unlimited-nametag-mode set to true in 1.18.2, animations in the tab list become extremely choppy. Disabling this setting "fixes" the issue. I cannot replicate this bug in 1.18.1 with the same plugin list.

### Expected behavior

Animations in the tab list shouldn't be affected by the setting of unlimited-nametag-mode.

### Steps to reproduce

Have an animation that refreshes at 100 to 150, then enable unlimited-nametag-mode. Animations will become noticeably choppier.

### Additional info

I cannot reproduce this with the default config and animations, so this may be an issue with my configuration. However, this issue did not affect me on 1.18.1 or on TAB 3.0.1 on a previous server with the same config. I've attached my files for reference.

[TAB.zip](https://github.com/NEZNAMY/TAB/files/8376960/TAB.zip)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
I tried your configuration and everything looks good to me. Is there a chance the plugin was overloaded? Check with /tab cpu

**Comment by BakiDance** [comment]
I ran the /tab CPU command as instructed. The results are as follows:
![image](https://user-images.githubusercontent.com/43658058/161154763-141fcdb0-7aad-4188-a1f6-dcbc26df7a26.png)
![image](https://user-images.githubusercontent.com/43658058/161154794-75bed2af-2f81-4209-8420-82855b03e90f.png)

I'm currently testing this without any other plugins loaded, and the result are the same.

**Comment by NEZNAMY** [comment]
Fixed in 3.1.1
