### ISSUE TITLE
Can't figure out how to put dummy objectives in scoreboard

### ISSUE THREAD

**Issue by SkarMC** [NEZNAMY/TAB#544]
How do I put a dummy objective in the scoreboard where like %statistic_deaths% would be

**Comment by SkarMC** [comment]
also how would I set display condition to a group?

**Comment by NEZNAMY** [comment]
Github issues are not for support.

**Comment by SkarMC** [comment]
> Owner

sorry I forgot to add a label and I couldn't find an actual support location

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB#links support for buyers is on discord.
