### ISSUE TITLE
customtabname and customtagname not work

### ISSUE THREAD

**Issue by xNikees911** [NEZNAMY/TAB#546]
### Server version

Spigot paper 1.17.1

### TAB version

TAB-3.1.1-pre2

### Describe the bug

Hi, customtagname and customtabname in groups.yml not work for me. I change it to display placeholder from CMI %cmi_user_display_name% to get other colors than default for ranks and it's not work.

In config.yml I have enabled this:
scoreboard-teams:
  enabled: true
  
unlimited-nametag-mode:
    enabled: true
    
Also in database I see this placeholders: 
![image](https://user-images.githubusercontent.com/89745544/161081234-1d6ba1a9-41f1-47b9-ae42-ae38e9ee8278.png)

When I check it by /papi parse me %cmi_user_display_name% command it's shows this what I want, my default nickname and changed nickname for &6&l color but on tab it's not changed. 

With &6&lxNikees911 nickname and without any colors in my nick tab will not change.
![image](https://user-images.githubusercontent.com/89745544/161082029-c2f0401c-82f7-41ba-8357-5a9049f339c4.png)

### Expected behavior

I wrote above.

### Steps to reproduce

I wrote above.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by xNikees911** [comment]
I updated to your latest dev version and still not working. Database changed for _DEFAULT_ but nick names still not refresh for custom names on tab. Didn't changed anything in configs still same like i wrote above.

**Comment by xNikees911** [comment]
![image](https://user-images.githubusercontent.com/89745544/161127114-c5d24c47-51be-469d-abf0-2ade07fea220.png)

**Comment by NEZNAMY** [comment]
Try again.
