### ISSUE TITLE
LuckPerms weight

### ISSUE THREAD

**Issue by 2x2x2x2x2** [NEZNAMY/TAB#547]
### Server version

Paper 1.18.1

### TAB version

3.1.0

### Describe the bug

Hello I have issue
Players displays in wrong priority 

![image](https://user-images.githubusercontent.com/96422956/161123676-e3ce3164-e69c-46b8-afb4-f1defe068ea2.png)
![image](https://user-images.githubusercontent.com/96422956/161123466-f4a139f2-6c38-499c-9668-eecbb37026f2.png)
If I did ranks or weights wrong please tell me 

### Expected behavior

I want to display players in good priority like 
1. Owner
2. Admin
3. Mod
4. Default

### Steps to reproduce

I dont know I just installed it

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist

**Comment by 2x2x2x2x2** [comment]
Really sorry
