### ISSUE TITLE
Crash when using the scoreboard

### ISSUE THREAD

**Issue by Serega007RU** [NEZNAMY/TAB#549]
### Server version

Mohist 1.12.2

### TAB version

3.1.1

### Stack trace

[crash-2022-04-03_01.16.35-client.txt](https://github.com/NEZNAMY/TAB/files/8403459/crash-2022-04-03_01.16.35-client.txt)

### Steps to reproduce (if known)

Step 1: Enable `scoreboard-teams` `enabled` to `true`
Step 2: Reload the plugin `/tab reload` or restart the server
You will get this crash on the client

### Additional info

Client logs [latest.log](https://github.com/NEZNAMY/TAB/files/8403467/latest.log)

It also seems to crash when using a simple scoreboard (not teams)

### Checklist

- [x] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What if you add `unregister-before-register: false` into config.yml?

**Comment by Serega007RU** [comment]
Adding `unregister-before-register: false` to `config.yml` helped, I think the problem is solved

**Comment by NEZNAMY** [comment]
The function will be removed in the next version entirely, hopefully without any side effects.
