### ISSUE TITLE
Prefix's and Suffix's not showing

### ISSUE THREAD

**Issue by OhhGeeCluster** [NEZNAMY/TAB#550]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Describe the bug

Tab & Tag prefix/suffix not being recognized causing no formatting to occur in the player list. 

![image](https://user-images.githubusercontent.com/101496280/161486104-9924b8e0-6918-43e3-9e60-71e72c047ccb.png)

It is properly configured in the groups.yml as follows 

![image](https://user-images.githubusercontent.com/101496280/161486282-998f5afb-d25d-4e1d-8d27-c3bcd3abc4ee.png)

With /tab deug. I get

![image](https://user-images.githubusercontent.com/101496280/161486359-7a339802-e6b0-4924-8c78-219b543a0ccc.png)

### Expected behavior

There should be entries under tabprefix & tagprefix according to the configuration.

### Steps to reproduce

I have no proper information to reproduce as I simply did `/tab reload` to refresh the tab quicker.
I did not touch any config files prior and was working just fine

### Additional info

I have the permission: `tab.group.owner` assigned to the owner group in luckperms.

Tab on bungee is configured nearly the same to paper side.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Disable mysql.

**Comment by OhhGeeCluster** [comment]
I have disable mysql on both now. And its still not showing. 
I originally had it disabled. But I thought it would help.

**Comment by NEZNAMY** [comment]
Show new debug output after disabling mysql.

**Comment by OhhGeeCluster** [comment]
debug after:

/tab debug
![image](https://user-images.githubusercontent.com/101496280/161518844-0e6889f9-6223-48be-aacb-201865fcd013.png)


/btab debug
![image](https://user-images.githubusercontent.com/101496280/161518895-3c8ec589-d79c-4f46-b1b2-8f549f7ff47f.png)

**Comment by NEZNAMY** [comment]
Well there you go. You can't have the plugin installed on both. Pick one and remove the plugin from the other one.

**Comment by OhhGeeCluster** [comment]
So TAB can only be installed on Bungee side or Paper Side?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Installation yes

**Comment by OhhGeeCluster** [comment]
Well okay then. Strange its worked up until now. 

I cant seem to get placeholders (which grabs it from a specific server) to work on bungee end :\

But I'm trying to utilize global tab list from everything under bungee. 

Is there a workaround this?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-set-up-PlaceholderAPI-support-on-bungeecord
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Global-playerlist

**Comment by OhhGeeCluster** [comment]
Yeah nvm I got it. Thank you so much.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer#per-world--per-server
