### ISSUE TITLE
Tab wont load unless you reload the plugin

### ISSUE THREAD

**Issue by zino7** [NEZNAMY/TAB#553]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Describe the bug

Hi, so basically i have downloaded the new version and when a player joins the server tab wont load for them. The only way to load the tab is to reload the plugin.

### Expected behavior

The previous versions they were fine but now the tab wont load unless i reload it. We changed nothing in the config.

### Steps to reproduce

Join the server nothing will show up
/tab reload
[12:05:26 INFO]: [PlaceholderAPI] Successfully registered expansion: tab [3.1.1]
[12:05:28 INFO]: [TAB] §aEnabled in 1192ms
[12:05:28 INFO]: [TAB] §3[TAB] Successfully reloaded

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Plugin loads for me and everyone else. Please provide more steps.

**Comment by zino7** [comment]
Hi thanks for the quick support. I have rolled back to 3.1.0 version and everything is fine now. With the new version there is no error or anything just the plugin wont load until its reloaded.

**Comment by NEZNAMY** [comment]
Try on a clean server with no other plugins. I need more info to reproduce and fix this issue.

**Comment by zino7** [comment]
I think my developer found out why. He searched the code and this is what he found. [https://cdn.discordapp.com/attachments/959881248753475605/961245966357368872/unknown.png](Link to screenshot)

**Comment by NEZNAMY** [comment]
What's the problem with that? It iterates all players on top of that, so it's some load code, not join processing.

**Comment by zino7** [comment]
Hi, i tried it in my lobby and it has no issue. I dont know what is causing the error. The plugin will disable itself after few minutes.

**Comment by NEZNAMY** [comment]
Send disable message. This must be a conflicting plugin, it's your mission to find out which one it is.

**Comment by zino7** [comment]
I have tried everything possible, it doesnt show any error in the console or anywhere. After few minutes the tab will not show up and i have to reload it. I will start disabling the plugins one by one to check which plugin is causing this mess

**Comment by zino7** [comment]
Found this >....[22525.884s][warning][gc,alloc] TAB Processing Thread: Retried waiting for GCLocker too often allocating 4541448 words

**Comment by NEZNAMY** [comment]
Does the plugin stop working at that time?

**Comment by NEZNAMY** [comment]
Any news @zino7 ?

**Comment by NEZNAMY** [comment]
Sounds related to #560, assuming the change fixes this one as well due to inactivity from user.
