### ISSUE TITLE
Prefix syncronisation with LP Bungee

### ISSUE THREAD

**Issue by SwartZCoding** [NEZNAMY/TAB#554]
### Server version

Pufferfish 1.18.1

### TAB version

3.1.0 Bungee

### Describe the bug

I have an issue with luckperms prefix change on tab on bungeecord tab version. When i change my rank with luckperms bungee, tab doesn't refresh. I always need to disconnect & reconnect to change it.

### Expected behavior

Default config with placeholders enabled.

### Steps to reproduce

Make a tab setup for Bungeecord. Use Luckperms bungee.

Set you to a specific group like admin. Check the tab for Admin Prefix.

Now change Admin rank for a default rank.

Tab doesn't got updated and you are always admin for tab. If you disconnect & reconnect, now you are default.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Fixed in 3.1.1.
