### ISSUE TITLE
Paper console colors not working

### ISSUE THREAD

**Issue by HexedHero** [NEZNAMY/TAB#555]
### Server version

1.18.2

### TAB version

3.1.1

### Describe the bug

Console colors not working in Paper

[17:01:21 INFO]: [TAB] Enabling TAB v3.1.1
[17:01:21 INFO]: [TAB] §7Server version: 1.18.2 (v1_18_R2)
[17:01:21 INFO]: [TAB] §7Loaded NMS hook in 12ms
[17:01:21 INFO]: [PlaceholderAPI] Successfully registered expansion: tab [3.1.1]
[17:01:21 INFO]: [TAB] §aEnabled in 89ms

You need to use the console command sender not the logger for colors to work in latest Paper.

### Expected behavior

Colors to work

### Steps to reproduce

Start the server.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Does paper no longer encourage to use logger? When did that happen?

**Comment by NEZNAMY** [comment]
It still says to use logger.
![image](https://user-images.githubusercontent.com/6338394/162259379-6ddae98b-065a-4585-9f2e-f706f7cd5318.png)

**Comment by 4drian3d** [comment]
Paper still recommends using the Logger instead of System.out, but for messages with colors, it recommends using ConsoleCommandSender#sendMessage

**Comment by NEZNAMY** [comment]
Which will break cross-platform code. Alright then, removing colors from plugin's messages.
