### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#557]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Stack trace

https://just-paste.it/692M4zQiaL

### Steps to reproduce (if known)

Starting server
2. Error occured

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
@supermem99 try https://github.com/NEZNAMY/TAB-Bridge/actions/runs/2141102103

**Comment by supermem99** [comment]
where can i download the file?

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/162583738-36490c6a-7072-47e7-83d9-24a17743ba31.png)

**Comment by NEZNAMY** [comment]
Any news @supermem99 ?

**Comment by supermem99** [comment]
Works for me Up to now. Thx
