### ISSUE TITLE
Colors in tab messed up

### ISSUE THREAD

**Issue by dooglz42** [NEZNAMY/TAB#558]
### Server version

Purpur 1.18.2

### TAB version

3.1.1

### Describe the bug

The  colors of prefixes are green and black
![image](https://user-images.githubusercontent.com/103332410/162587417-44be04b5-2824-4d6b-b86c-81640194c43e.png)

### Expected behavior

The prefix should be white and gold
![image](https://user-images.githubusercontent.com/103332410/162587539-fb24d28a-f00b-4ce8-b026-cfaa5b7ebe24.png)

### Steps to reproduce

Make a group with luckperms that has a colored prefix

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
So it's a bug that you didn't remove default group override for `owner` group in groups.yml?

**Comment by dooglz42** [comment]
oh sorry I didn't know that existed, I'm new to server stuff
