### ISSUE TITLE
[Unlimited nametags] Name tag positioning intermittently too low when mounted on horse

### ISSUE THREAD

**Issue by pgmann** [NEZNAMY/TAB#56]
**Server version**
1.14.4

**Plugin version** ("latest" is not a version)
2.5.4-pre2

**Describe the bug**
Tag name is too low down when riding a horse sometimes, it alternates between the right position and being inside the player's head

**How to reproduce**
Mount a horse

**Expected behavior**
Tag name displayed at correct height above player head

**Actual behavior**
Tag name is displayed inside the player's head (i.e. y co-ordinate is too low). This alternates between the right height and wrong height at intervals, usually every 2-3 seconds.

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/5852501/66704639-bba8aa80-ed15-11e9-971f-abd9688676fe.png)

**Comment by NEZNAMY** [comment]
Are you able to reproduce this on other server versions, such as 1.8.x ?

**Comment by pgmann** [comment]
Just tested this on a fresh 1.13 server with unlimited nametag mode on and abovename and belowname set. Worked perfectly.

Then tried the same on a fresh 1.14 server with unlimited nametag mode on and abovename and belowname set. Was able to reproduce the bug as reported above.

**Comment by pgmann** [comment]
Also tested with no abovename/belowname set and was still able to reproduce on 1.14.4.

When unlimited nametag mode is off everything works as it should, as you would expect.

**Comment by pgmann** [comment]
For reference, here's the video showing the player's y location in the nametag:
https://streamable.com/u658l

**Comment by pgmann** [comment]
Still present in 1.15.1

![image](https://user-images.githubusercontent.com/5852501/71107409-ee10d100-21b8-11ea-8bfc-09fda7f08c8d.png)
