### ISSUE TITLE
ArmorStandManager NPE

### ISSUE THREAD

**Issue by chistian95** [NEZNAMY/TAB#560]
### Server version

Paper 1.18.2 (283)

### TAB version

3.1.1

### Describe the bug

Whenever I try to set a player tag, the following error occurs: 
https://pastebin.com/KcLfK7fA

I have the advanced tag setting set to true
I have also tried to add the suggested "TAB-Bridge" plugin in #557

### Expected behavior

Being able o set player tags

### Steps to reproduce

Start the server
Run any /tab player <property> <value>

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/162612467-4fbb0e7d-5ffc-45b2-beb4-35ef0702c990.png)
works for me with steps you provided

**Comment by chistian95** [comment]
Hmmm it's weird. It doesn't happen every time. It's random. Sometimes works, sometimes it doesn't...
I'm trying to narrow it down

**Comment by NEZNAMY** [comment]
Try new build from actions.

**Comment by chistian95** [comment]
I think it's not working fine yet. Now instead of randomly showing errors it just stops working and does nothing. 
Randomly after 10 minutes or so the plugin will stop working. Now instead of throwing an error when trying to set a tag, it just does nothing instead.

Running /tab reload solves the issue and tags starts working again but that sometimes leaves "phantom" armorstands floating around with player names

**Comment by NEZNAMY** [comment]
The whole plugin will stop working?

**Comment by chistian95** [comment]
I think so, yes. If I try to set a tag of any of the players it just doesn't do anything at all. There are no errors in the console though, wich is weird

**Comment by NEZNAMY** [comment]
Enable debug in config and check console output on join if it says join processing was successful.

**Comment by chistian95** [comment]
Sorry for the late reply. I've enabled the debug mode. I can see the debug messages every time except when this bug occurs. When I execute the /tab command while the bug is happening, nothing happens. No error, no debug message, nothing.

I've seen that there is no armor stand riding the affected players and that sometimes there are some "phantom" armor stands left behind floating at random locations. Maybe that can give you enough hints

**Comment by NEZNAMY** [comment]
Can you send console output of a case where it doesn't load the player?

**Comment by chistian95** [comment]
https://pastebin.com/MX3qFTfD

**Comment by NEZNAMY** [comment]
Can you join discord? I will send you a jar to test.

**Comment by NEZNAMY** [comment]
User became inactive, commit linking this does as much as possible with available information. Delaying plugin's commands on join solved this.
