### ISSUE TITLE
Question: How to make scoreboard being visible in a different bungee servers?

### ISSUE THREAD

**Issue by KahpotVanilla** [NEZNAMY/TAB#561]
For example, I want scoreboard1 to be shown in my lobby server

and for scoreboard2 in my Survival server

how do I do that?

**Comment by NEZNAMY** [comment]
Support is not provided in github issues.
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#example-1---per-world-scoreboards
