### ISSUE TITLE
Strange characters in the balance line

### ISSUE THREAD

**Issue by Henebis** [NEZNAMY/TAB#563]
### Server version

Spigot 1.12.2

### TAB version

3.1.1

### Describe the bug

![Screenshot_1](https://user-images.githubusercontent.com/103355650/162634908-9a476291-9579-43d2-9af1-f4143dd6bdea.png)
There is a balance issue in the sidebar.

### Expected behavior

It shouldn't be there.

### Steps to reproduce

%vault_eco_balance_commas%

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of /papi parse me %vault_eco_balance_commas%

**Comment by Henebis** [comment]
![image](https://user-images.githubusercontent.com/103355650/162635236-2b22345d-6091-4bf8-af04-c4934977868d.png)

**Comment by Henebis** [comment]
Perhaps a Vault?

**Comment by NEZNAMY** [comment]
No idea, but this is not a TAB issue.
