### ISSUE TITLE
Packet Armorstands with unlimited nametag stays in world

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#564]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Describe the bug

Random there appears Placeholder, which stays there without Spieler. That are packet armorstand.
[https://prnt.sc/GCzKBozpB_H9](https://prnt.sc/GCzKBozpB_H9) 

### Expected behavior

it shouldnt be packet issues. Fake Packets

### Steps to reproduce

1. Unlimited nametags on
2. start server
3. there is another issue which occurs:
4. in example there will be one placeholder which always stays there as placeholder and if i did /btab reload, it will be fixed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
So what is the issue? Armor stands without player or placeholders not parsing?

**Comment by supermem99** [comment]
both

**Comment by supermem99** [comment]
but the placeholder which wont parse, is in the abovenametag

**Comment by supermem99** [comment]
[https://prnt.sc/TDR8qMlh45Cp](https://prnt.sc/TDR8qMlh45Cp)

**Comment by NEZNAMY** [comment]
According to the error log you sent TAB is on bungeecord, but you said it's on paper?

**Comment by supermem99** [comment]
Yes its on bungee but i have tab bridge.
So waterfall and paper

**Comment by NEZNAMY** [comment]
Any steps to reproduce? You decided to use steps to "explain another issue".

**Comment by supermem99** [comment]
Actually we have to wait until it  appears another time. Unloadedplaceholder appeared before when all users joined at one time.

**Comment by NEZNAMY** [comment]
Any news on providing better steps @supermem99 ?

**Comment by supermem99** [comment]
Its mostly on above nametag  that Placeholder dont load

**Comment by NEZNAMY** [comment]
When do they not load?

**Comment by NEZNAMY** [comment]
Can you show bungeecord plugins @supermem99 ? Did you get errors.log file in TAB's folder?

**Comment by NEZNAMY** [comment]
@supermem99 try with latest TAB and bridge.
