### ISSUE TITLE
Blacklisted Server will not be blacklistet

### ISSUE THREAD

**Issue by supermem99** [NEZNAMY/TAB#565]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Describe the bug

Before some  versions of tab, the server i blacklisted were isolated and had their own tablist and scoreboard etc. but now, nothing will be blacklisted.

see my config.yml: [https://just-paste.it/LBcDnmTQv2](https://just-paste.it/LBcDnmTQv2)
groups.yml: [https://just-paste.it/CGj1v8nHwa](https://just-paste.it/CGj1v8nHwa
)
### Expected behavior

all server which i set as blacklistet, should be isolated from other server

### Steps to reproduce

1. Set Blacklisted server on gloal-list in config
2. start server
3. see tab from config everywhere

### Additional info

i didnt changed anything since then

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Global playerlist feature has no blacklist function.

**Comment by supermem99** [comment]
i mean `isolate-unlisted-servers: true` so it would be isolated. If i only add server-1 and server-2 to server-groups then all other server should be isolated.

**Comment by NEZNAMY** [comment]
Works fine for me. You didn't accidentally enable layout, right?

**Comment by supermem99** [comment]
No i didnt enable it.

**Comment by NEZNAMY** [comment]
Then you'll need to provide more info.

**Comment by supermem99** [comment]
i uploaded my config

**Comment by NEZNAMY** [comment]
It works fine for me with your config.

**Comment by supermem99** [comment]
i will create it, if i am sure with that. thx you
