### ISSUE TITLE
LuckPerms Prefix is not shown in Tab

### ISSUE THREAD

**Issue by Lix187** [NEZNAMY/TAB#566]
Hi,

sometimes it happens to me that I don't see the prefix from LuckPerms in TAB, on some of my servers it works on some it works, I don't understand it and they have the same configuration.

Sincerely,

Lix187 (LixTheYT)!

**Comment by NEZNAMY** [comment]
Invalid issue. Use one of the templates and provide any information that could actually be worked with.

**Comment by Lix187** [comment]
Mám poslať config.yml?

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/163461632-a7132592-f4fe-4baf-a03e-316160476749.png)
