### ISSUE TITLE
LuckPerms Prefix is not shown in Tab

### ISSUE THREAD

**Issue by Lix187** [NEZNAMY/TAB#567]
### Server version

Spigot 1.8.8

### TAB version

3.0.0

### Describe the bug

Hi,

sometimes it happens to me that I don't see the prefix from LuckPerms in TAB, on some of my servers it works on some it works, I don't understand it and they have the same configuration.

Sincerely,

Lix187 (LixTheYT)

### Expected behavior

The prefix should show

### Steps to reproduce

I don't know

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
" I am running latest version of the plugin"
"TAB version
3.0.0"

?

**Comment by NEZNAMY** [comment]
A ty mozes skusit poskytnut akekolvek informacie umoznujuce opravit chybu, ktora mozno uz je aj opravena, kedze si pol roka pozadu s aktualizaciami.

**Comment by Lix187** [comment]
Tú verziu som tam nedal ja, a nemusíš byť hneď toxic :/

**Comment by Lix187** [comment]
Takže hovoríš že mám dať 3.0.2

**Comment by NEZNAMY** [comment]
Tak 3x poviem nech poskytnes informacie lepsie ako "pomoc, plugin nefunguje" a stale nic.
Najnovsia bola 3.1.1 ked som sa naposledy pozeral.
Toto je miesto pre nahlasovanie chyb, nie podpora.

**Comment by Lix187** [comment]
A kde najdem podporu?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB#links ludom, ktori plugin zakupili a vyjadrili respekt nad 5 rokmi stravenymi nad vyvojom pluginu som ochotny pomoct s pluginom vo svojom volnom case.

**Comment by Lix187** [comment]
Tak to je super podpora....

**Comment by NEZNAMY** [comment]
Takze mam vo svojom volnom case nastavovat tisice serverov zdarma? Dobre to chapem?

**Comment by Lix187** [comment]
Wait, iba ty si team?

**Comment by NEZNAMY** [comment]
A kto by robil otroka zadarmo?

**Comment by Lix187** [comment]
idk?

**Comment by NEZNAMY** [comment]
Spravne.

**Comment by Lix187** [comment]
Hej, vážne sa tu teraz budeme hádať? Proste ukončil som ticket a idem hľadať na forách cs
