### ISSUE TITLE
Cant Sort Ranks (luckperms)

### ISSUE THREAD

**Issue by FakeMan1331** [NEZNAMY/TAB#569]
### Server version

Paper 1.18.1

### TAB version

3.1.1

### Describe the bug

When I set the weight for the ranks in LuckPerms, the rank sorting isn't respected in the tab. For example:
Mod Player3
Creator Player1
Co-owner Player 2

### Expected behavior

I want it to sort ranks by Luckperms weight factor

### Steps to reproduce

Setup ranks in luckperms.
Doesnt sort them.

### Additional info

https://i.imgur.com/2eXKCQ4.png

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of ` /tab debug <player>` of a player who is not sorted correctly.

**Comment by FakeMan1331** [comment]
> Show output of ` /tab debug <player>` of a player who is not sorted correctly.

https://i.imgur.com/hjo7d20.png

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/163602190-efe95e31-44c9-4630-b8c8-8703ecc552f2.png)

**Comment by NEZNAMY** [comment]
Why did you not put "creator" into sorting list?

**Comment by FakeMan1331** [comment]
> Why did you not put "creator" into sorting list?

its not my server and idk how to do that. I made the owner install TAB so idk if he messed up something.  I set the group as: /lp group creator setweight 2000

**Comment by NEZNAMY** [comment]
You don't know? Then why did you say you read the wiki while you didn't? What is the bug then?

**Comment by FakeMan1331** [comment]
> 

i did but i couldnt find anything

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist#sorting-by-primary-group

**Comment by NEZNAMY** [comment]
And what should I fix when the plugin works as expected?

**Comment by FakeMan1331** [comment]
> And what should I fix when the plugin works as expected?

im really sorry i was analizing it from the outside: basically i didnt have access to the config file anf the rank for the owner was called creator instead of owner. Im really sorry for wasting your time. Wont happen again.
