### ISSUE TITLE
Nametag issue

### ISSUE THREAD

**Issue by HitmanxTrev** [NEZNAMY/TAB#570]
### Server version

Paper Spigot 1.18.2

### TAB version

3.1.1

### Stack trace

There is no error message I just cant see nametags for some reason

### Steps to reproduce (if known)

not known

### Additional info

I am not able to see nametags if you need more info please message me on discord GalaxyLova#9513

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by DrWurzeli** [comment]
send your config and groups.yml
since noone else reported this, this is likely a configuration issue.

**Comment by HitmanxTrev** [comment]
This is my whole tab folder just wanted to add this just in case so you dont have to ask for anything else down the line
[groups.zip](https://github.com/NEZNAMY/TAB/files/8499534/groups.zip)

**Comment by DrWurzeli** [comment]
![javaw_SsYA6TBhgr](https://user-images.githubusercontent.com/54333442/163668519-201a5ed1-e239-4109-a3db-27e1bb74eb27.png)
works perfectly fine.
Make sure to read <https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-info> all of the wiki page before using a feature. hint included in screenshot.

**Comment by HitmanxTrev** [comment]
no it works for yourself but it doesnt work when you are looking at someone else for some reason

**Comment by NEZNAMY** [comment]
Disable unlimited nametag mode, it cannot work all by itself on bungeecord, it requires bridge plugin installed.

**Comment by HitmanxTrev** [comment]
fixed thanks it was working before when I had tab on every server then I just took it out and just put it on bungee so I was just confused on why it wasnt working thanks for helping me tho <3

**Comment by NEZNAMY** [comment]
I hope you will not use github issues for support again when readme says support is not provided here.
