### ISSUE TITLE
How do I move a line in an animation?

### ISSUE THREAD

**Issue by Henebis** [NEZNAMY/TAB#572]
Hello. How can I move a line in an animation. "\n" doesn't help.

**Comment by NEZNAMY** [comment]
Github issues are not for support.

**Comment by Henebis** [comment]
And what should I do?

**Comment by Tanguygab** [comment]
you should probably start by reading the readme
![image](https://user-images.githubusercontent.com/45695833/163690565-f4a3298b-9cc1-45d5-8f2c-051121b7d050.png)
