### ISSUE TITLE
Prefix in tab

### ISSUE THREAD

**Issue by mrksbgg** [NEZNAMY/TAB#573]
### Server version

Spigot 1.12.2

### TAB version

2.9.2

### Describe the bug

ok so i have an admin group (luckperms) and my alt has an group belower but when i set prefix to like lower (like group admin prefix moderator) im higher than my alt

### Expected behavior

fake prefix is gonna be belower

### Steps to reproduce

??

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
2.9.2 is very ourdated and completely unsupported.

**Comment by mrksbgg** [comment]
ahuel
