### ISSUE TITLE
Maven Repo is Down

### ISSUE THREAD

**Issue by linsaftw** [NEZNAMY/TAB#574]
### Server version

N/A

### TAB version

N/A

### Describe the bug

https://repo.kryptonmc.org/ is down and cannot compile plugins using TAB as dependency.

### Expected behavior

https://repo.kryptonmc.org/ working properly.

### Steps to reproduce

Compile a project that uses TAB as dependency.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by BomBardyGamer** [comment]
Sorry, that's my fault. I'm the one who hosts that, and I had my payment method set to manual and forgot to pay the bills on time. It's back up now. I'll try to make sure this doesn't happen again.

**Comment by linsaftw** [comment]
Thx. It's working.
