### ISSUE TITLE
Unable to turn off collision 

### ISSUE THREAD

**Issue by Lizapiz** [NEZNAMY/TAB#575]
### Server version

Spigot 1.17.1

### TAB version

3.1.1

### Describe the bug

For some reason when tab is loaded you are unable to turn off collisions. I am assuming the custom nametags are what cause this problem and I am sure it is TAB that is causing the problem. If you know a way to fix this or if this is a bug please tell me or fix it.

also I am using the minecraft /team command to disable collision if that helps 

### Expected behavior

You shouldn't be able to collide with other players

### Steps to reproduce

1. Put two players on a team using /team
2. Set CollisionRule on the team to never
3. You are still able to collide with the other player

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#introduction
