### ISSUE TITLE
Way to use text components?

### ISSUE THREAD

**Issue by sasha066** [NEZNAMY/TAB#577]
Hello, is it possible to somehow use json text components in TAB for prefixes? I mean, something similar that we can use in vanilla Minecraft, for example with the /tellraw command.

**Comment by NEZNAMY** [comment]
What would it offer that the plugin doesn't already?

**Comment by sasha066** [comment]
> What would it offer that the plugin doesn't already?

For example, in my case, I need Translate for my server resource pack. https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Translate

With it, I can for example make prefixes like on Origin Realms for those players who have a resource pack installed, or display normal text prefixes for those who do not have a resource pack. This is a very difficult thing to explain.

**Comment by NEZNAMY** [comment]
No, the plugin doesn't offer that. There are plugins handling some sort of translation already though.

**Comment by sasha066** [comment]
> No, the plugin doesn't offer that. There are plugins handling some sort of translation already though.


Okay, can you please tell me the names of these plugins? I've been trying to find something for a whole day, but I haven't found anything. =(

**Comment by NEZNAMY** [comment]
Triton

**Comment by sasha066** [comment]
> Triton

Thank you very much for the tip! Hope this helps me. Sorry to bother you with this. 😅
