### ISSUE TITLE
disable skin display in TAB

### ISSUE THREAD

**Issue by GroGaloraGran** [NEZNAMY/TAB#579]
### Server version

Paper 1.18.1

### TAB version

3.1.0

### Stack trace

none

### Steps to reproduce (if known)

hi sorry i dont know where else to ask this question
We want to sometimes turn off the display of the player's head in TAB but I can't find where to do it
please help and sorry for asking this question

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
player heads cannot be disabled without turning off the online-mode in server.properties, which you probably don't want to do. Also this is not a bug, and support is provided on our Discord server.
