### ISSUE TITLE
Reload TAB remove placeholders

### ISSUE THREAD

**Issue by Elikill58** [NEZNAMY/TAB#580]
### Server version

Spigot 1.8.8

### TAB version

3.1.1

### Describe the bug

After using `/tab reload`, all custom placeholders are removed

### Expected behavior

Not beeing removed

### Steps to reproduce

1. Declare placeholder. For example:
```java
PlaceholderManager pm = TabAPI.getInstance().getPlaceholderManager();
pm.registerPlayerPlaceholder("%color%", 100, (tp) -> {
	return ChatColor.GRAY;
});
```
2. Use it somewhere.
3. Do `/tab reload` and see it beeing replaced by the placeholders key and not value (like for the example: `%color%` instead of the color)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Elikill58** [comment]
> This is not a bug, but expected behavior. Reload command also reloads placeholder manager, so it doesn't refresh placeholders which are not used, not make refresh intervals update etc. Use events to listen to reload.

Oh ok.
Why not make like `/tab reload placeholders` or something ?

**Comment by NEZNAMY** [comment]
Because 99.99% of users will never use it?

**Comment by Elikill58** [comment]
But how many players will break something by reloading placeholders not reload-proof ? Why don't let placeholders reloadable without cleaning ? Because I just use the doc for API and I got this bug

**Comment by NEZNAMY** [comment]
Events exist for this exact purpose. Again, this is not a bug.

**Comment by Elikill58** [comment]
Ok, thanks for informations, and for this very great plugin !
