### ISSUE TITLE
Suggestion: Translate Enabled and Disabled placeholders

### ISSUE THREAD

**Issue by NoltoxGit** [NEZNAMY/TAB#581]
Hello !

I wanted to use the placeholders `%tab_scoreboard_visible%`, but I noticed that it was in English and you can't change the color.
Would it be possible to add in *__messages.yml__* the ability to translate the placeholder output?

Ty,
~ @NoltoxGit ~

**Comment by DrWurzeli** [comment]
this is a joke right?
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements

**Comment by NoltoxGit** [comment]
> use https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements anything else?

That's the value it serves with the `/papi parse me`, so I don't think it will work.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements#using-in-other-plugins

**Comment by NoltoxGit** [comment]
Thank you for help, it's work :D
