### ISSUE TITLE
Vanilla Teams

### ISSUE THREAD

**Issue by yunanmadenci** [NEZNAMY/TAB#583]
### Server version

Purpur-1614 (1.18.2)

### TAB version

3.1.1

### Describe the bug

When you drink potion of invisibility it makes you completely invisible.
![image](https://user-images.githubusercontent.com/103884633/166113342-45bdcd03-2e60-434e-8549-59201418138f.png)
![image](https://user-images.githubusercontent.com/103884633/166113356-a5afb663-2558-428e-b679-a20e2b61a722.png)
When you turn off the scoreboard-teams option it works normally
![image](https://user-images.githubusercontent.com/103884633/166113388-c348d032-7bbb-4582-91f3-abf13f44705a.png)
I am half invisible
![image](https://user-images.githubusercontent.com/103884633/166113406-1e51ada3-72be-4673-9017-624743f10585.png)
The problem is that you wont see your prefix above your head.
![image](https://user-images.githubusercontent.com/103884633/166113437-bb9b4b28-09ce-4c81-a17c-fcc91a3b98c6.png)

### Expected behavior

I’ve seen many servers (Hypixel etc.) that are using the vanilla team invisibility option with prefixes. It should work and show the prefix above.

### Steps to reproduce

1. Turn off scoreboard-teams option from config.
2. Join your server and apply invisibility to yourself, as you can see you are half invisible. (You may have to create a new team with /team command and join on it)
3. Turn on the scoreboard-teams option and /reload
4. Bam! Broken

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This is not a bug, TAB simply sets `canSeeFriendlyInvisibles` flag value to `false`. Changed to `true` now.
