### ISSUE TITLE
Tab causing server to crash

### ISSUE THREAD

**Issue by Aarpn** [NEZNAMY/TAB#584]
### Server version

winespigot 1.8

### TAB version

3.1.1

### Describe the bug

https://pastebin.com/9bZ5Ha1k - crash log

### Expected behavior

not crash server

### Steps to reproduce

idk, just updated to latest version and it started happening

### Additional info

none

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
The crash log does not mention TAB in any way. If TAB was spamming threads, it would get OOM as well. Did you get errors.log file in TAB's folder reporting OOM?

**Comment by Aarpn** [comment]
Yes, if you mean Out of memory, yes

**Comment by NEZNAMY** [comment]
Send the erro log.

**Comment by SwartZCoding** [comment]
Sorry for the up @NEZNAMY. I have the same issue when i use Tab Bridge + Tab. Since i just use tab only spigot side, i don't have any crash. I don't have any proof or anything to prove that. But i prefer to report it.

**Comment by NEZNAMY** [comment]
You did not report anything. Your report has no value.

**Comment by SwartZCoding** [comment]
> You did not report anything. Your report has no value.

That's what i said lol. But it's better to notice that.

**Comment by NEZNAMY** [comment]
I am not able to do anything with this.
