### ISSUE TITLE
Geyser player not apply name and prefix

### ISSUE THREAD

**Issue by MRuNanM** [NEZNAMY/TAB#586]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Describe the bug

I use Geyser plugin but tab plugin prefix and name not apply BE player

### Expected behavior

Not apply prefix or name

### Steps to reproduce

1. Set prefix or name to BE player
2. Not apply prefix or name

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
If it works on Java, it might be a Geyser issue.

**Comment by NEZNAMY** [comment]
Geyser developer was not able to reproduce this issue, do you have any further information available that could help us @MRuNanM ?

**Comment by NEZNAMY** [comment]
Closing due to inactive user & issue being out of plugin's control.
