### ISSUE TITLE
Tag of invisible potion player not showing to staff in spectate.

### ISSUE THREAD

**Issue by TomLewis** [NEZNAMY/TAB#587]
### Server version

Waterfall with TAB and PurPur 1.18.2

### TAB version

3.1.1

### Describe the bug

When players are invisible potion and staff are spectating them, they can no longer see their name above their head at all!  

### Expected behavior

For staff in spectate to see tag names above heads when players are invisible potion but staff are in spectate. 

### Steps to reproduce

Step 1. Player goes in invisible 
Step 2. Staff goes into spectate
Step 3. Try and see were invisible players are. 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Try disabling unlimited nametag mode. Hard to say without any info.

**Comment by TomLewis** [comment]
I dont have that enabled, I only have enabled:
https://gist.github.com/TomLewis/873d0d8bf1b279fe5ce1aaab811b6430

**Comment by NEZNAMY** [comment]
Try disabling scoreboard-teams.

**Comment by TomLewis** [comment]
Ah, that fixes it (Kind of) it shows their name in pure white!

So its a bug with `scoreboard-teams` then!

**Comment by Tanguygab** [comment]
from what I recall, in vanilla, Minecraft doesn't hide player nametags when you have the invisibility potion, 
though I think TAB does hide them ([it checks for the potion effect](https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/nametags/NameTag.java#L302)), which from what I understood @TomLewis doesn't want?

**Comment by TomLewis** [comment]
> from what I recall, in vanilla, Minecraft doesn't hide player nametags when you have the invisibility potion, though I think TAB does hide them ([it checks for the potion effect](https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/nametags/NameTag.java#L302)), which from what I understood @TomLewis doesn't want?

Correct. This is what its doing, its showing the Vanilla username in plain white when I disable `scoreboard-teams`. So there is something broken in `scoreboard-teams` that is preventing usernames showing when they have a potion enabled and staff are in gm3.



> More like a teams feature. Try using vanilla team commands if it still happens.
I'm not sure how to test this?

At least this narrowed it down so you will be able to figure out where/why.

**Comment by Tanguygab** [comment]
can you disable the scoreboard-teams feature in TAB, execute the following commands:
`/team add test`
`/team join test`
and then drink an invisibility potion and ask another player to look at you, and see the result?

**Comment by NEZNAMY** [comment]
Have you tried it @TomLewis ?
