### ISSUE TITLE
can u add mvdw placeholders support?

### ISSUE THREAD

**Issue by HazoYT** [NEZNAMY/TAB#588]
### Server version

spigot 1.8.9

### TAB version

3.0.2

### Describe the bug

is it possible to use mvdw placeholders with tab?

### Expected behavior

.

### Steps to reproduce

.

### Additional info

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
PlaceholderAPI supports it, see it's wiki for usage. This is not a bug.
