### ISSUE TITLE
[Question] Checking a placeholder exists?

### ISSUE THREAD

**Issue by TomLewis** [NEZNAMY/TAB#589]
Is it possible to see if a placeholder exists with conditions?
I have Tab on proxy and have survival & Creative, on surival I have PvPManager and have a placehodler to show when a players in combat as a replcement.
```
  "%pvpmanager_in_combat%":
    "yes": " &8[&cCombat %pvpmanager_combat_timeleft%&8]&r"
    "no": ""
```

This works fine, but I dont need/have PvPManager on Creative, so it just shows the empty text `%pvpmanager_in_combat%` I dont need/want to install the plugin just to remove this, is it possible to check if a placeholder exists in conditions? that also works with a `placeholder-output-replacements`.

**Comment by NEZNAMY** [comment]
```
  "%pvpmanager_in_combat%":
    "yes": " &8[&cCombat %pvpmanager_combat_timeleft%&8]&r"
    "no": ""
    "%pvpmanager_in_combat%": "Placeholder does not exist"
```
?

**Comment by TomLewis** [comment]
oh my god that's so simple.. I love it! Thank you! I didn't even think to check for just the text!
