### ISSUE TITLE
Add API method to hide players' nametags

### ISSUE THREAD

**Issue by Drc-DEV** [NEZNAMY/TAB#59]
Since TAB also handles nametags, it would be cool to have some api methods to handle them, in order to offer more compatibility to plugins that have similar features. 

I know there's already a method to hide a player's nametag from anybody, but there are none to hide them just for a bunch of players.

For example, a  method like:
`
hideNameTag(Player playerToHide, List<Player> players)`

where "playerToHide"'s nametag is hidden from "players"'.

and a method to show back a player's nametag

Use case: maybe you want to hide nametags of other factions' members and only see your own factions' nametags.

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Developer-API

/**
 * Makes player's nametag invisible until server restart/reload or /plugman reload tab
 * @param player UUID of player
 * @see showNametag 
 * @see hasHiddenNametag
 * @since 2.4.12
 */
public static void hideNametag(UUID player);

**Comment by NEZNAMY** [comment]
So this way you will add/remove players from the list every time someone joins/leaves ?
