### ISSUE TITLE
Crouch effect on unlimited nametags

### ISSUE THREAD

**Issue by PedroMPagani** [NEZNAMY/TAB#591]
### Server version

1.18.2

### TAB version

3.1.1

### Describe the bug

I'm opening as a BUG because I don't see a tag suggestion or something else
It's not specifically a bug, but the shadow effect on contrast of the custom armorstand name is not applied, since the mc client renders the shadow and contrast change only if its in front of a solid piece of pixel, did you manage to figure out if this is possible to somehow trick the minecraft client or, its impossible to replay the behavior of the player name on top of his head while on the CROUCH position

### Expected behavior

Shadow contrast

### Steps to reproduce

Crouch

### Additional info

Dev

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Armor stands copy the sneaking effect when players sneak. Do you have a video or something of it not working?
