### ISSUE TITLE
Bug: Error message from yaml

### ISSUE THREAD

**Issue by Dungjava** [NEZNAMY/TAB#592]
### Server version

Fiadelity 1.17.1

### TAB version

3.1.1

### Describe the bug

Sorry for my bad english 
Here is bug
![image](https://user-images.githubusercontent.com/99890979/167259009-869594e5-4252-4af8-9f72-5de590e8b135.png)
![image](https://user-images.githubusercontent.com/99890979/167259022-4ba53393-f475-4f7c-ac58-e54bbf3eceb3.png)
![image](https://user-images.githubusercontent.com/99890979/167259028-82bb0d2c-68ce-4a9e-9ee2-a360a5d4a0d0.png)
![image](https://user-images.githubusercontent.com/99890979/167259041-49c4bc76-d666-4442-8cf7-8dfa89e8f5ef.png)
![image](https://user-images.githubusercontent.com/99890979/167259056-17987dc8-c16c-4837-8f44-f3cdff002faa.png)
Full config: https://pastebin.com/rGL9tHWG

### Expected behavior

It's work fine but after reload once again and this plugin show error but i think it's bug

### Steps to reproduce

Step1: reload plugin

### Additional info

Bug when i reload plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
It's a plugin bug that you broke yaml syntax in your config?

**Comment by Dungjava** [comment]
> It's a plugin bug that you broke yaml syntax in your config?

yes

**Comment by NEZNAMY** [comment]
No.

**Comment by NEZNAMY** [comment]
Add `"` at the end of line 142 like the suggestions tell you and you will solve the misconfiguration on your end, which is not caused by the plugin.
