### ISSUE TITLE
[Question] Creating my own groups?

### ISSUE THREAD

**Issue by hanatic** [NEZNAMY/TAB#593]
I'm writing a plugin for my server and as part of it am using a custom permissions and rank system. For ease of use I hook into TAB's API but to work with tablist sorting I need to create groups. Can't find any reference to creating groups in the wiki - how do I go about this?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/TabPlayer.java#L283

**Comment by hanatic** [comment]
That's all working fine and it *seems* like the user's group is being assigned. The sorting list isn't sorting them though. Config:
```yaml
  sorting-types:
  - GROUPS:admin,team,mod,helper,creator,premium,default
```

**Comment by Tanguygab** [comment]
/tab debug <player>
execute this command with 2 players of different groups not sorted correctly

**Comment by hanatic** [comment]
Ah, that helped. It says my primary permission group is NONE now, although I do explicitly set the user's group. Will edit with code.

**Comment by hanatic** [comment]
Never mind, it was an issue on my end.
