### ISSUE TITLE
Enhancement: whitelist servers / * operator

### ISSUE THREAD

**Issue by iVillager** [NEZNAMY/TAB#594]
I would like to suggest a modify in TAB. 
In order to open more instances with the same name and to avoid having to add every time the instance name to the config in the blacklist section, it would be better to change  "disable-in-servers:" into "enabled-in-servers", so you can whitelist only interested servers. I would also suggest adding a * operator for every server that starts with the same name, for example: survival-* (catches all servers with survival-_<name>_) or dungeon* (catches all servers with dungeon_name_).

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/167319165-452c3d59-ae2c-412f-811d-e512c853517f.png)
???

**Comment by iVillager** [comment]
Sorry, I didn't know about that. What's about the * operator?

**Comment by NEZNAMY** [comment]
Not supported and feature requests are closed permanently.

**Comment by NEZNAMY** [comment]
Apparently it's already suported https://github.com/NEZNAMY/TAB/blob/master/api/src/main/java/me/neznamy/tab/api/TabFeature.java#L298-L337.
You would have saved so much of your time if you just tried it.
