### ISSUE TITLE
Geyser Scoreboard odd sorting

### ISSUE THREAD

**Issue by DuneSciFye** [NEZNAMY/TAB#596]
### Server version

Purpur 1.18.1

### TAB version

3.1.1

### Describe the bug

The scoreboard lines are sorted in alphabetical order for bedrock. Works fine for Java. Never happened with scoreboard revision so I’m thinking something with config is messed up.

### Expected behavior

Scoreboard looks normal 

### Steps to reproduce

1. Make a scoreboard
2. Join on bedrock

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by DuneSciFye** [comment]
![image](https://user-images.githubusercontent.com/65089425/167452207-22f60a27-1582-4d9b-9a11-53e18822c345.png)
Here is an image from one of my players

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/scoreboard/lines/ScoreboardLine.java#L158
https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/ITabPlayer.java#L106
Are you able to find out why did the check not pass?

**Comment by Tanguygab** [comment]
also, what's your Floodgate version?

**Comment by DuneSciFye** [comment]
I put the floodgate on the velocity proxy, that may be why

**Comment by Tanguygab** [comment]
yeah, there's not much we can do then, try enabling `use-numbers`  under the scoreboard configuration

**Comment by NEZNAMY** [comment]
Can't hook into a plugin that isn't installed, obviously. Enabling use-numbers option will solve it.

**Comment by DuneSciFye** [comment]
Alright thank you very much

**Comment by DuneSciFye** [comment]
I installed Floodgate on the subserver, restarted, but the issue still persists for bedrock. Or is use-numbers required for velocity and geyser compatibility?

**Comment by NEZNAMY** [comment]
Are you sure installation is correct and subserver instance is able to detect bedrock players still?
