### ISSUE TITLE
fast refresh

### ISSUE THREAD

**Issue by FakEEE14** [NEZNAMY/TAB#597]
### Server version

bungee 1.18.2

### TAB version

3.1.1

### Describe the bug

from this build
https://github.com/NEZNAMY/TAB/commit/3a4530c999bb374e321887327001b8f2b4ad8590
well ignore placeholderapi-refresh-intervals

### Expected behavior

to refresh like the number that given

### Steps to reproduce

just install the jar and set any placeholder to any cooldown

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send example configuration and output of /tab cpu.

**Comment by FakEEE14** [comment]
config:
https://pastebin.com/trCRYnG0

clip
https://user-images.githubusercontent.com/68513641/167474039-2d94f141-4a3f-4aef-9444-20b430ecaa10.mp4

`   [ TAB CPU Stats ]
CPU stats from the last 10 seconds

Top 5 placeholders:
%time% (500) - 0.013%
%luckperms-prefix% (1000) - 0.006%
%animation:MyAnimation1% (100) - 0.004%
%memory-used% (200) - 0.004%
%animation:web% (200) - 0.003%

Some internal separately measured methods:
sendPacket: 0.034%
Property#update: 0.015%
hasPermission: 0.002%

Features:
Header/Footer (0.069%):
    Updating header/footer - 0.069%
Refreshing placeholders (0.041%):
    Refreshing placeholders - 0.041%
    Updating placeholders - 0%
Permission group refreshing (0.005%):
    Refreshing groups - 0.005%
Packet deserializing (0.001%):
    ByteBuf - 0.001%

Packets sent by the plugin: 109
    Header/Footer - 109
Placeholders Total: 0.036%
Plugin internals: 0.08%
Total: 0.116%
            [ TAB CPU Stats ]`

**Comment by NEZNAMY** [comment]
Install the plugin on spigot as you are saying you use it and try again.

**Comment by FakEEE14** [comment]
i'm using bungee version 
should i change to spigot ?

**Comment by FakEEE14** [comment]
spigot version is fine
but bungee don't work

**Comment by NEZNAMY** [comment]
Then why did you say spigot? And are you sure it's since that commit?

**Comment by FakEEE14** [comment]
my bad sorry
yes i download newer and older build it's from that commit

**Comment by NEZNAMY** [comment]
It doesn't make sense, this looks like an issue with forwarding refresh interval to bridge. Can you try again?

**Comment by FakEEE14** [comment]
this https://github.com/NEZNAMY/TAB/actions/runs/2098847700 work fine

**Comment by NEZNAMY** [comment]
But the next commit does not do anything with refresh intervals nor bridge communication. Have you tried again?

**Comment by FakEEE14** [comment]
i try it again now

**Comment by FakEEE14** [comment]
yes that build don't respect the refresh numbers

**Comment by NEZNAMY** [comment]
The one you said that works?

**Comment by FakEEE14** [comment]
this https://github.com/NEZNAMY/TAB/actions/runs/2098847700
and older ones

**Comment by FakEEE14** [comment]
call me if any testing is needed

**Comment by FakEEE14** [comment]
my bad
i test the new build right now

**Comment by FakEEE14** [comment]
this is so wierd but puting it on high number like 10000
on startup is the same and don't respect the interval, but when you /btab reload it's start working
i test both last 2 build and are same

**Comment by NEZNAMY** [comment]
Can you try changing https://github.com/NEZNAMY/TAB/blob/671d60bd7233e921034b3fc2ac40ca568b23905e/shared/src/main/java/me/neznamy/tab/shared/proxy/ProxyPlatform.java#L93 to 
```
bridgePlaceholders.put(placeholder.getIdentifier(), refresh);
```
and compiling it?

**Comment by FakEEE14** [comment]
sorry i didn't saw the last comment
i try it tonight
