### ISSUE TITLE
pet name not showing

### ISSUE THREAD

**Issue by FZDNSZYT** [NEZNAMY/TAB#599]
### Server version

paper-409.jar

### TAB version

3.1.0

### Describe the bug

The name of the tame
![Uploading image.png…]()
d pet is not displayed, but I observed with the info mod that the setting is successful.

### Expected behavior

Showing pet names normally because I didn't enable [fix-pet-names]

### Steps to reproduce

This has been the case since 1.17.1

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
> because I didn't enable [fix-pet-names]
?
enable it and it'll show them

**Comment by Tanguygab** [comment]
> because I didn't enable [fix-pet-names]
?
enable it and it'll show them
as explained here
![Screenshot_20220515-111123_Opera.jpg](https://user-images.githubusercontent.com/45695833/168465610-58d8deb8-f4d8-449c-ab3f-56f7300ceacf.jpg)

also, you're outdated

**Comment by FZDNSZYT** [comment]
> > 因为我没有启用 [修复宠物名称]
> 
> ?启用它，它将按照此处的说明显示它们 ![Screenshot_20220515-111123_Opera.jpg](https://user-images.githubusercontent.com/45695833/168465610-58d8deb8-f4d8-449c-ab3f-56f7300ceacf.jpg)
> 
> 另外，你已经过时了
I've tried enabling it, but it still doesn't work

**Comment by Tanguygab** [comment]
after enabling the feature in the config, you need to do /tab reload, disconnect, and reconnect onto the server, did you do that?

**Comment by FZDNSZYT** [comment]
> 在配置中启用该功能后，您需要执行 /tab 重新加载、断开连接并重新连接到服务器，以便应用更改，是否执行此操作？

yes

**Comment by Tanguygab** [comment]
send your config.yml and a screenshot of the pet in game

**Comment by FZDNSZYT** [comment]
![image](https://user-images.githubusercontent.com/86947716/168480996-9c581adf-053c-401f-aaef-2fbd6f594429.png)
![image](https://user-images.githubusercontent.com/86947716/168481076-5ed6712d-8f8f-436e-ad6b-cd6342575001.png)
this is closed

**Comment by FZDNSZYT** [comment]
![image](https://user-images.githubusercontent.com/86947716/168481138-b84c4422-21ee-4cdd-92e0-1b43c54dbb68.png)
![2022-05-15 (9)](https://user-images.githubusercontent.com/86947716/168481168-d221704f-33d9-4230-9fbf-875fcbca1946.png)
this is on

**Comment by FZDNSZYT** [comment]
> 发送您的config.yml和游戏中宠物的屏幕截图

Really, this bug has been bothering me for a long time, but I suddenly remembered it today and asked the author.

**Comment by NEZNAMY** [comment]
Try with vanilla client. Your modification might show it incorrectly.

**Comment by FZDNSZYT** [comment]
![image](https://user-images.githubusercontent.com/86947716/168482865-685326bf-e094-4f0b-8195-3adf43929958.png)
![2022-05-16 (1)](https://user-images.githubusercontent.com/86947716/168482893-aefcdf6b-26e5-4f6d-bd31-09c4a7cdc909.png)
The same is true for the official client without any components
The first one is enabled
The second is not enabled

**Comment by FZDNSZYT** [comment]
> 尝试使用香草客户端。您的修改可能会错误地显示它。
Where is the problem usually

**Comment by NEZNAMY** [comment]
Can you send your full config?

**Comment by FZDNSZYT** [comment]
> 你能发送你的完整配置吗？

I send you the document?

**Comment by NEZNAMY** [comment]
config.yml

**Comment by FZDNSZYT** [comment]
[tab_config.zip](https://github.com/NEZNAMY/TAB/files/8695397/tab_config.zip)

**Comment by FZDNSZYT** [comment]
> config.yml

This is

**Comment by NEZNAMY** [comment]
You don't have unlimited nametag mode enabled. TAB does not affect entities then. Try removing TAB if it keeps happening.

**Comment by FZDNSZYT** [comment]
> 您没有启用无限制的名牌模式。TAB 不会影响实体。如果它不断发生，请尝试删除TAB。

Do I need to enable Infinite Nameplate Mode to do this?

**Comment by NEZNAMY** [comment]
To do what? You are reporting a bug in a feature which you are not using.

**Comment by FZDNSZYT** [comment]
> 该怎么办？您正在报告未使用的功能中的错误。

The same is true, I remember when 1.16.5 can display the pet's owner and title, it feels very cool

**Comment by FZDNSZYT** [comment]
Do you mean you have dropped this feature?

**Comment by FZDNSZYT** [comment]
what a shame

**Comment by FZDNSZYT** [comment]
I think it looks cool to have a title on a dog's head

**Comment by NEZNAMY** [comment]
What? I am saying TAB does not affect this in any way. Remove TAB to confirm it.

**Comment by FZDNSZYT** [comment]
Seriously, I don't know where to set the function of that multi-line title. There are only prefixes and suffixes in MySQL data tables

**Comment by NEZNAMY** [comment]
For the 3rd time, remove TAB to confirm it's not the cause if your pets not having names.

**Comment by FZDNSZYT** [comment]
oh, only the prefix

**Comment by FZDNSZYT** [comment]
> 第三次，删除TAB以确认如果您的宠物没有名字，这不是原因。

ok

**Comment by FZDNSZYT** [comment]
It doesn't look like tab's pot

**Comment by FZDNSZYT** [comment]
very sorry

**Comment by FZDNSZYT** [comment]
![image](https://user-images.githubusercontent.com/86947716/168484475-112bc2a0-743b-4ff1-adf5-2ecccb548ffd.png)

**Comment by NEZNAMY** [comment]
So if this is not a TAB issue, can this be closed?

**Comment by FZDNSZYT** [comment]
ok, excuse me
