### ISSUE TITLE
TABAPI Custom nametags do not display or update

### ISSUE THREAD

**Issue by xt449** [NEZNAMY/TAB#60]
**Server version**
Paper 1.14.4 (git-Paper-221)

**Plugin version** ("latest" is not a version)
2.5.3

**Describe the bug**
Using the methods provided by TABAPI, I am unable to successfully modify a player's name tag.
I have tried both the older (deprecated) method and the new ones, as well as both at the same time. I have also have not had success even directly accessing them using Shared#getPlayer.

**How to reproduce**
1. Use default configuration.
2. Execute code:
```java
TABAPI.setCustomTagNameTemporarily(player.getUniqueId(), name);
TABAPI.setCustomTabNameTemporarily(player.getUniqueId(), name);

TABAPI.setValueTemporarily(player.getUniqueId(), EnumProperty.CUSTOMTAGNAME, name);
TABAPI.setValueTemporarily(player.getUniqueId(), EnumProperty.CUSTOMTABNAME, name);

TABAPI.setValuePermanently(player.getUniqueId(), EnumProperty.CUSTOMTAGNAME, name);
TABAPI.setValuePermanently(player.getUniqueId(), EnumProperty.CUSTOMTABNAME, name);

Shared.getPlayer(player.getUniqueId()).setProperty("customtagname", name);
Shared.getPlayer(player.getUniqueId()).setProperty("customtabname", name);

Shared.getPlayer(player.getUniqueId()).updateAll();
Shared.getPlayer(player.getUniqueId()).forceUpdateDisplay();
```
3. Observe no change in name tags. (Tab names update normally)

**Expected behavior**
See a change in name tags.

**Actual behavior**
No change in name tags.
(Tab names update normally)

**Additional info** (errors, screenshots, ...)
(Useless image that shows basically nothing)
![image](https://user-images.githubusercontent.com/3751431/67538009-bb13fa80-f6ab-11e9-8988-41dd5949de1e.png)

**Comment by NEZNAMY** [comment]
Customtagname requires unlimited nametag mode enabled. It uses armor stands which make it easy to modify such value. Changing entity's name is complicated and unsafe if not handled properly.
