### ISSUE TITLE
Boss plugin incompatibility 

### ISSUE THREAD

**Issue by kangarko** [NEZNAMY/TAB#603]
### Server version

Paper 1.18.2

### TAB version

3.1.1

### Describe the bug

Our Boss plugin seems to have a major incompatibility with TAB: https://github.com/kangarko/Boss/issues/1058

(Boss nametags are duplicated, and permanently remain in the world until restart. One stays at the spawn location, and another at the death location.)

Please make an exception if an entity (including players, as we support Player NPCs from Citizens) has the "Boss_V4" metadata tag. Any such entity is coming from our plugin and will become incompatible.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Armor stand spawn/despawn logic just copies server behavior via a packet listener. Any idea what could be causing packet listener to fail like this?

**Comment by kangarko** [comment]
I don't know what you're talking about? Our plugin doesn't deal with armor stands, it spawns simple entities and adds invisible NBT tag data to mark them.

**Comment by NEZNAMY** [comment]
What TAB does it listens to player spawn/destroy packets and if the ID is recognized (belongs to an online player), appropriate spawn/despawn packets are armor stands are sent. This way it should always be correct, yet something is causing it to fail.

**Comment by kangarko** [comment]
Thanks for explainer. I do not use ProtocolLib integration anywhere at all in my Boss plugin. We call Entity#setCustomName(Visible) to display its custom name.

**Comment by NEZNAMY** [comment]
Do you have any working steps to reproduce available? Is the plugin free to download?

**Comment by kangarko** [comment]
It's a premium plugin but I will upload a limited copy here for your convenience: [Boss-4.3.8.zip](https://github.com/NEZNAMY/TAB/files/8747851/Boss-4.3.8.zip)

As for steps to reproduce, I just assumed it should be enabling the tab-above-players feature in TAB, installing Citizens plugin and killing a player NPC boss. 

You can create that boss using /boss new player, then /boss egg <bossName> and spawning it. I am unable to sit down for a proper test environment at the moment, but I tag @essolar and @MarxminSD -- ask them if you need more help on reproducing since they have reported this bug.

**Comment by kangarko** [comment]
Oh important note, @essolar @MarxminSD please use the latest dev build of ProtocolLib as they have solved an important bug: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/169658696-89b1ebf7-4f90-4291-99a2-439b94ff6559.png)
Seems to be a bug in your plugin or Citizens. Issue is present without TAB installed at all.

**Comment by kangarko** [comment]
Thanks for the info, I assume this is because of ViaVersion/ViaXX since I could not reproduce this myself either, I will follow up with the user.
