### ISSUE TITLE
Shows wrong prefix

### ISSUE THREAD

**Issue by Smolax** [NEZNAMY/TAB#605]
### Server version

BungeeCord

### TAB version

3.1.1

### Describe the bug

I have TAB installed on BungeeCord and TABBridge on the servers. The problem is, that when a rank is given from LuckPerms with context server="servername", the prefix remains global and doesn't change to the rank that was given, and priority system shows #6 meaning per-world / per-server applied to group _DEFAULT_.

### Expected behavior

Priority system should show #5 per-world / per-server applied to player's group. 

The prefix should appear from the rank given with context server="servername".

### Steps to reproduce

1. /lp user "nick" parent set "rank" server="nameserver"`
2. /btab debug "nick"

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of the debug and groups.yml

**Comment by Smolax** [comment]
Groups.yml
https://pastebin.com/w4Ej3v5w

TAB Debug
https://pastebin.com/LEQv4cfC

LP User info
https://pastebin.com/63GJ4m4U

**Comment by NEZNAMY** [comment]
per-server / per-world means you set it in TAB, not LP. As long as you are using %luckperms-prefix% placeholder, TAB takes value from LP and doesn't care if you set something in LP per world or not. LP info shows prefix "[A] ". Is that not what appears in the tablist? 
Also, your debug output and groups file don't match.

**Comment by Tanguygab** [comment]
enable use-bukkit-permissions-manager in config.yml

**Comment by Smolax** [comment]
> per-server / per-world means you set it in TAB, not LP. As long as you are using %luckperms-prefix% placeholder, TAB takes value from LP and doesn't care if you set something in LP per world or not. LP info shows prefix "[A] ". Is that not what appears in the tablist? You are saying per-world / per-server doesn't work, but you didn't configure anything there. Also, your debug output and groups file don't match.

Sorry, wrong folder. This is groups.yml 
https://pastebin.com/iinvRLbW

"[A] " is not showing on the tab

**Comment by Smolax** [comment]
> enable use-bukkit-permissions-manager in config.yml

In which config?

**Comment by Smolax** [comment]
> Well the file doesn't make sense, if you want the same values in all servers, just use global settings. Show output of `/btab parse me %server%`.

https://pastebin.com/SjgB3KtS

I don't want the same values

**Comment by NEZNAMY** [comment]
Fix what? TAB does what you configured it to do - displays prefix from LP.

**Comment by Smolax** [comment]
> Fix what? TAB does what you configured it to do - displays prefix from LP.


Well, that's exactly what it doesn't display.

![image](https://user-images.githubusercontent.com/23561451/170077985-7c85fa62-ce12-4bde-8485-aafd5e248f51.png)
![image](https://user-images.githubusercontent.com/23561451/170078323-356e3594-fd9b-4136-8349-c4a717b5f837.png)

/lp user Smolax info
![image](https://user-images.githubusercontent.com/23561451/170078395-248c5c79-32fd-4a87-a71c-c62a85083cdd.png)

Maybe that's why it works that way, but a prefix from another plugin works fine.
/lpb user Smolax info 
![image](https://user-images.githubusercontent.com/23561451/170079496-270d3ed8-7598-4179-8c13-70c53cfb70da.png)
![image](https://user-images.githubusercontent.com/23561451/170080182-dac514f3-bc65-4d3c-b262-f5018b29c0f1.png)

**Comment by NEZNAMY** [comment]
You configured TAB to take info from LP. LP info says G and TAB also shows G. I do not see any problem.

**Comment by Smolax** [comment]
> You configured TAB to take info from LP. LP info says G and TAB also shows G. I do not see any problem.

LP Bungee shows [G] (bungee console), but on the server (server console screen above) LP shows [A]. At the very bottom I've shown that the chat plugin gets the prefix from LP with the server context, not like TAB without any context.

Maybe I'll just install the TAB separately on each server rather than bungeecord
