### ISSUE TITLE
Client desyncronization

### ISSUE THREAD

**Issue by PedroMPagani** [NEZNAMY/TAB#607]
### Server version

Purpur 1.18.2

### TAB version

3.1.0

### Describe the bug

https://www.youtube.com/watch?v=ygBLG53BHbg

Here its a showcase of the actual desyncronization, I'm not sure if this is a client bug, or a  "TAB" bug, but since I did it also in my development side I feel like its more of a client bug mixed with maybe server-side packet rels.

### Expected behavior

Stand be always syncronized with the client position, and the client position in relation to other players always syncronize with the server-side position.

### Steps to reproduce

Just have two accounts looking at each other and make one disappear because of the entity tracking range, get back to a closer position when you appear back (Has to be mostly flying), and then the entity position will desync.

### Additional info

Do you have any idea of how it would be the best way to workaround this desync position?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
I'm pretty sure I already encountered that bug in the past and reported it to NEZ, but unfortunately, to this day, we still don't know how to fix it =/

**Comment by NEZNAMY** [comment]
This is a server-sided bug. Crouch down until you hit the ground, you will magically teleport to the correct location (where armor stands are).

**Comment by PedroMPagani** [comment]
Yes, in the vidfeo i've noticed that the position gets syncroninzed again after some point, because of the server sending the teleport packet as it does between some ticks.

Thanks for the confirmations bois, maybe in 1.19...
