### ISSUE TITLE
yellow-number-in-tablist Error

### ISSUE THREAD

**Issue by Fair0** [NEZNAMY/TAB#608]
### Server version

Spigot 1.17.1

### TAB version

3.1.1

### Stack trace

26.05.2022 - 16:47:11 - [TAB v3.1.1] yellow number only accepts numeric values! (Attempted to use "{enabled=true, value=205, disable-in-worlds=[disabledworld]}")

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Your config is scuffed, you went from v2 to v3 to v2 and v3 again, reset it.

**Comment by Fair0** [comment]
Alright, thank you
