### ISSUE TITLE
Pwp bug

### ISSUE THREAD

**Issue by FASHv10** [NEZNAMY/TAB#61]
**Server version**
Spigot 1.8.8-R0.1-SNAPSHOT

**Plugin version** ("latest" is not a version)
2.5.3

**Describe the bug**
when a player enters the server the pwp gets bugged and shows that player even if he isn't in the world

**How to reproduce**
Be in another world and enter with another account but that account enter another world

**Expected behavior**
That there is a tab for each world

**Actual behavior**
It bugges when a player enters

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Can you provide more info, such as configuration and what exactly you did, and try to reproduce it without other plugins ?
