### ISSUE TITLE
TAG showing incorrectly in the nametag

### ISSUE THREAD

**Issue by Vayunee** [NEZNAMY/TAB#610]
### Server version

1.18.1

### TAB version

3.0.2

### Describe the bug

I'm using a plugin to let 1.8 users join my 1.18.1 server. The problem is that the tags above the player itself are buggy and don't show the full tag, but the tags above other players are fine.
I linked an image that shows how I see my tag (and in the scoreboard it's how I see other player's tag)

![image](https://user-images.githubusercontent.com/102831272/170840624-75a08c75-a660-49c3-80bf-32e9737ec580.png)

### Expected behavior

the tag should be seen like other players

### Steps to reproduce

Join the game

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags

**Comment by Vayunee** [comment]
That's okay, limitations etc.. but why do I see other player's tag fine?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-2---seeing-own-armor-stands

**Comment by Vayunee** [comment]
Ok thanks, you're the best
