### ISSUE TITLE
TAB 3.1.2 breaks on 1.19 paper.

### ISSUE THREAD

**Issue by VanillaChan6571** [NEZNAMY/TAB#612]
### Server version

Paper 1.19 (Paper version git-Paper-"4a51a54" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4a51a54 on dev/1.19))

### TAB version

3.1.2

### Describe the bug

Seems like a tab issue since most of my plugins launched except for this one.

https://sourceb.in/KYvSxP16EG

Have fun with paper support XD

### Expected behavior

To Start.

### Steps to reproduce

1. Launch Paper 1.19
2. Plugin gets disabled.

### Additional info

tag me on discord VanillaChan#6571 if needed.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by XionioXMaster** [comment]
Update?
