### ISSUE TITLE
Bossbar is being blue color

### ISSUE THREAD

**Issue by rbstsoul** [NEZNAMY/TAB#614]
### Server version

Purpur 1.18.2

### TAB version

3.1.1

### Describe the bug

Hi! I use bossbar feature of TAB plugin. But when I open it, the bossbar turns into blue. Here is a screenshot of it: 
![image](https://user-images.githubusercontent.com/72627840/173253738-10a52685-a4f7-4e1f-832f-b3a55d8ad0ab.png)
_I use ItemsAdder for making the bossbar invisible. I deleted white bossbar texture._

Why is it happening?

### Expected behavior

It shouldn't look like blue.

### Steps to reproduce

Step 1: Change bossbar configuration like this: https://paste.helpch.at/fayefakeve.cs
Step 2: Join to the server
Step 3: See bossbar is like this: 
![image](https://user-images.githubusercontent.com/72627840/173253790-db5c2208-517d-42a7-bc56-d726223d92bc.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Try without itemsadder, what color will the text have?

**Comment by rbstsoul** [comment]
> Try without itemsadder, what color will the text have?

Hi! I didn't try it without ItemsAdder yet, but I have something to say. When I join with the original Minecraft launcher, the bossbar is not being blue. But if I join with other clients/launchers like Feather Client, it turns into blue.

**Comment by rbstsoul** [comment]
> Bug of your custom client then. Nothing we can about it.

Oh, ok. Have a good day!
