### ISSUE TITLE
Fatal error from "net.minecraft.network.chat.ChatModifier.toString()"

### ISSUE THREAD

**Issue by starboyceleste** [NEZNAMY/TAB#616]
### Server version

Purpur 

### TAB version

3.1.1

### Stack trace

https://pastebin.com/0PnAfv2J

### Additional info

I'm finding crashes regularly from this, maybe 1-2 a day.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Remove ProtocolLib and try again.

**Comment by starboyceleste** [comment]
> Remove ProtocolLib and try again.

A lot of my plugins depend on ProtocolLib and the crash isn't very immediately reproducible to test. Is that still what I should do?

**Comment by NEZNAMY** [comment]
Then remove TAB and try again.

**Comment by NEZNAMY** [comment]
Any news @starboyceleste ?

**Comment by NEZNAMY** [comment]
TAB doesn't do anything that could lead to a JVM crash (such as a JNI hook). The crash dump doesn't mention TAB anywhere either.
