### ISSUE TITLE
TAB prefix not loading without /TAB reload every time the player joins

### ISSUE THREAD

**Issue by Roman-Emperor-42** [NEZNAMY/TAB#619]
### Server version

Spigot 1.18.2

### TAB version

3.1.1

### Describe the bug

I'm having a problem of prefix's (Admin in this case) not load on TAB without reloading the plugin every time a player joins, even if they've joined before. I've attached the screenshots of tab and /TAB debug before and after.
![Uploading 2022-06-14_13.06.15.png…]()
![Uploading 2022-06-14_13.06.48.png…]()
![2022-06-14_13 06 53](https://user-images.githubusercontent.com/107327703/173671753-c106372f-d911-47ed-9dae-d7f57c728664.png)
![2022-06-14_13 07 01](https://user-images.githubusercontent.com/107327703/173671807-2238b8ad-f7e0-4b8b-b039-c988edd971ee.png)
![2022-06-14_13 07 14](https://user-images.githubusercontent.com/107327703/173671859-b8d770d8-58f7-4a6d-aeab-d5f2602c4994.png)
![2022-06-14_13 07 17](https://user-images.githubusercontent.com/107327703/173671921-b275d409-b56e-4154-9220-cbcb82c97ab9.png)

### Expected behavior

The prefix should be there whenever you join the world without having to reload the plugin.

### Steps to reproduce

Here's my config file and i just log into the server and my nick loads but the prefix does not.

`# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  header:
  - '&c&lOG&9&lCraft'
  - '&7&l>> %animation:Welcome%&3 &l%player%&7&l! &7&l<<'
  - '&7Online players: &f%online%'
  - '&6Online staff: &e%staffonline%'
  - '&7&lYour ping is &6%ping%'
  - '&7--------------------'
  footer:
  - '&7--------------------'
  - '&7Visit our webpage by doing /forums'
  - '&aogcraft.org | store.ogcraft.org'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:founder,rfounder,admin,jradmin,mod,trial-mod,developer,engineer,architect,phoenix,streamer,OGCrafter,ogb,CEO,Banker,Collector,Miner,Carpenter,Netherite,Emerald,Diamond,Gold,Redstone,Lapis,Iron,Coal,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: 0.22
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-in-servers: []
yellow-number-in-tablist:
  enabled: true
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-in-worlds:
  - disabledworld
prevent-spectator-effect:
  enabled: true
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: true
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%&7/&4%maxplayers%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
ping-spoof:
  enabled: false
  value: 0
fix-pet-names:
  enabled: false
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: true
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &4*&4&lAFK&4*&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
    '%server_unique_joins%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 500
assign-groups-by-permissions: false
primary-group-finding-list:
  - founder
- admin
- jradmin
- mod
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/173673225-ff650a64-0fac-4194-8c7f-db8bffa19998.png)
Some plugin altered the value using TAB's API as you can very clearly see.

**Comment by Roman-Emperor-42** [comment]
I apologize for a novice question, I'm still new to configuring plugins. How do I fix it. Thank you in advance!

**Comment by NEZNAMY** [comment]
Configure other plugins to not hook into TAB? This is out of scope of github issues.
