### ISSUE TITLE
TAB Tag bug

### ISSUE THREAD

**Issue by TheModz01** [NEZNAMY/TAB#62]
**Server version**

PaperSpigot 1.12.2

**Plugin version** ("latest" is not a version)

2.5.3
**Describe the bug**

https://gyazo.com/eaf6a20594dcef647093963c76d839d4
**How to reproduce**

It happens automatically, without doing anything
**Expected behavior**

Don't keep the tag floating
**Actual behavior**

The tag stays floating
**Additional info** (errors, screenshots, ...)
https://gyazo.com/eaf6a20594dcef647093963c76d839d4

**Comment by NEZNAMY** [comment]
There must be a way to reproduce it. Did the player die ? Reconnect ? /tab reload ? Something ?

**Comment by HugoMauricio72** [comment]
Ok can you just to join our discord please is for more information https://discord.gg/ZZDcrD8

**Comment by NEZNAMY** [comment]
Turned out to be caused by errors which should be fixed now.
