### ISSUE TITLE
Place refresh

### ISSUE THREAD

**Issue by UsainSrht** [NEZNAMY/TAB#624]
### Server version

Purpur 1.19

### TAB version

3.1.2

### Describe the bug

plugi refreshes the placeholders even if they aren't visible to any player. 

### Expected behavior

Not refresh the placeholders that arent't visible

### Steps to reproduce

create a new placeholder that broadcasts "some text"
use thet placeholder in some scoreboard or any other tab feature
for example I use that placeholder in the scoreboard that has condition `%world%="spawn"`
So when I'm in the world "spawn" it broadcasts "some text" every x miliseconds
But when I leave that world and my scoreboard change. I still get "some text message" every x miliseconds.

### Additional info

I'm using a placeholder that gets some of player's permissions and its refresh rate is 10 seconds but when I'm in the world that has a scoreboard that doesn't have that placeholder. The placeholder tries the refresh it without the player. So I get this error on console 

```
method ApiUserManager#getUser called with (null (Null)) threw a NullPointerException: uuid
method ApiUserManager#loadUser called with (null (Null)) threw a NullPointerException: uuid
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This is due to the way placeholder refreshing works. Changing this would require a recode of the function. Refreshing in general is very optimized + you can choose your intervals, so this should not be a problem.

**Comment by UsainSrht** [comment]
> This is due to the way placeholder refreshing works. Changing this would require a recode of the function. Refreshing in general is very optimized + you can choose your intervals, so this should not be a problem.

But this error message shows up in the console every 10 seconds for each player :(

**Comment by NEZNAMY** [comment]
Make your plugin not throw errors.

**Comment by UsainSrht** [comment]
> Make your plugin not throw errors.

Yea I mean I can basically hide this error but I expected you to fix the refreshing thing.
Can't you change the system a bit to not refresh placeholders that aren't visible?

If no, well np. Thanks anyway.

**Comment by NEZNAMY** [comment]
No, I'm limiting development to fixing important bugs only, since I am looking to quit the plugin.
