### ISSUE TITLE
Boats & Nametags

### ISSUE THREAD

**Issue by mnfu** [NEZNAMY/TAB#625]
### Server version

Paper 1.19 build 28

### TAB version

3.1.2

### Describe the bug

Nametag remains visible when riding in **boat with chest**

### Expected behavior

Nametag to disappear like it does in regular boats

### Steps to reproduce

1. Have unlimited nametags enabled (Not sure if that's the setting name exactly, but you get the idea)
2. Hop into a **boat with chest**
3. Nametag does not disappear

### Additional info

![2022-06-18_21 33 55](https://user-images.githubusercontent.com/95727104/174462269-5c005ce4-61a3-484d-9e7c-bf4966a316d0.png)
![2022-06-18_21 33 58](https://user-images.githubusercontent.com/95727104/174462271-b441f353-49c0-47ee-8b3a-d593814a4fc6.png)
![2022-06-18_21 34 02](https://user-images.githubusercontent.com/95727104/174462272-e2c22477-dd76-4b17-b365-9ed7d77ffbd4.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by TOWUK** [comment]
how set visible your nametag with f5?

**Comment by NEZNAMY** [comment]
You can't.
