### ISSUE TITLE
Prefix in Tablist but not above the player

### ISSUE THREAD

**Issue by phoenix3394** [NEZNAMY/TAB#627]
### Server version

Bungeecord

### TAB version

3.1.2

### Stack trace

No error messages in console or errors.log

### Additional info

I tried it with:
  - TablistFormatManager#setName
  - TablistFormatManager#setPrefix
  - TeamManager
  - UnlimitedNametagManager#setName
  - UnlimitedNametagManager#setPrefix
  - UnlimitedNametagManager#setLine with abovename, belowname, nametag, another

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
TeamManager#setPrefix is the way to change nametag prefix. Can you show an example code that doesn't work? What shows up as source in /tab debug \<player\>?

**Comment by PhoenixGamer339** [comment]
![image](https://user-images.githubusercontent.com/102826375/174887345-c47d185d-bb9d-4d92-a4cd-2d24ac664584.png)

That is my TeamManager#setPrefix code but the prefix is only displayed in the tablist not above the player

**Comment by NEZNAMY** [comment]
I see no TeamManager on that screenshot.

**Comment by PhoenixGamer339** [comment]
![image](https://user-images.githubusercontent.com/102826375/174887591-ffc2ba63-c7f9-45fb-aa3a-0d2cb8b5a775.png)
![image](https://user-images.githubusercontent.com/102826375/174887610-ec2dfa1c-9ab9-40b6-88ee-cecfd887b8fd.png)

**Comment by PhoenixGamer339** [comment]
sry wrong method

**Comment by PhoenixGamer339** [comment]
![image](https://user-images.githubusercontent.com/102826375/174887662-7aa89928-31fd-4430-af3e-1a3c45051e7f.png)

**Comment by NEZNAMY** [comment]
Make sure your code ran and then show debug output.

**Comment by PhoenixGamer339** [comment]
I already used debug outputs and they work

**Comment by NEZNAMY** [comment]
Or even better, perform the command using code before and after.

**Comment by PhoenixGamer339** [comment]
does it also work from the console?

**Comment by Tanguygab** [comment]
yes

**Comment by NEZNAMY** [comment]
Above I asked you to provide player name argument.

**Comment by PhoenixGamer339** [comment]
sry

**Comment by NEZNAMY** [comment]
Also 3.1.2-SNAPSHOT is not how bungeecord is being versioned.

**Comment by PhoenixGamer339** [comment]
I just downloaded them and put them in the plugins folder and activated the unlimitednametags

**Comment by NEZNAMY** [comment]
Great, now download latest version of TAB and try again.

**Comment by PhoenixGamer339** [comment]
Ohh my bad its a Velocity server

![image](https://user-images.githubusercontent.com/102826375/174889249-59e8b0a5-2a75-474e-93fa-db4fc58c148f.png)

**Comment by NEZNAMY** [comment]
" I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform"
You didn't read it.
https://github.com/NEZNAMY/TAB/wiki/Compatibility#proxies
![image](https://user-images.githubusercontent.com/6338394/174889334-b14e57ea-391a-4453-8ee3-d2b37ddb91f4.png)

**Comment by PhoenixGamer339** [comment]
And what now?

**Comment by NEZNAMY** [comment]
Now we know why isn't it working and your issue is invalid.
