### ISSUE TITLE
Text operations not working

### ISSUE THREAD

**Issue by th3lucas** [NEZNAMY/TAB#628]
### Server version

Paper 1.19

### TAB version

3.1.2

### Describe the bug

I want to only show a placeholder if it is NOT Wilderness
    - " &7Welt: &3%world% &7| &7Ort: &6%husktowns_current_location_town%!=Wilderness &7 %world%!=Bauwelt"

![image](https://user-images.githubusercontent.com/96976624/175394455-b7d4efc0-12a3-4421-a7e6-8eb24598b6d3.png)
This is what i get - it is not working on my end. Tried it with world too just in case.

### Expected behavior

I want to only show a placeholder if it is NOT Wilderness like this
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders

### Steps to reproduce

1. Install HuskTowns
2. Set the footer just like this
    - " &7Welt: &3%world% &7| &7Ort: &6%husktowns_current_location_town%!=Wilderness &7 %world%!=Bauwelt"
3. Press Tab

### Additional info

![image](https://user-images.githubusercontent.com/96976624/175395080-ecafdfe9-d781-4402-8dde-1c2634bd8935.png)

![image](https://user-images.githubusercontent.com/96976624/175395127-826ef136-f225-448b-a399-03ec077954a7.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You did not use any conditional placeholder there. Read the page again.
