### ISSUE TITLE
Bossbar consuming massive resources

### ISSUE THREAD

**Issue by TechTailor** [NEZNAMY/TAB#63]
**Server version**
Paper 1.14.4 (build 225)

**Plugin version** ("latest" is not a version)
TAB v2.5.4

**Describe the bug**
When the bossbar (provided by TAB) is enabled, my CPU resources are going to over 44% from 6% while idle (testing on a solo server with no one else on). I tested multiple times, as soon as the command for enabling bossbar is executed, the resources drain on cpu starts and it goes over 40%.

**How to reproduce**
Attached my bossbar.yml content below. Just activating the bossbar using the command causes it drain.
[bossbar.txt](https://github.com/NEZNAMY/TAB/files/3835893/bossbar.txt)

**Expected behavior**
Expect the bossbar to have no effect on performance whatsoever.

**Additional info** (errors, screenshots, ...)
Resources stats when bb disabled - 
![bb error 1](https://user-images.githubusercontent.com/14147474/68668541-6eb33080-056e-11ea-8af9-cee039d6b03b.png)
Resource stats as soon as its enabled in-game and displayed - 
![bb error 2](https://user-images.githubusercontent.com/14147474/68668563-7d99e300-056e-11ea-880f-57f95ff4d4fb.png)

**Comment by NEZNAMY** [comment]
This bug is triggered by misconfiguration. You are trying to use "ServerInfo" bar which is not defined anywhere.

**Comment by TechTailor** [comment]
Ahh, okay so removing that and setting default as [] fixes the problem, but it still taking up extra resources when switching between worlds (on the same server) as compared to without it. Does having per-world boss bar do that?

**Comment by NEZNAMY** [comment]
Yes it does. World change event processing is still not async, but it will be in the future. Do you have some timings output that shows it ?

**Comment by NEZNAMY** [comment]
You could have mentioned a massive error spam in errors file, that would speed things up.
