### ISSUE TITLE
TabPlayerLoadEvent is missing in the API

### ISSUE THREAD

**Issue by MrEAlderson** [NEZNAMY/TAB#630]
### Server version

Doesn't matter

### TAB version

3.1.2

### Describe the bug

I followed your development docs and noticed that the TabPlayerLoadEvent is not a part of the jar that is being provided within the maven repo. With that, your docs that depend on that event are incorrect.

### Expected behavior

It being included within the API

### Steps to reproduce

1. Add the repository and dependency
2. Try to import TabPlayerLoadEvent

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
You're sure you've read the docs?
https://github.com/NEZNAMY/TAB/wiki/Developer-API#Events

**Comment by Tanguygab** [comment]
oh, that part must have been forgotten when updating the wiki, fair enough, though the right event is stated at the bottom of the page under the Events section, I'll fix that
