### ISSUE TITLE
Number on scoreboard showed on 1.19

### ISSUE THREAD

**Issue by SwartZCoding** [NEZNAMY/TAB#631]
### Server version

Purpur 1.19

### TAB version

Tab 3.1.2 & Latest Tab Bridge

### Describe the bug

I just copy my config of my 1.18.1 server on a 1.19 sever.

On my 1.18.1 server, i don't have "0" number on the right of the scoreboard and on my 1.19, i have 0.

### Expected behavior

Like my 1.18.1 server, don't have horrible number on the right.

### Steps to reproduce

1. Create a scoreboard and Test on 1.18.1 server.
2. Copy this config and Test on 1.19 server.

### Additional info

use-numbers: false
static-number: 0

Screen on 1.19 (bug) : https://gyazo.com/e08737b32347c69c64ce0ca959878508
Screen on 1.18.1 (not bug) : https://gyazo.com/b5f352f26c2370b1b844aa8cb281bbf9

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
that's just how Minecraft vanilla works, you're using a custom client on 1.18.1 which removes the numbers.
The `use-numbers: false` feature is there to use the `static-number` (in your case, 0) instead of 0,1,2,3,4,5.....

https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard#numbers

**Comment by SwartZCoding** [comment]
LOL yes sure, i'm tiredness today. Thanks
