### ISSUE TITLE
Dev knowledge

### ISSUE THREAD

**Issue by PedroMPagani** [NEZNAMY/TAB#633]
Did you manage to apply hex colors to normal vanilla player name on his head? Currently we have TAB enabled and for some reason there seems to be a hex color support, if so how did you do it? (I don't see any other label so im creating blank)

**Comment by DrWurzeli** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags
vanilla name does not support RGB colors.
