### ISSUE TITLE
Pls add function to disable nametags when scoreboard-teams enabled

### ISSUE THREAD

**Issue by GlitchAlpha** [NEZNAMY/TAB#634]
### Server version

Paper 1.17.1

### TAB version

3.0.2

### Describe the bug

I am using nametag edit plugin and when I enable scoreboard-teams (for tab-sorting) NTE ceases to be responsible for tags and tags disappear

### Expected behavior

Function:
control/format nametags: false
or compatibility with NameTag Edit

### Steps to reproduce

Add comfiguration to 
control/format nametags: false
or compatibility with NameTag Edit

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Not possible. Teams handle both nametags and sorting. TAB is a full replacement for nametagedit, therefore no compatibility hook is needed.
