### ISSUE TITLE
Conditional Header/Footer

### ISSUE THREAD

**Issue by ImNotStable** [NEZNAMY/TAB#636]
I'm not sure if this is a feature but I was hoping it was so I could have headers based on placeholders

If it is a feature could someone show me where I can do this

Also can I use placeholder conditions in layout.yml?

**Comment by Tanguygab** [comment]
This is technically already possible with [conditional placeholders](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders)
You can create a condition, and put text in `yes` or `no`, which can also contain other condition placeholders, then use the placeholder in your header.
