### ISSUE TITLE
Team color in chat not working

### ISSUE THREAD

**Issue by Jtcoop** [NEZNAMY/TAB#638]
Vanilla Scoreboard Teams don't display their team color in chat when plugin is active. I was able to have this color with the plugin before so I am assuming there is a way to make it work.

**Comment by Tanguygab** [comment]
Players can only have 1 scoreboard team. 
If you don't want TAB to handle those, disable it in the config, though it'll remove every feature that comes with it.

**Comment by Jtcoop** [comment]
To be clear I am talking about a player's name having the color of their team when they type in chat. In the past I have used the tab plugin to make a player's group and color display in tab and the vanilla "/team" command to make their names colored in chat, which is what I was calling a "scoreboard team." I'm not sure if you are referring to something else. I have tried switching "scoreboard-teams enabled:" to false and this does not make it display, player names are white in chat when they should have color, yet oddly the color still displays when using "/me" and "/tm" or "/teammsg." Is there something in the config to change to fix this?

**Comment by Tanguygab** [comment]
Scoreboard teams manage nametag color.
If you want to use teams and colors using MC's commands, use that and disable the feature in TAB.
If you want to do it with TAB, enable the feature and set a tagprefix to players with `/tab player <player> tagprefix <text>` (supports color codes)
