### ISSUE TITLE
TAB List Showing NPCs randomly for 1 second

### ISSUE THREAD

**Issue by TechTailor** [NEZNAMY/TAB#64]
Server version
Paper 1.14.4 (build 225)

Plugin version ("latest" is not a version)
TAB v2.5.4

Describe the bug
In the TAB List, when I am around NPC's in my spawn, it randomly displays their avatar/icon below my name for 1 second randomly. Sometimes it shows just the npc closest to me (like in the ss attached) and other times it shows all the npcs in the spawn area.

How to reproduce
There's no pattern to it but it randomly happens every few seconds when i move the mouse around with tab open.

Expected behavior
Expect the tab list to only show players and not npc's.

Additional info (errors, screenshots, ...)
Screen Shot - 
![2019-11-09_18 49 27](https://user-images.githubusercontent.com/14147474/68675844-b8a41280-057e-11ea-825a-b6b3c375e856.png)

**Comment by NEZNAMY** [comment]
Not a bug and not caused by this plugin. Read FAQ for detailed explanation of this Citizens behaviour.
