### ISSUE TITLE
BossBar Placeholder

### ISSUE THREAD

**Issue by PanHaskins** [NEZNAMY/TAB#641]
### Server version

Purpur 1.18.2

### TAB version

3.1.2

### Describe the bug

Placeholders doesn´t work in BossBar
![image](https://user-images.githubusercontent.com/58113388/177040733-249ca47d-3eed-4c84-bf26-eebd96fa38b9.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/58113388/177041076-c29bff5b-6456-4447-8109-5f7c8755aad9.png)
![image](https://user-images.githubusercontent.com/58113388/177041114-d6bc0e85-49ff-472f-9b43-d83f18cd37c7.png)

### Steps to reproduce

`bossbarText:
  change-interval: 120000
  texts:
  - '&9&lPodpoř náš server zakoupením výhod na &c&l/store'
  - '&9&lNavštiv náš discord &c&ldsc.gg/hexplay'
  - '&9&lPodpoř server hlasem &c&l/vote'
  - '&l<rw SUMMER SALE> #cc000c&l35% OFF &7(%server_countdown_dd.MM.yyyy_01.09.2022%) #0085e6/store'
bossbarAnimation:
  change-interval: 1200
  texts:
    - 100
    - 99
    - 98
    - 97
    - 96
    - 95
    - 94
    - 93
    - 92
    - 91
    - 90
    - 89
    - 88
    - 87
    - 86
    - 85
    - 84
    - 83
    - 82
    - 81
    - 80
    - 79
    - 78
    - 77
    - 76
    - 75
    - 74
    - 73
    - 72
    - 71
    - 70
    - 69
    - 68
    - 67
    - 66
    - 65
    - 64
    - 63
    - 62
    - 61
    - 60
    - 59
    - 58
    - 57
    - 56
    - 55
    - 54
    - 53
    - 52
    - 51
    - 50
    - 49
    - 48
    - 47
    - 46
    - 45
    - 44
    - 43
    - 42
    - 41
    - 40
    - 39
    - 38
    - 37
    - 36
    - 35
    - 34
    - 33
    - 32
    - 31
    - 30
    - 29
    - 28
    - 27
    - 26
    - 25
    - 24
    - 23
    - 22
    - 21
    - 20
    - 19
    - 18
    - 17
    - 16
    - 15
    - 14
    - 13
    - 12
    - 11
    - 10
    - 9
    - 8
    - 7
    - 6
    - 5
    - 4
    - 3
    - 2
    - 1`

`bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  default-bars:
  - announcement
  bars:
    announcement:
      style: PROGRESS
      color: PURPLE
      progress: '%animation:bossbarAnimation%'
      text: '%animation:bossbarText%'`
![image](https://user-images.githubusercontent.com/58113388/177040784-6c8d2442-1a52-403b-b730-d8e6f93d1dc2.png)
![image](https://user-images.githubusercontent.com/58113388/177040968-0298676a-0707-41f6-955a-250fd850fff4.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders#placeholder-is-not-working
Check the `Note`

**Comment by PanHaskins** [comment]
- '%sync:<rw SUMMER SALE>% #cc000c&l35% OFF %sync:server_countdown_dd.MM.yyyy_01.09.2022%'

i see WIKI and it doesn´t work...

**Comment by Tanguygab** [comment]
that's not how it works...
![image](https://user-images.githubusercontent.com/45695833/177834554-6f507d62-de81-4bd8-9930-e7749fe8001e.png)
the %sync:...% placeholder is for another issuse

**Comment by PanHaskins** [comment]
yes i test it too.

Placeholder server_countdown_dd.MM.yyyy_01.09.2022 worked
but ItemAdder Placeholder for rainbowing text doesn´t work.

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/177835280-106483b3-eb66-47d3-8221-491db3526a23.png)
you have a single % here, double it

**Comment by PanHaskins** [comment]
I have
  - '<rw SUMMER SALE> #cc000c&l35%% OFF &7(%sync:server_countdown_dd.MM.yyyy_01.09.2022%) #0085e6/store'

but <rw SUMMER SALE> doesn´t work

**Comment by Tanguygab** [comment]
what's <rw ...> ?

**Comment by Tanguygab** [comment]
TAB does not have this feature

**Comment by Tanguygab** [comment]
You can still make animations through the `animations.yml` file. More info: https://github.com/NEZNAMY/TAB/wiki/Animations

**Comment by Tanguygab** [comment]
maybe it works in ItemsAdder, but it doesn't in TAB
