### ISSUE TITLE
HEX Color 

### ISSUE THREAD

**Issue by Fair0** [NEZNAMY/TAB#645]
### Server version

Paper 1.17.1

### TAB version

3.1.2

### Describe the bug

ok so i use this hex color "&#FF0000&lOWNER &#FF0000" as rank owner but it show as "&#FF0000&lOWNER &4" in name tag idk why

### Expected behavior

..

### Steps to reproduce

Fix name tag

### Additional info

![2022-07-07_19 33 06](https://user-images.githubusercontent.com/101202792/177806735-17541c0b-494f-4930-8588-f0f5b5272fa6.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Fair0** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags
but how do they use HEX Color in nametags?
![2022-07-09_00 27 13](https://user-images.githubusercontent.com/101202792/178062317-21cae8b1-56a5-49e8-9070-883046f87a31.png)

**Comment by NEZNAMY** [comment]
With the bypass on the wiki page.

**Comment by Fair0** [comment]
but it says Name does not support RGB codes

**Comment by Tanguygab** [comment]
it also says "**Bypass**: enable unlimited nametag mode"
![image](https://user-images.githubusercontent.com/45695833/178063269-ec5f034c-f7bb-45c4-b4ce-1944675900a2.png)

**Comment by Fair0** [comment]
i have unlimited nametag mode enabled tho

**Comment by Tanguygab** [comment]
Then it should work. Though seeing as you're using a custom client, you might want to take a look at the 2nd Additional Note
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-2---seeing-own-armor-stands

**Comment by Fair0** [comment]
Thank you for your help, ye it's just because i was using an custom client
