### ISSUE TITLE
Idea - Add option to remove "belowname-objective" from NPC's

### ISSUE THREAD

**Issue by ItzSkyylark** [NEZNAMY/TAB#646]
Currently NPC's like Citizens can also produce the Belowname Objective.

Would be nice to see an option like in the section:

`ignoreNPC: true/false`

How CitizensAPI at least checks for NPC:
`boolean isCitizensNPC = entity.hasMetadata("NPC");`

**Comment by rxzvd** [comment]
Would like to add, this disables if you have a color coded name.

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#belowname
