### ISSUE TITLE
Separate Entity / Armor Stand Bug?

### ISSUE THREAD

**Issue by AceSardonyx** [NEZNAMY/TAB#647]
### Server version

Paper 1.19

### TAB version

3.1.2

### Describe the bug

I am not sure if there's an option to disable this because if there is, it needs to be linked somewhere better.
There are armor stands in spectator mode. Following that, name tags act like separate entities lagging behind when going fast.

### Expected behavior

Default MC nametag collision

### Steps to reproduce

S1: Install the plugin
S2: Join the game
S3: Go in vanish or spectator mode or go fast to see separate entity behavior

### Additional info

Sorry if this has bene covered or if I am bad at searching, but I cannot find anyone with this issue so I think it might just be me.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Disable unlimited nametag mode if you don't want it.
