### ISSUE TITLE
Empty spaces in players list

### ISSUE THREAD

**Issue by LeoPotter** [NEZNAMY/TAB#65]
Hi, for me and for me other players would be very incredible if you added the possibility to create empty spaces in players list, like, there are 5 players in the server who are using 5 spaces but not all, with this function, plus them there be also all other players spaces used by empty name spaces. I hope you'll understand what I'm saying.

**Comment by NEZNAMY** [comment]
How is this not duplicate of #31 ?

**Comment by LeoPotter** [comment]
> 
> 
> How is this not duplicate of #31 ?

This is not, I just want all online players in the first avable spaces and then all empty spaces, not that suddivision.

**Comment by NEZNAMY** [comment]
Are you able to provide a screenshot of what you want it to look like ?

**Comment by LeoPotter** [comment]
> 
> 
> Are you able to provide a screenshot of what you want it to look like ?

The bloomed are are players: https://i.imgur.com/8v7rHDJ.png

**Comment by NEZNAMY** [comment]
Organizing player list using fake player slots. Just like #31 says.

**Comment by NEZNAMY** [comment]
Request is matching #31 's title - Add option to have fake player slots for organizing player list

**Comment by Tanguygab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Organized PlayerList](https://trello.com/c/cAkIgMhZ/2-organized-playerlist)

**Comment by Tanguygab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Organized PlayerList](https://trello.com/c/cAkIgMhZ/2-organized-playerlist)
