### ISSUE TITLE
Not Displaying NameTag - Even With Unlimited Mode Enabled

### ISSUE THREAD

**Issue by Oliton** [NEZNAMY/TAB#650]
### Server version

BungeeCord (Tab Bridge On All Servers)

### TAB version

3.1.2

### Describe the bug

Supposed To Display, Prefix and Name (when nicked display nickname)
![image](https://user-images.githubusercontent.com/68617990/179240594-7e3faf47-2c5e-45d3-8fbf-d809909f4698.png)

![image](https://user-images.githubusercontent.com/68617990/179240561-9600d69e-c806-43ac-8c64-d62c72650fc3.png)

Even with unlimited mode enabled, the nametag doesn't work.
I am unsure if it is something inside of config.yml, or an issue with groups.yml.

### Expected behavior

Supposed To Display players nametags, and if they are nicked, their nick.

### Steps to reproduce

Step 1: Have a bungeecord with Tab Installed and Tab-Bridge on all servers
Step 2: Have Luckperms, and Essentials installed.
Step 3: Copy The Config.yml text and Groups.yml into your files.
Step 4: Run The Server!

### Additional info

CONFIG.YML TEXT
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
    - lighthouse
  disable-in-servers:
    - disabledserver
  header:
    - "&3&lThe BedBugs Network"
    - "&7&l>> %animation:Welcome%&3 &l%condition:nick%&7&l! &7&l<<"
    - ""
    - "%animation:MyAnimation1%"
  footer:
    - "%animation:MyAnimation1%"
    - "&aPing: &2&n%ping%&r &ams"
  per-server:
    server1:
      header:
        - "an example of server with custom"
      footer:
        - "header/footer and prefix/suffix"
    server2;server3:
      header:
        - "This is a shared header for"
        - "server2 and server3"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags
scoreboard-teams:
  enabled: true
  enable-collision: false
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "GROUPS:Owner,GM,gamemaster,ADMIN,MOD,twitch,Builder,Media,Premium,DEFAULT"
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
  disable-in-worlds:
    - disabledworld
    - lighthouse
  disable-in-servers:
    - disabledserver
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: true
    disable-on-boats: true
    space-between-lines: 0.22
    disable-in-worlds:
      - disabledworld
    disable-in-servers:
      - disabledserver
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Yellow-number
yellow-number-in-tablist:
  enabled: true
  value: "%ping%"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Global-playerlist
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - lobby1
      - lobby2
    group2:
      - server1
      - server2

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Belowname
belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix
prevent-spectator-effect:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  scoreboards:
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "%animation:MyAnimation1%"
        - "&6Online:"
        - "* &eOnline&7: &f%online%"
        - "* &eCurrent World&7: &f%worldonline%"
        - "* &eStaff&7: &f%staffonline%"
        - " "
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
        - "%animation:MyAnimation1%"
    scoreboard1:
      title: "Default"
      lines:
        - "%animation:MyAnimation1%"
        - "&6My Stats:"
        - "* &eKills&7: &f%statistic_player_kills%"
        - "* &eDeaths&7: &f%statistic_deaths%"
        - "* &eHealth&7: &f%health%"
        - " "
        - "&6Personal Info:"
        - "* &bRank&7: &f%group%"
        - "* &bPing&7: &f%ping%&7ms"
        - "* &bWorld&7: &f%world%"
        - "%animation:MyAnimation1%"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Ping-Spoof
ping-spoof:
  enabled: false
  value: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
fix-pet-names:
  enabled: false

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  register-tab-expansion: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" # placeholder did not parse correctly, show real name instead

  # bukkit-only placeholders used in default groups.yml, doing this as a fix
  "%afk%":
    "%afk%": "" 
  "%luckperms-prefix%":
    "%luckperms-prefix%" : ""
  "%luckperms-suffix%":
    "%luckperms-suffix%" : ""

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

# assigning groups by permission nodes instead of taking them from permission plugin
assign-groups-by-permissions: false

# if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
# Warning! This is not sorting list and has nothing to do with sorting players in tablist!
primary-group-finding-list:
  - Owner
  - gamemaster
  - Admin
  - Mod
  - Builder
  - Media
  - Premium
  - Default

debug: false

# https://github.com/NEZNAMY/TAB/wiki/MySQL
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password

use-bukkit-permissions-manager: false

GROUPS.YML
_DEFAULT_:
  tabprefix: '%luckperms-prefix%'
  tagprefix: '%luckperms-prefix%'
  tabsuffix: '%luckperms-suffix%'
  tagsuffix: '%luckperms-suffix%'
  nametag: '%essentials_nickname%' 
  customtabname: '%condition:nick%'
  customtagname: '%condition:nick%'

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
So enabling unlimited nametag mode causes name to be invisible to other players?

**Comment by Oliton** [comment]
Yes

**Comment by Oliton** [comment]
When it isn't enabled it works just fine

**Comment by NEZNAMY** [comment]
Did bridge enable correctly? Can you send startup log?

**Comment by Oliton** [comment]
![image](https://user-images.githubusercontent.com/68617990/179242539-a37f6660-5c7e-4b70-bf8c-53fa3d8899a1.png)
It looks all right

**Comment by NEZNAMY** [comment]
Backend log where bridge is installed.

**Comment by Oliton** [comment]
Do you mean the .gz files?

**Comment by NEZNAMY** [comment]
latest.log ideally, but generally yes.

**Comment by Oliton** [comment]
[latest.log](https://github.com/NEZNAMY/TAB/files/9121627/latest.log)

**Comment by NEZNAMY** [comment]
In that log no one connected. That's not log from the time when screenshot was taken. You are also 1 version out of date of bridge.

**Comment by Oliton** [comment]
Do you think being out of date is the issue?

**Comment by NEZNAMY** [comment]
Unlikely, but it's not impossible. Try again with latest version and send correct log.

**Comment by Oliton** [comment]
[latest.log](https://github.com/NEZNAMY/TAB/files/9121703/latest.log)

**Comment by Oliton** [comment]
So I just logged on with the newer version and it worked!

**Comment by Oliton** [comment]
Is that just something that you can't fix (i think i read something like that)

**Comment by NEZNAMY** [comment]
Probably something that cannot be fixed, hard to tell without seeing it.

**Comment by Oliton** [comment]
Alright Thanks!
