### ISSUE TITLE
When renaming mobs with a nametag, Prefix is ​​displayed

### ISSUE THREAD

**Issue by byNixo** [NEZNAMY/TAB#651]
### Server version

Paper 1.18.2

### TAB version

v3.1.2

### Describe the bug

When I rename an animal or monster with a nametag, the rank prefix is ​​added as well.

![grafik](https://user-images.githubusercontent.com/74796414/179401677-dfa43582-b363-4903-941b-09927b02b945.png)

### Expected behavior

Actually, the prefix should not be displayed there. But only be described as the nametag.

### Steps to reproduce

I don't know what to do to fix this. Maybe it's due to an additional plugin.

### Additional info

The nametag where the mob is comes from the TAB plugin.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#additional-note-3---prefixsuffix-on-pets & https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
