### ISSUE TITLE
Nicknames breaking on Tab

### ISSUE THREAD

**Issue by Caleston** [NEZNAMY/TAB#652]
### Server version

Waterfall 1.19 proxy with Paper 1.17.1 server

### TAB version

3.1.2

### Describe the bug

Nicknames have been breaking in a weird way since updating to 3.1.2 on Waterfall.
Setting a nickname breaks name/tab once you say something in chat. 
If you don't say anything in chat, it does not break, also applying /btab reload will fix it until a message is sent again.

I believe this nick issue is related to causing trouble with placeholders on our live server, as a nickname wipes placeholders entirely for that player and sets the nickname as the only thing. Even simple placeholders like %luckperms-prefix% will disappear, while still working fine for non-nicknamed players.

At first I thought the issue was with our nickname plugin (Multichat), but upon testing for hours and noticing that EssentialsX nickname displays similar behavior, I have to believe the issue lies with TAB-Bridge or TAB.

This is easy to test with Paper 1.17.1 + EssentialsX + TAB-Bridge and on Waterfall 1.19 + TAB. Default configs.
**TAB on Paper server instead of Waterfall did not cause this issue with nicknames.**

### Expected behavior

Nicknames shouldn't break tab, as before the update, same settings worked fine and nicknames did not reset or break placeholders.

### Steps to reproduce

1. Check TAB
2. Set yourself a colored nickname (/nickname &5ASDF)
3. Check TAB (name should appear colored)
4. Send any message in chat
5. Check TAB (name returns to default)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Caleston** [comment]
For EssentialsX, default config, but with change-playerlist: true.
For TAB, default config, but in groups.yml set %vault-prefix% into %vault_prefix% to see prefix disappearing.

This is how you start off: (red color comes from being OP)
![2022-07-18_17 16 51](https://user-images.githubusercontent.com/1515422/179532606-77c4d9ce-be1d-4c3a-b2c6-a6ebca7adea2.png)

Then you add a nickname, it displays perfectly:
![2022-07-18_17 16 57](https://user-images.githubusercontent.com/1515422/179532695-564e86d1-7230-4cff-974a-eda37bdaa5fb.png)

You send a message in chat, having the nickname resets prefixes.
![2022-07-18_17 16 59](https://user-images.githubusercontent.com/1515422/179532804-ed4d7002-15c7-4c86-a165-90f244df0ebb.png)
/btab reload or removing the nickname fixes the tab.

This seems to come down to the change-playerlist: true, but while it probably shouldn't be on for EssentialsX, Multichat has similar option of set_display_name which is required in order to have nicknames show (it has no displayname placeholder of its own).

I believe there was some sort of an override against it in the past with TAB, but it seems that it no longer overrides it. Same system worked on previous versions with TAB managing to override the nickname reset while still displaying the nickname.

**Comment by Caleston** [comment]
For what it looks like on a live server:

Old: 
TAB working perfectly, nicknames used for most name colors.
![tab1](https://user-images.githubusercontent.com/1515422/179537242-5173d500-e706-4926-83e1-1ac550a1e2d6.png)

Current:
Nicknames breaking placeholders on local server, almost everyone should have a prefix of some kind + nation tags.
Only those on other servers in the same network have it displayed correctly.
![tab2](https://user-images.githubusercontent.com/1515422/179537341-656bc835-4b0e-407e-a408-d2ca9385b8f8.png)

**Comment by NEZNAMY** [comment]
You forgot to send your config.

**Comment by Caleston** [comment]
> You forgot to send your config.

[Essentials & Tab configs.zip](https://github.com/NEZNAMY/TAB/files/9133041/Essentials.Tab.configs.zip)

EssentialsX, default config, but with change-playerlist: true. + removed OP name color
TAB, default config, but in groups.yml set %vault-prefix% into %vault_prefix% to see prefix disappearing.

**Comment by NEZNAMY** [comment]
Show output of `/btab debug <player>` on some player when formatting is lost.

**Comment by Caleston** [comment]
> Show output of `/btab debug <player>` on some player when formatting is lost.
There doesn't seem to be any difference:

[TAB]: [TAB] Showing debug information
[TAB]: >-------------------------------<
[TAB]: Server version: git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498
[TAB]: Plugin version: 3.1.2
[TAB]: Permission plugin: LuckPerms
[TAB]: Permission group choice logic: Primary group
[TAB]: Sorting system: GROUPS then PLACEHOLDER_A_TO_Z
[TAB]: >-------------------------------<
[TAB]: Player: Graddod
[TAB]: Primary permission group: default
[TAB]: Team name: 07GraddodA
[TAB]: Team name note: Primary group is #7 in sorting list. %player% returned "Graddod".
[TAB]: tabprefix: "%vault_prefix%" (14) (Source: group=_DEFAULT_)
[TAB]: tabsuffix: "%vault-suffix%%afk%" (19) (Source: group=_DEFAULT_)
[TAB]: customtabname: "%essentials_nickname%" (21) (Source: group=_DEFAULT_)
[TAB]: tagprefix: "%vault_prefix%" (14) (Source: group=_DEFAULT_)
[TAB]: tagsuffix: "%vault-suffix%%afk%" (19) (Source: group=_DEFAULT_)
[TAB]: >-------------------------------<

**Comment by NEZNAMY** [comment]
Does `/btab parse <player> %vault_prefix%` show correct prefix?

**Comment by NEZNAMY** [comment]
You are talking about players on other servers on the network, but you have global playerlist disabled. How do you see those players then?

**Comment by Caleston** [comment]
> You are talking about players on other servers on the network, but you have global playerlist disabled. How do you see those players then?

Live server has a bit different config. I only used default config for testing purposes as the issue seems to persist with even those.

> Set `disable_tab_list_rewrite: false` in waterfall.yml
Oh man, that seems to do the trick. Nickname isn't resetting now. I had no idea this setting existed, thank you.
I will try that on live server.

**Comment by Caleston** [comment]
Can confirm that changing the setting fixed it entirely, everything works great, thank you.
