### ISSUE TITLE
Luckperms not connecting to TAB

### ISSUE THREAD

**Issue by knowingbryan10** [NEZNAMY/TAB#656]
### Server version

paper 1.19

### TAB version

3.1.2

### Describe the bug

The Plugin will not connect to my luckperms and i do not know why can somone help me please

luckperms version : 5.4.35

### Expected behavior

I have A Rank system in a order it go's somthing like this 
Owner
Co-owner
admin
Godly (paid role)
Menece
Spicy+
Spicy
Default
And none of the show up only the Owner, Admin, Default (the default one in the groups is _Default_ in tab but not in luckperms

### Steps to reproduce

N/A

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist

**Comment by knowingbryan10** [comment]
i dont know what im looking for?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#how-to-make-tab-work-with-luckyperms 
Here's an alternate explanation.
