### ISSUE TITLE
Placeholders are sometimes displayed as their %placeholder_name% above players

### ISSUE THREAD

**Issue by ltjessem** [NEZNAMY/TAB#659]
### Server version

Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291 / Paper-1.19-66

### TAB version

3.1.2 build 433 + TAB-Bridge v2.0.3

### Describe the bug

Sometimes placeholders appear as their %placeholder_name% above players. In the tablist the placeholder function normally, it only affects `tagprefix`, `tagsuffix`, `belowname `and `abovename `. The only thing that never fails is the `customtagname: "%essentials_nickname%"` part.

`/papi parse` also returns sane values. 

Unfortunately I can't find any sort of pattern to when and how this happens. Two players can log in at the same time, one will have his normal prefix, the other will have `%vault_prefix%`

![image](https://user-images.githubusercontent.com/10084953/180770514-eb1a0b73-f071-4613-94ec-4601411f549c.png)

### Expected behavior

Placeholders to function in tags.

### Steps to reproduce

I can't really find a way to reproduce this on demand, it happens seemingly randomly, . 

### Additional info

[config.yml](https://pastebin.com/Xf1c4sWy)
[groups.yml](https://pastebin.com/V2BXS7tL) (The placeholders are commented out, but they are there)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
This issue is already described in existing issues, just in a different way. Can you try latest bridge build from github actions?

**Comment by ltjessem** [comment]
I'm using that, build 433

**Comment by Tanguygab** [comment]
talking about TAB-Bridge build :D https://github.com/NEZNAMY/TAB-Bridge/actions/runs/2685210495

**Comment by NEZNAMY** [comment]
Also, if the placeholders change value, do they appear correctly after?

**Comment by ltjessem** [comment]
Currently waiting to restart my servers with the latest bridge, I didn't think to update that.

These placeholders rarely update and are fairly static, but yes they do display when the placeholder is given a new value.

**Comment by ltjessem** [comment]
It's been looking good after updating the bridge, so I'll close this.
Thanks for actually responding to issues, that's almost a rarity these days :)

**Comment by NEZNAMY** [comment]
Bug reports are being taken seriously, sadly most people abuse issues to ask for help.
