### ISSUE TITLE
Hide health when not in Survival

### ISSUE THREAD

**Issue by tdubz1** [NEZNAMY/TAB#66]
Please could you add a feature to your plugin which hides the Health (under the display name) if you are not in Survival. It would be very useful if you could do this.

Thank you very much for an amazing plugin,

tdubz

**Comment by NEZNAMY** [comment]
Vanilla belowname feature is very limiting and cannot be turned off for specific players.

**Comment by tdubz1** [comment]
So you couldn't have it only in Survival Mode?

**Comment by NEZNAMY** [comment]
No. You either see it on everyone or no one.

**Comment by tdubz1** [comment]
On invadedlands.net staff members do not have health tags.

**Comment by tdubz1** [comment]
How is this possible?

**Comment by NEZNAMY** [comment]
I need screenshots.

**Comment by tdubz1** [comment]
Ok

**Comment by tdubz1** [comment]
You are right. It is impossible, I must have been mistaken.

**Comment by tdubz1** [comment]
However, Another thing I was going to ask, Could you implement in the Health Bar the extra absorption hearts e.g from a golden apple so the health displayed is Max 24HP instead of the 20HP at the moment It would be very useful to have this in my server,
Cheers,
tdubz123

**Comment by NEZNAMY** [comment]
Check out placeholderapi, should be doable with it.

**Comment by tdubz1** [comment]
Explain how I would do this please.

**Comment by NEZNAMY** [comment]
%player_health%, %player_saturation%,
and using math (https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#math) to count these two numbers.

**Comment by tdubz1** [comment]
Thank you so much.
