### ISSUE TITLE
White nicknames

### ISSUE THREAD

**Issue by ReferTV** [NEZNAMY/TAB#660]
### Server version

Purpur 1.19 build 1718

### TAB version

3.1.2

### Describe the bug

![image](https://user-images.githubusercontent.com/61411400/180774533-a667e8f5-d1c6-4be0-81cf-52cfcb333ff0.png)
My players sometimes has white nicknames.

### Expected behavior

Players will get the prefix they are supposed to get. (In this case, the color of the nickname, but the prefixes are not visible there either if I would give any)
![image](https://user-images.githubusercontent.com/61411400/180775150-ff9fac0e-33ad-4cfb-b621-f8e7aad90fc8.png)
![image](https://user-images.githubusercontent.com/61411400/180775228-586cacbf-66d5-44d0-8226-1e76fe64abca.png)
![image](https://user-images.githubusercontent.com/61411400/180775387-df4f773c-3851-44f3-9ded-60318c3ef2c7.png)

### Steps to reproduce

Step 1. Join the server
Step2. Sometimes players get a white nickname

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
"I am running latest version of the plugin" You are not. 
Show plugin list.

**Comment by Tanguygab** [comment]
set anti-override to true under scoreboard-teams

**Comment by ReferTV** [comment]
> "I am running latest version of the plugin" You are not. Show plugin list.

Sorry, my bad

![image](https://user-images.githubusercontent.com/61411400/180776156-d92c9e92-0cf1-4fe7-a5be-e9a4980510ee.png)

**Comment by ReferTV** [comment]
> set anti-override to true under scoreboard-teams

hmm looks like it is working, at least for now, if the problem continues I will add a new comment

**Comment by NEZNAMY** [comment]
If the problem continues it means you still didn't read the wiki, this is an issue tracker, support is not provided here.

**Comment by Tanguygab** [comment]
anti-override prevents other plugins from changing the player's scoreboard team (which manages) nametag prefixes and other stuff.
Also please consider updating.
