### ISSUE TITLE
Players switch the world in waterfall1.19, and customized prefixes cannot be used normally

### ISSUE THREAD

**Issue by 2053740844** [NEZNAMY/TAB#661]
### Server version

waterfall1.19

### TAB version

3.1.2

### Describe the bug

Players switch the world in waterfall1.19, and customized prefixes cannot be used normally。It will become the default of the sub server and will never work properly。But using /btab reload can solve the problem

Tab安装到waterfall1.19。玩家在切换世界等行为后Tab的自定义组或用户的前缀会消失。使用/btab reload 指令就能解决问题。望解决。感谢。

### Expected behavior

waterfall1.19

### Steps to reproduce

玩家进入服务器时可能会没有。玩家切换世界后绝对没有
输入/btab reload 就能解决问题

### Additional info

![QQ截图20220726212755](https://user-images.githubusercontent.com/70802107/181017660-776ef7c2-8ad3-422e-bdc8-cd53939ba086.png)
![QQ截图20220726212807](https://user-images.githubusercontent.com/70802107/181017663-7b81a129-957e-446a-a8af-d1630c63b245.png)
![QQ截图20220726212825](https://user-images.githubusercontent.com/70802107/181017670-4b73c940-d295-4539-8373-7ba864931483.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by killerprojecte** [comment]
I have same problem
Some time the player join the server his prefix papi will not replaced and tab will set player tagprefix first
when i excute /btab reload that will be normal

Please Fix it

And i can share my config
`
header-footer:
  enabled: true
  header:
  - ''
  - <#FFFF00>&lRemoved</#FFD700>
  - '&r%animation:gr%'
  footer:
  - ''
  - '<#00CED1>IP地址: Removed    官方QQ群: Removed</#32CD32>'
  - ''
  - '&7在线玩家: &3%online%&7 &8| &7当前世界: &8[&r%multiverse_world_alias%&8]'
  - ''
  - '&r%animation:gr%'
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  per-server: {}
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
scoreboard-teams:
  enabled: true
  invisible-nametags: false
  anti-override: true
  enable-collision: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  case-sensitive-sorting: true
  unlimited-nametag-mode:
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    enabled: false
  sorting-types:
  - GROUPS:admin,6,5,4,3,2,default
  - PLACEHOLDER_A_TO_Z:%player%
yellow-number-in-tablist:
  enabled: false
  value: ''
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
belowname-objective:
  enabled: true
  number: '%player_health_rounded%'
  text: '&c♥'
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-servers:
  - disabledserver
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
      announcement-bar: false
    test:
      style: PROGRESS
      color: WHITE
      progress: '100'
      text: test
      display-condition: '%server%=testworld'
      announcement-bar: false
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  use-numbers: false
  static-number: 0
  disable-in-worlds:
  - disabledworld
  scoreboards:
    scoreboard1:
      title: Default
      lines:
      - Scoreboard for players
    twscoreboard:
      title: TestWorld
      lines:
      - This is scoreboard for everyone in testworld world
      display-condition: '%server%=testworld'
    admin:
      display-condition: permission:tab.scoreboard.admin
      if-condition-not-met: scoreboard1
      title: Admin scoreboard
      lines:
      - Scoreboard for people with permission
      - tab.scoreboard.admin
ping-spoof:
  enabled: false
prevent-spectator-effect:
  enabled: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%tps%':
    '20': '&aPerfect'
  '%pvpmanager_pvp_status%':
    'yes': '&c&l已启用'
    'no': '&a&l已禁用'
conditions:
  health:
    conditions:
    - '%health%<21'
    - '%health%>15'
    type: AND
    true: Healthy!
    false: Damaged!
placeholders:
  afk-yes: ''
  afk-no: ''
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: true
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 500
assign-groups-by-permissions: false
primary-group-finding-list:
- admin
- '6'
- '5'
- '4'
- '3'
- '2'
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
global-playerlist:
  update-latency: true
  enabled: true
  spy-servers:
  - spyserver1
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
use-bukkit-permissions-manager: false
fix-pet-names:
  enabled: false

`

**Comment by NEZNAMY** [comment]
Are you using waterfall?

**Comment by killerprojecte** [comment]
yes i using waterfall 1.19

**Comment by NEZNAMY** [comment]
Set disable_tablist_rewrite in waterfall.yml to false @killerprojecte @2053740844 .
