### ISSUE TITLE
"else" in placeholder-output-replacements no longer works

### ISSUE THREAD

**Issue by NoltoxGit** [NEZNAMY/TAB#666]
### Server version

Purpur 1.18.2

### TAB version

3.1.3

### Describe the bug

Hellow !

Since the last update of the plugin (v3.1.3) the "else" function for placeholder-output-replacements no longer works or at least behaves very badly compared to v3.1.2.

### Expected behavior

The plugin is supposed to behave as in v3.1.2, that is to say that "else" corresponds to all the other possible results and currently it does a bit of a mess...
In my configuration I did this:
```yml
  '%cmi_user_playtime_days%':
    '0': ''
    'else': '%cmi_user_playtime_days%j '
```
And in game I have this result: https://gyazo.com/c11f689491af13ae03f1fdf8f1752355

other exemple on my config:
```yml
  '%cmi_server_online%':
    '0': '{#e5e5e5}Aucun joueur en ligne...'
    '1': '{#e5e5e5}Tu es le {#FFA500}seul {#e5e5e5}joueur en ligne.'
    'else': '{#FFA500}%cmi_server_online% {#e5e5e5}joueurs au total !'
```
Result: https://gyazo.com/ed7a7d4bf5eaaf4783e6ada1fbbcb04c

### Steps to reproduce

1. Have the latest version of TAB
2. Have Purpur-1632 1.18.2
3. Test my config with 3.1.3 and 3.1.2 to see the problem with "else".

### Additional info

Config: https://pastebin.com/MqJ7s2LN

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
utilises %value% au lieu du placeholder dans les remplacements, aussi j'espère que tu utilises bien la version 3.1.3 et pas 3.0.3 ;)

**Comment by NoltoxGit** [comment]
> utilises %value% au lieu du placeholder dans les remplacements, aussi j'espère que tu utilises bien la version 3.1.3 et pas 3.0.3 ;)
Oui oui j'utille bien la version 3.1.3, je me suis trompé x)

**Comment by NoltoxGit** [comment]
> utilises %value% au lieu du placeholder dans les remplacements

Salutations !
Même en utilisant le placeholders `%value%` dans la config, j'ai toujours le même soucis, le texte qui s'affiche en trop...
```yml
  '%cmi_user_playtime_days%':
    '0': ''
    'else': '%value%j '
```
```yml
  '%cmi_server_online%':
    '0': '{#e5e5e5}Aucun joueur en ligne...'
    '1': '{#e5e5e5}Tu es le {#FFA500}seul {#e5e5e5}joueur en ligne.'
    'else': '{#FFA500}%value% {#e5e5e5}joueurs au total !'
```

**Comment by Tanguygab** [comment]
je confirme, il y a un problème

**Comment by Tanguygab** [comment]
Check https://github.com/NEZNAMY/TAB/actions/runs/2760113579
ça devrait fix le problème

**Comment by NoltoxGit** [comment]
> ça devrait fix le problème

Effectivement ça refonctionne comme il faut ! Merci de l'aide 😉
