### ISSUE TITLE
I can't write Thai lang on scoreboard, it will be invisible when I write Thai lang on it.

### ISSUE THREAD

**Issue by SoloTHx** [NEZNAMY/TAB#667]
### Server version

Paper 1.18.2

### TAB version

3.1.3

### Describe the bug

I can't write Thai lang on scoreboard, it will be invisible when I write Thai lang on it.
![image](https://user-images.githubusercontent.com/103822130/181677999-4f0d0a28-e4f8-47a2-85eb-46e42fea208c.png)

But I can write Thai language on Tablist. Why is that?
![2022-07-29_10 41 04](https://user-images.githubusercontent.com/103822130/181678362-1d3364a9-c6f4-449b-a43d-0ac72bf69d25.png)

### Expected behavior

please fix the problem for me I really want to use this plugin.

### Steps to reproduce

Sorry i don't know about this part

### Additional info

![image](https://user-images.githubusercontent.com/103822130/181678620-8b3c7a0c-f7d1-439c-811e-e4f1315def07.png)
![image](https://user-images.githubusercontent.com/103822130/181678648-10fbd45c-0f25-4a1e-b60e-fd72f53aefe0.png)
![image](https://user-images.githubusercontent.com/103822130/181678675-b1dc0b0a-c2c2-4310-91df-ec51cbe54837.png)
![image](https://user-images.githubusercontent.com/103822130/181678688-76e4114a-568f-4d2c-b9e6-67234a584e18.png)
This is my config.yml

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
works for me 
![image](https://user-images.githubusercontent.com/45695833/181744552-58738952-dabd-4156-bee7-a27abc941d39.png)

**Comment by SoloTHx** [comment]
> works for me ![image](https://user-images.githubusercontent.com/45695833/181744552-58738952-dabd-4156-bee7-a27abc941d39.png)

Oh sry my bad 
Its is Because my resources pack
