### ISSUE TITLE
3.1.3 placeholder replacement bug

### ISSUE THREAD

**Issue by UsainSrht** [NEZNAMY/TAB#670]
### Server version

Purpur 1.19.1

### TAB version

3.1.3

### Describe the bug

Placeholder replacements are broken with the latest change. My gradient placeholder replacements aren't working anymore.

### Expected behavior

not broken gradient placeholders  

### Steps to reproduce

```
placeholder-output-replacements:
  '%player_ping%':
    0-50: '<gradient:#55ff55:#00aa00>%value%ms</gradient>'
    50-100: '<gradient:#ffff55:#ffaa00>%value%ms</gradient>'
    else: '<gradient:#ff5555:#aa0000>%value%ms</gradient>'
```

/papi parse me %tab_placeholder_player_ping%

![image](https://user-images.githubusercontent.com/59025999/182012608-29df4076-ee11-46ae-8ff9-b5c16cff1495.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by UsainSrht** [comment]
In scoreboard
![image](https://user-images.githubusercontent.com/59025999/182012639-181be9ff-9333-4af1-a528-ff8713a9ffad.png)

**Comment by Tanguygab** [comment]
already fixed, get the latest build from the Actions page

**Comment by Tanguygab** [comment]
Try another format of gradient, the <gradient:> format seems to have some issues on Purpur, the others should work fine. 

And for the `else` replacement being shown twice, that's already fixed, get the latest build from the Actions page

**Comment by UsainSrht** [comment]
👍
