### ISSUE TITLE
New animation maked TAB not work

### ISSUE THREAD

**Issue by Vairoon** [NEZNAMY/TAB#672]
### Server version

Paper 1.17.1

### TAB version

3.0.2

### Describe the bug

I add an animation in animations.yml in the same format and looks valid, i add the animation in the normal config.yml, and boot up the game, but then the tab plugin doesnt work!

### Expected behavior

that the animation is showing and the tab plugin works.

### Steps to reproduce

Step 1: Add animation to animations.yml
Step 2: Add animation to config.yml
Step 3: Boot up server

### Checklist

- [x] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
You're outdated
You didn't provide your animations.yml file
You didn't provide your config.yml
You didn't send a screenshot of the animation not working in-game
