### ISSUE TITLE
Add ability to make /sb spigot side when we used Tab Bungee

### ISSUE THREAD

**Issue by SwartZCoding** [NEZNAMY/TAB#676]
All in the title.

My issue here is i have a DeluxeMenu /settings with a lots of configuration for my players.

Since Tab is bungee rated, DeluxeMenu does not allow bungeecord commands, and so I get stuck. It would be enough to add in the bridge this command to plugin message with Bungee Side.

**Comment by NEZNAMY** [comment]
Requests are closed. Use a plugin like CommandSync to achieve it.

**Comment by SwartZCoding** [comment]
> Requests are closed. Use a plugin like CommandSync to achieve it.

Another plugin, for an request easiest to implements and which can improve Tab ... ^^.

**Comment by NEZNAMY** [comment]
How is it so easy for a proxy plugin to do something on the backend server? And yes, I am no longer looking to improve the plugin. As I said a few updates ago, I am quitting the development.
