### ISSUE TITLE
[SUGGESTION] Feature to hide Players NameTags

### ISSUE THREAD

**Issue by TeQTabanca** [NEZNAMY/TAB#677]
I tried this feature in other plugins but it didn't work in any of them. Since your plugin has a nametag section, I wanted to write it here. It would be nice if the property was set as follows.

```.yml
nametag-hide-worlds:
 - TestWorld
```

```.yml
nametag-hide-regions: ( Worldguard support is required! If you add Worldguard support, it would be nice if you add this kind of feature to other sections.)
 -TestRegion
```

**Comment by Tanguygab** [comment]
Feature requests are currently closed.
Though I made an [addon](https://github.com/Tanguygab/TAB-Additions) with a feature that could help with what you're trying to achieve
In the config, you'll have to set `conditional-nametags: true` and go in TAB's groups.yml file, under `_DEFAULT_`, add `condition-nametag: "%worldguard_region_name%=YourRegionName"`
That way, it will only show your nametag in the region YourRegionName. If you want to do it the other way around, you can flip ```yml
conditional-nametags:
  show-by-default: false
``` to `true` in TAB-Additions' config.yml 

You can also use any kind of condition in groups.yml (https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders)

**Comment by TeQTabanca** [comment]
> Feature requests are currently closed. Though I made an [addon](https://github.com/Tanguygab/TAB-Additions) with a feature that could help with what you're trying to achieve In the config, you'll have to set `conditional-nametags: true` and go in TAB's groups.yml file, under `_DEFAULT_`, add `condition-nametag: "%worldguard_region_name%=YourRegionName"` That way, it will only show your nametag in the region YourRegionName. If you want to do it the other way around, you can flip `yml conditional-nametags: show-by-default: false ` to `true` in TAB-Additions' config.yml
> 
> You can also use any kind of condition in groups.yml (https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders)

**First I tried it as `"show-by-default: true" `. The player's nametag was not hidden even though I was in the area. Finally I set it to `"show-by-default: false"`, it worked but it didn't work even though I entered the zone. Minecraft Version: 1.12.2**

![image](https://user-images.githubusercontent.com/89253304/184434423-53145ffe-e905-4144-a7b4-f56104253d78.png)

![image](https://user-images.githubusercontent.com/89253304/184434335-fdb7f3bf-e081-43b2-a54f-ee2d077fbea9.png)

![image](https://user-images.githubusercontent.com/89253304/184434231-cd0c1668-0aab-44ee-8f43-6a37d75b4e99.png)

![image](https://user-images.githubusercontent.com/89253304/184434701-bec2e832-2710-4f21-a10f-33d52f583b19.png)

![image](https://user-images.githubusercontent.com/89253304/184434640-63f9c017-3fbf-4981-a3cc-67d698673780.png)

**Comment by TeQTabanca** [comment]
![image](https://user-images.githubusercontent.com/89253304/184435411-433e82e7-497b-4916-870b-465309900444.png)

**Comment by Tanguygab** [comment]
wait, so when do you want it to show?

**Comment by TeQTabanca** [comment]
only in the lobby

**Comment by Tanguygab** [comment]
try with show-by-default set to false and %placeholder%=lobbyName

**Comment by TeQTabanca** [comment]
yes

**Comment by Tanguygab** [comment]
nevermind, I'm stupid, it's `nametag-condition` in your groups.yml

**Comment by TeQTabanca** [comment]
I didn't understand what you said last

**Comment by Tanguygab** [comment]
here
![image](https://user-images.githubusercontent.com/45695833/184441735-467b593c-35c7-446f-ab7e-bae9f584815b.png)
replace `condition-nametag` by  nametag-condition`

**Comment by TeQTabanca** [comment]
show-by-default: true

> here ![image](https://user-images.githubusercontent.com/45695833/184441735-467b593c-35c7-446f-ab7e-bae9f584815b.png) replace `condition-nametag` by `nametag-condition`

**It works now but when I do `"show-by-default: true" `it doesn't hide the player's nametag while in the lobby area.**

**Comment by Tanguygab** [comment]
use != in the condition instead of =
