### ISSUE TITLE
Issue with ItemsAdder

### ISSUE THREAD

**Issue by WarnDa** [NEZNAMY/TAB#678]
### Server version

Pufferfish 1.19.2

### TAB version

Build #453

### Describe the bug

The placeholders that should return a tag from itemsadder doesn't work, you have to use the raw name created by itemsAdder.

In ItemsAdder when you create a tag and you want to use it in chat/other, you need to use it's name, it's created in config example :diamond_1: and when you put it somewhere it automatically put the tag.
But I'm using it in LuckPerms to make custom tags to each ranks, and I want to apply this to the prefix in tab.
So In luckperms I set the prefix as :diamond_1: 
![image](https://user-images.githubusercontent.com/31826333/184457725-942befa6-9bcb-497c-b301-9630f0c98c98.png)
and then I use %luckperms_primary_group_name% to display them in chat or TAB

![image](https://user-images.githubusercontent.com/31826333/184457130-cd0db8a5-fce3-4e70-9386-b33346187bae.png)
But tab refuse to display the icon, it works on my other plugins (deluxemenus, deluxechat, etc.) but not in tab.

In TAB the only way I have to display a custom tag is using the itemsadder name :diamond_1:
But impossible for me as player get differents tags and I can't just create a group for each player.

### Expected behavior

TAB should parse the placeholder and it should return the custom tag

### Steps to reproduce

- Use ItemsAdder
- Add a custom tag
- Parse the tag in TAB, it will show nothing

- use /papi parse to parse this placeholder, it will work

### Additional info

Using ItemsAdder 3.2.3f

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
je te conseille plutôt de mettre le placeholder dans ton tagprefix au lieu du customtagname, juste pour l'esthétique et que la config soit mieux organisé ¯\_(ツ)_/¯

Sinon, pour ItemsAdder, va dans ta config.yml de TAB et ajoute %luckperms_primary_group_name% dans `placeholder-output-replacements` et remplace `:diamond_1:` par `%img_diamond_1%`
Fait ça pour tout les groupes possibles (genre si t'as un :diamond_2:, tu fait la même, tu remplaces par %img_fiamond_2% etc...

**Comment by WarnDa** [comment]
> je te conseille plutôt de mettre le placeholder dans ton tagprefix au lieu du customtagname, juste pour l'esthétique et que la config soit mieux organisé ¯_(ツ)_/¯
> 
> Sinon, pour ItemsAdder, va dans ta config.yml de TAB et ajoute %luckperms_primary_group_name% dans `placeholder-output-replacements` et remplace `:diamond_1:` par `%img_diamond_1%` Fait ça pour tout les groupes possibles (genre si t'as un :diamond_2:, tu fait la même, tu remplaces par %img_fiamond_2% etc...

merci de l'aide (pour le premier point je viens de voir, je dois refaire tout au propre car mon tab était un giga bordel avant, je simplifie tout, et j'étais bloqué au début justement)

Et pour la config j'ai bien suivi comme indiqué mais j'ai une belle petite erreur :
https://pastebin.com/P6yEypGG
`placeholder-output-replacements:
  '%luckperms_primary_group_name%':
    ':diamond_1:': '%img_diamond_1%'
    ':diamond_2:': '%img_diamond_2%'`

**Comment by Tanguygab** [comment]
envoie ta config

**Comment by WarnDa** [comment]
After checking discord, issue found, we can close this, big thanks to @Tanguygab

**Comment by zettend** [comment]
It still doesn't work for me:
![image](https://user-images.githubusercontent.com/47987619/203668723-8cb2f5a9-37b0-471b-b75c-5f7bebdf5dba.png)

My Config:
![image](https://user-images.githubusercontent.com/47987619/203668785-3bc524c9-189d-414a-affe-b3f57da256a2.png)

Parse Command:
![image](https://user-images.githubusercontent.com/47987619/203668870-a04aaa63-64b9-413f-ac12-88297c8aa12c.png)

**Comment by NEZNAMY** [comment]
%luckperms**-**prefix% and %luckperms**_**prefix% is not the same. Again, support is not provided in github issues.
