### ISSUE TITLE
Tab using Tag instead of Tab prefix

### ISSUE THREAD

**Issue by InsideIntel** [NEZNAMY/TAB#679]
### Server version

1.18.2

### TAB version

3.1.4

### Describe the bug

I have quite a few groups who have a different tag in the tab list and their nametag, Every once in a while, it gives me tagprefix on the tablist, instead of tabprefix on tablist. It never gives tabprefix on nametag (which is good), but tagprefix on tablist. 

### Expected behavior

I want tagprefix to only be as a tag for nametags, not tablist, 

### Steps to reproduce

Step 1:
Create a few groups (with luckperms).
Step 2:
Add groups to groups.yml (TAB plugin)
Step 3:
Give groups a tabprefix and a tagprefix 
Step 4: 
Restart server
Step 5:
Join server and press tab

Folder (TAB jar included):
[Tab Plugin.zip](https://github.com/NEZNAMY/TAB/files/9331422/Tab.Plugin.zip)

### Additional info

Youtube Video of joining server after a restart:

https://www.youtube.com/watch?v=xmhmUPlLIOo

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You decided to disable anti-override, which causes this. Configure your other plugins properly or enable it back like it is by default.

**Comment by InsideIntel** [comment]
It still does it when it's enabled.

**Comment by NEZNAMY** [comment]
Send your new config.

**Comment by InsideIntel** [comment]
Sorry about that, i'm wrong, i just didn't save it, my bad!
