### ISSUE TITLE
Placeholder for staff not working

### ISSUE THREAD

**Issue by Dejvi1** [NEZNAMY/TAB#681]
### Server version

1.19.1

### TAB version

latest

### Describe the bug

%staffonline%  doesnt work
papi is true in config 

![image](https://user-images.githubusercontent.com/58938630/184687486-982b88e1-846a-43df-9d95-414ebfc610a8.png)

### Expected behavior

Show staff members

### Steps to reproduce

Reinstall 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
latest is not a version

**Comment by Dejvi1** [comment]
sorry 5.6.3

**Comment by Tanguygab** [comment]
uh what, TAB only goes up to 3.1.4 o_O
make sure you're using the right plugin
