### ISSUE TITLE
Error with TAB and the 1.19.2-R0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Threshian** [NEZNAMY/TAB#682]
### Server version

Paper 1.19.2

### TAB version

3.1.4

### Stack trace

[TAB] Unknown server version: 1.19.2-R0.1-SNAPSHOT! Plugin may not work correctly.

### Steps to reproduce (if known)

Install the latest version of Tab
Start the server
The error appears in the console
The scoreboard does not work

### Additional info

If the problem is due to the fact that the plugin does not work in version 1.19.2, please change your title on the Built By Bit site as it says "TAB [1.5.x - 1.19.2] (free trial) 3.1.4"

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
The plugin works fine on 1.19.2. You can ignore the message. If you don't want the warning, use the latest dev builds https://github.com/NEZNAMY/TAB/actions
abou the scoreboard, send your config

**Comment by Tanguygab** [comment]
essaye de désactiver `scoreboard.respect-other-plugins`

**Comment by Tanguygab** [comment]
t'as essayé le dev build?

**Comment by Threshian** [comment]
Yep, j'ai pris le dernier "[Bukkit - Include 1.19.2 in supported version range](https://github.com/NEZNAMY/TAB/actions/runs/2864173579)"

**Comment by Threshian** [comment]
https://i.imgur.com/G4bvyRi.png

**Comment by Tanguygab** [comment]
Je sais pas vraiment, je vois pas de plugins qui pourrait affecter.
T'as un client custom ou tu lances le jeu via le launcher officiel?
Et tu peux envoyer tes logs?

**Comment by Threshian** [comment]
Je joue via Lunar Client. Ca vient peut être de là

**Comment by Tanguygab** [comment]
😂 tu peux pas savoir le nombre de bugs qu'on a eu avec ce client
Essaye en vanilla

**Comment by Threshian** [comment]
C'est bon, j'ai trouvé, le scoreboard était désactivé dans Lunar xD
Désolé du dérangement et merci pour l'aide ^^

**Comment by Tanguygab** [comment]
mdr, tkt, bonne soirée 👋
