### ISSUE TITLE
Players not appearing on tab / wrong priority

### ISSUE THREAD

**Issue by BrianMayMC** [NEZNAMY/TAB#685]
### Server version

1.19.2

### TAB version

3.1.4

### Describe the bug

Sometimes, with some players, their tag does not appear properly on the tablist. Also, sometimes the priority is messed up and someone with a higher priority is displayed under someone with a lower priority. Sometimes placeholders are missing for some players as well.

### Expected behavior

Players are supposed to appear on tab properly with full tags and placeholders in the right order (according to the priority in the config files.

### Steps to reproduce

Step 1: Get a 1.19.2 Pufferfish server online with TAB and preferably Luckperms
Step 2: Create multiple groups for tab with luckperms and get multiple people online and add them to different groups.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config. This is definitely misconfiguration and not a bug.

**Comment by BrianMayMC** [comment]
https://pastebin.com/uvHMpbJ4

That's my config.yml

**Comment by Tanguygab** [comment]
anti-override: false

**Comment by BrianMayMC** [comment]
thank you, I believe that fixed it. Will make reopen if not.
