### ISSUE TITLE
Geyser Support

### ISSUE THREAD

**Issue by Tazler89** [NEZNAMY/TAB#687]
### Server version

1.19.2

### TAB version

3.1.3

### Describe the bug

When viewing as Geyser player on bedrock, player name don't go away, just hovers over the top, it moves back and forth but this not really a problem, it seems to not be removing the normal name tag when the stand is put on.

### Expected behavior

As java

### Steps to reproduce

unlimited names on.
view player from bedrock client via geyser.
move other player back and forth.

### Additional info

can't seem to stop it have turned lots options on and off, when i turn off scoreboard team, it stops but thats as the stand gets removed and unlimited don't work anymore

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

![image](https://user-images.githubusercontent.com/51469267/185717120-85a5c3c2-df8a-4cbf-8d7c-0c533643c756.png)

**Comment by Camotoy** [comment]
Can you provide a Geyser dump?

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by Tazler89** [comment]
https://dump.geysermc.org/lBZtwmm4XPVQMCWJ2ttbaX0O3DzTiAu7

**Comment by Camotoy** [comment]
And can you list `/plugins` and `/version` from the backend server this happens on, please?

**Comment by Tazler89** [comment]
![image](https://user-images.githubusercontent.com/51469267/185798348-fcb412f0-25ce-4a72-8f04-607f8189ad8d.png)

**Comment by Camotoy** [comment]
With Waterfall and Paper 1.19.2, I tried putting TAB on the backend server and connecting through Waterfall, but everything appears to be working fine. Maybe another plugin conflict?

**Comment by MrGraycat** [comment]
Are you using a 5.0.0 snapshot version of protocollib? we've seen some issues with that.

**Comment by Tazler89** [comment]
> Are you using a 5.0.0 snapshot version of protocollib? we've seen some issues with that.

ya not seen any other to use

**Comment by Tazler89** [comment]
well its not lib as i removed the plugin and its still the same

**Comment by Tazler89** [comment]
> With Waterfall and Paper 1.19.2, I tried putting TAB on the backend server and connecting through Waterfall, but everything appears to be working fine. Maybe another plugin conflict?

was that with bedrock account, it looks fine on the java client, its the bedrock client thats seeing the duplicate name, have just updated it to the latest LIB and removed Lib no change updated to the latest paper also no change.

**Comment by Camotoy** [comment]
Yes, this was a Bedrock player viewing a Java player.

**Comment by Tazler89** [comment]
i will try a new install with no other plugins and give that a go then add 1 by 1

**Comment by Tazler89** [comment]
ok found it its a mix of 2 things, Luckperms and CMI, if one of them is removed problem go away but when both of them are on together is when this happens, going to disabled all the models of CMI and see if i can find what one it is

**Comment by Tazler89** [comment]
`# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  header:
  - '&3&lServer name'
  - '&7&l>> %animation:Welcome%&3 &l%player%&7&l! &7&l<<'
  - '&7Online players: &f%online%'
  - '&6Online staff: &e%staffonline%'
  - ''
  - '%animation:MyAnimation1%'
  footer:
  - '%animation:MyAnimation1%'
  - '%animation:time%'
  - '%animation:ping-tps%'
  - '&7&l Used memory: %memory-used% MB / %memory-max% MB'
  - ''
  - '&7Visit our webpage %animation:web%'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
scoreboard-teams:
  enabled: true
  enable-collision: false
  invisible-nametags: true
  anti-override: false
  sorting-types:
  - GROUPS:default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-in-servers: []
yellow-number-in-tablist:
  enabled: true
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: false
  number: '%rel_simpleclans_color%Taz'
  text: '%rel_simpleclans_color%Health'
  disable-in-worlds:
  - disabledworld
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
ping-spoof:
  enabled: false
  value: 0
fix-pet-names:
  enabled: false
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
    '%server_unique_joins%': 5000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
`

**Comment by Tazler89** [comment]
that fixed it, that is freaky the reason it was on false as i had been turning everything on and off trying to get rid of it, i did change this true false nothing changed, it could be as i was just reloading the plugin and not restarting the server after every single change, i even removed the foles and let it remake the config files so in your last one it must have defaulted to false or something i have no idea, but Thank you :D will be one of them unknowns
