### ISSUE TITLE
CUSTOM RESOURCE PACK FONTS

### ISSUE THREAD

**Issue by DarkmayGOD** [NEZNAMY/TAB#688]
Hi, does it support custom fonts in resource pack?

/
CZ:
Zdravim, podporuje plugin vlastní fonty v resource packu?

**Comment by NEZNAMY** [comment]
font feature of minecraft 1.16+ is not supported by the plugin.

**Comment by DarkmayGOD** [comment]
Why it was deleted from plugin?

**Comment by NEZNAMY** [comment]
It was not deleted, it was never available.

**Comment by DarkmayGOD** [comment]
Okay, so could you add it?

**Comment by NEZNAMY** [comment]
No, feature requests are closed.

**Comment by DarkmayGOD** [comment]
oh, okay
