### ISSUE TITLE
Velocity not working

### ISSUE THREAD

**Issue by TDSTOS** [NEZNAMY/TAB#689]
### Server version

Velocity 3.1.1

### TAB version

3.1.4

### Stack trace

![image](https://user-images.githubusercontent.com/100531026/185805953-8f3d1a73-d8fb-4b72-bd8c-811ed2018812.png)

### Steps to reproduce (if known)

Step 1: put the TAB plugin into the velocity plugins folder

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/185806027-e8163855-9175-4c7c-a8da-fbc8e48b6aa8.png)

**Comment by TDSTOS** [comment]
than why has the source code velocity in it??

**Comment by TDSTOS** [comment]
in the jar folder of the source code is the platform velocity definitely registered

**Comment by Tanguygab** [comment]
Because old versions had (limited) support for Velocity, but since a few months, NEZNAMY didn't want to bother with it anymore 
because of bugs and unsupported features and decided to disable the velocity module. 
You can still clone the repo and enable back the module, but we won't provide support for it.

**Comment by NEZNAMY** [comment]
We do not provide support for compiling the plugin, let alone unsupported modules.

**Comment by gadget78** [comment]
@Tanguygab mentioned about cloning/forking and to re-enable it ... (as github compiles it as a action)
so the github only complies the core, and not plugins/modules ?
