### ISSUE TITLE
Request: Toggling nametag preview for other players

### ISSUE THREAD

**Issue by Soufreur78** [NEZNAMY/TAB#690]
Hello, I really want to thank you for this great plugin!

I wanted to know if it was possible to add something to the "/tab nametag preview" command.

It would be nice to be able to perform it on other players like the command "/tab scoreboard [on/off/toggle] [player] [options]"

So the command could be like this "/tab nametag preview [player] [options]". With the option for silent toggling.

Thank you again for your work, have a nice day!

(I am French so I used a little google translation)

**Comment by Soufreur78** [comment]
Sorry, I just translated the main page and saw that it's not allowed to put requests here.

So you can closed sorry. (but the feature could be nice)

**Comment by Tanguygab** [comment]
Essaye le nouveau dev-build https://github.com/NEZNAMY/TAB/actions/runs/2904651349 (quand il est prêt), ça devrait marcher avec
- /tab nametag preview [player] (-s)
- /tab nametag toggle [player] (-s)

**Comment by Soufreur78** [comment]
ça marche parfaitement ! 
Je te remercie beaucoup :)
