### ISSUE TITLE
Request, Bedrock Support TAB

### ISSUE THREAD

**Issue by Tazler89** [NEZNAMY/TAB#692]
Hello, thanks for the plugin, i know its been around for years and thats amazing, with the bringing of geyser more and more cross platform servers are popping up, mine included, as you know, bedrock don't have a TAB, with this i was wondering as you do with BOSSBAR using /toggle could it be so that bedrock players could use /toggle to also view the same Tab that java can see ?, i am trying to find a way to make this possible by using maybe the scoreboard if it can show online play list and be toggled or showing the normal one to bedrock using toggle.

Thank You.

**Comment by Tazler89** [comment]
could it not be shown the same as the scoreboard bit on the right ? as this works for bedrock

**Comment by Tanguygab** [comment]
if you want to edit the scoreboard, you can in the config.yml
but the tablist like in Java isn't a thing on Bedrock

**Comment by Tazler89** [comment]
can the scoreboard be toggled ? don't want it all ways showing if i am to use it as a player list for bedrock

**Comment by Tazler89** [comment]
> /sb

Wicked thank you, how would i get the player list into the scoreboard, i can't find anything for it.

**Comment by NEZNAMY** [comment]
This is an issue tracker, support is not provided here. Plugin cannot edit bedrock edition's client code and add missing features.
