### ISSUE TITLE
Conditional placeholders don't parse placeholders as a output

### ISSUE THREAD

**Issue by Dagrond** [NEZNAMY/TAB#694]
### Server version

Purpur 1.19.2

### TAB version

3.1.4

### Describe the bug

It seems that in TAB 3.1.4 placeholders inside conditional placeholders does not work. 
My condition:
![image](https://user-images.githubusercontent.com/30177675/186426258-15d24ec7-fddf-4cfd-b576-36bcaaf3119b.png)
Output of single single placeholder to prove that this placeholder actually works:
![image](https://user-images.githubusercontent.com/30177675/186426578-d65bfaf7-b67c-4fe6-94ff-a69fd04465b2.png)
Output of this condition:
![image](https://user-images.githubusercontent.com/30177675/186426842-8c2229bf-7b72-46cc-94fc-f3a84a0176cb.png)

### Expected behavior

This was working on some older version. This is example with TAB 3.1.1 on purpur 1.18.2 and placeholderAPI 2.11.2:
![image](https://user-images.githubusercontent.com/30177675/186427519-65421401-13e9-4ba3-90cd-3583341f2d3a.png)

### Steps to reproduce

1. Install TAB 3.1.4 on purpur 1.19.2 along with PlaceholderAPI 2.11.2
2. Write some condition which output is another placeholder
3. View that condition using /papi parse me

### Additional info

1. Note that both (working and not working) examples are made on the same version of PlaceholderAPI which is 2.11.2, the difference is only between minecraft and TAB versions.

2. I've tried some other placeholders from other plugins, and none of them works as a output of TAB's conditional placeholders (but they work with /papi parse or anywhere else, even on TAB's scoreboard etc.)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
can you do /tab parse me %eternaltags_tag% and /tab parse me %condition:tag% and send the outputs?

Also, do you have a placeholder-errors.log file in your TAB folder?
