### ISSUE TITLE
Allow placeholders in layout's skin

### ISSUE THREAD

**Issue by soladev** [NEZNAMY/TAB#696]
Hi, 

I wanted to know if it could be possible to add placeholders in a layout's skin for a fixed slot. 

My use case for this : I split the tablist in half, the first half displaying a list of gamemode-specific informations and the second half displaying the players, like this : 
![image](https://user-images.githubusercontent.com/16501931/186831117-bae25904-4939-4122-90e3-2485b7aa6ebd.png)

So for aesthetic purposes I want to make the skin of a line in the first half the same color as the information displayed, with the possibility to gray-out an information, like on the picture above. But I want to use placeholders for this. 

 As you can see above, I already made a kinda-working list like I described, but it consists of editing the layout.yml file and reloading TAB, which is far from ideal. 

I guess that it could be a bother to make the skin update itself, but it could really help me to make it working. Either way, you've done an excellent and qualitative job with your plugin, so thank you for that !

**Comment by NEZNAMY** [comment]
Feature requests are closed as I am looking to quit MC, not go deeper in.
