### ISSUE TITLE
Bug in case of mass charge

### ISSUE THREAD

**Issue by Press22** [NEZNAMY/TAB#699]
### Server version

Spigot 1.18.2

### TAB version

3.1.4

### Describe the bug

When we get a lot of players (+150), TAB is bugged and players are not correctly sorted.

### Expected behavior

![image](https://user-images.githubusercontent.com/112178125/187205685-053ed523-4580-46de-9553-626a2b8d1259.png)
As you can see, when we have a lot of players on one server, TAB is bugged

### Steps to reproduce

Just have a lot of players

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by Press22** [comment]
[TAB.zip](https://github.com/NEZNAMY/TAB/files/9444659/TAB.zip)
Here you get it :)

**Comment by Press22** [comment]
When I was with less connected I haven't the issue and I tried to dwngrade my version

**Comment by NEZNAMY** [comment]
Error log says you are using 3.1.2

**Comment by Press22** [comment]
Yes because I just downgrade my version this night but I've the same issue on 3.1.4

**Comment by NEZNAMY** [comment]
does /tab reload fix it? Does /tab cpu show a number similar to 100% or is it fine?

**Comment by NEZNAMY** [comment]
Show plugin list.

**Comment by Press22** [comment]
![image](https://user-images.githubusercontent.com/112178125/187207260-0b9b5d25-dbd7-4546-9583-6e65f3a4eb29.png)

**Comment by NEZNAMY** [comment]
There you go. Fix your placeholders and try again. Tutorial is on the wiki.

**Comment by Press22** [comment]
Ok thank you !
It's because my placeholder aren't optimized ?

**Comment by NEZNAMY** [comment]
Correct. Wiki explains it.

**Comment by Press22** [comment]
Ok thank you !
Have a nice day :p
