### ISSUE TITLE
Tab is not recognizing users from different groups across servers.

### ISSUE THREAD

**Issue by Jaimss** [NEZNAMY/TAB#7]
**Server version**
BungeeCord 1.14.4
Survival: 1.14.4
Skyblock: 1.14.2
Hub: 1.14.4

**Plugin version** ("latest" is not a version)
2.4.15 on all servers, not on BungeeCord.

**Describe the bug**
I am using UltraPermissions on Bungeecord and I have groups on specific servers. My skyblock has some groups and my survival has some other groups. If a player buys a rank on skyblock they only get it on skyblock. When they log onto skyblock their name in tab will change color to show the rank they purchased. If they switch over to another server, it still shows the same rank color not the rank color from their current server.

**How to reproduce**
Add a player to a group on one server and then have them switch servers.

**Expected behavior**
Use the %rank% value for the rank that is actually on the server.

**Actual behavior**
Uses the %rank value from the server which they have the highest rank on.

**Additional info** (errors, screenshots, ...)
None.

**Comment by NEZNAMY** [comment]
Looks like UPerms API is returning wrong group. Try using /tab debug [player] on someone who does not show correctly at the time and check if group is correct.

**Comment by NEZNAMY** [comment]
UPerms API bug, can be avoided by using full group list and letting plugin choose it from list.
