### ISSUE TITLE
Placeholder "%tps%" will over 20.

### ISSUE THREAD

**Issue by WMGameLive** [NEZNAMY/TAB#70]
**Server version**
1.14.4

**Plugin version** ("latest" is not a version)
v2.5.4

**Describe the bug**
Placeholder %tps% will over 20.

**How to reproduce**
just use %tps% in config.

**Expected behavior**
tps should not over 20.

**Actual behavior**
over 20.

**Additional info** (errors, screenshots, ...)
https://imgur.com/a/mEooHZ9

**Comment by NEZNAMY** [comment]
Might be a result of TPS catchup. I will add a check so it won't display higher tha 20.
