### ISSUE TITLE
Rank Weight

### ISSUE THREAD

**Issue by zZGuardian** [NEZNAMY/TAB#704]
### Server version

1.19.2

### TAB version

3.0.2

### Describe the bug

I'm using LuckPerms for rank weight, but the Tab doesn't seem to read some of the rank's weights. I really love the plugin, please do help me.

### Expected behavior

In the Tab, the rank display for other ranks are literally scrambled, some of them are in order but most of them are not.

### Steps to reproduce

Have no idea what this question is about

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-setup-weights-priorities

https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups

**Comment by zZGuardian** [comment]
This worked, thanks so much
