### ISSUE TITLE
Players dissapearing on changing bungee servers.

### ISSUE THREAD

**Issue by kiriles** [NEZNAMY/TAB#705]
### Server version

1.19.2

### TAB version

3.1.4

### Describe the bug

Everything seems fine but when i set global playlist to on and i have added bungee tab support to my other servers, they see everyone from previous server they left but the players leave the server are no longer seen in the global tablist from the server previous server they were online.

### Expected behavior

It should show global players when players leave the current bungee server to another server in the bungeecord.

### Steps to reproduce

I added Tab bridge,
I also enabled global playlist and we tested it ingame.

### Additional info

Thank you for creating such a good plugin!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Players who leave the proxy are not supposed to be seen. Are you using waterfall?

**Comment by kiriles** [comment]
Yes sir i am!

**Comment by kiriles** [comment]
You are really fast with responding, respect man.

**Comment by NEZNAMY** [comment]
send your waterfall.yml

**Comment by kiriles** [comment]
plugin_channel_name_limit: 128
use_netty_dns_resolver: true
disable_modern_tab_limiter: true
log_initial_handler_connections: true
throttling:
  tab_complete: 1000
game_version: ''
disable_tab_list_rewrite: true
registered_plugin_channels_limit: 128
disable_entity_metadata_rewrite: false

**Comment by NEZNAMY** [comment]
disable_tab_list_rewrite: true
set it to false

**Comment by kiriles** [comment]
Thank you very much ! Good work and have a nice weekday!

**Comment by Tanguygab** [comment]
Is this resolved @kiriles ?

**Comment by NEZNAMY** [comment]
Updated wiki https://github.com/NEZNAMY/TAB/wiki/Compatibility#compatibility-issues-with-other-plugins--forks

**Comment by kiriles** [comment]
> Is this resolved @kiriles ?

This is resolved buddy!
