### ISSUE TITLE
Garbage accumulating and not being cleared

### ISSUE THREAD

**Issue by Gabo6480** [NEZNAMY/TAB#709]
### Server version

Paper 1.19.2

### TAB version

3.1.4

### Describe the bug

I'm having a problem in my server where when I install TAB, garbage keeps accumulating until the whole ram gets filled. The only way I can clear this ram is either restarting or using spark's `/spark heapsummary` command which trigger the GarbageCollector manually. 

I should note that I'm using quite a lot of Relational Papi placeholders and custom JavaScript placeholders on the player's nametag, and it apparently becomes more severe when loading more chunks and when there are more players online. 

### Expected behavior

Garbage not being able to be cleared

### Steps to reproduce

Step 1: Install TAB with PAPI
Step 2: Use placeholders that produce a lot of garbage internally in the player's nametag?
Step 3: Play with many players.
Step 4: Flying around generating chunks seems to make it worse.
Step 5: Not profit.

### Additional info

Plugin Info:
  Auto-Tune                      [Version: 0.14.0]
  BalancedVillagerTrades         [Version: 2.0-beta7]
  BedrockPlayerManager           [Version: 1.4]
  ChatInjector                   [Version: 1.0.6]
  CoreProtect                    [Version: 21.2]
  Corpses                        [Version: 2022.10]
  CraniumCollection              [Version: 1.1]
  DeathMessages                  [Version: 1.4.15]
  DiscordSRV                     [Version: 1.26.0-SNAPSHOT]
  EmojiReplacer                  [Version: 1.0]
  Essentials                     [Version: 2.19.7]
  EssentialsAntiBuild            [Version: 2.19.7]
  EssentialsChat                 [Version: 2.19.7]
  EssentialsSpawn                [Version: 2.19.7]
  Factions                       [Version: 1.6.9.5-3.0.5-RC]
  Geyser-Spigot                  [Version: 2.0.7-SNAPSHOT]
  Harbor                         [Version: 1.6.3]
  InteractiveChat                [Version: 4.2.3.1]
  InteractiveChatDiscordSrvAddon [Version: 4.2.3.1]
  ItemsAdder                     [Version: 3.2.3m]
  LoneLibs                       [Version: 1.0.21]
  LuckPerms                      [Version: 5.4.46]
  PickMeUp                       [Version: 1.3.7]
  PlaceholderAPI                 [Version: 2.11.2]
  PlayerNPC                      [Version: 2022.8]
  ProtocolLib                    [Version: 5.0.0-SNAPSHOT-b600]
  ReviveMe                       [Version: 2.3.3]
  ServerBooster                  [Version: 1.1.3]
  SkinsRestorer                  [Version: 14.2.3]
  StreamingDrops                 [Version: 10.6]
  TAB                            [Version: 3.1.4]
  Vault                          [Version: 1.7.3-b131]
  ViaBackwards                   [Version: 4.4.2]
  ViaVersion                     [Version: 4.4.2]
  ViaVersionStatus               [Version: 3.11]
  WhitelistPlayers               [Version: 1.0.3]
  WorldEdit                      [Version: 7.2.12+6240-87f4ae1]
  emotecraft                     [Version: 2.2.0]
  floodgate                      [Version: 2.2.0-SNAPSHOT (b73-4f36112)]
  nLogin                         [Version: 10.1.7]
  spark                          [Version: 1.9.25]
  voicechat                      [Version: 1.19.2-2.3.6]
  voicechat_interaction          [Version: 1.1.0]

Papi Expansions:
  changeoutput    [Author: Kaliber, Version: 1.2.2]
  deathmessages   [Author: [Joshb_, MrShawn], Version: 1.4.15]
  discordsrv      [Author: [Scarsz, Androkai, Vankka], Version: 1.26.0-SNAPSHOT]
  factionsuuid    [Author: drtshock, Version: 1.6.9.5-3.0.5-RC]
  iaplayerstat    [Author: LoneDev, Version: 1.0.1]
  img             [Author: LoneDev, Version: 1.0.1]
  interactivechat [Author: loohp, Version: 1.0.0]
  javascript      [Author: clip, Version: 2.1.0]
  luckperms       [Author: Luck, Version: 5.1-R2]
  player          [Author: clip, Version: 2.0.3]
  playerlist      [Author: Tanguygab, Version: 2.1]
  relcon          [Author: aBooDyy, Version: 1.1]
  releval         [Author: Gabo6480, Version: 1.1]
  reviveme        [Author: FavioMC19, Version: 2.3.3]
  servertime      [Author: GoldenGamerZone, Version: 1.0]
  spark           [Author: Luck, Version: 1.9.25]
  streamingdrops  [Author: [Morelaid], Version: 10.6]
  string          [Author: BlitzOffline, Version: 1.0.0]
  tab             [Author: NEZNAMY, Version: 3.1.4]
  vault           [Author: clip, Version: 1.7.1]
  voicechat       [Author: Max Henkel, Matthew Wells, Version: 1.19.2-2.3.6]
  
https://spark.lucko.me/Hn62WMKB4y
![image](https://user-images.githubusercontent.com/60194781/190333467-4290d64a-c7e1-411c-923c-2089ebdb567e.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send heap dump if you think TAB has a memory leak.

**Comment by Gabo6480** [comment]
https://drive.google.com/file/d/1R-6Xk9q4tP6X-SqmNaBEyGaw85qm-5Jr/view?usp=sharing

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/190626971-2fa178b1-d4e3-4603-8d08-667e82d2fd30.png)
While the first object references the second one, so that would be a total of something over 20MB. Far from 5GB.
![image](https://user-images.githubusercontent.com/6338394/190627341-0eb51360-4471-4d98-bf00-97999fe40768.png)
Only 2 player objects are in the memory, assuming you had 2 online players, no memory leak is present.

**Comment by Gabo6480** [comment]
Then what is filling that much space?

**Comment by NEZNAMY** [comment]
Chunks and other things not related to TAB.

**Comment by Gabo6480** [comment]
What tool are you using to visualize the heapdump?

**Comment by Gabo6480** [comment]
Then again, It might be that TAB is not the direct culprit, but an interaction between TAB and something else. Because the garbage problem only happens when I have TAB present.

**Comment by NEZNAMY** [comment]
I used YourKit.

**Comment by Gabo6480** [comment]
Or what do you think could be going on? If it isn't TAB or a negative interaction of it, then either PAPI or the placeholders could be at fault.

**Comment by Gabo6480** [comment]
Alright, the first suspect has appeared https://github.com/PlaceholderAPI/Javascript-Expansion/issues/61

**Comment by NEZNAMY** [comment]
Perfect, can we close this? Or can you try without javascript placeholders?
