### ISSUE TITLE
Error with LuckPerms.

### ISSUE THREAD

**Issue by RaulyYahaira** [NEZNAMY/TAB#71]
**Server version**
Spigot 1.8.8

**Plugin version** ("latest" is not a version)
TAB v2.5.4

**Describe the bug**
When I try to change any group tabprefix or tagprefix, it don't do nothing and creates a file "errors.txt". In the error says that the plugin can't found my group of LuckPerms.

**How to reproduce**

**Expected behavior**

**Actual behavior**
The plugin don't do any change when I reload it, or restart the server.

**Additional info** (errors, screenshots, ...)
![Captura de pantalla 2019-12-06 a las 20 30 38](https://user-images.githubusercontent.com/58607983/70350583-482f9f00-1867-11ea-8bcb-086cc75fda75.png)

**Comment by NEZNAMY** [comment]
LuckPerms had a non conpatible API update. New jar with new API compatibility is available on discord.

**Comment by SmartHosting** [comment]
what is the discord?

**Comment by SmartHosting** [comment]
cause I have the same problem

**Comment by NEZNAMY** [comment]
http://prntscr.com/q7uxfk
