### ISSUE TITLE
[TAB v2.9.2] yellow number only accepts numeric values! (Attempted to use "{enabled=true, value=15, disable-in-worlds=[disabledworld]}")

### ISSUE THREAD

**Issue by RevriK27cm** [NEZNAMY/TAB#711]
### Server version

Paper 1.17

### TAB version

2.9.2/3.1.4

### Stack trace

[TAB v2.9.2] yellow number only accepts numeric values! (Attempted to use "{enabled=true, value=15, disable-in-worlds=[disabledworld]}")

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/190861848-8a80a1b4-0680-4dad-8031-1333a85a07d5.png)
you are 1 year out of date.
