### ISSUE TITLE
Time Problem

### ISSUE THREAD

**Issue by NevereZ** [NEZNAMY/TAB#712]
### Server version

PaperSpigot 1.17.1

### TAB version

3.1.2

### Describe the bug

How do i change time?
Currently, it is 16:37 at my place but on server is 14:37

### Expected behavior

Diffrent time.

### Steps to reproduce

idk

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
time-offset: 2
Please stop abusing issue tracker for support.
