### ISSUE TITLE
Supporting Velocity as Waterfall is able to be knocked offline

### ISSUE THREAD

**Issue by TomLewis** [NEZNAMY/TAB#713]
Hello, I have been a massive fan of Tab for ages and its an amazing tool to work cross server! I recently have been in the position where my server is being attacked 24/7 by "stress testing" websites, Neither Bungee/waterfall/Flamecord is able to sustain these attacks which is forcing a lot of people to move to Velocity as it can stand them.

I noticed in your release notes you said this:

> Second, I want to inform Velocity users that Velocity support is not officially advertised and although the plugin works, support will be dropped in the future for both objective and subjective reasons.

Which is a massive shame, as there is no good alternative to Tab for cross server tablists & overhead names! I'm now stuck on what I can do to replace Tab, In a perfect world Tab would be updated for Velocity compatibility due to the nature of not being able to run a Bungee based proxy due to its flaws to be attacked.

I'm hoping that you will reconsider velocity compatibility.

Thank you

**Comment by Tanguygab** [comment]
https://gist.github.com/NEZNAMY/21c1aabe57a0a462ee175386c510fdf8

**Comment by TomLewis** [comment]
Thank you for the background. 

I did read just now on the Wiki that it may be possible to do cross-server without having a proxy plugin? 
Under Bungeecord https://github.com/NEZNAMY/TAB/wiki/Installation
It says I can install on Each server OR on the proxy, if I install on each server, can I still retain showing players in the tablist from each server?

**Comment by NEZNAMY** [comment]
Global playerlist is a proxy-only feature and will not be implemented on backend installation.

**Comment by TomLewis** [comment]
I assumed as much. This is majorly disappointing. As I will lose cross server tab lists because velocity isn't supported because of their toxic discord, and I cant use any Bungee server software because of how poorly it handles attacks. 

I'm at a loss for what to do now.

**Comment by NEZNAMY** [comment]
Life is hard. However, you are not the only server owner in the world who is running a network. Many faced this issue before you and many will face it after you as well. Try asking others what they did.

**Comment by TomLewis** [comment]
If you know of a solution or alternative I can switch to, that would be very much appreciated, from what I have seen nothing matches Tab, and i really like tab.

**Comment by NEZNAMY** [comment]
In short, there is no solution to this.

**Comment by TomLewis** [comment]
How about using your MySQL? All it would need is a table of who's online and what server, but the logic would be, run the server list in that server like normal, but periodically check this table to see if anyone else is online other servers.

**Comment by NEZNAMY** [comment]
That would be very complicated and I am not interested to add any more features to the plugin, let alone something for velocity.

**Comment by TomLewis** [comment]
I meant, without requiring a proxy at all, each server just talks back to the MySQL table.

**Comment by NEZNAMY** [comment]
Yes, I am not interested to go that way just for velocity users.
