### ISSUE TITLE
NameTags are very buggy on GeyserMC players

### ISSUE THREAD

**Issue by roggy666** [NEZNAMY/TAB#715]
### Server version

Paper 1.17.1 + GeyserMC

### TAB version

3.1.4

### Describe the bug

When bedrock players run/jump or move, their tag above head lagging behind them . 

### Expected behavior

Normal behaviour, like on NameTagEdit

### Steps to reproduce

You can check NameTagEdit code, there is no such bug in this plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Disable unlimited nametag mode.
