### ISSUE TITLE
tabprefix/customtabname bug

### ISSUE THREAD

**Issue by m4kii420** [NEZNAMY/TAB#716]
### Server version

Paper 1.18.2

### TAB version

3.1.4

### Describe the bug

**I don't know why but after some time my username doesn't work with hex colors.**
![image](https://user-images.githubusercontent.com/85348361/191112796-aa0de76c-59ed-415b-8de3-ede514f20cb7.png)

**Then after reloading it gets fixed but only for some time**
![image](https://user-images.githubusercontent.com/85348361/191113322-b0f873e2-b9a5-4629-8757-1a67b15ae042.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/85348361/191113851-e8d0b3cb-9ba8-4946-b800-dd5467c19980.png)

### Steps to reproduce

.

### Additional info

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by m4kii420** [comment]
https://wtools.io/paste-code/bFf0

**Comment by NEZNAMY** [comment]
Set line 39 to true.
