### ISSUE TITLE
No Suitable Driver

### ISSUE THREAD

**Issue by Waffl3Development** [NEZNAMY/TAB#717]
### Server version

Paper 1.19.2

### TAB version

3.1.4

### Stack trace

19.09.2022 - 16:43:04 - java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/tab2
19.09.2022 - 16:43:04 - 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
19.09.2022 - 16:43:04 - 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
19.09.2022 - 16:43:04 - 	at TAB.v3.1.4.jar//me.neznamy.tab.shared.config.MySQL.openConnection(MySQL.java:34)
19.09.2022 - 16:43:04 - 	at TAB.v3.1.4.jar//me.neznamy.tab.shared.config.MySQL.<init>(MySQL.java:29)
19.09.2022 - 16:43:04 - 	at TAB.v3.1.4.jar//me.neznamy.tab.shared.config.Configs.<init>(Configs.java:68)
19.09.2022 - 16:43:04 - 	at TAB.v3.1.4.jar//me.neznamy.tab.shared.TAB.load(TAB.java:155)
19.09.2022 - 16:43:04 - 	at TAB.v3.1.4.jar//me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:43)
19.09.2022 - 16:43:04 - 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
19.09.2022 - 16:43:04 - 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
19.09.2022 - 16:43:04 - 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
19.09.2022 - 16:43:04 - 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
19.09.2022 - 16:43:04 - 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
19.09.2022 - 16:43:04 - 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
19.09.2022 - 16:43:04 - 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
19.09.2022 - 16:43:04 - 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
19.09.2022 - 16:43:04 - 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1126)
19.09.2022 - 16:43:04 - 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
19.09.2022 - 16:43:04 - 	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

not fully sure 
I have 2 servers both use MariaDB/MySQL One connects successfully the other gives the error above
it does not matter if the server that does connect is offline or not it produces the same error all the same 
both are hosted on the same machine so logically they both should be able to access the driver

### Additional info

the servers are almost exact twins with a difference of some plugins, none of which should affect TABs ability to connect to MySQL

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Any idea what is the difference between the two servers?

**Comment by NEZNAMY** [comment]
I may or may not have found a fix. I will make an exception and offer you to test it when you join discord.
