### ISSUE TITLE
When using plugin with Citizens, can't hide npc nametag.

### ISSUE THREAD

**Issue by Florixa** [NEZNAMY/TAB#719]
### Server version

spigot 1.19.2

### TAB version

3.1.5

### Describe the bug

When I am using TAB plugin and Citizens, there is a plugin conflict and it doesn't allow me to (/npc name) toggle anymore.
![image](https://user-images.githubusercontent.com/114229578/192075497-59c68139-aee9-4a77-b74a-ace9228a57ab.png)
![image](https://user-images.githubusercontent.com/114229578/192075544-a9bb4086-71d6-4470-97c3-11f10366a70f.png)
It says "Nameplate Visibility set to false" but this conflict doesn't happen with the plugin not installed.

### Expected behavior

TAB plugin should let Citizens Plugin hide name tags of npc's with that command.

### Steps to reproduce

1.Have Citizens and TAB installed on server.
2.Once in game open up chat and do "/npc create (username)"
3.When the npc is summoned type "/npc select (username of npc)"
4.Then open up chat again and type "/npc name" In chat it will say "Nameplate Visibility set to false" but won't hide name.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Make their names different than names of online players. You cannot choose which plugin affects which entities, because they are bound to player names, not entity IDs.

**Comment by Florixa** [comment]
Thanks, it works :) Have a nice day or night.
