### ISSUE TITLE
Double Usernames bug

### ISSUE THREAD

**Issue by SamGamerYT** [NEZNAMY/TAB#722]
### Server version

Purpur 1.19.2

### TAB version

v3.1.5

### Describe the bug

The plugin on Bedrock with geysermc support shows the username double but the double name bug only happens to a few people not everyone.

### Expected behavior

The plugin shouldn't see 2 Name tags being merged into each other and unreadable

### Steps to reproduce

1) Get on Java and make the server supported
2) Get a bedrock alt account and view the Java Account or fellow bedrock account
3) You will see double usernames being merged into each other

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Camotoy** [comment]
Hey; this is *probably* a Geyser bug. Can you make an issue there instead? Thanks.

**Comment by NEZNAMY** [comment]
Closing since issue got moved to Geyser issue tracker as requested.
