### ISSUE TITLE
Bug after restart server

### ISSUE THREAD

**Issue by mani1232** [NEZNAMY/TAB#723]
### Server version

Purpur 1.19.2

### TAB version

3.1.5

### Stack trace

none

### Steps to reproduce (if known)

Join to server and use /cmi vanish
Full restart server
Join to server and see your nickname in tab and overhead 
To fix it again use /cmi vanish

### Additional info

Fix it, pls

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
What's the bug?

**Comment by NEZNAMY** [comment]
According to the description, it's just CMI not remembering vanish status, since a single vanish command will solve it. If it required the vanish command twice then maybe, but not with the current description.
