### ISSUE TITLE
Nickname issue

### ISSUE THREAD

**Issue by Orange661** [NEZNAMY/TAB#724]
### Server version

Pufferfish 1.18.2

### TAB version

3.1.5

### Describe the bug

ok so whenever i do /nick and then i change my nickname my nickname doesnt change on the tab i dont know why and i also have unlimited nametag mode on soo thats a plugin issue ig?

### Expected behavior

the plugin is supposed to change my ign after i do /nick its not like that it just doesnt work as a nickname changer it works as a fancy tab also i have unlimited nametag mode on ;-; oh and i also have a customtabname on  
  customtabname: "%essentials_nickname%"
  customtagname: "%essentials_nickname%"
yea so you need to fix your plugin ig ;-;

### Steps to reproduce

i dont know...

### Additional info

Please tell me how to fix it cuz i might be stupid

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
There ia no way this is a bug. Show output of `/tab debug <player>`

**Comment by Orange661** [comment]
bro do you wanna see proof if yes add me on discord and i will screenshare

**Comment by Orange661** [comment]
![unknownae](https://user-images.githubusercontent.com/82337681/193742406-fe34861e-5269-4ea3-a7d0-d5e706ad8d15.png)
there you fucking go lad

**Comment by Orange661** [comment]
![unkneaown](https://user-images.githubusercontent.com/82337681/193742636-26a77fc0-ffc0-4525-a299-e7c204d5666b.png)

**Comment by Orange661** [comment]
![unknowean](https://user-images.githubusercontent.com/82337681/193747244-b3b3c102-09b2-4e58-8b54-ef52b151ba52.png)
not even a command xd im on pufferfish 1.18.2

**Comment by Orange661** [comment]
OOPS NVM I FORGOT TO DOWNLOAD PAPI

**Comment by Orange661** [comment]
![image](https://user-images.githubusercontent.com/82337681/193747945-4cb9fb08-e3e9-4d5f-adff-b5a405f25428.png)
men :/

**Comment by Orange661** [comment]
alright

**Comment by Orange661** [comment]
fucking thank you dude i was so confused as why it wasnt working
