### ISSUE TITLE
infinite console error log

### ISSUE THREAD

**Issue by rjscdev** [NEZNAMY/TAB#725]
### Server version

1.18.2

### TAB version

3.1.4

### Stack trace

8.10 20:34:33 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:122)
08.10 20:34:33 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68)
08.10 20:34:33 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:350)
08.10 20:34:33 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
08.10 20:34:33 [Server] [WARN] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
08.10 20:34:33 [Server] [WARN] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
08.10 20:34:33 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
08.10 20:34:33 [Server] [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
08.10 20:34:33 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:831)
08.10 20:34:34 [Server] [WARN] java.lang.NoSuchFieldException: ping
08.10 20:34:34 [Server] [WARN] at java.base/java.lang.Class.getDeclaredField(Class.java:2584)
08.10 20:34:34 [Server] [WARN] at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:46)
08.10 20:34:34 [Server] [WARN] at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:268)
08.10 20:34:34 [Server] [WARN] at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
08.10 20:34:34 [Server] [WARN] at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
08.10 20:34:34 [Server] [WARN] at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.platforms.bukkit.BukkitPlatform.lambda$registerUnknownPlaceholder$2(BukkitPlatform.java:180)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:123)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:52)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:122)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:350)
08.10 20:34:34 [Server] [WARN] at TAB v3.1.4.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
08.10 20:34:34 [Server] [WARN] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

### Additional info

i just install my papi extensions an then all this was appearing on my console over and over again

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That's a PlaceholderAPI player expansion compatibility error on 1.17.+ which got fixed years ago.

**Comment by Tanguygab** [comment]
your Player expansion for PAPI is outdated, redownload it with
/papi ecloud download Player
/papi reload

and your TAB version is also outdated, you should update to 3.1.5
