### ISSUE TITLE
tagprefix disappears

### ISSUE THREAD

**Issue by Fartumasti** [NEZNAMY/TAB#726]
### Server version

paper 1.19.2

### TAB version

3.1.5

### Describe the bug

when a high online player appears on the server, about 50 people, then tagprefix does not keep up with the player, or disappears altogether. If you register /tab reload, they appear for a while
![bug](https://user-images.githubusercontent.com/40197653/194743150-12b27820-a993-4f4b-8c3e-d14eecd5495f.png)
![notbug](https://user-images.githubusercontent.com/40197653/194743156-c53c578f-2506-411c-858b-45f5c6866786.png)

### Expected behavior

tagprefix should not disappear

### Steps to reproduce

you don't need to do anything yourself, high online contributes to this

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of /tab cpu when they disappear.

**Comment by Fartumasti** [comment]
oh shit, I couldn't even expect that a placeholder for unique players loads the system so much! thank you, the topic is closed
