### ISSUE TITLE
Legacy placeholders doesn't work

### ISSUE THREAD

**Issue by eki-github** [NEZNAMY/TAB#728]
### Server version

Paper 1.17.1

### TAB version

3.1.5

### Describe the bug

The problem occurs when I want to add a rank prefix to the old placeholder because it looks unsightly on the new one. Everything works on the chat plugin (LPC). And your plugin doesn't detect the old placeholder. It's about the funnyguilds plugin

### Expected behavior

The plugin should detect the old placeholder

### Steps to reproduce

It is enough to create a prefix of the player above his head, insert the funnyguilds prefix eg {POINTS} from the plugin and it will not detect it. And other plugins detect.

### Additional info

TAB v3.1.5
![image](https://user-images.githubusercontent.com/65031661/195819440-34a07d70-508c-4b15-9081-4b722356fdcc.png)
LPC plaugin:
![image](https://user-images.githubusercontent.com/65031661/195819775-32e35272-aa35-4da5-acfe-9f9d6292c538.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What does "legacy placeholder" mean? Also placeholders are used with %%, not {}.

**Comment by eki-github** [comment]
> What does "legacy placeholder" mean? Also placeholders are used with %%, not {}.

"{TAG}" is a placeholder plugin funnyguilds it works in other plugins placed the same and in this does not detect

**Comment by NEZNAMY** [comment]
TAB does not support such syntax, it is not advertised anywhere. Only standard PlaceholderAPI format is supported.

**Comment by eki-github** [comment]
it would be possible to put a placeholder with funnyguilds plugin

**Comment by NEZNAMY** [comment]
Check its documentation for PlaceholderAPI placeholders the plugin offers.

**Comment by eki-github** [comment]
I know that it works like this but it looks unsightly and placeholder from the plugin nicer and I wanted to ask if it is possible in any way to put it there.

**Comment by NEZNAMY** [comment]
No, placeholder syntax will not be changed.

**Comment by eki-github** [comment]
I meant that inserting a placeholder with %% will write the name of the guild itself. And I would prefer [GuildTag] and in case the player does not have a guild will be something like that []. so placeholder plugin funnyguilds removes these [] simply put.

**Comment by NEZNAMY** [comment]
That is doable with conditions, either way it's out of scope of the original request.
