### ISSUE TITLE
unwanted belowname

### ISSUE THREAD

**Issue by adyzzek** [NEZNAMY/TAB#729]
### Server version

Purpur 1.19.2

### TAB version

3.1.4

### Describe the bug

Hello, I wanted to add money to belowname, I entered %vault_eco_balance_formatted% there and even though I deleted the default setting, hp, it still shows me there.

### Expected behavior

I want money under my name.

### Steps to reproduce

.

### Additional info

<img width="106" alt="image" src="https://user-images.githubusercontent.com/115493082/195974930-e35dce47-c168-4d0b-800d-1fb1f308d9d1.png">

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That's a limitation of the feature. See wiki for more info. Not a bug.
