### ISSUE TITLE
Big spacing on tab for player who used player#hidePlayer() to hide all online players on the list

### ISSUE THREAD

**Issue by TheJoshue** [NEZNAMY/TAB#730]
### Server version

Paper 1.12.2

### TAB version

3.1.5

### Describe the bug

When we use `player#hidePlayer()` in our/any plugin (most probably player hiding/visibility plugins for lobby/hub servers) we experience this:
![image](https://user-images.githubusercontent.com/56804505/196047935-76cf67c5-4b77-4876-b84a-6570dcc7bc95.png)

* Just for sake of proofing what is going on, this is when players are not hidden:
![image](https://user-images.githubusercontent.com/56804505/196047922-b75a503e-ec7a-4bd5-96f8-c78dd733e64d.png)

### Expected behavior

We expect this:
![image](https://user-images.githubusercontent.com/56804505/196047961-ef58b691-62a0-486f-9457-76319acb768c.png)

### Steps to reproduce

1. Get any plugin that uses mentioned (`player#hidePlayer()`) code in itself (or code it yourself) and put it onto server, load it correctly.
2. Try to hide players for yourself while you have other player online whose tab name is longer than the player who is trying to use hide function
3. This will happen.

### Additional info

* This does happen on any mc version (any mc server version with any mc client version)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Give the player `vanished` metadata attribute and those who should see the player `tab.seevanished` permission.

**Comment by TheJoshue** [comment]
Also a notice:
In most cases this happens when 1 player is op and it gets de-opped, then when you try to hide/unhide players this will happen
This will not happen if you restart server and nobody ever had OP (except 1 player) and however many times any of (let's say there are 3 players online because i tested like that) 3 players online try to hide/unhide other players for them, this WILL NOT happen (i tested for like 15 minutes spamming a lot of things on all 3 clients, also all clients are on different mc version)

**Comment by TheJoshue** [comment]
i don't know if this would be worth opening another issue but
![image](https://user-images.githubusercontent.com/56804505/196048119-4ed2d917-0bec-462b-84f7-c60becb996ec.png)

This happened **while all players were op**, then i did some hide/unhide functions (multiple times idk how many per player) for all clients and then when i got into vanish (with 1 player) this happened.

**Comment by NEZNAMY** [comment]
Sounds like the same kind of issue which I offered a solution for.

**Comment by TheJoshue** [comment]
> Give the player `vanished` metadata attribute and those who should see the player tab.seevanished permission.

Are you saying to add this metadata attribute within the plugin i am coding?

**Comment by NEZNAMY** [comment]
Yes, for TAB to properly detect the player as vanished.

**Comment by TheJoshue** [comment]
> Yes, for TAB to properly detect the player as vanished.

ok, is this like LuckPerms thing? that metadata attribute

**Comment by NEZNAMY** [comment]
Bukkit API.

**Comment by TheJoshue** [comment]
Ok thanks, i will try then go back here and reply when i test things out with what you said

**Comment by Tanguygab** [comment]
> Ok thanks, i will try then go back here and reply when i test things out with what you said

Did you try?

**Comment by NEZNAMY** [comment]
@TheJoshue

**Comment by TheJoshue** [comment]
Hi,
i did not yet try, i was busy with some stuff
i will try to test it out today more thoroughly

**Comment by NEZNAMY** [comment]
@TheJoshue if you don't test it, I will close this as it's not an issue, but expected behavior (https://github.com/NEZNAMY/TAB/wiki/Additional-information#vanish-detection).

**Comment by NEZNAMY** [comment]
Inactive user, assuming plugin works as described and user didn't follow insctructions.
