### ISSUE TITLE
Velocity global tab suport?

### ISSUE THREAD

**Issue by Lipe17CPS** [NEZNAMY/TAB#732]
### Server version

Velocity

### TAB version

3.0.2

### Describe the bug

How date to implement velocity tab list global suport?

### Expected behavior

.

### Steps to reproduce

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
You just checked that checklist without actually checking it didn't you?

1. You're outdated
2. If you would have read the compatibility wiki you would see velocity isn't supported

And to answer the question this will never be supported on velocity it's incapable of having most of TAB's features
