### ISSUE TITLE
Scorebord Bug

### ISSUE THREAD

**Issue by JaTiTV** [NEZNAMY/TAB#733]
### Server version

1.19.2

### TAB version

3.1.5

### Describe the bug

If I set the option 'hidden-by-default: false' at Scorebord, then the toggle command does not work anymore

### Expected behavior

The toggle command should work

### Steps to reproduce

1. set in config hidden-by-default: false
2. execute the toggle command

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
`hidden-by-default: false` is a default value. The toggle command works just fine with default configuration.

**Comment by AgentPieCZ** [comment]
Have same problem, Paper 1.19.2 , Everyone can write /sb , but, it wont hide scoreboard for everyone, only someone...

**Comment by NEZNAMY** [comment]
Find out what is the difference between players it works for and those who it doesn't work for.

**Comment by NEZNAMY** [comment]
Someone said it was a compatibility issue with Triton. Send your plugin list if you want me to investigate it further.

**Comment by NEZNAMY** [comment]
If no one responds until next version is released, I will consider the cause being `https://github.com/tritonmc/Triton/issues/251` (because no information proving this is not the case was provided).
