### ISSUE TITLE
[Unlimited Nametags] Nickname doesn't follows player

### ISSUE THREAD

**Issue by en0tuk** [NEZNAMY/TAB#734]
### Server version

Waterfall 1.19-R0.1-SHAPSHOT + git-Purpur-1808 (MC: 1.19.2)

### TAB version

TAB version: 3.1.5  TAB-Bridge version: 2.0.3 

### Describe the bug

When player riding horse nickname stuck in the last place where player was like not passenger

### Expected behavior

Nickname follows player instead stuck on position

### Steps to reproduce

Step 1: Enable unlimited nametag mod
Step 2: Ride horse

### Additional info

![image](https://user-images.githubusercontent.com/71115913/198082048-7fdbb96f-46fb-464c-832b-84187ca2bc12.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
update the bridge, latest version is 2.0.7

**Comment by NEZNAMY** [comment]
@en0tuk

**Comment by NEZNAMY** [comment]
Since user is outdated, assuming https://github.com/NEZNAMY/TAB-Bridge/commit/7a4fe5cf6df75845449fcdc292616b1a363a9d96 fixed it.
