### ISSUE TITLE
No work <bold></bold>

### ISSUE THREAD

**Issue by dwdsty** [NEZNAMY/TAB#735]
### Server version

Purpur 1.16.5

### TAB version

3.1.5

### Describe the bug

<bold><gradient:#ff0008:#ff6347>ChaosMine</gradient><bold>

<bold></bold> doesn't work
![Screenshot_1](https://user-images.githubusercontent.com/80200880/198349528-f612f6cf-a569-45ff-b4db-3dc8ea7cbc58.png)

### Expected behavior

Should work <bold></bold>

### Steps to reproduce

Apply <bold></bold> in the config and check if it works

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Looks good to me. You just didn't read the wiki to see how to use bold text.

**Comment by dwdsty** [comment]
I just saw it, thank you.
