### ISSUE TITLE
Yellow number does not accept numerical values!

### ISSUE THREAD

**Issue by mrdiploben** [NEZNAMY/TAB#736]
### Server version

Paper 1.17.1

### TAB version

3.1.5

### Describe the bug

[19:19:53 INFO]: [TAB v2.9.2] yellow number only accepts numeric values! (Attempted to use "{enabled=true, value=60, disable-in-worlds=[disabledworld]}")
No clue why this happens but tab and scoreboard don't load.

### Expected behavior

Tab and scoreboard are meant to display

### Steps to reproduce

No clue, just booted up the server and it gives that error.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Support is not provided for 1 year old versions.

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/198381720-2f5333c9-da42-4913-8d4a-15d61a5f8f15.png)

![image](https://user-images.githubusercontent.com/45695833/198381742-172aecc9-c4bf-43e8-8fca-8476ebe96bac.png)

**Comment by MurshidAlom** [comment]
Vv
