### ISSUE TITLE
Tag Name doesnt work

### ISSUE THREAD

**Issue by Steve22210** [NEZNAMY/TAB#737]
### Server version

Spigot/Bukkit 1.17.1

### TAB version

3.1.5

### Describe the bug

if you use %displayname% or smth like that as tab name it displays the player name not nick/displayname

### Expected behavior

it should display the display/nickname

### Steps to reproduce

nothing really it just doesnt change at all

### Additional info

uhh you need a screenshot for that?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of `/tab debug <player>` and send groups.yml

**Comment by Steve22210** [comment]
i meant tag sorry,and unlimited nametag mode is enabled
and here the other stuff
![1 1](https://user-images.githubusercontent.com/108025862/198900251-4fd7fe0a-5ef4-468f-bf3e-5ae9b353940b.PNG)
![1 2](https://user-images.githubusercontent.com/108025862/198900259-1c43bcc9-3880-4d8c-938f-de41e914692e.PNG)
and here my groups.yml
_DEFAULT_:
  tabprefix: "%vault-prefix%&7 ◆ &f"
  tabsuffix: "%vault-suffix%%afk%  "
  tagprefix: "%vault-prefix%&7 ◆ &f"
  tagsuffix: "%vault-suffix%%afk%  "
  customtabname: "%displayname%"
  customtagname: "%displayname%"

**Comment by NEZNAMY** [comment]
Are you sure you are looking at another player and not yourself?

**Comment by Steve22210** [comment]
yeah

**Comment by NEZNAMY** [comment]
Show a screenshot in game and output of `/tab parse <player> %displayname%`

**Comment by Steve22210** [comment]
it tells me 123

**Comment by NEZNAMY** [comment]
And what shows in game?

**Comment by Steve22210** [comment]
the parse msg is 123 and my nametag is Steve2210 not 123 but my tab is 12 tho it is the same placeholder

**Comment by NEZNAMY** [comment]
Send that screenshot of looking at another player.

**Comment by NEZNAMY** [comment]
@Steve22210 if you don't send that screenshot, I will assume you were looking at yourself with F5 not knowing you're supposed to use /tab nametag preview for that.

**Comment by NEZNAMY** [comment]
Assuming user was looking at themselves instead of another player.
