### ISSUE TITLE
TAB's PlaceholderAPI does not parse and/or reset when player switch server on Bungeecord

### ISSUE THREAD

**Issue by nhanledev** [NEZNAMY/TAB#740]
### Server version

Paper 1.19.2

### TAB version

3.1.5

### Describe the bug

(edit) I installed TAB on Bungeecord only

TAB's placeholders like `%tab_tabprefix%` and `%tab_tabsufffix%` show raw text when player switch to other server on same network.

TAB's customtabname reset to default player name on same context. (edit: fixedby set waterfall.yml `disable_tab_list_rewrite: false` - my bad)

Do a `/btab reload` on bungeecord fix that bug, and it happens again if you switch server or a new player join.

### Expected behavior

TAB's placeholders should be parsed into their value.
customtabname should return its content instead of just real username.

### Steps to reproduce

1. Run at least 2 paper servers and 1 bungeecord server
2. Install TAB 3.1.5 on bungeecord, TAB Bridge 2.0.7 on paper servers.
3. Turn on `global-playerlist:` with `enabled: true`
4. Format prefix and suffix and customtabname of player in `groups.yml` as you like

5. Reload btab on bungeecord and make sure that your custom above works
6. Setup a scoreboard or a bossbar and utilize `%tab_tabprefix%` and `%tab_tabsufffix%` 
8. Switch to other server and see the placeholders we set at step 6 brokes and the format of customtabname does not parse (it fallback to real playername instead)

### Additional info

ProtocolLib build 602

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an un
```supported server version / platform

**Comment by nhanledev** [comment]
The only way to fix this issue now is I have to send a `/btab reload` command to bungeecord when a player join any server :(

**Comment by NEZNAMY** [comment]
Server version says paper but you use /btab, is TAB on bungeecord then? Any of its forks?

**Comment by NEZNAMY** [comment]
Send config of TAB and waterfall.yml

**Comment by nhanledev** [comment]
waterfall.yml
```
throttling:
  tab_complete: 1000
log_initial_handler_connections: false
registered_plugin_channels_limit: 128
use_netty_dns_resolver: false
game_version: ''
disable_tab_list_rewrite: true
disable_entity_metadata_rewrite: false
disable_modern_tab_limiter: true
plugin_channel_name_limit: 128
```

config.yml
```
header-footer:
  enabled: true
  disable-in-worlds: []
  disable-in-servers:
    - auth0
  header:
    - "&r"
    - "&r              testMC              "
    - "&r"
  footer:
    - "&r"
  per-server: []

tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: false
  disable-in-worlds: []
  disable-in-servers:
  - auth0

scoreboard-teams:
  enabled: true
  enable-collision: false
  invisible-nametags: false
  anti-override: false
  sorting-types:
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: false
  can-see-friendly-invisibles: false
  disable-in-worlds: []
  disable-in-servers:
  - auth0

  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: false
    space-between-lines: 0.3
    disable-in-worlds: []
    disable-in-servers:
      - auth0
    dynamic-lines:
      - topname
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
    static-lines:
      myCustomLine: 0.66

yellow-number-in-tablist:
  enabled: false
  value: "%ping%"
  disable-in-worlds: []
  disable-in-servers:
  - auth0

global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: false
  isolate-unlisted-servers: true
  update-latency: true
  fill-profile-key: false
  spy-servers: []
  server-groups:
    main:
      - server1
      - server2

belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds: []
  disable-in-servers:
  - auth0

prevent-spectator-effect:
  enabled: true

bossbar:
  enabled: true
  toggle-command: /thongtin
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - auth0
  bars:
    # Other placeholder are redacted for debugging
    player_hud_hub:
      style: PROGRESS
      color: WHITE
      progress: '100'
      display-condition: "%server%=server1"
      text: '%tab_tabprefix%'
    player_hud_s2:
      style: PROGRESS
      color: WHITE
      progress: '100'
      display-condition: "%server%=server2"
      text: '%tab_tabprefix%'

per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  shared-playerlist-world-groups:
    none:
    - none

scoreboard:
  enabled: false
  toggle-command: /stats
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: false
  disable-in-worlds: []
  disable-in-servers:
  - auth0

  scoreboards:
    normal:
      title:  &rThông tin nhân vật
      lines:
      -  &r

ping-spoof:
  enabled: false
  value: 0

fix-pet-names:
  enabled: false

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  register-tab-expansion: true

placeholder-output-replacements: []

conditions:
  player-island-role-display:
    conditions:
    - "%server%=hub0"
    yes: "%ct_player-island-role-display%"
    no: ""

placeholderapi-refresh-intervals:
  default-refresh-interval: 1000
  player:
    '%player_world_time_24%': 400

# assigning groups by permission nodes instead of taking them from permission plugin
assign-groups-by-permissions: false

# if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
# Warning! This is not sorting list and has nothing to do with sorting players in tablist!
primary-group-finding-list:
  - default

debug: true

pipeline-injection: false

mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password

use-bukkit-permissions-manager: false
```

**Comment by nhanledev** [comment]
I made a simple network to replicate the placeholder bug
This include the build version of the master branch
Download the files here https://drive.google.com/file/d/1UQvXVoBWk8lQid0MrDZZWjlxk31izy9B/view?usp=share_link

Video of the bug (please notice the bossbar)

https://user-images.githubusercontent.com/28459250/200520960-2d036359-1ed8-482b-b2f3-e2a840385620.mp4

**Comment by NEZNAMY** [comment]
As you know from compatibility page you have read, you are supposed to set tablist rewrite option to false in waterfall.yml

**Comment by nhanledev** [comment]
Hello, looks like PlayerList is fixed on my side by set waterfall.yml tablist rewrite to `false` and enable tablist-name-formatting anti-override.

But the placeholder bug is still there. You can try with my shared config above.

Thank you so much

**Comment by nhanledev** [comment]
This is fixed in commit https://github.com/NEZNAMY/TAB/commit/a92f07aa40fbe551a1a18398029e63a9259b4144. Thank you.
