### ISSUE TITLE
colors in dimensions

### ISSUE THREAD

**Issue by saryxx** [NEZNAMY/TAB#741]
how can I make different colors for nicknames when the players are in different dimensions?

for example
if the players are in the overworld, then their nickname will be white, and if they are in nether, it will be red
tell me, I will be glad to help

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/201523291-65f82d59-6638-49d4-a1ef-dbe5ccece4e4.png)
