### ISSUE TITLE
Removing PING

### ISSUE THREAD

**Issue by ProtousSLO** [NEZNAMY/TAB#742]
### Page link

none

### Current text (if applicable)

I'd like to know If there is a way to remove the ping off the scoreboard completely.

### New text

uhm

**Comment by NEZNAMY** [comment]
This cannot be added to the wiki, because it's not possible with a plugin.

**Comment by ProtousSLO** [comment]
How can I remove it though?

**Comment by NEZNAMY** [comment]
Custom client/resource pack.
