### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by LuckyKuka** [NEZNAMY/TAB#743]
### Server version

⠀

### TAB version

⠀

### Describe the bug

⠀

### Expected behavior

⠀

### Steps to reproduce

⠀

### Additional info

Looks like a cool plugin, do you still support it?
 1; Does it support PlaceholderAPI? 
2; Does it support PermissionsEx? 
 3; Does it eat my TPS, cpu or ram?
4; Is [MySkin](https://www.spigotmc.org/resources/myskin-1-8-x-1-16-5.52303/) your plugin?
5; Where is the spigot website for this plugin?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
1. Yes, it's written on the wiki
2. It does through Vault, check the Compatibility page which you should have considering you ticked "I have read Compatibility page" but then again, you also ticked "I ticked all the boxes without actually reading them" so it's not surprising....
3. It doesn't affect the TPS, check it by yourself, for the CPU, it shouldn't do much, the only thing that could affect is the unlimited nametag mode with a lot of players. Either way, you can check your usage with /tab cpu anytime, there's even a wiki page to help you optimize the plugin.
4. MySkin isn't NEZNAMY's plugin, a friend of his gave him the ownership without telling him and left. NEZ wasn't interested in maintaining it last time I checked.

**Comment by LuckyKuka** [comment]
> 1. Yes, it's written on the wiki
> 2. It does through Vault, check the Compatibility page which you should have considering you ticked "I have read Compatibility page" but then again, you also ticked "I ticked all the boxes without actually reading them" so it's not surprising....
> 3. It doesn't affect the TPS, check it by yourself, for the CPU, it shouldn't do much, the only thing that could affect is the unlimited nametag mode with a lot of players. Either way, you can check your usage with /tab cpu anytime, there's even a wiki page to help you optimize the plugin.
> 4. MySkin isn't NEZNAMY's plugin, a friend of his gave him the ownership without telling him and left. NEZ wasn't interested in maintaining it last time I checked.

thanks for fast answer and also where is the spigot website for this plugin?

**Comment by Tanguygab** [comment]
As of TAB 3.0.0, support is only provided to buyers. This is the first plugin (as far as I know) to move to this monetization model as a different way of funding the development, which takes a lot of time and effort despite plugin's listed price. To get access to support tickets, you'll need to get yourself verified in <#913097543989198948> channel. After you are verified, you'll get access to <#690582612196065340>.

**Download**
*The plugin is not available on spigot, since I am banned from the website.*
**Note: mc-market.org has rebranded to builtbybit.com**
    <https://builtbybit.com/resources/20631>
    <https://github.com/NEZNAMY/TAB/releases>
    <https://github.com/NEZNAMY/TAB/actions> (dev builds) (must be logged in to download)

**Support my work to keep the plugin alive & get access to high-priority support**
    <https://builtbybit.com/resources/14009>
    <https://polymart.org/resource/484>
    <https://paypal.me/neznamy1>
   
Bridge plugin (for extending features on proxy)
    <https://builtbybit.com/resources/21641>

**Wiki <https://github.com/NEZNAMY/TAB/wiki>**

**Discord invite link:** https://discord.gg/EaSvdk6

**Comment by LuckyKuka** [comment]
> 



> From the Disocrd server:
> 
> As of TAB 3.0.0, support is only provided to buyers. This is the first plugin (as far as I know) to move to this monetization model as a different way of funding the development, which takes a lot of time and effort despite plugin's listed price. To get access to support tickets, you'll need to get yourself verified in #verification channel. After you are verified, you'll get access to #support.
> 
> **Download** _The plugin is not available on spigot, since I am banned from the website._ **Note: mc-market.org has rebranded to builtbybit.com** https://builtbybit.com/resources/20631 https://github.com/NEZNAMY/TAB/releases https://github.com/NEZNAMY/TAB/actions (dev builds) (must be logged in to download)
> 
> **Support my work to keep the plugin alive & get access to high-priority support** https://builtbybit.com/resources/14009 https://polymart.org/resource/484 https://paypal.me/neznamy1
> 
> Bridge plugin (for extending features on proxy) https://builtbybit.com/resources/21641
> 
> **Wiki https://github.com/NEZNAMY/TAB/wiki**
> 
> **Discord invite link:** https://discord.gg/EaSvdk6

thanks for information
