### ISSUE TITLE
Adding gradient with bold does not work

### ISSUE THREAD

**Issue by AshiroKun** [NEZNAMY/TAB#745]
### Server version

purpurmc 1.19

### TAB version

3.1.5

### Describe the bug

Editing the config.yml

I wanted to setup gradient colours but it being bold.

I did

<gradient:#FF512F:#F09819> &lTest</gradient>

but it seems to do the gradient and make it bold but put the l next to Test.

### Expected behavior

it is supposed to bold it with a gradient.

### Steps to reproduce

Step 1: Go to config.yml
Step 2: edit the header-footer
Step 3: Add a gradient there and try to add &l to bold it

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by AshiroKun** [comment]
Found out that it only happens for "header" in the config. the footer works normally

**Comment by NEZNAMY** [comment]
That is not a supported RGB gradient https://github.com/NEZNAMY/TAB/wiki/How-to-use-RGB-color-codes#usage
