### ISSUE TITLE
TAB not showing names

### ISSUE THREAD

**Issue by XayCraft** [NEZNAMY/TAB#746]
### Server version

Paper 1.19.2

### TAB version

3.1.5

### Describe the bug

Well lets just say in tab it just shows %essentials_nickname% (Thats the exact text) 

### Expected behavior

not to show %essentials_nickname%

### Steps to reproduce

I have no clue im not a plugin coder

### Additional info

none

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/202901613-f12f823e-4a79-4be3-a5a6-deb0120e5fec.png)
You also didn't even bother checking configuration files to manually delete placeholder you don't want.
