### ISSUE TITLE
Gradients do not work with more than 2 colors

### ISSUE THREAD

**Issue by RhythmicSys** [NEZNAMY/TAB#747]
### Server version

git-Purpur-1845 (MC: 1.19.2)*

### TAB version

v3.1.5

### Describe the bug

When using gradient with more than 2 colors, it does not parse properly

### Expected behavior

Expected that multiple colors can be used in a gradient, as that's normally how the gradient tag can be used

### Steps to reproduce

```
  header:
  - '<gradient:#E62388:#8F1798>Some placeholder text</gradient>'
  - '<gradient:#E62388:#8F1798:#87169A:#6613A1:#4728B0:#4759CC:#4BBBEB>Some placeholder text</gradient>'
  - '----------------------'
  footer:
  - '<gradient:#E62388:#8F1798:#87169A:#6613A1:#4728B0:#4759CC:#4BBBEB>----------------------</gradient>'
  - '&ePing:&f %ping% &b- &aTPS: %tps%'
```
 Place this in the header/footer section of config.yml

### Additional info

![image](https://user-images.githubusercontent.com/45906780/203186189-a0c32cd7-89fd-4c2a-8f45-d3f1926f90da.png)

![image](https://user-images.githubusercontent.com/45906780/203186325-9327f2f8-6c88-4723-8141-c6f56bbb583c.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Where does the wiki say you can use more than 2 colors?
