### ISSUE TITLE
Can't work with CustomNameplates's placeholder

### ISSUE THREAD

**Issue by xiaozhangup** [NEZNAMY/TAB#749]
### Server version

1.19.2

### TAB version

3.1.4

### Describe the bug

TAB may support minimessage, but when i use 
<font:nameplates:default>%nameplates_bg_pos%</font>%img_bar_compass%  <font:nameplates:offset_3><color:#BC8F8F>%player_x%, %player_y%, %player_z%</color>   </font><font:nameplates:default>%nameplates_bg_inv%</font>%img_bar_chest_minecart% <font:nameplates:offset_3><color:#DEB887>%player_empty_slots%</color></font>   <font:nameplates:default>%nameplates_bg_time%</font>%img_bar_clock% <font:nameplates:offset_3><color:#FFE4C4>%player_world_time_24%</color></font>

then a garbled code will appear

### Expected behavior

Same as Describe the bug

### Steps to reproduce

Same as Describe the bug

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Font field is not supported.

**Comment by xiaozhangup** [comment]
> Font field is not supported.

Can you support it? Or when will it be supported?

**Comment by NEZNAMY** [comment]
I am not interested in adding any more features.

**Comment by xiaozhangup** [comment]
> I am not interested in adding any more features.
Does TAB use MiniMessage to parse?

**Comment by xiaozhangup** [comment]
> I tried something but ended up with a huge amount of errors, so it's not officially supported.

i love you
