### ISSUE TITLE
Bossbar timer/countdown

### ISSUE THREAD

**Issue by Ayntrx** [NEZNAMY/TAB#75]
A countdown for the bossbar would be cool. With a custom command like /bossbar countdown, with a custom placeholder to display when the timer would be done. I could really use this and I know others would as well.

**Comment by DrWurzeli** [comment]
I'd like to add some ideas to it.

1) make command similar to the announce feature for it to be easily memorable like:
/tab countdown bar <duration>
1.1) <duration> should consist of two things: <amount> and <type>: "1s" for 1 second, "1m" for 1minute, "1h" for 1hour, "1d" for 1day...
2) bossbar style default should be "PROGRESS"
2.1) or config based.
3) text should be the duration displayed based on the duration given by the user.
3.1) seconds: "<amount> seconds", minutes and above: "<minutes>:<seconds> remaining"
3.2) this could also be configurable in config as sth like: show-seconds-with-minutes: true/false
4) PROGRESS initial value should be 100 and lower itself during countdown if possible and get to 0 once the cooldown is done.
5) command to stop countdown /tab countdown bar remove
