### ISSUE TITLE
/skin set issue with SkinsRestorer

### ISSUE THREAD

**Issue by nhanledev** [NEZNAMY/TAB#752]
### Server version

Paper 1.19.2

### TAB version

3.1.5 latest dev build

### Describe the bug

TAB is installed in proxy mode.

If I turn `global-playerlist` on, the `/skin set` command does not apply player skin on 1.19.2 client, but 1.18.2 client the skin is applied immediately (vanila client, no resource pack)

### Expected behavior

SkinsRestores `/skin set` command apply skin to the player immediately on 1.19.2 client.

### Steps to reproduce

1. Setup server in proxy mode.
2. Install SkinsRestorer
3. Set TAB config.yml `global-playerlist.enabled: true`, set waterfall.yml `disable_tab_list_rewrite: false`
4. Use command to set your skin, eg `/skin set tester01` on 1.19.2 client. SR send successfully message but the skin is not applied.
5. Rejoin and see that the skin is the one that set on step 4
6. Rejoin the server with 1.18.2 client and run the skin set to another skin, eg `/skin set eth707`
7. The player skin is applied immediately 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Are you sure the version thing is related in any way and not just it working for the player who ran the command or so? TAB makes no difference between client versions really.

**Comment by nhanledev** [comment]
Yes I have test on both backend (spigot) 1.17 and 1.19 and client 1.18.2, 1.19.2. It is so weird to report this but it is really what I see and can reproduce so far.

**Comment by nhanledev** [comment]
This is the server I set up for debugging this
The only thing that I change from the default files are 
- Waterfall `waterfall.yml`: `disable_tab_list_rewrite: false`
- TAB `config.yml`: 
```
global-playerlist:
  enabled: false
```

Video;
https://youtu.be/kLAagFy4bcU

Server Files:
https://drive.google.com/file/d/11viU92gww0lJ6fMv-JlBSQbWDVVpbuC0/view?usp=share_link

**Comment by NEZNAMY** [comment]
I tried it and it's bugged even without TAB installed.

**Comment by nhanledev** [comment]
I test with only SkinsRestorer and whether `disable_tab_list_rewrite: false` or `true` it still works.
With `disable_tab_list_rewrite: false`, it is only bug if `global-playerlist` is enabled. Disable this feature makes it work again.
Can you please look more at it? I've also sent this issue to SR's support thread to get their opinions.

**Comment by NEZNAMY** [comment]
I'll make a video for you.

**Comment by NEZNAMY** [comment]
https://youtu.be/AvXDOcvu8tY

**Comment by nhanledev** [comment]
You need to install SR on both proxy and backend servers :D I think you missed that step
Thank you for taking your time, but can you please check it again

**Comment by NEZNAMY** [comment]
I was able to identify the issue. Apparently 1.19 no longer accepts double-adding the same playerlist entry (previously new entry took priority) and ignores the second call.

**Comment by nhanledev** [comment]
I will put this fix on a production server to see if everything still works as intended. I tested the latest commit, and it looks good to me.
