### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by NEZNAMY** [NEZNAMY/TAB#754]
*first*
The plugin does not support 1.19.3, yes, I know, plugin requires an update. No need to create new issues or spam discord.
There is also no need for comments on this issue that add no value, such as "yes please add support". This is not a survey or a poll, you don't need to vote for it, support **will** be added.

**Comment by Meekness1** [comment]
True please update it to 1.19.3 it's nice plugin

**Comment by Caleston** [comment]
Would it be possible for future versions to not prevent joining to the server entirely if out of date, but rather just.. break?

**Comment by NEZNAMY** [comment]
Compatibility check is already available on bukkit as you should be well aware. On bungeecord, breaking changes rarely happen and are absolutely unpredictable.
