### ISSUE TITLE
1.7 Globalplayerlist player vanishes of tab after switching Server

### ISSUE THREAD

**Issue by c0dingnoobi** [NEZNAMY/TAB#755]
### Server version

Spigot 1.8.8

### TAB version

3.1.5 (678eed2)

### Describe the bug

Couldnt find anything related to this inside of Compatibility and Limitations. 
Default config with globalplayerlist enabled.

Player vanishes from 1.7 Tab as soon as he switches servers.

### Expected behavior

1.7 Client should still see player after server switch in tab if globalplayerlist is enabled. 

### Steps to reproduce

1. Have two accounts online at lobby
2. Join any backend using the first account (regardless of client version)
3. See that the player who switched server vanishes from tab of player who is still at lobby (which is the 1.7 client) 
4. Execute /btab reload to make him visible again

### Additional info

This has been tested using vanilla 1.7 on Flamecord.
Backends had ViaVersion 4.5 (also happened with 4.4.2) and ViaRewind and TAB-Bridge(2.0.7).
Seems also to be irrelevant to waterfalls `disable_entity_metadata_rewrite: true` since this behaviour is also reproduceable if it is set to `false`
If i missed any important informations, let me know.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by c0dingnoobi** [comment]
Everything else works fine dw. 
Ig this issue can be closed then.

**Comment by NEZNAMY** [comment]
Are you able to compile code? I have one little thing I want to try, but my workspace state is too different due to 1.19.3 to safely push a change.

**Comment by c0dingnoobi** [comment]
Yea i am able to compile.
But wont be able to do it now (in like 2h i can)

**Comment by NEZNAMY** [comment]
delete lines https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/globalplayerlist/GlobalPlayerList.java#L129-L133 and only keep the content of line 130

**Comment by c0dingnoobi** [comment]
https://pastebin.com/jPAxnuhj
![image](https://user-images.githubusercontent.com/97745777/206740255-6b57e44d-545e-4963-8b11-3c1091d50e94.png)
happens on 1.7 client join.
I think i compiled it wrongly https://pastebin.com/PABkJ4r8

**Comment by NEZNAMY** [comment]
Right, bungeecord dependency got updated. You'll need to update your bungeecord server as well.

**Comment by c0dingnoobi** [comment]
Bungeecord itself does not support 1.7 and Flamecord does not have yet updated anything. 
That error only happens on the jar which i compiled. The latest commit you made yesterday and its prebuild artifact does not send this stacktrace.

**Comment by NEZNAMY** [comment]
Yes, because the bungeecord dependency got updated without changing version number, so it was automatically downloaded and used for compiling.

**Comment by c0dingnoobi** [comment]
Ah, got it. I will try with Xcord (they already merged with upstream of bungee today).

**Comment by c0dingnoobi** [comment]
Works, player vanishes for a blip of second then gets set again to tab

**Comment by c0dingnoobi** [comment]
Seems to cause some stacktraces.
when 1.7 disconnects there is one in console (https://pastebin.com/aTYS3jkS) 
when a player (regardless of version) disconnects, everyone with 1.7 gets kicked (https://pastebin.com/pXEkkH6u)

Sure it might be a XCord issue, but it works when not having TAB installed.
I could try to use latest TAB build with latest XCord to see if it still happens.

**Comment by c0dingnoobi** [comment]
Seems to be caused by XCord.

**Comment by NEZNAMY** [comment]
Due to massive difference between 1.7 and 1.8 tablist, global playerlist is not even supposed to support 1.7 in the first place. I will add this to the wiki.
