### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YrChen1001** [NEZNAMY/TAB#756]
### Server version

BungeeCord(latest)

### TAB version

3.1.5

### Stack trace

`17:18:07 [INFO] [TAB] [TAB v3.1.5] Feature PlayerList failed to process player Patronsaint1
17:18:07 [INFO] [TAB] java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.PlayerListItem$Item.setGamemode(int)'
17:18:07 [INFO] [TAB]     at me.neznamy.tab.platforms.bungeecord.BungeePacketBuilder.build(BungeePacketBuilder.java:59)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.api.protocol.PacketBuilder.lambda$new$2(PacketBuilder.java:31)
17:18:07 [INFO] [Patronsaint1] <-> ReconnectDownstreamHandler <-> [Survival1] Exception caught: net.md_5.bungee.protocol.BadPacketException: Packet GAME:TO_CLIENT/58 (ResourcePackSendPacket) larger than expected, extra bytes: 75336
17:18:07 [INFO] [TAB]     at me.neznamy.tab.api.protocol.PacketBuilder.build(PacketBuilder.java:54)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:335)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.ITabPlayer.sendCustomPacket(ITabPlayer.java:343)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.features.PlayerList.updatePlayer(PlayerList.java:95)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.features.PlayerList.refresh(PlayerList.java:190)
17:18:07 [INFO] Netty is not using direct IO buffers.
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.features.PlayerList.lambda$onJoin$0(PlayerList.java:202)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.features.PlayerList.onJoin(PlayerList.java:211)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.FeatureManagerImpl.onJoin(FeatureManagerImpl.java:125)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.platforms.bungeecord.BungeeEventListener.lambda$onSwitch$1(BungeeEventListener.java:55)
17:18:07 [INFO] [TAB]     at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
17:18:07 [INFO] [TAB]     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
17:18:07 [INFO] [TAB]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17:18:07 [INFO] [TAB]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
17:18:07 [INFO] [TAB]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
17:18:07 [INFO] [TAB]     at java.base/java.lang.Thread.run(Thread.java:833)
17:18:08 [INFO] [Reconnect] Cancelled reconnect for "Patronsaint1" on "Survival1" as they have disconnected
17:18:08 [INFO] [Patronsaint1] -> UpstreamBridge has disconnected`
[errors.log](https://github.com/NEZNAMY/TAB/files/10199594/errors.log)

### Steps to reproduce (if known)

When Player try to join server that will happend, and player can't join server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
#754 ???

**Comment by YrChen1001** [comment]
what do you mean? back to last version? or?

**Comment by NEZNAMY** [comment]
I mean you are duplicating an existing issue.

**Comment by YrChen1001** [comment]
Oh! sorry. So just waiting for an update will fix this?

**Comment by NEZNAMY** [comment]
Yes.
