### ISSUE TITLE
Feature request Kiori mini message

### ISSUE THREAD

**Issue by JaTiTV** [NEZNAMY/TAB#758]
Can you add Kiori mini message support?
[https://docs.adventure.kyori.net/minimessage/format.html](https://docs.adventure.kyori.net/minimessage/format.html)

**Comment by Tanguygab** [comment]
Not planned, NEZNAMY already tried in the past but encountered a lot of errors because of how both Kyori and TAB works.
This would take a lot of time to change and NEZNAMY isn't looking forward to that.
Also, feature requests are closed.
