### ISSUE TITLE
Issue with external playes

### ISSUE THREAD

**Issue by Miriam0** [NEZNAMY/TAB#759]
### Server version

Multipaper 1.19.2

### TAB version

3.1.5

### Describe the bug

Players from external servers 'invinsible' for TAB plugin.
Pls add support MultiPaper.

### Expected behavior

-

### Steps to reproduce

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
You already had your answer, feature requests are closed, no need to spam issues.
