### ISSUE TITLE
TAB plugin causing Internal Exception

### ISSUE THREAD

**Issue by ProtousSLO** [NEZNAMY/TAB#761]
### Server version

Paper 1.18

### TAB version

3.1.5

### Describe the bug

With the plugin installed I always, but only me gets kicked for "Internal Exception: java.net.SocketException. Connection reset. 
How did I come to this conclusion? I am making another server apart from the main one and I installed the same files from TAB into this one and It does this... Please help...

### Expected behavior

Same as it is before?

### Steps to reproduce

No idea how to reproduce this as It only happens to me.

### Checklist

- [X] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/206918308-28082822-d775-4f82-8b63-c86538219310.png)
Provide useful information or this will be closed as invalid.

**Comment by ProtousSLO** [comment]
:D damn, I'm stupid as hell. But no matter what It's running on latest, I read wiki plenty of times before to setup the plugin itself and I don't think It includes this error?

**Comment by NEZNAMY** [comment]
Check console log if it says anything. Remove TAB to try if it really is the cause.

**Comment by ProtousSLO** [comment]
Alrighty, let me do it again.

**Comment by ProtousSLO** [comment]
The reason why I believe It is, I joined the server and it worked perfectly fine without disconnecting me for hours and right after I install TAB it basically kicks me.

**Comment by ProtousSLO** [comment]
Hmm, I haven't removed it and so far I haven't been disconnected... But right before It did disconnect me, that's weird.

**Comment by ProtousSLO** [comment]
Would you have any clue, It only happens on my server and nowhere else, and only for me too.

**Comment by ProtousSLO** [comment]
I need to be using a VPN constantly to not get disconnected from my OWN server.

**Comment by NEZNAMY** [comment]
TAB is not checking IP addresses of players for VPN in any way.

**Comment by NEZNAMY** [comment]
I have no idea, this is a TAB issue tracker, not minecraft server support.

**Comment by ProtousSLO** [comment]
Damn, that's quite mean. Is there a way to center align text in the TAB column?

**Comment by NEZNAMY** [comment]
No.

**Comment by ProtousSLO** [comment]
hmm
