### ISSUE TITLE
Kicking players

### ISSUE THREAD

**Issue by MisterLolxd2** [NEZNAMY/TAB#765]
### Server version

PaperSpigot 1.8.8

### TAB version

3.2.0

### Describe the bug

[18:34:12] [Netty Epoll Server IO #0/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

[18:34:12] [Netty Epoll Server IO #3/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

[18:34:12] [Netty Epoll Server IO #2/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

[18:34:12] [Netty Epoll Server IO #0/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

[18:34:12] [Netty Epoll Server IO #0/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

[18:34:12] [Netty Epoll Server IO #2/WARN]: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

### Expected behavior

I have a server connected to bungeecord, after updating the plugin TAB from 3.1.5 to 3.2.0 an error appeared. The error is that it kicks all players when it enters with the netty reason. I threw all the plugins one by one until I got to the point where it stopped kicking players from the server after removing TAB 3.2.0.

### Steps to reproduce

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You forgot to include steps to reproduce.

**Comment by MrTimotys** [comment]
@NEZNAMY It does this to me when I reload the tab

**Comment by NEZNAMY** [comment]
So /tab reload kicks players? You don't want me to believe that, do you? There has to be something more you didn't tell.

**Comment by MrTimotys** [comment]
`[20:28:46 INFO]: MrTimoty lost connection: Internal Exception: java.io.IOException: Connection reset by peer`

**Comment by NEZNAMY** [comment]
That'a the same message? What do you get in game?

**Comment by MrTimotys** [comment]
Kick

**Comment by NEZNAMY** [comment]
You get a disconnect message saying "Kick"?
Something like this?
![image](https://user-images.githubusercontent.com/6338394/207712482-78bab9c4-3bea-4b79-ae42-7d7586a620dc.png)

**Comment by MisterLolxd2** [comment]
Nope i didn't use /tab reload.

"You forgot to include steps to reproduce." 
1. have a server 1.8.8 (On other versions of this problem is not present. like 1.12.2 1.16.5, 1.19.2 - i tested in my another servers)
2. have a bungeecord
3. add tab 3.2.0 to the server
4. Join to the server.
5. the reason of kick i send below.

**Comment by NEZNAMY** [comment]
What displays in the game on kick?

**Comment by MisterLolxd2** [comment]
"Connection lost"

**Comment by NEZNAMY** [comment]
And install TAB where? On bungeecord or the 1.8.8 server?

**Comment by MisterLolxd2** [comment]
On server 1.8.8

**Comment by NEZNAMY** [comment]
Then bungeecord is just sitting around existing? What if you don't use it?

**Comment by MisterLolxd2** [comment]
I don't know, i didn't test this, beacuse my all servers are connected with bungee.

**Comment by NEZNAMY** [comment]
Find out using a testing environment.

**Comment by MisterLolxd2** [comment]
I created a test server with 1.8.8 and tab 3.2.0 and nothing happens. It turns out that this maybe is a conflict between tab and bungee.

**Comment by NEZNAMY** [comment]
Find out.

**Comment by MisterLolxd2** [comment]
Maybe the problem is that I'm using bungeecord: WaterFall 1.19-R0.1?
Beacuse i think: "Updated to latest bungeecord build, which adds 1.19.3 support (no longer compatible with older versions)".

**Comment by NEZNAMY** [comment]
That is for bungeecord installation of TAB, not backend. Please stop asking all possible questions. Take your time replicating your environment and come back here with steps to reproduce the issue.

**Comment by MisterLolxd2** [comment]
You are the author of the plugin. After testing, it can be clearly stated that the problem with the latest version of tab occurs at the 1.8 server, which is connected to the bungeecord server. Playing detective from the series what the author broke, I reported this error to you and wrote all the possible details. A problem that, as you can see, does not occur only for me. Welp...

**Comment by NEZNAMY** [comment]
You decided to make a bug report, you are responsible for providing enough information for me to be able to reproduce your issue.

**Comment by MisterLolxd2** [comment]
I'm not a virtuoso to guess what else might be the reason and I have provided you with such. If this is not enough for you, just close the ticket and "sweep under the carpet".

**Comment by MisterLolxd2** [comment]
Lmao...
