### ISSUE TITLE
CITIZENS NPC are shown in tablist

### ISSUE THREAD

**Issue by Ant8off** [NEZNAMY/TAB#766]
### Server version

git-Paper-328 (MC: 1.19.3) 

### TAB version

3.2.1

### Describe the bug

Citizens NPC are shown in TAB

![2022-12-17_14 02 29](https://user-images.githubusercontent.com/92182190/208243170-29c9a7b7-edae-416d-bb69-7bdd679d1300.png)

### Expected behavior

in previous server version the npcs weren't shown in tablist

### Steps to reproduce

Step 1: install a git-Paper-328 (MC: 1.19.3) server
Step 2: install TAB 3.2.1 and Citizens 2.0.30-SNAPSHOT (build 2813)
Step 3: Start server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Known-issues#1---1192---npcs-in-tablist

**Comment by DexterSK** [comment]
FINALLY! nice plugin btw
