### ISSUE TITLE
dev build below name bug

### ISSUE THREAD

**Issue by FallingCactus** [NEZNAMY/TAB#77]
**Server version**
1.15 (paperMC)

**Plugin version** ("latest" is not a version)
2.55 pre15

**Describe the bug**
dev builds "belowname:" still shows when disabled

**How to reproduce**
set to false in config reload plugin/restart server

**Expected behavior**
to be removed

**Actual behavior**
stayed as if set true

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
A screenshot ? Config?

**Comment by FallingCactus** [comment]
config - https://hastebin.com/iyituvuyul.http

**Comment by FallingCactus** [comment]
![2019-12-13_22 31 28](https://user-images.githubusercontent.com/34792280/70836543-6150c680-1df8-11ea-9f6c-fd40b629f77b.png)
screenshot

**Comment by NEZNAMY** [comment]
Your config has "belowname1:" instead of the actual name "belowname:", which might be causing it.

**Comment by FallingCactus** [comment]
yup, my bad, no idea how it got there, thanks, sorry
