### ISSUE TITLE
Server RAM placeholder for PlaceholderAPI grabs RAM values from Bungeecord instead of backend server

### ISSUE THREAD

**Issue by vhcrack** [NEZNAMY/TAB#770]
Basically what the title says. It only grabs the amt of ram used/max ram from the Bungeecord server instead of the backend. 
Does this for other server placeholders too. I believe this may be an error.

**Comment by NEZNAMY** [comment]
Java cannot access internal memory values of another computer device. Use PlaceholderAPI if you want values from backend servers.

**Comment by vhcrack** [comment]
> Java cannot access internal memory values of another computer device. Use PlaceholderAPI if you want values from backend servers.

That's what I'm doing...
It is not working.

**Comment by NEZNAMY** [comment]
What placeholders are you using?

**Comment by vhcrack** [comment]
> What placeholders are you using?

%server_ram_used% / %server_ram_max%

Shouldn't it grab from the backend and not the actual bungeecord server using these?

**Comment by NEZNAMY** [comment]
Show output of `/btab parse me <placeholder>` and `/papi parse me <placeholder>`.

**Comment by vhcrack** [comment]
It literally just started working. Not even kidding. It was grabbing the values off the proxy yesterday but now it's just magically working. Thanks for the quick responses 😭
