### ISSUE TITLE
Disabled tablist works - Until you reload the plugin or a player joins

### ISSUE THREAD

**Issue by thevalleyy** [NEZNAMY/TAB#774]
### Server version

git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510 (waterfall-1.19-510.jar)

### TAB version

3.2.1

### Describe the bug

When somebody joins/leaves/or reloads TAB on my TAB-disabled-server, TAB enables itself automatically.

### Expected behavior

- The tablist should just stay the same, regardless of reloads and joins and leaves

### Steps to reproduce

1. Install TAB on a bungee proxy with two or more subservers
2. Disable TAB on one of these servers
3. Join the Server where TAB is disabled
4. Run `/btab reload` or make a player join/leave
5. Watch the tablist get weird

### Additional info

[Reload Bug](https://www.youtube.com/watch?v=Iy_4sXNxlrA)
[Join/Leave Bug](https://www.youtube.com/watch?v=Tjj8MJYilTQ)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Do not use TAB on both BungeeCord and the backends, only on one of those.
You will experience a lot of incompatibilities, we do not recommend using TAB like this.

**Comment by thevalleyy** [comment]
The only instance of TAB is running on my proxy.

**Comment by Tanguygab** [comment]
Oh, I misread, sorry. Can you send your config.yml ?

**Comment by thevalleyy** [comment]
[Here it is!](https://gist.github.com/thevalleyy/dd35b0b929b36f7d8c82ce380f0fe7b8)

**Comment by Tanguygab** [comment]
Your config seems alright, I guess NEZNAMY will have to look into it when he's available

**Comment by thevalleyy** [comment]
Thank you for your quick response!

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=xrr86pcR6Xk).
Quick summary:
* I was on a server where tablist formatting should be disabled and it is
* I switched server to one where it's enabled, and it was
* I switched back to disabled server, where formatting got reset
* I ran /btab reload, without getting my formatting back

**Comment by thevalleyy** [comment]
Well, weird that it now also works right on my servers (I resetted `config.yml`).
Hope it keeps working right from now on. 
Thank you for your time and effort to keep that plugin working fine, really appreciate it.
