### ISSUE TITLE
Relational placeholders are not working with TAB Conditions

### ISSUE THREAD

**Issue by frafol** [NEZNAMY/TAB#775]
### Server version

Paper 1.8.8

### TAB version

3.2.1

### Describe the bug

If you put a relational placeholder in a condition output, it won't be displayed.

### Expected behavior

Placeholder might be showed

### Steps to reproduce

Put a relational placeholder in a condition

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
that's not a bug, Conditions simply do not support realtional placeholders, and since feature requests are closed, this will likely not happen anytime soon
