### ISSUE TITLE
Abovename / Belowname not showing

### ISSUE THREAD

**Issue by RAMENSeater** [NEZNAMY/TAB#777]
### Server version

spigot 1.16.5

### TAB version

3.2.1

### Describe the bug

nothing is appearing on top of my nick name even tho i created a abovename with the /TAB group ... (The below name dosent shows up either but i managed to makeit show up by setting it up directly in the config instead of the group. )

### Expected behavior

The text should appear on top of the username because it is set up in the default group.

### Steps to reproduce

1. "/tab group _DEFAULT_ abovename [text]"
2. nothing show up

### Additional info

sorry for my bad english i am french x)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#why-do-the-abovenamebelowname-properties-not-work

**Comment by RAMENSeater** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#why-do-the-abovenamebelowname-properties-not-work

what if it is already enabled

**Comment by NEZNAMY** [comment]
Then read the second part of the answer.

**Comment by RAMENSeater** [comment]
fixed thx 👍 (is there a way to always show the preview?)

**Comment by NEZNAMY** [comment]
No, it would be annoying in game.
