### ISSUE TITLE
Visibility of NPC Citizens in the tab

### ISSUE THREAD

**Issue by Weyl1** [NEZNAMY/TAB#778]
### Server version

Purpur-1883-1.19.3

### TAB version

3.2.1

### Describe the bug

![image](https://user-images.githubusercontent.com/96068728/210441015-cbf4311c-3065-466a-8ccb-8fd76f308b3a.png)

### Expected behavior

The npc's are visible in the tab constantly

### Steps to reproduce

1.19.3 
Tab 3.2.1

Place npc 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Known-issues#1---1192---npcs-in-tablist ???

**Comment by Weyl1** [comment]
Yes, but they never disappear, even if you move to another world, you have to disconnect and stay away from them

but I don't think this is due to the TAB plugin

**Comment by NEZNAMY** [comment]
It isn't. Remove TAB and try again to confirm.

**Comment by Weyl1** [comment]
![image](https://user-images.githubusercontent.com/96068728/210456558-c3f4e6c9-1333-4767-bf1f-03fa51089991.png)
 Confirmed

**Comment by NEZNAMY** [comment]
Well yes, you are experiencing issue like hundreds of others which is not caused by TAB just like the wiki says.
