### ISSUE TITLE
1.15 armorstand bug with viaversion

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [NEZNAMY/TAB#78]
**Server version**
1.14.4

**Plugin version** ("latest" is not a version)
2.6.0-pre17

**Describe the bug**
If you have server on older version with viaversion - if somebody joins from 1.15 he sees only armorstands on heads of people. I have unlimited-nametag-prefix-suffix-mode enabled

**Comment by NEZNAMY** [comment]
This viaversion bug was fixed already https://www.spigotmc.org/resources/viaversion.19254/update?update=308352
