### ISSUE TITLE
Errors when reloading, random tab freeze, no sorting and kick

### ISSUE THREAD

**Issue by SkirmiLTU** [NEZNAMY/TAB#781]
### Server version

Bungeecord (Xcord 1.50 ) Purpur 1.19.2 build 1858

### TAB version

3.2.1 and 3.2.2 (maybe other versions too)

### Describe the bug

I am experiencing an error with TAB plugin, player count freezes, sorting stops working also when attempting to reload the plugin i get error, plugin disables itself and some players gets kicked. The error can be found at the following link: https://pastebin.com/H35avHfE. Error is mostly occurring when i have more than about 70 players connected the server. 

### Expected behavior

Tablist being displayed normally, player count updated normally, no error when reloading

### Steps to reproduce

Install bungeecord and spigot servers
Get ~70+ players online
Wait for plugin to glitch out or reload it

### Additional info

My configs:
[TAB.zip](https://github.com/NEZNAMY/TAB/files/10366901/TAB.zip)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Error says your server ran out of memory.

**Comment by SkirmiLTU** [comment]
My server has 6 gigabytes of memory which is more than enough for bungeecord, also, it's using less than half of that 6gb. So not running out of memory. Any other ideas?

**Comment by NEZNAMY** [comment]
Using a free panel that limits thread count for the server.

**Comment by SkirmiLTU** [comment]
Could you provide more information? I am don't understand your statement and how to resolve my issue.

**Comment by NEZNAMY** [comment]
Something is limiting thread count for your server.

**Comment by SkirmiLTU** [comment]
What could be limiting tread count? Why it only started happening after i updated from TAB 3.1.4 to 3.2.1? I am using `java  -Xms128M -Xmx6144M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -jar server.jar` startup parameters, can they cause this issue?

**Comment by FearDiamond** [comment]
Could TAB be spamming thread creation?

_FYI I am support from the server hosting company that SkirmiLTU uses for his server._

**Comment by NEZNAMY** [comment]
There's a limit of TAB's thread pool set to [20 threads](https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/CpuManager.java#L50) (+1 processing thread). I can catch the error and print size of TAB's thread pool to confirm (how) full it is, but that won't fix anything.

**Comment by NEZNAMY** [comment]
I added a try/catch showing amount of threads from TAB, which is as much as I can do.
