### ISSUE TITLE
Scoreboard doesn't show to players on join sometimes.

### ISSUE THREAD

**Issue by Albeyzhy** [NEZNAMY/TAB#782]
### Server version

PaperSpigot 1.8.8

### TAB version

3.2.1

### Describe the bug

When a player joins, it just sometimes doesn't show the scoreboard, i didn't have this issue on the older versions.
It might be something with my config, but it's just weird that it only happens sometimes, and it says nothing in log or in tab errors.
Heres my scoreboard config:

`scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: false
  disable-in-worlds:
  - disabledworld
  scoreboards:
    vagt:
      display-condition: "%luckperms_primary_group_name%=pvagt|%luckperms_primary_group_name%=vagt|%luckperms_primary_group_name%=officer|%luckperms_primary_group_name%=inspektør|%luckperms_primary_group_name%=direktør"
      title: '&a&l&nHEROPRISON&7 (&n%online%&7)'
      lines:
      - ''
      - '&2&lSPILLER &f&lINFO'
      - '&8 ▎ &7Rank: &f%luckperms_prefix%'
      - '&8 ▎ &7Penge: &f%vault_eco_balance_formatted%&a&l$'
      - '&8 ▎ &7Coins: &f%sb_coins%&e&l⛃'
      - ''
      - '&2&lVAGT &f&lINFO'
      - '&8 ▎ &7Kills: &f%sb_kills%'
      - '&8 ▎ &7Døde: &f%sb_døde%'
      - '&8 ▎ &7Level: &f%sb_level%'
      - ''
    fange:
      title: '&a&l&nHEROPRISON&7 (&n%online%&7)'
      lines:
      - ''
      - '&2&lSPILLER &f&lINFO'
      - '&8 ▎ &7Rank: &f%luckperms_prefix%'
      - '&8 ▎ &7Penge: &f%vault_eco_balance_formatted%&a&l$'
      - '&8 ▎ &7Coins: &f%sb_coins%&e&l⛃'
      - ''
      - '&2&lBANDE &f&lINFO'
      - '&8 ▎ &7Bande: &f%sb_bande%'
      - '&8 ▎ &7Level: &f%sb_bandelevel%'
      - '&8 ▎ &7Bank: &f%sb_bandebank%&a&l$'
      - ''`

### Expected behavior

Show the scoreboard

### Steps to reproduce

I don't really know... just try to join with that config.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show plugin list.

**Comment by Albeyzhy** [comment]
![image](https://user-images.githubusercontent.com/96750444/211169618-947cf698-deb5-4eae-87b7-527dd1d023af.png)

**Comment by NEZNAMY** [comment]
SkBee causes it, see compatibility page.

**Comment by Albeyzhy** [comment]
Oh okay, thanks for the help.
