### ISSUE TITLE
Spectators don`t see the nickname of the invisible player with unlimited-nametags

### ISSUE THREAD

**Issue by kforbro** [NEZNAMY/TAB#785]
### Server version

Purpur 1.19.2

### TAB version

3.2.1

### Describe the bug

Spectators cannot find out the nickname of an invisible player if unlimited-nametags is enabled

### Expected behavior

Players with gamemode spectator should see the nametag of the invisible player, gamemode survival|adventure|creative does not

### Steps to reproduce

1. throw an invisibility potion
2. /gamemode spectator
3. enable unlimited-nametag-mode.enabled

### Additional info

unlimited-nametag-mode.enabled: false
![image](https://user-images.githubusercontent.com/39985355/211308457-b04bba7a-b0f8-4ae7-9569-ee35a9308629.png)
unlimited-nametag-mode.enabled: true
![image](https://user-images.githubusercontent.com/39985355/211308488-2477dcc4-0232-4c8a-a89d-f789e49f172e.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Armor stands are not hidden from spectator players. Originial name is hidden to avoid double names. This is not a bug, but intended behavior.

**Comment by kforbro** [comment]
> Armor stands are not hidden from spectator players. Original name is hidden to avoid double names. This is not a bug, but intended behavior.

Yes, I understand that, but how do I find out the nickname of an invisible player?

**Comment by NEZNAMY** [comment]
I would probably need to disable armor stand showing for spectators.

**Comment by kforbro** [comment]
> I would probably need to disable armor stand showing for spectators.

It's going to be great. I would also like to see a option that will allow you to completely remove the armor stands and see the original nickname, regardless of visibility only for spectators. Because, for example, it looks very ugly for YouTube videos when 100 players are in one place and YouTube includes gamemode spectator with unlimited-nametags

**Comment by NEZNAMY** [comment]
Disabling armor stand view for a certain player will not be added.

**Comment by NEZNAMY** [comment]
I just checked it again, and nametags of invisible players are not supposed to be seen. Not even in spectator gamemode.

**Comment by kforbro** [comment]
> 

is there any way to find out the nickname of an invisible player?

**Comment by NEZNAMY** [comment]
Looks like not using unlimited nametag mode. I would need to implement it.
