### ISSUE TITLE
Players aren't in primary groups

### ISSUE THREAD

**Issue by JacobWasTaken** [NEZNAMY/TAB#786]
### Server version

Paper 1.19.3

### TAB version

3.2.1

### Describe the bug (Or me just being stupid)

I'm trying to sort higher players to the top of tab, but when I run /tab debug player, it says they aren't in a group. Groups are on though, because it doesn't say DISABLED. I have the groups properly configured in LuckPerms.

### Expected behavior

For the players to be in groups and for tab to auto sort them.

### Additional info

![image](https://user-images.githubusercontent.com/102453197/211441655-e71e9604-25c6-4d45-b33a-050345fac5fa.png)
![image](https://user-images.githubusercontent.com/102453197/211441752-e41fff48-043c-4df0-a9de-3b5ef02155c1.png)
![image](https://user-images.githubusercontent.com/102453197/211449188-859bf42a-2215-4af4-a52f-69aa83cd79b4.png)
![image](https://user-images.githubusercontent.com/102453197/211449341-d1c5804a-f94e-40cb-8636-7f2b5878aea8.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
not a bug, debug clearly shows you enabled sorting by permission which you didn't setup correctly.
[https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist#permissions](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist#permissions)

**Comment by JacobWasTaken** [comment]
I knew it wasn't a bug, but there wasn't a "Help" tag, all I needed was support so thank you.

**Comment by NEZNAMY** [comment]
That's right, support is not provides in issues just like readme says.
