### ISSUE TITLE
Problem wirh long prefix

### ISSUE THREAD

**Issue by EduardAstroSpace** [NEZNAMY/TAB#787]
### Server version

1.12.2

### TAB version

3.2.1

### Describe the bug

The prefix in the nickname cannot be more than 8 characters, not counting &f,&c and so on.

### Expected behavior

The prefix in the nickname should not have been limited.

### Steps to reproduce

Set player prerfix to (P)&c&lImperator&f using LuckPerms

### Additional info

![2023-01-10_15 58 11 (2)](https://user-images.githubusercontent.com/122363966/211546272-2a8f97a6-63df-401e-ad06-9efbdbf04366.png)

![image](https://user-images.githubusercontent.com/122363966/211546562-a2695b92-3c00-44c4-868e-a41729735024.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#limitations
