### ISSUE TITLE
[Emergency] TAB forces the server to shut down.

### ISSUE THREAD

**Issue by madebygood** [NEZNAMY/TAB#789]
### Server version

Purpur 1.19.2

### TAB version

3.2.1

### Describe the bug

Server keeps crashing due to TAB plugin.
Probably the server crashes often when mining and picking up blocks.

I'll attach the log.

If I remove the TAB plugin, the server will not turn off.

### Expected behavior

![image](https://user-images.githubusercontent.com/43653581/211699658-59f1ae92-566f-4173-98f4-181cd771de77.png)

### Steps to reproduce

1) Open the server.
2) Cap the block.
3) The server is turned off.

It may be conflicting with some plugins.

### Additional info

[hs_err_pid12036.log](https://github.com/NEZNAMY/TAB/files/10388151/hs_err_pid12036.log)
[replay_pid12036.log](https://github.com/NEZNAMY/TAB/files/10388152/replay_pid12036.log)

![image](https://user-images.githubusercontent.com/43653581/211702296-ba827b77-98bd-4f26-a52c-bd3e14724530.png)
Sometimes the server turns off immediately after turning it on for no reason.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Java bug.
