### ISSUE TITLE
[TAB] Failed to enable

### ISSUE THREAD

**Issue by Jakaboii** [NEZNAMY/TAB#79]
**Server version**
Paper 1.8.8

**Plugin version** ("latest" is not a version)
2.6.0

**Describe the bug**
Anytime I try to start the plugin, it just sends the error
This didn't happen to me before, so I don't know why it would now

**How to reproduce**
Start your server?

**Expected behavior**
It's supposed to enable the plugin

**Actual behavior**
It doesn't enable the plugin & sends an error

**Additional info**
`
> [22:50:06 INFO]: [TAB] Enabling TAB v2.6.0
> [22:50:06 INFO]: [TAB] Server version: 1.8.8 (v1_8_R3)
> [22:50:06 INFO]: [TAB] Failed to enable
> [22:50:06 INFO]: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
> [22:50:06 INFO]: at me.neznamy.tab.shared.ConfigurationFile.getList(ConfigurationFile.java:184)
> [22:50:06 INFO]: at me.neznamy.tab.platforms.bukkit.Main.loadConfig(Main.java:568)
> [22:50:06 INFO]: at me.neznamy.tab.shared.Configs.loadConfig(Configs.java:140)
> [22:50:06 INFO]: at me.neznamy.tab.shared.Configs.loadFiles(Configs.java:125)
> [22:50:06 INFO]: at me.neznamy.tab.platforms.bukkit.Main.load(Main.java:105)
> [22:50:06 INFO]: at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:50)
> [22:50:06 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [22:50:06 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
> [22:50:06 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
> [22:50:06 INFO]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
> [22:50:06 INFO]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
> [22:50:06 INFO]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
> [22:50:06 INFO]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
> [22:50:06 INFO]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
> [22:50:06 INFO]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
> [22:50:06 INFO]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
> [22:50:06 INFO]: at java.lang.Thread.run(Thread.java:748)
`

**Comment by NEZNAMY** [comment]
You misconfigured "ignore-pwp-in-worlds" option in advancedconfig.yml. It is supposed to be a list, you made it a map.

**Comment by Jakaboii** [comment]
Ahh, OK
I wanted it to be nothing so I made it `{}` but making it `[]` fixed it 
Thanks!
