### ISSUE TITLE
Gradient does not work

### ISSUE THREAD

**Issue by soshimee** [NEZNAMY/TAB#790]
### Server version

Paper 1.19.3

### TAB version

3.2.1

### Describe the bug

Code: 
![image](https://user-images.githubusercontent.com/45235204/211959513-37526b0c-c9dd-4c16-bd01-027f0e1b2eef.png)
Shows as:
![image](https://user-images.githubusercontent.com/45235204/211959474-92822df3-e8b0-4fe4-bfbe-72d79d0638b2.png)

### Expected behavior

Supposed to look like:
![image](https://user-images.githubusercontent.com/45235204/211959464-e7ce0223-f066-4ba4-8c60-7f9c54e6ef29.png)

### Steps to reproduce

1. <gradient> with named colors
2. breaks

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Where does wiki say it supports named colors?

**Comment by soshimee** [comment]
![image](https://user-images.githubusercontent.com/45235204/212231957-6a94045f-7a53-425c-abb7-c82ea1d11ec0.png)
I think it's best to follow what the official Adventure API does.

**Comment by NEZNAMY** [comment]
I am not affiliated with adventure API.

**Comment by soshimee** [comment]
Alright I was just wrong about this issue. It seems to be related with nesting. So I can't have gradients while it's bold, underlined, strikethrough, etc.
