### ISSUE TITLE
Placeholder took longer than 50ms to retrieve value for player

### ISSUE THREAD

**Issue by samparotony228** [NEZNAMY/TAB#792]
### Server version

git-Purpur-1858 (MC: 1.19.2)*

### TAB version

3.2.2

### Stack trace

[errors.log](https://github.com/NEZNAMY/TAB/files/10428152/errors.log)

### Steps to reproduce (if known)

This happens during the game at any time.

### Additional info

How can this error be corrected? If this error is not a bug on the plugin side.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That's to prevent placeholders from freezing TAB when using sleep/SQL tasks that freeze forever. Intended behavior. Do you wish to have a higher timeout?

**Comment by samparotony228** [comment]
> That's to prevent placeholders from freezing TAB when using sleep/SQL tasks that freeze forever. Intended behavior. Do you wish to have a higher timeout?

Yes, I would like this function to be configurable in the plugin.

**Comment by samparotony228** [comment]
And this error does not entail serious problems on the side of the plugin? Is it a sign that the plugin is configured incorrectly?

**Comment by NEZNAMY** [comment]
In that case, how would you prevent 10 year old from opening an issue if they set the value to something like 1 and get spammed and placeholders will stop working?

**Comment by samparotony228** [comment]
> In that case, how would you prevent 10 year old from opening an issue if they set the value to something like 1 and get spammed and placeholders will stop working?

I don't quite understand what you mean. 🙂

**Comment by samparotony228** [comment]
> Imagine you configure timeout to 1ms, which will result in all placeholders taking longer than 1ms to stop working (most of them) and error file getting massively spammed.

I imagined, but then how can I avoid these errors that I sent above in errors.log?

**Comment by NEZNAMY** [comment]
Highly experienced java developers can change 1 number in source code and compile it. I am telling you why I didn't make it configurable and asked you how would you solve the problem I am afraid of.

**Comment by samparotony228** [comment]
> I will increase timeout to 500ms then.

It seems to me that yes, this number should be increased to a high number so that this occurs very rarely. You agree with me?

**Comment by samparotony228** [comment]
> I will increase timeout to 500ms then.

And the value 500 is not small for this? Maybe better than 2000? (Is this value in milliseconds?)

**Comment by NEZNAMY** [comment]
We will see.

**Comment by madebygood** [comment]
I am experiencing the same problem.

250 players are connected to one server,

If the above error appears, the tab is broken and the nickname of the user's character is not displayed.

**Comment by SheepyVN** [comment]
i have a same error for placeholder took longer than 50ms to retrieve value

**Comment by SheepyVN** [comment]
how to increase timeout to 500ms

**Comment by madebygood** [comment]
> how to increase timeout to 500ms

github => actions => download latest

**Comment by kforbro** [comment]
![image](https://user-images.githubusercontent.com/39985355/213446503-34207fc8-1558-4d40-b206-037103ae9611.png)

**Comment by NEZNAMY** [comment]
Reverted timeout entirely.
