### ISSUE TITLE
Broken tab sort and unlimited nametag

### ISSUE THREAD

**Issue by madebygood** [NEZNAMY/TAB#793]
### Server version

purpur 1.19.2

### TAB version

3.2.2

### Describe the bug

After a few minutes of opening the server, the tab list and the character's nameplate are broken.

above the character
Nothing is displayed.

Tabs stop displaying place holder and are no longer sorted.

It is a large server with close to 300 people connected to one server.

I am attaching a picture of the error.

### Expected behavior

If I turn off the unlimited nametag option, the above error does not occur.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/43653581/212814909-fb8be96f-fea0-4b8d-b1da-c49b5fe246f5.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by madebygood** [comment]
[config.txt](https://github.com/NEZNAMY/TAB/files/10433572/config.txt)

**Comment by NEZNAMY** [comment]
Your steps to reproduce some issue include running /tab reload. Is that all? Plugin "breaks" when you run /tab reload? Probably when someone is joining?

**Comment by madebygood** [comment]
> Your steps to reproduce some issue include running /tab reload. Is that all? Plugin "breaks" when you run /tab reload? Probably when someone is joining?

When I open the server and users join, an error occurs. (gradually, not immediately)

Typing '/tab reload' fixes it temporarily, but the same error repeats after a few more minutes.

And when I enter '/tab reload' in a broken state, an error like the picture you sent is displayed.

**Comment by NEZNAMY** [comment]
Send the error that occurs on join.

**Comment by madebygood** [comment]
> Send the error that occurs on join.

There are no errors popping up in the buckkit.

It's just that the tabs aren't jumbled together, and nicknames don't pop up over characters.

User tab-prefix is ​​also not displayed.

**Comment by NEZNAMY** [comment]
Did you get errors.log file? Your steps to reproduce only said run /tab reload, nothing more.

**Comment by madebygood** [comment]
The following text was printed on bukkit.

I'll attach my log file just in case.

11:48:25] [TAB Processing Thread/INFO]: [TAB] [TAB v3.2.2] Placeholder %img_logo_3% took longer than 50ms to retrieve value for player simba5671, aborting.

[11:56:02] [TAB Processing Thread/INFO]: [TAB] [TAB v3.2.2] Placeholder %vault_rank% took longer than 50ms to retrieve value for player JIEUNSUNG, aborting.

[12:51:56] [TAB Processing Thread/INFO]: [TAB] [TAB v3.2.2] Placeholder %essentials_nickname% took longer than 50ms to retrieve value for player wide_deer_bug, aborting.

[anti-override.log](https://github.com/NEZNAMY/TAB/files/10434484/anti-override.log)

[errors.log](https://github.com/NEZNAMY/TAB/files/10434482/errors.log)

[placeholder-errors.log](https://github.com/NEZNAMY/TAB/files/10434489/placeholder-errors.log)

**Comment by NEZNAMY** [comment]
Sounds like #792 . Try going back to 3.2.1 if that solves it.

**Comment by madebygood** [comment]
Servers A, B, and C have the same configuration.

Among them, this error appears only in A and B where more than 200 concurrent connections occur.

The C server isn't popular, and it doesn't generate errors.

Too many connections are also suspect.

**Comment by NEZNAMY** [comment]
Or try latest build from actions if that fixes it.

**Comment by NEZNAMY** [comment]
@madebygood try latest build from github actions.

**Comment by NEZNAMY** [comment]
Fixed in new version, reopen if not
