### ISSUE TITLE
TAB BUG & PLAYER DISCONNECTED

### ISSUE THREAD

**Issue by Darkseno** [NEZNAMY/TAB#794]
### Server version

Purpur 1.19.3 #1895

### TAB version

Free trial 3.2.2

### Stack trace

https://pastebin.com/QSNZavBs

### Steps to reproduce (if known)

Sometimes the TAB & scoreboard bug and when I /tab reload it disconnects the whole server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/212923872-158f95dc-aebf-4aaf-bdc5-0344dd23f021.png)
Send disconnect message from client.

**Comment by NEZNAMY** [comment]
That's console. In game it shows exactly the same thing? "Disconnected"?

**Comment by Darkseno** [comment]
Yes, the /tab reload just made them disconnect.
In game the scoreboard was not displayed anymore & the tab was complete bug 

I only have this information, sorry

**Comment by NEZNAMY** [comment]
Getting "Disconnected" in game means BungeeCord kicked you. Are you using it? If yes, check its console at that time.

**Comment by Darkseno** [comment]
https://pastebin.com/g5ajFxmm

**Comment by NEZNAMY** [comment]
Well that's super useless.
Are you able to find steps to reproduce it in a testing environment? I can fix the error, but I'm not sure if that'll fix the disconnect.

**Comment by Darkseno** [comment]
I was not connected and I don't know how it happened, the players complained that the scoreboard and the TAB were buggy, I did a /tab reload from the console and it kicked them.

I think that the disconnected & the error are necessarily linked and it is since the last update of your plugin.

**Comment by NEZNAMY** [comment]
Try latest build from https://github.com/NEZNAMY/TAB/actions, it might help. "Buggy" is very player-like description which I cannot work with.

**Comment by Darkseno** [comment]
I do not understand where to download on GitHub sorry

**Comment by NEZNAMY** [comment]
You click the build and then jar button on the bottom.

**Comment by matipoirierg** [comment]
same issue here, the plugin randomly stops working, when I do /tab reload it kicks the players and get this error on console:
https://pastebin.com/tv0KXMnN

**Comment by NEZNAMY** [comment]
Did you try with latest build?

**Comment by NEZNAMY** [comment]
Fixed in new version, reopen if not.
