### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by SkirmisLTU** [NEZNAMY/TAB#796]
### Server version

Bungeecord (Xcord 1.50 ) 

### TAB version

and 3.2.2+ (maybe other versions too)

### Describe the bug

I think TAB plugin has memory leak, this might also be a cause of issue  #781  . I did `/sparkb heapsummary` and `/sparkb heapsummary --run-gc-before` this is the results:
Before garbage collector:
![image](https://user-images.githubusercontent.com/51238910/213263539-7aedfaca-d60b-4de2-be5f-4ef0cbd174d6.png)
After garbage collector:
![image](https://user-images.githubusercontent.com/51238910/213263791-066e49a9-00f9-47d7-90bd-8501dca70b1e.png)

As we see `ChatModifier`, `TextColor` and `IChatBaseComponent` was not garbage collected, also `ChatModifier` and `IChatBaseComponent` has the same number of instances (i think that's because `IChatBaseComponent` calls `ChatModifier`).

Here is my heapdump: https://www.mediafire.com/file/jakqa9e6rh8jq2o/tab_config_and_hpdump.zip/file (i wasn't able to upload it here, because it's too big)

### Expected behavior

No memory leak, `ChatModifier`, `TextColor` and `IChatBaseComponent` being garbage collected normaly

### Steps to reproduce

1. Install bungeecord and spigot servers
2. Add tab and spark plugins to bungeecord.
3. Get some players.
4. Analyze memory (easiest and fastes way to do it is `/sparkb heapsummary` and `/sparkb heapsummary --run-gc-before` in my opinion)
5. 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by SkirmiLTU** [comment]
I already gave you the link to heapdump in bug description. https://www.mediafire.com/file/jakqa9e6rh8jq2o/tab_config_and_hpdump.zip/file
There is heapdump and config in the zip. Also, I'd like to mention, that this also occurs on clean waterfall (no plugins)

**Comment by NEZNAMY** [comment]
Oh oops, I missed that. I just bought an expensive license for a java profiling tool, I'll let you know what I find.

**Comment by NEZNAMY** [comment]
Well apparently it's correct. 6400 components are cached, the rest are their extras ("children"). I wasted 100$ on this.

**Comment by SkirmiLTU** [comment]
Do you have any thoughts on #781 because this issue persists?

**Comment by NEZNAMY** [comment]
No, but TAB is not causing your server to run out of memory.

**Comment by SkirmiLTU** [comment]
It's not running out of memory, it's running out of threads...

**Comment by NEZNAMY** [comment]
You didn't send any error showing that.

**Comment by SkirmiLTU** [comment]
I did, in #781 . this is main part of the error: `me.neznamy.tab.platforms.bungeecord.BungeeEventListener@556733e4
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached` (it's not out of memory by the way)

**Comment by NEZNAMY** [comment]
As I said there, TAB only creates up to 20 threads. I also added a message to the error, did you get it? Does spark offer a way to see all threads and their traces?

**Comment by NEZNAMY** [comment]
Looks like I made a mistake, which although should not matter, may have in the end. Try latest build.

**Comment by Paradis4432** [comment]
is this still open? im having a similar issue, profiling a server with a memory leak i found this 
BEFORE GC
![image](https://github.com/NEZNAMY/TAB/assets/49301263/0c923d82-a912-490d-87d7-10924475656d)

AFTER GC triggered manually 
![image](https://github.com/NEZNAMY/TAB/assets/49301263/66436e51-cf0e-4423-b04c-87b5d22d0daa)

issue doesnt seem to happen with just 1 player online, but it does with 40-90.

**Comment by NEZNAMY** [comment]
That's cache to prevent servers from blowing up when using high speed animated RGB gradients. Its size is limited and hardcoded. You can change it in the code if you think it's too high.

**Comment by Paradis4432** [comment]
it grows consistently over time

**Comment by Paradis4432** [comment]
even with no animations

**Comment by NEZNAMY** [comment]
Then it makes sense, you are filling the cache up slowly and therefore it doesn't regularly reset.

**Comment by Paradis4432** [comment]
and whats the solution for this?

**Comment by NEZNAMY** [comment]
If you don't want the cache, decrease its size in code.

**Comment by Paradis4432** [comment]
i need to rebuild the plugin?

**Comment by NEZNAMY** [comment]
Yes.

**Comment by Paradis4432** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/49301263/38a89957-5801-4b67-840b-2a88c08a72d7)
this is the server after a few hours, i dont think its limited at all

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/util/ComponentCache.java#L21-L28 I see nothing wrong with the code. I'll perform some tests.

**Comment by NEZNAMY** [comment]
I can confirm it works properly. You can decrease cache size and see if memory usage gets smaller.
