### ISSUE TITLE
Error NoSuchElementException

### ISSUE THREAD

**Issue by BestMark** [NEZNAMY/TAB#797]
### Server version

Pufferfish 1.19.3

### TAB version

3.2.1 and 3.2.2

### Stack trace

18.01.2023 - 19:24:32 - [TAB v3.2.2] An error occurred when reading packets
18.01.2023 - 19:24:32 - java.util.NoSuchElementException: null
18.01.2023 - 19:24:32 - at java.base/java.util.concurrent.CopyOnWriteArrayList$COWIterator.next(CopyOnWriteArrayList.java:1099)
18.01.2023 - 19:24:32 - at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
18.01.2023 - 19:24:32 - at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1054)
18.01.2023 - 19:24:32 - at TAB.v3.2.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPacketBuilder.build(BukkitPacketBuilder.java:103)
18.01.2023 - 19:24:32 - at TAB.v3.2.2.jar//me.neznamy.tab.shared.FeatureManagerImpl.onPacketPlayOutPlayerInfo(FeatureManagerImpl.java:97)
18.01.2023 - 19:24:32 - at TAB.v3.2.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:72)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
18.01.2023 - 19:24:32 - at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
18.01.2023 - 19:24:32 - at eGlow 3.2.1 1.9.4-1.19.3.jar//me.MrGraycat.eGlow.Util.Packets.PipelineInjector$1.write(PipelineInjector.java:92)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
18.01.2023 - 19:24:32 - at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
18.01.2023 - 19:24:32 - at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
18.01.2023 - 19:24:32 - at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
18.01.2023 - 19:24:32 - at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
18.01.2023 - 19:24:32 - at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
18.01.2023 - 19:24:32 - at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
18.01.2023 - 19:24:32 - at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
18.01.2023 - 19:24:32 - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
18.01.2023 - 19:24:32 - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
18.01.2023 - 19:24:32 - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
18.01.2023 - 19:24:32 - at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
18.01.2023 - 19:24:32 - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
18.01.2023 - 19:24:32 - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
18.01.2023 - 19:24:32 - at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

Step 1. Install TAB plugin.
Step 2. Install eGlow plugin.

### Additional info

https://github.com/MrGraycat/eGlow/issues/31

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
According to that error no player was online while a packet was being sent to some player.

**Comment by BestMark** [comment]
> According to that error no player was online while a packet was being sent to some player.

Yes. Can you fix it? Or the reason is in other plugin?

**Comment by NEZNAMY** [comment]
Doesn't look like you understood my sentence. I will try to fix the issue.
