### ISSUE TITLE
broke the plugin

### ISSUE THREAD

**Issue by Aurnobb-Tasneem** [NEZNAMY/TAB#799]
### Server version

Paper 1.19.2

### TAB version

3.2.3

### Stack trace

https://paste.md-5.net/gazumohana.md

### Additional info

Basically I wanted to delete the empty space in TAB when I turned on the layout.yml. so in player slots i wrote '2-%bungee_survival%'. That's how I broke it.  IK there should be an integer but I wanna delete the empty space

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You clearly have a space after the `2`, see the message you sent.

**Comment by Aurnobb-Tasneem** [comment]
but same thing happened when I tried to do this https://paste.md-5.net/sanopimaju.cs

**Comment by NEZNAMY** [comment]
Makes sense. %bungee_survival% is not a number.
