### ISSUE TITLE
Tab and tag attributes randomly stops working for some players

### ISSUE THREAD

**Issue by matipoirierg** [NEZNAMY/TAB#800]
### Server version

Purpur 1.19.3

### TAB version

3.2.3

### Describe the bug

I can't reproduce this, it happens randomly, tab and tag attributes stop working for some players. 
![2023-01-21_20 24 49](https://user-images.githubusercontent.com/97362850/213894024-ebc33db5-a03f-4216-92a7-fd859d056f5c.png)
![2023-01-21_20 25 55](https://user-images.githubusercontent.com/97362850/213894027-68471d98-62a6-47e7-9b03-f30b55cc4982.png)

### Expected behavior

The plugin should show the attributes of all players.

### Steps to reproduce

I can't

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by matipoirierg** [comment]
also there is no error on console

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/213894056-94233ed2-d81f-48f9-9a4f-98ecc14ab1c7.png)
send your config

**Comment by matipoirierg** [comment]
> ![image](https://user-images.githubusercontent.com/45695833/213894056-94233ed2-d81f-48f9-9a4f-98ecc14ab1c7.png) send your config

XD https://pastebin.com/52MxrFK6

**Comment by Tanguygab** [comment]
Are you using Waterfall?

**Comment by matipoirierg** [comment]
also plugin was working without any issues before the first update required for 1.19.3, I didn't change any configuration since then, and yes I'm suing waterfall.

**Comment by Tanguygab** [comment]
can you send your waterfall.yml file?

**Comment by NEZNAMY** [comment]
Do those players see visuals from TAB? 
Does `/tab debug <player>` work on those players? 
Did you get errors.log file in TAB's folder? 
If you set debug: true in config, will it say players were loaded when a bugged player joins?
Does /tab reload fix it?

**Comment by matipoirierg** [comment]
> Do those players see visuals from TAB? Does `/tab debug <player>` work on those players? Did you get errors.log file in TAB's folder? If you set debug: true in config, will it say players were loaded when a bugged player joins? Does /tab reload fix it?
I found out that the tab it's different for every player (once the the bug starts). I told my community to send pictures on how they see the tab and ask them to rejoin and send a picture again. These were the results:
Player 1:
First ss: 
![image](https://user-images.githubusercontent.com/97362850/213959146-97173bc7-d7a7-472d-b0b6-92b969b84d29.png)
After reconnect:
![image](https://user-images.githubusercontent.com/97362850/213959162-b03a3d70-ed9c-4e40-9352-241cbfee0c18.png)

Player 2:
First ss:
![image](https://user-images.githubusercontent.com/97362850/213959189-4e750943-f891-450d-b5ff-db9babc76f48.png)
After reconnect:
![image](https://user-images.githubusercontent.com/97362850/213959211-20976bbd-3ddb-40ec-bd05-2e5f8c150ef0.png)
Player 3:
First ss:
![image](https://user-images.githubusercontent.com/97362850/213959257-180c29d8-19f9-4de8-aad6-6a1fce775e64.png)
After reconnect:
![image](https://user-images.githubusercontent.com/97362850/213959267-294f1034-9c04-4f94-9919-468185f02dfe.png)

Tab debug return error when used on white players on tab: https://pastebin.com/HtDcvgM4 (It works on other players), no error on error.logs.
Tab reload does not fix it and also kicks people and give error: https://pastebin.com/LTdJC5nM

**Comment by matipoirierg** [comment]
I'll try the debug now.

**Comment by matipoirierg** [comment]
I enabled debug and I did /tab reload and the tab seems to be fixed cause white player dissapear but it starts spamming this error: https://pastebin.com/QTW1VAAs

**Comment by matipoirierg** [comment]
Sorry for being inconsistent but this behaves pretty randomly.

**Comment by matipoirierg** [comment]
Bug started happening again, I told a bugged player to reconnect but debug seems fine [03:33:18 INFO]: [TAB] [DEBUG] Player join of Unsy27 processed in 1ms

**Comment by NEZNAMY** [comment]
Show console output when the player joined for the first time when they got the issue.

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by matipoirierg** [comment]
> Show console output when the player joined for the first time when they got the issue. Can you also try if you get this issue with TAB 3.2.1? It would be convenient if I could send you jars to test on discord. Did you buy the plugin so you have access to tickets?

> Show console output when the player joined for the first time when they got the issue. It'll be hard since the bug affects players that are already online, issue started on 3.2.0, I just bought the plugin, I'll try the latest build firstm if not working I'll join the discord.

**Comment by matipoirierg** [comment]
Also I got an error when the bug starts, https://mclo.gs/QgYEdtU

**Comment by NEZNAMY** [comment]
> Also I got an error when the bug starts, https://mclo.gs/QgYEdtU

Out of the 5 people who reported this, you are the first one who provided this useful stack trace. Try latest build from actions.

**Comment by matipoirierg** [comment]
Running latest action build without any issues, ty very much.
