### ISSUE TITLE
tab and tag suffix dont work

### ISSUE THREAD

**Issue by FireQuacker** [NEZNAMY/TAB#801]
### Server version

Purpur 1.19

### TAB version

3.2.3

### Describe the bug

tag and tab suffix dont show even though it is set in config

![image](https://user-images.githubusercontent.com/58408434/213898115-5c44e4fc-d7b7-4495-adb5-76a7afcb973e.png)

![image](https://user-images.githubusercontent.com/58408434/213898123-51f0da4d-a11a-455b-a234-8293ec4ae95e.png)

### Expected behavior

Show tab and tag prefix

### Steps to reproduce

tabprefix: "tabprefix "
  tabsuffix: " tabsuffix"
  tagprefix: "tagprefix "
  tagsuffix: " tagsuffix"
  
In groups.yml under _DEFAULT_:

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of `/tab debug <player>`

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/213919048-be022559-9292-496e-8700-530567cb2294.png)
![image](https://user-images.githubusercontent.com/6338394/213919057-b4331eac-ac25-4af7-96e8-ecd4f7e6c5dd.png)
