### ISSUE TITLE
Placeholder took longer than 50ms to retrieve value for player

### ISSUE THREAD

**Issue by catches** [NEZNAMY/TAB#802]
### Server version

Pufferfish+ 1.19.3

### TAB version

3.2.2

### Stack trace

Getting messages like this on console, don't know what it means, or how to fix it, or if it's a normal thing?
![image](https://user-images.githubusercontent.com/105005455/213917510-320253f9-a878-47f1-82ae-6656e4e9f65c.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/213917574-97738833-d59f-4dfa-9fdf-e51176d9c19a.png)
No, you're not. This was removed in 3.2.3, which is latest.
