### ISSUE TITLE
i got this error when i had 50 players in the server and the server started lagging and i'm 100% sure its from tab plugin

### ISSUE THREAD

**Issue by HEMO313** [NEZNAMY/TAB#804]
### Server version

CarbonSpigot 1.8.9

### TAB version

3.2.3

### Stack trace

21.01.2023 - 14:56:20 - [TAB v3.2.1] An error was thrown when executing task
21.01.2023 - 14:56:20 - java.lang.NullPointerException: null
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.placeholders.TabPlaceholder.getNestedPlaceholders(TabPlaceholder.java:99)
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.placeholders.TabPlaceholder.setPlaceholders(TabPlaceholder.java:133)
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:56)
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:117)
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68)
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:350)
21.01.2023 - 14:56:20 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112)
21.01.2023 - 14:56:20 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21.01.2023 - 14:56:20 - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21.01.2023 - 14:56:20 - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21.01.2023 - 14:56:20 - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21.01.2023 - 14:56:20 - 	at java.lang.Thread.run(Thread.java:748)
22.01.2023 - 13:29:39 - [TAB v3.2.3] An error was thrown when executing task
22.01.2023 - 13:29:39 - java.lang.NullPointerException: null
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.placeholders.TabPlaceholder.getNestedPlaceholders(TabPlaceholder.java:99)
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.placeholders.TabPlaceholder.setPlaceholders(TabPlaceholder.java:133)
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:56)
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:117)
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68)
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:354)
22.01.2023 - 13:29:39 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:111)
22.01.2023 - 13:29:39 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22.01.2023 - 13:29:39 - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22.01.2023 - 13:29:39 - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22.01.2023 - 13:29:39 - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22.01.2023 - 13:29:39 - 	at java.lang.Thread.run(Thread.java:748)
22.01.2023 - 15:12:53 - [TAB v3.2.3] An error was thrown when executing task
22.01.2023 - 15:12:53 - java.lang.NullPointerException: null
22.01.2023 - 15:12:53 - 	at me.neznamy.tab.shared.features.nametags.NameTag.refresh(NameTag.java:85)
22.01.2023 - 15:12:53 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:79)
22.01.2023 - 15:12:53 - 	at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:71)
22.01.2023 - 15:12:53 - 	at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:354)
22.01.2023 - 15:12:53 - 	at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:111)
22.01.2023 - 15:12:53 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22.01.2023 - 15:12:53 - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22.01.2023 - 15:12:53 - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22.01.2023 - 15:12:53 - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22.01.2023 - 15:12:53 - 	at java.lang.Thread.run(Thread.java:748)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/213934282-617d4a92-a437-4ba7-8c47-ef98e1073dd5.png)

**Comment by NEZNAMY** [comment]
Did you reload the plugin at the time of the errors from 3.2.3?

**Comment by HEMO313** [comment]
> Did you reload the plugin at the time of the errors from 3.2.3?

yes cause a few players in tab was in white color and sometimes all players is in white
![image](https://user-images.githubusercontent.com/39499245/213937081-a5872e2c-906a-4662-9245-ce79062a38bf.png)

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/issues/800#issuecomment-1399499258 please answer these questions then.

**Comment by HEMO313** [comment]
> [#800 (comment)](https://github.com/NEZNAMY/TAB/issues/800#issuecomment-1399499258) please answer these questions then.

Do those players see visuals from TAB? what does that mean
Does /tab debug <player> work on those players? yes
Did you get errors.log file in TAB's folder? yes and i send it up
If you set debug: true in config, will it say players were loaded when a bugged player joins? i will try that but idk how should i know which players cause this bug happen almost to everyone
Does /tab reload fix it? no

**Comment by NEZNAMY** [comment]
If it happens to everyone, just pick one player then.

**Comment by HEMO313** [comment]
> If it happens to everyone, just pick one player then. Can you try if you get it with TAB 3.2.1 as well? Also send your config just in case. Also show output of /tab cpu.

the problem is i don't get it now only when i get alot of players

`# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml
header-footer:
  enabled: true
  header:
  - '&e&lEagle&6&lMc'
  - '&e---------------'
  footer:
  - '&e---------------'
  - '&6store.eaglemc.net'
  disable-in-worlds:
  - disabledworld
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-in-worlds:
  - disabledworld
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
scoreboard-teams:
  enabled: true
  invisible-nametags: false
  anti-override: false
  enable-collision: true
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
  case-sensitive-sorting: true
  sorting-types:
  - GROUPS:owner,headadmin,admin,dev,srmod,moderator,helper,builder,trial,youtuber,eagle,diamond,gold,default
  - PLACEHOLDER_A_TO_Z:%player%
  can-see-friendly-invisibles: false
yellow-number-in-tablist:
  enabled: false
  value: ''
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: false
  number: '%health%'
  text: Health
  disable-in-worlds:
  - disabledworld
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
      announcement-bar: false
    test:
      display-condition: permission:tab.bossbar.test;%world%=testworld
      style: PROGRESS
      color: WHITE
      progress: '100'
      text: test
      announcement-bar: false
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%&7/&4%maxplayers%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
ping-spoof:
  enabled: false
prevent-spectator-effect:
  enabled: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    'true': ' &4*&4&lAFK&4*&r'
    'false': ''
  '%clantagprovider_clan_color%':
    '': '§f'
    'else': '§%clantagprovider_clan_color%'
  '%clantagprovider_clantag%':
    '': ''
    'else': ' [%clantagprovider_clantag%]'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    'yes': '%player%'
    'no': ~%essentials_nickname%
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: true
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 500
assign-groups-by-permissions: false
primary-group-finding-list:
- owner
- admin
- dev
- srmod
- moderator
- helper
- builder
- trial
- youtuber
- eagle
- diamond
- gold
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby: {}
fix-pet-names:
  enabled: false
`

**Comment by NEZNAMY** [comment]
That paste into a comment is just horrible. I can see you have anti-override disabled. Enable them both. And show output of /tab cpu.

**Comment by HEMO313** [comment]
![image](https://user-images.githubusercontent.com/39499245/213938611-0190add7-02e7-486f-b6dc-efda016c9d18.png)

**Comment by NEZNAMY** [comment]
I don't know then. You will need to provide steps to reproduce.

**Comment by HEMO313** [comment]
> I don't know then. You will need to provide steps to reproduce.

i think i fixed it the problem is from updating the placeholder it update every 100 tick so i think thats it

**Comment by NEZNAMY** [comment]
What placeholder? How is 100 ticks a problem? Is the issue solved?

**Comment by HEMO313** [comment]
> What placeholder? How is 100 ticks a problem? Is the issue solved?

the clantag placeholder it was using too much cpu so maybe from it and i don't know it if it solved cause i need to test it with many players but the cpu usage is much less now when i changed the ticks

**Comment by NEZNAMY** [comment]
That is possible. Run /tab cpu every 10 seconds and check outputs, maybe once in a while the placeholder will appear there with enormous number.

**Comment by HEMO313** [comment]
> That is possible. Run /tab cpu every 10 seconds and check outputs, maybe once in a while the placeholder will appear there with enormous number.

ok now i tested for almost 30 minutes and everything looks perfect
i have a question you told me enable anti-override option is it needed anymore cause in docs its says disable it for better performance

**Comment by NEZNAMY** [comment]
It also says disable it if you don't need it. I don't know if you need it or not. But I will not accept any bug reports with anti-override disabled, since it's the cause most of the time.

**Comment by HEMO313** [comment]
ok i will keep it on until tomorrow tomorrow players will join and i will test

**Comment by HEMO313** [comment]
thank you so much for your time

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by NEZNAMY** [comment]
(again, new build was published)
