### ISSUE TITLE
TabSuffix over ping

### ISSUE THREAD

**Issue by jman13378** [NEZNAMY/TAB#805]
### Server version

git-Paper 1.18.2 388

### TAB version

3.2.3

### Describe the bug

When i put something in the tabsuffix and have right align on it will be over the ping

### Expected behavior

show **NEXT** to the ping

### Steps to reproduce

create a tabsuffix
enable `tablist-name-formatting.align-tabsuffix-on-the-right` and `tablist-name-formatting.enabled`
then reload TAB

### Additional info

![image](https://user-images.githubusercontent.com/101841938/213946947-4b0918be-068a-4dc5-9c78-2a7a80c0f71b.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Your GUI scale with long tablist formatting is too high for your monitor to handle. The 3 spaces are expected and required for alignment to work properly.
