### ISSUE TITLE
Where can we suggest a new features? I‘d even pay for it? But there is no information…

### ISSUE THREAD

**Issue by PalmTamino** [NEZNAMY/TAB#807]
##test

**Comment by NEZNAMY** [comment]
Readme says feature requests are closed forever because I no longer want to involve in MC.

**Comment by PalmTamino** [comment]
> #805



> Readme says feature requests are closed forever because I no longer want to involve in MC.

So tab is discontinued besides bug fixes? :/

**Comment by NEZNAMY** [comment]
That's right, plugin is in maintenance mode now. Small tiny additions requested by buyers on discord are still accepted, but no new major stuff like chat formatting, titles, actionbar and similar.
Pull requests are being accepted if they don't have any issues.

**Comment by PalmTamino** [comment]
> That's right, plugin is in maintenance mode now. Small tiny additions requested by buyers on discord are still accepted, but no new major stuff like chat formatting, titles, actionbar and similar.
> Pull requests are being accepted if they don't have any issues.

Okay, because I want a feature that the disabling scoreboard option (toggling it) saves after rejoin and server switch (bungee). I would pay you the price of the plugin for it would you do it? Or is this considered too big?

**Comment by NEZNAMY** [comment]
remember-toggle-choice: true

**Comment by PalmTamino** [comment]
> remember-toggle-choice: true
oh well, thanks!!
