### ISSUE TITLE
Placeholder dont work between Paper and BungeeCord

### ISSUE THREAD

**Issue by kouke0638** [NEZNAMY/TAB#809]
### Server version

Paper 1.19.3

### TAB version

3.2.4

### Describe the bug

![image](https://user-images.githubusercontent.com/60027874/214641267-f90e2979-ae39-4b9a-a5f3-70ca05cc74a8.png)

I upgraded from Minecraft 1.16.5 and at that time I had TAB version 2.8.11 installed and running on BungeeCord, along with TAB-BukkitBridge on the PaperServer side. However, when I upgraded to 1.19.3 and also updated the TAB version to 3.2.4 , the Placeholder became invalid. There were no errors in the console. I want to know if I possibly did something wrong or if this is a normal situation.

### Expected behavior

I believe it should be able to display Placeholders normally instead of being stuck in that state.

### Steps to reproduce

1. I installed TAB 3.2.4 on BungeeCord, and at the same time, installed the latest TAB-BukkitBridge on the PaperServer.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Did you update bridge? Communication protocol changed in TAB 3.0.0.

**Comment by kouke0638** [comment]
Yes, I tried updating, but it didn't have any effect.

**Comment by kouke0638** [comment]
The new version is TAB-BukkitBridge v1.5.2, correct?

**Comment by NEZNAMY** [comment]
Show output of /papi list.

**Comment by kouke0638** [comment]
So the plugin on Spigot is not updated? I'll try again then.......

**Comment by NEZNAMY** [comment]
I got banned from spigot in 2021, how could you not have noticed?

**Comment by kouke0638** [comment]
It worked!! Sorry for bothering you, I haven't maintained the server for more than 2 years. I just searched the plugin name on Google and since the TAB-BukkitBridge website is still up, I thought TAB was just banned, but it turned out the whole account was, I'm really sorry.
