### ISSUE TITLE
Scoreboard not showing after someone rejoin

### ISSUE THREAD

**Issue by Lazer4o** [NEZNAMY/TAB#811]
### Server version

Paper 1.16.5

### TAB version

3.2.4

### Describe the bug

The scoreboard is working fine but when someone rejoin the scoreboard is hidden (He didn't typed the command /sb or smth)

### Expected behavior

Because, i am using the scoreboard option from this plugin!

### Steps to reproduce

idk

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/215200244-0391e674-d4e1-40dd-bf2c-6f274e485c0e.png)
![image](https://user-images.githubusercontent.com/6338394/215200279-9e6bb6a9-d820-4356-95b3-650935f48b87.png)
You're not serious, right? Show plugin list and TAB config.

**Comment by Lazer4o** [comment]
![image](https://user-images.githubusercontent.com/84748484/215201411-9548d5d5-7901-4dce-9ff8-f1ff8a385d69.png)

[tabconfig.txt](https://github.com/NEZNAMY/TAB/files/10523202/tabconfig.txt)

**Comment by Lazer4o** [comment]
here


> ![image](https://user-images.githubusercontent.com/6338394/215200244-0391e674-d4e1-40dd-bf2c-6f274e485c0e.png) ![image](https://user-images.githubusercontent.com/6338394/215200279-9e6bb6a9-d820-4356-95b3-650935f48b87.png) You're not serious, right? Show plugin list and TAB config.

**Comment by NEZNAMY** [comment]
Compatibility page says SkBee breaks TAB's scoreboard.
![image](https://user-images.githubusercontent.com/6338394/215202177-40cd47b0-e7a9-4ef5-bdc9-5356efe9d779.png)
another lie from your "bug report".
