### ISSUE TITLE
Is there any way to make the TAB not take over the tab list of the subservice

### ISSUE THREAD

**Issue by HansOffice** [NEZNAMY/TAB#814]
After installing the TAB plugin in my group service, it will automatically take over the tabs of the subservices causing the tab list of my original subservices to be unavailable, I checked the wiki but didn't get effective help, is there a way to make the TAB plugin not take over the tab list of the specified subservices?

**Comment by NEZNAMY** [comment]
Disable global playerlist I guess? 
This is an issue tracker, not support.

**Comment by NEZNAMY** [comment]
Please don't use github issues for support.
