### ISSUE TITLE
Error after /tab reload causing players to disconnect from server

### ISSUE THREAD

**Issue by liquidman228** [NEZNAMY/TAB#815]
### Server version

Paper 1.19.2

### TAB version

3.2.3

### Stack trace

  [Tue 16:32:44 INFO  Server/PlayerConnection] d1nPP issued server command: /tab reload
  [Tue 16:32:44 INFO ] [TAB] [TAB v3.2.3] Failed to disable
  [Tue 16:32:44 INFO ] [TAB] java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.ArmorStandManager.destroy()" because the return value of "me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.getArmorStandManager(me.neznamy.tab.api.TabPlayer)" is null
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.shared.features.nametags.unlimited.NameTagX.unload(NameTagX.java:100)
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.platforms.bukkit.features.unlimitedtags.BukkitNameTagX.unload(BukkitNameTagX.java:65)
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.shared.FeatureManagerImpl.unload(FeatureManagerImpl.java:53)
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.shared.TAB.unload(TAB.java:187)
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.shared.command.ReloadCommand.execute(ReloadCommand.java:21)
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.shared.command.TabCommand.execute(TabCommand.java:55)
  [Tue 16:32:44 INFO ] [TAB]     at TAB.v3.2.3.jar//me.neznamy.tab.platforms.bukkit.Main$TABCommand.onCommand(Main.java:128)
  [Tue 16:32:44 INFO ] [TAB]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
  [Tue 16:32:44 INFO ] [TAB]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
  [Tue 16:32:44 INFO ] [TAB]     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
  [Tue 16:32:44 INFO ] [TAB]     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
  [Tue 16:32:44 INFO ] [TAB]     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2294)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
  [Tue 16:32:44 INFO ] [TAB]     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.TickTask.run(TickTask.java:18)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1389)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
  [Tue 16:32:44 INFO ] [TAB]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
  [Tue 16:32:44 INFO ] [TAB]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Tue 16:32:44 INFO ] [TAB] Animation "dominatus" has refresh interval of 90 which is not divisible by 50! Using 50.

### Steps to reproduce (if known)

Let the server run for a while
Do /tab reload

### Additional info

I have another issue happen sometimes - i have 'double nicknames'
I saw on the internet that it can be because of geyser (bedrock) players
Maybe this 'double nickname' issue somehow related to this problem?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/215832478-9a1a010a-dfb6-463b-af2f-4877d79098a9.png)
No. This was fixed in 3.2.4.
