### ISSUE TITLE
How to stop TAB from messing with peoples names

### ISSUE THREAD

**Issue by BluishHaze** [NEZNAMY/TAB#816]
### Server version

Latest Paper

### TAB version

3.4.2

### Describe the bug

I have a team called red with a specific prefix and color, but when TAB is enabled you don’t see the prefix or the name color above someone’s head you just see their name plain white. Also when a player has a glowing effect, the glow isn’t determined by their team color it’s just plain white.

### Expected behavior

I think the plug-in should not mess with players namestags and glowing color.

### Steps to reproduce

Just use the plug-in make a new team give it a color then join the team and give yourself the glowing effect, it will just be plain white.

### Additional info

Nope

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
`I think the plug-in should not mess with players namestags and glowing color.`
It doesn't if you disable it, obviously.
