### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by zfsbsdf** [NEZNAMY/TAB#817]
### Server version

Paper 1.19.3

### TAB version

3.2.4

### Describe the bug

1.I hope the author can add translatable files (properties),because when I input Chinese, the plug-in doesn't work
2.For example
![1](https://user-images.githubusercontent.com/113145735/217201991-0bdcb724-ecac-4611-a7e4-226849789f20.png)

### Expected behavior

The plug-in can be simply localized,Support author!

### Steps to reproduce

Step 1:When I modify these contents
![1](https://user-images.githubusercontent.com/113145735/217203430-fabfbf63-f083-4382-8d81-7c09a06bfd7a.png)
Step 2:It doesn't work

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
you need to save the file with the UTF-8 encoding
