### ISSUE TITLE
The tab disappears with a large number of players

### ISSUE THREAD

**Issue by dwdsty** [NEZNAMY/TAB#818]
### Server version

Purpur 1.16.5

### TAB version

3.2.4

### Describe the bug

At an online rate of over 300 players, the tab just disappears. On the server of 500 players, the tab disappeared, but the plugin itself works. After restarting /tab the tab appears

### Expected behavior

The tab should not disappear

### Steps to reproduce

Start 300 or more bots on the server. Then log out of the server and log in again.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Check usage of /tab cpu, the plugin might be overloaded.

**Comment by dwdsty** [comment]
When there is a lot of online, the fillers from the Plan plugin are loaded. I guess I need to contact the developer of the Plan plugin ?

**Comment by NEZNAMY** [comment]
I have no idea, I didn't see the output.

**Comment by dwdsty** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/80200880/218189241-baa2cc45-ec49-45ba-b10f-f2ba316d4dbd.png)

**Comment by NEZNAMY** [comment]
That explains everything. This is not a TAB bug, but an issue with an inefficient placeholder which I cannot do anything about.
Here are a few things you can do:
* Drastically [increase refresh intervals](https://github.com/NEZNAMY/TAB/wiki/Optimizing-the-plugin#2---placeholder-refresh-intervals) (start with 5000 and see)
* Consider not using the placeholders at all
* Contact authors of those placeholders/plugins
