### ISSUE TITLE
belowname for player, NOT for citizen

### ISSUE THREAD

**Issue by Zzheyd** [NEZNAMY/TAB#82]
**Server version** 1.15.1

**Plugin version** ("latest" is not a version) 2.6.1

Hello :)

**Describe the bug**
I have try this : 

`belowname:
  refresh-interval-ticks: 5
  number: '%health%'
  text: '&4❤'
  enabled: true`

It's perfect ... but ... i see Citizens health too :'(

It's a bug ?

Or it's possible to turn off this with citizen, and only see the real player ?

**Additional info** (errors, screenshots, ...)

This is a NPC with plugin Citizens

https://www.zupimages.net/up/19/52/sya3.png

Thank you very much :)

**Comment by NEZNAMY** [comment]
Not a bug, cannot be disabled on NPCs. Use unlimited nametag mode with it's belowname function.

**Comment by Zzheyd** [comment]
This ?

unlimited-nametag-prefix-suffix-mode:
  enabled: true
  modify-npc-names: false

with this

belowname:
  refresh-interval-ticks: 5
  number: '%health%'
  text: '&4❤'
  enabled: true

?

**Comment by NEZNAMY** [comment]
Leave the vanilla belowname feature off.

**Comment by Zzheyd** [comment]
Ok its turn to false, but, now, how can i see player's health Oo ?

**Comment by NEZNAMY** [comment]
/tab player <playername> belowname <the placeholder with text>
or group (_OTHER_ for all groups)

**Comment by Zzheyd** [comment]
Oh nice perfect thanks !

Its possible to get same result with ennemy ?
If player hurt ennemy, set belowname to hp ?

**Comment by NEZNAMY** [comment]
Just configure it like that and it will show hp of players.

**Comment by Zzheyd** [comment]
And for hostile entity its possible ? Creeper, zombie etc

**Comment by NEZNAMY** [comment]
This plugin only handles players.
