### ISSUE TITLE
I cant download it

### ISSUE THREAD

**Issue by FlriAnus** [NEZNAMY/TAB#820]
### Server version

spigot 1.19

### TAB version

3.2.5

### Stack trace

I cant click download butten even if im logged in it still says i need to register

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/218876965-dba1442d-f284-4e48-b3e2-eb94824d2c4d.png)
I am not a staff member of BuiltByBit and cannot do anything about potential bugs on their website. Did you confirm your email and everything? Alternatively, use another download source, such as [releases](https://github.com/NEZNAMY/TAB/releases).
