### ISSUE TITLE
TAB back-end kick

### ISSUE THREAD

**Issue by 4NTx** [NEZNAMY/TAB#821]
### Server version

PAPER 1.8.8

### TAB version

3.2.5

### Describe the bug

This error from the scoreboard (I tested all the options, and it really is from the scoreboard), when I give /tab reload or change my position in luckperms, it kicks me from the server and also to all other online players. Generates the following error in the proxy (WATERFALL 1.19-511.jar)

https://mclo.gs/B3xp6Vf

### Expected behavior

https://mclo.gs/u0FjNpN

### Steps to reproduce

I made the proxy, without any plugin

Connected to lobby server (paper1.8.8)

In the lobby server I activated the scoreboard

Afterwards, I put luckperms

I put the player's group on the scoreboard

Updated the player's group and got kicked

Also /tab reload and got kicked

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=H2Gr-ary12w) by following all provided steps.

**Comment by Tanguygab** [comment]
I see you're using something called NullCordX
![image](https://user-images.githubusercontent.com/45695833/219402773-d3839544-e4ab-4ea7-948c-561dd97751ca.png)
 can you try on BungeeCord/Waterfall and see if the error occurs as well?

**Comment by 4NTx** [comment]
It's not the proxy or the plugin, it's the fork of the paper I use :x
if it is possible to solve the plugin part, I can pass access to the fork for you to test (I had the same problem with pandaspigot and windspigot)

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/219465920-00551a89-2a36-4d2a-9769-d9f10864a886.png)
Read it again, it has information about random forks. If it works on Paper, it means it's caused by the fork. I remember several of them having issues with scoreboard packets, this might be another case.

**Comment by NEZNAMY** [comment]
Belowname has nothing to do with the disconnect. Issue creator confirmed it's the scoreboard feature.
