### ISSUE TITLE
Health Update (belowname)

### ISSUE THREAD

**Issue by m4kii420** [NEZNAMY/TAB#823]
### Server version

paper 1.18.2

### TAB version

3.2.5

### Describe the bug

We use armor with custom attributes so players get for example extra +1 HP when they wear it.
So it says 21 HP when player put it on, but doesn't go back to 20 HP when player take it off

### Expected behavior

-

### Steps to reproduce

-

### Additional info

-

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
No steps to reproduce? No configuration? Nothing?

**Comment by m4kii420** [comment]
> No steps to reproduce? No configuration? Nothing?

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  header:
  - ''
  - ''
  - '&#ff6900&lHideOut'
  - '&#f3f3f3ʙ ᴏ x ᴘ ᴠ ᴘ'
  - ''
  - '&#494949&m                                   '
  footer:
  - '&#494949&m                                   '
  - ''
  - ' &#808080Ping: &7%ping%ms &#4d4d4d┃ &#808080Online: &7%essentials_safe_online%
    &#4d4d4d┃ &#808080Network: &7%stafffacilities_bungeetotal% &#4d4d4d┃ &#808080Rank:
    &7%vault_group% '
  - '&#808080Playtime: &7%autorank_total_time_of_player_formatted%'
  - '%animation:hideout-ip%'
  - ''
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,developer,admin,sr.mod,mod,jr.mod,helper,media,elite,legend,hideout+,hideout,champion,master,titan,lord,knight,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
  can-see-friendly-invisibles: false
yellow-number-in-tablist:
  enabled: false
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: true
  number: '%health%'
  text: ❤
  disable-in-worlds:
  - disabledworld
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  scoreboards:
    scoreboard1:
      title: '&#ff6900&lHideOut'
      lines:
      - '     &#f3f3f3%localtime_time%'
      - ''
      - '&#ffad3b%player_name%:'
      - '&#fffc00⛨ &fRank: &#fffc00%vault_group%'
      - '&#00c3ff⚐ &fGang: &#00c3ffsoon'
      - '&#00ff93© &fGems: &#00ff93%gamepoints_balance_formatted%'
      - '&#f32f2d🗡 &fKills: &#f32f2d%statistic_player_kills%'
      - ''
      - '&#ffad3bVote:'
      - '&#8fc3ff⚓ &fVotes: &#8fc3ff%VotingPlugin_alltimetotal%'
      - '&#ffcb8f☻ &fParty: &#ffcb8f%VotingPlugin_VotePartyVotesCurrent%&f/&#ffcb8f%VotingPlugin_VotePartyVotesRequired%'
      - ''
      - '    %animation:hideout-ip%   '
ping-spoof:
  enabled: true
  value: 1
fix-pet-names:
  enabled: false
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &c❌&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 5000
  server:
    '%commandtimer_KOTH_hh:mm:ss_nextExecution%': 1000
    '%health%': 500
  player:
    '%tempfly_time-formatted%': 1000
    '%crazyenvoys_cooldown%': 1000
    '%vault_eco_balance_formatted%': 1000
    '%health%': 500
  relational:
    '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
global-playerlist:
  enabled: false

**Comment by NEZNAMY** [comment]
And this is why you use a website like pastebin. Steps to reproduce were still not provided.

**Comment by m4kii420** [comment]
here
https://pastebin.com/42iBGY8T

**Comment by NEZNAMY** [comment]
That's a standard config. Now steps to reproduce the issue you are describing.

**Comment by m4kii420** [comment]
Huh? I described the issue.
Belowname %health% placeholder doesn't update properly. When you gain +1 HP it says "21 Health" but if you lose that 1 HP its still says "21 Health" until someone hits you or you take any damage. 

In this case, we used armor attributes, you put the helmet on and it gives you extra HP while you are wearing it. Placeholder updates to "21 Health", you put it off and the placeholder doesn't update to "20 Health".

**Comment by NEZNAMY** [comment]
Vanilla helmet doesn't give health. You must be using a plugin for that. This is supposed to be included in steps to reproduce.

**Comment by m4kii420** [comment]
Thats vanilla, you can create that helmet with command block

**Comment by NEZNAMY** [comment]
Will you keep that command a secret or will you share it with me?

**Comment by m4kii420** [comment]
All weapons and armors have attributes, like attack damage, attack speed, armor, armor toughness, knockback_resistance, max_health, etc.
You can also add those attributes to any other items in vanilla but it's much more complicated to do it that way so we use the ItemEdit plugin to do it.

**Comment by NEZNAMY** [comment]
And how was I supposed to know you are using ItemEdit without saying it? Are you sure it's not a bug in the plugin? Either way, I'm waiting for working steps to give myself such helmet.

**Comment by m4kii420** [comment]
https://www.youtube.com/watch?v=zWY9pUhZODQ&ab_channel=Risate (1:20)

`/give @p diamond_sword{Unbreakable:1,AttributeModifiers:[{Slot:"mainhand", AttributeName:"generic.attack_damage", Amount:100000.0, UUID:[I; -1, -1, -1, -1]},{Slot:"mainhand", AttributeName:"generic.movement_speed", Amount:1, UUID:[I; -1, -1, -1, -1]}]} 1`

**Comment by m4kii420** [comment]
Shouldnt be up to that plugin, this plugin just makes your life easier so you don't need to use all this giant commands all the time

**Comment by NEZNAMY** [comment]
Got the sword in my hand, still 10 hearts and %health% says 20.
![image](https://user-images.githubusercontent.com/6338394/219946936-b2256474-be66-41b6-9ced-5d4e70500dd1.png)

**Comment by m4kii420** [comment]
`/give @p diamond_sword{Unbreakable:1,AttributeModifiers:[{Slot:"mainhand", AttributeName:"generic.attack_damage", Amount:100000.0, UUID:[I; -1, -1, -1, -1]},{Slot:"mainhand", AttributeName:"generic.max_health", Amount:1, UUID:[I; -1, -1, -1, -1]}]} 1`

**Comment by m4kii420** [comment]
try this one

**Comment by m4kii420** [comment]
It same for armor, you can choose do you want it to work only when player wear it on head, chest, legs or feet

**Comment by NEZNAMY** [comment]
Looks like this is a Bukkit API bug. I added a console message showing direct output of player's health and this is what I got:
![image](https://user-images.githubusercontent.com/6338394/219947279-0cdb81d7-1369-4f03-8620-c60a658c0629.png)
![image](https://user-images.githubusercontent.com/6338394/219947284-ea7cf5da-21f7-48ab-9aa6-f0c8256f2e44.png)
Additionally, `/papi parse me %player_health%` gives the same result confirming this issue.
