### ISSUE TITLE
Placehoders

### ISSUE THREAD

**Issue by Cabno** [NEZNAMY/TAB#824]
### Server version

1.16

### TAB version

latest

### Stack trace

hi, the plugin's placeholders are not working on my server. I read your wiki page and did what you said, but no results, can you help?

### Steps to reproduce (if known)

-

### Additional info

![image](https://user-images.githubusercontent.com/125756768/219878201-3d4e70ab-fdcd-43e9-9816-f19ed4d28f78.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/219878249-60782245-38d7-4e76-870f-1261be26e132.png)
You didn't fill plugin version correctly. I am also assuming you didn't enable tab's expansion in config or didn't install placeholderapi.
