### ISSUE TITLE
Below name placeholder API

### ISSUE THREAD

**Issue by Studio755** [NEZNAMY/TAB#825]
### Server version

Paper 1.19.3 

### TAB version

3.2.3

### Stack trace

Nothing 

### Steps to reproduce (if known)

Nothing

### Additional info

Hi How would I set up with placeholder api and TAB something like this I know it has something to do with below name in the config
dynamic-lines:
- abovename
- nametag #the original one, combination of tagprefix + customtagname + tagsuffix
- belowname
- another

https://preview.redd.it/3gzc8zxkmeia1.png?width=456&format=png&auto=webp&v=enabled&s=d2f2ce803597bde6ef73a7d3ae98562d6dcbb0a7

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Studio755** [comment]
Currently I have done this 

https://pastebin.com/GGYb24xr

**Comment by NEZNAMY** [comment]
Where is the error?

**Comment by Studio755** [comment]
No it just does not work....
Idk how to set  it up.

**Comment by NEZNAMY** [comment]
This is an issue tracker, not customer support.
