### ISSUE TITLE
Bug, another tab remains when switching between velocity servers.

### ISSUE THREAD

**Issue by Felson999** [NEZNAMY/TAB#826]
### Server version

Pufferfish 1.17.1

### TAB version

3.2.5

### Describe the bug

When you go to the server, where + - big online. Tab remains server lobby. To display the correct server tab, it only helps to reload the plugin (/tab reload)

### Expected behavior

When switching to another server velocity should appear in the tab of exactly the server where you are moving.

### Steps to reproduce

1. You must switch to another proxy server. (velocity)
2. There must be at least 30-50+ players on the other server (somewhere about)

### Additional info

1. After some time, a tab of this server may appear, but not always.
2. I add screenshots, everything is clear on them.
1) https://imgur.com/a/VIJiRTo Lobby server. Everything is fine.
2) https://imgur.com/a/rPalw7Y The same huter, footer and more on a different velocity server.
3) https://imgur.com/a/BugVsZZ If you reload the TAB and you are on this server, then you will see the correct TAB.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Sounds like https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer#additional-note-1---not-resetting-on-server-switch to me.

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=BiMFVVaJlmA). In that screenshot tablist prefixes are missing as well, which suggests the plugin may have failed to load the player. It does make sense, since a bug causing players not to load was fixed in 3.3.0.
For this reason and with user being inactive, I must assume this is the reason and bug was fixed. Reopen if not.
