### ISSUE TITLE
%afk% not working in tab

### ISSUE THREAD

**Issue by BigLemons123** [NEZNAMY/TAB#828]
### Server version

Bungeecord

### TAB version

3.2.4

### Describe the bug

Plugin does not show Afk in tab. I believe this is a bug bc I Have everything set properly to my knowledge and per wiki.
![image](https://user-images.githubusercontent.com/110860672/220245767-86061f95-0cf9-4d80-810c-91d7d82c17b3.png)
![image](https://user-images.githubusercontent.com/110860672/220245826-61f194c0-644a-4e9d-b581-ef569783bd34.png)
![2023-02-20_22 12 39](https://user-images.githubusercontent.com/110860672/220245974-45f81c11-2cc4-4369-81f7-2b47d6a3dff3.png)
![2023-02-20_22 12 25](https://user-images.githubusercontent.com/110860672/220245987-cbfe142e-6ed8-498e-9a51-b7d3eef1d76b.png)

### Expected behavior

Afk is supposed to show in tab

### Steps to reproduce

Group.yml

%afk% as tab_suffix and tag_suffix

Config.yml 

Changed formatting to "&7&oAFK"

Loaded plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/220348152-8444ad3e-6cb4-4c75-a061-93ed4d42769d.png)

https://github.com/NEZNAMY/TAB/wiki/Placeholders#bukkit-only
![image](https://user-images.githubusercontent.com/45695833/220348121-e832b73a-d50c-46de-8ee4-3b41a715c2eb.png)

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/220348414-93f6a1b1-0b18-4407-9b0d-0dedb23b613b.png)
Says bungeecord though.
What's your AFK plugin?

**Comment by Tanguygab** [comment]
> ![image](https://user-images.githubusercontent.com/6338394/220348414-93f6a1b1-0b18-4407-9b0d-0dedb23b613b.png) Says bungeecord though. What's your AFK plugin?

Yeah? %afk% is Bukkit only, so it doesn't work on Bungee right?
