### ISSUE TITLE
Citizens displays on tab for ticks

### ISSUE THREAD

**Issue by pawelkuwa** [NEZNAMY/TAB#830]
### Server version

PaperSpigot 1.18.2 R1

### TAB version

3.2.5

### Describe the bug

When player render citizens on tab citizens are adding for 1/2 ticks and goes hide 

### Expected behavior

Not visible citizens on tab

### Steps to reproduce

Use citizens and use tab plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/220706759-d59c1331-ab07-4a9f-b3e9-31c0d2cbdcd0.png)
![image](https://user-images.githubusercontent.com/6338394/220706777-adb22dcf-f4d1-450d-9854-8307067341d5.png)

![image](https://user-images.githubusercontent.com/6338394/220706792-06cdd22a-3c86-4902-a8be-43f6b3975d20.png)


https://wiki.citizensnpcs.co/Frequently_Asked_Questions#Why_are_NPCs_showing_up_in_the_tablist.3F
