### ISSUE TITLE
Perfomance problem with animations

### ISSUE THREAD

**Issue by kforbro** [NEZNAMY/TAB#831]
### Server version

Purpur 1.19.3

### TAB version

3.3.0

### Describe the bug

Unnecessary animation parsing for each online player when parsing is needed for only one player

### Expected behavior

The placeholder should only be called for one player

### Steps to reproduce

1. animations.yml:
`rainbow:
  change-interval: 50
  texts:
  - "%ac_rainbow_${nick}%"`
2. /tab player One_Player customtabname %animation:rainbow% (perhaps without this command the animation will still be called for everyone)

### Additional info

![image](https://user-images.githubusercontent.com/39985355/220959292-f805df38-3169-430e-bd4d-9dc96fb5ba5a.png)

debug messages, which shows that the placeholder is called for all online players, but it should only be for 1 player:
https://i.imgur.com/DASYhqy.png

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
"%ac_rainbow_${nick}%" sounds like a placeholder that must be parsed for each player separately, not just once.
Animations are parsed for each player, because they might contain player placeholders (and in your case they do). The CPU output shows your custom placeholder is the one taking the CPU, not the animation placeholder (cpu shows raw usage of the placeholder itself, usage of nested placeholders is not included there).

**Comment by kforbro** [comment]
> "%ac_rainbow_${nick}%" sounds like a placeholder that must be parsed for each player separately, not just once. Animations are parsed for each player, because they might contain player placeholders (and in your case they do). The CPU output shows your custom placeholder is the one taking the CPU, not the animation placeholder (cpu shows raw usage of the placeholder itself, usage of nested placeholders is not included there).
Yes, but this placeholder is only in one animation, nowhere else.
The essence of the placeholder is that it makes a rainbow nickname. And, for example, it is installed only for 1 player, but TAB parses it for all the other 99 online players

**Comment by NEZNAMY** [comment]
That's unfortunately the limitation of the current placeholder refreshing system. Tracking placeholder usage on per-player basis would be even more complicated, which I don't think is worth the effort and potential bugs I would accidentally introduce and hear about them for months after fixing.
