### ISSUE TITLE
ItemsAdder text effect

### ISSUE THREAD

**Issue by DarkFort** [NEZNAMY/TAB#834]
### Server version

Purpur 1.19.3

### TAB version

3.2.1

### Describe the bug

Problem is related to the fact that TAB does not see the animation of the ItemsAdder text.
https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+
![image](https://user-images.githubusercontent.com/25278617/221435115-8468faf4-789f-4c91-8547-22c6fb3aeec4.png)

### Expected behavior

Tab should display ItemsAdder animation

### Steps to reproduce

Add text to the TAB configuration, for example <rw HI>

### Additional info

In plugins for chat and LuckPerms animation is visible.
![image](https://user-images.githubusercontent.com/25278617/221435206-0c0fe10e-ac44-4310-a69a-bebc84e87ad8.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#how-can-i-display-itemsadder-images

**Comment by DarkFort** [comment]
> https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#how-can-i-display-itemsadder-images
It doesn't work, it's not a picture, it's text
![image](https://user-images.githubusercontent.com/25278617/221435740-01d6a735-f24b-4531-9c22-fbcccffb5ca0.png)

**Comment by NEZNAMY** [comment]
Same thing, the only way you can use ItemsAdder's placeholders in TAB is to use its placeholderapi placeholders. Check its wiki or use support to find out what the palceholders are.

**Comment by Tanguygab** [comment]
ItemsAdder's text effects are not supported by TAB.
You could however ask ItemsAdder's dev to add a PAPI placeholder that would return text with the specified effect.
