### ISSUE TITLE
Compatibility of glow from CMI and TAB plugin. [Question/Error]

### ISSUE THREAD

**Issue by samparotony228** [NEZNAMY/TAB#835]
### Server version

git-Purpur-1858 (MC: 1.19.2)* latest

### TAB version

3.3.0

### Describe the bug

It seems that I did everything exactly as described in the section "https://github.com/NEZNAMY/TAB/wiki/How-to-make-TAB-compatible-with-glow-plugins' in order to glow from CMI worked and was compatible with the TAB plugin, but it doesn't work for me, when I try to select a glow color from CMI, it immediately turns white, and does not change to the color I chose.

It also creates an 'anti-override' file in which the following message appears: 'Something just tried to add player Samparo into team CMINP2 (expected team: 0SamparoA)'

### Expected behavior

I admit that maybe I did something wrong. (I'm trying to understand this problem) I need help to solve this problem.

### Steps to reproduce

Enter the /glow command from the CMI plugin with the settings I sent in the 'Additional info' section.

### Additional info

In the CMI folder > config.yml, function 'DisableTeamManagement: false'
In the CMI folder > Modules.yml function 'tablist: false'
In the CMI folder > Modules.yml function 'nameplate: false'

And this is how my file looks like from the TAB folder > groups.yml -  https://pastebin.com/aCL4SSMX
And this is how my file looks like from the TAB folder > config.yml - https://pastebin.com/1UFE7rTZ

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of `/tab parse me %cmi_user_glow_code%` when you have a glow color set.

**Comment by samparotony228** [comment]
> Show output of `/tab parse me %cmi_user_glow_code%` when you have a glow color set.

empty string.

**Comment by samparotony228** [comment]
> Then how is it a TAB issue?

Yes, '/papi parse me' gives me an empty string, but when I turn on the glow - my nickname becomes the color that I chose.

**Comment by NEZNAMY** [comment]
Why didn't you do that for tab parse as well?

**Comment by samparotony228** [comment]
> Why didn't you do that for tab parse as well?


Didn't quite understand what you meant?

**Comment by NEZNAMY** [comment]
Turn on your glow and show output of `/tab parse me %cmi_user_glow_code%`

**Comment by samparotony228** [comment]
> Turn on your glow and show output of `/tab parse me %cmi_user_glow_code%`

I turned on the glow for example red, but I glow white. And when I glow and write the command '/papi parse me %cmi_user_glow_code%' - I get an empty string. But the color of my nickname in TAB is changing....

**Comment by NEZNAMY** [comment]
Turn on your glow and show output of `/tab parse me %cmi_user_glow_code%`

**Comment by Tanguygab** [comment]
he asked for /tab parse, not /papi parse, those are two different commands

**Comment by samparotony228** [comment]
> Turn on your glow and show output of `/tab parse me %cmi_user_glow_code%`

Ah, I'm sorry, I was very sleepy yesterday, I didn't notice that you wrote /tab and not /papi. I'm sorry... it was stupid ahaha, I'll check it now and let you know.

**Comment by samparotony228** [comment]
![image](https://user-images.githubusercontent.com/78056389/221733077-31fd0d28-ce15-4670-aabe-595ed0eb7dd7.png)

**Comment by NEZNAMY** [comment]
And you still glow white? Can you show output of `/tab debug <player>`?

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/221829910-8f816002-b92a-4a01-b526-3cd4267f5853.png)
Works fine for me using eGlow.

**Comment by samparotony228** [comment]
> ![image](https://user-images.githubusercontent.com/6338394/221829910-8f816002-b92a-4a01-b526-3cd4267f5853.png) Works fine for me using eGlow.

Yes, it works fine with eglow too. But this function is in CMI, and I would not want to load the server with unnecessary plugins, I need optimization.

**Comment by NEZNAMY** [comment]
If it works with eGlow, are you sure it's a TAB issue? You didn't even answer my previous question. Unfortunately I don't buy plugin that I'm never going to use, so I am unable to test it with CMI.

**Comment by samparotony228** [comment]
> And you still glow white? Can you show output of `/tab debug <player>`?

![image](https://user-images.githubusercontent.com/78056389/221831111-f8bf371a-88c4-4bd3-a670-570936a5590b.png)

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/221831186-5403b956-d7de-4d66-9ee3-d537109b482b.png)
Your user settings override group, and it doesn't have the CMI placeholder.

**Comment by samparotony228** [comment]
Now it works, but if I enter the command /tab player <player> tagprefix <text> - but I glow white again. (And for some reason, the color of the nickname changes to the color that I chose in the glow, can this be fixed somehow?)

**Comment by NEZNAMY** [comment]
This is an issue tracker, not support. We have confirmed this is not a bug, but an issue with your configuration.

**Comment by samparotony228** [comment]
> This is an issue tracker, not support. We have confirmed this is not a bug, but an issue with your configuration.

That is, I can twist it in the settings and this problem will not happen?

**Comment by NEZNAMY** [comment]
Yes, I even told you how.
