### ISSUE TITLE
When wearing body decorations, can not get off the vehicle. 

### ISSUE THREAD

**Issue by madebygood** [NEZNAMY/TAB#837]
### Server version

Purpur 1.19.2

### TAB version

3.3.0

### Describe the bug

I Wearing body cosmetics.

Other players sit over my head with skript, gsit, etc.
image

Then that player can't leave me. can never get off.

And this is a problem with the TAB plugin, the developer said.

### Expected behavior

https://github.com/PluginBugs/Issues-CosmeticsCore/issues/94

### Steps to reproduce

Detailed explanation in the link above

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/221698852-3e1073c8-b549-445e-822a-ae276deec94c.png)
![image](https://user-images.githubusercontent.com/6338394/221698867-f54d3244-8e33-4d5d-b58e-257cd96888ee.png)
How is that latest?

![image](https://user-images.githubusercontent.com/6338394/221698886-639c40d7-148d-42c6-b6a4-c67e53bf8a6a.png)
?

Disable unlimited nametag mode and try again. What is your client version?

**Comment by madebygood** [comment]
my bad.

It is correct that I am using version 3.3.0.

**Comment by NEZNAMY** [comment]
Try uninstalling TAB entirely and try again.

**Comment by NEZNAMY** [comment]
Any news @madebygood ?

**Comment by madebygood** [comment]
> 

its not TAB plugin's problem.

my bad.

thank you for your advice.

close the ticket.
