### ISSUE TITLE
Relation placeholders not loading correctly

### ISSUE THREAD

**Issue by giorgakism1** [NEZNAMY/TAB#84]
**Server version**
Paper 31 - 1.15.1

**Plugin version** ("latest" is not a version)
TAB V2.6.1 safe and for factions, I'm using FactionsUUID 1.6.9.5-U0.5.6-b210 but SavageFactions should have the same problem and PAPI 2.10.4.

**Describe the bug**
For some reason faction relational placeholders from PAPI [%rel_factionsuuid_relation_color%]
need some time in order to work (~10 seconds) when the player gets into view distance from another player the placeholder looks like this:
https://prnt.sc/qhei5z

and after some time if the player doesn't exit from view distance the placeholder starts displaying normally: 
https://prnt.sc/qhejqr

Also when the relation with the player is changed (e.g enemy their faction) it takes the same amount of time in order to change from the default color to the enemy color.
My refresh-interval is set to 3 ticks and this bug only started happening when I updated to 1.15.1 without changing anything on TAB.

**Comment by giorgakism1** [comment]
Dev build v2.6.2-pre6 fixed the issue of the placeholder appearing raw but it still needs a few seconds when changing relations with the other player for the color to change.

**Comment by NEZNAMY** [comment]
relational-placeholders-refresh: 30
Add this into your config and you can make it lower.
