### ISSUE TITLE
the plugins isn't loading 

### ISSUE THREAD

**Issue by RhrPlayz06** [NEZNAMY/TAB#840]
### Server version

spigot 1.19.3

### TAB version

3.3.0

### Stack trace

2023/03/02 09:13:56 [serv  ≡≡  ] java.lang.RuntimeException: Directory 'plugins/TAB v3.3.0.jar' failed to load!
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$2(DirectoryProviderSource.java:32) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:30) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at net.minecraft.server.Main.main(Main.java:114) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at org.bukkit.craftbukkit.Main.main(Main.java:302) ~[paper-1.19.3.jar:git-Paper-431]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ] Caused by: java.util.zip.ZipException: zip file is empty
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
2023/03/02 09:13:56 [serv  ≡≡  ]        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:51) ~[paper-1.19.3.jar:git-Paper-431]

### Additional info

plugins isn't loading 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
"Zip file is empty". You have a corrupted jar file.
