### ISSUE TITLE
Chane The time AM to any time 

### ISSUE THREAD

**Issue by CleanupSeeker61** [NEZNAMY/TAB#846]
### Page link

https://github.com/NEZNAMY/TAB/

### Current text (if applicable)

Wye kann chane the time to geman time 

Lg danny

### New text

Wye kann chane the time to geman time 

Lg danny

**Comment by DrWurzeli** [comment]
https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/resources/config.yml#L175

Support is not provided in GitHub issues.
Buy a license and open a support ticket on the discord.
