### ISSUE TITLE
[Bug]: Name Goes Off Tab

### ISSUE THREAD

**Issue by rbcoder117** [NEZNAMY/TAB#848]
### Server version

Paper 1.19.3

### TAB version

3.3.1

### Describe the bug

Not sure if this is a bug or if I'm asking for support. If its the latter please close the issue and don't even try to answer. If not then the bug is that the name goes behind the other tab slots.

### Expected behavior

It resizes the name to fit in one slot

### Steps to reproduce

1. 1.19.3 Paper Server
2. Use [Config](https://github.com/NEZNAMY/TAB/files/11057521/TAB.zip)
3. Join with a long name or with a long rank
4. It goes off of the tab

### Additional info

https://i.imgur.com/riMt7yP.png

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
that's not something we can fix, it's entirely client size and the only thing you can do is change your GUI scale in your graphic settings
