### ISSUE TITLE
Add bukkit bridge plugin

### ISSUE THREAD

**Issue by NEZNAMY** [NEZNAMY/TAB#85]
To allow PlaceholderAPI and plugin's bukkit placeholders to be displayed on bungeecord.

**Comment by HgeX** [comment]
Is it possible to create an API in this bukkit bridge to allow plugins running on bukkit to change players prefixes and stuff, even when the tab plugin is used as a bungee plugin? Don't know how complicated would be though. :c

**Comment by NEZNAMY** [comment]
Bukkit bridge will only be a bridge for parsing placeholders, it won't do anything else. I will be possible to use a placeholder as prefix and bungeecord plugin using and applying it.

**Comment by HgeX** [comment]
Oh, i see.
