### ISSUE TITLE
MySQL conflict with Tab format

### ISSUE THREAD

**Issue by ItzRonaldMLG** [NEZNAMY/TAB#850]
### Server version

1.19.4

### TAB version

3.3.1

### Describe the bug

When enabling MySQL (tested on Bungeecord) the tab format will not apply and the TAB will just be vanilla with header & footer.

### Expected behavior

Tab format would still work

### Steps to reproduce

Enable MySQL data storage
Start the server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- :D I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Not a bug, you either use MySQL or groups.yml. You can import your groups.yml data into your MySQL database through commands though
https://github.com/NEZNAMY/TAB/wiki/MySQL
