### ISSUE TITLE
nametagedit prefixes don't show up it tab

### ISSUE THREAD

**Issue by Saidas25** [NEZNAMY/TAB#852]
### Server version

Paper 1.19.3

### TAB version

3.3.1

### Describe the bug

when the plugin is installed any prefixes from nametagedit, don't show up it tab, but if i remove TAB plugin the prefixes show up

### Expected behavior

prefixes to work in tab when the TAB plugin is installed

### Steps to reproduce

1. install nametagedit
2. create a group
3. make a prefix
4. make permision for luckyperms
5. put the prefix on your nickname
6. get no prefix with TAB

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
```
tablist-name-formatting:
  enabled: false

scoreboard-teams:
  enabled: false
```
You're welcome, you got free support.

**Comment by Saidas25** [comment]
already tried that, does not work

**Comment by NEZNAMY** [comment]
Did you reload TAB and reconnect?

**Comment by Saidas25** [comment]
> ```
> tablist-name-formatting:
>   enabled: false
> 
> scoreboard-teams:
>   enabled: false
> ```
> 
> You're welcome, you got free support.



> Did you reload TAB and reconnect?

yes, i did

**Comment by Saidas25** [comment]
never mind fixed it

**Comment by NEZNAMY** [comment]
Suddenly out of nowhere it started working? How? So I can tell people in the future.
