### ISSUE TITLE
Layout.yml won't reload

### ISSUE THREAD

**Issue by Tissemyren** [NEZNAMY/TAB#855]
### Server version

Paper 1.8

### TAB version

3.3.1

### Describe the bug

When i use `/tab reload` the config reloads, but not `layouts.yml`. It just stays the same as before. What can i do to fix that?

### Expected behavior

It is supposed to reload `layout.yml`

### Steps to reproduce

I just use `/tab reload`

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Layout reloads just fine for everyone else. Are you sure you are uploading the file correctly to the correct server? People make this mistake way too often.

**Comment by Tissemyren** [comment]
> [Unable to reproduce](https://youtu.be/ZEMPkBfjGeU). Are you sure you are uploading the file correctly to the correct server? People make this mistake way too often.

Yes i am pretty sure, as the config file gets reloaded

**Comment by Tissemyren** [comment]
I was just dumb. It was actually updating, i just made some weird stuff in the fixed-slots so it didn't look like it updated, but it did
