### ISSUE TITLE
Changing font doesn't work

### ISSUE THREAD

**Issue by kalleswe** [NEZNAMY/TAB#857]
### Server version

Paper 1.19.4

### TAB version

3.3.2

### Describe the bug

Trying to change font, like one would expect it to work, in the header/footer but it seems that it is not working like it should.

(font=minecraft:uniform) or [font=minecraft:uniform]. This works properly in other tablist plugins and I though TAB would have implemented that.

Could you fix this issue?

### Expected behavior

Be able to use uniform fonts in the TAB-list.

### Steps to reproduce

Configure text strings with either (font=minecraft:uniform) or [font=minecraft:uniform].

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Bug means the plugin doesn't work as described. Where does the wiki say plugin supports that?
