### ISSUE TITLE
performance improvement proposal

### ISSUE THREAD

**Issue by SonyaADM** [NEZNAMY/TAB#858]
### Server version

1.8.8

### TAB version

latest

### Evidence

A lot of placeholders like luckperms_prefix or skywars_wins from skywars x don't need to be updated every 5 seconds, so I can increase their refresh rate, but when I log into a server where there is a skywars_wins placeholder, due to the increased delay, it uses "dumb" for a while, until the main placeholder will be loaded. why not add a separate option, placeholderapi-refresh-onjoin, which will specify how fast the placeholder will be refreshed after joining the server/world (or the first placeholder request)
it will also improve the plugin's optimization

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
All placeholders are automatically refreshed on join / PAPI ones on server switch. You'll need to provide steps to reproduce.

**Comment by SonyaADM** [comment]
maybe some plugins like skywars x don't immediately load placeholders after entering the server. i set '%skywars_kills%': 8000 and on login it always waits 8 seconds before loading. maybe it makes sense to add a delay for the first TAB request to the PlaceholderAPI? optionally

**Comment by NEZNAMY** [comment]
You can try using /papi parse to confirm your theory, but I don't think that's the case. Is the placeholder used on that server and not any other? If so, how? Some sort of per-server settings? I'll need steps to reproduce.

**Comment by SonyaADM** [comment]
Yes, my theory is correct. it loads about 0.5 seconds after joining, and it "breaks" the functionality of placeholders in tab plugin

**Comment by SonyaADM** [comment]
also marcely's bedwars plugin has a similar problem lol

**Comment by NEZNAMY** [comment]
That would be an issue of the placeholders, compensating for bugs in other plugins is something I am not doing as much as before anymore.

**Comment by SonyaADM** [comment]
adding the ability to delay the placeholder request at login can fix this

**Comment by NEZNAMY** [comment]
Have you confirmed it's an issue of the placeholder using /papi parse? There is one thing that could cause this and not being fault of the plugin, so I want to make sure.

**Comment by SonyaADM** [comment]
Yes. I wrote /papi parse me %skywars_kills% thanks to the spammer when logging in and noticed that the answer is not provided immediately after logging in, but with a slight delay

**Comment by NEZNAMY** [comment]
In that case we can call it a bug in the plugin, which I am not interested to compensate for.
