### ISSUE TITLE
Does not display pastel colors in tagprefix ONLY with built-in nickname

### ISSUE THREAD

**Issue by Timoti11** [NEZNAMY/TAB#859]
### Server version

Purpur 1.19.4

### TAB version

3.3.2

### Describe the bug

When
```
tablist-name-formatting:
  enabled: false
  ```
some colors in tags doesn't work. Bright and noticeable colors are displayed correctly, but pastel colors are replaced with gray. 
When `tablist-name-formatting` is `true` all colors are displayed correctly.
Issue only with built-in nickname, which i can't edit. When i do `tagprefix: '#bda4cc %player_name%'` is displayed correctly, but nickname after %player_name% is gray

screens:
[wuth blue color](https://imgur.com/a/3klNKkH)
[#bda4cc](https://imgur.com/a/BvBKGu2)

### Expected behavior

In both cases pastel colors are displayed correctly.

### Steps to reproduce

Step1: Set `tablist-name-formatting` to `false`
Step2: Set `#bda4cc` to tag-prefix in gropus.yml
Step3: See the gray nick

### Additional info

***groups.yml***
```
_DEFAULT_:
  tabprefix: '#bda4cc'
  tagprefix: '#bda4cc'
```

In TAB colors displayed correctly.

[/btab debug Timoti11](https://pastebin.com/Ga2H2bKC)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#name-tags
