### ISSUE TITLE
ping, hearts 

### ISSUE THREAD

**Issue by GreensaPenguin** [NEZNAMY/TAB#86]
my server is 1.14.4

i'm using 2.5.4 http://prntscr.com/qi4n0w

so i not sure whats going on i have it set to hearts and if i reload the plugin it show the players the hearts but after a little bit of playing and then when i hit tab it goes back to the numbers and gives all players high ping, i even tried setting it to none but same thing happens after a little it goes back to the ping and makes it high http://prntscr.com/qi4ljx http://prntscr.com/qi4lvq

**Comment by NEZNAMY** [comment]
You said it happens when set to none -> another plugin doing it.

**Comment by GreensaPenguin** [comment]
ok thanks for reply i will look in to this

**Comment by NEZNAMY** [comment]
Have you found the cause ?

**Comment by GreensaPenguin** [comment]
omg sorry didnt mean to not reply no i have not found it, i been trying to find the plugin that is doing it. 

all the plugins i got
http://prntscr.com/qs263j
http://prntscr.com/qs269u
http://prntscr.com/qs26ji

**Comment by NEZNAMY** [comment]
Try to delete world/data/scoreboard.dat file.

**Comment by GreensaPenguin** [comment]
ok delete it now going to see if it breaks. sorry i took so long to reply, thanks for replying

**Comment by GreensaPenguin** [comment]
now that i delete that this keeps happening https://pastebin.com/MHTHQVfq 


i delete it on my test server, not main server

**Comment by NEZNAMY** [comment]
Some plugin is doing it then.

**Comment by liscuate** [comment]
Could you try disabling EasyBackup and Head database? See if that fixes it.

**Comment by GreensaPenguin** [comment]
i think it was mcmmo when i turn power level off from going over peoples head it seems to be fine

**Comment by GreensaPenguin** [comment]
nvm it just took longer this time to up http://prntscr.com/qsi1co

**Comment by GreensaPenguin** [comment]
still breaks with Head database & EasyBackup off

**Comment by liscuate** [comment]
What about setting the customplaceholder to `%player_health%`?

**Comment by liscuate** [comment]
And then set the normal one to `CUSTOM`.

**Comment by NEZNAMY** [comment]
He says it happens after uninstalling TAB too, so it's another plugin doing it.

**Comment by liscuate** [comment]
Hm

**Comment by GreensaPenguin** [comment]
i remove move mcmmo and it still has not missed up to day so idk if its mcmmo or its just wanting to work now or its just being slow at breaking

**Comment by GreensaPenguin** [comment]
with mcmmo removed from the server it seems to be working fine

i'm using mcMMO Classic atm but with it off the tab seems to be fine but was thinking of getting the new 1 idk if that world break it 

New 1 https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/
i have atm https://www.spigotmc.org/resources/official-mcmmo-classic.2445/
