### ISSUE TITLE
[ERROR]: Packet encoding of packet ID 78 threw (skippable? false) randomly kick players - Randomly kick players in radius

### ISSUE THREAD

**Issue by Timoti11** [NEZNAMY/TAB#860]
### Server version

Purpur 1.19.4

### TAB version

3.3.2 (tab-bridge 2.0.12)

### Describe the bug

Randomly when somebody open/drop/break a shulker server kicks all players near the 'zone' and spam to console mentioning tab-brifge

### Expected behavior

Players don't kick

### Steps to reproduce

Step1. Install last build 1.19.4
Step2. Randomly when somebody open/drop/break a shulker server kicks all players near the 'zone'
Step3. [See errors in console](https://pastebin.com/txUe01aw) (some error with at me.neznamy.tab.bridge.*)

### Additional info

**TAB**
 ```
 unlimited-nametag-mode:
    enabled: false
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
[Out of scope, TAB doesn't ](https://github.com/NEZNAMY/TAB/issues/844)
