### ISSUE TITLE
TAB 3.3.2 - User get kicked by Paper because of packet limiter

### ISSUE THREAD

**Issue by nhanledev** [NEZNAMY/TAB#862]
### Server version

Paper 1.17.1

### TAB version

3.3.2

### Describe the bug

The bug happens if two proxies are connected to the same Redis server using RedisBungee, and only happen on TAB v3.3.2

If one proxy has player online, all connections to other proxy will be kicked by Paper because of its packet spamming protection / limiter with message in `paper.yml` `packet-limiter.kick-message`

### Expected behavior

Player should be able to join any proxy normally, and it not kicked by packet spamming.

### Steps to reproduce

1. Run two waterfall proxies on different ports
2. Install RedisBungee and connect two above proxies
3. Change `register-tab-expansion` to `true`
4. Reload and use two accounts to join. You can join the first server, but the second one will kick you out by Paper

### Additional info

The backend servers behind the proxies are only two blank 1.17.1 paper servers, which are used as AUTH servers only.
This bug does not happen on tab v3.3.1

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by nhanledev** [comment]
This error is thrown on proxy when the issue happens https://github.com/NEZNAMY/TAB/issues/861

**Comment by NEZNAMY** [comment]
The only way to keep information in expansion up to date is to send plugin message each time a value changes. Nothing can be done about that. Disable tab expansion if you don't need / want it to work.

**Comment by nhanledev** [comment]
This is fixed in https://github.com/NEZNAMY/TAB/commit/c211724d132d2d166ad52627222f94582d4b3617 which caused by something with Redis. TYSM <3
