### ISSUE TITLE
condition:nick not registering properly ONLY on playerlist

### ISSUE THREAD

**Issue by ubdeadhaha** [NEZNAMY/TAB#863]
### Server version

Paper 1.19.3 #448

### TAB version

3.2.2

### Describe the bug

I've configured my scoreboard and playerlist to use a condition for Essentials nicknames. I have a prefixed symbol to show players who is using a nickname. This prefix does not show in the playerlist, though the nickname shows fine. This condition works as intended on my scoreboard and my header. Here's an example of my config:

conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: '◦%essentials_nickname%'

### Expected behavior

Properly portray conditions on the tablist

### Steps to reproduce

1. apply my config 
2. profit

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show where are you using the condition.

**Comment by ubdeadhaha** [comment]
header:
  - <#FFFFFF>&m                                                </#17ff55>
  - '%animation:chunky%'
  - ''
  - '&e✦ %animation:Welcome%&f &l%condition:nick%&7&l! &e✦'

scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - PERMISSIONS:group.owner,group.admin
  - PLACEHOLDER_A_TO_Z:%condition:nick%

scoreboards:
    adminworld:
      display-condition: permission:tab.scoreboard.survivalworldadmin
      title: '&f&7⋆&r&a&lᴄʜᴜɴᴋʏ&r&e✦&fᴍᴏɴᴋᴇʏ&7⋆'
      lines:
      - ' '
      - '&7ʜɪ &e&l%condition:nick%&f&7!'

**Comment by NEZNAMY** [comment]
And this is why you use a paste website or use ```, since now I can't even copypaste that into my config. What is it displaying instead?

**Comment by NEZNAMY** [comment]
And groups.yml? Since you said it doesn't work there.

**Comment by ubdeadhaha** [comment]
Hey was just trying to report what I thought was a bug cheer up

**Comment by NEZNAMY** [comment]
Can you send groups.yml?

**Comment by ubdeadhaha** [comment]
I've since changed The essentials_nickname placeholder to condition:nick and it works. Wasn't trying to get support as I haven't bought the plugin was truly just trying to help. Thanks for the pointers though
