### ISSUE TITLE
Customtagname

### ISSUE THREAD

**Issue by kokqi** [NEZNAMY/TAB#864]
### Server version

Paper 1.19.4

### TAB version

3.3.2

### Describe the bug

customtagname doesn't sync in my point of view unless I use tagprefix/suffix:
https://streamable.com/bw8ucc

### Expected behavior

.

### Steps to reproduce

.

### Additional info

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Steps to reproduce are a required field, why did you ignore it? According to the video, nametag line doesn't update for everyone? Is that it?

**Comment by NEZNAMY** [comment]
Yes, you cannot see your own customtagname. Is that it?

**Comment by NEZNAMY** [comment]
Perfect, not a bug then.
