### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Nicolol1234** [NEZNAMY/TAB#866]
### Server version

CardBoard 1.19.2

### TAB version

3.3.2

### Stack trace

[11:50:59] [Server thread/INFO]: Enabling TAB v3.3.2
[11:50:59] [Server thread/INFO]: [TAB] Server version: 1.19.2 (v1_18_R1)
[11:50:59] [Server thread/INFO]: §c[TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report this issue (include your server version & fork too)
[11:50:59] [Server thread/INFO]: Disabling TAB v3.3.2

Nothing else (realy, that's all I have)

### Additional info

Fabric 1.19.2 with cardboard installed

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Nicolol1234** [comment]
CardBoard isn't on compatibility page, so idk if i can post

**Comment by NEZNAMY** [comment]
Isn't cardboard the fabric mod allowing bukkit plugins?

**Comment by bsndmd** [comment]
> Isn't cardboard the fabric mod allowing bukkit plugins?

it allows you to use bukkit, spigot, and paper plugins

**Comment by NEZNAMY** [comment]
Only those that use the bukkit API. TAB uses a lot of NMS due to lack of API, and that plugin doesn't remap server jar to bukkit format. I tried to add support for it in the past, but cardboard had massive issues at that time. Either way, next plugin version will include native fabric support.
