### ISSUE TITLE
LuckPerms/ItemsAdder rank prefix error

### ISSUE THREAD

**Issue by CinemaMC** [NEZNAMY/TAB#867]
### Server version

1.19,3 Paper

### TAB version

3.3.2

### Stack trace

I have the tab goups.yml setup like this
![image](https://user-images.githubusercontent.com/36867172/230700822-e1d72891-bf63-4dad-baec-ae12f9dbd40d.png)

However, in-game, it shows up like this 
![image](https://user-images.githubusercontent.com/36867172/230700842-e8dd95b0-f0ab-492f-96ab-8daf7e7c16ad.png)

The :mod: image prefix isn't being shown. This is also going for other ranks when I add the user to multiple groups in LuckPerms

### Additional info

I have the tab goups.yml setup like this
![image](https://user-images.githubusercontent.com/36867172/230700822-e1d72891-bf63-4dad-baec-ae12f9dbd40d.png)

However, in-game, it shows up like this 
![image](https://user-images.githubusercontent.com/36867172/230700842-e8dd95b0-f0ab-492f-96ab-8daf7e7c16ad.png)

The :mod: image prefix isn't being shown. This is also going for other ranks when I add the user to multiple groups in LuckPerms

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
FAQ on wiki

**Comment by Tanguygab** [comment]
> This is also going for other ranks when I add the user to multiple groups in LuckPerms
You probably didn't set weights correctly, check https://github.com/NEZNAMY/TAB/wiki/How-to-setup-weights-priorities
