### ISSUE TITLE
Scoreboard Bug

### ISSUE THREAD

**Issue by magef1x** [NEZNAMY/TAB#868]
### Server version

Paper 1.19.4

### TAB version

3.3.2

### Describe the bug

Hi! Scoreboard is broken on lower versions (tested only 1.8)

1.19.4 Scoreboard

![image](https://user-images.githubusercontent.com/114337601/230776857-d6ee8ee2-40ef-4c44-b036-af93ab486260.png)

1.8 Scoreboard

![image](https://user-images.githubusercontent.com/114337601/230776870-ed0a0238-2d4e-45ed-b7d1-45dbe0454bad.png)

### Expected behavior

https://mclo.gs/uC9nepm

### Steps to reproduce

Step 1. Use my configuration
Step 2. Join with 1.8 
Step 3. Check scoreboard

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations#scoreboard
