### ISSUE TITLE
Unlimited NameTag Marker Tag

### ISSUE THREAD

**Issue by PanHaskins** [NEZNAMY/TAB#869]
### Server version

Paper 1.18.2 (build 388)

### TAB version

3.3.2

### Describe the bug

Since you removed the option from config.yml "use-marker-tag-for-1-8-x-clients" which defaults to "true" from now on, players with version 1.8 have a nametag a kilometer away from the player. Players with 1.8.9 see it just fine.

![image](https://user-images.githubusercontent.com/58113388/230788241-9b57b492-ea2d-43c0-9667-f874d782079d.png)

### Expected behavior

Nametag should behave as in 1.8.9+ just a bit above the player's head

### Steps to reproduce

1. Add on 1.18.2 server this plugins: ViaVersion, ViaBackwards, ViaRewind (with default configs), TABS, Luckperms
2.  Set unlimited-nametag-mode to true
3.  Add below name to the player (I have belowname at group) 

my groups.yml:

_DEFAULT_:
  tabprefix: ""
  tagprefix: ""
  customtabname: "%player%"
  customtagname: "%player%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: ""
  tagsuffix: ""
  belowname: "&c☠ &f%d_your_death%"
  
4. Start 2 clients (1. at 1.18.2 version or other version, 2. at 1.8) and join to the server
5. Look at the player :)

### Additional info

I probably don't have any additional information. If you can't reproduce it just reply.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
that's expected, just update to at least 1.8.1, there's no reason to not use 1.8.9 anyways

**Comment by PanHaskins** [comment]
But the plugin includes compatibility of this version.
And some still play on 1.8 instead of 1.8.9 for example.

**Comment by Tanguygab** [comment]
there's no way to distinguish 1.8.0 from other 1.8.X versions, so this can't be fixed

**Comment by NEZNAMY** [comment]
There is no reason not to use at least 1.8.9. Tell your players to update their killaura.
