### ISSUE TITLE
I ticked all of the boxes without actually reading them

### ISSUE THREAD

**Issue by Tanguygab** [NEZNAMY/TAB#870]

**Comment by Tanguygab** [comment]
wtf did I just do

**Comment by tomkeuper** [comment]
You should probably rename this issue as its perm linked to all checkboxes containing "I ticked all of the boxes without actually reading them"

**Comment by Tanguygab** [comment]
I think it's just linked to issue #869 so shouldn't be a big problem

**Comment by tomkeuper** [comment]
Oh lol, I clicked on that issue and saw it was linked. I thought that the original issue was older but I was mistaken
