### ISSUE TITLE
Scoreboard toggle from console

### ISSUE THREAD

**Issue by ItzRonaldMLG** [NEZNAMY/TAB#872]
### Server version

1.19.4

### TAB version

3.3.2

### Stack trace

This command must be ran from the game

### Additional info

Im creating an easy access gui for players on the server.
Since i got TAB running on bungeecord i cant toggle scoreboard from out the sub servers.
Could this be added to the Bridge?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- ;) I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
This isn't an error/bug, and feature requests are currently closed.
Moreover, I believe that NEZ already said no to that feature

**Comment by NEZNAMY** [comment]
Use a plugin like CommandSync (but updated).

**Comment by ItzRonaldMLG** [comment]
I tried to use CommandSync and bungeecommand and multiple more.
All plugins i tried have a problem with executing the commands from TAB plugin.
Latest i tried: https://www.spigotmc.org/resources/commandsync-reborn.63194/
even this one: https://www.spigotmc.org/resources/bungeecommand.89275/

When executing those commands it doesnt output/activate the TAB command.
When trying on other bungeecord plugins it does work like BungeeOnlineTime & BungeeTextCommands.
But on TAB plugin it doesnt seem to work for some reason...
Does this have to do with the registering of commmands because even the main /btab doesnt execute.

**Comment by NEZNAMY** [comment]
TAB is registering commands on bungeecord normally. Maybe try without `/`? `btab scoreboard toggle [player]` must work.

**Comment by ItzRonaldMLG** [comment]
I know its without the /, but for some reason it didnt work before.
And for some reason it does work now... Strange thing to put hours in trying different things, but its solved now.
