### ISSUE TITLE
problem with abovename and placeholderapi

### ISSUE THREAD

**Issue by shoutzz011** [NEZNAMY/TAB#873]
### Server version

Waterfall-1.19-520/paper-1.8-445

### TAB version

TAB-3.3.2/TAB-BRIDGE-2.0.12

### Stack trace

[19:55:57] [Craft Scheduler Thread - 264/WARN]: [PlaceholderAPI] [math] Invalid Placeholder detected!
[19:55:57] [Craft Scheduler Thread - 264/WARN]: [PlaceholderAPI] [math] Placeholder: %math_{bw1058plus_player_kills}+{bw1058plus_player_kills_final}%
[19:55:57] [Craft Scheduler Thread - 264/WARN]: [PlaceholderAPI] [math] Cause: '{bw1058plus' is not a valid number for precision!

### Steps to reproduce (if known)

It's not really an error, actually the "error" isn't very well caused by the TAB, but I think it's maybe a little bit responsible for that. I use "unlimited-nametag-mode:" and leave the following in ``groups.yml`` on the bw1058 game servers:
![image](https://user-images.githubusercontent.com/120399502/232230792-7447def9-eac3-493d-bd66-ae6686b9493b.png)

conditional:
![image](https://user-images.githubusercontent.com/120399502/232230816-f0114afe-5f2f-4271-b260-9c4bf0314d66.png)

I preferred to use conditionals for this because I want the ``"abovename"`` to be shown only when the game starts.
But what is actually happening is that these placeholders are being counted on all other servers (limbo, lobby, survival, rankup) that don't have bw1058, and the more players, the more the placeholderAPI error is shown, making a good spam big sometimes. and that's why I think the cause of this is the TAB. yes I already disabled this function for the servers but even so it continues to be shown (not the abovename, the placeholderAPI error)

### Additional info

The problem is not a TAB error, but the placeholderAPI, but the possible cause for this is the ``"unlimited-nametag-mode:"`` function that is counting for all servers (even being disabled on these servers).

PlaceholderAPI "error" disappears completely when starting a match. But while it is not started or is on another server the error continues, which should not happen

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
The error message says you are supposed to define precision, which you didn't. This doesn't look like a TAB bug.

**Comment by shoutzz011** [comment]
> The error message says you are supposed to define precision, which you didn't. This doesn't look like a TAB bug.

It doesn't really look like a TAB error, but what happens is this is being shown on every server on my network, including those that don't have bw1058

**Comment by NEZNAMY** [comment]
Then yeah it makes sense, TAB doesn't track which placeholders are used on which server, just list of used placeholders, which are then forwarded to bridge.

**Comment by shoutzz011** [comment]
> Then yeah it makes sense, TAB doesn't track which placeholders are used on which server, just list of used placeholders, which are then forwarded to bridge.

I understand. Is there any way around/resolving this? It is generating significantly high spam from players. And I honestly wouldn't want to use another plugin for that...

I was thinking here, instead of having ``"disable-in-servers/worlds:"``, maybe it could be ``"enabled-in-servers/worlds:"`` in some functions, like this instead of being sent for everyone, it would only be sent to those who were selected, but I think this would be "costly" (I don't speak English and I don't know what I should call it) for development, and consequently could cause some problems for others who use the TAB. That's your decision

**Comment by NEZNAMY** [comment]
Tracking used placeholders per server would be more complicated to do and could result in more bugs being added in for everyone. Ideal solution would be to disable warns in math expansion (or modifying the code if not configurable).

**Comment by shoutzz011** [comment]
I understand. Sorry to open a "problem" like that this way, but thanks.
I think this can be closed
