### ISSUE TITLE
SupremeTags

### ISSUE THREAD

**Issue by Kijler** [NEZNAMY/TAB#874]
### Server version

1.19.3

### TAB version

3.2.1

### Evidence

I would need the tag to be visible in the tab, I use supremetags, but they are not visible in the tab, can you advise?

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [X] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
Use PlaceholderAPI and use the placeholders in groups.yml

**Comment by NEZNAMY** [comment]
Support is not provided in github issues, see readme for more info.
