### ISSUE TITLE
Can I apply the display-condition to tab?

### ISSUE THREAD

**Issue by f1xc0d3** [NEZNAMY/TAB#875]
I want to make it so that a different tab is shown to a person if he has certain permission. It's possible? How?

**Comment by NEZNAMY** [comment]
No, only per-world/per-server/per-group/per-user are supported directly. You can use conditions for text by creating a condition with the whole text inside and using it in header/footer directly.

**Comment by NEZNAMY** [comment]
I just told you how. Permission based tablist will not be added.
