### ISSUE TITLE
Negative "~" ranges do not work

### ISSUE THREAD

**Issue by 13377Sined1337** [NEZNAMY/TAB#878]
### Server version

spigot 1.19.4

### TAB version

3.3.2

### Describe the bug

  register-tab-expansion: true
placeholder-output-replacements:
  "%rs_temperature_int%":
    "0~100": "%img_freezing%"
    "1-15": "%img_12%"
    "16-23": "%img_14%"
    "24-31": "%img_15%"
    "32-38": "%img_16%"
    "39-46": "%img_17%"
    "47-54": "%img_18%"
    "55-69": "%img_19%"
    "70-500": "%img_burning%"
    
    With positive numbers it works, everything is replaced, but as soon as I need to output negative numbers, there is no effect 

### Expected behavior

Negative variables must work

### Steps to reproduce

placeholder-output-replacements:
  "%rs_temperature_int%":
    "0~100": "%img_freezing%"

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Assuming the output is negative, use "-100~0".

**Comment by 13377Sined1337** [comment]
Excuse me for my idiocy, you are the best plugin developer for meinkraft servers
You have made an incredible contribution to the development of servers 
Thank you more, I wish you luck in life
