### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by BystricTV** [NEZNAMY/TAB#882]
### Server version

1.8.8

### TAB version

3.3.2

### Describe the bug

It's not really a bug but I wanted to ask how do I make the animation pass on the name in the tab as well

### Expected behavior

I would like the animation to pass on the name as well

### Steps to reproduce

I don't know in fact I'm asking for support

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Animations
