### ISSUE TITLE
Nametags bug

### ISSUE THREAD

**Issue by luucay** [NEZNAMY/TAB#883]
### Server version

PaperSpigot 1.8.8

### TAB version

3.2.2

### Describe the bug

Some players' nametags appear high above their heads, flying aimlessly.

### Expected behavior

[errors.log](https://github.com/NEZNAMY/TAB/files/11369503/errors.log)
[config.log](https://github.com/NEZNAMY/TAB/files/11369514/config.log)

### Steps to reproduce

Idk, it just appeared out of nowhere when updating the plugin.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by luucay** [comment]
![image](https://user-images.githubusercontent.com/70462104/235576008-5027ed24-e50f-4215-8bfc-c25941374f7a.png)

**Comment by Tanguygab** [comment]
don't use 1.8.0, update to at least 1.8.1.
There's no reason to not use 1.8.9 anyways
