### ISSUE TITLE
Can not set collisions per world

### ISSUE THREAD

**Issue by Damianquq** [NEZNAMY/TAB#885]
### Server version

1.19.4 Paper Build 524

### TAB version

3.3.2

### Describe the bug

Can not set enable-collision option per world

### Expected behavior

Change player colission in specific world

### Steps to reproduce

Set enable-collision per world
Reload plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
That's not a bug and feature requests are closed
