### ISSUE TITLE
Placeholder issue after skinblob change

### ISSUE THREAD

**Issue by Lorias-Jak** [NEZNAMY/TAB#886]
### Server version

Velocity 3.2.0-252

### TAB version

4.0.0

### Describe the bug

We have built a script with Denizen that allows players to save skins and change them live. We grab the prefix and suffix placeholders from LuckPerms via the TAB bridge from the servers, so that TAB 4.0.0 also has them on the Velocity proxy. 

Normally the ranks are all written in bold, but when I change the skin via the skinblob, all of a sudden the rank is no longer written in italics. 

I know what was actually said about velocity. But I have also seen the changelogs that there was not exactly little time invested there. I just wanted to report it in case it might be relevant after all. If no bugreports about velocity are wanted please let me know and I will let it be

Bevore skin change
![grafik](https://user-images.githubusercontent.com/62625225/236265217-558cf634-0c6e-49a4-b1d6-27df53ab1e69.png)

After skin change
![grafik](https://user-images.githubusercontent.com/62625225/236265402-73021ff3-933e-4a9a-b460-2639029972de.png)

### Expected behavior

The prefix of the rank should remain in bold letters

### Steps to reproduce

Step 1: Have LuckPerms, the LuckPerms addon from Papi-ecloud installed, use TAB on Velocity Proxy and have the latest version of TAB-Bridge on your Supservers, as well as Denizen on your Server

Step 2: use the Following Group configs for your test-group
 - tabprefix: '&8[&l%luckperms_prefix%&8] &7'
 - tagprefix: '&8[%luckperms_suffix%&8] &7'

Step 3: Give your group in LuckPerms the following Permissions
- prefix.5.§4§lAdmin
- suffix.5.§4Admin

Step 4: Check if the Group Prefix is shown in the TAB bar at your Player. The "Admin" should be bold

Step 5: execute the following denizen command as ingame player
- /ex adjust <player> skin_blob:<player.skin_blob>

Now in your tab your rank should lose it's boldness. If you now use /vtab reload it changes back to the bold one

### Additional info

- Subservers running Paper - 1.19.4-524
- Newest Denizen version - 1.2.5-b1791
- Latest DEV-Build of TAB available on Actions
- Latest version of TAB-Bridge on BBB
- Latest version of PAPI - 2.11.3

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
I tried running Denizen and executed the same command but got this error
![image](https://user-images.githubusercontent.com/45695833/236283048-3b8064af-83a9-45a9-b86c-7356632069fc.png)

**Comment by NEZNAMY** [comment]
Skin change removes the player from tablist and adds back with new skin. The add action probably has display name set to `null`, which makes tablist use player's name and team prefix/suffix. 

Unlike on Bukkit and BungeeCord, packet detection is not available on Velocity, which makes it impossible for TAB to detect this and apply display name to the packet / send an update packet after.

[Compatibility page](https://github.com/NEZNAMY/TAB/wiki/Compatibility#supported-features-per-platform) shows "❗" at tablist names for Velocity, which may result in issues such as this one.

Possible solutions could be:
* Periodically force-update tablist entries (I don't like this solution, as it's a waste of resources and would only be needed on Velocity)
* Add packet detection (Velocity has no API for this and I have no interest in doing this, as using internals means the code may break any time in the future and in the worst case scenario cause a protocol error and we will repeat what happened years ago)
* Option 1, but config side. The easiest invisible solution would be to make a custom animation consisting of 2 frames, both being random different color codes and put the text at the end of tabsuffix. Users will see no animations, but plugin will periodically update tablist formatting with a chosen period.

Here I conclude that the plugin works as described. I don't think this can ever be properly "fixed", but I am open to serious suggestions if anyone has an idea.
