### ISSUE TITLE
Broken centering of Cyrillic in the footer on 1.8

### ISSUE THREAD

**Issue by SonyaADM** [NEZNAMY/TAB#888]
### Server version

1.8.8

### TAB version

3.2.2

### Describe the bug

In the new version of TAB, the centering of the Cyrillic alphabet in the footer is broken
It is also shown from above how it is displayed in the header, and there are no such problems there

### Expected behavior

Correct centering, as in the header

### Steps to reproduce

config:
 
 per-world:
    world:
      header:
      - 'раз раз'
      - ''
      - 'два два'
      - 'Не сломанное сообщение'
      - '&7&m&l--------------------------'
      - ''
      footer:
      - ''
      - '&7&m&l--------------------------'
      - '&fсломанное сообщение сверху'
      - ''
      - '&7&l%animation:messages123%'

Animations:
messages123:
  change-interval: 4500
  texts:
  - '&eСломанное сообщение по центру'

### Additional info

https://ibb.co/CKLkjxG
https://ibb.co/jVwwr8K
https://ibb.co/CQNZxSh

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
Centering is done by the client, there's nothing TAB can do about it

**Comment by SonyaADM** [comment]
no matter how funny it sounds, but if the server is 1.17 + viabackwards, there is no such problem. It appeared in one of the latest updates, namely 1.8.8. I just started vanilla minecraft and the problem is still there

**Comment by Tanguygab** [comment]
I'm unsure of what could possibly be wrong, maybe it's a Via issue? can you try without the Via plugins?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Known-issues#15x---112x---unwanted-space
You didn't add &r after the bold line.
