### ISSUE TITLE
TAB & PremiumVanish Bungee Issue

### ISSUE THREAD

**Issue by damo1995** [NEZNAMY/TAB#89]
**Server version**
Paper-33(1.15.1) & Waterfall-Bootstrap:1.15-SNAPSHOT:d505b21:311

**Plugin version** ("latest" is not a version)
TAB: 2.6.2
PremiumVanish: 2.5.3

**Describe the bug**
When using 'global-playerlist: true' in config.yml when a user vanish's the user still shows on the tab list until one of the below events occur:

- Another player leaves/joins
- User Re-logs

**How to reproduce**
- Set global-playerlist: true in config.yml
- Ensure PremiumVanish is installed on both Bungee & Upstream Servers and configured to use a Database.
- Log two accounts into the same or different upstream servers
- Vanish one of the accounts
- Check Tab List and see the user still present.

**Expected behavior**
- User should be removed from the tab list if in a vanished state.

**Actual behavior**
- User stays present on the TAB list when in a vanished state

**Additional info** (errors, screenshots, ...)
![image](https://user-images.githubusercontent.com/797051/71752679-deabac00-2e77-11ea-8fbd-1c789e00d157.png)

**Comment by NEZNAMY** [comment]
Are you able to join discord to try a debug build ? I don't own the plugin so i can't really test it.
