### ISSUE TITLE
My TAB doesn't work with unlimited-name tag-mode.

### ISSUE THREAD

**Issue by chunjoonseo541** [NEZNAMY/TAB#895]
### Server version

Plazma1.19.4 (https://github.com/PlazmaMC/Plazma)

### TAB version

3.3.2

### Describe the bug

I implement displaying Nickname on Tag with a plugin called CMI. But it doesn't work. I turned on unlimited-nametag-mode, and I turned on scoreboard-teams, but it doesn't work. Save variables as MySQL. I tried using bungeecord, and I tried using bukkit, but it didn't work. Somebody help me! (Used PlaceholderAPI)

Edit:I used Papago translator because I am not good at English. Please understand even if the sentence is weird.

### Expected behavior

![image](https://github.com/NEZNAMY/TAB/assets/79959917/7d532de6-de35-4ce6-8769-e03b68a92784)
![image](https://github.com/NEZNAMY/TAB/assets/79959917/ea3a0f08-c9f5-4acc-ac54-4cecdca28cff)

### Steps to reproduce

Step 1: Enable unlimited nametag mode
Step 2: Sharing CMI NIckname

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
show a screenshot of your game

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Unlimited-nametag-mode#additional-note-2---f5-view

**Comment by chunjoonseo541** [comment]
I'll trying
