### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Xitryne** [NEZNAMY/TAB#897]
### Server version

Waterfall 1.17.1

### TAB version

3.3.2

### Stack trace

Hello, when I try this command /tab mysql upload in my console it says command not found, but before it worked fine

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Commands-&-Permissions
