### ISSUE TITLE
Pet names disappear when the owner is nearby

### ISSUE THREAD

**Issue by radiant-ai** [NEZNAMY/TAB#898]
### Server version

Current: git-Purpur-1976 (MC: 1.19.4)*

### TAB version

3.3.2

### Describe the bug

Pet names are visible only when pet owner is not nearby. Sometimes pet name is not visible to its owner as well.

### Expected behavior

Pet names should always be visible to everyone.

### Steps to reproduce

1. Spawn a wolf, tame it and put a nametag on it with some text on it
2. Ask other play to check the name (also try to disconnect both players so the bug will 100% reproduce).
3. Other player cannot see the name of the wolf (owner possibly will never see the name if disconnected once)
4. Disconnect or fly away
5. The other player now can see the name.

### Additional info

I tried to turn on-off the overrides and tried to switch pet name fix. Did not help. No other plugins were installed during the test.

Config:
https://pastes.dev/X9dG9lbbTm

Video:
https://github.com/NEZNAMY/TAB/assets/43506080/d6890f98-56fa-4267-b409-b3272fd22014

Thank you for the best existing TAB plugin!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
disable petfix and try this plugin https://github.com/Tanguygab/PetNameFix/releases/tag/1.0.0

**Comment by NEZNAMY** [comment]
1.19.4 added something that has to be compensated for, which is already fixed in the mentioned plugin ([here's a spigot link if you prefer those](https://www.spigotmc.org/resources/109466/)). The feature will be removed from the main plugin in version 4.0.0, so I will not be fixing this in the main plugin.
