### ISSUE TITLE
Pets Names

### ISSUE THREAD

**Issue by MrApocalyptic** [NEZNAMY/TAB#9]
Server version - 1.14.4

Plugin version - 2.5.0

Describe the bug - Pretty much when I upgraded to tab v2.5.0 pet nametags have the prefix of the owner, but i tested it with version tab v2.4.15 and it removed the prefix. I also have fixed pet names set as true in advancedconfig.

Additional info
Version 2.5.0 - http://prntscr.com/opxxi2
Version 2.4.15 - http://prntscr.com/opxzqx

**Comment by NEZNAMY** [comment]
Thanks for the report, fixed, new jar can be found on discord.
