### ISSUE TITLE
Logging in vanished with "SuperVanish" plugin doesn't hide name in tab.

### ISSUE THREAD

**Issue by Voiddar** [NEZNAMY/TAB#90]
**Server version**
1.13.2

**Plugin version** ("latest" is not a version)
2.6.2

**Describe the bug**
Recently I updated tab and noticed that using vanish on the "SuperVanish" plugin I use on my server now also hides the name in tab's player list.
However, some days later I joined my server vanished and some players started noticing me, so I joined in an alt to see what was going on. My name was showing in TAB even when I was vanished. In my main account I did /vanish twice to "Reload" the vanish and my name dissapeared as usual.

TLDR: vanishing while in game hides the name in tab, but joining vanished doesn't.

**How to reproduce**
1- Have TAB, EssentialsX and SuperVanish Installed.
2- (Super Vanish has "Remember old vanish state" on as default iirc, so this step is just to check that is on)
3- Enable EssentialsX options to join vanished (silent-join/silent-quit)
4- Join your server once and vanish. Then quit. This should save your state as a vanished player.
5- Join the server once again. You should still be getting the "You're invisible to other players" action bar message and other players shouldn't be able to see you/drop items to you and stuff, but your name should appear in tab.

**Expected behavior**
Joining the server vanished hides your name tag in TAB instantly

**Actual behavior**
Joining the server while vanished shows your tag in TAB until you "refresh" the vanish by using it twice.

**Additional info** (errors, screenshots, ...)

**Comment by NEZNAMY** [comment]
Can you try without TAB ?

**Comment by Voiddar** [comment]
Just did it. It wasn't an issue with TAB afterall. It seems it's an issue with vanish plugins in general (Tried Essentials and SuperVanish standalone). Sorry!

**Comment by Sikatsu** [comment]
This is the exact issue I have but then with PremiumVanish. Joining in vanish the plugin doesn't actually see/recognize you are in vanish.

So how did you solve it then?

**Comment by iTaeyeonKim** [comment]
> 
> 
> This is the exact issue I have but then with PremiumVanish. Joining in vanish the plugin doesn't actually see/recognize you are in vanish and basically reveal you on the tablist.
> 
> So how did you solve it then?


Sorry for bump, my issue was "SkinsRestorer" plugin.
