### ISSUE TITLE
PlayerLoadEvent doesn't work

### ISSUE THREAD

**Issue by ItsBlade** [NEZNAMY/TAB#901]
### Server version

Paper-1.19.4-538

### TAB version

3.3.2

### Describe the bug

So in the IDE (IntelliJ Idea) I get this warning

![image](https://github.com/NEZNAMY/TAB/assets/3113648/6b29d8ae-1289-4745-86a0-33cb2b4ac309)

and after compiling and launching the server I receive this warning in the console (don't mind the plugin name)

![image](https://github.com/NEZNAMY/TAB/assets/3113648/479bdd6c-58fd-48a1-b4d0-fa9a0fbf7092)

### Expected behavior

For it to work

### Steps to reproduce

Step 1: add PlayerLoadEvent to your listener class
Step 2: compile and launch the server

### Additional info

I spent like well over 5 hours trying to figure out how to use ProtocolLib's packets to change the display names of users based on their PVP setting but I gave up and decided to use another plugin that can already do it because the docs aren't very informative and any other method I've tried online is either deprecated, removed or just broken

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
You're using the event incorrectly.
[https://github.com/NEZNAMY/TAB/wiki/Developer-API#events](
https://github.com/NEZNAMY/TAB/wiki/Developer-API#events)
