### ISSUE TITLE
does not recognize the "permission plugin" if I use aquacore

### ISSUE THREAD

**Issue by Zapry** [NEZNAMY/TAB#902]
### Server version

Purpur 1.17.1

### TAB version

3.3.2

### Describe the bug

The problem (in my case) is that in my Network some modalities do not detect the aquacore plugin. For example, in Survival the plugin is detected correctly, and the order in the TAB works correctly (https://imgur.com/a/7M4BODG). The problem is that in other modalities such as the Hub it does not correctly detect the plugin, which causes the ranks in the tab to not be placed correctly. Aquacore and TAB plugin config is exactly the same as in survival (https://imgur.com/a/LTHBlQi)

### Expected behavior

The expected behavior has to be that in all modalities it detects the Aquacore plugin

### Steps to reproduce

There are no steps for this to happen, it always happens regardless of what I do

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You must be missing Vault then.

**Comment by Zapry** [comment]
I love you <3
