### ISSUE TITLE
Conditional placeholder fails until plugin is reloaded

### ISSUE THREAD

**Issue by BakiDance** [NEZNAMY/TAB#903]
### Server version

Waterfall with Paper 1.19.4 backend  (TAB bridge)

### TAB version

3.3.2

### Stack trace

[00:41:13 INFO] [TAB]: "%essentials_afk%" is not a defined condition nor a condition pattern

### Additional info

I have a single conditional placeholder which consistently fails to display/parse, and I have been unable to determine why.  The placeholder's condition is based on the output of %essentials_afk%. When a player first joins the server, the tab shows the placeholder instead of parsing it (eg. "%condition:PlayerGradient_EventsPrefix%") until either:

A. The plugin is reloaded (/btab reload)
B. The player runs / afk. (/papi parse <NAME> %essentials_afk% returns the expected value, so it's not the external placeholder)

Even weirder, I have other conditional placeholders that use %essentials_afk%, but these are not affected by this issue.  

## Images

1. Shows the appearance of Tab when a player logs into the server
2. Shows the appearance of Tab when the player is given a Staff role (condition is fixed. removing the staff role reverts to the previous image)
3. The appearance of Tab after the player toggles their AFK status twice (this is the expected appearance)

![2023-05-25_19 39 19](https://github.com/NEZNAMY/TAB/assets/43658058/707c463d-893d-4a77-ab88-26299fb9d4a4)
![2023-05-25_19 38 48](https://github.com/NEZNAMY/TAB/assets/43658058/58f42b25-a169-4c8f-b072-da6f57e2e761)
![2023-05-25_19 42 48](https://github.com/NEZNAMY/TAB/assets/43658058/061b336d-3c37-44e8-a668-1f5513e76286)

## Files
[config.txt](https://github.com/NEZNAMY/TAB/files/11570385/config.txt)
[groups.txt](https://github.com/NEZNAMY/TAB/files/11570386/groups.txt)
[errors.log](https://github.com/NEZNAMY/TAB/files/11570393/errors.log) (No error is logged, but I've attached it anyway)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
Inactive user and an update was released, reopen if issue is still present.
