### ISSUE TITLE
scoreboard error

### ISSUE THREAD

**Issue by adriancors13** [NEZNAMY/TAB#904]
### Server version

Spigot 1.19.2

### TAB version

3.3.2

### Stack trace

![api2](https://github.com/NEZNAMY/TAB/assets/132400762/5b9fadef-0b30-4eef-9be8-eb1558ccb6c4)
![api1](https://github.com/NEZNAMY/TAB/assets/132400762/6e56d099-21fc-4dc0-bc62-25c0e4c0a546)
![api3](https://github.com/NEZNAMY/TAB/assets/132400762/5c544538-d828-46fc-94d0-543ae11145f6)

### Steps to reproduce (if known)

..

### Additional info

I have a small problem with my scoreboard, out of nowhere the api variables stopped working and I even downloaded PlaceholderAPI plugin again and nothing... the strange thing is that the tab works

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/5fa85d20-6826-4a9c-9155-e456eb83da5c)
Send your TAB config and server log.

**Comment by NEZNAMY** [comment]
Unable to reproduce and user went missing, reopen if issue is present in new version.
