### ISSUE TITLE
Name tags freak out when spamming shift

### ISSUE THREAD

**Issue by AddmanMinecraft** [NEZNAMY/TAB#905]
### Server version

PaperSpigot-445 (MC: 1.8.8)

### TAB version

3.3.2

### Describe the bug

When the plugin is loaded and you spam shift the nametags moved about 2 players hights up  

### Expected behavior

The name tag should stay above the players head at all times.

### Steps to reproduce

1. Download TAB 3.3.2
2. Install it on 1.8.8 server
3. spam shift

### Additional info

Video: https://youtu.be/Uj9d4puCoFs

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
I did some tests and it works fine since 1.11. This must be a client bug, which got fixed a long time ago.

**Comment by RobuxTRex** [comment]
freaks out
