### ISSUE TITLE
Weird suffix alignment issue with bold nickname/prefix

### ISSUE THREAD

**Issue by TheMoltenHusky** [NEZNAMY/TAB#907]
### Server version

BungeeCord 1.19.4

### TAB version

3.3.2

### Describe the bug

When a user has a bold name or prefix, the aligned suffix gets pushed over to the left slightly, misaligning the suffix
![2023-05-30_08 26 03](https://github.com/NEZNAMY/TAB/assets/38053171/e7dc2241-ce5b-4573-8ed5-80fc3f52c0c2)

### Expected behavior

Align the suffix whether the player has a bold name/prefix or not
![2023-05-30_08 25 35](https://github.com/NEZNAMY/TAB/assets/38053171/f16fdaac-b635-4691-a2dc-2efff5403a2c)

### Steps to reproduce

Apply a bold nickname or prefix

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Known-issues#15x---112x---unwanted-space

**Comment by NEZNAMY** [comment]
That doesn't sound like it.
