### ISSUE TITLE
how can I make individual tab sorting for each player?

### ISSUE THREAD

**Issue by okzerus** [NEZNAMY/TAB#909]
### Server version

Paper 1.19.2

### TAB version

3.3.2

### Describe the bug

I have 3 groups of players on my server (not permissions)
the player (white, should be above other players)
his friends (light gray, should be below the player)
strangers (dark gray, should be below the strangers)
I want to make this sorting for each player, but can't figure out how.
I'm not sure if this is the right place to ask, but I hope for at least some tips on how to do it.

### Expected behavior

..

### Steps to reproduce

..

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
You cannot.
