### ISSUE TITLE
Crash due to minecraft version

### ISSUE THREAD

**Issue by Lok3rn3t** [NEZNAMY/TAB#917]
### Server version

Purpur 1.20

### TAB version

latest

### Stack trace

[TAB] No compatibility issue was found, but this plugin version does not claim to support your server package (v1_20_R1). This jar has only been tested on 1.5 - 1.19.4. Disabling just to stay safe.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
"latest" is not a version. 1.20 support was added in 4.0.0, which is currently only available for buyers.
