### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by Potothingi** [NEZNAMY/TAB#919]
I hope someday this plugin will support Folia.
Folia isn't a stable release yet, so don't rush.

Currently, 'ProtocolLib, Vault, LuckPerms, PlaceholderAPI, EssentialsX, ViaVersion, ViaBackwards, CoreProtect, DiscordSRV, Chunky, Spark' plugins already support Folia, or Folia support is ready in pull requests.

https://docs.papermc.io/folia
https://github.com/PaperMC/Folia#plugin-compatibility

**Comment by Tanguygab** [comment]
In and case you use BungeeCord, TAB-Bridge already supports Folia so you could use TAB on Bungee and put the bridge on Folia. Though the main plugin doesn't support it just yet

**Comment by NEZNAMY** [comment]
> Folia isn't a stable release yet, so don't rush.

I don't rush, just everyone else around does and makes requests while they are closed.  
In TAB's case, it's not as simple as calling a different method for scheduling a task. While there might be more, I noticed the following problems:
* `Bukkit.getTPS()` is hardcoded to always return `20`. What should TAB do about this? Should the placeholder just be considered not working? What if people want to display average or min tps? That would require a deep hook into Folia. Would that still be TAB's job? Shouldn't a PlaceholderAPI expansion for folia be made instead?
* `Bukkit.getAverageTickTime()` is hardcoded to return `0`. See above.
* [Sync placeholders](https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing) no longer make sense. This could be a problem, for example:
  * Placeholders like %server_total_entities% will now perma-throw.
  * Denizen placeholders have a main thread check, which now doesn't make much sense either. More plugins can/may have this as well. Should this problem be left to them or should be considered on TAB's side?
* https://github.com/NEZNAMY/TAB/blob/master/bukkit/src/main/java/me/neznamy/tab/platforms/bukkit/features/unlimitedtags/BukkitNameTagX.java#L97-L110 will throw. Should the task be scheduled? Will it not cause a deadlock on plugin reload?

If none of this affects you / you don't care, mark folia as supported and use the plugin.

**Comment by NEZNAMY** [comment]
Doesn't matter as long as I don't have answers to previous questions.

**Comment by Zoltus** [comment]
> Doesn't matter as long as I don't have answers to previous questions.

Well just trying to help you, but gl figuring those things out.

**Comment by ImNotSoftik** [comment]
@NEZNAMY 

To get TPS on Folia, do the following:

        Bukkit.getAsyncScheduler().runAtFixedRate(Pitbul.instance, task1 -> player.getScheduler().run(
                Pitbul.instance,
                task2 -> {
                    TickData.TickReportData report = TickRegionScheduler.getCurrentRegion()
                                                                        .getData()
                                                                        .getRegionSchedulingHandle()
                                                                        .getTickReport15s(System.nanoTime());
                    tps = report.tpsData().segmentAll().average();
                }, null), 1, 1, TimeUnit.SECONDS);

MSPT 

        Bukkit.getAsyncScheduler().runAtFixedRate(Pitbul.instance, task1 -> player.getScheduler().run(
                Pitbul.instance,
                task2 -> {
                    TickData.TickReportData report = TickRegionScheduler.getCurrentRegion()
                                                                        .getData()
                                                                        .getRegionSchedulingHandle()
                                                                        .getTickReport15s(System.nanoTime());
                    double MSPT = report.timePerTickData().segmentAll().average() / 1.0E6;

I suggest adding folia_player_region_tps and 
folia_player_region_mspt placeholders

**Comment by NEZNAMY** [comment]
That sounds like something for PlaceholderAPI.
