### ISSUE TITLE
Spaces in front of overhead usernames

### ISSUE THREAD

**Issue by I0wnu4life** [NEZNAMY/TAB#92]
**Server version**
1.15.1

**Plugin version** ("latest" is not a version)
v2.6.2

**Describe the bug**
Players on tab and above their heads have an extra space in front of their names.

**How to reproduce**
I removed the [Player] prefix/suffix. 

**Expected behavior**
Remove everything in front of their names.

**Actual behavior**
Removes just the [Player] and keeps the space

**Additional info** (errors, screenshots, ...)
http://prntscr.com/qmi7rr
http://prntscr.com/qmi7y5

**Comment by NEZNAMY** [comment]
Looks like default config's space set in tabprefix and tagprefix after vault-prefix placeholder. There is no space hardcoded into the plugin so it must be in your config.

**Comment by I0wnu4life** [comment]
I looked for a "(space) or a "(space)" and I couldn't find anything. I'm not seeing where the issue would come in. The only configuration that I had for the section "Players" was a "&7" which that shouldn't create a space in front of their names. It doesn't make sense to me.

**Comment by NEZNAMY** [comment]
Show your config.

**Comment by I0wnu4life** [comment]
change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

#20 ticks = 1 second
nametag-refresh-interval-ticks: 20
tablist-refresh-interval-ticks: 20
header-footer-refresh-interval-ticks: 2

header:
  - "%animation:ServerName%"
  - "&6&lRank: %rank%"
  - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
  - "&7Online players: &f%online%"
  - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
  - "%animation:ping-tps%"
  - ""
  - "%animation:MyAnimation1%"
# - "%animation:versions%" #requires ViaVersion or ProtocolSupport
footer:
  - "%animation:MyAnimation1%"
  - "%animation:time%"
  - ""
  - "&7Visit our webpage %animation:web%"

#the yellow number in tablist
#options: PING, HEARTS, NONE (to disable it), CUSTOM (any placeholder defined below)
tablist-objective: PING
tablist-objective-custom-value: "%some_placeholderapi_placeholder%"

#NOT case sensitive
group-sorting-priority-list:
  - Owner
  - SrAdmin
  - Admin
  - SrMod
  - Mod
  - Helper
  - Builder
  - ObsidianRank
  - EmeraldRank
  - DiamondRank
  - GoldRank
  - IronRank
  - CoalRank
  - default

#properties: tabprefix, tabsuffix, tagprefix (in name tag), tagsuffix, customtabname (modifying the name itself), header, footer
#extra ones which need unlimited nametag mode enabled: abovename (line of text above name tag), belowname (below name tag), customtagname
Groups:
  Owner:
    tabprefix: "&f&l[&4&lOwner&f&l] &7"
    tagprefix: "&f&l[&4&lOwner&f&l] &7"
    header:
      - "%animation:ServerName%"
      - "&6&lRank: %rank%"
      - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
      - "&7Online players: &f%online%"
      - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
      - "%animation:ping-tps%"
      - ""
      - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
      - "%animation:MyAnimation1%"
    footer:
      - "%animation:MyAnimation1%"
      - "%animation:time%"
      - ""
      - "&7Visit our webpage %animation:web%"
  SrAdmin:
    tabprefix: "&f&l[&c&lSr Admin&f&l] &7"
    tagprefix: "&f&l[&c&lSr Admin&f&l] &7"
    header:
      - "%animation:ServerName%"
      - "&6&lRank: %rank%"
      - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
      - "&7Online players: &f%online%"
      - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
      - "%animation:ping-tps%"
      - ""
      - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
      - "%animation:MyAnimation1%"
    footer:
      - "%animation:MyAnimation1%"
      - "%animation:time%"
      - ""
      - "&7Visit our webpage %animation:web%"
  Admin:
    tabprefix: "&f&l[&c&lAdmin&f&l] &7"
    tagprefix: "&f&l[&c&lAdmin&f&l] &7"
    header:
      - "%animation:ServerName%"
      - "&6&lRank: %rank%"
      - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
      - "&7Online players: &f%online%"
      - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
      - "%animation:ping-tps%"
      - ""
      - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
      - "%animation:MyAnimation1%"
    footer:
      - "%animation:MyAnimation1%"
      - "%animation:time%"
      - ""
      - "&7Visit our webpage %animation:web%"
  SrMod:
    tabprefix: "&f&l[&9&lSr Mod&f&l] &7"
    tagprefix: "&f&l[&9&lSr Mod&f&l] &7"
    header:
      - "%animation:ServerName%"
      - "&6&lRank: %rank%"
      - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
      - "&7Online players: &f%online%"
      - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
      - "%animation:ping-tps%"
      - ""
      - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
      - "%animation:MyAnimation1%"
    footer:
      - "%animation:MyAnimation1%"
      - "%animation:time%"
      - ""
      - "&7Visit our webpage %animation:web%"
  Mod:
    tabprefix: "&f&l[&9&lMod&f&l] &7"
    tagprefix: "&f&l[&9&lMod&f&l] &7"
    header:
      - "%animation:ServerName%"
      - "&6&lRank: %rank%"
      - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
      - "&7Online players: &f%online%"
      - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
      - "%animation:ping-tps%"
      - ""
      - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
      - "%animation:MyAnimation1%"
    footer:
      - "%animation:MyAnimation1%"
      - "%animation:time%"
      - ""
      - "&7Visit our webpage %animation:web%"
  Helper:
    tabprefix: "&f&l[&a&lHelper&f&l] &7"
    tagprefix: "&f&l[&a&lHelper&f&l] &7"
    header:
      - "%animation:ServerName%"
      - "&6&lRank: %rank%"
      - "&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<"
      - "&7Online players: &f%online%"
      - "&6Online staff: &e%staffonline%" # staffs are people with "tab.staff" permission
      - "%animation:ping-tps%"
      - ""
      - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
      - "%animation:MyAnimation1%"
    footer:
      - "%animation:MyAnimation1%"
      - "%animation:time%"
      - ""
      - "&7Visit our webpage %animation:web%"
  Obsidian:
    tabprefix: "&f[&5Obsidian&f] &7"
    tagprefix: "&f[&5Obsidian&f] &7"
  Emerald:
    tabprefix: "&f[&aEmerald&f] &7"
    tagprefix: "&f[&aEmerald&f] &7"
  Diamond:
    tabprefix: "&f[&bDiamond&f] &7"
    tagprefix: "&f[&bDiamond&f] &7"
  Gold:
    tabprefix: "&f[&6Gold&f] &7"
    tagprefix: "&f[&6Gold&f] &7"
  Iron:
    tabprefix: "&f[&7Iron&f] &7"
    tagprefix: "&f[&7Iron&f] &7"
  Coal:
    tabprefix: "&f[&8Coal&f] &7"
    tagprefix: "&f[&8Coal&f] &7"
  Player:

    
  #any other group not defined above
  _OTHER_:
    tabprefix: "%vault-prefix% "
    tagprefix: "%vault-prefix% "
    tabsuffix: "%afk%"
    tagsuffix: "%afk%"
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"

#personal settings, override group settings
Users:
  _NEZNAMY_:
    tabprefix: "&6&lTAB Author &a"
    tagprefix: "&6&lTAB &r&a"
    abovename: "&bOh look, 3 lines of text !"
    belowname: "&eThere's only one plugin out there supporting it"

#the vanilla belowname feature
#doesn't support player placeholders (faction, prefix), only server placeholders (time, date, animations) and static text
belowname:
  enabled: true
  refresh-interval-ticks: 5
  number: "%health%"
  text: "Health"
  
  
#servers and clients 1.9+
enable-collision: true
    
#preventing players in spectator gamemode from appearing at the bottom of tablist with transparent name FOR OTHER PLAYERS
do-not-move-spectators: false

#VERY EXPERIMENTAL !
#IF YOU EXPERIENCE ANY ISSUES CONTACT ME
unlimited-nametag-prefix-suffix-mode:
  enabled: false
  
  #modifying names of NPCs to avoid empty names on NPCs of online players
  #this blocks any other attemps to change the name visibility or anything, so you need to disable it if you are using some citizens addon that changes their name
  #needs relog to see the change
  modify-npc-names: false


#list of worlds with different settings than default, other worlds will use settings from above
per-world-settings:
  world1:
    header:
      - "an example of world with custom"
    footer:
      - "header/footer and prefix/suffix"
    Groups:
      Owner:
        tabprefix: "&0&l[&a&lOwner&0&l] &a"
        tagprefix: "&2&lOwner &a"
  world2-world3:
    header:
      - "This is a shared header for"
      - "world2 and world3"
#setting output of some placeholders
placeholders:
  deluxetag-yes: "< %value% >"
  deluxetag-no: "&oNo Tag :("
  faction-yes: "< %value% >"
  faction-no: "&2Wilderness"
  afk-yes: " &4*&4&lAFK&4*&r"
  afk-no: ""
  date-format: "MM.dd.yyyy"
  time-format: "[HH:mm:ss / h:mm a]" #pick one of the two common formats
  
  #if time doesn't show correctly, you can change the time it shows
  #setting to -1 will make it show 1 hour less than it does currently, 1 makes it show one hour more than currently, 0 does nothing
  time-offset: -6
  
  #remove these strings from everywhere. Typically an empty output when using some clan/faction related plugin but player isn't in any
  #so players won't have empty brackets before their names
  remove-strings:
    - "[] "
    - "< > "
  
#better showing of %rank% placeholder
rank-aliases:
  Owner: "&4&lOWNER"
  SrAdmin: "&c&lSR ADMIN"
  Admin: "&c&lADMIN"
  SrMod: "&9&lSR MOD"
  Mod: "&9&lMOD"
  Helper: "&a&lHelper"
  #any group not defined above
  _OTHER_: "&7&lNo Rank"
  
disable-features-in-worlds:
  header-footer:
    - disabledworld
  tablist-names:
    - disabledworld
  nametag:
    - disabledworld
  tablist-objective:
    - disabledworld
  bossbar:
    - disabledworld
  belowname:
    - disabledworld

**Comment by NEZNAMY** [comment]
Pastebin would be more appropriate. The reason are lines:
OTHER:
tabprefix: "%vault-prefix% "
tagprefix: "%vault-prefix% "

For groups with no vault prefix there's a space only.
