### ISSUE TITLE
TAB v4 & Bridge v3

### ISSUE THREAD

**Issue by c0dingnoobi** [NEZNAMY/TAB#921]
### Server version

Spigot 1.8.8

### TAB version

4.0.0

### Describe the bug

This issue is (once again) in relation to 1.7 Clients. When running dev version of TAB behind proxy (FlameCord) and TAB-Bridge v3 on backend, 1.7 client will get kicked when `scoreboards.enabled: true`, mostly when using '/btab reload' or when forcing the scoreboard (f.e by a placeholder like %world% as condition for another scoreboard) to be set again. 
Tested without plugins except Via* + Bridge on backend and TAB with default config (except scoreboards defined and enabled).

Kick reason: `[noobiii] disconnected with: EncoderException : java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null @ io.netty.handler.codec.MessageToByteEncoder:-1`

### Expected behavior

Expected behaviour would be to not being kicked when either reloading or forcing a scoreboard updating
Does work without problems for 1.8 Client && without scoreboards enabled for 1.7 Client

### Steps to reproduce

1. Load default config and enable Scoreboards
2. Do `/btab reload` while any 1.7 player is online 
3. See him getting kicked for mentioned error

or
2. Define two scoreboards which do have `display-condition: %world%=world` for scoreboard number 1 and `display-condition: %world%=(anyWorldName)` for scoreboard number 2
3. Switch from world to world anyWorldName
4. Results in same kick reason

### Additional info

Would be nice to see this fixed, even tho its basically an unsupported version. Might also be important to mention that this only happens when being behind proxy, when running tab v4 on backend this issue is not reproduceable.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
When recoding I accidentally broke it again, because I was checking code of bungeecord, which doesn't include 1.7 support, so I set an unused field to null instead of empty string, which is encoded on 1.7. Will be fixed in next version.

**Comment by c0dingnoobi** [comment]
<3
