### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by naickkk** [NEZNAMY/TAB#923]
### Server version

Paper 1.16.5

### TAB version

3.3.2

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/91740990/17ee8f5c-cc1e-44ba-8e06-8c08e4872cc2)

### Expected behavior

hide the nametags correctly

### Steps to reproduce

![image](https://github.com/NEZNAMY/TAB/assets/91740990/f3f6dba4-045d-4789-983e-7f8b6cf6417f)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Clearly player is null. It is not a TAB bug you are passing null to a non-null parameter. The reason why API returned null is probably because you are calling it before TAB had a chance to load the player. See API page for more info.

**Comment by naickkk** [comment]
The getOnlinePlayers from Api contains not loaded players?

**Comment by Tanguygab** [comment]
the error comes from this hideNametag call 
![image](https://github.com/NEZNAMY/TAB/assets/45695833/8af728df-8d94-4e8c-9586-e17959538151)
you're getting players from name, maybe those players disconnected or don't exist?

**Comment by naickkk** [comment]
> the error comes from this hideNametag call 
> 
> ![image](https://github.com/NEZNAMY/TAB/assets/45695833/8af728df-8d94-4e8c-9586-e17959538151)
> 
> you're getting players from name, maybe those players disconnected or don't exist? 

i've created an optional ofNullable tab.getPlayer(s) and do things only when is present, same error

**Comment by NEZNAMY** [comment]
You cannot get a NPE if passing a non-null argument. Plugin does work correctly.

**Comment by naickkk** [comment]
> Non puoi ottenere un NPE se passi un argomento non nullo. Il plugin funziona correttamente.

![image](https://github.com/NEZNAMY/TAB/assets/91740990/0564439e-b234-4d54-b9b0-3738e46aa940)

**Comment by Tanguygab** [comment]
does it work now? if it doesn't, send the new error and show send your class over a [paste service](paste.helpch.at), or at least show your code's lines on the left in your screenshots

**Comment by naickkk** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/91740990/1d0c5e16-06ed-4bf7-9f21-21862d2b475e)

**Comment by naickkk** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/91740990/5e8809d7-3d0a-45c1-b6cd-6913c4cf2826)

**Comment by Tanguygab** [comment]
before hiding the player's nametag, check whether the player's nametag is hidden or not

**Comment by naickkk** [comment]
https://pastebin.com/yu0ZtYAL

**Comment by Tanguygab** [comment]
kinda late, I already gave you the answer
