### ISSUE TITLE
Tab/Vault API Intergration Issue

### ISSUE THREAD

**Issue by Enchalopax** [NEZNAMY/TAB#924]
### Server version

Paper 1.20.1

### TAB version

4.0.1

### Describe the bug

![2023-06-14_23 20 50](https://github.com/NEZNAMY/TAB/assets/71933613/6adff983-0afa-48be-87f5-28a101599aab)

Doesn't look like Tab is like an API somewhere as shown in image its putting %vault-prefix% before username and then %vault-suffix%%afk% after the username.

### Expected behavior

As expected should have the API writing in Tab menu

### Steps to reproduce

there all the time

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
read the changelogs

**Comment by Enchalopax** [comment]
oops didnt see thats bit sorry
