### ISSUE TITLE
ping placeholder error

### ISSUE THREAD

**Issue by f1xxd** [NEZNAMY/TAB#928]
### Server version

Purpur 1.20.1

### TAB version

4.0.0

### Stack trace

15.06.2023 - 18:26:02 - [TAB v4.0.0-SNAPSHOT] Player placeholder %ping% generated an error when setting for player flxpr
15.06.2023 - 18:26:02 - java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
15.06.2023 - 18:26:02 - 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69)
15.06.2023 - 18:26:02 - 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132)
15.06.2023 - 18:26:02 - 	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.getInt(UnsafeQualifiedObjectFieldAccessorImpl.java:59)
15.06.2023 - 18:26:02 - 	at java.base/java.lang.reflect.Field.getInt(Field.java:601)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.platforms.bukkit.BukkitTabPlayer.getPing(BukkitTabPlayer.java:75)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.placeholders.UniversalPlaceholderRegistry.lambda$registerPlaceholders$10(UniversalPlaceholderRegistry.java:42)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:138)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:57)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:118)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:69)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$11(CpuManager.java:217)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.CpuManager.run(CpuManager.java:243)
15.06.2023 - 18:26:02 - 	at TAB.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:96)
15.06.2023 - 18:26:02 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
15.06.2023 - 18:26:02 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
15.06.2023 - 18:26:02 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
15.06.2023 - 18:26:02 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
15.06.2023 - 18:26:02 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
15.06.2023 - 18:26:02 - 	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce (if known)

Step 1: join server (???)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
you're using outdated dev builds that don't support 1.20+

**Comment by f1xxd** [comment]
Bukkit & forks | (1.5 - 1.20.1)

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/fbff5284-9acc-49a3-9c46-2082054a756a)
Which is currently only available for buyers.

**Comment by Tanguygab** [comment]
4.0.1 will be released for free tomorrow, just wait a little longer

**Comment by f1xxd** [comment]
ok thanks
