### ISSUE TITLE
Plugin doesnt support

### ISSUE THREAD

**Issue by maxbridges1998** [NEZNAMY/TAB#929]
### Server version

Paper 1.20.1

### TAB version

3.3.2

### Describe the bug

Plugin doesnt support

### Expected behavior

Plugin doesnt support

### Steps to reproduce

Plugin doesnt support

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
can't be more obvious
3rd duplicate
![image](https://github.com/NEZNAMY/TAB/assets/45695833/fbcc9981-cc3d-4ecf-aad8-9c27a858df72)
