### ISSUE TITLE
Name animations stuck

### ISSUE THREAD

**Issue by Sm4k1na** [NEZNAMY/TAB#93]
**Server version**

spigot 1.8.9 
**Plugin version** ("latest" is not a version)

2.6.2
**Describe the bug**
I made animations, all in the correct way and added %animation:animationname% in TAB it shows the animation but it's locked, it doesn't work it's stuck, as ticks in every animation I set 500

**How to reproduce**

I don't know
**Expected behavior**
That in TAB I see the full NAME animations

**Actual behavior**
 the name animations are stuck, the other ones works like the Welcome etc. but the names doesn't work

**Additional info** (errors, screenshots, ...)
No errors in console

**Comment by NEZNAMY** [comment]
Show you config.yml and animations.yml, you misconfigured something.

**Comment by Sm4k1na** [comment]
OK here they are, thanks for the quick answer.
config: https://pastebin.com/LdtqZUAP
animations: https://pastebin.com/jzBH4tpy

**Comment by NEZNAMY** [comment]
And which one of these animations is not working ?

**Comment by NEZNAMY** [comment]
That's because you did not decrease refresh interval. You kept it at 20 ticks (1000 milliseconds) but the animation refreshes once per 500 millis. As a result, animations skip every other frame.

**Comment by Sm4k1na** [comment]
I tried 10 and 9 but it didn't work, What am I doing werong? Thanks

**Comment by NEZNAMY** [comment]
Try 10. And you did not show a screenshot or any explanation which allows me to understand what is actually wrong.

**Comment by Sm4k1na** [comment]
Would you help me with AnyDesk so I can show you? Because it's difficult to explain with a screenshot. Thanks

**Comment by NEZNAMY** [comment]
I'm pretty sure a screenshot or two with an exaplanation what's wrong there will do it.

**Comment by Sm4k1na** [comment]
Ok I'll try

**Comment by Sm4k1na** [comment]
https://imgur.com/a/R0EWPFe

**Comment by Sm4k1na** [comment]
As you can see the tablist animation of FOUNDER doesn't work.

**Comment by NEZNAMY** [comment]
Check your permission group using /tab debug. You might be in a different group, which uses %vault-prefix% instead of what you think it uses.

**Comment by Sm4k1na** [comment]
Ok so I discovered that I copied  all the files of the configuration and pasted on my Hub (different server) and there they works prefectly, so There must be something wrong outside the configuration files, what could it possibily be? THanks

**Comment by NEZNAMY** [comment]
I have no idea what could an issue be caused by when i don't know what the issue is. Did you check your group as i told you using the debug command ?

**Comment by Sm4k1na** [comment]
yes I did the output says %vault-prefix%

**Comment by NEZNAMY** [comment]
But vault-prefix is not an animation, is it ? Also i said check group, you didn't. Your group is different than the group using the animation.

**Comment by Sm4k1na** [comment]
Oh turns out that the %vault-prefix% shouldn't be there, so once removed it removes all the prefixses, but now I am Founder and I created a group in the TAB called Founder but after the reload I am not in it, I use Aquacore for the permissions maybe this is the problem

**Comment by NEZNAMY** [comment]
For the 4rd time, verify your permission group using /tab debug [player].

**Comment by Sm4k1na** [comment]
Sorry, The output says : "Primary permission group: Founder"

**Comment by NEZNAMY** [comment]
Can you show a screenshot of the full output and current config ?

**Comment by Sm4k1na** [comment]
Sure,
Config: https://pastebin.com/SLrNWJMq
screenshot: https://pasteboard.co/IPOMLVT.png

**Comment by NEZNAMY** [comment]
Because your group name contains colors which it shouldn't. Rename groups in permission plugin or in tab's config use group names such as "§4§oFounder" instead of just "Founder" which you are using.

**Comment by Sm4k1na** [comment]
Oh ok sorry, changing it now

**Comment by Sm4k1na** [comment]
Ok I changed them and added the right color and format codes, but it still doesn't work it displays a white name wiothout anything the output of tab debug is the same of the last one.

**Comment by NEZNAMY** [comment]
Try using the other of & or § than you tried before.

**Comment by Sm4k1na** [comment]
I tried and it still doesn't work

**Comment by NEZNAMY** [comment]
Then use appropriate group names without color codes in your permission plugin.
