### ISSUE TITLE
Afk placeholder not work

### ISSUE THREAD

**Issue by phys1cs27** [NEZNAMY/TAB#931]
### Server version

PurPur 1.20

### TAB version

last build 4.0.2

### Describe the bug

%afk% not working

### Expected behavior

![image](https://github.com/NEZNAMY/TAB/assets/95995512/56476f7c-6ca2-4ddd-acf0-23fb6e602f17)

### Steps to reproduce

Write %afk%

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
read changelogs
