### ISSUE TITLE
Prevent spectator effect is not working

### ISSUE THREAD

**Issue by Nononitas** [NEZNAMY/TAB#934]
### Server version

Waterfall 1.20 Build 536. Sub-serverPaper 1.19.4

### TAB version

4.0.1

### Describe the bug

prevent-spectator-effect option doesn't work when bungeecord is in online mode

### Expected behavior

prevent-spectator-effect option should work if bungeecord is in online mode

### Steps to reproduce

- Make sure the Bungeecord is in online mode
- Have prevent-spectator-effect enabled
- Join the server and go in gm3
- You will see that everyone sees you are in gm3

### Additional info

It works when the bungeecord is in offline mode

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your waterfall.yml

**Comment by Nononitas** [comment]
```
throttling:
  tab_complete: 1000
log_initial_handler_connections: true
registered_plugin_channels_limit: 128
use_netty_dns_resolver: true
game_version: ''
disable_tab_list_rewrite: false
disable_entity_metadata_rewrite: false
disable_modern_tab_limiter: true
plugin_channel_name_limit: 128
```

**Comment by NEZNAMY** [comment]
Sounds good. Send TAB config.yml as well.

**Comment by Nononitas** [comment]
I am using the default one

**Comment by NEZNAMY** [comment]
So `use-online-uuid-in-tablist` is `true`? What if you set it to `false`?

**Comment by Nononitas** [comment]
Issue persists

**Comment by NEZNAMY** [comment]
Turns out BungeeCord is not tracking player's gamemode correctly when online mode is enabled. I will perform further tests, but I'm not sure if I can resolve it.

**Comment by Nononitas** [comment]
Maybe it's a Bungeecord Bug then, because it worked with older waterfall versions?

**Comment by Nononitas** [comment]
Nevermind, it they don't work either. Seems like v4 is the cause, but you have already made a commit.

**Comment by Nononitas** [comment]
I tested your build 766 with the TAB-Bridge build 6 and I can confirm that the problem still persists

**Comment by NEZNAMY** [comment]
Does plugin reload fix it?

**Comment by Nononitas** [comment]
No

**Comment by NEZNAMY** [comment]
What does `/btab parse <player> %gamemode%` show for players in spectator gamemode?

**Comment by Nononitas** [comment]
https://i.postimg.cc/SstN37nh/grafik.png

**Comment by NEZNAMY** [comment]
Are you sure you don't have the bypass permission and are not looking at yourself? It worked when I tested it after fixing it.

**Comment by Nononitas** [comment]
Yes I am very sure

**Comment by NEZNAMY** [comment]
Well that's bad. Sadly I can't even send you jars to test here.

**Comment by Nononitas** [comment]
Send me your discord id or something

**Comment by NEZNAMY** [comment]
Problem is that this kind of service is only provided to customers to at least have any little reason to support years of my work.

**Comment by Nononitas** [comment]
I don't want support, but if you don't want help fixing the error, that's up to you

**Comment by NEZNAMY** [comment]
Well [here's a video](https://www.youtube.com/watch?v=jAAnrACoxFg) trying out everything possible and it works.

**Comment by Nononitas** [comment]
Is your backend on 1.19.4?

**Comment by NEZNAMY** [comment]
Yes

**Comment by Nononitas** [comment]
Here my [proof](https://www.youtube.com/watch?v=oIcd9mXGh98)
I have only TAB-bridge installed, TAB on proxy. No other plugins. The player Nononitas is oped

**Comment by NEZNAMY** [comment]
Can you include gamemode placeholder somewhere like I did to make sure it updates correctly? Also if you run `/btab debug <player>`, does it say bridge connected?

**Comment by Nononitas** [comment]
I would be very grateful if you could send the configuration for it with the gamemode placeholder
Here [debug](https://postimg.cc/v1FK1ZhX/04d3d929)

**Comment by NEZNAMY** [comment]
`/btab group _DEFAULT_ tabsuffix " GM: %gamemode%"`

**Comment by Nononitas** [comment]
[Video](https://youtu.be/ywpK65cW8OA)

**Comment by NEZNAMY** [comment]
Can you send your config? I'll try it.

**Comment by Nononitas** [comment]
https://pastebin.com/zXx1WgGw

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/93eab93f-a246-496d-8de7-761af9e3a43c)
?

**Comment by Nononitas** [comment]
Uffff

**Comment by Nononitas** [comment]
I'm sorry I deleted the TAB folder, before updating to the dev build. I forgot that this wasn't enabled by default.
Sorry for wasting your time. I appreciate your helpfulness

**Comment by Nononitas** [comment]
It works now
