### ISSUE TITLE
Groups are not recognized by TAB

### ISSUE THREAD

**Issue by kamil445** [NEZNAMY/TAB#935]
### Server version

Purpur 1.19.4 and Purpur 1.20.1

### TAB version

4.0.1

### Describe the bug

After upgraded to 4.0.1, group tabprefix and tagprefix stopped working, only settings from _DEFAULT_ section are visible.

Now is: 
![bad](https://github.com/NEZNAMY/TAB/assets/24758185/5f576877-3862-4b9f-b029-8f1577bb9afa)

Should be: 
![good](https://github.com/NEZNAMY/TAB/assets/24758185/bfff62ce-30c7-4fa0-88ae-833124ebd732)

I also tried recreate configuration and try again but no luck.

### Expected behavior

tabprefix, tagprefix should be displayed per player group as 3.3.2 version did

### Steps to reproduce

1. install 4.0.1 or upgrade from 3.3.2,
2. run server with permissions plugin and add tabprefix and tagprefix for example group,
3. add player to that group,
4. press TAB and see there are no tabprefix and tagprefix values from config,

### Additional info

groups.yml:

Admin:
  tabprefix: '%essentials_afk%&f[&4&lA&f] &1'
  abovename: '&f[&6%ping%&f]&f[&7Admin&f]%essentials_afk%'
Mod:
  tabsuffix: '%ping%'
  tabprefix: '&f[&e%player-version%&f]&f[&6M&f]%essentials_afk% &3'
  tagprefix: '&f[&6%ping%&f][&6Moderator&f]%essentials_afk% '
KidMod:
  tabprefix: '&f[&e%player-version%&f]&f[&eKM&f]%essentials_afk% &3'
  tagprefix: '&f[&6%ping%&f][&eKidMod&f]%essentials_afk% '
Gracz:
  tabprefix: '&f[&e%player-version%&f]&f[&7G&f]%essentials_afk% &3'
  tagprefix: '&f[&6%ping%&f][&7Gracz&f]%essentials_afk% '
per-world: {}
_DEFAULT_:
  tabsuffix: '%ping%'
  customtabname: '%essentials_nickname%'

I'm using PermissionsEx plugin for permissions.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Show output of `/tab debug <player>`

**Comment by kamil445** [comment]
Looks like permissions plugin isn't recognized ?

![obraz](https://github.com/NEZNAMY/TAB/assets/24758185/9f20bd92-5463-4453-8bb9-e9470ef8ad60)

**Comment by NEZNAMY** [comment]
Are you sure LuckPerms is installed correctly?

**Comment by kamil445** [comment]
i'm using PermissionsEx since years

**Comment by NEZNAMY** [comment]
Then assign by permissions. Vault hook was removed. Not a bug.

**Comment by kamil445** [comment]
Thanks for information, so i must switch to LuckPerms :)
