### ISSUE TITLE
/sb worked, but does not show the scoreboard

### ISSUE THREAD

**Issue by euj3ne** [NEZNAMY/TAB#936]
### Server version

Velocity 3.2.0 & Spigot 1.12.2/1.16.5

### TAB version

4.0.2

### Describe the bug

/sb worked, but does not show scoreboard

### Expected behavior

/sb worked, and show scoreboard

### Steps to reproduce

fix

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by euj3ne** [comment]
there are no errors in consoles and files

**Comment by NEZNAMY** [comment]
Velocity is not supported. Stop abusing issues.

**Comment by euj3ne** [comment]
I ran on Spigot

**Comment by euj3ne** [comment]
Ok, Ill create another request

**Comment by NEZNAMY** [comment]
[/sb works](https://www.youtube.com/watch?v=LlyOiQ_nMJE)

**Comment by euj3ne** [comment]
Yes, it works, but the scoreboard does not show

**Comment by NEZNAMY** [comment]
It does. See the video.

**Comment by euj3ne** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/109100606/9e62ac49-c566-4547-9a09-b5bf80429212)
![image](https://github.com/NEZNAMY/TAB/assets/109100606/cf528ef7-80e5-4ab3-a47f-faabe3770c9d)

**Comment by euj3ne** [comment]
He is not! And there are no errors either.

**Comment by NEZNAMY** [comment]
Are you sure you meet a condition for at least one scoreboard?

**Comment by euj3ne** [comment]
Yes

**Comment by euj3ne** [comment]
I reset even to the standard config

**Comment by NEZNAMY** [comment]
Show output of `/tab debug`

**Comment by euj3ne** [comment]
This command does not exist....

**Comment by Tanguygab** [comment]
> This command does not exist....

try /vtab debug

**Comment by NEZNAMY** [comment]
Then you don't have the plugin on spigot.

**Comment by euj3ne** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/109100606/90f9a675-abb7-455a-862c-802fae895844)

**Comment by NEZNAMY** [comment]
Backend version is not sending any plugin messages.

**Comment by euj3ne** [comment]
I can't figure out what's going on(

**Comment by Tanguygab** [comment]
you're using TAB on Velocity while we don't support Velocity

**Comment by NEZNAMY** [comment]
You don't have TAB installed. That's why the plugin doesn't work.

**Comment by euj3ne** [comment]
Give me a sec

**Comment by euj3ne** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/109100606/96ffffaf-0197-4419-b783-c7c954a5d7a4)

**Comment by Tanguygab** [comment]
show the upper part

**Comment by euj3ne** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/109100606/6f68dcae-3325-40db-a5c6-2e51d1719375)

**Comment by Tanguygab** [comment]
send your config.yml

**Comment by euj3ne** [comment]
Worth the standard

**Comment by Tanguygab** [comment]
what?

**Comment by euj3ne** [comment]
The standard config is installed, sorry

**Comment by Tanguygab** [comment]
then scoreboard is disabled

**Comment by NEZNAMY** [comment]
Change the command to something else and try that.

**Comment by euj3ne** [comment]
Oh my God, it's working

**Comment by NEZNAMY** [comment]
Now finally remove TAB from Velocity and never put it back again.

**Comment by euj3ne** [comment]
Then why do you have a platform for it there? and in 4.0.2 the file is compiled to support it?

**Comment by NEZNAMY** [comment]
For people looking to experiment with broken software.

**Comment by euj3ne** [comment]
understood, thank you very much
