### ISSUE TITLE
%afk% showed at the end of every player name regardless of AFK status

### ISSUE THREAD

**Issue by Zenologia** [NEZNAMY/TAB#937]
### Server version

Paper 1.20.1

### TAB version

4.0.1

### Describe the bug

Upon updating the plug-in from 3.2.2 to 4.0.1, a prefix of %afk% will display at the end of all names, regardless of AFK status through essentials. No config options were changed in the plug-in when updating it. 

Something to note:  I have 2 environments I’ve replicated this on with TAB version 4.0.1. 

Purpur 1.19.4 and Paper 1.20.1. Both have identical issues. I was able to fix the issue on the purpur server (this is the live server) by reverting the plug-in to 3.2.2. The paper 1.20.1 is a test server. 

I should also note I’ve seen this issue on a different 1.20 server (though I do not have admin rights to that other SMP) and their admin told me they also do not know why it’s happening. 

For example right now it will show me as “Zenologia%afk%” regardless of my AFK status

### Expected behavior

For the %afk% is placeholder to not show up in the tab list like that, and for the afk status to only display in the brackets [ ] if a user is actually afk

### Steps to reproduce

Update TAB from 3.2.2 to 4.0.1

ensure essentials, Placeholder API are up to date 

ensure placeholder api expansions are up to date

restart server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by H34R7L3s** [comment]
ok - so what do i have to do now? :)

**Comment by NEZNAMY** [comment]
Use %essentials_afk% with PlaceholderAPI and essentials expansion downloaded.

**Comment by H34R7L3s** [comment]
and for   tabprefix: "%vault-prefix%"   tagprefix: "%vault-prefix%"  --> essentials-prefix ?

**Comment by NEZNAMY** [comment]
No. This is not support. This is an issue tracker.

**Comment by CptDinosaur** [comment]
Worked it out.

In config.yml:
```
conditions:
  displayname:
    conditions:
    - '%essentials_afk%=yes'
    yes: '&cAFK&7| %essentials_nickname%'
    no: '%essentials_nickname%'
```

Then in groups.yml:
```
customtabname: "%condition:displayname%"
customtagname: "%condition:displayname%"
```

You might rather use a prefix or smth. But you get the idea.
