### ISSUE TITLE
TabPlayer.getTeamName() is no longer usable

### ISSUE THREAD

**Issue by Xiao-MoMi** [NEZNAMY/TAB#939]
### Server version

1.20.1

### TAB version

4.x

### Stack trace

I'm a developer and I noticed that 4.0 comes with some API changes. For the moment I can't find a method to get the player's team name. I hope to get some simple code to do that in 4.x

This method in 3.x is no longer usable in 4.0
java.lang.NoSuchMethodError: 'java.lang.String me.neznamy.tab.api.TabPlayer.getTeamName()'

Thanks for your work!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
It was removed. Why do you need player's team name? It's not like you can safely alter it, especially since it doesn't exist on server side.

**Comment by Xiao-MoMi** [comment]
> It was removed. Why do you need player's team name? It's not like you can safely alter the team, especially since it doesn't exist on server side.

I know that teams are sent by packets but some other plugins need to get the team name in TAB to make sure some packets(something like team info) can work

**Comment by NEZNAMY** [comment]
I can add a method for this. I still don't understand what is this needed for exactly.

**Comment by Xiao-MoMi** [comment]
To update the team prefix and suffix by packets. A team name (String) is required as the parameter

**Comment by Xiao-MoMi** [comment]
font support is not available as i known (in 3.x)
