### ISSUE TITLE
Playerlist still shows vanished players

### ISSUE THREAD

**Issue by guikaua12** [NEZNAMY/TAB#942]
### Server version

1.20.1

### TAB version

4.0.1

### Describe the bug

When `layout` (config.yml) (
![image](https://github.com/NEZNAMY/TAB/assets/33811154/9afbea4e-30bd-4d5f-940e-26dca5c1cd06)
) is disabled, it works fine, but when it is enabled, vanished players are still shown in the playerlist.

Is it a config issue? as i saw in the wiki, there is some sort of "condition", i'm not sure

i'm hiding players like this:
```java
p.hidePlayer(plugin, player);
```
i also tried with ProtocolLib:
```java
PacketContainer packet = protocolManager.createPacket(PacketType.Play.Server.PLAYER_INFO_REMOVE);
packet.getUUIDLists().write(0, Collections.singletonList(player.getUniqueId()));

Bukkit.getOnlinePlayers()
                .stream()
                .forEach(p -> {
                    protocolManager.sendServerPacket(p, packet);
                });
```

### Expected behavior

Player get removed from playerlist, as it happens with `layout` disabled

### Steps to reproduce

Enable `layout` on config.yml
Use /vanish on any vanish plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
<https://github.com/NEZNAMY/TAB/wiki/Additional-information#vanish-detection> You didn't say anything about applying the metadata flag. How is the plugin supposed to know to not display that palyer?

**Comment by guikaua12** [comment]
Thank you!
