### ISSUE TITLE
Velocity Placeholder issue

### ISSUE THREAD

**Issue by BearLeonLight** [NEZNAMY/TAB#944]
### Server version

Velocity - 3.2.0-SNAPSHOT 

### TAB version

4.0.2

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/52900334/e57bf22a-e9cb-4804-990d-a93e88e1755a)
PAPI doesn't work, I tried using CMI's nickname, server time, etc. to no avail.
Install TAB-Bridge v3.0.0 on the server.
Server version Paper-527 (MC: 1.19.4)

### Expected behavior

show PAPI

### Steps to reproduce

1. Install TAB 4.0.2 on Velocity
2. Install TAB-Bridge v3.0.0 on PaperMC and download the corresponding PAPI.
3. Change any place where PAPI can be used on the TAB. Use whatever PAPI the server can expose.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Right, I forgot to update bridge. Thanks for the reminder. Velocity still remains unsupported though.

**Comment by BearLeonLight** [comment]
> Right, I forgot to update bridge. Thanks for the reminder. Velocity still remains unsupported though.
Will there be later? (Support)

**Comment by NEZNAMY** [comment]
No.

**Comment by TomLewis** [comment]
I wish you would reconsider velocity support, most peolpe have already moved to it.

**Comment by Tanguygab** [comment]
https://gist.github.com/NEZNAMY/21c1aabe57a0a462ee175386c510fdf8
