### ISSUE TITLE
4.0 changelog missing

### ISSUE THREAD

**Issue by Chris6ix** [NEZNAMY/TAB#945]
### Page link

https://github.com/NEZNAMY/TAB/releases

### Current text (if applicable)

Hey, I noticed that TAB 4.0 (now 4.0.2) is out, but as it looks, you never released 4.0, meaning that there is no changelog of 4.0 in the [Github releases](https://github.com/NEZNAMY/TAB/releases).

I tried checking if you maybe posted it on Discord, but I noticed that you completely locked it down for free users.
There is also no discussions tab on the repo, so I am opening this issue to ask you if you could please somehow provide the 4.0 changelog.

Cheers

### New text

/

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/releases/tag/4.0.1
Problem is that I don't remember every single change and don't want to go though the 200+ commits I made since then.

**Comment by Chris6ix** [comment]
Ah, thanks. 
No worries, I don't need every single minor bug fix, just wanted to know the main changes to see if there is breaking stuff, if there is a reconfig necessary etc. since it's a major update ;)

**Comment by NEZNAMY** [comment]
Yes, but [all config changes are automatically converted](https://github.com/NEZNAMY/TAB/wiki/Installation#updating-the-plugin).

**Comment by Chris6ix** [comment]
Awesome, thank you.
