### ISSUE TITLE
Weird symbols visible in tablist but not in config

### ISSUE THREAD

**Issue by RealmKebab** [NEZNAMY/TAB#947]
### Server version

Paper 1.19.4 (Velocity)

### TAB version

4.0.2

### Describe the bug

There's symbols visible in the tablist, but I never see it in the config. (I updated 3.2.2 to 4.0.2, first is 3.2.2 second is 4.0.2 "it seems similar because i didn't update shit about the config")
![image](https://github.com/NEZNAMY/TAB/assets/73048123/c2f568b9-1d01-46ee-96e3-52476ea3638a)
![image](https://github.com/NEZNAMY/TAB/assets/73048123/e5f18c25-c5a3-4c8a-99e3-7e4fd9c33193)

### Expected behavior

Not suppose to be symbols in there?

### Steps to reproduce

idek how this happened, it just happened

### Additional info

The entirety of the config.yml
3.2.2: https://mclo.gs/aMo9KOW
4.0.2: https://mclo.gs/pAsPEw1

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/8711c631-5c2b-4afc-8baf-e0df1805494b)
Your config works fine for me.

**Comment by RealmKebab** [comment]
yeah i'm unsure,
even if i make the domain name which i put as empty it still appears

**Comment by NEZNAMY** [comment]
Try resetting the config and start again. But again, providing steps to reproduce is your job. As long as you don't provide them, there is nothing I can do.

**Comment by RealmKebab** [comment]
how do i reset it

**Comment by RealmKebab** [comment]
still shows up

**Comment by NEZNAMY** [comment]
Try vanilla client, no resourcepacks etc.

**Comment by RealmKebab** [comment]
nothing works, ill just leave it as is
