### ISSUE TITLE
Groupmanager compatibility 

### ISSUE THREAD

**Issue by aSethyy** [NEZNAMY/TAB#948]
Would it be possible to add the permission plugin "GroupManager" to the list of permission plugins?
I know this enabled in older versions but servers still happen to use this as their main permission plugin.

**Comment by Tanguygab** [comment]
Install Vault

**Comment by aSethyy** [comment]
> Install Vault

Vault is installed

**Comment by aSethyy** [comment]
https://pastebin.com/ffq1X0Vh

**Comment by NEZNAMY** [comment]
And this is why you don't use 10 year old plugins. We cannot fix other plugins.

**Comment by NEZNAMY** [comment]
Great, then ask them to fix the error in their code, not us.
