### ISSUE TITLE
Cmi and vanish

### ISSUE THREAD

**Issue by DanRubMaster** [NEZNAMY/TAB#949]
### Server version

Spigot 1.19.1

### TAB version

4.0.2

### Describe the bug

Hi, I have been dealing with the problem regarding AFK for a long time. The problem I have is that I don't know how to get it to be visible in the tab once the player is afk, I've read a lot, I've done what I can, but for God's sake I can't figure out how to do it, I would have Placeholders it had, however it still doesn't work for some reason..

Here are the screenshots of how I did it and how it can be seen in the game (I use the cmi plugin), if you could advise me, I would be grateful.
![Desktop Screenshot 2023 06 27 - 20 40 35 57 (2)](https://github.com/NEZNAMY/TAB/assets/132781517/0536ce1b-1e37-4968-beae-f37eecc47a91)
![Badlion Client Screenshot 2023 06 27 - 19 40 05 31](https://github.com/NEZNAMY/TAB/assets/132781517/f2b9cdf3-5ea6-466d-b851-6e85df040015)

### Expected behavior

Display in tab afk, as it should.

### Steps to reproduce

Step 1: Make sure all Placeholders are correct, but i think they should be..
Step 2: Make sure cmi can do that
Step 3: Restart server and pray xd

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
> Step 1: Make sure all Placeholders are correct, but i think they should be..
CMI has his own AFK placeholder, you're not using it
Also, support is only given on the Discord server, issues are reserved for bug reports
