### ISSUE TITLE
Can we add World before Prefix

### ISSUE THREAD

**Issue by darrennrena** [NEZNAMY/TAB#95]
Im not sure if possible but id like to show where all players are in different worlds across my server in the TAB list before Prefix.

Thanks

**Comment by NEZNAMY** [comment]
Use %world% in prefix.

**Comment by darrennrena** [comment]
What setting?

**Comment by NEZNAMY** [comment]
tabprefix: "%world%"

**Comment by darrennrena** [comment]
Can you do this?
    tabprefix: '%world%-%rank% '

**Comment by NEZNAMY** [comment]
Yes you can, just try it... by the time you are waiting for a response you could have done it already.

**Comment by darrennrena** [comment]
Thanks and sorry, i understand where you are coming from but i cant
currently test as i am developing a new server so head deep in config
files. By the way love the plug in and appreciate the support.

**Comment by darrennrena** [comment]
Sorry to bother you man, but since your last update %world% doesnt work any
more has it changed?

**Comment by NEZNAMY** [comment]
Does the placeholder not replace correctly or how exactly does it not work ?

**Comment by darrennrena** [comment]
Just shows %world% where as before it showed the world name where the
player was its set up as "tabprefix: '%world% - %rank% '" and this worked
as we discussed but now it doesnt, it shows prefix just fine but not the
world

**Comment by darrennrena** [comment]
just for info i have reverted back to 2.6.1 and it works again

**Comment by NEZNAMY** [comment]
Try new build from discord.

**Comment by darrennrena** [comment]
Which channel?

**Comment by NEZNAMY** [comment]
#pre-release-versions. There's not that many channels.

**Comment by darrennrena** [comment]
I found it thanks and yes that works, thanks for the help
