### ISSUE TITLE
TAB not supported PlaceholderAPI.setRelationalPlaceholders() on animations

### ISSUE THREAD

**Issue by shiksyt** [NEZNAMY/TAB#950]
### Server version

PufferFish 1.20.1

### TAB version

4.0.2

### Stack trace

he is not

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That's intended behavior. Not even an error.

**Comment by NEZNAMY** [comment]
No, feature requests are permanently closed.
