### ISSUE TITLE
CustomScoreboards not refreshing

### ISSUE THREAD

**Issue by mehmet-27** [NEZNAMY/TAB#952]
### Server version

1.16.5

### TAB version

4.0.2

### Describe the bug

The placeholder values in the scoreboard that I show to the players using the `ScoreboardManager.showScoreboard(tabPlayer, scoreboard)` method are not updated. I guess the refresh method doesn't work for customscoreboards.

### Expected behavior

It should refresh placeholders in customscoreboards

### Steps to reproduce

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
I tested this just today and it worked. Are you sure you are passing in the raw identifiers and not already replaced values?

**Comment by mehmet-27** [comment]
> I tested this just today and it worked. Are you sure you are passing in the raw identifiers and not already replaced values?

i did check my placeholders updating but not affecting to scoreboard.

**Comment by NEZNAMY** [comment]
What updating? You didn't show any example code at all.

**Comment by mehmet-27** [comment]
> What updating? You didn't show any example code at all.

i am using placeholders from PlaceholderAPI

**Comment by mehmet-27** [comment]
when i re use ScoreboardManager.showScoreboard(tabPlayer, scoreboard) method its showing scoreboard with updated placeholders

**Comment by Tanguygab** [comment]
send your code

**Comment by mehmet-27** [comment]
sorry the problem is from my project. A method in the project could not update the tab because it set the placeholders before the tab.

**Comment by NEZNAMY** [comment]
That's exactly what I asked first.
