### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by liexes** [NEZNAMY/TAB#953]
Is there any possibility to show the players every certain number of blocks? Example, that if a player is 100 blocks from another, they cannot see if they are connected in the tab due to the distance, that is, that the same player can be seen, but the other cannot be seen in the tab. Something like a tab range, to be able to see the players in the tab every certain range of blocks.

I hope and help me, thank you.

**Comment by NEZNAMY** [comment]
No, TAB does not have such feature.

**Comment by liexes** [comment]
And there is no other plugin with which I can do it? Could this feature be added please?

**Comment by NEZNAMY** [comment]
I don't know what other plugins do and I do not accept any feature requests anymore.

**Comment by liexes** [comment]
Ok, sorry, I have an error with the plugin and it is that the ranks are bugged, I have them configured so that they align by ranks and when there are 10 people everything is messed up, the ranks do not align correctly.

**Comment by liexes** [comment]
> Ok, sorry, I have an error with the plugin and it is that the ranks are bugged, I have them configured so that they align by ranks and when there are 10 people everything is messed up, the ranks do not align correctly.

@NEZNAMY

**Comment by NEZNAMY** [comment]
You not configuring sorting is not a bug.

**Comment by liexes** [comment]
> You not configuring sorting is not a bug.

I am telling you that I already configured it my dear :)

**Comment by NEZNAMY** [comment]
Alright, you will get a chance. Explain your issue, send configs, screenshots etc.

**Comment by liexes** [comment]
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ""
  - "    &3♦ &f&kILS&r &b&lDRABY NETWORK &f&kILS&r &3♦    "
  - "    &fServidor: &bArenaPvP    "
  - ""
  footer:
  - ""
  - "      &6&lTienda&f&l: %animation:tienda%    "
  - "        &9&lDiscord&f&l: %animation:discord%    "
  - ""
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-condition: '%world%=arenas'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:dueño,admin,mod,ayudante,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=arenas'
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
yellow-number-in-tablist:
  enabled: false
  value: '%ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: true
primary-group-finding-list:
- Dueño
- Admin
- admin
- Mod
- mod
- Ayudante
- ayudante
- Builder
- builder
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true

**Comment by NEZNAMY** [comment]
Seriously? You paste the config into the message? How about the rest of my questions?

**Comment by Tanguygab** [comment]
Can you paste it on a website like https://paste.helpch.at/ ?
Also send the output of /tab debug <player not sorted> and a screen of the tablist

**Comment by liexes** [comment]
https://paste.helpch.at/igibiqoviz.yaml

Please, one moment, becouse dont have users in this moment on my server, get my 1 minute please.

**Comment by liexes** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/121281203/cf58fdf5-1d08-4d1d-931e-1ec8e47bb9da)
![image](https://github.com/NEZNAMY/TAB/assets/121281203/e11fa726-6022-40c7-9a40-d57b1f222190)

**Comment by liexes** [comment]
Te second image is the command /tab debug

**Comment by NEZNAMY** [comment]
Why did you enable assigning groups by permissions if you didn't give any permissions?

**Comment by liexes** [comment]
> Why did you enable assigning groups by permissions if you didn't give any permissions?

Need turn off this option?

**Comment by NEZNAMY** [comment]
Yes, if you want groups taken from permission plugin.

**Comment by liexes** [comment]
> Yes, if you want groups taken from permission plugin.

And that's how it's fixed?

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups
For some unknown reason you went for option 2, but did nothing else besides enabling it. You didn't configure it.

**Comment by liexes** [comment]
> https://github.com/NEZNAMY/TAB/wiki/How-to-assign-players-into-groups For some unknown reason you went for option 2, but did nothing else besides enabling it. You didn't configure it.

I already fixed it by deactivating that option, but I have a much bigger problem and that is that I have the per world tab activated, when I am in another world or I tp to another, I keep seeing the players from other worlds. And it's not because I have the bypass permission, this happens to all users

**Comment by NEZNAMY** [comment]
So you're now going to ask every possible question and pretend like it's all a bug report?

**Comment by liexes** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/121281203/a4763492-8cb4-45b1-8175-a491f8cbb180)

**Comment by liexes** [comment]
> So you're now going to ask every possible question and pretend like it's all a bug report?
> Every time this is reported, it's caused by another plugin. Try removing other plugins.

I have a plugin that only gives colors to the users, in the tab, it's a pvp plugin, but as you can see in the photo, the user Klixhy is in another world and I keep seeing him, please stop being so arrogant, I'm just Asking for help as a normal user, is it so difficult?

**Comment by NEZNAMY** [comment]
Such a random screenshot won't do anything. Try without other plugins.

**Comment by NEZNAMY** [comment]
Yes, it is a problem, customer support it paid and you are masking it as a bug report to get it for free, just like 90% of users here.

**Comment by liexes** [comment]
> Such a random screenshot won't do anything. Try without other plugins.

The plugin only gives colors to the names, I already talked to the owner and he says that the problem is with the tab, so that he could give it the colors I had to disable the custom nametags in that world, so the plugin is not interfering with that part, I also don't have another plugin that handles or manages something from the tab

**Comment by liexes** [comment]
> Such a random screenshot won't do anything. Try without other plugins.

I can film a video

**Comment by NEZNAMY** [comment]
Remove all other plugins (maybe except multiworld plugin) and try again.

**Comment by liexes** [comment]
> Yes, it is a problem, customer support it paid and you are masking it as a bug report to get it for free, just like 90% of users here.

So you only support your premium users? what kind of pay to win plugin is this? If all plugins support their users regardless if they are premium or not

**Comment by liexes** [comment]
> Remove all other plugins (maybe except multiworld plugin) and try again.

Don't you think I already did that?

**Comment by NEZNAMY** [comment]
So you're telling me if I get a cracked plugin the original author will help me with anything?

**Comment by liexes** [comment]
> So you're telling me if I get a cracked plugin the original author will help me with anything?

I don't use the cracked plugin friend, I use the free one, maybe you don't understand me because I use a translator, but I never said that I had a cracked plugin

**Comment by NEZNAMY** [comment]
You said paid plugins give free support to everyone. So if I don't buy it but use a cracked version, I will still get free support?

**Comment by liexes** [comment]
> You said paid plugins give free support to everyone. So if I don't buy it but use a cracked version, I will still get free support?

I mean plugins that have 2 versions, paid and free, like yours

**Comment by NEZNAMY** [comment]
It's my decision to ask users to fund all the time I wasted on the plugin. If you don't like it, you're free to go elsewhere.

**Comment by liexes** [comment]
In the end, are you going to help me or not?

**Comment by NEZNAMY** [comment]
Help? No. Fix a properly reported bug? Yes.

**Comment by liexes** [comment]
> Help? No. Fix a properly reported bug? Yes.

Thx for your help :/
