### ISSUE TITLE
%online% and %staffonline% and %server_uptime% dont working

### ISSUE THREAD

**Issue by herrlamatv** [NEZNAMY/TAB#954]
### Server version

1.20.1

### TAB version

4.0.2

### Describe the bug

I join a a admin on the server, but it says, that 0 players are online and 0 staff
There thands just %server_uptime%

### Expected behavior

acctually the plugin is supposed to say how many staff and player are online
there is supposed to stand how long the server is online

### Steps to reproduce

i think there needs a place holder, but i always have PlaceholderAPI-2.11.3 (1).jar on the server...

### Additional info

![Screenshot 2023-07-02 020623](https://github.com/NEZNAMY/TAB/assets/114185806/07dc1019-5361-4b79-a692-3897322fbabe)
![Screenshot 2023-07-02 020513](https://github.com/NEZNAMY/TAB/assets/114185806/c5e86896-8333-4e8e-ab56-44a56b6b830a)
![Screenshot 2023-07-02 020353](https://github.com/NEZNAMY/TAB/assets/114185806/b641c50a-9dc4-4595-8739-07bf0c9a208b)
![Screenshot 2023-07-02 020205](https://github.com/NEZNAMY/TAB/assets/114185806/a9e420c2-22a1-4ebe-957d-1c57b284f956)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by DrWurzeli** [comment]
![javaw_SQopJDaZ7m](https://github.com/NEZNAMY/TAB/assets/54333442/c90da20c-252f-46cd-8552-2a3bf4d317e1)
works as expected on latest paper with fresh install of TAB and placeholderAPI. closing as "plugin works as expected" as support for individual configuration is not provided on GitHub but only on discord for people with a support licence.
