### ISSUE TITLE
TAG hex color problem

### ISSUE THREAD

**Issue by shaqupl** [NEZNAMY/TAB#957]
### Server version

1.20.1

### TAB version

4.0.2

### Describe the bug

Hi, I wanted to create HEX color group prefix along with HEX color tag. This is what I get:
![image](https://github.com/NEZNAMY/TAB/assets/68109218/6e461f64-5f28-4a87-8bc7-dca80313b076)
In [TAB] both rank and nickname is hex color.

In game rank name is HEX color but nick turns into simliar minecraft color node.
![image](https://github.com/NEZNAMY/TAB/assets/68109218/8320c144-07c7-437b-adad-b36908a8a9f4)

### Expected behavior

Prefix and nickname should be in HEX colors

### Steps to reproduce

.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Nametags#limitations
