### ISSUE TITLE
Nametag doesn't work

### ISSUE THREAD

**Issue by EmnichtdaYT** [NEZNAMY/TAB#96]
**Server version**
1.14.4 Paper

**Plugin version** ("latest" is not a version)
2.6.3

**Describe the bug**
Ok, I have setted up my config like this:
Groups:
  #any other group not defined above
  _OTHER_:
    tabprefix: '%vault-prefix% '
    tagprefix: '%vault-prefix% '
    tabsuffix: '%afk%'
    tagsuffix: '%afk%'
    customtabname: '%essentialsnick%'
    customtagname: 'test'
But it never says test above the player. I have disabled every other plugin but it still doesnt work.
I don't have set up any User at the User tab

**How to reproduce**
Well I don't know. Maybe install Paper 1.14.4 and do the same as I did

**Expected behavior**
Well it should say test above the Player

**Actual behavior**
It shows the Username

**Additional info** (errors, screenshots, ...)
![grafik](https://user-images.githubusercontent.com/55759123/72683251-fd47af00-3ad5-11ea-819d-6fc55d8085bb.png)

**Comment by NEZNAMY** [comment]
"extra ones which need unlimited nametag mode enabled: customtagname"
Did you enable it ?

**Comment by EmnichtdaYT** [comment]
omg I am an idiot. Thank you so much. Your plugin is great! Gonna donate you something for your quick response! Thx!
