### ISSUE TITLE
Health Indikator

### ISSUE THREAD

**Issue by VladSlot** [NEZNAMY/TAB#960]
### Server version

1.18.2

### TAB version

3.3.2

### Describe the bug

Good evening,

I have encountered an issue with displaying health indicators above NPCs while using the TAB plugin. I have already researched this problem on various forums and attempted to solve it, but unfortunately, I have been unsuccessful so far. Although I managed to remove the health indicators initially, they reappear upon server restart.

I am reaching out to you in the hope that you can assist me in resolving this matter. Specifically, I need guidance on how to permanently remove the health indicator above NPCs.

Thank you in advance for your support.

### Expected behavior

The plugin should completely disable the display of health

### Steps to reproduce

idk

### Additional info

![image](https://github.com/NEZNAMY/TAB/assets/138400854/698d1c6b-5296-4258-b9ba-9cd019697685)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
If you believe TAB is causing it despite disabling belowname in config, try removing the plugin entirely. Also 3.3.2 is not latest.

**Comment by VladSlot** [comment]
Thanks for the quick response!

I think the problem is with the plugin, but I can't figure out why.  I've really already tried everything. How can I install the latest version of the plugin?

**Comment by VladSlot** [comment]
I found a new version of the plugin. Now I will try to see if it works. I am a new user on github and for me it is not all clear, it is difficult to find the necessary information, etc.

**Comment by VladSlot** [comment]
I solved the problem with this command.
/scoreboard objectives setdisplay belowname
For as long as it creates an extra health display for the NPC. I could not disable it in TAB config. If people come up with the same problem, you can advise them to do this. Thanks again!

**Comment by NEZNAMY** [comment]
That's where I was heading. This means another plugin added it, not TAB.
