### ISSUE TITLE
How to put the AFK back

### ISSUE THREAD

**Issue by Z3r0xh** [NEZNAMY/TAB#961]
### Server version

1.20.1

### TAB version

4.0.2

### Describe the bug

I have seen that you removed it from version 4.0.0 but I would like it to come back again, how could I put it back? Or if you could add it back to the plugin.

Please don't close my ticket without answering me, it's something I really liked.

### Expected behavior

idk

### Steps to reproduce

idk

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
%essentials_afk%
