### ISSUE TITLE
Tab color issue

### ISSUE THREAD

**Issue by FoxtrayStudio** [NEZNAMY/TAB#963]
### Server version

Spigot 1.8.8

### TAB version

4.0.2

### Describe the bug

When a player that is playing with 1.19+ / 1.20 (using viaversion) leave my server and reconnect, his scoreboard is completly buggy, the footer is merged with the header and the color are buggy.

This my initial scoreboard :
![99d3d8d93728b552eaf30e007edfdc60](https://github.com/NEZNAMY/TAB/assets/90271699/181da1fc-07c0-4483-b487-6d467dd42a0e)

And this is what we can while disconnecting and reconnecting :
![fdeb2246ce32ff69d54e561a4c37571e](https://github.com/NEZNAMY/TAB/assets/90271699/9ef5cd68-be44-4732-a21c-4696eba5758c)

### Expected behavior

.

### Steps to reproduce

Play on an 1.8 spigot with viaversion, use 1.19 or 1.20, connect on the server.

### Additional info

The /tab reload command put the good scoreboard back.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
try https://github.com/NEZNAMY/TAB/suites/14061650876/artifacts/785766198
