### ISSUE TITLE
I cant use command /tab

### ISSUE THREAD

**Issue by GOOLDOVE** [NEZNAMY/TAB#964]
### Server version

Mohist 1.16.5

### TAB version

4.0.2

### Describe the bug

successful loaded but cant use
![image](https://github.com/NEZNAMY/TAB/assets/81006632/6d0a9610-9142-4870-93b9-6b2f3b00134b)

### Expected behavior

success load
![image](https://github.com/NEZNAMY/TAB/assets/81006632/e5bcccce-5552-4cb2-84fd-818fbd75e526)

### Steps to reproduce

1.start server

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Clearly it didn't successfully load if it's disabled. You didn't send the startup error.
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d901b03f-f0fe-4d4c-9df4-a874732e5585)
