### ISSUE TITLE
error in console spam

### ISSUE THREAD

**Issue by Heissenz** [NEZNAMY/TAB#966]
### Server version

purpur 1.19.4

### TAB version

4.0.2

### Stack trace

https://pastebin.com/Zva1KViu

### Steps to reproduce (if known)

appeared from nowhere

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Extraflags plugin is trying to use 2 years old API. I will not revert it due to one abandoned plugin.
