### ISSUE TITLE
placeholder-output-replacements not working properly with %tps%

### ISSUE THREAD

**Issue by LiWinDom** [NEZNAMY/TAB#967]
### Server version

Spigot 1.16, 1.19, 1.20.1

### TAB version

4.0.2

### Describe the bug

When `%tps%` is not a fraction number, everything works nice
![изображение](https://github.com/NEZNAMY/TAB/assets/19565137/ac7c8c04-3fe3-4302-b55a-e6a478f85a32)
But when `%tps%` is a fraction number, placeholder replacements for number intervals stops working (TPS value isn't colored)
![изображение](https://github.com/NEZNAMY/TAB/assets/19565137/81a51e7b-b55b-4692-9e1d-5f7c466a0c18)

### Expected behavior

Working `placeholder-output-replacements` for %tps%

### Steps to reproduce

Set configuration like this:
```yml
placeholder-output-replacements:
  '%tps%':
    20-21: §2%value%
    19-19.99: §a%value%
    15-18.99: §e%value%
    10-14.99: §6%value%
    0-9.99: §4%value%
```

or from [wiki page](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements):
```yml
placeholder-output-replacements:
  "%tps%":
    "15-20": "Solid"
    "5-15": "Bad"
    "0-5": "Terrible"
```

### Additional info

In this example for every fraction number I got `%tps% (Terrible)`
```yml
placeholder-output-replacements:
  "%tps%":
    "20": "Running at perfect 20 TPS!"
    "15-20": "%tps% (Solid)"
    "5-15": "%tps% (Bad)"
    "else": "%tps% (Terrible)"
```
![изображение](https://github.com/NEZNAMY/TAB/assets/19565137/d342b8d2-2519-407c-8e44-bf95397d0035)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
What is the symbol displayed to separate decimals? Is it `,` or `.`?

**Comment by LiWinDom** [comment]
`,`

**Comment by NEZNAMY** [comment]
The plugin is coded to use `.` symbol. Any idea why is it different for you? Could it be caused by language set in your machine?

**Comment by LiWinDom** [comment]
I changed language in Minecraft and nothing changed
Maybe regional settings on server?...

**Comment by LiWinDom** [comment]
I changed regional setting on server, but nothing changed
I also changed regional setting on client, but again nothing changed (I don't thing it's client problem)
