### ISSUE TITLE
idk if its this plugin or placeholder api that isnt working or smt but the screenshot will tell everything

### ISSUE THREAD

**Issue by 4kKoZ** [NEZNAMY/TAB#968]
### Server version

paper 1.20.1

### TAB version

4.0.2

### Describe the bug

<img width="598" alt="Screenshot 2023-07-07 at 4 59 09 PM" src="https://github.com/NEZNAMY/TAB/assets/136613764/85146996-0ffc-4879-a362-9997ad6ca97b">

### Expected behavior

its supposed to show numbers and not the % % thing

### Steps to reproduce

no steps

### Additional info

<img width="814" alt="Screenshot 2023-07-07 at 5 16 34 PM" src="https://github.com/NEZNAMY/TAB/assets/136613764/ef814a67-3570-430d-aeb1-2b7796db2163">

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
`/papi parse me %statistic_player_kills%`

**Comment by 4kKoZ** [comment]
> `/papi parse me %statistic_player_kills%`

not working

**Comment by NEZNAMY** [comment]
Then it's not a TAB issue.
