### ISSUE TITLE
Developer API

### ISSUE THREAD

**Issue by oscarPLL** [NEZNAMY/TAB#97]
Hello, perhaps could you make a Developer API since most of the stuff in Developer API section are deprecated. I was thinking if you perhaps made it so let's say you can call `instanceOfAPI.setNameTag(player, "&c&lSome very long name tag for " + p.getName() + " yay :)");`
`instanceOfAPI.setNameTagAbove(player, "&c&lSome cool text above the name");`

**Comment by NEZNAMY** [comment]
Methods are deprecated as they were replaced by new more universal methods listed on wiki.
For the first one, use combination of prefix, name and suffix.
For second, call TABAPI.setValueTemporarily(uuid, EnumProperty.ABOVENAME, "abovename text")
