### ISSUE TITLE
Console Spam TAB Warning Messages

### ISSUE THREAD

**Issue by DJGamer98765** [NEZNAMY/TAB#972]
### Server version

PaperSpigot 1.20.1

### TAB version

4.0.3

### Stack trace

[https://pastebin.com/XrdbTE9N](url)

### Steps to reproduce (if known)

Any time a player joins the server, these messages start to occur.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Do one of the following:
* Update player expansion using `/papi ecloud download player` and `/papi reload`
* Don't use `%player_ping%`, because your version of player expansion doesn't support 1.20 and use `%ping%` instead.
