### ISSUE TITLE
Stuck on connecting to the server

### ISSUE THREAD

**Issue by T4B999** [NEZNAMY/TAB#973]
### Server version

 git-Purpur-2014 (MC: 1.20.1)*

### TAB version

4.0.3

### Describe the bug

When players attempt to join the server after installing the Tab plugin, enabling the scoreboard, and using the Flamecord proxy, they become stuck on the "Connecting to the server" screen. Eventually, they time out and are unable to join the server successfully. (tab plugin running on my backend server not proxy)

### Expected behavior

disabling the scoreboard and reloading the Tablist plugin should resolve the issue. Players should be able to join the server without experiencing any connection problems.

### Steps to reproduce

Install the Tab plugin in the backend and Flamecord for proxy.
Enable the scoreboard feature in the tab configuration.
 join the server.  disconnect from the server and wait a few minutes then rejoin)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=HPln9_waFcY). Tried to reconnect after a few minutes as well, still works.

**Comment by T4B999** [comment]
we just fixed it thanks.

**Comment by NEZNAMY** [comment]
How? Make a pull request if you fixed this TAB bug.

**Comment by T4B999** [comment]
> How? Make a pull request if you fixed this TAB bug.

not an issue with the tab plugin, the issue is from my proxy's wrong configuration.

**Comment by NEZNAMY** [comment]
Why opening an issue here then?

**Comment by T4B999** [comment]
im sorry about that I thought the issue is from your tab plugin scoreboard
