### ISSUE TITLE
Using NameTagManager sets 2 armor stands above player's name

### ISSUE THREAD

**Issue by itspinger** [NEZNAMY/TAB#974]
### Server version

1.20.1

### TAB version

4.0.3

### Describe the bug

When using NameTagManager with TabAPI#getNameTagManager when setting custom prefixes, two armor stands are shown in instead of just one.

![Bug](https://github.com/NEZNAMY/TAB/assets/29760085/49e0f44f-5438-4733-99ce-3bc73dff5da4)

### Expected behavior

It's expected to only show the armor stand colored in blue in the screenshot above.

### Steps to reproduce

I wrote this method for setting the prefix of the player when they are disguised.

```java
@Override
public void setPrefix(Player player, Rank rank) {
        if (!this.vaultEnabled && !this.tabEnabled) {
            return;
        }

        if (this.chat != null) {
            this.chat.setPlayerPrefix(player, rank.getPrefix());
        }

        if (this.tab != null) {
            TabPlayer tp = this.tab.getPlayer(player.getUniqueId());

            if (tp == null || !tp.isLoaded()) {
                return;
            }

            // Check if the player isn't null and apply the name
            this.tab.getTabListFormatManager().setPrefix(tp, rank.getPrefix());
            this.tab.getNameTagManager().setPrefix(tp, rank.getPrefix());
        }
}
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send your config.

**Comment by itspinger** [comment]
config.yml: https://hastebin.skyra.pw/juyicuvefo.nestedtext
groups.yml: https://hastebin.skyra.pw/udikigekup.yaml

**Comment by NEZNAMY** [comment]
works for me using the code
```
            TabAPI tab = TabAPI.getInstance();
            me.neznamy.tab.api.TabPlayer tp = tab.getPlayer(e.getPlayer().getUniqueId());

            if (tp == null || !tp.isLoaded()) {
                return;
            }

            // Check if the player isn't null and apply the name
            tab.getTabListFormatManager().setPrefix(tp, "Prefix test ");
            tab.getNameTagManager().setPrefix(tp, "Prefix test ");
```
![image](https://github.com/NEZNAMY/TAB/assets/6338394/ba876cd8-0472-43f5-bbcb-6e0a290041c4)

**Comment by NEZNAMY** [comment]
What's the difference? I added a 1000ms delay to give the plugin enough time to load the player and it's all working fine.

**Comment by itspinger** [comment]
I don't know, but this issue was reported by a user when I updated the API to 4.0.0 and it didn't happen with prior versions for example 3.2.4

**Comment by NEZNAMY** [comment]
Are you sure the user was using config you sent?

**Comment by itspinger** [comment]
Yeah the screenshot is from my computer. 

This is what I use in 1.20 to update player skins and such, could it be that some of these packets cause issues with your plugins?
https://github.com/itspinger/DisguiseAPI/blob/master/v1.20/src/main/java/net/pinger/disguise/packet/v1_20/PacketProviderImpl.java

**Comment by NEZNAMY** [comment]
If you are changing player's name it makes sense, as teams are bound to player names, not entity ids/uuids.

**Comment by itspinger** [comment]
I change the name by changing the GameProfile property and sending the packets within #sendServerPackets method.
But like I said, this didn't happen with prior versions. What should I change in order to fix?

**Comment by itspinger** [comment]
Yeah so basically, the double armor stand happens when I use `tab.getNameTagManager();`
In previous versions, I used `tab.getTeamManager()` cause I'm guessing the NameTagManager replaced the TeamManager.
When I don't use the NameTagManager the name of the player still changes, but when I'm trying to set the prefix, that's when it breaks.

For example, I removed the last line in the setPrefix method above and this is the result

![](https://github.com/NEZNAMY/TAB/assets/29760085/96da5bf5-687d-402a-abb7-d68ef2c871a5)

```java
    @Override
    public void setPrefix(Player player, Rank rank) {
        if (!this.vaultEnabled && !this.tabEnabled) {
            return;
        }

        if (this.chat != null) {
            this.chat.setPlayerPrefix(player, rank.getPrefix());
        }

        if (this.tab != null) {
            TabPlayer tp = this.tab.getPlayer(player.getUniqueId());

            if (tp == null || !tp.isLoaded()) {
                return;
            }

            // Check if the player isn't null and apply the name
            this.tab.getTabListFormatManager().setPrefix(tp, rank.getPrefix());
            //this.tab.getNameTagManager().setPrefix(tp, rank.getPrefix());
        }
    }
```

**Comment by itspinger** [comment]
The thing is, when I try just set the prefix to a player without disguising in the nametag, it works fine.

**Comment by NEZNAMY** [comment]
I highly doubt this is double armor stand. I'm pretty sure it's the vanilla name appearing while it should be hidden. Try creating a new clean plugin and use the API there. If it works, try your plugin again and disable some code until you find out what exactly causes it. I still didn't receive valid steps to reproduce.

**Comment by itspinger** [comment]
Yeah I thinks it's the vanilla name, when I do `/tab nametag toggle`, the prefixed name disappears, while the white name still appears.

**Comment by NEZNAMY** [comment]
Now you'll need to find out why does it show up. The only reason I can think of is a plugin changing player name and therefore name-bound teams no longer work.

**Comment by itspinger** [comment]
It looks like refreshing the player to clients after disguising causes it.

```static void refreshPlayer(Player player, Plugin plugin) {
        // Skip this action
        // If the plugin is disabled
        // Otherwise an error will be thrown
        if (!plugin.isEnabled()) {
            return;
        }

        // Check if the version is at least 1.16
        // Which changed the way you can hide a player
        // Using "Player#hidePlayer(Plugin, Player)"
        // Instead of "Player#hidePlayer(Player)"
        final boolean version = MinecraftServer.atLeast("1.16");

        // Hide the player
        // To all other players
        for (Player other : Bukkit.getOnlinePlayers()) {
            if (other.equals(player)) {
                continue;
            }

            if (version) {
                other.hidePlayer(plugin, player);
            } else {
                other.hidePlayer(player);
            }
        }

        // Now loop once again
        // And show the player
        for (Player other : Bukkit.getOnlinePlayers()) {
            if (other.equals(player)) {
                continue;
            }

            if (version) {
                other.showPlayer(plugin, player);
            } else {
                other.showPlayer(player);
            }
        }
    }```

**Comment by NEZNAMY** [comment]
That doesn't make sense. So you want me to try hiding and showing the player?

**Comment by NEZNAMY** [comment]
So you **are** changing the name in profile? Either way, how can not setting prefix in the API make this issue not happen? Are you sure it wasn't just both of them on the same place, making you think you can only see one?

**Comment by itspinger** [comment]
Well the issue is in order for the skin of the player to change, I need to call hidePlayer and showPlayer provided by bukkit.
The method #hidePlayer(Player, Entity) in background calls ClientboundPlayerInfoRemovePacket and **ClientboundRemoveEntitiesPacket**).
When the second packet is not sent, the issue doesn't happen, but the skin of the player doesn't change. So I kinda hit a dead end again

**Comment by NEZNAMY** [comment]
But does player info update feature a different username?

**Comment by itspinger** [comment]
I mean yeah of course, the Player which has the name changed

**Comment by NEZNAMY** [comment]
So you **are** changing player names?

**Comment by itspinger** [comment]
Yes, since that is the only way for server to actually recognize a different username under that uuid. If you use #setDisplayName and #setPlayerList, you're not really changing the username.

**Comment by NEZNAMY** [comment]
Well then it makes sense. Teams are bound to player names, not entity ids/uuids. Changing name breaks everything name-bound. I already explained this at https://github.com/NEZNAMY/TAB/issues/974#issuecomment-1629524111

**Comment by itspinger** [comment]
You're saying I would have to hook into ProtocolLib to fix this?

**Comment by NEZNAMY** [comment]
You can manipulate packets without ProtocoLib as well. But yes, you'll need to go deeper if you don't want to break other plugins. This will break every nametag/team plugin, not just TAB.

**Comment by itspinger** [comment]
**Could you guide me a bit more on how I should achieve this?**

I wanted to go with _**not changing the name**_ approach, just using Player#setDisplayName, but the issue is that users can TAB out the names of online players, and without sending the needed packets, this won't change.

![image](https://github.com/NEZNAMY/TAB/assets/29760085/50079da3-ccd8-4f37-8e42-735a91e31bc1)

I really don't want to go and write my own version of TAB, since I always recommended your plugin above all others.
My **Disguise** plugins were compatible with it for over a year, and it's a bummer that it's not really working anymore.

I'm not asking you to rewrite your plugin to the way it was, but I would appreciate it if you could go in-depth with me in how I would achieve the behavior I described in the issue already, or if you know how I can fix the issue in the image instead.

**Comment by NEZNAMY** [comment]
What exactly do you want to be added into TAB? How is it supposed to know player's name changed? How would it work with TAB on BungeeCord for example?

**Comment by itspinger** [comment]
Well, let's suppose that no nick plugins are changing player uuid's, since that should be forbidden to do in the first place, as it breaks almost any Minecraft plugin.

Note that I either use "**%dp_name%**" (custom placeholder) or "**%player_name%**" placeholder for displaying player names in TAB.

I am considering two approaches:

1. **Stop using GameProfile to change player name**:
 \- With this, I will not be changing the name of the actual player, but rather just changing a value in my plugin which will change the placeholder value
 \- I can use #setDisplayName and #setPlayerListName to ensure that the player's name changes in chat ([Although I did run into an issue when using #setDisplayName without changing the GameProfile](https://pastebin.com/rdUgMLXw)) <br>
My issue with this approach is that since I use no packets here, the clients will still recognize the player as their original name (https://imgur.com/1vCGiJT). This cannot be overridden by TabCompleteEvent, as this only covers cases where a command is supposed to be executed.

2. **Continue using GameProfile to change name, but fix duplicate names in Tablist (happens with Layout enabled) and Nametag**
 \- We already talked about the issue above, but I'm still not sure how I would go about and fix it, without breaking compatibility for other plugins as well
 \- I tried listening for Scoreboard packets and modifying them with **TinyProtocol**, but I got the same result
 \- With this approach it was easier to know when a player's name was changed, since the plugin itself would change the player name whenever the player changed servers

**Comment by NEZNAMY** [comment]
> Well, let's suppose that no nick plugins are changing player uuid's, since that should be forbidden to do in the first place, as it breaks almost any Minecraft plugin.

Tell that to authors who are actually doing it.

How should I detect this name change? Should I check for Player#getName periodically and see when it changes? Will that work with TAB on BungeeCord? Probably not. The second way is to listen to packets. However, this adds more room for problems and even packet reading is not available on all platforms.

**Comment by itspinger** [comment]
I suppose reading PacketPlayOutPlayerInfo (ADD_PLAYER) will do on Bukkit/Spigot/Paper platforms just fine, I'm not sure what about Sponge and Fabric.
I think Player#getName would also work on the same platforms but I'm not sure how that translates to BungeeCord, but even if it doesn't I think the information can be moved through Redis or Bungee Plugin Messaging.

**Comment by NEZNAMY** [comment]
I really don't feel like adding plugin messaging for this. Listening to the packet will only make it work on bukkit and bungeecord, which is most of the servers, but will it just be ignored on the rest?

**Comment by itspinger** [comment]
Yeah it will be ignored, but that's fine

**Comment by NEZNAMY** [comment]
For you. This is a public plugin, I should assume you are not the only one going to use it.

**Comment by itspinger** [comment]
No, of course, mine is a public plugin API as well, which other people use.

**Comment by itspinger** [comment]
Hey, I tried building the jar in order to test.
I ran the build from both the terminal and IDE and I got this:

https://hastebin.skyra.pw/oxomitonag.nestedtext
https://hastebin.skyra.pw/gujisagixa.bash

**Comment by Tanguygab** [comment]
download the build from the Actions tab

**Comment by itspinger** [comment]
Okay, so basically the issue is happening again (vanilla nametag is showing):
This was in the errors.yml: [errors.log](https://github.com/NEZNAMY/TAB/files/12139615/errors.log)

If you have discord or something where I can privately send you the plugin if you wish to accomplish this behavior yourself, do let me know.

**Comment by NEZNAMY** [comment]
That error message does not break anything. Is your plugin still not working? Enable debug in config, it sends a console message whenever a player name change is detected.

**Comment by itspinger** [comment]
Okay never mind, looks like it is indeed working!
I was using an old version of DisguiseAPI from when I was testing modifying team packets.

Thank you for updating, I appreciate it very much :D
