### ISSUE TITLE
 Taba heads

### ISSUE THREAD

**Issue by Spartan302** [NEZNAMY/TAB#975]
### Server version

1.20

### TAB version

1.20.1

### Evidence

I really need help, as few people know about this feature! How to make it so that when a player enters from a pirate, his heads are not displayed, and when the heads are displayed from a license! I saw a server that did this but I don't know if it uses your plugin but I don't know how to do it please help!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included sufficient evidence of the issue
- [ ] I ticked all of the boxes without actually reading them

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#8---how-to-make-player-heads-visible-in-tablist
How is this a performance issue?
