### ISSUE TITLE
TAB Plugin Configuration - Displaying Two Columns for Player Count Above 12

### ISSUE THREAD

**Issue by adnogpu** [NEZNAMY/TAB#977]
Hello, I have a question about using the TAB plugin. As shown in the screenshot, when the number of players on the server is equal to or greater than 21, the TAB display is in two columns. However, when the number of players is less than 20, it displays in a single column. Now, I would like the TAB plugin to display in two columns when the player count exceeds 12. I tried modifying the configuration file but it didn't work. Can you help me modify the configuration file? Thank you.
![image](https://github.com/NEZNAMY/TAB/assets/86664074/3c0ecabd-4375-4c4d-84d2-186c8ec76559)

**Comment by DrWurzeli** [comment]
Not possible and therefore not a TAB feature. Playerlist splits at 21, 41 and 61 online players. Mojang/Notch/someone over at Minecraft made it that way and there is nothing we can do about it.
You can enable layout to always show 80 slots. That is the closest thing we can do.
Cheers
