### ISSUE TITLE
%essentials_nickname% animated

### ISSUE THREAD

**Issue by ThatsSpryzen** [NEZNAMY/TAB#979]
![Immagine 2023-07-15 031923](https://github.com/NEZNAMY/TAB/assets/92258734/16f5ad14-3599-456c-b997-3761bf32b1a6) Like This but with every nickname with animation

Hello, i think this is not the right section to report this, (srry for bad english) i have a question about Animations. Can i make an animated placeholder? Like %essentials_nickname% (with HEX 1.20) animated with every name with https://www.simplymc.art/AnimTab/ and not with a single color. Thanks!

**Comment by Tanguygab** [comment]
You can't since TABs animations require all animation frames to manually be defined. Though you can use the Animations expansion for PAPI which does support placeholders inside of it
