### ISSUE TITLE
TAB doesn't work for 1.15.2

### ISSUE THREAD

**Issue by Syrkulous** [NEZNAMY/TAB#98]
**Server version**
1.15.2

**Plugin version** ("latest" is not a version)
2.6.3

**Describe the bug**
Despite 1.15.2 not changing much of anything to MC, TAB does not show/work
Names are kept white, no 

**How to reproduce**
update a server to 1.15.2

**Expected behavior**
Tab doesn't show

**Actual behavior**
Tab doesn't show

**Additional info** (errors, screenshots, ...)
Sorry, I made a bug report in the comments of the plugin, moved it here.

This is a suggestion info: Option to remove ping counts globally or in general.
-Doesn't look to great seeing a tab then pings spiking from -1 to 6000

**Comment by liscuate** [comment]
As the plug-in page says, 1.15.2 is not supported yet, it will be updated once there is time for it.

**Comment by Syrkulous** [comment]
I apologize, that's what I expected anyway.

I was just reporting in case it wasn't known.
Anyway, if you saw the additional info. If its possible please add, I'd appreciate it greatly.

**Comment by NEZNAMY** [comment]
You can set tablist objective to NONE to not display ping.

**Comment by DrWurzeli** [comment]
version 2.6.4 is out and you can now download it https://www.spigotmc.org/resources/tab-1-5-x-1-15-2-reborn.57806/updates

**Comment by Syrkulous** [comment]
Damn, still doesn't work

**Comment by NEZNAMY** [comment]
Show console log how it doesn't work.
