### ISSUE TITLE
Unable to use /tab nametag preview, even while unlimited-nametag-mode is enabled in config.

### ISSUE THREAD

**Issue by TheAlmightyGrand** [NEZNAMY/TAB#980]
### Server version

MC 1.20.1 - Fabric 0.14.21-1.20.1

### TAB version

4.0.3

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/91681083/6c6866c2-1955-4bb3-94ef-22b347e18737)
Unable to preview nametags, even with unlimited-nametag-mode enabled in config.
![image](https://github.com/NEZNAMY/TAB/assets/91681083/02c807dd-76ea-44c6-93df-4f7e6e9ae817)

### Expected behavior

From what I read in the wiki, this should allow me to preview abovename, belowname etc for my own character, used for testing and configurating the plugin

### Steps to reproduce

Step 1: Enable unlimited-nametag-mode
Step 2: Don't work

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
You may have forgotten to enable scoreboard-teams

**Comment by TheAlmightyGrand** [comment]
Unfortunately that's already enabled aswell :/
![image](https://github.com/NEZNAMY/TAB/assets/91681083/b0a50359-6ad1-4d82-a54b-6807a82cd1f1)

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/4e52c08a-cccb-4426-ae37-bab65e7b06c4)

**Comment by TheAlmightyGrand** [comment]
I must have completely missed that somewhere. Thanks for clearing that up so I don't spend more time wondering what I'm doing wrong
