### ISSUE TITLE
Compatibility problem causes the tab to not load in its latest version / Hybrid server 

### ISSUE THREAD

**Issue by MamohoReloaded** [NEZNAMY/TAB#981]
### Server version

Executions/1.0.5 / arclight-forge-1.19.4-1.0.5

### TAB version

4.0.3

### Describe the bug

at the time of starting the server everything loads correctly except the plugin tab It should be noted that I did not have any mods installed on the server, I only had plugins

### Expected behavior

To begin with, the plugin works and loads correctly until version 4.0.1 from then on, there is a compatibility error that causes the plugin to not load correctly and I would like to know if it is a problem of arclight or the plugin.

### Steps to reproduce

step 1: download arclight and run the server
step 2: Once the server has been started correctly and the eula accepted, download the plugin and place it in the corresponding folder, run the server and the plugin will not load correctly, giving a warning in the console about the compatibility problem and it will be automatically disabled

### Additional info

I leave you the arclight git that is required to recreate the error along with a list of the plugins I had at the time of the error
arclight:
https://github.com/IzzelAliz/Arclight
plugins:
![Screenshot_4](https://github.com/NEZNAMY/TAB/assets/115244034/684a8af0-b3c6-4648-99f8-ecfd65fb77f7)
mods: 
0

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Compatibility page doesn't say that software is supported. I tried launching it, it didn't even try to load up the plugin regardless of where I put it (plugins / mods).

**Comment by MamohoReloaded** [comment]
> Compatibility page doesn't say that software is supported. I tried launching it, it didn't even try to load up the plugin regardless of where I put it (plugins / mods).

It's strange, I'll stay at version 4.0.1, which works fine, and I'm going to report the problem, which I suppose is caused by Arclight.
