### ISSUE TITLE
looking for help

### ISSUE THREAD

**Issue by ElYucas** [NEZNAMY/TAB#982]
Hello.

I'm trying to configure the plugin as a fabric mod on a small server (just some friends and i), and i'd like to have the small groups we've made shown in tab and chat, but i haven't find a way to make it without a permission plugin. 

Does it exist? I believe these kind of permission stuff doesn't belong to a server this small, and would be great to configure your mod in a way without those.

Thank you for your time.

**Comment by Tanguygab** [comment]
Considering PlaceholderAPI doesn't have Fabric support, the only way would be to use the built-in %luckperms-prefix% which relies on LuckPerms, so, there isn't really any other way. It's not that difficult though, you can just make the groups in LuckPerms, give them prefixes and assign the groups to players without touching permissions and all and it'll work fine
