### ISSUE TITLE
Hexcode color doesn't work on tagnames above player

### ISSUE THREAD

**Issue by MusaMisto** [NEZNAMY/TAB#984]
### Server version

Paper 1.20.1

### TAB version

4.0.3

### Describe the bug

Regarding the tagname above the player, when using hex code the player name doesn't display the correct color but rather indicates a color that's the closest match to the vanilla counterpart of Minecraft color, ie. If I pick a particular shade of red/orange, it will display either &c color or &6 colors on the tag name above the player. The color works as expected in the tab name and tab in-game, however, the tag name doesn't apply the hex color as it should.

### Expected behavior

The tag name should be displaying the assigned hex code color by the user, thus both the tab name and tag name of the player should have the same hex color code assigned by the user rather than only the tab name of the player applying the designated hex code color whilst the tag name doesn't get the assigned hex code color as mentioned before.

### Steps to reproduce

Set hex code color through either luckperms or the config, join the game, and check the tab name color of the player and the tag name color of the player.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://github.com/NEZNAMY/TAB/wiki/Limitations

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/6670de3f-5a71-4106-a1da-92d37aa62fac)
