### ISSUE TITLE
[Velocity] Sorting randomly breaking after reconnecting

### ISSUE THREAD

**Issue by twisti-dev** [NEZNAMY/TAB#986]
### Server version

Velocity 3.2.0-SNAPSHOT (git-5ef90c46-b258)

### TAB version

4.0.4-SNAPSHOT

### Describe the bug

When the player joins the server for the first time (after the restart), the tab list is sorted correctly, but when the player reconnects, the tab list sorting breaks and everything is messed up. But when you go into spectator mode and look up the teams, they are set correctly as you can see in the debug mode but not sorted.
![sorted](https://github.com/NEZNAMY/TAB/assets/76837088/e2a66bc6-7bde-4270-8499-a3b4ac159e58)
![not sorted](https://github.com/NEZNAMY/TAB/assets/76837088/3e85f5d7-126f-4d9b-982c-73ccb8c45c84)
I have also tried the following sorting methods without success: PERMISSIONS, PLACEHOLDER_HIGH_TO_LOW, PLACEHOLDER_A_TO_Z

### Expected behavior

The tablist should be sorted correctly.

### Steps to reproduce

Step 1: TAB on the velocity proxy
Step 2: Install Tab-bridge on the backend servers
Step 3: Create Luckperms group with weight
Step 4: Use my config

### Additional info

I know Velocity is not production ready, but I thought I should report it anyway.

Here is my config: [Config](https://pastebin.com/awANMYEh)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Send startup log.

**Comment by twisti-dev** [comment]
https://pastebin.com/HPFQMT9x

**Comment by twisti-dev** [comment]
Oh and here is the error log if this helps https://pastebin.com/qLQanqwj

**Comment by NEZNAMY** [comment]
Check line 133 of the startup log you sent. The error log may explain it, which is another velocity-only issue and one of many reasons why velocity is not officially supported.

**Comment by NEZNAMY** [comment]
Reproduce on BungeeCord and provide working steps to reproduce if you want this fixed in the future.
