### ISSUE TITLE
AFk showing on name tags

### ISSUE THREAD

**Issue by RyanNuggyen** [NEZNAMY/TAB#988]
### Server version

Paper 1.19.4

### TAB version

4.0.3

### Describe the bug

https://gyazo.com/389b65e0fd6267bf7a088d8f2c5a5631

%afk% showing in tab

### Expected behavior

no %afk%

### Steps to reproduce

right out the box

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by RyanNuggyen** [comment]
the group.yml doesn't have any %afk%

**Comment by NEZNAMY** [comment]
Send groups.yml and output of `/tab debug <player>`.

**Comment by RyanNuggyen** [comment]
Owner:
  tabprefix: "&0[&x&E&F&0&B&0&B&lO&x&D&2&1&C&1&C&lw&x&B&4&2&7&2&7&ln&x&9&D&2&B&2&B&le&x&8&8&2&E&2&E&lr&0] &#F33B3B&l"
  tagprefix: "&0&l[&x&E&F&0&B&0&B&lO&x&D&2&1&C&1&C&lw&x&B&4&2&7&2&7&ln&x&9&D&2&B&2&B&le&x&8&8&2&E&2&E&lr&0&l] &#F33B3B&l"
Admin:
  tabprefix: "&0[&4&lAdmin&0] &4"
  tagprefix: "&4Admin &a"
Player:
  tabprefix: "&0[&7Player&0] &3"
  tagprefix: "&2Player &3"
example_group:
  header:
    - "This is an example of per-group header/footer"
  footer:
    - "applied to a group"

 # default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
_DEFAULT_:
  tabprefix: "%vault-prefix%"
  tagprefix: "%vault-prefix%"
  customtabname: "%essentials_nickname%"
  customtagname: "%essentials_nickname%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: "%vault-suffix%%afk%"
  tagsuffix: "%vault-suffix%%afk%"

per-world:
  world1:
    Owner:
      tabprefix: "&0&l[&a&lOwner&0&l] &a"
      tagprefix: "&2&lOwner &a"

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d5c035bd-9717-44b8-b415-67ac66927371)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/71e12219-7254-41ed-89c8-ef9c6e71a2f6)
???

**Comment by RyanNuggyen** [comment]
Sorry i used a feature in notepad++ to find afk didnt find it
