### ISSUE TITLE
Priority in TAB is not working as needed. 

### ISSUE THREAD

**Issue by TopStrixStudios** [NEZNAMY/TAB#989]
### Server version

1.19.4

### TAB version

4.0.4

### Describe the bug

Priority in TAB is not working as needed. 
Even though the sorting in /tab debug shows the correct # that the player should be sorted as, they users are still not being disguised correctly.
I use Hynick, which uses DisguiseAPI and when a user is nicked, the plugin sets the temporary group of the user.
However, the sorting is not working after being nicked.

when nicked: https://prnt.sc/TBIN_55tc_Uc
when not nicked: https://prnt.sc/7eN2igBChu2w

### Expected behavior

a

### Steps to reproduce

a

### Additional info

a

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/eb1c96fa-f72a-4065-a6ff-c3070cc11853)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/f3132105-5156-428a-9a89-3f0e3878f02b)
Disguise plugins usually change player's name, which breaks all name-bound features, including teams. Reproduce this issue without a plugin changing player names in gameprofile.
