### ISSUE TITLE
Important! Don't work TABAPI.removeTemporaryBelowName

### ISSUE THREAD

**Issue by car1ot** [NEZNAMY/TAB#99]
`
TABAPI.removeTemporaryBelowName(((Player) sender).getUniqueId());
 TABAPI.removeTemporaryBelowName(Bukkit.getOfflinePlayer(targetName).getUniqueId());`

I'm trying to remove temporary below name, wich I setted before with TABAPI. But **deletion don't work**.
Also I tried to log players ids. They are correct.

**Comment by NEZNAMY** [comment]
Also modifying tagprefix / tagsuffix is not working when unlimited nametag mode is enabled. Got this report too but didn't actually try it.

**Comment by car1ot** [comment]
Okay, the way to delete this is: TABAPI.setBelowNameTemporarily(targetPlayer.getUniqueId(), "");

**Comment by NEZNAMY** [comment]
Unable to reproduce. Likely fixed already.
