### ISSUE TITLE
PlaceholderAPI fail to display on scoreboard

### ISSUE THREAD

**Issue by Iehu** [NEZNAMY/TAB#991]
### Server version

1.20 Paper

### TAB version

4.0.3

### Describe the bug

Add %server_total_entities% placeholder in scoreboard.
When the server restart or when I rejoin, that placeholder doesn't get parsed.
When I do /tab reload, it DOES get parsed.
/papi reload doesn't solve the problem

### Expected behavior

%server_total_entities% get parsed correctly 

### Steps to reproduce

Step1: Setup paper server
Step2: Download papi server expansion
Step3:Put the %server_total_entities% in scoreboard

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
That placeholder must be refreshed synchronously, see wiki and error file you got in TAB folder.

**Comment by Iehu** [comment]
Man, are you even human? How could you be so good? Btw I am considering support your work, but it is extremely difficult to find a way to buy TAB premium. Is there any link you can give me?

**Comment by NEZNAMY** [comment]
No.
