### ISSUE TITLE
Added Support

### ISSUE THREAD

**Issue by Volc94** [NEZNAMY/TAB#994]
Please hear me out. I have seen your comments related to the excessive demand from users for very little in return and the decision not to include velocity support. I see no place to support the development of your plugin with donations though. Are you accepting donations? Patreon, paypal, or an hourly rate for new features? Looking forward to your reply.

**Comment by NEZNAMY** [comment]
No, I am no longer accepting donations anymore. The problem with velocity is that it can be very random at times, making it impossible to come with a systematic solution to some problems. Plus it's missing a lot of API.

**Comment by Volc94** [comment]
I'm sorry you've had to deal with all that headache. I can only imagine how frustrating it must be. It's very unfortunate to learn you're considering to drop continued support for this wonderful plugin. We've used it for over a year now and have never run into any issues with it whatsoever. Which is a testament to your ability to design a high quality plugin in both design and functionality. I do hope you reconsider, but I understand and respect your decision. I am more than willing to support the plugin long term through donations and actually useful bug reporting. Thank you for your time.
