### ISSUE TITLE
Suggestion to add resume nametag preview on join.

### ISSUE THREAD

**Issue by Chalityst** [NEZNAMY/TAB#995]
Sorry, I'm not good at english.

I'm not sure if I can suggest a new feature.
When player enabled nametag preview by command, disconnect and rejoin that will not reset to disable state.
If you interesting it's will be good feature. 

Thank you so much!

**Comment by Tanguygab** [comment]
preview is only for debug  purposes, it will annoy players more than anything since their nametag won't teleport instantly

**Comment by Chalityst** [comment]
Thank you so much for your response.
