### ISSUE TITLE
why?unexpected disabled

### ISSUE THREAD

**Issue by whohhnb** [NEZNAMY/TAB#996]
### Server version

Folia 1.20.1

### TAB version

4.0.3

### Stack trace

![image](https://github.com/NEZNAMY/TAB/assets/108384401/640f7a03-5c5f-4520-abb1-763088c19f6b)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by MrGraycat** [comment]
![f](https://github.com/NEZNAMY/TAB/assets/16325595/cc005795-f7bd-42ce-b416-e9c0e8887a15)

Not supported.

**Comment by NEZNAMY** [comment]
Actually folia is supported. I will check it out.

**Comment by MrGraycat** [comment]
> Actually folia is supported. I will check it out.

oh didn't see it on the compatibility page

**Comment by NEZNAMY** [comment]
Works on older build of folia.

Compiling latest fails with an error.

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/01dbd8ba-b5f5-42b0-8e27-c37f1f1f47c4)
Works on latest build of folia.

**Comment by whohhnb** [comment]
@NEZNAMY ok i got it

**Comment by NEZNAMY** [comment]
Got what?

**Comment by whohhnb** [comment]
It could be my problem
![image](https://github.com/NEZNAMY/TAB/assets/108384401/9e9c5e14-d777-4a52-9256-3867c2a5d7d9)

**Comment by whohhnb** [comment]
okay thank

**Comment by NEZNAMY** [comment]
I checked the entire commit history of Folia, commit "d610591" does not even exist. You are probably using a fork that breaks something or so.

**Comment by whohhnb** [comment]
I see

**Comment by whohhnb** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/108384401/df47b4b7-7628-42b1-ab70-c6f5a42b69df)
running the latest version,but
`[15:03:57 INFO]: [TAB] Enabling TAB v4.0.3
[15:03:57 INFO]: [TAB] Server version: 1.20.1 (v1_20_R1)
[15:03:57 INFO]: [TAB] A compatibility issue with your server was found. Unless you are running some really weird server software, this is a bug.`
![image](https://github.com/NEZNAMY/TAB/assets/108384401/c096d4e0-d79a-42df-8ae2-9c6a6112ed41)

what i to do

**Comment by whohhnb** [comment]
i need help!

**Comment by NEZNAMY** [comment]
You probably didn't run the second compilation command. Your current folia jar is mojang-mapped, which is not supported.

**Comment by whohhnb** [comment]
what can i do

**Comment by NEZNAMY** [comment]
You can properly compile folia or just don't use it if you don't know how. Once it's stable enough, they will release downloads publicly.

**Comment by whohhnb** [comment]
Alas, okay
