### ISSUE TITLE
Bossbar Triggers

### ISSUE THREAD

**Issue by StevenGoh-YH** [NEZNAMY/TAB#997]
Hi,

I'm working on a bossbar to only appear when there is an event trigger.

The configurations I have in place at the moment. It shows out nicely. but it stays there all the way until the "quests" is completed.

I was hoping to make it work in such a way that it will only appear when there is an update trigger to the '%quests_player_current_objectives_custom1%'.

May I know if the plugin currently supports this and I'm missing some syntax? Thank you!

bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: true
  hidden-by-default: false
  bars:
    Quest1:
      style: 'NOTCHED_20'
      color: 'GREEN'
      progress: '0'
      text: '%quests_player_current_objectives_custom1%'
      display-condition: '%quests_player_current_stage_number_custom1%=1'

**Comment by NEZNAMY** [comment]
You cannot detect change of the output, but you can compare it to the value when it should be hidden.
Triggers to placeholder changes will not be added.
