### ISSUE TITLE
%essentials_nickname% seems not to work with tab

### ISSUE THREAD

**Issue by xatake06** [NEZNAMY/TAB#998]
### Server version

Purpur 1.19.3

### TAB version

3.2.2

### Describe the bug

heres the part with the issue
  customtabname: '%essentials_nickname%'
  customtagname: '%essentials_nickname%'
nickname itself is fine, because its shown in the chat but not it the tab or as a tag for some reason.
am i missing something?

### Expected behavior

use essentials nickname as a nickname in the tab and above the head

### Steps to reproduce

paste 
  customtabname: '%essentials_nickname%'
  customtagname: '%essentials_nickname%'
in any group

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/ef11702d-8593-4bc1-a201-c270ee8f1512)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/0d2b6fc1-cf72-497d-b899-f01b18428fda)
![image](https://github.com/NEZNAMY/TAB/assets/6338394/68939f18-07b0-41a5-8aa0-f5c69c9d9a0d)
PlaceholderAPI is supported, there is no way such a bug would exist. You probably forgot to install it or essentials expansion.

**Comment by xatake06** [comment]
Why would you even need screenshots here? Everything is already explained. How could it be lack of PAPI or extension if this placeholder works with my chat plugin?

**Comment by Tanguygab** [comment]
send a screenshot of /papi list
and /papi parse me %essentials_nickname%

also update

**Comment by NEZNAMY** [comment]
Also /tab debug <player>

**Comment by Tanguygab** [comment]
you disabled tablist-name-formatting

**Comment by xatake06** [comment]
> you disabled tablist-name-formatting

thank you, sorry for taking this much time

**Comment by Tanguygab** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/45695833/899d2f87-a0fc-4ef3-9094-8846f0095a03)
check users.yml
