### ISSUE TITLE
Built-In AFK Placeholder Bug

### ISSUE THREAD

**Issue by Midnight9746** [NEZNAMY/TAB#999]
### Server version

Paper 1.19.4

### TAB version

4.0.3

### Describe the bug

After updating the TAB plugin to version 4.0.3, the built-in %afk% placeholder was no longer working. It did show Essential's version of the AFK placeholder, ([AFK] [Player]) at one point, but while trying to fix it, it remained as "%afk%".

### Expected behavior

That the built-in %afk% placeholder works 

### Steps to reproduce

Update from version 4.0.2 (last working %afk% placeholder) to version 4.0.3

### Additional info

I have it set up to show an animation instead of Essential's AFK message, where when the player is active, it shows a green icon slowly flashing between light and dark green, and the same thing in red when they're AFK.

Currently I had to do a work around fix, where I changed the placeholder to use the "%essentials_afk%" instead of %afk%. Since this was something I saw listed on the wiki as being built in and is now not working, (while also being something that worked on version 4.0.2), I am reporting it as a bug. 

Its a small minor bug that's easily fixable by server owners instead. Which if it ends up not being something added back in, server owners can just change the %afk% placeholder in the config.yml and groups.yml to %essentials_afk%, and follow the same format as %essentials_vanish%, (where it uses yes/no instead of true/false).

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
%afk% was removed in 4.0.0 and changelog says to use %essentials_afk% instead. I don't see any bug here.

**Comment by Midnight9746** [comment]
I must of had the version it was last in and didn't realize it got removed. My bad.

**Comment by ArcticRaven** [comment]
No, this might still be an issue. AFK is getting appended to player names where this functionality was not being used at all. even on a fresh TAB installation, with a fresh config, %AFK% is getting appended to player names. 
![image](https://github.com/NEZNAMY/TAB/assets/43667891/d7cea0d0-0527-4429-8994-223e321b11ec)
